(function(root){'use strict';const M=typeof Matter!=='undefined'?Matter:require('./matter.min.js'),{Engine,Bodies,Body,Composite,Constraint,Events,Vector}=M,clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const levels=[
{name:'First fall',mode:'clear',goal:.65,budget:3,builds:[[320,4,7,'brick']],hint:'Tap a low support. Then blast.'},
{name:'Glass house',mode:'clear',goal:.72,budget:3,builds:[[320,5,8,'glass']],hint:'Glass breaks easily. Start low.'},
{name:'A clean cut',mode:'clear',goal:.72,budget:3,builds:[[320,7,9,'steel']],hint:'The saw cuts through connected beams.'},
{name:'Small neighbour',mode:'protect',goal:.68,budget:3,builds:[[295,4,8,'brick']],house:395,hint:'Keep the little house safe. Aim left.'},
{name:'Special delivery',mode:'land',goal:1,budget:3,builds:[[290,3,8,'brick']],zone:[370,490],hint:'Drop the gold rooftop into the striped bay.'},
{name:'Twin trouble',mode:'clear',goal:.72,budget:3,builds:[[220,3,7,'brick'],[420,3,9,'glass']],hint:'Three charges. Two towers.'},
{name:'The overhang',mode:'clear',goal:.72,budget:3,builds:[[290,3,9,'steel']],overhang:true,hint:'One support holds a heavy roof.'},
{name:'Mind the garden',mode:'protect',goal:.75,budget:3,builds:[[355,5,9,'glass']],house:240,hint:'Pull away from the garden.'},
{name:'Rooftop express',mode:'land',goal:1,budget:3,builds:[[340,3,10,'steel']],zone:[165,285],hint:'Free the base. Pull the tower left.'},
{name:'Three little towers',mode:'clear',goal:.78,budget:3,builds:[[170,2,7,'brick'],[320,2,10,'glass'],[470,2,8,'brick']],hint:'One carefully placed charge per tower.'},
{name:'A narrow escape',mode:'protect',goal:.78,budget:3,builds:[[365,7,10,'steel']],house:215,hint:'Cut low. Send the pieces right.'},
{name:'The grand finale',mode:'clear',goal:.8,budget:3,builds:[[220,5,9,'brick'],[420,5,11,'glass']],bridge:true,hint:'A bridge links both towers. Find its weak points.'}
];
class Game{constructor(index=0,plan=[],unlocked=index){this.index=clamp(Math.floor(index),0,levels.length-1);this.level=levels[this.index];this.unlocked=Math.max(this.index,unlocked);this.phase='plan';this.t=0;this.events=[];this.nodes=[];this.joints=[];this.plan=[];this.progress=0;this.houseHP=100;this.chain=0;this.bestChain=0;this.lastBreak=-10;this.broken=0;this.settled=0;this.ropes=[];this.engine=Engine.create({enableSleeping:true,positionIterations:6,velocityIterations:5,constraintIterations:3});this.engine.gravity.y=1;this.engine.gravity.scale=.0012;Composite.add(this.engine.world,[Bodies.rectangle(320,588,1800,56,{isStatic:true,friction:.85,label:'ground'}),Bodies.rectangle(-190,320,40,1000,{isStatic:true}),Bodies.rectangle(830,320,40,1000,{isStatic:true})]);this.build();Events.on(this.engine,'collisionStart',e=>this.collisions(e));for(let p of plan.slice(0,this.level.budget))if(this.nodes.some(n=>n.id===p.id))this.plan.push({...p,tool:['blast','saw','pull'].includes(p.tool)?p.tool:'blast'});}
node(x,y,w,h,kind,id,extra={}){let b=Bodies.rectangle(x,y,w,h,{density:kind==='steel'?.0022:kind==='glass'?.0009:.0015,friction:.55,frictionStatic:.8,restitution:kind==='glass'?.12:.05,frictionAir:.005,sleepThreshold:50,chamfer:{radius:1}});let n={id,b,w,h,kind,x,y,health:kind==='glass'?22:kind==='steel'?110:55,removed:false,...extra};b.plugin.node=n;this.nodes.push(n);Composite.add(this.engine.world,b);return n}
joint(a,b,axis='v',anchor=false){let offsets=axis==='v'?[{x:-7,y:0},{x:7,y:0}]:[{x:0,y:-7},{x:0,y:7}];for(let o of offsets){let pa=axis==='v'?{x:o.x,y:a.h/2}:{x:a.w/2,y:o.y},pb=anchor?null:axis==='v'?{x:o.x,y:-b.h/2}:{x:-b.w/2,y:o.y};let con=anchor?Constraint.create({pointA:{x:a.x+o.x,y:560},bodyB:a.b,pointB:{x:o.x,y:a.h/2},length:1,stiffness:.85,damping:.12}):Constraint.create({bodyA:a.b,pointA:pa,bodyB:b.b,pointB:pb,length:.1,stiffness:.95,damping:.15});let j={con,a,b:anchor?null:b,limit:anchor?6:a.kind==='steel'&&b.kind==='steel'?10:6,anchor,protected:!!(a.parcel||b?.parcel),dead:false};this.joints.push(j);Composite.add(this.engine.world,con)}}
build(){let ci=0;for(let [cx,cols,rows,material]of this.level.builds){let grid=[];for(let row=0;row<rows;row++){grid[row]=[];for(let col=0;col<cols;col++){let x=cx+(col-(cols-1)/2)*32,y=543-row*34;let kind=material==='glass'?(col===0||col===cols-1||row===0?'steel':'glass'):material==='steel'?(col===0||col===cols-1||row%3===0?'steel':'glass'):(col===0||col===cols-1||row===0?'brick':row%2?'glass':'brick');let n=this.node(x,y,32,34,kind,`b${ci}r${row}c${col}`);grid[row][col]=n;if(row===0)this.joint(n,null,'v',true);if(col>0)this.joint(grid[row][col-1],n,'h');if(row>0)this.joint(n,grid[row-1][col],'v')}}let roof=this.node(cx,543-rows*34+9,cols*32+8,16,'steel',`roof${ci}`,{roof:true,health:1e9});for(let col=0;col<cols;col++){let top=grid[rows-1][col];let con=Constraint.create({bodyA:roof.b,pointA:{x:top.x-cx,y:8},bodyB:top.b,pointB:{x:0,y:-17},length:.1,stiffness:.95});this.joints.push({con,a:roof,b:top,limit:9,dead:false});Composite.add(this.engine.world,con)}if(this.level.mode==='land'){this.parcel=this.node(cx,roof.y-23,28,28,'gold','parcel',{parcel:true,health:1e9});this.joint(this.parcel,roof,'v')}if(this.level.overhang){let n=this.node(cx+48,roof.y-18,180,20,'steel','overhang');for(let xx of[-18,18]){let con=Constraint.create({bodyA:n.b,pointA:{x:xx-48,y:10},bodyB:roof.b,pointB:{x:xx,y:-8},length:.1,stiffness:.95});this.joints.push({con,a:n,b:roof,limit:10,dead:false});Composite.add(this.engine.world,con)}}ci++}if(this.level.bridge){let n=this.node(320,254,40,16,'steel','bridge');for(let [id,side]of[['b0r8c4',-1],['b1r8c0',1]]){let end=this.nodes.find(a=>a.id===id);for(let yy of[-5,5]){let con=Constraint.create({bodyA:n.b,pointA:{x:side*20,y:yy},bodyB:end.b,pointB:{x:-side*16,y:-17+yy},length:.1,stiffness:.95});this.joints.push({con,a:n,b:end,limit:7,dead:false});Composite.add(this.engine.world,con)}}}this.targets=this.nodes.filter(n=>!n.parcel);if(this.level.house){this.house=Bodies.rectangle(this.level.house,524,65,72,{isStatic:true,label:'house'});Composite.add(this.engine.world,this.house)}}
emit(type,extra={}){this.events.push({type,t:this.t,...extra})}nearest(x,y){let best=null,dist=65;for(let n of this.nodes){if(n.removed||n.parcel)continue;let d=Math.hypot(x-n.b.position.x,y-n.b.position.y);if(d<dist){dist=d;best=n}}return best}
place(x,y,tool='blast',dx=0,dy=0){if(this.phase!=='plan'||this.plan.length>=this.level.budget||!['blast','saw','pull'].includes(tool)||tool==='saw'&&this.unlocked<2||tool==='pull'&&this.unlocked<4)return false;let n=this.nearest(x,y);if(!n||this.plan.some(p=>p.id===n.id))return false;let len=Math.hypot(dx,dy);this.plan.push({id:n.id,x:n.x,y:n.y,tool,dx:len>20?dx/len:0,dy:len>20?dy/len:0});this.emit('place',{x:n.x,y:n.y});return true}undo(){if(this.phase==='plan')return this.plan.pop()}fire(){if(this.phase!=='plan'||!this.plan.length)return false;this.phase='run';this.t=0;this.emit('start');return true}
breakJoint(j){if(j.dead||j.protected)return;j.dead=true;Composite.remove(this.engine.world,j.con);for(let n of[j.a,j.b])if(n&&!n.removed)M.Sleeping.set(n.b,false)}
shatter(n){if(n.removed||n.parcel||n.roof)return;n.removed=true;for(let j of this.joints)if(j.a===n||j.b===n)this.breakJoint(j);Composite.remove(this.engine.world,n.b);if(this.t-this.lastBreak<.45)this.chain++;else this.chain=1;this.lastBreak=this.t;this.bestChain=Math.max(this.bestChain,this.chain);this.broken++;this.emit('break',{x:n.b.position.x,y:n.b.position.y,kind:n.kind,chain:this.chain});if(this.nodes.length<165&&n.kind!=='steel'){for(let i=0;i<2;i++){let b=this.node(n.b.position.x+(i?6:-6),n.b.position.y,9,11,n.kind,`chip${this.nodes.length}`,{chip:true,health:1e9});Body.setVelocity(b.b,{x:n.b.velocity.x+(i?1.5:-1.5),y:n.b.velocity.y-1.2});Body.setAngularVelocity(b.b,(i?.1:-.1))}}}
detonate(p){let source=this.nodes.find(n=>n.id===p.id),pos=source?.b.position||p,x=pos.x,y=pos.y;this.emit(p.tool,{x,y,dx:p.dx,dy:p.dy});let dir={x:p.dx||0,y:p.dy||0};if(p.tool==='pull'){let selected=source&&!source.removed?source:this.nearest(x,y);if(!selected)return;let rope=Constraint.create({bodyA:selected.b,pointB:{x:x+(dir.x||1)*140,y:y+dir.y*140},length:0,stiffness:.045,damping:.35});this.ropes.push({con:rope,until:this.t+2.5});Composite.add(this.engine.world,rope);M.Sleeping.set(selected.b,false);return}
for(let j of this.joints){if(j.dead)continue;let a=j.a.b.position,b=j.b?.b.position||{x:j.a.x,y:560},mx=(a.x+b.x)/2,my=(a.y+b.y)/2;let hit=p.tool==='saw'?Math.abs(my-y)<26&&Math.abs(mx-x)<115:Math.hypot(mx-x,my-y)<90;if(hit)this.breakJoint(j)}
for(let n of this.nodes.slice()){if(n.removed||n.chip)continue;let d=Math.hypot(n.b.position.x-x,n.b.position.y-y);if(p.tool==='saw'){if(Math.abs(n.b.position.y-y)<38&&Math.abs(n.b.position.x-x)<115&&!n.parcel&&!n.roof){this.shatter(n)}continue}if(d>135)continue;let f=1-d/135,ux=(n.b.position.x-x)/(d||1),uy=(n.b.position.y-y)/(d||1);M.Sleeping.set(n.b,false);n.health-=110*f;if(d<45&&!n.parcel&&!n.roof||n.health<=0)this.shatter(n);else{Body.applyForce(n.b,n.b.position,{x:(ux*.023+dir.x*.045)*f*n.b.mass,y:(uy*.023+dir.y*.045-.008)*f*n.b.mass});Body.setAngularVelocity(n.b,(n.b.position.x>=x?.025:-.025)*f)}}}
collisions(e){if(this.phase!=='run')return;for(let pair of e.pairs){let a=pair.bodyA,b=pair.bodyB;let av=a.velocity,bv=b.velocity,impact=Math.hypot(av.x-bv.x,av.y-bv.y);if(impact<2.6)continue;if(a===this.house||b===this.house){let other=a===this.house?b:a,n=other.plugin.node;if(n&&!n.chip&&this.t>.2){this.houseHP=clamp(this.houseHP-impact*2.2,0,100);this.emit('houseHit',{x:this.level.house,y:500})}}for(let body of[a,b]){let n=body.plugin.node;if(!n||n.removed||n.chip||n.parcel)continue;if(impact>(n.kind==='steel'?6.5:4.2))for(let j of this.joints)if(j.a===n||j.b===n)this.breakJoint(j);n.health-=impact*(n.kind==='glass'?5:3);if(n.health<=0)this.shatter(n)}if(impact>5)this.emit('impact',{x:(a.position.x+b.position.x)/2,y:Math.min(560,(a.position.y+b.position.y)/2),power:impact})}}
updateProgress(){let sum=0;for(let n of this.targets){let y=n.removed?560:n.b.position.y;sum+=clamp((y-n.y)/Math.max(38,510-n.y),0,1)}this.progress=sum/this.targets.length;let zone=this.level.zone,p=this.parcel;this.delivered=!!(zone&&p&&!p.removed&&p.b.position.x>=zone[0]&&p.b.position.x<=zone[1]&&p.b.position.y>490&&p.b.speed<2);this.valid=this.level.mode==='land'?this.delivered:this.progress>=this.level.goal;if(this.level.mode==='protect')this.valid=this.valid&&this.houseHP>=95}
finish(){if(this.phase!=='run')return;this.updateProgress();this.phase=this.valid?'win':'fail';this.medal=this.valid?this.plan.length===1?3:this.plan.length===2?2:1:0;if(this.valid&&this.level.mode==='protect'&&this.houseHP<90)this.medal=Math.min(this.medal,2);this.emit(this.phase,{medal:this.medal,progress:this.progress})}
step(dt=1/60){if(this.phase!=='run')return;this.t+=dt;for(let i=0;i<this.plan.length;i++){let p=this.plan[i];if(!p.fired&&this.t>=.25+i*.5){p.fired=true;this.detonate(p)}}for(let rope of this.ropes){if(!rope.dead&&this.t>rope.until){Composite.remove(this.engine.world,rope.con);rope.dead=true}}Engine.update(this.engine,dt*1000);for(let j of this.joints){if(j.dead)continue;let con=j.con,a=con.bodyA?Vector.add(con.bodyA.position,Vector.rotate(con.pointA,con.bodyA.angle-con.angleA)):con.pointA,b=con.bodyB?Vector.add(con.bodyB.position,Vector.rotate(con.pointB,con.bodyB.angle-con.angleB)):con.pointB;if(Math.hypot(a.x-b.x,a.y-b.y)>con.length+j.limit)this.breakJoint(j)}this.updateProgress();let moving=this.nodes.filter(n=>!n.removed&&!n.chip&&!n.b.isSleeping&&(n.b.speed>.9||Math.abs(n.b.angularVelocity)>.06)).length;this.settled=moving<3&&this.ropes.every(r=>r.dead)&&(!this.parcel||this.parcel.b.speed<.5)?this.settled+dt:0;if(this.t>3.2&&this.plan.every(p=>p.fired)&&this.settled>.9||this.t>=15)this.finish()}
dispose(){Events.off(this.engine);Composite.clear(this.engine.world,false);Engine.clear(this.engine)} }
root.Fallwork={Game,levels,M,clamp};if(typeof module!=='undefined')module.exports=root.Fallwork;})(typeof window!=='undefined'?window:globalThis);















