(()=>{'use strict';const $=id=>document.getElementById(id),KEY='tether-chime-v1';let profile={best:Array(8).fill(0),skin:0,sound:true},s=Chime.create(),paused=true,screen='intro',target=null,primary=null,reelIds=new Set(),keys={},fx=[],trail=[],acc=0,audio=null,voices=[],toastEnd=0;
try{const a=JSON.parse(localStorage.getItem(KEY));if(a){profile.best=Array.from({length:8},(_,i)=>Math.max(0,Math.min(3,a.best?.[i]|0)));profile.sound=a.sound!==false;profile.skin=[0,1,2].includes(a.skin)?a.skin:0;s=Chime.restore(a.state)||s}}catch{}
const total=()=>profile.best.reduce((a,b)=>a+b,0),allowed=i=>total()>=[0,6,15][i];if(!allowed(profile.skin))profile.skin=0;
function save(){try{localStorage.setItem(KEY,JSON.stringify({...profile,state:{...s,events:[]}}))}catch{}}
function hush(){for(const o of voices)try{o.stop()}catch{}voices=[]}
function wake(){if(!profile.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume()}catch{}}
function sound(freq,len=.55,volume=.045,type='sine'){if(paused||!profile.sound||!audio)return;try{while(voices.length>13){const old=voices.shift();try{old.stop()}catch{}}const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.001,audio.currentTime);g.gain.exponentialRampToValueAtTime(volume,audio.currentTime+.008);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+len);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+len);voices.push(o);o.onended=()=>{const i=voices.indexOf(o);if(i>=0)voices.splice(i,1)}}catch{}}
function bell(i){const notes=[523.25,587.33,659.25,783.99,880,1046.5,1174.66],f=notes[i%7]*([1,1,.89,1,.75,1,.89,1][s.level]);sound(f,1.05,.055);sound(f*2.76,.32,.013)}
function toast(t){$('toast').textContent=t;toastEnd=s.t+1.2}
function release(){target=null;primary=null;reelIds.clear();keys={}}
function resume(){paused=false;screen='play';release();$('overlay').hidden=true;wake();save()}
function start(n){s=Chime.create(n);fx=[];trail=[];resume();toast(Chime.stages[n].name)}
function mark(){profile.best[s.level]=Math.max(profile.best[s.level],s.rating);save()}
const hero='<svg viewBox="0 0 110 90" aria-hidden="true"><path d="M29 5Q13 50 64 58" fill="none" stroke="#baa080" stroke-width="2"/><ellipse cx="29" cy="6" rx="12" ry="5" fill="#dcc293"/><circle cx="67" cy="58" r="24" fill="#b87e60"/><circle cx="67" cy="54" r="23" fill="#dcaa86"/><circle cx="67" cy="54" r="17" fill="#f8e7c3"/><circle cx="67" cy="54" r="12" fill="#dcaa86"/><circle cx="67" cy="54" r="4" fill="#f8e7c3"/><path d="M16 60l2 5 5 1-5 2-2 5-2-5-5-2 5-1zM96 19l2 4 4 1-4 2-2 4-1-4-4-2 4-1z" fill="#d2aa6b"/></svg>';
function modal(kind){paused=true;screen=kind;release();hush();save();$('overlay').hidden=false;const p=$('panel');if(kind==='intro')p.innerHTML='<div class="eyebrow">A POCKET ORCHESTRA</div><div class="hero">'+hero+'</div><h1>Tether<br>& Chime</h1><p>Drag to swing. Ring every little bell.<br>Hold REEL to pull the yo-yo closer.</p><button class="primary" data-act="resume">'+(s.hits||s.t?'CONTINUE':'LET IT SWING')+'</button><button class="secondary" data-act="help">HOW TO PLAY</button><button class="secondary" data-act="book">COLLECTION</button>';
if(kind==='pause')p.innerHTML='<div class="eyebrow">A QUIET MOMENT</div><h2>'+Chime.stages[s.level].name+'</h2><p>The melody can wait.</p><button class="primary" data-act="resume">KEEP PLAYING</button><button class="secondary" data-act="help">HOW TO PLAY</button><button class="secondary" data-act="book">COLLECTION</button>';
if(kind==='restart')p.innerHTML='<div class="eyebrow">PLAY IT AGAIN?</div><h2>A fresh melody</h2><p>Restart this music box.<br>Your collection stays safe.</p><button class="primary" data-act="restart">START AGAIN</button><button class="secondary" data-act="resume">KEEP PLAYING</button>';
if(kind==='help')p.innerHTML='<div class="eyebrow">SMALL MOVES, LOVELY SWINGS</div><div class="hero">'+hero+'</div><div class="help">Drag anywhere to move the round hand grip. The yo-yo swings below it.<br><br>Brush the bells with a moving yo-yo. A dot means two hits: swing away, then back.<br><br>Hold REEL, or add a second finger, to shorten the string. Collect the three stars for a perfect melody.<br><br>Arrows / WASD move the grip. Space reels. Escape pauses.</div><button class="primary" data-act="back">GOT IT</button>';
if(kind==='book')p.innerHTML='<div class="eyebrow">THE LITTLE CHIME COMPANY</div><h2>Pocket melodies</h2><p>'+total()+' / 24 ★ · Mint at 6 · Lilac at 15</p><div class="grid">'+Chime.stages.map((y,i)=>'<button data-act="level" data-n="'+i+'" '+(i&&!profile.best[i-1]?'disabled':'')+' aria-label="'+y.name+'">'+(i+1)+'<small>'+'★'.repeat(profile.best[i])+'☆'.repeat(3-profile.best[i])+'</small></button>').join('')+'</div><div class="skins">'+['Peach','Mint','Lilac'].map((n,i)=>'<button data-act="skin" data-n="'+i+'" '+(!allowed(i)?'disabled':'')+'>'+n+(profile.skin===i?' ✓':'')+'</button>').join('')+'</div><button class="primary" data-act="back">BACK TO THE MUSIC</button>';
if(kind==='win')p.innerHTML='<div class="eyebrow">MUSIC BOX '+(s.level+1)+' / 8</div><h2>A lovely little melody.</h2><div class="stars">'+'★'.repeat(s.rating)+'☆'.repeat(3-s.rating)+'</div><p>'+s.bells.length+' bells lit · '+s.stars.filter(a=>a.found).length+' / 3 stars<br>'+(s.rating===3?'Every note found its home.':'Collect all three stars for a perfect melody.')+'</p><button class="primary" data-act="next">'+(s.level<7?'NEXT MUSIC BOX':'PLAY THE ENCORE')+'</button><button class="secondary" data-act="restart">PLAY AGAIN</button><button class="secondary" data-act="book">COLLECTION</button>';
}
$('panel').onclick=e=>{const b=e.target.closest('[data-act]');if(!b)return;wake();const n=+b.dataset.n;switch(b.dataset.act){case'resume':case'back':s.won?modal('win'):resume();break;case'restart':start(s.level);break;case'next':start((s.level+1)%8);break;case'level':if(!n||profile.best[n-1])start(n);break;case'book':modal('book');break;case'help':modal('help');break;case'skin':if(allowed(n)){profile.skin=n;save();modal('book')}break}};
$('book').onclick=()=>modal('book');$('pause').onclick=()=>paused?(s.won?modal('win'):resume()):modal('pause');$('retry').onclick=()=>modal('restart');$('sound').onclick=()=>{profile.sound=!profile.sound;if(profile.sound)wake();else hush();save()};$('finish').onclick=()=>{if(!paused&&Chime.finish(s))effects()};
$('reel').onpointerdown=e=>{e.preventDefault();if(paused||s.won)return;wake();reelIds.add(e.pointerId);$('reel').setPointerCapture(e.pointerId)};window.addEventListener('pointerup',e=>reelIds.delete(e.pointerId));window.addEventListener('pointercancel',e=>reelIds.delete(e.pointerId));
function burst(x,y,n,col){for(let i=0;i<n;i++)fx.push({kind:i%5===0?'note':'spark',x,y,vx:(Math.random()-.5)*145,vy:-40-Math.random()*115,life:.7+Math.random()*.5,col,size:2+Math.random()*3})}
function effects(){for(const e of s.events){if(e.type==='bell'){bell(e.i);burst(e.x,e.y,15,e.done?'#fff0b7':'#d9b688');fx.push({kind:'ring',x:e.x,y:e.y,vx:0,vy:0,r:12,life:.65,col:'#fff0bd'});if(e.combo>=3)toast('HARMONY ×'+e.combo);else if(!e.done)toast('One more little chime')}if(e.type==='star'){sound(1318.5,.7,.04);sound(1975.5,.35,.02);burst(e.x,e.y,25,'#fff2b6');toast('A little star!')}if(e.type==='bump'){sound(180,.08,.025,'triangle');fx.push({kind:'ring',x:e.x,y:e.y,vx:0,vy:0,r:12,life:.4,col:'#fff1c7'})}if(e.type==='reel')sound(390,.08,.015,'triangle');if(e.type==='win'){mark();for(let i=0;i<7;i++)burst(100+i*85,260+i%2*100,10,['#e6ba78','#faf1ca','#adbdaf'][i%3]);setTimeout(()=>bell(0),100);setTimeout(()=>bell(2),230);setTimeout(()=>bell(4),350);setTimeout(()=>{if(s.won&&screen==='play')modal('win')},1250)}}s.events=[];if(fx.length>200)fx.splice(0,fx.length-200)}
function sync(){const done=s.bells.filter(b=>!b.left).length;$('number').textContent=String(s.level+1).padStart(2,'0');$('name').textContent=Chime.stages[s.level].name.toUpperCase();$('count').textContent=done+' / '+s.bells.length;const lampKey=s.bells.map(b=>!b.left?1:0).join('');if($('lamps').dataset.key!==lampKey){$('lamps').innerHTML=s.bells.map(b=>'<i class="'+(!b.left?'on':'')+'"></i>').join('');$('lamps').dataset.key=lampKey}$('stars').textContent=s.stars.map(a=>a.found?'★':'☆').join(' ');$('finish').hidden=done!==s.bells.length||s.won;$('status').textContent=s.reeling&&!paused?'STRING PULLED IN':s.combo>=3?'HARMONY ×'+s.combo:done===s.bells.length?'FIND THE LAST STARS':'MAKE A LITTLE MUSIC';$('detail').textContent=done===s.bells.length?'Finish now, or collect every star.':'Swing the yo-yo into the bells.';$('reel').className=s.reeling&&!paused?'active':'';$('sound').textContent=profile.sound?'♫':'♪';$('hint').textContent=done===s.bells.length?'Collect the stars, or tap DONE':s.level===0?'Drag to swing · Hold REEL to pull closer':s.level===1?'Dotted bells need two separate swings':s.level===2?'Follow the moving bells':'Swing · Reel · Make a little music';if(s.t>toastEnd)$('toast').textContent=''}
let canvas,art;new p5(p=>{p.setup=()=>{p.pixelDensity(Math.min(1.5,devicePixelRatio||1));canvas=p.createCanvas(720,900).parent('canvas').elt;art=ChimeArt(p.drawingContext);p.frameRate(45);resize();window.addEventListener('resize',resize);const point=e=>{const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*720/r.width,y:(e.clientY-r.top)*900/r.height}};canvas.onpointerdown=e=>{e.preventDefault();if(paused||s.won)return;wake();canvas.setPointerCapture(e.pointerId);if(primary!==null){reelIds.add(e.pointerId);return}primary=e.pointerId;target=point(e)};canvas.onpointermove=e=>{if(e.pointerId===primary&&!paused)target=point(e)};const end=e=>{if(e.pointerId===primary){primary=null;target=null}reelIds.delete(e.pointerId)};canvas.onpointerup=end;canvas.onpointercancel=end;modal(s.won?'win':'intro');sync()};function resize(){const r=$('canvas').getBoundingClientRect(),scale=Math.min(r.width/720,r.height/900);canvas.style.width=scale*720+'px';canvas.style.height=scale*900+'px'}
p.draw=()=>{if(!paused){acc+=Math.min(.08,p.deltaTime/1000);while(acc>=1/60){let input=target?{...target}:{};const dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),dy=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);if(dx||dy)input={x:s.hx+dx*100,y:s.hy+dy*100};input.reel=reelIds.size>0||!!keys[' '];Chime.step(s,1/60,input);effects();if(!s.won){trail.push({x:s.x,y:s.y});if(trail.length>22)trail.shift()}for(const f of fx){f.life-=1/60;f.x+=f.vx/60;f.y+=f.vy/60;if(f.kind==='ring')f.r+=90/60;else f.vy+=45/60}fx=fx.filter(f=>f.life>0);acc-=1/60}}else acc=0;art.draw(s,fx,trail,profile.skin,paused?null:target);sync()}});
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys[e.key]=true;if(e.key===' '&&!paused)wake();if(e.key==='Escape')paused?(s.won?modal('win'):resume()):modal('pause')});window.addEventListener('keyup',e=>keys[e.key]=false);window.addEventListener('blur',()=>{if(!paused)modal(s.won?'win':'pause')});document.addEventListener('visibilitychange',()=>{if(document.hidden){if(!paused)modal(s.won?'win':'pause');save();hush()}});window.addEventListener('pagehide',save);setInterval(save,2000);
window.game={get state(){return s},get profile(){return profile},get paused(){return paused},get voices(){return voices.length},get particles(){return fx.length}};
})();
