(function(root){
const M=typeof Matter!=='undefined'?Matter:require('./matter.min.js'),{Engine,Bodies,Body,Composite,Constraint,Events,Vector}=M;
const clone=x=>JSON.parse(JSON.stringify(x)),key=p=>p.x+','+p.y;
const parts={wood:{name:'Timber',cost:1},wheel:{name:'Wheel',cost:2},ram:{name:'Ram',cost:3},cannon:{name:'Cannon',cost:4},spring:{name:'Spring',cost:3},balloon:{name:'Balloon',cost:3},erase:{name:'Remove',cost:0}};
const starter=[{x:1,y:1,type:'core'},{x:0,y:1,type:'wood'},{x:2,y:1,type:'wood'},{x:0,y:2,type:'wheel'},{x:2,y:2,type:'wheel'},{x:3,y:1,type:'ram'},{x:2,y:0,type:'cannon'}];
const levels=[
{name:'A Very Small Siege',length:1250,towers:[[660,3]],ramp:[],gaps:[],barrels:[610],stars:[430,850],budget:12},
{name:'The Orchard Wall',length:1550,towers:[[640,3],[1120,4]],ramp:[],gaps:[],barrels:[590,1080],stars:[450,1310],budget:13},
{name:'Over the Green Hill',length:1650,towers:[[900,4],[1330,3]],ramp:[[500,110,260]],gaps:[],barrels:[850],stars:[480,1450],budget:14},
{name:'Bridge of Little Worries',length:1730,towers:[[720,4],[1390,4]],ramp:[],gaps:[[920,180]],barrels:[680,1340],stars:[450,1580],budget:14},
{name:'Under the Old Aqueduct',length:1830,towers:[[650,5],[1530,3]],ramp:[],gaps:[],arches:[[900,280,420]],barrels:[600,1490],stars:[430,1690],budget:12},
{name:'The High Garden Gate',length:1900,towers:[[820,4],[1510,5]],ramp:[[430,80,220]],gaps:[],gates:[[1130,140]],barrels:[770,1460],stars:[400,1740],budget:16},
{name:'A Castle Across the River',length:2000,towers:[[700,4],[1430,5],[1740,3]],ramp:[],gaps:[[940,220]],gates:[[1240,110]],barrels:[650,1380,1700],stars:[400,1880],budget:15},
{name:'The Brass Crown',length:2200,towers:[[660,4],[1210,5],[1800,5]],ramp:[],gaps:[[1460,150]],arches:[[840,200,420]],gates:[[1640,100]],barrels:[610,1160,1750],stars:[430,2040],budget:16}
];
function cost(bp){return bp.reduce((n,p)=>n+(parts[p.type]?.cost||0),0)}
function valid(bp){if(!bp.some(p=>p.type==='core'&&p.x===1&&p.y===1))return false;const map=new Map(bp.map(p=>[key(p),p]));if(map.size!==bp.length)return false;for(const p of bp){if(p.x<0||p.x>4||p.y<0||p.y>2)return false;if(p.type==='wheel'&&!['wood','core','ram','spring'].includes(map.get(p.x+','+(p.y-1))?.type))return false}const reached=new Set(['1,1']),q=[map.get('1,1')];for(let j=0;j<q.length;j++){const p=q[j];for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const k=(p.x+dx)+','+(p.y+dy),n=map.get(k);if(n&&!reached.has(k)){reached.add(k);q.push(n)}}}return reached.size===bp.length&&bp.some(p=>p.type==='wheel')&&cost(bp)<=22}
function edit(bp,x,y,type){if(x===1&&y===1)return null;const next=bp.filter(p=>p.x!==x||p.y!==y);if(type!=='erase')next.push({x,y,type});if(cost(next)>22)return null;return next}
class Run{
constructor(index,bp=starter,snapshot=null){this.index=index;this.level=levels[index];this.bp=clone(bp);this.engine=Engine.create({enableSleeping:false,positionIterations:8,velocityIterations:8,constraintIterations:6});this.engine.gravity.y=1;this.bodies=[];this.vehicle=[];this.joints=[];this.bells=[];this.barrels=[];this.shots=[];this.coins=[];this.events=[];this.time=0;this.cooldown=0;this.hop=0;this.status='play';this.collected=0;this.fired=0;this.broken=0;this.angle=35;this.goalTime=0;this.build();if(snapshot)this.restore(snapshot);Events.on(this.engine,'collisionStart',e=>{for(const p of e.pairs){for(const b of [p.bodyA,p.bodyB])if(b.plugin.kind==='shot'&&!b.plugin.dead){b.plugin.dead=true;this.explode(b.position.x,b.position.y,180,1);}}});}
add(body,kind,extra={}){body.plugin={kind,...extra};body.plugin.id=this.bodies.length;this.bodies.push(body);Composite.add(this.engine.world,body);return body}
ground(x,w,y=520){this.add(Bodies.rectangle(x+w/2,y+65,w,130,{isStatic:true,friction:1}),'ground',{width:w,height:130})}
build(){const l=this.level;let from=-200;for(const [x,w] of l.gaps){this.ground(from,x-from);from=x+w}this.ground(from,l.length+400-from);this.add(Bodies.rectangle(-220,100,40,1200,{isStatic:true}),'wall');this.add(Bodies.rectangle(l.length+380,100,40,1200,{isStatic:true}),'wall');
for(const [x,h,w] of l.ramp){const slope=Bodies.fromVertices(x,520-h/2,[[{x:-w/2,y:h/2},{x:0,y:-h/2},{x:w/2,y:h/2}]],{isStatic:true,friction:.9});this.add(slope,'ramp',{x,h,w})}
for(const [x,w,bottom] of l.arches||[])this.add(Bodies.rectangle(x+w/2,bottom-32,w,64,{isStatic:true,friction:.7}),'arch',{width:w,height:64});
for(const [x,h] of l.gates||[])this.add(Bodies.rectangle(x,520-h/2,42,h,{isStatic:true,friction:.7}),'gate',{width:42,height:h});
for(const [x,w] of l.gaps){let prev=null;const count=Math.ceil(w/30);for(let k=0;k<count;k++){const b=this.add(Bodies.rectangle(x+15+k*w/count,518,w/count+2,12,{density:.003,friction:1}),'bridge',{width:w/count+2,height:12});if(prev)Composite.add(this.engine.world,Constraint.create({bodyA:prev,pointA:{x:w/count/2,y:0},bodyB:b,pointB:{x:-w/count/2,y:0},length:0,stiffness:.8}));else Composite.add(this.engine.world,Constraint.create({pointA:{x:x-3,y:515},bodyB:b,pointB:{x:-w/count/2,y:0},length:0,stiffness:.9}));prev=b;if(k===count-1)Composite.add(this.engine.world,Constraint.create({pointA:{x:x+w+3,y:515},bodyB:b,pointB:{x:w/count/2,y:0},length:0,stiffness:.9}))}}
for(let ti=0;ti<l.towers.length;ti++){const [x,rows]=l.towers[ti];for(let r=0;r<rows;r++)for(let c=0;c<2;c++){this.add(Bodies.rectangle(x+(c-.5)*40+(r%2?4:0),499-r*39,39,38,{density:.002,friction:.65,restitution:.04}),'stone',{width:39,height:38,variant:(r+c+ti)%3})}const bell=this.add(Bodies.rectangle(x,499-rows*39,64,28,{density:.001,friction:.8}),'bell',{width:64,height:28,home:{x,y:499-rows*39},cleared:false,tower:ti});this.bells.push(bell)}
for(const x of l.barrels)this.barrels.push(this.add(Bodies.rectangle(x,493,26,48,{density:.001,friction:.6}),'barrel',{width:26,height:48,spent:false}));
for(const x of l.stars)this.coins.push({x,y:450,taken:false});
const group=Body.nextGroup(true);for(const p of this.bp){const x=140+(p.x-1)*44,y=380+(p.y-1)*44;let b;if(p.type==='wheel')b=Bodies.circle(x,y,24,{density:.0025,friction:1.4,frictionStatic:4,restitution:.04,collisionFilter:{group}});else b=Bodies.rectangle(x,y,40,p.type==='cannon'?32:40,{density:p.type==='ram'?.004:p.type==='balloon'?.0004:.0015,friction:.8,restitution:.02,collisionFilter:{group}});this.add(b,p.type,{grid:clone(p),width:40,height:40,group,active:true});this.vehicle.push(b);if(p.type==='core')this.core=b}
const map=new Map(this.vehicle.map(b=>[key(b.plugin.grid),b]));for(const b of this.vehicle){const p=b.plugin.grid;if(p.type==='wheel'){const above=map.get(p.x+','+(p.y-1));if(above){const j=Constraint.create({bodyA:above,pointA:{x:0,y:44},bodyB:b,pointB:{x:0,y:0},length:0,stiffness:.98,damping:.1});j.plugin={vehicle:true,hinge:true,base:44};this.joints.push(j);Composite.add(this.engine.world,j)}continue}for(const [dx,dy] of [[1,0],[0,1]]){const n=map.get((p.x+dx)+','+(p.y+dy));if(n&&n.plugin.kind!=='wheel'){// Two bolts per timber seam resist free rotation.
for(const side of [-1,1]){const j=Constraint.create({bodyA:b,pointA:{x:dx*22+(dy?side*13:0),y:dy*22+(dx?side*13:0)},bodyB:n,pointB:{x:-dx*22+(dy?side*13:0),y:-dy*22+(dx?side*13:0)},length:0,stiffness:.85,damping:.15});j.plugin={vehicle:true,hinge:false,base:44};this.joints.push(j);Composite.add(this.engine.world,j)}}}}
}
event(type,x,y){this.events.push({type,x,y});if(this.events.length>30)this.events.shift()}
explode(x,y,r,power){this.event('blast',x,y);for(const b of this.bodies){if(b.isStatic||b.plugin.kind==='shot')continue;const dx=b.position.x-x,dy=b.position.y-y,d=Math.hypot(dx,dy);if(d<r&&d>1){const f=(1-d/r)*power*.022*b.mass;Body.applyForce(b,b.position,{x:dx/d*f,y:dy/d*f-.004*b.mass});if(b.plugin.kind==='barrel'&&!b.plugin.spent){b.plugin.spent=true;this.event('barrel',b.position.x,b.position.y);(this.deferred||(this.deferred=[])).push({x:b.position.x,y:b.position.y,r:210,power:.8})}}}}
fire(){if(this.cooldown>0||this.status!=='play')return false;const cannons=this.vehicle.filter(b=>b.plugin.kind==='cannon'&&Math.hypot(b.position.x-this.core.position.x,b.position.y-this.core.position.y)<250);if(!cannons.length)return false;for(const c of cannons){const a=-this.angle*Math.PI/180+c.angle,dir={x:Math.cos(a),y:Math.sin(a)},b=this.shots.find(b=>b.plugin.removed)||this.add(Bodies.circle(c.position.x+dir.x*43,c.position.y+dir.y*43,9,{density:.004,restitution:.2,collisionFilter:{group:c.plugin.group}}),'shot',{age:0,dead:false});if(b.plugin.removed){Body.setPosition(b,{x:c.position.x+dir.x*43,y:c.position.y+dir.y*43});Body.setAngle(b,0);Body.setAngularVelocity(b,0);b.plugin.age=0;b.plugin.dead=false;b.plugin.removed=false;Composite.add(this.engine.world,b)}Body.setVelocity(b,{x:dir.x*15,y:dir.y*15});if(!this.shots.includes(b))this.shots.push(b);Body.applyForce(c,c.position,{x:-dir.x*.012,y:-dir.y*.012});this.event('fire',b.position.x,b.position.y)}this.fired++;this.cooldown=.75;return true}
update(input={}){if(this.status!=='play')return;this.time+=1/60;this.cooldown=Math.max(0,this.cooldown-1/60);this.hop=Math.max(0,this.hop-1/60);if(input.fire)this.fire();const throttle=Math.max(-1,Math.min(1,input.drive||0));for(const w of this.vehicle.filter(b=>b.plugin.kind==='wheel')){Body.setAngularVelocity(w,w.angularVelocity*.7+throttle*.16);if(Math.abs(w.velocity.x)>5)Body.setVelocity(w,{x:w.velocity.x*.985,y:w.velocity.y})}
const near=this.vehicle.filter(b=>Math.hypot(b.position.x-this.core.position.x,b.position.y-this.core.position.y)<190),mass=near.reduce((a,b)=>a+b.mass,0),balloons=near.filter(b=>b.plugin.kind==='balloon');for(const b of balloons)Body.applyForce(b,b.position,{x:0,y:-(input.lift&&this.core.position.y>230?.03:.004)});const grounded=this.vehicle.some(b=>b.plugin.kind==='wheel'&&this.engine.pairs.list.some(p=>p.isActive&&(p.bodyA===b||p.bodyB===b)&&[p.bodyA.plugin.kind,p.bodyB.plugin.kind].some(k=>['ground','ramp','bridge','stone'].includes(k))));if(balloons.length&&throttle)Body.applyForce(this.core,this.core.position,{x:throttle*mass*.00012,y:0});if(grounded&&throttle)Body.applyForce(this.core,this.core.position,{x:throttle*mass*.0004,y:0});const groundedFrame=grounded||this.engine.pairs.list.some(p=>p.isActive&&near.some(b=>p.bodyA===b||p.bodyB===b)&&[p.bodyA.plugin.kind,p.bodyB.plugin.kind].some(k=>['ground','bridge','ramp'].includes(k)));if(input.lift&&near.some(b=>b.plugin.kind==='spring'))for(const b of near.filter(b=>b.plugin.kind!=='wheel'))Body.setAngularVelocity(b,b.angularVelocity*.8-Math.atan2(Math.sin(this.core.angle),Math.cos(this.core.angle))*.025);if(input.lift&&this.hop<=0&&groundedFrame&&near.some(b=>b.plugin.kind==='spring')){for(const b of near)Body.applyForce(b,b.position,{x:throttle*b.mass*.002,y:-b.mass*.04});this.hop=1.05;this.event('hop',this.core.position.x,this.core.position.y)}
Engine.update(this.engine,1000/60);for(let i=0;this.deferred?.length&&i<12;i++){const q=this.deferred;this.deferred=[];q.forEach(f=>this.explode(f.x,f.y,f.r,f.power))}
for(const b of this.bells){if(!b.plugin.cleared&&(b.position.y>b.plugin.home.y+55||Math.abs(b.position.x-b.plugin.home.x)>65||Math.abs(b.angle)>.9)){b.plugin.cleared=true;this.event('bell',b.position.x,b.position.y)}}
for(const c of this.coins)if(!c.taken&&near.some(b=>Math.hypot(b.position.x-c.x,b.position.y-c.y)<62)){c.taken=true;this.collected++;this.event('coin',c.x,c.y)}
for(const j of this.joints){if(j.plugin.broken)continue;const a=Vector.add(j.bodyA.position,Vector.rotate(j.pointA,j.bodyA.angle)),b=Vector.add(j.bodyB.position,Vector.rotate(j.pointB,j.bodyB.angle));if(Math.hypot(a.x-b.x,a.y-b.y)>65){j.plugin.broken=true;Composite.remove(this.engine.world,j);this.broken++;this.event('snap',a.x,a.y)}}
for(const b of this.shots){b.plugin.age+=1/60;if((b.plugin.dead||b.plugin.age>4)&&!b.plugin.removed){b.plugin.removed=true;Composite.remove(this.engine.world,b)}}
if(this.bells.every(b=>b.plugin.cleared)&&this.core.position.x>this.level.length-150){this.goalTime+=1/60;if(this.goalTime>.3){this.status='win';this.event('win',this.core.position.x,this.core.position.y)}}else this.goalTime=0;if(this.core.position.y>800){this.status='lost';this.event('lost',this.core.position.x,this.core.position.y)}
}
snapshot(){return {index:this.index,bp:clone(this.bp),time:this.time,cooldown:this.cooldown,hop:this.hop,status:this.status,collected:this.collected,fired:this.fired,broken:this.broken,angle:this.angle,goalTime:this.goalTime,coins:clone(this.coins),bodies:this.bodies.map(b=>({p:clone(b.position),v:clone(b.velocity),a:b.angle,av:b.angularVelocity,plugin:clone(b.plugin)})),joints:this.joints.map(j=>!!j.plugin.broken)}}
restore(s){this.time=s.time;this.cooldown=s.cooldown;this.hop=s.hop;this.status=s.status;this.collected=s.collected;this.fired=s.fired;this.broken=s.broken;this.angle=s.angle;this.goalTime=s.goalTime;this.coins=clone(s.coins);for(let i=0;i<s.bodies.length;i++){const row=s.bodies[i];let b=this.bodies[i];if(!b&&row.plugin.kind==='shot'){b=this.add(Bodies.circle(row.p.x,row.p.y,9,{density:.004,restitution:.2,collisionFilter:{group:this.core.plugin.group}}),'shot');this.shots.push(b)}if(!b)continue;Body.setPosition(b,row.p);Body.setAngle(b,row.a);Body.setVelocity(b,row.v);Body.setAngularVelocity(b,row.av);b.plugin=clone(row.plugin);if(row.plugin.group)b.collisionFilter.group=row.plugin.group;if(b.plugin.removed)Composite.remove(this.engine.world,b)}s.joints.forEach((broken,i)=>{if(broken&&this.joints[i]){this.joints[i].plugin.broken=true;Composite.remove(this.engine.world,this.joints[i])}});this.events=[]}
dispose(){Engine.clear(this.engine);Composite.clear(this.engine.world,false);Events.off(this.engine)}
}
function setTimeoutSafe(run,fn){(run.deferred||(run.deferred=[])).push(fn)}
function rating(run){return 1+(run.collected===2?1:0)+(cost(run.bp)<=run.level.budget?1:0)}
root.Scrap={Run,parts,starter,levels,valid,edit,cost,rating,clone,M};if(typeof module!=='undefined')module.exports=root.Scrap;
})(typeof window==='undefined'?globalThis:window);
