(function(){'use strict';const $=id=>document.getElementById(id),key='odd-wheels-v1';let s=OW.fresh();try{s=OW.load(localStorage.getItem(key))}catch{}let c=OW.course(s.n),art,audio=null,muted=false,started=false,paused=false,steer=0,held=false,actionQueued=false,keys=new Set,drag=null,toastTimer=0,saved=0,acc=0,last=0,renderTime=0,menuBefore='',lastNativeAction=-1000,celebration=0;try{muted=localStorage.getItem(key+'-mute')==='1'}catch{}try{art=new OWArt($('world'));art.load(c,s)}catch(e){console.error(e);$('error').hidden=false;return}
function save(){try{localStorage.setItem(key,JSON.stringify(s));localStorage.setItem(key+'-mute',muted?'1':'0')}catch{}}
function tone(f=500,d=.08,vol=.035,type='sine'){if(muted)return;try{audio ||= new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(50,f*.7),audio.currentTime+d);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');toastTimer=1.5;}
function wire(e,fn){e.addEventListener('pointerup',ev=>{if(ev.button!==0||e.disabled)return;ev.preventDefault();e.__up=lastNativeAction=performance.now();fn(ev)});e.addEventListener('click',ev=>{if(ev.isTrusted&&performance.now()-(e.__up||0)<600)return;fn(ev)});}function bind(id,fn){wire($(id),fn)}document.addEventListener('click',ev=>{if(ev.isTrusted&&ev.detail>0&&performance.now()-lastNativeAction<600){ev.preventDefault();ev.stopImmediatePropagation()}},true);
function clearInput(){steer=0;held=false;keys.clear();drag=null;actionQueued=false;}
function panelsOff(){for(const id of['cover','menu','result','collection'])$(id).hidden=true;}
function enter(n){panelsOff();OW.start(s,n);c=OW.course(n);art.load(c,s);started=true;paused=false;clearInput();$('hud').hidden=false;$('controls').hidden=false;const tips={legs:'Drag to steer · Tap to jump',spring:'Big springs. Bigger jumps.',wings:'Jump, then HOLD to glide',sneeze:'Tap to sneeze obstacles away',delivery:'Carry lunch to the finish',stilts:'Long legs step over tiny gaps',roller:'Fast feet. Watch the edges.',party:'A different car every stretch'};$('tip').textContent=tips[c.mode];$('courseName').textContent=c.name;$('courseNumber').textContent=n<8?String(n+1).padStart(2,'0')+' / 08':'WILD '+(n-7);abilityLabel();toast(c.mode==='legs'?'THE CAR HAS LEGS.':c.mode==='spring'?'BOING!':c.mode==='wings'?'SPECIAL DELIVERY.':c.name);save();updateHUD();}
function abilityLabel(){let m=s.mode;if(m==='party')m=s.z<45?'spring':s.z<100?'sneeze':'wings';const labels={legs:['↑','JUMP'],spring:['↟','BOING'],wings:['≈','HOLD'],sneeze:['✺','ACHOO'],delivery:['↑','JUMP'],stilts:['↑','STEP'],roller:['↑','JUMP']};const a=labels[m]||labels.legs;$('action').querySelector('span').textContent=a[0];$('action').querySelector('small').textContent=a[1];}
function updateHUD(){$('timer').textContent=Math.floor(s.time/60)+':'+String(Math.floor(s.time%60)).padStart(2,'0');$('coins').textContent=s.collected.length;$('progress').firstElementChild.style.width=Math.min(100,s.z/c.length*100)+'%';$('badges').textContent=c.coins.filter(x=>x.gold).map(x=>s.collected.includes(x.id)?'◆':'◇').join(' ');abilityLabel();}
function finish(){clearInput();paused=true;celebration=1.5;$('controls').hidden=true;$('result').hidden=false;const r=s.lastResult;$('medals').textContent='★'.repeat(r.medal)+'☆'.repeat(3-r.medal);$('resultTitle').textContent=['Good legs.','Peak boing.','Air apparently works.','Bless you.','Lunch has landed.','A tall order.','Wheely good.','Legends have legs.'][s.n%8];$('resultStats').innerHTML=r.time.toFixed(1)+'s &nbsp; · &nbsp; '+r.badges+'/3 badges<br>+'+r.reward+' garage tokens';$('resultLabel').textContent=s.falls?'A FEW DETOURS. STILL A LEGEND.':'EXTREMELY QUESTIONABLE. PERFECTLY EXECUTED.';$('next').textContent=s.n>=7?'WILD LAP ↗':'NEXT WEIRD THING ↗';tone(660,.3);setTimeout(()=>tone(880,.4),120);save();}
function handle(e){art.emit(e);if(e.type==='coin')tone(700+s.collected.length%5*90,.08,.025);else if(e.type==='badge'){tone(1100,.2);toast('A LITTLE DETOUR. A BIG SHINY.');}else if(e.type==='sneeze'){tone(110,.2,.08,'sawtooth');toast(e.count?'ACHOO! '+e.count+' THINGS FLUNG':'ACHOO!');}else if(e.type==='bonk'){tone(90,.13,.06,'triangle');toast('BONK. STILL RUNNING.');if(navigator.vibrate)navigator.vibrate(25);}else if(e.type==='spring'||e.type==='fan'||e.type==='boost'){tone(340,.22,.045,'triangle');toast(e.type==='fan'?'AIR MAIL!':e.type==='boost'?'WHEEEEE!':'BOING!');}else if(e.type==='cargo'){tone(520,.16);toast('LUNCH STACK +1');}else if(e.type==='fall'){tone(190,.2);toast('A QUICK DETOUR.');art.camReady=false;}else if(e.type==='jump'){tone(s.mode==='spring'?310:420,.07,.022,'triangle');}else if(e.type==='land'){tone(160,.05,.012,'triangle');}else if(e.type==='finish')finish();}
function openMenu(){if(!$('collection').hidden)return;paused=true;clearInput();$('menu').hidden=false;save();}
function collection(){menuBefore=!$('result').hidden?'result':!$('cover').hidden?'cover':!$('menu').hidden?'menu':'run';panelsOff();$('collection').hidden=false;paused=true;clearInput();$('bank').textContent='✦ '+s.bank+' TOKENS · '+Object.keys(s.records).filter(x=>+x<8).length+'/8 POSTCARDS';$('paintShop').replaceChildren();for(let i=0;i<4;i++){const b=document.createElement('button'),prices=[0,20,35,55];b.style.background=OWPaint[i];b.className=s.paint===i?'selected':'';b.textContent=s.owned.includes(i)?['SUNSHINE','SEAFOAM','BERRY','BLUEBELL'][i]:'✦ '+prices[i];b.setAttribute('aria-label',['Sunshine','Seafoam','Berry','Bluebell'][i]+' paint');wire(b,()=>{if(!s.owned.includes(i)){if(s.bank<prices[i]){tone(160);toast('A FEW MORE TOKENS');return}s.bank-=prices[i];s.owned.push(i)}s.paint=i;art.load(c,s);save();collectionRefresh()});$('paintShop').appendChild(b)}$('courses').replaceChildren();for(let i=0;i<8;i++){const b=document.createElement('button'),rec=s.records[i];b.innerHTML='<b>'+String(i+1).padStart(2,'0')+' · '+OW.names[i]+'</b><span>'+(rec?'★'.repeat(rec.medal)+' · '+rec.time.toFixed(1)+'s':'◇ ◇ ◇')+'</span>';b.disabled=i>s.unlocked;b.setAttribute('aria-label','Course '+(i+1)+' '+OW.names[i]);wire(b,()=>enter(i));$('courses').appendChild(b)}$('wild').hidden=s.unlocked<8;}
function collectionRefresh(){const old=menuBefore;collection();menuBefore=old;}
bind('start',()=>{tone(500);if(s.phase==='run'){panelsOff();started=true;paused=false;$('hud').hidden=false;$('controls').hidden=false;$('courseName').textContent=c.name;$('courseNumber').textContent=s.n<8?String(s.n+1).padStart(2,'0')+' / 08':'WILD '+(s.n-7);$('tip').textContent='Drag to steer · Tap to jump';art.camReady=false;updateHUD()}else if(s.phase==='finish'){started=true;$('cover').hidden=true;$('hud').hidden=false;finish()}else enter(0)});
bind('sound',()=>{muted=!muted;$('sound').textContent=muted?'♪':'♫';$('sound').setAttribute('aria-pressed',String(muted));tone();save()});$('sound').textContent=muted?'♪':'♫';
bind('pause',openMenu);bind('resume',()=>{$('menu').hidden=true;paused=false;clearInput();});bind('retry',()=>enter(s.n));bind('help',()=>{$('helpText').hidden=!$('helpText').hidden});bind('next',()=>enter(s.n+1));bind('replay',()=>enter(s.n));for(const id of['album','menuAlbum','resultAlbum'])bind(id,collection);bind('wild',()=>enter(Math.max(8,s.bestWild+8)));bind('closeAlbum',()=>{$('collection').hidden=true;if(menuBefore==='cover')$('cover').hidden=false;else if(menuBefore==='result')$('result').hidden=false;else if(menuBefore==='menu')$('menu').hidden=false;else paused=false;});
for(const[id,value]of[['left',-1],['right',1]]){$(id).addEventListener('pointerdown',e=>{e.preventDefault();$(id).setPointerCapture(e.pointerId);steer=value;tone(230,.03,.012)});for(const ev of['pointerup','pointercancel','lostpointercapture'])$(id).addEventListener(ev,()=>{steer=0});}
$('action').addEventListener('pointerdown',e=>{e.preventDefault();$('action').setPointerCapture(e.pointerId);held=true;actionQueued=true;});for(const ev of['pointerup','pointercancel','lostpointercapture'])$('action').addEventListener(ev,()=>held=false);
$('world').addEventListener('pointerdown',e=>{if(!started||paused)return;e.preventDefault();$('world').setPointerCapture(e.pointerId);drag={id:e.pointerId,x:e.clientX,start:e.clientX,moved:false,at:performance.now()};});$('world').addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const dx=e.clientX-drag.start;if(Math.abs(dx)>6)drag.moved=true;steer=Math.max(-1,Math.min(1,dx/45));});$('world').addEventListener('pointerup',e=>{if(drag?.id!==e.pointerId)return;if(!drag.moved)actionQueued=true;drag=null;steer=0;});$('world').addEventListener('pointercancel',clearInput);
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Space','KeyA','KeyD'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.code==='Space'&&!e.repeat){actionQueued=true;held=true}if(e.code==='Escape'){if($('menu').hidden)openMenu();else{$('menu').hidden=true;paused=false;}}});window.addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='Space')held=false});window.addEventListener('blur',()=>{if(started&&s.phase==='run')openMenu();clearInput()});document.addEventListener('visibilitychange',()=>{if(document.hidden){save();clearInput();}last=0;});window.addEventListener('pagehide',save);window.addEventListener('resize',()=>{clearInput();art.resize();art.render(s,0,true)});
function frame(now){requestAnimationFrame(frame);if(document.hidden){last=0;return}const dt=last?Math.min(.05,(now-last)/1000):0;last=now;if(started&&!paused&&s.phase==='run'){acc+=dt;while(acc>=1/60){const events=OW.step(s,c,1/60,{steer:keys.has('ArrowLeft')||keys.has('KeyA')?-1:keys.has('ArrowRight')||keys.has('KeyD')?1:steer,action:actionQueued,hold:held});actionQueued=false;for(const e of events)handle(e);acc-=1/60;if(s.phase!=='run'){acc=0;break}}updateHUD();saved+=dt;if(saved>=1.5){save();saved=0}}else acc=0;if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('toast').classList.remove('show');}if(!paused||!started||celebration>0&& !$("result").hidden){celebration=Math.max(0,celebration-dt);renderTime+=dt;if(renderTime>=1/30){art.render(s,renderTime);renderTime=0}}}
requestAnimationFrame(frame);window.__odd={state:()=>OW.copy(s),course:()=>OW.copy(c),renderer:()=>({drawCalls:art.renderer.info.render.calls,triangles:art.renderer.info.render.triangles})};
})();


