'use strict';const $=id=>document.getElementById(id),KEY='kickflip-cove-v1';let profile={stars:Array(8).fill(0),scores:Array(8).fill(0),skin:0,sound:true,save:null},game,paused=true,pointer=null,menu='intro',clock=0,acc=0,saveTime=0,toast=0,fx=[],view={w:390,h:700,s:.6,oy:280,cam:0},ctxAudio,voices=0;const oscs=new Set();
try{const d=JSON.parse(localStorage.getItem(KEY));if(d&&Array.isArray(d.stars)&&d.stars.length===8&&d.stars.every(v=>Number.isInteger(v)&&v>=0&&v<=3)){profile={...profile,...d};profile.scores=Array.from({length:8},(_,i)=>Number.isFinite(d.scores?.[i])?Math.max(0,d.scores[i]):0);profile.skin=[0,1,2].includes(d.skin)?d.skin:0;}}catch{}
const total=()=>profile.stars.reduce((a,b)=>a+b,0),threshold=[0,6,15];if(total()<threshold[profile.skin])profile.skin=0;game=Kick.Run.restore(profile.save)||new Kick.Run(0);window.game=game;
function save(){profile.save=game.snapshot();try{localStorage.setItem(KEY,JSON.stringify(profile));}catch{}}
function audio(){if(!profile.sound)return;try{ctxAudio??=new(window.AudioContext||window.webkitAudioContext)();if(ctxAudio.state!=='running')ctxAudio.resume();}catch{}}
function note(f,d=.14,delay=0,type='sine',vol=.035,end){if(!profile.sound||!ctxAudio||ctxAudio.state!=='running'||voices>=14)return;const o=ctxAudio.createOscillator(),gain=ctxAudio.createGain(),t=ctxAudio.currentTime+delay;o.type=type;o.frequency.setValueAtTime(f,t);if(end)o.frequency.exponentialRampToValueAtTime(end,t+d);gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(vol,t+.008);gain.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(gain);gain.connect(ctxAudio.destination);o.start(t);o.stop(t+d+.02);oscs.add(o);voices++;o.onended=()=>{oscs.delete(o);voices--;o.disconnect();gain.disconnect();};}
function silence(){for(const o of oscs){try{o.stop();}catch{}}ctxAudio?.suspend();}
function tune(e){if(e.type==='jump'||e.type==='spring'){note(180,.18,0,'triangle',.04,e.type==='spring'?800:500);}if(e.type==='flip'){note(650,.12,0,'triangle',.035,220);note(850,.1,.08);}if(e.type==='grind')note(150,.14,0,'sawtooth',.02,220);if(e.type==='spark')note(110+Math.sin(clock*7)*30,.05,0,'triangle',.013);if(e.type==='land'){note(90,.08,0,'triangle',.06);note(440*Math.pow(1.1,Math.min(e.combo,8)),.18);}if(e.type==='token')[659,784,1047].forEach((f,i)=>note(f,.18,i*.07));if(e.type==='fall'){note(220,.25,0,'triangle',.06,70);}if(e.type==='won')[523,659,784,1047].forEach((f,i)=>note(f,.3,i*.1));}
function clear(){pointer=null;game.release(true);}
function say(s){$('toast').textContent=s;toast=1.05;$('toast').style.opacity=1;}
function burst(x,y,col,n=14){fx.push({kind:'ring',x,y,life:.45,max:.45,col});for(let i=0;i<n;i++)fx.push({kind:'bit',x,y:y-6,vx:Math.sin(i*2.399)*70-30,vy:-25+Math.cos(i*2.399)*60,spin:i%2?4:-3,life:.6,max:.6,col:i%3?col:'#fff1c1'});if(fx.length>100)fx.splice(0,fx.length-100);}
function consume(){for(const e of game.events.splice(0)){tune(e);if(e.type==='jump')burst(game.x,game.y,'#ecd3b1',6);if(e.type==='flip')say('KICKFLIP!');if(e.type==='spring')say('MORE AIR!');if(e.type==='grind'){say('ON RAIL!');burst(game.x,game.y,'#f7d99d',9);}if(e.type==='spark')burst(game.x-15,game.y,'#ffd896',3);if(e.type==='land'){say((e.perfect?'PERFECT':'NICE')+' ×'+e.combo);burst(game.x,game.y,'#ead1a2');}if(e.type==='token'){say('SHINY! +300');burst(e.x,e.y,'#f7db91',22);}if(e.type==='checkpoint')say('CHECKPOINT');if(e.type==='fall'){clear();say('BACK ON BOARD');burst(game.x,game.y,'#d6b4b1',18);}if(e.type==='won'){profile.stars[game.n]=Math.max(profile.stars[game.n],game.stars);profile.scores[game.n]=Math.max(profile.scores[game.n],game.score);paused=true;clear();save();open('won');}}}
function reset(n){game=new Kick.Run(n);window.game=game;game.start();paused=false;fx=[];acc=0;clear();$('overlay').classList.add('off');menu='';audio();save();update();}
function resume(){if(game.state==='won')return reset(game.n);clear();game.start();paused=false;menu='';$('overlay').classList.add('off');audio();update();}
function open(kind){paused=true;clear();if(kind!=='won')silence();menu=kind;save();$('overlay').classList.remove('off');let html='';
 if(kind==='intro')html='<div class="eyebrow">A LITTLE MORE AIR</div><div class="hero"></div><h1>Kickflip<br>Cove</h1><p>Hold to crouch. Release to jump.<br>Press in the air to flip & catch rails.<br>Find three shinies. Ride to the finish.</p><button data-act="resume">Let’s roll</button><button class="alt" data-act="book">Ride book</button>';
 if(kind==='pause')html='<div class="eyebrow">TAKE FIVE</div><h1>Good vibes.</h1><p>'+game.map.name+'<br>Your board is parked.</p><button data-act="resume">Keep rolling</button><button class="alt" data-act="book">Ride book</button><button class="alt" data-act="restart">Restart</button>';
 if(kind==='won')html='<div class="eyebrow">THAT WAS A GOOD RIDE</div><h1>'+game.map.name+'</h1><div class="stars">'+'★'.repeat(game.stars)+'☆'.repeat(3-game.stars)+'</div><div class="stamp">'+game.tokens.length+'/3 SHINIES · '+game.score+' POINTS<br>'+game.falls+' BAILS · BEST CHAIN '+game.bestCombo+'</div><p>'+(game.stars===3?'All style. All smiles. A perfect postcard.':game.tokens.length<3?'The shiny route takes a little more air.':'A clean ride earns one more star.')+'</p><button data-act="next">'+(game.n<7?'Next ride':'Open ride book')+'</button><button class="alt" data-act="restart">Again</button><button class="alt" data-act="photo">Postcard</button>';
 if(kind==='book'){html='<div class="eyebrow">THE GOOD VIBES TOUR</div><h1>Eight little escapes.</h1><div class="stamp">'+total()+' / 24 STARS</div><div class="grid">';for(let i=0;i<8;i++)html+='<button data-level="'+i+'" '+(i&&!profile.stars[i-1]?'disabled':'')+'>'+String(i+1).padStart(2,'0')+'<small>'+'★'.repeat(profile.stars[i])+'·'.repeat(3-profile.stars[i])+'</small></button>';html+='</div><div class="skins">';['Peach','Mint','Lilac'].forEach((s,i)=>html+='<button class="alt" data-skin="'+i+'" '+(total()<threshold[i]?'disabled':'')+' style="border:2px solid '+(profile.skin===i?'#adbdac':'transparent')+'">'+s+'<br><small>'+threshold[i]+' ★</small></button>');html+='</div><button data-act="resume">Back to the board</button><p style="margin-bottom:0;font-size:10px">Stars: finish · three shinies · zero bails</p>';}
 $('panel').innerHTML=html;update();}
function photo(){try{const a=document.createElement('a');a.download='kickflip-cove-'+(game.n+1)+'.png';a.href=$('canvas').querySelector('canvas').toDataURL('image/png');a.click();if(!menu)say('POSTCARD SAVED');}catch{say('POSTCARD UNAVAILABLE');}}
$('panel').addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;audio();if(b.dataset.level!==undefined)return reset(Number(b.dataset.level));if(b.dataset.skin!==undefined){profile.skin=Number(b.dataset.skin);save();return open('book');}const a=b.dataset.act;if(a==='resume')resume();if(a==='book')open('book');if(a==='restart')reset(game.n);if(a==='next'){if(game.n<7)reset(game.n+1);else open('book');}if(a==='photo')photo();});$('book').onclick=()=>open('book');$('pause').onclick=()=>{if(paused&&menu==='pause')resume();else open('pause');};$('photo').onclick=photo;$('sound').onclick=()=>{profile.sound=!profile.sound;if(profile.sound)audio();else silence();save();update();};
function update(){$('subtitle').textContent=game.map.name.toUpperCase();$('level').textContent=String(game.n+1).padStart(2,'0')+' / 08';$('tokens').textContent='◆ '.repeat(game.tokens.length)+'◇ '.repeat(3-game.tokens.length);$('score').textContent=String(game.score).padStart(4,'0');$('progress').firstElementChild.style.width=Math.min(100,game.x/game.map.length*100)+'%';$('status').textContent=game.grind>=0?'✦ GRINDING':game.air?'↗ AIR TIME':game.held?'↓ CROUCH & CHARGE':'✦ FIND YOUR FLOW';$('sound').textContent=profile.sound?'♫':'♪';$('sound').setAttribute('aria-pressed',String(profile.sound));$('hint').textContent=game.t<8?'Hold to crouch · Release to jump · Press in air to flip':'';}
$('canvas').addEventListener('pointerdown',e=>{if(paused||pointer!==null)return;e.preventDefault();pointer=e.pointerId;$('canvas').setPointerCapture(pointer);audio();game.press();consume();});$('canvas').addEventListener('pointerup',e=>{if(e.pointerId!==pointer)return;e.preventDefault();pointer=null;game.release();consume();save();});function cancel(e){if(e.pointerId===pointer){clear();save();}}$('canvas').addEventListener('pointercancel',cancel);$('canvas').addEventListener('lostpointercapture',cancel);
document.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();if(!paused&&!e.repeat){audio();game.press();consume();}}if(e.code==='Escape'){if(paused&&menu==='pause')resume();else open('pause');}});document.addEventListener('keyup',e=>{if(e.code==='Space'&&!paused){game.release();consume();}});function suspend(){if(!paused&&game.state==='playing')open('pause');clear();silence();}window.addEventListener('blur',suspend);document.addEventListener('visibilitychange',()=>{if(document.hidden)suspend();});window.addEventListener('pagehide',save);
new p5(p=>{p.setup=()=>{const box=$('canvas');p.pixelDensity(Math.min(devicePixelRatio||1,1.5));p.createCanvas(box.clientWidth,box.clientHeight).parent(box);p.frameRate(60);resize();open(game.state==='won'?'won':'intro');};function resize(){const box=$('canvas');p.resizeCanvas(box.clientWidth,box.clientHeight);view.w=box.clientWidth;view.h=box.clientHeight;view.s=Math.min(1.1,view.w/500,view.h/430);view.oy=view.h*.76-380*view.s;view.cam=game.x-view.w*.27/view.s;clear();}p.windowResized=resize;p.draw=()=>{const dt=Math.min(p.deltaTime/1000,.05);if(!paused){clock+=dt;acc+=dt;while(acc>=1/60){game.step(1/60);acc-=1/60;consume();if(paused){acc=0;break;}}for(const f of fx){f.life-=dt;if(f.kind==='bit'){f.x+=f.vx*dt;f.y+=f.vy*dt;f.vy+=180*dt;}}fx=fx.filter(f=>f.life>0);toast-=dt;$('toast').style.opacity=toast>0?1:0;saveTime+=dt;if(saveTime>1){save();saveTime=0;}update();}view.cam=game.x-view.w*.27/view.s;KickArt.draw(p.drawingContext,view,game,fx,clock,profile.skin);};});

