(()=>{'use strict';
const A=TidyArt,$=id=>document.getElementById(id),canvas=$('table'),ctx=canvas.getContext('2d'),KEY='tidy-tails-v1',sequence=['books','drawer','plates','jars','drawer','plates','books','drawer','jars','plates','drawer','books'];
const ribbonColors=['#aa8785','#8caaa2','#bf9c5d','#9b92b1'],ribbonNames=['Rose','Sage','Honey','Lilac'],costs=[0,4,8,12];
let meta={completed:0,bank:0,earned:0,ribbon:0,owned:[0],photos:[],sound:true,pets:0},round,phase='intro',W=0,H=0,DPR=1,world={w:420,h:480,x:0,y:0,s:1,landscape:false},layoutData={},drag=null,selected=-1,history=[],hint=null,particles=[],time=0,last=0,acc=0,paint=0,checkTime=0,mood=0,toastTime=0,audioCtx=null,slideTick=0;
function rng(seed){return()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296}}
function shuffle(a,R){for(let i=a.length-1;i>0;i--){const j=Math.floor(R()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function dimensions(p){return p.rot%2?[p.rows,p.cols]:[p.cols,p.rows]}
function solvePacking(pieces,cols,rows,keep=true){const occ=new Uint8Array(cols*rows),placed=[],free=[];for(const p of pieces){if(keep&&p.gx>=0){const [w,h]=dimensions(p);for(let y=p.gy;y<p.gy+h;y++)for(let x=p.gx;x<p.gx+w;x++){if(x<0||x>=cols||y<0||y>=rows||occ[y*cols+x])return null;occ[y*cols+x]=1}placed.push({id:p.id,x:p.gx,y:p.gy,rot:p.rot})}else free.push(p)}free.sort((a,b)=>b.cols*b.rows-a.cols*a.rows);let visits=0;
 function search(k){if(++visits>150000)return false;if(k===free.length)return true;const p=free[k];for(let rot=0;rot<(p.cols===p.rows?1:2);rot++){const [w,h]=rot?[p.rows,p.cols]:[p.cols,p.rows];for(let y=0;y<=rows-h;y++)for(let x=0;x<=cols-w;x++){let fits=true;for(let yy=y;yy<y+h&&fits;yy++)for(let xx=x;xx<x+w;xx++)if(occ[yy*cols+xx]){fits=false;break}if(!fits)continue;for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++)occ[yy*cols+xx]=1;placed.push({id:p.id,x,y,rot});if(search(k+1))return true;placed.pop();for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++)occ[yy*cols+xx]=0}}return false}
 return search(0)?placed:null;
}
function make(level,seed=(Math.random()*4294967295)>>>0){const R=rng(seed),type=sequence[(level-1)%sequence.length],r={level,seed,type,moves:0,hints:0,completed:false,rating:0,items:[],order:[],stacks:[],title:'',subtitle:'',par:0};
 if(type==='books'||type==='jars'){const n=level===1?5:6;r.title=type==='books'?['The book nook','A shelf of stories','The reading corner'][Math.floor((level-1)/6)%3]:['The pantry rainbow','Herbs & little jars'][Math.floor(level/9)%2];r.subtitle=type==='books'?'Small to tall. Or tall to small.':'Put the labels in order. Either way.';r.items=Array.from({length:n},(_,id)=>({id,kind:type==='books'?'book':'jar',rank:id,w:44,h:type==='books'?102+id*19:122}));r.order=shuffle(r.items.map(p=>p.id),R);if(level===1)r.order=[0,2,1,3,4];if(r.order.every((v,i)=>v===i)||r.order.every((v,i)=>v===n-1-i))[r.order[1],r.order[2]]=[r.order[2],r.order[1]];r.par=Math.max(1,n-Math.max(lis(r.order),lis([...r.order].reverse())))}
 else if(type==='drawer'){const large=level>=11,medium=level>=5;r.cols=large?5:4;r.rows=medium?4:3;r.title=large?'The creative drawer':medium?'Tea for a quiet afternoon':'The little desk drawer';r.subtitle='Everything inside. Nothing overlaps.';let pieces=large?[['notebook',2,2],['cup',2,2],['pens',3,1],['scissors',2,1],['spoon',1,2],['tea',2,1],['stamp',1,1],['ink',1,1],['lemon',1,1]]:[['notebook',2,2],['pens',2,1],['stamp',1,1],['ink',1,1],['spool',1,2],['spoon',1,2]];if(medium&&!large)pieces.push(['tea',2,1],['envelope',2,1]);r.items=pieces.map(([kind,cols,rows],id)=>({id,kind,cols,rows,rot:cols===rows?0:Math.floor(R()*2),gx:-1,gy:-1,w:cols*58-8,h:rows*58-8}));r.solution=solvePacking(r.items,r.cols,r.rows,false);if(!r.solution)throw Error('Generated drawer has no solution');r.par=r.items.length+Math.floor(r.items.length/3)}
 else{const groups=level<10?2:3;r.title=['A little porcelain','Sunday tea plates','The supper cupboard'][Math.floor(level/5)%3];r.subtitle='Match the rims. Nest big to small.';r.groups=groups;r.stacks=Array.from({length:groups},()=>[]);for(let g=0;g<groups;g++)for(let k=0;k<3;k++){const id=r.items.length;r.items.push({id,kind:'plate',group:g,rank:k,radius:62-k*14,w:(62-k*14)*2,h:(62-k*14)*1.4,well:-1})}r.order=shuffle(r.items.map(p=>p.id),R);r.par=r.items.length}
 return r;
}
function lis(arr){const a=[];for(const v of arr){let k=0;while(k<a.length&&a[k]<v)k++;a[k]=v}return a.length}
function storage(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s?.version===1&&Array.isArray(s.meta?.photos)){meta={...meta,...s.meta};const r=s.round;if(r&&sequence.includes(r.type)&&Number.isInteger(r.level)&&Array.isArray(r.items)&&r.items.length>=5&&r.items.length<=9&&r.items.every(p=>Number.isInteger(p.id)))round=r}}catch{}}
function save(){try{localStorage.setItem(KEY,JSON.stringify({version:1,meta,round}))}catch{}}
function active(){return phase==='play'&&!document.hidden&&$('collection').hidden&&$('guide').hidden}
function snapshot(){return JSON.stringify({order:round.order,stacks:round.stacks,items:round.items.map(p=>({id:p.id,rot:p.rot,gx:p.gx,gy:p.gy,well:p.well})),moves:round.moves})}
function remember(){history.push(snapshot());if(history.length>80)history.shift()}
function undo(){if(!active()||!history.length||drag)return;const s=JSON.parse(history.pop());round.order=s.order;round.stacks=s.stacks;round.moves=s.moves;s.items.forEach(a=>Object.assign(round.items[a.id],a));hint=null;selected=-1;checkTime=0;note(230,.12,.03);hud();save()}
function sorted(){const values=round.order.map(id=>round.items[id].rank);return values.every((v,i)=>!i||v>values[i-1])||values.every((v,i)=>!i||v<values[i-1])}
function solved(){if(['books','jars'].includes(round.type))return sorted();if(round.type==='drawer')return round.items.every(p=>p.gx>=0);return round.items.every(p=>p.well===p.group)&&round.stacks.every(ids=>ids.every((id,i)=>!i||round.items[id].radius<round.items[ids[i-1]].radius))}
function readyCount(){if(['books','jars'].includes(round.type)){let best=0;for(const list of [round.order,[...round.order].reverse()])best=Math.max(best,list.filter((v,i)=>v===i).length);return best}return round.items.filter(p=>round.type==='drawer'?p.gx>=0:p.well>=0).length}
function hud(){$('day').textContent='RITUAL '+String(round.level).padStart(2,'0');$('title').textContent=round.title;$('subtitle').textContent=round.subtitle;$('count').textContent=readyCount()+' / '+round.items.length;$('turns').textContent=round.moves+' moves';$('total').textContent=meta.bank;$('undo').disabled=!history.length||phase!=='play'||!!drag;$('rotate').hidden=round.type!=='drawer';$('rotate').disabled=selected<0||phase!=='play';$('hint').disabled=phase!=='play'||!!drag;$('sound').setAttribute('aria-pressed',String(meta.sound));$('sound').style.opacity=meta.sound?1:.5}
function toast(text,d=2.8){$('toast').textContent=text;$('toast').classList.add('show');toastTime=d}
function audio(){if(!meta.sound)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume().catch(()=>{})}catch{}}
function note(f=450,d=.12,v=.04,type='sine',delay=0){if(!audioCtx||!meta.sound)return;try{const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime+delay;o.type=type;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(f*.76,t+d);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(v,t+.009);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+d+.02)}catch{}}
function clickSound(p){if(p.kind==='plate'||p.kind==='jar'||p.kind==='cup'){note(1030+p.id*44,.25,.026);note(1640,.12,.012,'sine',.02)}else{note(180+p.id*14,.09,.035,'triangle');note(330,.06,.016,'triangle',.025)}}
function chime(){[523.25,659.25,783.99,1046.5].forEach((f,i)=>note(f,.3,.036,'sine',i*.08))}
function burst(x,y,n=12){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,v=25+Math.random()*65;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v-20,life:.8+Math.random()*.5,color:['#d5ae6c','#faf0cd','#b0bd99','#cda18d'][i%4]})}}
function pet(){mood=3;meta.pets++;note(130,.45,.018,'triangle');note(190,.35,.014,'sine',.12);burst(layoutData.cat.x,layoutData.cat.y-30,8);save()}
function resize(){W=innerWidth;H=innerHeight;DPR=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*DPR);canvas.height=Math.round(H*DPR);world.landscape=H<520&&W>600;world.w=world.landscape?720:420;world.h=world.landscape?310:round.type==='drawer'&&H<720?440:480;const leftWidth=world.landscape?W-195:W,top=$('caption').getBoundingClientRect().bottom+14,bottom=world.landscape?H-12:$('buttons')?.getBoundingClientRect().top||document.querySelector('footer').getBoundingClientRect().top-8,space=Math.max(120,bottom-top-12);world.s=Math.min(1.3,(leftWidth-18)/world.w,space/world.h);world.x=(leftWidth-world.w*world.s)/2;world.y=top+(space-world.h*world.s)/2;setupPositions();drag=null;round.items.forEach(p=>{const q=position(p);p.dx=q.x;p.dy=q.y;p.ds=q.scale;p.da=(p.rot||0)*Math.PI/2})}
function setupPositions(){const L=world.landscape;layoutData.cat=L?{x:world.w-50,y:45,s:.43}:{x:351,y:47,s:.5};layoutData.plant=L?{x:52,y:217,s:.62}:{x:43,y:327,s:.55};layoutData.cup=L?{x:640,y:273,s:.62}:{x:337,y:407,s:.8};if(['books','jars'].includes(round.type)){const n=round.items.length,pitch=L?62:60,base=L?235:292;layoutData.slots=Array.from({length:n},(_,i)=>({x:world.w/2+(i-(n-1)/2)*pitch,y:base}));layoutData.shelf={x:layoutData.slots[0].x-31,y:base,w:(n-1)*pitch+62}}
 else if(round.type==='drawer'){const cell=L?58:round.cols===5?54:58;layoutData.tray={x:L?365:(world.w-round.cols*cell)/2,y:L?36:world.h===440?34:64,cell,cols:round.cols,rows:round.rows};const n=round.items.length,cols=L?3:3,rows=Math.ceil(n/cols),start=L?120:world.h===440?310:round.rows===4?319:334,dy=L?(rows===3?76:106):(rows===3?(world.h===440?57:65):95);layoutData.homes=round.items.map((p,i)=>({x:L?67+(i%cols)*107:70+(i%cols)*140,y:start+Math.floor(i/cols)*dy,scale:n>8?.52:n>6?.57:.65}));if(L)layoutData.cat={x:77,y:41,s:.38};else layoutData.cat={x:360,y:30,s:.38}}
 else{layoutData.wells=Array.from({length:round.groups},(_,i)=>({x:L?(round.groups===3?392+i*128:450+i*145):world.w/2+(i-(round.groups-1)/2)*(round.groups===2?168:140),y:L?145:122}));const rows=Math.ceil(round.items.length/3);layoutData.homes=round.order.map((id,i)=>({id,x:L?60+(i%3)*111:70+(i%3)*140,y:L?(rows===3?67:112)+Math.floor(i/3)*(rows===3?81:115):(rows===3?244:310)+Math.floor(i/3)*(rows===3?91:103),scale:.7}));if(L)layoutData.cat={x:world.w-34,y:40,s:.33};else layoutData.cat={x:365,y:45,s:.34}}
}
function position(p,preview=null){if(['books','jars'].includes(round.type)){const order=preview||round.order,slot=layoutData.slots[order.indexOf(p.id)];return{x:slot.x,y:slot.y-p.h/2,scale:1}}if(round.type==='drawer'){if(p.gx>=0){const t=layoutData.tray,[w,h]=dimensions(p);return{x:t.x+(p.gx+w/2)*t.cell,y:t.y+(p.gy+h/2)*t.cell,scale:t.cell/58}}return layoutData.homes[p.id]}if(p.well>=0){const slot=layoutData.wells[p.well],i=round.stacks[p.well].indexOf(p.id);return{x:slot.x,y:slot.y-i*10,scale:1}}return layoutData.homes.find(a=>a.id===p.id)}
function scenePoint(clientX,clientY){return{x:(clientX-world.x)/world.s,y:(clientY-world.y)/world.s}}
function screenPoint(x,y){return{x:world.x+x*world.s,y:world.y+y*world.s}}
function pick(x,y){let best=-1,dist=Infinity;const items=[...round.items];if(round.type==='plates')items.sort((a,b)=>(a.well>=0?round.stacks[a.well].indexOf(a.id):0)-(b.well>=0?round.stacks[b.well].indexOf(b.id):0));for(const p of items){if(round.type==='plates'&&p.well>=0&&round.stacks[p.well].at(-1)!==p.id)continue;const scale=p.ds??position(p).scale,a=(p.rot||0)*Math.PI/2,dx=x-p.dx,dy=y-p.dy,lx=(dx*Math.cos(a)+dy*Math.sin(a))/scale,ly=(-dx*Math.sin(a)+dy*Math.cos(a))/scale;const hw=Math.max(p.w/2+4,28/world.s/scale),hh=Math.max(p.h/2+4,23/world.s/scale);if(Math.abs(lx)<hw&&Math.abs(ly)<hh){const score=dx*dx+dy*dy;if(score<=dist){best=p.id;dist=score}}}return best}
function freeCell(p,gx,gy,rot=p.rot){const t=layoutData.tray,[w,h]=rot%2?[p.rows,p.cols]:[p.cols,p.rows];if(gx<0||gy<0||gx+w>round.cols||gy+h>round.rows)return false;for(const other of round.items){if(other.id===p.id||other.gx<0)continue;const [ow,oh]=dimensions(other);if(gx<other.gx+ow&&gx+w>other.gx&&gy<other.gy+oh&&gy+h>other.gy)return false}return true}
function nearestCell(p,x,y){const t=layoutData.tray,[w,h]=dimensions(p);return{gx:Math.round((x-t.x)/t.cell-w/2),gy:Math.round((y-t.y)/t.cell-h/2)}}
function previewOrder(id,x){const old=round.order.filter(v=>v!==id),slots=layoutData.slots;let index=0,dist=Infinity;slots.forEach((p,i)=>{if(Math.abs(p.x-x)<dist){dist=Math.abs(p.x-x);index=i}});old.splice(index,0,id);return old}
function move(id,x,y){const p=round.items[id];if(!p||!active())return false;let changed=false;if(['books','jars'].includes(round.type)){const order=previewOrder(id,x);if(JSON.stringify(order)!==JSON.stringify(round.order)){remember();round.order=order;changed=true}}
 else if(round.type==='drawer'){const t=layoutData.tray;if(x>t.x-30&&x<t.x+round.cols*t.cell+30&&y>t.y-30&&y<t.y+round.rows*t.cell+30){const a=nearestCell(p,x,y);if(freeCell(p,a.gx,a.gy)){if(p.gx!==a.gx||p.gy!==a.gy){remember();p.gx=a.gx;p.gy=a.gy;changed=true}}else{toast('A little more room needed.');note(160,.15,.018,'triangle')}}else if(p.gx>=0){remember();p.gx=-1;p.gy=-1;changed=true}}
 else{if(p.well>=0&&round.stacks[p.well].at(-1)!==id)return false;let index=-1,dist=Infinity;layoutData.wells.forEach((s,i)=>{const d=Math.hypot(x-s.x,y-s.y);if(d<76&&d<dist){index=i;dist=d}});if(index>=0){const stack=round.stacks[index],top=stack.at(-1);if(index!==p.group){toast('Match the little rim pattern.');note(190,.12,.015)}else if(top!==id&&top!==undefined&&round.items[top].radius<=p.radius){toast('Big underneath. Little on top.');note(190,.12,.015)}else if(p.well!==index){remember();if(p.well>=0)round.stacks[p.well].pop();round.stacks[index].push(id);p.well=index;changed=true}}else if(p.well>=0){remember();round.stacks[p.well].pop();p.well=-1;changed=true}}
 if(changed){round.moves++;hint=null;const q=position(p);burst(q.x,q.y,5);clickSound(p);if(navigator.vibrate)try{navigator.vibrate(7)}catch{}checkTime=0;hud();save()}return changed}
function rotate(){if(!active()||round.type!=='drawer'||selected<0)return;const p=round.items[selected],rot=(p.rot+1)%4;if(p.gx>=0&&!freeCell(p,p.gx,p.gy,rot)){toast('Lift this item before turning it.');return}remember();p.rot=rot;round.moves++;hint=null;checkTime=0;note(310,.09,.03,'triangle');hud();save()}
function showHint(){if(!active()||drag)return;round.hints++;if(['books','jars'].includes(round.type)){const asc=round.items.map(p=>p.id),desc=[...asc].reverse();const score=o=>o.filter((v,i)=>v===round.order[i]).length,target=score(asc)>=score(desc)?asc:desc;const index=round.order.findIndex((v,i)=>v!==target[i]);if(index<0)return;const id=target[index],slot=layoutData.slots[index],p=round.items[id];hint={id,x:slot.x,y:slot.y-p.h/2,rot:0,life:10};selected=id;toast('This one has a lovely place here.');}
 else if(round.type==='drawer'){let solution=solvePacking(round.items,round.cols,round.rows,true),a;if(solution)a=solution.find(a=>round.items[a.id].gx<0);else{solution=solvePacking(round.items,round.cols,round.rows,false);a=solution.find(a=>{const p=round.items[a.id];return p.gx!==a.x||p.gy!==a.y||(p.rot%2)!==a.rot})}if(!a)return;const p=round.items[a.id],t=layoutData.tray,[w,h]=a.rot?[p.rows,p.cols]:[p.cols,p.rows];selected=a.id;hint={id:a.id,x:t.x+(a.x+w/2)*t.cell,y:t.y+(a.y+h/2)*t.cell,rot:a.rot,life:12};toast(p.rot%2!==a.rot?'Turn this one, then follow the outline.':'Try this little arrangement.');}
 else{let p;for(let g=0;g<round.groups;g++){const free=round.items.filter(p=>p.group===g&&p.well<0).sort((a,b)=>b.radius-a.radius);if(!free.length)continue;const top=round.stacks[g].at(-1);if(top!==undefined&&round.items[top].radius<free[0].radius){p=round.items[top];const q=layoutData.homes.find(a=>a.id===p.id);hint={id:p.id,x:q.x,y:q.y,rot:0,life:10};toast('Lift the little plate to make room.')}else{p=free[0];const q=layoutData.wells[g];hint={id:p.id,x:q.x,y:q.y,rot:0,life:10};toast('Start with the biggest plate.')}break}if(p)selected=p.id}
 hud();save();note(640,.2,.025)
}
canvas.addEventListener('pointerdown',e=>{audio();if(!active())return;const q=scenePoint(e.clientX,e.clientY),cat=layoutData.cat;if(Math.hypot(q.x-cat.x,q.y-cat.y)<51*cat.s){pet();return}const id=pick(q.x,q.y);if(id<0){if(selected>=0){move(selected,q.x,q.y);selected=-1;hud()}return}const p=round.items[id];drag={id,startX:q.x,startY:q.y,x:p.dx,y:p.dy,offsetX:q.x-p.dx,offsetY:q.y-p.dy,moved:false,previous:selected,tilt:0};selected=id;canvas.setPointerCapture(e.pointerId);note(210,.07,.016,'triangle');hud()});
canvas.addEventListener('contextmenu',e=>e.preventDefault());
canvas.addEventListener('pointermove',e=>{if(!drag||!active())return;const q=scenePoint(e.clientX,e.clientY),d=drag;d.moved||=Math.hypot(q.x-d.startX,q.y-d.startY)>7;d.tilt=Math.max(-.12,Math.min(.12,(q.x-d.offsetX-d.x)*.005));d.x=q.x-d.offsetX;d.y=q.y-d.offsetY;if(d.moved&&time-slideTick>.15){slideTick=time;note(100+Math.random()*50,.045,.006,'triangle')}});
canvas.addEventListener('pointerup',e=>{if(!drag)return;const d=drag,q=scenePoint(e.clientX,e.clientY);drag=null;if(active()){if(d.moved){const changed=move(d.id,d.x,d.y);selected=changed?-1:d.id}else if(d.previous>=0&&d.previous!==d.id&&(['books','jars'].includes(round.type)||(round.type==='plates'&&round.items[d.id].well>=0))){selected=d.previous;if(move(d.previous,q.x,q.y))selected=-1}else selected=d.id}if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);hud()});canvas.addEventListener('pointercancel',()=>{drag=null;hud()});canvas.addEventListener('lostpointercapture',()=>{if(drag){drag=null;hud()}});
function scene(c){const L=world.landscape;if(round.type==='books'||round.type==='jars'){const s=layoutData.shelf;A.rr(c,s.x-4,s.y-218,s.w+8,222,4,'#ede2ca55');A.shelf(c,s.x,s.y,s.w);A.plant(c,layoutData.plant.x,layoutData.plant.y,layoutData.plant.s);A.cup(c,layoutData.cup.x,layoutData.cup.y,layoutData.cup.s,time);const x=L?255:112,y=L?278:421;A.rr(c,x-40,y-17,80,35,2,'#e6d5b4','#bba88a');A.line(c,[[x,y-15],[x,y+15]],'#b6a082',1);for(let i=0;i<4;i++){A.line(c,[[x-31,y-9+i*6],[x-7,y-9+i*6]],'#c2ac8b',1);A.line(c,[[x+7,y-9+i*6],[x+31,y-9+i*6]],'#c2ac8b',1)}}
 else if(round.type==='drawer'){const t=layoutData.tray;A.tray(c,t.x,t.y,round.cols,round.rows,t.cell);if(!round.completed){const y=L?72:round.rows===4?298:303;A.line(c,L?[[18,y],[327,y]]:[[28,y],[392,y]],'#b6a08255',1);c.fillStyle='#a28d72';c.font='8px Trebuchet MS';c.textAlign='center';/* the linen edge keeps the staging area quiet */}if(!L){A.leaf(c,36,129,.6,'#a8b393',-.6);A.leaf(c,25,114,.6,'#94a786',-.9)}else A.plant(c,669,269,.48)}
 else{for(let g=0;g<round.groups;g++){const p=layoutData.wells[g];const radius=L&&round.groups===3?62:71;A.ell(c,p.x,p.y+8,radius+1,radius*.74,'#c3b69a22');A.ell(c,p.x,p.y,radius,radius*.69,'#e8dfca','#b5a58a');A.ell(c,p.x,p.y,radius-4,radius*.63,null,A.colors[g]);if(!round.stacks[g].length){c.save();c.globalAlpha=.35;if(g%3===0){A.leaf(c,p.x,p.y+10,.9,A.colors[g],-.4);A.leaf(c,p.x+5,p.y+12,.65,A.colors[g],.5)}else if(g%3===1)A.flower(c,p.x,p.y,2,A.colors[g]);else{A.star(c,p.x,p.y,13,A.colors[g]);A.ell(c,p.x,p.y,20,13,null,A.colors[g])}c.restore()}}A.line(c,L?[[328,42],[328,283]]:[[25,208],[395,208]],'#b5a18055',1);}
 if(hint){const p=round.items[hint.id],q=position(p);c.save();c.globalAlpha=.16;A.item(c,p,hint.x,hint.y,hint.rot*Math.PI/2,0,false);c.restore();c.save();c.strokeStyle='#b79766';c.lineWidth=1.5;c.setLineDash([4,4]);c.beginPath();c.moveTo(p.dx,p.dy);c.quadraticCurveTo((p.dx+hint.x)/2,(p.dy+hint.y)/2-26,hint.x,hint.y);c.stroke();c.setLineDash([]);A.star(c,hint.x,hint.y,5,'#c8a164');c.restore()}
 const ordered=[...round.items];if(round.type==='plates')ordered.sort((a,b)=>(a.well>=0?round.stacks[a.well].indexOf(a.id)+10:0)-(b.well>=0?round.stacks[b.well].indexOf(b.id)+10:0));for(const p of ordered){if(drag?.id===p.id)continue;c.save();c.translate(p.dx,p.dy);c.scale(p.ds,p.ds);A.item(c,p,0,0,p.da,0,selected===p.id);c.restore()}
 const cat=layoutData.cat;A.cat(c,cat.x,cat.y,cat.s,time,mood,ribbonColors[meta.ribbon]);
 if(drag){const p=round.items[drag.id];if(round.type==='drawer'){const t=layoutData.tray,a=nearestCell(p,drag.x,drag.y),[w,h]=dimensions(p);if(a.gx>=0&&a.gy>=0&&a.gx+w<=round.cols&&a.gy+h<=round.rows){A.rr(c,t.x+a.gx*t.cell+2,t.y+a.gy*t.cell+2,w*t.cell-4,h*t.cell-4,5,freeCell(p,a.gx,a.gy)?'#aabd8b70':'#cc9b8970')}}if(round.type==='plates'){for(let i=0;i<layoutData.wells.length;i++){const well=layoutData.wells[i];if(Math.hypot(drag.x-well.x,drag.y-well.y)<76){const top=round.stacks[i].at(-1),valid=i===p.group&&(top===undefined||top===p.id||round.items[top].radius>p.radius);A.ell(c,well.x,well.y,75,52,null,valid?'#93a97b':'#b98d7a');A.ell(c,well.x,well.y,72,50,valid?'#bfcca233':'#ddb3a233')}}}A.item(c,p,drag.x,drag.y,(p.rot||0)*Math.PI/2+drag.tilt,1,true)}
 for(const p of particles){c.globalAlpha=Math.min(1,p.life/.3);A.star(c,p.x,p.y,3,p.color)}c.globalAlpha=1;
}
function photo(){const cv=$('memory'),c=cv.getContext('2d');c.setTransform(1,0,0,1,0,0);c.fillStyle='#e9dec9';c.fillRect(0,0,cv.width,cv.height);A.paper(c,0,0,cv.width,cv.height);const width=world.w,height=world.landscape?280:380,s=Math.min(320/width,220/height);c.save();c.translate((cv.width-width*s)/2,(cv.height-height*s)/2-(world.landscape?15:15)*s);c.scale(s,s);scene(c);c.restore();return cv.toDataURL('image/png')}
function finish(){if(round.completed)return;round.completed=true;selected=-1;hint=null;round.rating=round.hints===0&&round.moves<=round.par+3?3:round.hints<=2?2:1;meta.bank+=round.rating;meta.earned+=round.rating;meta.completed=Math.max(meta.completed,round.level);phase='complete';mood=4;chime();round.memory=photo();if(round.level<=12&&!meta.photos.some(p=>p.level===round.level))meta.photos.push({level:round.level,title:round.title,src:round.memory});save();showResult();hud()}
function showResult(){$('complete').hidden=false;$('rating').innerHTML=Array.from({length:3},(_,i)=>'<span'+(i>=round.rating?' class="dim"':'')+'>✦</span>').join(' ');$('result-title').textContent=round.type==='drawer'?'A perfect little fit.':round.type==='plates'?'A lovely little nest.':'Everything in its place.';$('reward').textContent='+'+round.rating+' stars · '+round.moves+' moves · Miso approves.';if(round.memory){const im=new Image();im.onload=()=>{const c=$('memory').getContext('2d');c.clearRect(0,0,340,240);c.drawImage(im,0,0,340,240)};im.src=round.memory}else photo()}
function next(){round=make(round.level+1);history=[];hint=null;selected=-1;drag=null;particles=[];checkTime=0;phase='play';$('complete').hidden=true;hud();resize();save();note(520,.17,.024)}
function gallery(){const wrap=$('memories');wrap.replaceChildren();for(let i=1;i<=12;i++){const p=meta.photos.find(p=>p.level===i),div=document.createElement('div');div.className='keepsake'+(p?'':' locked');if(p){const im=document.createElement('img');im.src=p.src;im.alt=p.title;div.append(im)}else{const d=document.createElement('div');d.textContent='✿';div.append(d)}const label=document.createElement('small');label.textContent=p?p.title:'Ritual '+String(i).padStart(2,'0');div.append(label);wrap.append(div)}ribbons();$('collection').hidden=false}
function ribbons(){const wrap=$('ribbons');wrap.replaceChildren();for(let i=0;i<4;i++){const b=document.createElement('button');b.className='ribbon'+(meta.ribbon===i?' selected':'');b.style.setProperty('--ribbon',ribbonColors[i]);b.innerHTML='<i></i>'+ribbonNames[i]+'<small>'+(meta.ribbon===i?'Wearing':meta.owned.includes(i)?'Wear':'✦ '+costs[i])+'</small>';b.onclick=()=>{audio();if(meta.owned.includes(i))meta.ribbon=i;else if(meta.bank>=costs[i]){meta.bank-=costs[i];meta.owned.push(i);meta.ribbon=i}else{toast('A few more quiet moments first.');return}mood=3;note(720,.25,.028);save();hud();ribbons()};tapAction(b,b.onclick);wrap.append(b)}}
$('start').onclick=()=>{audio();$('intro').hidden=true;if(round.completed){phase='complete';showResult()}else{phase='play';if(round.level===1)toast('Drag a book along the shelf.')}hud()};$('undo').onclick=()=>{audio();undo()};$('rotate').onclick=()=>{audio();rotate()};$('hint').onclick=()=>{audio();showHint()};$('next').onclick=()=>{audio();next()};$('sound').onclick=()=>{meta.sound=!meta.sound;audio();hud();save()};$('album').onclick=gallery;$('close-album').onclick=()=>{$('collection').hidden=true};$('help').onclick=()=>{$('guide').hidden=false};$('close-help').onclick=()=>{$('guide').hidden=true};
addEventListener('resize',resize);addEventListener('pagehide',save);document.addEventListener('visibilitychange',()=>{drag=null;last=0;acc=0;save();if(audioCtx){if(document.hidden)audioCtx.suspend().catch(()=>{});else if(meta.sound)audioCtx.resume().catch(()=>{})}});document.addEventListener('keydown',e=>{if(!active())return;audio();if(e.key.toLowerCase()==='r')rotate();if(e.key.toLowerCase()==='z')undo();if(e.key.toLowerCase()==='h')showHint();if(e.key==='Escape'){selected=-1;hint=null;hud()}});
function step(dt){time+=dt;toastTime-=dt;if(toastTime<=0)$('toast').classList.remove('show');mood=Math.max(0,mood-dt);if(!active())return;if(hint){hint.life-=dt;if(hint.life<=0)hint=null}const preview=drag?.moved&&['books','jars'].includes(round.type)?previewOrder(drag.id,drag.x):null;for(const p of round.items){const q=position(p,preview),k=Math.min(1,dt*14);p.dx+=(q.x-p.dx)*k;p.dy+=(q.y-p.dy)*k;p.ds+=(q.scale-p.ds)*k;p.da+=((p.rot||0)*Math.PI/2-p.da)*k}for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=25*dt;if(p.life<=0)particles.splice(i,1)}if(!drag&&solved()){if(checkTime===0){mood=3;for(const p of round.items)burst(p.dx,p.dy,8);note(660,.3,.028)}checkTime+=dt;if(checkTime>.9)finish()}else checkTime=0}
function render(){ctx.setTransform(DPR,0,0,DPR,0,0);A.backdrop(ctx,W,H,time);ctx.save();ctx.translate(world.x,world.y);ctx.scale(world.s,world.s);scene(ctx);ctx.restore()}
function frame(now){requestAnimationFrame(frame);if(document.hidden){last=0;return}if(!last)last=now;acc+=Math.min(.08,(now-last)/1000);last=now;while(acc>=.02){step(.02);acc-=.02}if(now-paint>=(W<600?1000/30:1000/60)-1){render();paint=now}}
function tapAction(button,action){let pressed=null,lastPointer=-1000;button.addEventListener('pointerdown',e=>{if(!button.disabled&&e.button===0)pressed=e.pointerId});button.addEventListener('pointercancel',()=>{pressed=null});button.addEventListener('pointerup',e=>{if(pressed!==e.pointerId)return;pressed=null;lastPointer=performance.now();e.preventDefault();const box=button.getBoundingClientRect();if(!button.disabled&&e.clientX>=box.left&&e.clientX<=box.right&&e.clientY>=box.top&&e.clientY<=box.bottom)action(e)});button.onclick=e=>{if(e.detail!==0&&performance.now()-lastPointer<750)return;action(e)}}
for(const id of ['start','undo','rotate','hint','next','sound','album','close-album','help','close-help'])tapAction($(id),$(id).onclick);
storage();if(!round)round=make(1);hud();resize();A.welcome($('welcome-art').getContext('2d'));if(round.moves||meta.completed)$('start').textContent='Welcome back';requestAnimationFrame(frame);
window.__tidy={build:'1.0.0',get round(){return round},get meta(){return meta},get world(){return world},get layout(){return layoutData},get phase(){return phase},get selected(){return selected},get audioState(){return audioCtx?.state||'not-started'},get drag(){return drag},make,solvePacking,screenPoint,position,dimensions,solved};
})();
