import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {Reflector} from 'three/addons/objects/Reflector.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
const $=s=>document.querySelector(s), scene=new THREE.Scene();
scene.background=new THREE.Color('#080910');scene.fog=new THREE.FogExp2('#080910',.055);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;$('#stage').append(renderer.domElement);
const camera=new THREE.PerspectiveCamera(37,innerWidth/innerHeight,.05,100);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=3;controls.maxDistance=10;controls.maxPolarAngle=Math.PI*.49;controls.target.set(0,1.1,0);controls.autoRotateSpeed=.6;
function reset(){camera.position.set(0,2.05,innerWidth<700?9.6:6.9);controls.target.set(0,innerWidth<700?.72:1.12,0);controls.update()}reset();
scene.add(new THREE.HemisphereLight(0xece2ff,0x302035,2));const key=new THREE.DirectionalLight(0xffe6df,3);key.position.set(2,4,4);scene.add(key);
const palette={rose:[0xff367a,0x8e8fff],blue:[0x38beff,0x8875ff],gold:[0xffb856,0xff666e]};let colors=palette.rose;
const stage=new THREE.Mesh(new THREE.CylinderGeometry(2.5,2.65,.16,128),new THREE.MeshStandardMaterial({color:0x111321,metalness:.8,roughness:.22}));stage.position.y=-.13;scene.add(stage);
const mirror=new Reflector(new THREE.CircleGeometry(2.48,128),{clipBias:.003,textureWidth:Math.min(innerWidth,1200),textureHeight:Math.min(innerHeight,1000),color:0x777080});mirror.rotation.x=-Math.PI/2;mirror.position.y=-.04;scene.add(mirror);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.MeshStandardMaterial({color:0x080910,roughness:.35,metalness:.6}));floor.rotation.x=-Math.PI/2;floor.position.y=-.22;scene.add(floor);
const accents=[],beams=[];
function emissive(color,intensity=2){return new THREE.MeshBasicMaterial({color:new THREE.Color(color).multiplyScalar(intensity)})}
for(const radius of [2.5,2.6]){const m=new THREE.Mesh(new THREE.TorusGeometry(radius,.012,8,180),emissive(colors[0]));m.rotation.x=Math.PI/2;m.position.y=-.04;scene.add(m);accents.push(m)}
const halo=new THREE.Group();halo.position.set(0,1.9,-2);scene.add(halo);
for(const r of [1.72,1.85]){let m=new THREE.Mesh(new THREE.TorusGeometry(r,.014,8,180),emissive(colors[0],2));halo.add(m);accents.push(m)}
for(let i=0;i<64;i++){let a=i/64*Math.PI*2;let m=new THREE.Mesh(new THREE.BoxGeometry(.018,i%4===0?.16:.055,.022),emissive(colors[1],1.5));m.position.set(Math.sin(a)*1.98,Math.cos(a)*1.98,0);m.rotation.z=-a;halo.add(m)}
for(let i=0;i<8;i++){let x=(i-3.5)*.86;let bar=new THREE.Mesh(new THREE.BoxGeometry(.018,2.8,.025),emissive(i%2?colors[0]:colors[1],1.3));bar.position.set(x,1.5,-3.3);scene.add(bar);accents.push(bar)}
for(let i=0;i<6;i++){const pivot=new THREE.Group();pivot.position.set((i%3-1)*2.3,4.5,-1.5-Math.floor(i/3)*1.5);scene.add(pivot);const geo=new THREE.ConeGeometry(.7,4.8,32,1,true);geo.translate(0,-2.4,0);const mat=new THREE.ShaderMaterial({uniforms:{tint:{value:new THREE.Color(colors[i%2])}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform vec3 tint;varying vec2 vUv;void main(){float a=pow(sin(vUv.x*3.14159),2.)*.045*vUv.y;gl_FragColor=vec4(tint,a);}',transparent:true,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending});const beam=new THREE.Mesh(geo,mat);pivot.add(beam);beams.push(pivot);const lamp=new THREE.PointLight(colors[i%2],4,7);lamp.position.copy(pivot.position);scene.add(lamp)}
const count=420,pos=new Float32Array(count*3);for(let i=0;i<count;i++){pos[i*3]=(Math.random()-.5)*13;pos[i*3+1]=Math.random()*7;pos[i*3+2]=(Math.random()-.5)*10}const pg=new THREE.BufferGeometry();pg.setAttribute('position',new THREE.BufferAttribute(pos,3));const particles=new THREE.Points(pg,new THREE.PointsMaterial({color:0xfacbdf,size:.014,transparent:true,opacity:.65,depthWrite:false,blending:THREE.AdditiveBlending}));scene.add(particles);
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.42,.45,1.05));composer.addPass(new OutputPass());
let mixer,actions=[],duration=12.3,playing=true,elapsed=0,model;const clock=new THREE.Clock();
const audio=$('#bgm');let soundEnabled=false;audio.volume=.7;async function startAudio(){try{audio.playbackRate=Number($('#speed').value);await audio.play()}catch{soundEnabled=false;$('#sound').textContent='Sound · Off';$('#sound').setAttribute('aria-label','Enable background music')}}
$('#sound').onclick=async()=>{soundEnabled=!soundEnabled;if(soundEnabled){if(audio.duration)audio.currentTime=elapsed%audio.duration;if(playing)await startAudio()}else audio.pause();$('#sound').textContent=soundEnabled?'Sound · On':'Sound · Off';$('#sound').setAttribute('aria-label',soundEnabled?'Mute background music':'Enable background music')};$('#speed').onchange=()=>audio.playbackRate=Number($('#speed').value);

async function modelData(){let received=0;const parts=await Promise.all(["dancer-0.bin","dancer-1.bin","dancer-2.bin","dancer-3.bin","dancer-4.bin","dancer-5.bin","dancer-6.bin","dancer-7.bin","dancer-8.bin"].map(async name=>{const r=await fetch('./'+name);if(!r.ok)throw Error('Model download failed');const data=await r.arrayBuffer();received+=data.byteLength;$('#loadbar').value=received/67420344*100;$('#loadtext').textContent='Loading dancer and choreography… '+Math.round(received/67420344*100)+'%';return data}));const merged=new Uint8Array(received);let offset=0;for(const part of parts){merged.set(new Uint8Array(part),offset);offset+=part.byteLength}return merged.buffer}
let assetData;try{assetData=await modelData()}catch(e){$('#loading h2').textContent='Unable to load the dancer';$('#loadtext').textContent='Please refresh to try again.';throw e}
new GLTFLoader().parse(assetData,'./',g=>{model=g.scene;let visibleMeshes=0;model.traverse(o=>{if(!o.isMesh)return;const mats=Array.isArray(o.material)?o.material:[o.material];if(mats.every(m=>m.name.startsWith('mmd_tools'))){o.visible=false;return}visibleMeshes++;o.frustumCulled=false;mats.forEach(m=>{m.side=THREE.DoubleSide;if(m.transparent){m.alphaTest=.035;m.depthWrite=true}})});scene.add(model);model.updateMatrixWorld(true);const box=new THREE.Box3();model.traverse(o=>{if(o.isMesh&&o.visible)box.expandByObject(o)});const size=box.getSize(new THREE.Vector3());const scale=2.25/size.y;model.scale.multiplyScalar(scale);model.position.y=-box.min.y*scale;model.position.x=-(box.min.x+box.max.x)*.5*scale;model.position.z=-(box.min.z+box.max.z)*.5*scale;mixer=new THREE.AnimationMixer(model);duration=Math.max(...g.animations.map(c=>c.duration));actions=g.animations.map(c=>{const a=mixer.clipAction(c);a.play();return a});$('#seek').max=duration;$('#seek').disabled=false;$('#play').disabled=false;$('#loading').classList.add('done');$('#loading').setAttribute('aria-hidden','true');window.stageInfo={animations:g.animations.map(c=>c.name),duration,visibleMeshes,modelHeight:size.y,ready:true};},e=>{$('#loading h2').textContent='Unable to load the dancer';$('#loadtext').textContent='Model parsing failed. Please refresh to try again.';console.error(e)});
function fmt(n){return `00:${Math.floor(n).toString().padStart(2,'0')}`}
$('#play').onclick=()=>{playing=!playing;if(soundEnabled){if(playing)startAudio();else audio.pause()}$('#play').textContent=playing?'Ⅱ':'▶';$('#play').setAttribute('aria-label',playing?'Pause dance':'Play dance')};$('#seek').oninput=e=>{elapsed=Number(e.target.value);mixer?.setTime(elapsed);if(audio.duration)audio.currentTime=elapsed%audio.duration};$('#reset').onclick=reset;$('#camera').onclick=()=>{controls.autoRotate=!controls.autoRotate;$('#camera').textContent=`Orbit · ${controls.autoRotate?'On':'Off'}`};$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{ $('#fullscreen').textContent='Use browser fullscreen'}};
document.querySelectorAll('[data-look]').forEach(b=>b.onclick=()=>{colors=palette[b.dataset.look];document.querySelectorAll('[data-look]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});accents.forEach((m,i)=>m.material.color.set(colors[i%2]).multiplyScalar(2));beams.forEach((p,i)=>p.children[0].material.uniforms.tint.value.set(colors[i%2]));particles.material.color.set(colors[0])});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight)});
renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05),t=clock.elapsedTime;if(mixer&&playing){elapsed=soundEnabled&&!audio.paused?audio.currentTime%duration:(elapsed+dt*Number($('#speed').value))%duration;mixer.setTime(elapsed);$('#seek').value=elapsed}$('#time').textContent=`${fmt(elapsed)} / ${fmt(duration)}`;beams.forEach((p,i)=>{p.rotation.z=Math.sin(t*.32+i*1.5)*.42;p.rotation.x=Math.sin(t*.25+i)*.32});particles.rotation.y=t*.018;controls.update();composer.render()});
