'use strict';
(()=>{
const $=id=>document.getElementById(id),stage=$('stage'),canvas=$('art'),ctx=canvas.getContext('2d'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const palettes=[
 {name:'Peach Picnic',bg:'#f4eadb',ink:'#55423b',soft:'#a18b7e',accent:'#dc7666',dark:'#b95b51',box:'#e99580',rim:'#fbc5ac',paper:'#fffaf0',line:'rgba(116,86,67,.12)'},
 {name:'Mint Meadow',bg:'#e3eddf',ink:'#35534b',soft:'#789185',accent:'#5c9b82',dark:'#3c7865',box:'#82b79c',rim:'#bfddc3',paper:'#fbfff3',line:'rgba(69,106,83,.12)'},
 {name:'Sakura Day',bg:'#f4e4e8',ink:'#694551',soft:'#a38190',accent:'#cb789c',dark:'#a8567d',box:'#df94b0',rim:'#f4c4d6',paper:'#fff6f8',line:'rgba(133,71,103,.12)'},
 {name:'Blueberry Night',bg:'#272943',ink:'#f1e7d8',soft:'#afa7c7',accent:'#9b8cd1',dark:'#73659e',box:'#78709e',rim:'#a99cca',paper:'#393951',line:'rgba(216,205,245,.12)'},
 {name:'Honey Club',bg:'#f3e8c6',ink:'#695233',soft:'#a18b60',accent:'#c8a04f',dark:'#a97e2d',box:'#dfb66a',rim:'#f3d799',paper:'#fffbeb',line:'rgba(129,99,48,.12)'},
 {name:'Ocean Picnic',bg:'#dcebed',ink:'#375861',soft:'#7b969c',accent:'#5d9eae',dark:'#417c8d',box:'#7eb4c0',rim:'#b5d9dc',paper:'#f4fcf7',line:'rgba(53,102,113,.12)'}
];
const foods=[{name:'Rice Bear',base:'#fff0cf',light:'#fffbee',shade:'#e4c9a3',detail:'#b49775'}, {name:'Salmon Pal',base:'#f49779',light:'#ffb599',shade:'#d76957',detail:'#ffe1bd'}, {name:'Cucumber Cub',base:'#9cc788',light:'#c3e2a7',shade:'#6e9e67',detail:'#628a58'}, {name:'Egg Buddy',base:'#f6ce73',light:'#ffe7a2',shade:'#d4a543',detail:'#fff4ce'}, {name:'Berry Bun',base:'#baa4d7',light:'#dbc9ed',shade:'#927ab7',detail:'#f0dcfa'}, {name:'Peach Mochi',base:'#f1b5bb',light:'#ffd8d7',shade:'#d5919e',detail:'#ffe7e3'}];
let saved={};try{saved=JSON.parse(localStorage.getItem('bento-buddies-v1')||'{}')||{}}catch{}
let level=Math.max(1,Math.min(1000000,(Number(saved.level)||1)+(saved.completed?1:0))),clears=Math.max(0,Number(saved.clears)||0),theme=Math.max(0,Math.min(5,Number(saved.theme)||0)),sound=saved.sound!==false;
if(theme>=unlocked())theme=0;
let b,pos,selected=-1,drag=null,hover=null,hint=null,win=false,pendingWin=0,animations=[],particles=[],lidStart=0,lastTime=performance.now(),layout={},toastTimer,audioCtx=null,focusReturn=null;
const rnd=(a,z)=>a+Math.random()*(z-a),clamp=(v,a,z)=>Math.max(a,Math.min(z,v));
function unlocked(){return Math.min(6,1+Math.floor(clears/3))}
function save(){try{localStorage.setItem('bento-buddies-v1',JSON.stringify({level,clears,theme,sound,completed:win}))}catch{}}
function applyTheme(){const p=palettes[theme],root=document.documentElement.style;for(const[key,value]of Object.entries({bg:p.bg,ink:p.ink,soft:p.soft,accent:p.accent,'accent-dark':p.dark,box:p.box,rim:p.rim,paper:p.paper,line:p.line}))root.setProperty('--'+key,value);document.querySelector('meta[name=theme-color]').content=p.bg}
function chime(kind){if(!sound)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const notes=kind==='win'?[523.25,659.25,783.99,1046.5]:kind==='drop'?[523.25,659.25]:kind==='no'?[220,196]:[392];notes.forEach((hz,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime+i*.075;o.type='sine';o.frequency.value=hz;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.09,t+.008);g.gain.exponentialRampToValueAtTime(.001,t+.24);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+.25)})}catch{}}
function vibrate(ms){if(!reduced&&navigator.vibrate)navigator.vibrate(ms)}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2200)}
function update(){const n=pos.filter(Boolean).length;$('restart').disabled=win;$('hint').disabled=win;$('level').textContent=String(level).padStart(2,'0');$('packed').textContent=n+' / '+pos.length;$('clears').textContent=clears;$('stylecount').textContent=unlocked()+' / 6';$('dots').innerHTML=pos.map(p=>'<i class="'+(p?'on':'')+'"></i>').join('');$('sound').setAttribute('aria-pressed',String(sound));[...$('tray').children].forEach((el,i)=>{el.classList.toggle('chosen',selected===i);el.setAttribute('aria-pressed',String(selected===i));el.setAttribute('aria-label',foods[b.pieces[i].kind].name+(pos[i]?', packed. Select to move.':', select to pack.'))});[...$('targets').children].forEach((el,k)=>{const x=k%b.w,y=Math.floor(k/b.w),owner=pos.findIndex((p,i)=>p&&b.pieces[i].cells.some(c=>p[0]+c[0]===x&&p[1]+c[1]===y));el.setAttribute('aria-label',`Row ${y+1}, column ${x+1}${owner>=0?', '+foods[b.pieces[owner].kind].name:', empty'}`)})}
function start(){clearTimeout(pendingWin);$('win').hidden=true;win=false;drag=null;hover=null;hint=null;selected=-1;lidStart=0;particles=[];b=BentoPuzzle.make(level,BentoBoards);pos=b.pieces.map(()=>null);animations=b.pieces.map(()=>({time:0,kind:'pop'}));$('targets').replaceChildren();$('tray').replaceChildren();for(let k=0;k<b.w*b.h;k++){const el=document.createElement('button');el.className='cellbutton';el.dataset.cell=k;el.addEventListener('click',e=>{if(e.detail===0)cellAction(k%b.w,Math.floor(k/b.w))});$('targets').append(el)}b.pieces.forEach((p,i)=>{const el=document.createElement('button');el.className='foodbutton';el.dataset.piece=i;el.addEventListener('click',e=>{if(e.detail===0&&!win){selected=i;hint=null;update();toast('Choose a spot for '+foods[p.kind].name+'.')}});$('tray').append(el)});$('tip').textContent=level<=2?'Drag the buddies. Fill the box.':'A little puzzle. A happy little lunch.';measure();update()}
function measure(){const r=stage.getBoundingClientRect(),W=r.width,H=r.height,dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);let c,bx,by,slots=[];const landscape=W/H>1.5;if(landscape){c=Math.max(20,Math.min((H-48)/b.h,(W*.54-45)/b.w,66));bx=(W*.54-b.w*c)/2;by=(H-b.h*c)/2;const cols=2,rows=Math.ceil(b.pieces.length/cols),left=W*.57,cw=(W-left-12)/cols,ch=Math.min(83,(H-18)/rows);for(let i=0;i<b.pieces.length;i++)slots.push({x:left+(i%cols)*cw+4,y:(H-rows*ch)/2+Math.floor(i/cols)*ch+4,w:cw-8,h:ch-8})}else{const cols=3,rows=Math.ceil(b.pieces.length/cols),ch=clamp(H*.18,56,88),trayH=rows*ch+4;c=Math.max(20,Math.min((H-trayH-61)/b.h,(W-46)/b.w,82));bx=(W-b.w*c)/2;by=Math.max(22,(H-trayH-52-b.h*c)/2+22);const cw=W/cols,ty=Math.min(H-trayH,by+b.h*c+28);for(let i=0;i<b.pieces.length;i++)slots.push({x:(i%cols)*cw+4,y:ty+Math.floor(i/cols)*ch+4,w:cw-8,h:ch-8})}
layout={W,H,c,bx,by,slots,landscape};[...$('targets').children].forEach((el,k)=>Object.assign(el.style,{left:bx+k%b.w*c+'px',top:by+Math.floor(k/b.w)*c+'px',width:c+'px',height:c+'px'}));[...$('tray').children].forEach((el,i)=>Object.assign(el.style,{left:slots[i].x+'px',top:slots[i].y+'px',width:slots[i].w+'px',height:slots[i].h+'px'}))}
function trayGeometry(i){const s=layout.slots[i],p=b.pieces[i],pw=Math.max(...p.cells.map(c=>c[0]))+1,ph=Math.max(...p.cells.map(c=>c[1]))+1,c=Math.min((s.w-22)/pw,(s.h-18)/ph,27);return{x:s.x+(s.w-pw*c)/2,y:s.y+(s.h-ph*c)/2,c}}
function geometry(i){const p=pos[i];return p?{x:layout.bx+p[0]*layout.c,y:layout.by+p[1]*layout.c,c:layout.c}:trayGeometry(i)}
function hit(x,y){for(let i=pos.length-1;i>=0;i--){const g=geometry(i);const cell=b.pieces[i].cells.find(([cx,cy])=>x>=g.x+cx*g.c&&x<=g.x+(cx+1)*g.c&&y>=g.y+cy*g.c&&y<=g.y+(cy+1)*g.c);if(cell)return{i,anchor:cell.slice()}}for(let i=0;i<pos.length;i++){const s=layout.slots[i];if(x>s.x&&x<s.x+s.w&&y>s.y&&y<s.y+s.h)return{i,anchor:b.pieces[i].cells[0].slice()}}return null}
function point(e){const r=stage.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function candidate(d){return[Math.round((d.x-layout.bx)/layout.c-.5-d.anchor[0]),Math.round((d.y-layout.by)/layout.c-.5-d.anchor[1])]}
stage.addEventListener('pointerdown',e=>{if(win||!$('collection').hidden||e.button>0||drag)return;const p=point(e),found=hit(p.x,p.y);if(found){selected=found.i;hint=null;drag={...found,...p,startX:p.x,startY:p.y,moving:false,pointer:e.pointerId};stage.setPointerCapture(e.pointerId);chime('pick');update()}else if(selected>=0){cellAction(Math.floor((p.x-layout.bx)/layout.c),Math.floor((p.y-layout.by)/layout.c))}e.preventDefault()});
stage.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointer)return;const p=point(e);drag.x=p.x;drag.y=p.y;if(Math.hypot(p.x-drag.startX,p.y-drag.startY)>6)drag.moving=true;if(drag.moving){const[x,y]=candidate(drag);hover={i:drag.i,x,y,valid:BentoPuzzle.fits(b,pos,drag.i,x,y)}}});
stage.addEventListener('pointerup',e=>{if(!drag||e.pointerId!==drag.pointer)return;const d=drag;drag=null;hover=null;if(d.moving){const[x,y]=candidate(d),inside=d.x>layout.bx-12&&d.x<layout.bx+b.w*layout.c+12&&d.y>layout.by-12&&d.y<layout.by+b.h*layout.c+12;if(BentoPuzzle.fits(b,pos,d.i,x,y))place(d.i,x,y);else if(!inside){if(pos[d.i]){pos[d.i]=null;chime('pick');update()}selected=d.i;animations[d.i]={time:performance.now(),kind:'pop'};update()}else{animations[d.i]={time:performance.now(),kind:'shake'};chime('no');vibrate(12)}}update();if(stage.hasPointerCapture(e.pointerId))stage.releasePointerCapture(e.pointerId)});
stage.addEventListener('pointercancel',()=>{drag=null;hover=null;update()});
function cellAction(x,y){if(win||x<0||x>=b.w||y<0||y>=b.h)return;const owner=pos.findIndex((p,i)=>p&&b.pieces[i].cells.some(c=>p[0]+c[0]===x&&p[1]+c[1]===y));if(selected<0){if(owner>=0){selected=owner;update()}return}const anchor=b.pieces[selected].cells[0];if(BentoPuzzle.fits(b,pos,selected,x-anchor[0],y-anchor[1]))place(selected,x-anchor[0],y-anchor[1]);else{chime('no');animations[selected]={time:performance.now(),kind:'shake'};toast('Try another spot, or move a buddy.')}}
function place(i,x,y){if(win)return;const same=pos[i]&&pos[i][0]===x&&pos[i][1]===y;pos[i]=[x,y];selected=-1;hint=null;animations[i]={time:performance.now(),kind:'pop'};if(!same){chime('drop');vibrate(8);const p=b.pieces[i],g=geometry(i);for(let k=0;k<9;k++)particles.push({x:g.x+(p.cells[0][0]+.5)*g.c,y:g.y+(p.cells[0][1]+.5)*g.c,vx:rnd(-35,35),vy:rnd(-95,-25),life:rnd(.4,.7),max:.7,color:foods[p.kind].base,type:'spark'})}update();if(BentoPuzzle.complete(b,pos))finish()}
function finish(){win=true;lidStart=performance.now();clears++;save();update();chime('win');vibrate([15,30,15]);for(let k=0;k<75;k++)particles.push({x:layout.W/2,y:layout.by+b.h*layout.c*.5,vx:rnd(-170,170),vy:rnd(-210,-50),life:rnd(1.5,2.3),max:2.3,color:[palettes[theme].accent,'#f6ce73','#9cc788','#fff4d8'][k%4],type:'confetti'});$('reward').textContent=clears%3===0&&unlocked()<=6&&clears<=15?'New picnic style: '+palettes[unlocked()-1].name+'!':clears<15?(3-clears%3)+' more '+(3-clears%3===1?'lunch':'lunches')+' to a new picnic style.':'Another little box of happy.';pendingWin=setTimeout(()=>{$('win').hidden=false;$('next').focus()},reduced?350:1450)}
$('next').addEventListener('click',()=>{level++;if(clears%3===0&&clears<=15){theme=unlocked()-1;applyTheme()}start();save()});
$('restart').addEventListener('click',()=>{start();chime('pick');toast('A fresh little start.')});$('sound').addEventListener('click',()=>{sound=!sound;save();update();if(sound)chime('pick')});
$('hint').addEventListener('click',()=>{if(win)return;let solution=BentoPuzzle.solve(b,pos);if(!solution){let found=false;for(let i=0;i<pos.length;i++)if(pos[i]){const old=pos[i];pos[i]=null;solution=BentoPuzzle.solve(b,pos);if(solution){found=true;animations[i]={time:performance.now(),kind:'pop'};toast('Made a little room. Follow the glow.');break}pos[i]=old}if(!found){pos.fill(null);solution=BentoPuzzle.solve(b,pos);toast('Fresh start. Follow the glow.')}}const i=pos.findIndex(p=>!p);if(i>=0&&solution){hint={i,x:solution[i][0],y:solution[i][1]};selected=i;update();chime('pick');if(!$('toast').classList.contains('show'))toast('Match this buddy to the glowing spot.')}});
function collection(){focusReturn=document.activeElement;$('stylecards').replaceChildren();palettes.forEach((p,i)=>{const el=document.createElement('button'),locked=i>=unlocked();el.className='stylecard'+(locked?' locked':'')+(i===theme?' active':'');el.style.setProperty('--cardbox',p.box);el.style.setProperty('--cardrim',p.rim);el.disabled=locked;el.setAttribute('aria-pressed',String(i===theme));el.innerHTML='<span class="minibox"><i></i><i></i><i></i></span>'+p.name+'<small>'+(locked?i*3+' happy lunches':i===theme?'Your picnic today':'Use this style')+'</small>';el.addEventListener('click',()=>{theme=i;applyTheme();save();collection();chime('drop')});$('stylecards').append(el)});$('unlocktip').textContent=unlocked()===6?'Every picnic mood is yours.':'A new style every 3 lunches.';$('collection').hidden=false;$('closecollection').focus()}
$('styles').addEventListener('click',collection);$('closecollection').addEventListener('click',()=>{$('collection').hidden=true;$('styles').focus()});$('collection').addEventListener('click',e=>{if(e.target===$('collection'))$('closecollection').click()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('collection').hidden)$('closecollection').click();const modal=!$('collection').hidden?$('collection'):!$('win').hidden?$('win'):null;if(modal&&e.key==='Tab'){const buttons=[...modal.querySelectorAll('button:not(:disabled)')];let i=buttons.indexOf(document.activeElement);if(e.shiftKey&&i<=0){e.preventDefault();buttons.at(-1).focus()}else if(!e.shiftKey&&i===buttons.length-1){e.preventDefault();buttons[0].focus()}}});
function rounded(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function boundary(cells){const set=new Set(cells.map(c=>c.join(','))),edges=new Map(),add=(a,z)=>edges.set(a.join(','),z);for(const[x,y]of cells){if(!set.has([x,y-1].join(',')))add([x,y],[x+1,y]);if(!set.has([x+1,y].join(',')))add([x+1,y],[x+1,y+1]);if(!set.has([x,y+1].join(',')))add([x+1,y+1],[x,y+1]);if(!set.has([x-1,y].join(',')))add([x,y+1],[x,y])}const first=[...edges.keys()][0].split(',').map(Number),points=[first];let next=edges.get(first.join(','));while(next&&next.join(',')!==first.join(',')&&points.length<40){points.push(next);next=edges.get(next.join(','))}return points}
function blobPath(points,x,y,c,inset=0){const p=points.map(v=>[x+v[0]*c,y+v[1]*c]),r=c*.24;ctx.beginPath();for(let i=0;i<p.length;i++){const a=p[(i+p.length-1)%p.length],v=p[i],z=p[(i+1)%p.length],da=Math.hypot(a[0]-v[0],a[1]-v[1]),dz=Math.hypot(z[0]-v[0],z[1]-v[1]),before=[v[0]+(a[0]-v[0])/da*r,v[1]+(a[1]-v[1])/da*r],after=[v[0]+(z[0]-v[0])/dz*r,v[1]+(z[1]-v[1])/dz*r];if(i===0)ctx.moveTo(...before);else ctx.lineTo(...before);ctx.quadraticCurveTo(...v,...after)}ctx.closePath()}
function drawFood(i,x,y,c,t,ghost=false){const p=b.pieces[i],f=foods[p.kind],shape=boundary(p.cells),a=animations[i],elapsed=(t-a.time)/1000;let squash=0,shake=0;if(!reduced&&elapsed<.6){if(a.kind==='pop')squash=Math.sin(elapsed*22)*Math.exp(-elapsed*6)*.09;else shake=Math.sin(elapsed*55)*Math.exp(-elapsed*7)*c*.11}ctx.save();ctx.translate(x+shake,y);const pw=Math.max(...p.cells.map(c=>c[0]))+1,ph=Math.max(...p.cells.map(c=>c[1]))+1;ctx.translate(pw*c*.5,ph*c*.5);ctx.scale(1+squash,1-squash);ctx.translate(-pw*c*.5,-ph*c*.5);if(ghost)ctx.globalAlpha=.35;
blobPath(shape,0,c*.07,c);ctx.fillStyle=f.shade;ctx.fill();blobPath(shape,0,0,c);const grad=ctx.createLinearGradient(0,0,0,ph*c);grad.addColorStop(0,f.light);grad.addColorStop(1,f.base);ctx.fillStyle=grad;ctx.fill();ctx.strokeStyle='rgba(255,255,255,.6)';ctx.lineWidth=Math.max(1,c*.035);ctx.stroke();
ctx.save();blobPath(shape,0,0,c);ctx.clip();ctx.fillStyle=f.detail;ctx.globalAlpha*=.5;for(let j=0;j<p.cells.length;j++){const[cx,cy]=p.cells[j];for(let k=0;k<3;k++){const sx=(cx+.25+(k*.23)% .6)*c,sy=(cy+.23+((k+j)%3)*.21)*c;ctx.save();ctx.translate(sx,sy);ctx.rotate((k-1)*.7);rounded(-c*.025,-c*.045,c*.05,c*.09,c*.025);ctx.fill();ctx.restore()}if(p.kind===1){ctx.strokeStyle=f.detail;ctx.lineWidth=c*.045;ctx.beginPath();ctx.moveTo(cx*c,cy*c+c*.2);ctx.lineTo(cx*c+c*.9,cy*c+c*.85);ctx.stroke()}}ctx.restore();
const anchor=p.cells[Math.floor(p.cells.length/2)],fx=(anchor[0]+.5)*c,fy=(anchor[1]+.48)*c;ctx.fillStyle='#56443f';const happy=win||elapsed<.65&&a.kind==='pop';for(const sign of[-1,1]){if(happy){ctx.strokeStyle='#56443f';ctx.lineWidth=Math.max(1.4,c*.035);ctx.beginPath();ctx.arc(fx+sign*c*.15,fy,c*.055,Math.PI,Math.PI*2);ctx.stroke()}else{ctx.beginPath();ctx.ellipse(fx+sign*c*.15,fy,c*.035,c*.052,0,0,Math.PI*2);ctx.fill()}}ctx.strokeStyle='#56443f';ctx.lineWidth=Math.max(1.1,c*.028);ctx.beginPath();ctx.arc(fx,fy+c*.05,c*.07,0,Math.PI);ctx.stroke();ctx.fillStyle='rgba(219,101,97,.32)';for(const sign of[-1,1]){ctx.beginPath();ctx.ellipse(fx+sign*c*.25,fy+c*.08,c*.068,c*.04,0,0,Math.PI*2);ctx.fill()}if(p.kind===0){ctx.fillStyle=f.base;for(const sign of[-1,1]){ctx.beginPath();ctx.arc(fx+sign*c*.27,fy-c*.25,c*.1,0,Math.PI*2);ctx.fill();ctx.fillStyle=f.shade;ctx.beginPath();ctx.arc(fx+sign*c*.27,fy-c*.25,c*.05,0,Math.PI*2);ctx.fill();ctx.fillStyle=f.base}}ctx.restore()}
function ghost(i,x,y,valid,t){ctx.save();const f=foods[b.pieces[i].kind];b.pieces[i].cells.forEach(([cx,cy])=>{rounded(layout.bx+(x+cx)*layout.c+3,layout.by+(y+cy)*layout.c+3,layout.c-6,layout.c-6,layout.c*.2);ctx.fillStyle=valid?'rgba(126,175,107,.22)':'rgba(226,103,90,.2)';ctx.fill();ctx.strokeStyle=valid?'#93b881':'#d88479';ctx.lineWidth=2;ctx.setLineDash([4,4]);ctx.stroke()});ctx.restore()}
function draw(t){const dt=Math.min(.035,(t-lastTime)/1000);lastTime=t;const{W,H,c,bx,by,slots}=layout,p=palettes[theme];ctx.clearRect(0,0,W,H);
const bw=b.w*c,bh=b.h*c;ctx.save();ctx.shadowColor='rgba(88,53,32,.16)';ctx.shadowBlur=22;ctx.shadowOffsetY=12;rounded(bx-16,by-16,bw+32,bh+36,25);ctx.fillStyle=p.box;ctx.fill();ctx.restore();rounded(bx-15,by-16,bw+30,bh+29,24);ctx.fillStyle=p.rim;ctx.fill();rounded(bx-8,by-8,bw+16,bh+16,17);ctx.fillStyle='#fff4dc';ctx.fill();rounded(bx-3,by-3,bw+6,bh+6,13);ctx.fillStyle='#eddfc3';ctx.fill();
for(let y=0;y<b.h;y++)for(let x=0;x<b.w;x++){rounded(bx+x*c+2,by+y*c+2,c-4,c-4,c*.17);ctx.fillStyle='#f8ebd1';ctx.fill();ctx.fillStyle='rgba(153,128,89,.18)';ctx.beginPath();ctx.arc(bx+(x+.5)*c,by+(y+.5)*c,1.7,0,Math.PI*2);ctx.fill()}
for(const sign of[-1,1]){rounded(bx+bw*.5-10,by+(sign===-1?-20:bh+13),20,7,3);ctx.fillStyle=p.accent;ctx.fill()}
slots.forEach((s,i)=>{ctx.save();rounded(s.x,s.y,s.w,s.h,16);ctx.fillStyle=i===selected?'rgba(255,255,255,.55)':'rgba(255,255,255,.28)';ctx.fill();ctx.strokeStyle=p.line;ctx.lineWidth=1;ctx.stroke();if(pos[i]){ctx.strokeStyle=p.accent;ctx.globalAlpha=.3;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(s.x+s.w*.44,s.y+s.h*.5);ctx.lineTo(s.x+s.w*.49,s.y+s.h*.56);ctx.lineTo(s.x+s.w*.59,s.y+s.h*.43);ctx.stroke()}ctx.restore()});
if(hint){ghost(hint.i,hint.x,hint.y,true,t);drawFood(hint.i,bx+hint.x*c,by+hint.y*c,c,t,true)}
if(hover)ghost(hover.i,hover.x,hover.y,hover.valid,t);
for(let i=0;i<pos.length;i++){if(drag&&drag.moving&&drag.i===i)continue;const g=geometry(i);if(selected===i&&!pos[i]){ctx.save();ctx.shadowColor=p.accent;ctx.shadowBlur=10;ctx.globalAlpha=.28;blobPath(boundary(b.pieces[i].cells),g.x,g.y,g.c);ctx.fillStyle=p.accent;ctx.fill();ctx.restore()}drawFood(i,g.x+2,g.y+2,g.c-1,t)}
if(drag&&drag.moving){ctx.save();ctx.shadowColor='rgba(74,44,29,.2)';ctx.shadowBlur=16;ctx.shadowOffsetY=10;drawFood(drag.i,drag.x-(drag.anchor[0]+.5)*c,drag.y-(drag.anchor[1]+.5)*c,c,t);ctx.restore()}
if(win&&lidStart){const age=(t-lidStart)/1000,cover=clamp((age-.6)/.5,0,1);if(cover>0){ctx.save();ctx.globalAlpha=cover*.97;rounded(bx-15,by-15,bw+30,bh+30,24);ctx.fillStyle=p.box;ctx.fill();ctx.strokeStyle=p.rim;ctx.lineWidth=4;ctx.stroke();ctx.strokeStyle=p.accent;ctx.globalAlpha=cover*.3;ctx.lineWidth=1;for(let x=bx-4;x<bx+bw;x+=21){ctx.beginPath();ctx.moveTo(x,by);ctx.lineTo(x,by+bh);ctx.stroke()}ctx.globalAlpha=cover;ctx.fillStyle=p.rim;ctx.beginPath();ctx.arc(bx+bw/2,by+bh/2,Math.min(bw,bh)*.21,0,Math.PI*2);ctx.fill();ctx.fillStyle=p.ink;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='bold '+Math.floor(c*.68)+'px system-ui';ctx.fillText('♥',bx+bw/2,by+bh/2);ctx.restore()}}
particles=particles.filter(s=>s.life>0);for(const s of particles){s.life-=dt;s.x+=s.vx*dt;s.y+=s.vy*dt;s.vy+=180*dt;ctx.save();ctx.globalAlpha=clamp(s.life/.35,0,1);ctx.fillStyle=s.color;ctx.translate(s.x,s.y);ctx.rotate(s.life*5);if(s.type==='confetti')rounded(-3,-2,6,4,1);else{ctx.beginPath();ctx.moveTo(0,-4);ctx.lineTo(2,0);ctx.lineTo(0,4);ctx.lineTo(-2,0);ctx.closePath()}ctx.fill();ctx.restore()}
if(!document.hidden)requestAnimationFrame(draw);else lastTime=t}
document.addEventListener('visibilitychange',()=>{if(!document.hidden){lastTime=performance.now();requestAnimationFrame(draw)}});new ResizeObserver(measure).observe(stage);applyTheme();start();requestAnimationFrame(draw);
})();
