(()=>{'use strict';
const $=s=>document.querySelector(s),c=$('#board'),g=c.getContext('2d'),KEY='bounce-safari-v1';
const base=[{id:25,name:'Pikachu',color:'#ffdb63',evo:26},{id:1,name:'Bulbasaur',color:'#83dfae',evo:2},{id:4,name:'Charmander',color:'#ff9c70',evo:5},{id:7,name:'Squirtle',color:'#8acff5',evo:8},{id:133,name:'Eevee',color:'#e8bc82',evo:136},{id:39,name:'Jigglypuff',color:'#ffbad8',evo:40},{id:37,name:'Vulpix',color:'#ffb078',evo:38},{id:143,name:'Snorlax',color:'#a5d0b6',evo:null}];const evoNames={26:'Raichu',2:'Ivysaur',5:'Charmeleon',8:'Wartortle',136:'Flareon',40:'Wigglytuff',38:'Ninetales'};
const imgs={};for(const p of base)for(const id of [p.id,p.evo])if(id&&!imgs[id]){let im=new Image();im.src=`sprites/${id}.png`;imgs[id]=im}const bg=new Image();bg.src='safari-bg.webp';
let data={};try{data=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}
let s={round:Math.max(1,data.round||1),coins:Math.max(0,data.coins||0),best:Math.max(0,data.best||0),dex:data.dex||{},evolved:data.evolved||{},magnet:data.magnet||0,luck:data.luck||0,power:data.power||0,mode:'menu',score:0,caught:0,shots:0,combo:0,ball:null,targets:[],particles:[],rings:[],floats:[],captures:[],stars:[],bumpers:[],aiming:false,aim:null,nudge:false,flipLeft:0,flipRight:0,flipCooldown:0,fever:0,feverTime:0,flash:0,shake:0,time:0,token:0,sound:true};
let W=0,H=0,dpr=1,ac=null,toastTimer=0,globalTime=0;
const rnd=(a,b)=>a+Math.random()*(b-a),clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function save(){try{localStorage.setItem(KEY,JSON.stringify({round:s.round,coins:s.coins,best:s.best,dex:s.dex,evolved:s.evolved,magnet:s.magnet,luck:s.luck,power:s.power}))}catch{}}
function resize(){let rect=c.getBoundingClientRect();W=rect.width;H=rect.height;dpr=Math.min(devicePixelRatio||1,1.8);c.width=Math.round(W*dpr);c.height=Math.round(H*dpr);g.setTransform(dpr,0,0,dpr,0,0);s.stars=Array.from({length:55},()=>({x:rnd(15,W-15),y:rnd(5,H*.75),r:rnd(.6,2),phase:rnd(0,7)}));placeBumpers();if(s.mode==='play'&&!s.ball)spawnTargets()}
function placeBumpers(){s.bumpers=[{x:W*.21,y:H*.60,r:23},{x:W*.79,y:H*.60,r:23}];if(s.round%3!==0)s.bumpers.push({x:W*.5,y:H*.48,r:19})}
function ui(){$('#round').textContent=String(s.round).padStart(2,'0');$('#coins').textContent=s.coins;$('#best').textContent=s.best;$('#balls').innerHTML=Array.from({length:3},(_,i)=>`<span class="ballDot ${i<s.shots?'used':''}"></span>`).join('');$('#dex').innerHTML=base.slice(0,7).map(p=>`<img src="sprites/${p.id}.png" alt="${p.name}" title="${p.name}: ${s.dex[p.id]||0} caught" class="${s.dex[p.id]?'':'locked'}">`).join('');$('#hint').textContent=s.ball?'TAP LOWER LEFT / RIGHT TO FLIP':s.mode==='play'?'DRAG UP TO LAUNCH':'DRAG UP TO AIM'}
function tone(freq,dur=.13,vol=.04,type='sine',delay=0){if(!s.sound)return;try{if(!ac)ac=new(window.AudioContext||window.webkitAudioContext)();if(ac.state==='suspended')ac.resume();let o=ac.createOscillator(),v=ac.createGain(),t=ac.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(freq*1.12,t+dur);v.gain.setValueAtTime(vol,t);v.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(v).connect(ac.destination);o.start(t);o.stop(t+dur)}catch{}}
function soundCatch(n){tone(360+n*70,.16,.065,'triangle');tone(620+n*80,.23,.05,'sine',.09)}
function buzz(ms=15){navigator.vibrate?.(ms)}
function toast(text){let el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),950)}
function burst(x,y,color,n=22,force=4){s.rings.push({x,y,r:5,life:.55,max:.55,color});for(let i=0;i<n;i++){let a=i*6.283/n+rnd(-.25,.25),v=rnd(force*.35,force);s.particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v-1,life:rnd(.4,1),max:1,size:rnd(2,5),color:i%4?'#fff0be':color})}}
function floatText(x,y,text,color='#fff5c1',size=18){s.floats.push({x,y,text,color,size,life:1.2,max:1.2})}
function flash(){let el=$('#shine');el.classList.remove('on');void el.offsetWidth;el.classList.add('on')}
function speciesPool(){let n=s.round<2?4:s.round<4?6:8;return base.slice(0,n)}
function chooseSpecies(){let p=speciesPool(),pick=p[Math.floor(Math.random()*p.length)];return pick}
function spawnTargets(){s.token++;let bossRound=s.round%3===0,slots=bossRound?[[.18,.28],[.5,.20],[.82,.28]]:s.round<3?[[.22,.28],[.78,.28],[.5,.22]]:[[.18,.28],[.5,.20],[.82,.28],[.5,.36]];let token=s.token;s.targets=slots.map(([rx,ry],i)=>{let p=bossRound&&i===1?base[7]:chooseSpecies(),showEvo=!!s.evolved[p.id]&&Math.random()<.3,boss=bossRound&&i===1;return{x:W*rx,y:H*ry,baseX:W*rx,baseY:H*ry,r:boss?38:30,id:p.id,name:showEvo?evoNames[p.evo]:p.name,color:p.color,showEvo,shiny:!boss&&Math.random()<.045+s.luck*.02,boss,hp:boss?2:1,phase:rnd(0,7),vx:rnd(.2,.5)*(i%2?1:-1),alive:true,token}})}
function startRound(){s.mode='play';s.score=0;s.caught=0;s.shots=0;s.combo=0;s.ball=null;s.nudge=false;s.fever=0;s.feverTime=0;s.flipLeft=0;s.flipRight=0;s.captures=[];s.particles=[];s.rings=[];s.floats=[];s.aim=null;s.aiming=false;placeBumpers();spawnTargets();$('#modal').classList.add('hidden');ui();tone(490,.17,.05);tone(750,.25,.045,'sine',.1);if(s.round%3===0)toast('BOSS ROUND!')}
function launch(x,y){if(s.mode!=='play'||s.ball||s.shots>=3)return;let ox=W*.5,oy=H-56,dx=x-ox,dy=Math.min(-80,y-oy),l=Math.hypot(dx,dy),speed=11+s.power*.3;s.ball={x:ox,y:oy,vx:dx/l*speed,vy:dy/l*speed,r:12,life:0,absoluteLife:0,saves:0,trail:[],bumperCD:0};s.shots++;s.combo=0;s.nudge=false;s.aiming=false;ui();burst(ox,oy,'#fb747b',13,3);tone(230,.18,.09,'triangle');buzz(12)}
function nudge(x,y){if(!s.ball||s.nudge)return;let b=s.ball,dx=x-b.x,dy=y-b.y,l=Math.hypot(dx,dy)||1,bv=Math.hypot(b.vx,b.vy);b.vx=b.vx*.33+dx/l*Math.max(8,bv)*.67;b.vy=b.vy*.33+dy/l*Math.max(8,bv)*.67;s.nudge=true;burst(b.x,b.y,'#affdf4',18,3);toast('NICE NUDGE!');tone(500,.14,.05);buzz(9);ui()}
function addFever(amount){if(s.feverTime>0)return;s.fever=clamp(s.fever+amount,0,100);if(s.fever>=100){s.fever=0;s.feverTime=6;s.coins+=30;save();ui();flash();toast('FEVER MODE!');floatText(W*.5,H*.37,'+30 FEVER BONUS','#fff1a5',22);burst(W*.5,H*.38,'#ffe57d',70,6);tone(440,.27,.08,'sawtooth');tone(660,.32,.07,'sine',.08);tone(880,.35,.06,'sine',.17);buzz(55)}}
function flip(side){if(!s.ball||s.flipCooldown>0)return;let b=s.ball;s.flipCooldown=.18;s[side==='left'?'flipLeft':'flipRight']=.22;let correct=side==='left'?b.x<W*.59:b.x>W*.41,near=b.y>H-165&&b.y<H-16,limit=2+s.power;if(near&&correct&&b.vy>-4&&b.saves<limit){b.saves++;b.life=Math.max(0,b.life-1.5);let target=s.targets.filter(t=>t.alive).sort((a,z)=>Math.hypot(a.x-b.x,a.y-b.y)-Math.hypot(z.x-b.x,z.y-b.y))[0];let dx=target?target.x-b.x:(side==='left'?W*.25:-W*.25),dy=target?target.y-b.y:-H*.55,l=Math.hypot(dx,dy)||1,v=12+s.power*.8;b.vx=dx/l*v;b.vy=dy/l*v;b.y=Math.min(b.y,H-47);burst(b.x,b.y,'#aafff0',28,5);floatText(b.x,b.y-22,'FLIP SAVE!','#fff3b5',20);s.shake=5;addFever(18);tone(320,.16,.08,'triangle');tone(610,.22,.06,'sine',.07);buzz(25);ui()}else{tone(200,.06,.015,'triangle')}}
function catchTarget(t){if(!t.alive)return;if(t.hp>1){t.hp--;t.invuln=.65;burst(t.x,t.y,'#fff0ad',30,5);floatText(t.x,t.y-25,'SHIELD BREAK!','#ffe99b',18);s.shake=8;addFever(15);tone(180,.24,.09,'sawtooth');buzz(35);if(s.ball){s.ball.hitstop=.08;s.ball.vx=rnd(-5,5);s.ball.vy=8;s.ball.y=t.y+t.r+s.ball.r+4}return}t.alive=false;s.caught++;s.combo++;let fresh=!(s.dex[t.id]||0),mult=(t.shiny?3:1)*(s.feverTime>0?2:1)*(t.boss?3:1),coins=(8+s.combo*4)*mult,points=(100+s.combo*60)*mult;s.coins+=coins;s.score+=points;s.best=Math.max(s.best,s.score);s.dex[t.id]=(s.dex[t.id]||0)+1;s.captures.push({x:t.x,y:t.y,id:t.showEvo?base.find(p=>p.id===t.id)?.evo:t.id,life:.36,max:.36});save();ui();let suffix=s.combo>1?`  ×${s.combo}`:'';floatText(t.x,t.y-25,`+${points}${suffix}`,t.shiny?'#ffe67e':'#fff4ca',s.combo>2?23:18);if(fresh)floatText(t.x,t.y-51,'NEW!','#b9ffe0',13);burst(t.x,t.y,t.shiny?'#ffe571':t.color,t.shiny?50:34,t.shiny?7:5);s.shake=Math.min(10,3+s.combo*1.5);soundCatch(Math.min(6,s.combo));buzz(s.combo>2?30:14);if(s.combo>=3){flash();toast(s.combo>=5?'SUPER CHAIN!':'CHAIN CATCH!')}addFever(19+s.combo*3);
  let p=base.find(p=>p.id===t.id);if(p?.evo&&s.dex[t.id]>=3&&!s.evolved[t.id]){s.evolved[t.id]=true;save();setTimeout(()=>{toast(`${p.name.toUpperCase()} EVOLVED!`);flash();tone(560,.3,.07,'triangle');tone(860,.35,.06,'sine',.12);burst(W*.5,H*.35,'#fff0a1',55,6)},250)}
  const b=s.ball;if(b){b.hitstop=.075;let next=s.targets.filter(x=>x.alive).sort((a,z)=>Math.hypot(a.x-b.x,a.y-b.y)-Math.hypot(z.x-b.x,z.y-b.y))[0];if(next&&s.combo<3){let dx=next.x-b.x,dy=next.y-b.y,l=Math.hypot(dx,dy)||1,v=10.4+s.power*.4;b.vx=dx/l*v;b.vy=dy/l*v}else{b.vx=rnd(-6,6);b.vy=7+s.power*.35}}
  if(!s.targets.some(x=>x.alive)){let token=s.token;setTimeout(()=>{if(s.mode==='play'&&s.token===token){spawnTargets();toast('NEW WAVE!')}},620)}
}
function endShot(){if(!s.ball)return;let b=s.ball;burst(clamp(b.x,25,W-25),H-35,'#aedbe5',15,2);s.ball=null;s.nudge=false;if(s.shots>=3){setTimeout(endRound,600)}else{toast(s.caught?'GREAT SHOT!':'TRY A NEW ANGLE');ui()}}
function endRound(){if(s.mode!=='play'||s.ball||s.shots<3)return;s.mode='summary';s.token++;save();$('#modalBrow').textContent='SAFARI COMPLETE';$('#hero').src=`sprites/${s.caught?base.find(p=>s.dex[p.id])?.id||25:25}.png`;$('#modalTitle').innerHTML=s.caught>=6?'AMAZING<br>RUN!':s.caught>=2?'NICE<br>CATCHES!':'ONE MORE<br>ROUND?';$('#modalText').innerHTML=`${s.caught} caught · ${s.score} points · ${s.coins} coins to spend`;
  $('#go').textContent='NEXT ROUND';$('#modalMini').textContent='COLLECTION AND UPGRADES SAVE AUTOMATICALLY';renderUpgrades();$('#upgrades').hidden=false;$('#modal').classList.remove('hidden')}
const upgrades=[{id:'magnet',icon:'🧲',name:'CATCH MAGNET',info:'Easier near-miss catches.',cost:80,max:4},{id:'power',icon:'⚡',name:'FLIP SPRINGS',info:'Extra saves and stronger rebounds.',cost:100,max:4},{id:'luck',icon:'✨',name:'SHINY CHARM',info:'More golden encounters.',cost:130,max:4}];
function renderUpgrades(){let box=$('#upgrades');box.innerHTML='';for(let u of upgrades){let level=s[u.id],price=u.cost+level*80,el=document.createElement('button');el.className='upgrade';el.disabled=level>=u.max||s.coins<price;el.innerHTML=`<span class="symbol">${u.icon}</span><span class="desc"><b>${u.name} · LV ${level}</b><small>${u.info}</small></span><span class="price">${level>=u.max?'MAX':price+' ◉'}</span>`;el.onclick=()=>{s.coins-=price;s[u.id]++;save();ui();tone(610,.18,.065);toast(`${u.name} UP!`);renderUpgrades();$('#modalText').innerHTML=`${s.caught} caught · ${s.score} points · ${s.coins} coins to spend`};box.append(el)}}
function drawBG(){if(bg.complete&&bg.naturalWidth){let scale=Math.max(W/bg.width,H/bg.height),sw=W/scale,sh=H/scale;g.drawImage(bg,(bg.width-sw)/2,(bg.height-sh)/2,sw,sh,0,0,W,H)}else{let grad=g.createLinearGradient(0,0,0,H);grad.addColorStop(0,'#152547');grad.addColorStop(1,'#176069');g.fillStyle=grad;g.fillRect(0,0,W,H)}if(s.round>1){g.fillStyle=['#0000','#68418218','#337f6a18','#aa5d4b16'][(s.round-1)%4];g.fillRect(0,0,W,H)}g.fillStyle='#08213938';g.fillRect(0,0,W,H);if(s.feverTime>0){g.fillStyle=`rgba(255,198,89,${.08+Math.sin(globalTime*15)*.035})`;g.fillRect(0,0,W,H)}
  for(const star of s.stars){g.globalAlpha=.2+.28*(1+Math.sin(globalTime*1.6+star.phase))/2;g.fillStyle='#e9f9e1';g.fillRect(star.x,star.y,star.r,star.r)}g.globalAlpha=1;
  g.strokeStyle='#9ae8e953';g.lineWidth=4;g.strokeRect(8,7,W-16,H-15);g.strokeStyle='#dcfff1a8';g.lineWidth=1;g.strokeRect(14,13,W-28,H-27);
  g.fillStyle='#081d33c9';g.fillRect(15,13,W-30,43);g.fillStyle='#d9f7e9';g.font='900 11px Trebuchet MS,Arial';g.textAlign='left';g.fillText('SCORE',27,31);g.fillStyle='#fff3b2';g.font='900 19px Trebuchet MS,Arial';g.fillText(s.score.toLocaleString(),27,49);g.textAlign='right';g.fillStyle=s.feverTime>0?'#ffe58d':s.combo>1?'#fff0a2':'#92cdd5';g.font='900 16px Trebuchet MS,Arial';g.fillText(s.feverTime>0?'✦ FEVER ×2':s.combo>1?`×${s.combo} CHAIN`:s.ball?'CATCH THEM!':'READY',W-28,43);g.textAlign='left';g.fillStyle='#091e31c9';g.fillRect(15,58,W-30,9);let bar=g.createLinearGradient(15,0,W-15,0);bar.addColorStop(0,'#62dbdd');bar.addColorStop(.65,'#ffd27e');bar.addColorStop(1,'#fff5b3');g.fillStyle=bar;g.fillRect(17,60,(W-34)*(s.feverTime>0?s.feverTime/6:s.fever/100),5);
  // Decorative gold route markings and springy bumpers.
  for(let b of s.bumpers){let pulse=Math.sin(globalTime*4+b.x)*2;g.shadowColor='#ffeea1';g.shadowBlur=15;g.fillStyle='#102e48';g.beginPath();g.arc(b.x,b.y,b.r+5+pulse,0,7);g.fill();g.shadowBlur=0;g.strokeStyle='#ffd998';g.lineWidth=4;g.stroke();g.fillStyle='#f9b970';g.beginPath();g.arc(b.x,b.y,b.r*.67,0,7);g.fill();g.fillStyle='#fff0bc';g.beginPath();g.arc(b.x,b.y,b.r*.32,0,7);g.fill()}
  for(const side of ['left','right']){let left=side==='left',lift=s[left?'flipLeft':'flipRight']/.22,baseX=left?16:W-16,tipX=left?W*.32:W*.68,tipY=H-35-lift*55;g.save();g.shadowColor=lift?'#c9fff3':'#f9cf88';g.shadowBlur=lift?25:12;g.fillStyle='#103750';g.beginPath();g.moveTo(baseX,H-78);g.lineTo(tipX,tipY);g.lineTo(baseX,H-30);g.closePath();g.fill();g.strokeStyle=lift?'#a8fff2':'#f9df9d';g.lineWidth=5;g.lineCap='round';g.beginPath();g.moveTo(baseX,H-76);g.lineTo(tipX,tipY);g.stroke();g.restore()}if(s.ball){g.fillStyle='#d8f9e7c9';g.font='900 10px Trebuchet MS,Arial';g.textAlign='center';g.fillText(`FLIP SAVES ${Math.max(0,2+s.power-s.ball.saves)}`,W*.5,H-16)}
}
function drawTarget(t){if(!t.alive)return;let q=1+Math.sin(globalTime*3+t.phase)*.045,x=t.x,y=t.y;g.save();g.translate(x,y);g.scale(q,q);g.shadowColor=t.shiny?'#ffe477':t.color;g.shadowBlur=t.shiny?35:20;g.fillStyle=t.shiny?'#fff1a877':'#c7faff30';g.beginPath();g.arc(0,0,t.r+9,0,7);g.fill();g.shadowBlur=0;g.strokeStyle=t.shiny?'#ffe575':t.color;g.lineWidth=3;g.beginPath();g.arc(0,0,t.r+8,0,7);g.stroke();if(t.boss&&t.hp>1){g.strokeStyle='#fff0aa';g.setLineDash([5,4]);g.lineWidth=3;g.beginPath();g.arc(0,0,t.r+17+Math.sin(globalTime*5)*2,0,7);g.stroke();g.setLineDash([])}let img=imgs[t.showEvo?base.find(p=>p.id===t.id)?.evo:t.id]||imgs[t.id];if(img?.complete&&img.naturalWidth){g.imageSmoothingEnabled=false;let sz=clamp(t.r*2.5,60,88);g.drawImage(img,-sz/2,-sz/2-5,sz,sz);g.imageSmoothingEnabled=true}else{g.fillStyle=t.color;g.beginPath();g.arc(0,0,t.r*.75,0,7);g.fill()}
  if(t.shiny){g.fillStyle='#fff7b4';g.font='20px Arial';g.textAlign='center';g.fillText('✦',t.r+9,-t.r+2)}g.fillStyle='#0a2438e6';g.beginPath();g.roundRect(-30,t.r+7,60,17,8);g.fill();g.fillStyle='#fff7e0';g.font='900 10px Trebuchet MS,Arial';g.textAlign='center';g.fillText(t.name.toUpperCase(),0,t.r+19);g.restore()}
function drawBall(b){if(!b)return;g.save();for(let i=0;i<b.trail.length;i++){let p=b.trail[i],a=i/b.trail.length;g.globalAlpha=a*(s.feverTime>0?.72:.35);g.fillStyle=s.feverTime>0?'#ffe995':'#c7fbea';g.beginPath();g.arc(p.x,p.y,3+a*(s.feverTime>0?8:5),0,7);g.fill()}g.globalAlpha=1;g.translate(b.x,b.y);g.rotate(globalTime*12);g.shadowColor=s.feverTime>0?'#ffe073':'#fff5b1';g.shadowBlur=s.feverTime>0?30:17;g.fillStyle='#fff9e9';g.beginPath();g.arc(0,0,12,0,7);g.fill();g.shadowBlur=0;g.fillStyle=s.feverTime>0?'#ffbc4a':'#f35b69';g.beginPath();g.arc(0,0,11.6,Math.PI,Math.PI*2);g.closePath();g.fill();g.strokeStyle='#1e2b41';g.lineWidth=2.5;g.beginPath();g.moveTo(-12,0);g.lineTo(12,0);g.stroke();g.fillStyle='#1e2b41';g.beginPath();g.arc(0,0,4.5,0,7);g.fill();g.fillStyle='#fff';g.beginPath();g.arc(0,0,2.7,0,7);g.fill();g.restore()}
function drawLauncher(){let x=W*.5,y=H-56;g.save();g.shadowColor='#ffca8b';g.shadowBlur=20;g.fillStyle='#152d46';g.beginPath();g.arc(x,y,25,0,7);g.fill();g.shadowBlur=0;g.strokeStyle='#f5d293';g.lineWidth=3;g.stroke();if(!s.ball&&s.mode==='play'){drawBall({x,y,trail:[]});if(s.aiming&&s.aim){let dx=s.aim.x-x,dy=Math.min(-80,s.aim.y-y),l=Math.hypot(dx,dy);g.strokeStyle='#fff5b7b0';g.setLineDash([6,8]);g.lineWidth=2;g.beginPath();g.moveTo(x,y);g.lineTo(x+dx/l*Math.min(l,H*.58),y+dy/l*Math.min(l,H*.58));g.stroke();g.setLineDash([]);g.fillStyle='#fff5b8';g.beginPath();g.arc(s.aim.x,s.aim.y,5+Math.sin(globalTime*9)*2,0,7);g.fill()}}g.restore()}
function update(dt){
  globalTime+=dt;s.time+=dt;s.flipLeft=Math.max(0,s.flipLeft-dt);s.flipRight=Math.max(0,s.flipRight-dt);s.flipCooldown=Math.max(0,s.flipCooldown-dt);
  if(s.mode==='play'){
    for(const t of s.targets){t.phase+=dt;t.invuln=Math.max(0,(t.invuln||0)-dt);t.x=t.baseX+Math.sin(globalTime*(.95+s.round*.035)+t.baseX)*Math.min(22,W*.055);t.y=t.baseY+Math.sin(globalTime*1.8+t.phase)*4}
    let b=s.ball;if(b){if(s.feverTime>0)s.feverTime=Math.max(0,s.feverTime-dt);let steps=Math.max(1,Math.ceil(dt*60)),d=dt*60/steps;
      for(let k=0;k<steps&&s.ball;k++){
        b.life+=dt/steps;b.absoluteLife+=dt/steps;
        if(b.hitstop>0){b.hitstop-=dt/steps;continue}
        b.trail.push({x:b.x,y:b.y});if(b.trail.length>13)b.trail.shift();
        let nearest=s.targets.filter(t=>t.alive).sort((a,z)=>Math.hypot(a.x-b.x,a.y-b.y)-Math.hypot(z.x-b.x,z.y-b.y))[0];
        if(nearest){let dx=nearest.x-b.x,dy=nearest.y-b.y,dist=Math.hypot(dx,dy);if(dist<110+s.magnet*18&&dist>1){let pull=.025+s.magnet*.013;b.vx+=dx/dist*pull*d;b.vy+=dy/dist*pull*d}}
        b.vy+=.075*d;b.x+=b.vx*d;b.y+=b.vy*d;b.vx*=.999;b.vy*=.999;b.bumperCD=Math.max(0,b.bumperCD-d);
        if(b.x<25){b.x=25;b.vx=Math.abs(b.vx)*.92;burst(b.x,b.y,'#a7f6f2',7,1.4);tone(250,.07,.02)}
        if(b.x>W-25){b.x=W-25;b.vx=-Math.abs(b.vx)*.92;burst(b.x,b.y,'#a7f6f2',7,1.4);tone(250,.07,.02)}
        if(b.y<68){b.y=68;b.vy=Math.abs(b.vy)*.9;burst(b.x,b.y,'#a7f6f2',7,1.4)}
        for(const bump of s.bumpers){let dx=b.x-bump.x,dy=b.y-bump.y,dist=Math.hypot(dx,dy);if(dist<bump.r+b.r&&b.bumperCD<=0){let nx=dx/(dist||1),ny=dy/(dist||1),v=11+s.power*.35;b.vx=nx*v;b.vy=ny*v-1;b.x=bump.x+nx*(bump.r+b.r+2);b.y=bump.y+ny*(bump.r+b.r+2);b.bumperCD=8;burst(bump.x,bump.y,'#ffe397',12,2.3);addFever(5);tone(370,.11,.036,'triangle');s.shake=2}}
        for(const t of s.targets)if(t.alive&&!t.invuln&&Math.hypot(b.x-t.x,b.y-t.y)<t.r+b.r+3+s.magnet*2+(s.feverTime>0?7:0)){catchTarget(t);break}
        if(b.y>H-18||b.life>8.5||b.absoluteLife>14){endShot();break}
      }
    }
  }
  for(let i=s.particles.length-1;i>=0;i--){let p=s.particles[i];p.x+=p.vx*dt*60;p.y+=p.vy*dt*60;p.vy+=dt*5;p.life-=dt;if(p.life<=0)s.particles.splice(i,1)}
  for(let i=s.rings.length-1;i>=0;i--){let r=s.rings[i];r.r+=dt*160;r.life-=dt;if(r.life<=0)s.rings.splice(i,1)}
  for(let i=s.floats.length-1;i>=0;i--){let f=s.floats[i];f.y-=dt*40;f.life-=dt;if(f.life<=0)s.floats.splice(i,1)}
  for(let i=s.captures.length-1;i>=0;i--){let q=s.captures[i];q.life-=dt;if(q.life<=0)s.captures.splice(i,1)}
  s.shake=Math.max(0,s.shake-dt*25)
}
function draw(){g.clearRect(0,0,W,H);g.save();if(s.shake)g.translate(rnd(-s.shake,s.shake),rnd(-s.shake,s.shake));drawBG();for(const t of s.targets)drawTarget(t);
  for(const q of s.captures){let img=imgs[q.id],p=1-q.life/q.max,sz=72*(1-p);g.globalAlpha=Math.max(0,q.life/q.max);if(img?.complete&&img.naturalWidth&&sz>1){g.imageSmoothingEnabled=false;g.drawImage(img,q.x-sz/2,q.y-sz/2-p*30,sz,sz);g.imageSmoothingEnabled=true}g.globalAlpha=1}
  drawLauncher();drawBall(s.ball);
  for(const r of s.rings){g.globalAlpha=Math.max(0,r.life/r.max)*.7;g.strokeStyle=r.color;g.lineWidth=4;g.beginPath();g.arc(r.x,r.y,r.r,0,7);g.stroke()}
  for(const p of s.particles){g.globalAlpha=Math.max(0,p.life/p.max);g.fillStyle=p.color;g.beginPath();g.arc(p.x,p.y,p.size,0,7);g.fill()}
  for(const f of s.floats){g.globalAlpha=Math.max(0,f.life/f.max);g.textAlign='center';g.font=`900 ${f.size}px Trebuchet MS,Arial`;g.fillStyle='#13253b';g.fillText(f.text,f.x+2,f.y+2);g.fillStyle=f.color;g.fillText(f.text,f.x,f.y)}g.globalAlpha=1;g.restore()}
let prev=performance.now();function frame(now){let dt=Math.min(.05,(now-prev)/1000);prev=now;update(dt);draw();requestAnimationFrame(frame)}
function loc(e){let r=c.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
c.addEventListener('pointerdown',e=>{if(s.mode!=='play')return;e.preventDefault();let p=loc(e);if(s.ball){if(p.y>H*.58)flip(p.x<W*.5?'left':'right');else nudge(p.x,p.y);return}s.aiming=true;s.aim=p;c.setPointerCapture(e.pointerId)});
c.addEventListener('pointermove',e=>{if(!s.aiming)return;e.preventDefault();s.aim=loc(e)});
c.addEventListener('pointerup',e=>{if(!s.aiming)return;e.preventDefault();let p=loc(e);s.aiming=false;s.aim=null;launch(p.x,p.y)});
c.addEventListener('pointercancel',()=>{s.aiming=false;s.aim=null});
$('#go').onclick=()=>{if(s.mode==='summary')s.round++;save();startRound()};$('#mute').onclick=()=>{s.sound=!s.sound;$('#mute').textContent=s.sound?'♫ ON':'♫ OFF';if(s.sound)tone(550,.14,.04)};
if(location.protocol==='file:')window.__bounceQA=()=>({mode:s.mode,ball:s.ball&&{x:s.ball.x,y:s.ball.y,vy:s.ball.vy,saves:s.ball.saves},fever:s.fever,feverTime:s.feverTime,round:s.round,shots:s.shots,caught:s.caught,targets:s.targets.map(t=>({x:t.x,y:t.y,id:t.id,hp:t.hp,alive:t.alive,boss:t.boss}))});
addEventListener('resize',resize);resize();spawnTargets();ui();requestAnimationFrame(frame);
})();
