(function(root){'use strict';const key=(x,z)=>x+','+z,inside=(x,z)=>Number.isInteger(x)&&Number.isInteger(z)&&Math.abs(x)<=3&&Math.abs(z)<=3,copy=o=>JSON.parse(JSON.stringify(o));
const specs=[{name:'A little harbour',sub:'Four houses by the water.',target:[[-1,0,1],[0,0,1],[1,0,1],[0,-1,2]],gift:'Seafoam paint'},{name:'Three friendly towers',sub:'A little skyline, one tap at a time.',target:[[-1,0,2],[0,0,3],[1,0,2]],gift:'Roof pennants'},{name:'The secret garden',sub:'Leave the middle open. Nature moves in.',target:[[-1,-1,1],[0,-1,1],[1,-1,1],[-1,0,1],[1,0,1],[-1,1,1],[0,1,1],[1,1,1]],need:'garden',gift:'Courtyard flowers'},{name:'A seaside arcade',sub:'Neighbours make a real archway.',target:[[-2,0,2],[-1,0,2],[0,0,2],[1,0,2],[2,0,2]],need:'arch',gift:'Warm lanterns'},{name:'Two little shores',sub:'Build around a narrow canal.',target:[[-2,-1,1],[-1,-1,2],[0,-1,2],[1,-1,1],[2,-1,2],[-2,1,2],[-1,1,1],[0,1,2],[1,1,2],[2,1,1],[2,0,1]],gift:'A harbour sailboat'},{name:'The lighthouse keeper',sub:'Four floors. A light above the waves.',target:[[0,0,4],[-1,0,1],[1,0,1],[0,-1,1],[0,1,1],[-1,-1,1],[1,1,1]],gift:'Lighthouse finials'},{name:'Above the green',sub:'A garden beneath a ring of rooftops.',target:[[-1,-1,2],[0,-1,2],[1,-1,2],[-1,0,2],[1,0,2],[-1,1,2],[0,1,2],[1,1,2]],need:'garden',gift:'Festival bunting'},{name:'Wish you were here',sub:'A whole little world to call your own.',target:[[-2,-1,1],[-1,-1,2],[0,-1,3],[1,-1,2],[2,-1,1],[-2,0,2],[-1,0,2],[0,0,4],[1,0,3],[2,0,2],[-2,1,1],[-1,1,2],[0,1,2],[1,1,1],[2,1,2],[0,2,1]],gift:'Endless island postcards'}];
function project(i){if(i<specs.length)return copy(specs[i]);const target=[];for(let x=-2;x<=2;x++)for(let z=-2;z<=2;z++){const r=(x*17+z*31+i*13+193)%7;if(r>1)target.push([x,z,1+(Math.abs(x*3-z*5+i)%3)])}return{name:['Saltwater wishes','A roof for every dream','Letters from the blue','A tiny island holiday'][i%4],sub:'Another island. A different skyline.',target,gift:'Another sea-mail stamp'}}
function stats(cells){let floors=0,houses=0,arches=0,gardens=0,towers=0;const h=(x,z)=>(cells[key(x,z)]||[]).length;for(const [k,v]of Object.entries(cells)){if(!v.length)continue;houses++;floors+=v.length;if(v.length>=3)towers++;const [x,z]=k.split(',').map(Number);if(v.length>=2&&((h(x-1,z)>=2&&h(x+1,z)>=2&&!h(x,z-1)&&!h(x,z+1))||(h(x,z-1)>=2&&h(x,z+1)>=2&&!h(x-1,z)&&!h(x+1,z))))arches++}for(let x=-3;x<=3;x++)for(let z=-3;z<=3;z++)if(!h(x,z)&&h(x-1,z)&&h(x+1,z)&&h(x,z-1)&&h(x,z+1))gardens++;return{floors,houses,arches,gardens,towers}}
function progress(cells,p){let have=0,total=0;for(const[x,z,h]of p.target){have+=Math.min(h,(cells[key(x,z)]||[]).length);total+=h}const s=stats(cells),extra=p.need==='garden'?(s.gardens>0&&!cells['0,0']):p.need==='arch'?s.arches>0:true;return{have,total,complete:have>=total&&!!extra,extra:!!extra}}
function valid(cells){if(!cells||Array.isArray(cells)||typeof cells!=='object')return false;return Object.entries(cells).every(([k,v])=>{const[x,z]=k.split(',').map(Number);return inside(x,z)&&Array.isArray(v)&&v.length>0&&v.length<=4&&v.every(c=>Number.isInteger(c)&&c>=0&&c<6)})}
class Town{constructor(cells={}){this.cells=valid(cells)?copy(cells):{};this.undoStack=[];this.redoStack=[]}remember(){this.undoStack.push(copy(this.cells));if(this.undoStack.length>80)this.undoStack.shift();this.redoStack=[]}add(x,z,c){if(!inside(x,z)||!Number.isInteger(c)||c<0||c>5||(this.cells[key(x,z)]||[]).length>=4)return false;this.remember();(this.cells[key(x,z)]??=[]).push(c);return true}remove(x,z){if(!inside(x,z)||!this.cells[key(x,z)]?.length)return false;this.remember();this.cells[key(x,z)].pop();if(!this.cells[key(x,z)].length)delete this.cells[key(x,z)];return true}undo(){if(!this.undoStack.length)return false;this.redoStack.push(copy(this.cells));this.cells=this.undoStack.pop();return true}redo(){if(!this.redoStack.length)return false;this.undoStack.push(copy(this.cells));this.cells=this.redoStack.pop();return true}reset(cells={}){this.cells=valid(cells)?copy(cells):{};this.undoStack=[];this.redoStack=[]}}
function showcase(){const c={},put=(x,z,h,color)=>c[key(x,z)]=Array.from({length:h},(_,i)=>(color+(i>1?1:0))%6);for(let x=-2;x<=2;x++){put(x,-1,2+(x===0?2:0),(x+8)%6);put(x,1,1+(Math.abs(x)%2),((x+7)%6))}put(-2,0,2,3);put(2,0,3,0);put(0,-2,2,1);put(-1,-2,1,4);put(1,-2,3,2);put(0,2,1,5);put(2,2,1,4);return c}
const api={Town,key,inside,copy,project,stats,progress,valid,showcase,specs};root.TideEngine=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window==='undefined'?globalThis:window);
