(function(root){const themes=[{bg:'#f5ecdf',board:'#f5e2ce',rim:'#caa582',ink:'#46665a',pond:'#a2c1bd',leaf:'#7e9c7b',bloom:'#d6988e'},{bg:'#e7eee4',board:'#e1e6cd',rim:'#a6b994',ink:'#426f63',pond:'#99babc',leaf:'#688c70',bloom:'#d2aa80'},{bg:'#eee5ea',board:'#ead9e3',rim:'#bca1b9',ink:'#67627b',pond:'#a3b2c9',leaf:'#939a9f',bloom:'#ca8fa6'},{bg:'#f8ecd1',board:'#f3dfb4',rim:'#d0af79',ink:'#84714d',pond:'#adc7bb',leaf:'#91a578',bloom:'#db9e67'},{bg:'#293e4a',board:'#415968',rim:'#718c97',ink:'#d8e5d3',pond:'#527e8c',leaf:'#6c9891',bloom:'#d8aac3'},{bg:'#eee8db',board:'#e4dfcb',rim:'#b4b39b',ink:'#60776b',pond:'#9db9b7',leaf:'#859c8b',bloom:'#d3a897'}];const skins=[['#db997e','#c8ba85','#a4b996','#8db5bd','#b7a5c5'],['#bca0d0','#dc9fae','#b0aed6','#b9c9e0','#d7b6cd'],['#80b4a6','#a3cbb4','#7da8b2','#b8cd9d','#98bebb'],['#cfb98c','#e1ca9c','#afc2c7','#ddbeb0','#cad4c2']];const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
class BloomArt{
constructor(canvas){this.c=canvas;this.ctx=canvas.getContext('2d');this.fx=[];this.t=0;this.cursor=null;this.guide=false;this.winAt=0;this.resize()}
resize(){let r=this.c.getBoundingClientRect();this.w=r.width;this.h=r.height;this.rotate=this.w>this.h*1.25;let ww=this.rotate?700:540,hh=this.rotate?540:700;this.s=Math.min((this.w-30)/ww,(this.h-36)/hh,1.05);this.ox=(this.w-ww*this.s)/2;this.oy=(this.h-hh*this.s)/2+8}
project(x,y){return this.rotate?{x:this.ox+(700-y)*this.s,y:this.oy+x*this.s}:{x:this.ox+x*this.s,y:this.oy+y*this.s}}
unproject(x,y){return this.rotate?{x:(y-this.oy)/this.s,y:700-(x-this.ox)/this.s}:{x:(x-this.ox)/this.s,y:(y-this.oy)/this.s}}
world(){let c=this.ctx;c.translate(this.ox,this.oy);c.scale(this.s,this.s);if(this.rotate){c.translate(700,0);c.rotate(Math.PI/2)}}
rr(x,y,w,h,r,fill,stroke){let c=this.ctx;c.beginPath();c.roundRect(x,y,w,h,r);if(fill){c.fillStyle=fill;c.fill()}if(stroke){c.strokeStyle=stroke;c.lineWidth=1;c.stroke()}}
ellipse(x,y,rx,ry,col){let c=this.ctx;c.beginPath();c.ellipse(x,y,rx,ry,0,0,Math.PI*2);c.fillStyle=col;c.fill()}
line(points,col,width=2){let c=this.ctx;c.beginPath();points.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.strokeStyle=col;c.lineWidth=width;c.lineCap='round';c.lineJoin='round';c.stroke()}
poly(points,fill,stroke){let c=this.ctx;c.beginPath();points.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.closePath();c.fillStyle=fill;c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=.6;c.stroke()}}
label(txt,x,y,size,col,font='system-ui'){let c=this.ctx;c.font=`${size}px ${font}`;c.fillStyle=col;c.textAlign='center';c.textBaseline='middle';c.fillText(txt,x,y)}
rosette(x,y,r,color,open=1){let c=this.ctx;c.save();c.translate(x,y);for(let i=0;i<6;i++){c.save();c.rotate(i*Math.PI/3);this.ellipse(0,-r*.65*open,r*.35,r*.55*open,color);c.restore()}this.ellipse(0,0,r*.25,r*.25,'#f7deb1');c.restore()}
foliage(x,y,r,pal,seed){let c=this.ctx;c.save();c.translate(x,y);for(let i=0;i<7;i++){let a=seed+i*2.399,dx=Math.cos(a)*r*.55,dy=Math.sin(a)*r*.4;c.save();c.translate(dx,dy);c.rotate(a);this.ellipse(0,0,r*.5,r*.2,i%2?pal.leaf:pal.rim+'aa');this.line([[-r*.3,0],[r*.3,0]],'#fff3',.8);c.restore()}c.restore()}
node(t,i,g){let c=this.ctx,s=this.s,p=this.project(t.x,t.y),dx=Math.cos(t.a),dy=Math.sin(t.a),nx=-dy*6,ny=dx*6,travel=Math.sin(t.angle)*29,height=Math.cos(t.angle)*29+3,up=this.project(t.x+dx*travel,t.y+dy*travel),q1=this.project(t.x+nx,t.y+ny),q2=this.project(t.x-nx,t.y-ny),a=this.project(t.x+dx*travel+nx,t.y+dy*travel+ny),b=this.project(t.x+dx*travel-nx,t.y+dy*travel-ny);a.y-=height*s;b.y-=height*s;let color=t.locked?'#bf975c':skins[g.profile.skin][Math.floor(i/6)%5];this.ellipse(p.x+5*s,p.y+3*s,(8+travel*.3)*s,4*s,'#304b3920');let grad=c.createLinearGradient(q1.x,q1.y,a.x,a.y);grad.addColorStop(0,color);grad.addColorStop(.75,color);grad.addColorStop(1,g.profile.skin===3?'#f2ead5':'#ffffffc9');this.poly([q1,q2,b,a],grad,'#46584930');let side={x:b.x+4*s,y:b.y+3*s};this.poly([q2,b,side,{x:q2.x+4*s,y:q2.y+3*s}],color,'#46584930');this.line([[a.x,a.y],[b.x,b.y]],'#fff9',1.6*s);if(t.angle<1.2){let cx=(q1.x+q2.x+a.x+b.x)/4,cy=(q1.y+q2.y+a.y+b.y)/4;this.ellipse(cx,cy,1.5*s,1.5*s,'#fff9e5b0');if(i%3===0)this.ellipse(cx,cy+7*s,1.5*s,1.5*s,'#fff9e5b0')}if(t.sent&&g.phase==='win'&&i%5===0){let grow=clamp((this.t-this.winAt)*1.5-i*.008,0,1);this.rosette(p.x,p.y-4*s,8*s,skins[g.profile.skin][i%5],grow)}}
bell(b,i,pal){let c=this.ctx,p=this.project(b.x,b.y),s=this.s,hit=b.hit;this.ellipse(p.x,p.y+6*s,24*s,9*s,'#274d3a18');this.ellipse(p.x,p.y,24*s,13*s,pal.rim);this.ellipse(p.x,p.y-2*s,21*s,12*s,'#fcf2d3');c.save();c.translate(p.x,p.y-18*s);c.rotate(hit?Math.sin(this.t*16+i)*.1:0);let grad=c.createLinearGradient(-12*s,-15*s,12*s,5*s);grad.addColorStop(0,'#9e8047');grad.addColorStop(.45,'#ffedb0');grad.addColorStop(1,'#c79b50');this.line([[-16*s,18*s],[-16*s,-19*s],[16*s,-19*s],[16*s,18*s]],pal.rim,3*s);this.rr(-3*s,-23*s,6*s,8*s,2*s,'#aa8f56');c.beginPath();c.moveTo(-12*s,6*s);c.quadraticCurveTo(-10*s,-13*s,0,-13*s);c.quadraticCurveTo(10*s,-13*s,12*s,6*s);c.closePath();c.fillStyle=grad;c.fill();this.ellipse(0,7*s,14*s,3*s,'#c29b58');this.ellipse(0,10*s,3*s,3*s,'#9e7b3e');c.restore();if(hit){for(let j=0;j<2;j++){let r=((this.t*23+j*22)%44+10)*s;c.beginPath();c.ellipse(p.x,p.y-14*s,r,r*.45,0,0,Math.PI*2);c.strokeStyle='#f9e6af'+Math.floor((1-r/(55*s))*100+15).toString(16).padStart(2,'0');c.lineWidth=1.4*s;c.stroke()}this.rosette(p.x+18*s,p.y+7*s,9*s,pal.bloom)}else{c.beginPath();c.ellipse(p.x,p.y-6*s,33*s,19*s,0,0,Math.PI*2);c.setLineDash([2*s,5*s]);c.strokeStyle=pal.rim+'88';c.stroke();c.setLineDash([])}}
event(e){if(e.type==='win'){this.winAt=this.t;this.fx.push({type:'win',x:270,y:350,life:0,total:2})}if(['bell','flower','gear','knock','place'].includes(e.type)){this.fx.push({type:e.type,x:e.x,y:e.y,index:e.index||0,life:0,total:e.type==='place'?.23:e.type==='knock'?.35:.8})}if(e.type==='jump')this.fx.push({...e,life:0,total:.5});if(this.fx.length>95)this.fx.splice(0,this.fx.length-95)}
draw(g,dt){this.t+=dt;let c=this.ctx,w=this.w,h=this.h,pal=themes[(g.day-1)%6];c.setTransform(this.c.width/w,0,0,this.c.height/h,0,0);c.clearRect(0,0,w,h);c.fillStyle=pal.bg;c.fillRect(0,0,w,h);let bg=c.createRadialGradient(w*.35,h*.3,0,w*.5,h*.5,Math.max(w,h)*.7);bg.addColorStop(0,'#fff6');bg.addColorStop(1,'#fff0');c.fillStyle=bg;c.fillRect(0,0,w,h);c.save();this.world();this.rr(-7,14,554,700,43,'#304b3d18');this.rr(-5,6,550,700,42,pal.rim);let floor=c.createLinearGradient(0,0,500,680);floor.addColorStop(0,pal.board);floor.addColorStop(1,pal.board);this.rr(0,0,540,700,40,floor);this.rr(10,10,520,680,33,null,'#fff5');this.rr(25,25,490,650,25,null,pal.rim+'66');for(let x=50;x<500;x+=26)for(let y=60;y<650;y+=26)this.ellipse(x,y,.7,.7,pal.rim+'66');for(let k=0;k<4;k++){let x=k%2?510:30,y=k<2?30:665;this.foliage(x,y,37,pal,k*1.3);this.rosette(x+(k%2?-10:10),y,11,pal.bloom);this.rosette(x+(k%2?8:-8),y+11,7,'#f5dbab')}
for(let b of g.level.blocks){if(b.type==='pond'){this.rr(b.x-5,b.y+5,b.w+10,b.h+4,25,pal.rim);this.rr(b.x,b.y,b.w,b.h,23,pal.pond);this.rr(b.x+4,b.y+4,b.w-8,b.h-8,20,null,'#fff4');c.save();c.beginPath();c.roundRect(b.x+4,b.y+4,b.w-8,b.h-8,20);c.clip();for(let j=0;j<5;j++){let y=b.y+15+j*b.h/5;this.line([[b.x+10,y],[b.x+b.w*.3,y+Math.sin(this.t+j)*2],[b.x+b.w-12,y]],'#fff3',1)}this.ellipse(b.x+b.w*.25,b.y+b.h*.58,14,6,'#e6c899');this.ellipse(b.x+b.w*.7,b.y+b.h*.42,10,4,'#f0ddd5');this.ellipse(b.x+35,b.y+24,13,9,pal.leaf);this.rosette(b.x+37,b.y+22,6,pal.bloom);c.restore()}else{this.rr(b.x-4,b.y+8,b.w+8,b.h,19,'#304b3b22');this.rr(b.x,b.y+4,b.w,b.h,18,pal.rim);this.rr(b.x,b.y-2,b.w,b.h-3,17,'#c1c0a2');this.rr(b.x+7,b.y+5,b.w-14,b.h-18,13,'#8c9d7c');this.line([[b.x+18,b.y+13],[b.x+b.w-18,b.y+13]],'#fff4',2);for(let j=0;j<5;j++){let x=b.x+20+(j%3)*(b.w-40)/2,y=b.y+25+Math.floor(j/3)*(b.h-45);this.foliage(x,y,30,pal,j);if(j%2)this.rosette(x+4,y,9,pal.bloom)}}}
for(let a of g.gadgets){if(a.type==='ramp'){this.rr(a.x,a.y,a.w,a.h,15,pal.rim+'33');for(let j=0;j<8;j++){let y=a.y+10+j*(a.h-15)/8;this.line([[a.x+6,y],[a.x+a.w-6,y]],'#fff6',2)}this.label('↑',a.x+a.w/2,a.y+a.h/2,25,pal.ink)}else{if(a.to){c.save();c.setLineDash([4,8]);this.line([[a.x,a.y],[a.to.x,a.to.y]],pal.ink+'55',2);c.restore();this.ellipse(a.to.x,a.to.y,25,17,pal.rim);this.ellipse(a.to.x,a.to.y-3,21,14,'#fbefcf');this.label('↓',a.to.x,a.to.y-3,18,pal.ink)}this.ellipse(a.x,a.y+4,31,21,'#304b3c20');this.ellipse(a.x,a.y,30,22,pal.rim);this.ellipse(a.x,a.y-3,25,19,'#f8ebcc');c.save();c.translate(a.x,a.y-3);c.rotate(a.hit?this.t*(a.type==='turn'?2:1):0);for(let j=0;j<8;j++){c.save();c.rotate(j*Math.PI/4);this.rr(-2,-23,4,7,1,pal.rim);c.restore()}if(a.type==='spring'){for(let j=0;j<5;j++)this.ellipse(0,j*3-9,12,3,pal.rim);this.line([[-13,-11],[13,-11]],'#fff5',2)}else{for(let j=0;j<3;j++){let r=j*Math.PI*2/3;this.line([[0,0],[Math.cos(r)*15,Math.sin(r)*15]],pal.ink,3);this.ellipse(Math.cos(r)*15,Math.sin(r)*15,3,3,pal.bloom)}this.ellipse(0,0,5,5,'#c9a76a')}c.restore()}}
let show=this.guide||(g.day===1&&g.tiles.length<7);if(show){c.save();c.setLineDash([2,12]);c.strokeStyle=pal.ink+'66';c.lineWidth=2;for(let path of g.level.paths){c.beginPath();path.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.stroke()}c.restore()}
for(let f of g.flowers){if(f.hit)this.rosette(f.x,f.y,14,pal.bloom);else{c.beginPath();c.arc(f.x,f.y,12,0,Math.PI*2);c.strokeStyle=pal.rim;c.setLineDash([2,3]);c.stroke();c.setLineDash([]);this.rosette(f.x,f.y,8,pal.bloom,.5)}}let start=g.level.start;c.beginPath();c.ellipse(start.x,start.y,32,22,0,0,Math.PI*2);c.strokeStyle='#bc9459';c.lineWidth=2;c.stroke();this.label('↗',start.x-25,start.y+29,16,pal.ink);c.restore();
let sorted=g.tiles.map((t,i)=>({t,i,p:this.project(t.x,t.y)})).sort((a,b)=>a.p.y-b.p.y);for(let n of sorted)this.node(n.t,n.i,g);for(let i=0;i<g.bells.length;i++)this.bell(g.bells[i],i,pal);
for(let f of this.fx){f.life+=dt;let p=this.project(f.x,f.y),a=1-f.life/f.total,s=this.s;c.save();if(['place','knock','bell','gear','flower'].includes(f.type)){let rr=f.type==='place'?8+f.life*30:12+f.life*55;c.globalAlpha=Math.max(0,a*.65);c.beginPath();c.ellipse(p.x,p.y,rr*s,rr*.6*s,0,0,Math.PI*2);c.strokeStyle=f.type==='knock'?skins[g.profile.skin][Math.floor(f.index/6)%5]:'#fff7db';c.lineWidth=(f.type==='bell'?3:1.5)*s;c.stroke();if(f.type==='bell'||f.type==='flower'){for(let j=0;j<8;j++){let an=j*Math.PI/4,rr2=f.life*45;this.ellipse(p.x+Math.cos(an)*rr2*s,p.y+Math.sin(an)*rr2*s-20*f.life*s,3*s,5*s,pal.bloom)}}}if(f.type==='jump'){let q=this.project(f.to.x,f.to.y),t=clamp(f.life/.5,0,1);c.globalAlpha=1;this.rosette(p.x+(q.x-p.x)*t,p.y+(q.y-p.y)*t-Math.sin(t*Math.PI)*75*s,8*s,'#efd6a1')}if(f.type==='win'){c.globalAlpha=Math.max(0,a*.3);let q=this.project(270,350);c.beginPath();c.arc(q.x,q.y,f.life*210*s,0,Math.PI*2);c.strokeStyle=pal.bloom;c.lineWidth=15*s;c.stroke()}c.restore()}this.fx=this.fx.filter(f=>f.life<f.total);
if(this.cursor&&g.phase==='edit'){let p=this.project(this.cursor.x,this.cursor.y);c.beginPath();c.arc(p.x,p.y,13,0,Math.PI*2);c.strokeStyle=g.valid(this.cursor)?'#6d8e72aa':'#c87365bb';c.lineWidth=1.5;c.stroke()}
if(this.w>1000){this.label('DRAW A LITTLE WONDER',this.ox*.5,h*.4,10,pal.ink);this.label('ONE PUSH',w-this.ox*.5,h*.4,15,pal.ink,'Georgia');this.label('A lovely chain reaction.',w-this.ox*.5,h*.4+27,10,pal.ink);c.save();c.translate(0,0);this.rosette(this.ox*.5,h*.4+46,17,pal.bloom);c.restore()}
}
}root.BloomArt=BloomArt})(globalThis);

