(function(root){const chapters=[{name:'First little sparks',place:'THE SLEEPING WORKSHOP',color:'#d9c884'},{name:'A head of your own',place:'THE COPPER GARDEN',color:'#9ebfaa'},{name:'The light comes home',place:'THE MIDNIGHT ENGINE',color:'#c5aacc'}],levels=[];
function make(name,chapter,build,hints){const s={w:12,h:12,grid:Array.from({length:12},()=>Array(12).fill('.')),devices:[],chips:[],exit:[10,9],exitTerminal:null,pos:[1,9],face:1,attached:true,head:null,moves:0,failed:false,won:false};const line=(x,y,w,h=1,t='#')=>{for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++)s.grid[yy][xx]=t};const metal=(x,y,w,h=1)=>line(x,y,w,h,'M');const device=(kind,cells,terminal)=>s.devices.push({kind,cells,terminal});const bridge=(x,y,n,terminal)=>device('bridge',Array.from({length:n},(_,i)=>[x+i,y]),terminal);const gate=(x,y,n,terminal)=>device('gate',Array.from({length:n},(_,i)=>[x,y+i]),terminal);const laser=(x,y,n,terminal)=>device('laser',Array.from({length:n},(_,i)=>[x,y+i]),terminal);build({s,line,metal,bridge,gate,laser,chip:(x,y)=>s.chips.push([x,y]),exit:(x,y,t=null)=>{s.exit=[x,y];s.exitTerminal=t},start:(x,y,f=1)=>{s.pos=[x,y];s.face=f}});s.grid=s.grid.map(r=>r.join(''));levels.push({name,chapter,initial:s,hints,solution:null})}
make('A touch of light',0,({metal,chip,exit})=>{metal(1,10,10,2);chip(5,9);exit(10,9,[10,10])},['Your helmet lights every connected copper tile.','Walk across the glowing floor.','Pick up the little spark and enter the lamp.']);
make('The sleeping bridge',0,({metal,line,bridge,chip,exit})=>{metal(0,10,4,2);line(7,10,4,2);bridge(4,10,3,[3,10]);chip(6,9);exit(10,9)},['The dotted bridge wakes when the copper is lit.','Stay in contact with copper, or leave your helmet on it.','Stand at the left edge, face left, and toss your helmet onto the copper.']);
make('A little leap',0,({metal,line,chip,exit})=>{metal(1,10,4,2);line(5,8,2,4);metal(7,10,4,2);chip(6,7);exit(10,9)},['Jump travels two tiles in the direction you face.','Walk to the edge of the raised block, then jump.','Collect the spark on top before walking down.']);
make('Open sesame',0,({metal,gate,chip,exit})=>{metal(1,10,10,2);gate(6,6,4,[2,10]);chip(8,9);exit(10,9)},['Copper powers the tall door too.','A glowing door is open.','Walk right while the connected floor stays lit.']);
make('Leave a little light',1,({metal,line,bridge,chip,exit})=>{line(0,10,3,2);metal(3,10,2,2);line(9,10,3,2);bridge(5,10,4,[4,10]);chip(8,9);exit(10,9)},['Your body cannot power copper without its helmet.','Toss the helmet onto the copper before crossing.','From the stone on the left, throw right. Leave it behind to keep the bridge lit.']);
make('A quiet crossing',1,({metal,laser,chip,exit})=>{metal(1,10,10,2);laser(6,5,5,[2,10]);chip(9,9);exit(10,9)},['This beam wakes with the copper floor.','A jump cuts contact while you are in the air.','Jump over the beam without letting your helmet touch copper beside it.']);
make('The second shore',1,({line,metal,bridge,chip,exit,start})=>{line(0,10,4,2);metal(4,10,1,2);line(9,8,3,4);bridge(5,10,4,[4,10]);chip(8,9);exit(10,7);start(2,9)},['Send your helmet to the small copper island.','Walk over the bridge while it stays lit.','Jump up to the higher lamp from the end of the bridge.']);
make('Around the corner',1,({line,metal,gate,chip,exit})=>{line(0,10,12,2);metal(3,10,2,2);metal(4,8,1,2);gate(8,6,4,[4,8]);chip(9,9);exit(10,9)},['Copper connects around a corner, not across empty space.','Leave the helmet at the foot of the copper column.','Go over the column, then through its powered door.']);
make('A spark upstairs',2,({line,metal,gate,chip,exit})=>{line(0,10,12,2);line(5,9,2,1);metal(5,8,2,1);line(7,7,1,3);gate(9,5,5,[5,8]);chip(6,7);exit(10,9)},['The high copper controls the door below.','Jump onto the ledge, take the spark, and leave your helmet there.','Walk down headless. The helmet keeps the door open.']);
make('Two little circuits',2,({line,metal,gate,laser,chip,exit})=>{line(0,10,12,2);metal(2,10,2,2);metal(7,10,2,2);gate(5,6,4,[2,10]);laser(9,5,5,[7,10]);chip(10,9);exit(11,9)},['The two copper patches do not share power.','Leave your helmet on the first patch to open its door.','Cross the second patch headless so its beam stays asleep.']);
make('The long way round',2,({line,metal,gate,chip,exit,start})=>{line(0,10,12,2);line(4,9,2,1);metal(5,8,3,1);gate(8,5,5,[5,8]);chip(2,7);chip(10,9);exit(11,9);start(1,9)},['You can turn around before jumping.','The first spark hangs above the starting floor.','Leave light on the high copper, then carry the other spark home.']);
make('Goodnight, little engine',2,({line,metal,bridge,gate,laser,chip,exit,start})=>{line(0,10,3,2);metal(3,10,2,2);bridge(5,10,4,[3,10]);line(9,8,3,4);gate(10,5,3,[3,10]);chip(7,9);chip(9,7);exit(11,7);start(1,9)},['One little helmet can light the bridge and the final door.','Toss it onto the copper and leave it there.','Cross, collect both sparks, then jump to the engine lamp.']);
const out={chapters,levels};if(typeof module==='object')module.exports=out;else root.SparkLevels=out})(typeof window!=='undefined'?window:globalThis);
