(function(root){'use strict';const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),route=[{x:110,y:560},{x:90,y:400},{x:110,y:220},{x:250,y:160},{x:410,y:220},{x:450,y:400},{x:420,y:570},{x:275,y:610}],reefs=['Sunlit lagoon','Coral carnival','Blue cathedral','Moonlit drift'];
function makeRun(stage){let quota=Math.min(7,3+Math.floor((stage-1)/2)),angle=(stage-1)%4,points=route.map(a=>({x:stage%2===0?540-a.x:a.x,y:a.y})),babies=points.slice(0,quota).map((a,i)=>({...a,id:i})),pearls=[];for(let i=0;i<points.length;i++){let a=points[i],b=points[(i+1)%points.length];for(let j=0;j<5;j++){let t=j/5;pearls.push({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,id:pearls.length})}}return{stage,quota,waypoints:points,phase:'play',x:270,y:610,vx:0,vy:0,angle:-Math.PI/2,hp:3,inv:0,dash:0,cool:0,time:0,score:0,combo:0,comboTime:0,maxCombo:0,pearls:0,rescued:0,babies,coins:pearls,followers:[],jellies:[{x:245,y:300,r:31,phase:.4},{x:330,y:460,r:33,phase:2.1},...(stage>=5?[{x:165,y:475,r:27,phase:3.4}]:[])],predators:stage>=2?[{x:300,y:355,homeX:300,homeY:355,phase:'rest',timer:4.2,dx:0,dy:0,angle:0},...(stage>=8?[{x:270,y:280,homeX:270,homeY:280,phase:'rest',timer:6.5,dx:0,dy:0,angle:0}]:[])]:[],hitFlash:0,paid:false,reward:0,stars:0,reef:angle}}
class Game{constructor(s){this.profile={stage:1,coins:0,best:0,wins:0,fin:0,current:0,glow:0,...s?.profile};this.run=s?.run||null;this.mute=s?.mute||false;this.events=[]}start(){this.run=makeRun(this.profile.stage);return this.run}get speed(){return 185+this.profile.fin*18}get cooldown(){return 5.5-this.profile.current*.65}dash(){let r=this.run;if(!r||r.phase!=='play'||r.cool>0)return false;r.dash=.38;r.inv=Math.max(r.inv,.44);r.cool=this.cooldown;this.events.push({type:'dash',x:r.x,y:r.y});return true}buy(k){if(!['fin','current','glow'].includes(k)||this.run?.phase==='play')return false;let n=this.profile[k],cost=this.cost(k);if(n>=3||this.profile.coins<cost)return false;this.profile.coins-=cost;this.profile[k]++;return true}cost(k){return(k==='fin'?6:8)+this.profile[k]*6}finish(win){let r=this.run;if(!r||r.phase!=='play'||r.paid)return false;r.phase=win?'win':'fail';r.stars=win?(r.hp===3&&r.pearls>=30?3:r.hp>=2?2:1):0;r.reward=win?4+Math.floor(r.pearls/5)+r.stars:Math.min(3,Math.floor(r.score/90));r.paid=true;this.profile.coins+=r.reward;this.profile.best=Math.max(this.profile.best,r.score);if(win){this.profile.stage++;this.profile.wins++}this.events.push({type:win?'win':'fail',x:r.x,y:r.y});return true}hit(){let r=this.run;if(r.inv>0||r.phase!=='play')return;r.hp--;r.inv=1.6;r.hitFlash=.35;r.combo=0;r.followers.forEach((a,i)=>{let angle=i*Math.PI*2/Math.max(1,r.followers.length);a.x=clamp(r.x+Math.cos(angle)*48,48,492);a.y=clamp(r.y+Math.sin(angle)*48,108,652)});this.events.push({type:'hit',x:r.x,y:r.y});if(r.hp<=0)this.finish(false)}step(dt,target){let r=this.run;if(!r||r.phase!=='play')return;dt=clamp(dt,0,1/30);r.time+=dt;r.inv=Math.max(0,r.inv-dt);r.dash=Math.max(0,r.dash-dt);r.cool=Math.max(0,r.cool-dt);r.hitFlash=Math.max(0,r.hitFlash-dt);r.comboTime=Math.max(0,r.comboTime-dt);if(!r.comboTime)r.combo=0;let dx=target?target.x-r.x:0,dy=target?target.y-r.y:0,len=Math.hypot(dx,dy),spd=this.speed*(r.dash>0?2.7:1),vx=len>4?dx/len*Math.min(spd,len*7):0,vy=len>4?dy/len*Math.min(spd,len*7):0;r.vx+=(vx-r.vx)*Math.min(1,dt*12);r.vy+=(vy-r.vy)*Math.min(1,dt*12);r.x=clamp(r.x+r.vx*dt,48,492);r.y=clamp(r.y+r.vy*dt,108,652);if(Math.hypot(r.vx,r.vy)>8)r.angle=Math.atan2(r.vy,r.vx);
for(let i=r.coins.length-1;i>=0;i--){let a=r.coins[i],d=dist(a,r),mag=25+this.profile.glow*9;if(d<mag){r.coins.splice(i,1);r.pearls++;r.combo++;r.comboTime=2.2;r.maxCombo=Math.max(r.maxCombo,r.combo);let mult=1+Math.min(4,Math.floor(r.combo/8));r.score+=10*mult;this.events.push({type:'pearl',x:a.x,y:a.y,combo:r.combo,mult})}else if(d<mag+20){a.x+=(r.x-a.x)*dt*3;a.y+=(r.y-a.y)*dt*3}}
for(let i=r.babies.length-1;i>=0;i--){let a=r.babies[i];if(dist(a,r)<30){r.babies.splice(i,1);r.rescued++;r.score+=50;r.followers.push({x:a.x,y:a.y,angle:r.angle});this.events.push({type:'rescue',x:a.x,y:a.y})}}
for(let i=0;i<r.followers.length;i++){let a=r.followers[i],lead=i===0?r:r.followers[i-1],dx=lead.x-a.x,dy=lead.y-a.y,l=Math.hypot(dx,dy),wanted=20+Math.sin(r.time*5+i)*3;if(l>wanted){let sp=Math.min(340,(l-wanted)*8);a.x+=dx/l*sp*dt;a.y+=dy/l*sp*dt;a.angle=Math.atan2(dy,dx)}}
for(let a of r.jellies){let rad=a.r+Math.sin(r.time*2+a.phase)*5;if(dist(a,r)<rad+12)this.hit()}
for(let a of r.predators){a.timer-=dt;if(a.phase==='rest'){a.x+=(a.homeX-a.x)*dt*1.8;a.y+=(a.homeY-a.y)*dt*1.8;if(a.timer<=0){a.phase='warn';a.timer=.9;let d=Math.hypot(r.x-a.x,r.y-a.y)||1;a.dx=(r.x-a.x)/d;a.dy=(r.y-a.y)/d;a.angle=Math.atan2(a.dy,a.dx);this.events.push({type:'warn',x:a.x,y:a.y})}}else if(a.phase==='warn'){if(a.timer<=0){a.phase='lunge';a.timer=.85}}else if(a.phase==='lunge'){let speed=Math.min(350,260+r.stage*5);a.x+=a.dx*speed*dt;a.y+=a.dy*speed*dt;if(dist(a,r)<26)this.hit();if(a.timer<=0||a.x<50||a.x>490||a.y<110||a.y>650){a.phase='rest';a.timer=Math.max(3,5.4-r.stage*.08)}}}
if(r.rescued>=r.quota&&Math.hypot(r.x-270,r.y-105)<40)this.finish(true);if(this.events.length>100)this.events=this.events.slice(-100)}snapshot(){return{profile:this.profile,run:this.run,mute:this.mute}}}
const api={Game,makeRun,route,reefs,dist};if(typeof module!=='undefined')module.exports=api;root.Shoal=api;})(typeof window!=='undefined'?window:globalThis);


