'use strict';
try{window.IsleArt=(()=>{
const T=THREE,scene=new T.Scene(),camera=new T.PerspectiveCamera(42,innerWidth/innerHeight,.1,140),renderer=new T.WebGLRenderer({antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputEncoding=T.sRGBEncoding;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;document.querySelector('#world').append(renderer.domElement);scene.background=new T.Color('#b8dadd');scene.fog=new T.Fog('#bedddd',25,74);
const group=new T.Group();scene.add(group);const rng=(()=>{let s=838417;return ()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296}})(),mats=[],treeMats=[],groundMats=[],leaves=[],panels=[],ghosts=[];let biome=0,solved=false,power=0,look=0,view=false,time=0,travel=0,oldBiome=-1;
function mat(color,roughness=.95,metalness=0){let m=new T.MeshStandardMaterial({color,roughness,metalness});mats.push(m);return m}
const stone=mat('#d5c8a7'),stoneEdge=mat('#ac9e82'),wood=mat('#594232'),bronze=mat('#80693e',.48,.48),dark=mat('#26382c',.6,.2),lit=new T.MeshBasicMaterial({color:'#ffe989'}),wiremat=mat('#423d2a'),waterColor=new T.Color('#31ada6');
function noiseTexture(){let c=document.createElement('canvas');c.width=c.height=256;let a=c.getContext('2d');a.fillStyle='#ad9971';a.fillRect(0,0,256,256);for(let i=0;i<3500;i++){a.fillStyle=i%2?'#f3e7bc18':'#2b251819';a.fillRect(rng()*256,rng()*256,rng()*10+1,rng()*3+1)}for(let i=0;i<6;i++){a.strokeStyle='#48382730';a.beginPath();a.moveTo(rng()*256,0);a.lineTo(rng()*256,256);a.stroke()}let t=new T.CanvasTexture(c);t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(3,3);return t}let grain=noiseTexture();stone.bumpMap=grain;stone.bumpScale=.028;bronze.bumpMap=grain;bronze.bumpScale=.013;
const geos={box:new T.BoxGeometry(1,1,1),sphere:new T.IcosahedronGeometry(1,1),cyl:new T.CylinderGeometry(1,1,1,8),leaf:new T.IcosahedronGeometry(1,1)};function mesh(type,m,x,y,z,sx,sy,sz,parent=group){let o=new T.Mesh(geos[type],m);o.position.set(x,y,z);o.scale.set(sx,sy,sz);o.castShadow=o.receiveShadow=true;parent.add(o);return o}function beam(a,b,r,m,parent=group){let mid=a.clone().add(b).multiplyScalar(.5),o=mesh('cyl',m,mid.x,mid.y,mid.z,r,a.distanceTo(b),r,parent);o.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),b.clone().sub(a).normalize());return o}
let amb=new T.HemisphereLight('#e3eff2','#536f48',.55);scene.add(amb);let sun=new T.DirectionalLight('#fff1c4',1.1);sun.position.set(-13,25,13);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-22,right:22,top:22,bottom:-22,near:1,far:70});sun.shadow.bias=-.001;sun.shadow.normalBias=.05;scene.add(sun);
// A gradient sky, distant rock ridges and animated water use no downloaded assets.
let sky=new T.Mesh(new T.SphereGeometry(95,24,12),new T.ShaderMaterial({side:T.BackSide,vertexShader:'varying float h;void main(){h=position.y/95.;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying float h;void main(){vec3 low=vec3(.78,.87,.84),high=vec3(.27,.62,.76);gl_FragColor=vec4(mix(low,high,clamp(h*.85+.12,0.,1.)),1.);}'}));scene.add(sky);
let wg=new T.PlaneGeometry(140,140,36,36);wg.rotateX(-Math.PI/2);let wm=new T.ShaderMaterial({uniforms:{time:{value:0}},vertexShader:'uniform float time;varying vec3 v;void main(){vec3 p=position;p.y+=sin(p.x*.45+time*.55)*.025+cos(p.z*.35-time*.7)*.02;v=p;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}',fragmentShader:'uniform float time;varying vec3 v;void main(){float w=sin(v.x*1.3+sin(v.z*.7)+time*.4)*sin(v.z*1.7-time*.7);vec3 c=mix(vec3(.10,.48,.50),vec3(.24,.68,.65),w*.3+.65);float spark=pow(max(0.,w),14.);gl_FragColor=vec4(c+vec3(.2)*spark,1.);}'});let water=new T.Mesh(wg,wm);water.position.y=-.5;scene.add(water);
let terrainGeo=new T.PlaneGeometry(60,60,38,38);terrainGeo.rotateX(-Math.PI/2);let ps=terrainGeo.attributes.position;for(let i=0;i<ps.count;i++){let x=ps.getX(i),z=ps.getZ(i),edge=Math.max(Math.abs(x),Math.abs(z));ps.setY(i,Math.sin(x*.18)*Math.cos(z*.19)*.25+(edge>23?-(edge-23)*.65:0))}terrainGeo.computeVertexNormals();let ground=mat('#c5ba77');groundMats.push(ground);let terrain=new T.Mesh(terrainGeo,ground);terrain.receiveShadow=true;group.add(terrain);
let mountainMat=mat('#779b9b');for(let i=0;i<10;i++){let x=-48+i*11,z=-49-rng()*10,y=3+rng()*4;mesh('sphere',mountainMat,x,y-4,z,8+rng()*5,y+4,9+rng()*6).castShadow=false}
// Paths, stones and grass are instanced by material.
let matrix=new T.Matrix4(),quat=new T.Quaternion(),pos=new T.Vector3(),scl=new T.Vector3();function instanced(type,m,items,shadow=true){let o=new T.InstancedMesh(geos[type],m,items.length);for(let [i,a]of items.entries()){pos.set(a[0],a[1],a[2]);quat.setFromEuler(new T.Euler(a[6]||0,a[7]||0,a[8]||0));scl.set(a[3],a[4],a[5]);matrix.compose(pos,quat,scl);o.setMatrixAt(i,matrix)}o.castShadow=shadow;o.receiveShadow=true;group.add(o);return o}
let pathItems=[];for(let i=0;i<28;i++){let z=6-i*.8,x=Math.sin(i*.22)*.9;for(let j=-1;j<=1;j++)pathItems.push([x+j*.73,.045,z,.7,.13,.68,0,(rng()-.5)*.07,0])}instanced('box',stone,pathItems);
let rockmat=mat('#b8b29b'),rocks=[];for(let i=0;i<100;i++){let x=(rng()-.5)*47,z=(rng()-.5)*46;if(Math.abs(x)<3&&z>-11&&z<8)continue;let s=.13+rng()*.7;rocks.push([x,s*.27,z,s,s*.58,s*.65,0,rng()*6,0])}instanced('sphere',rockmat,rocks);
let grassMat=mat('#849d54');groundMats.push(grassMat);let grass=[];for(let i=0;i<780;i++){let x=(rng()-.5)*47,z=(rng()-.5)*46;if(Math.abs(x)<2.7&&z>-13&&z<8)continue;let s=.1+rng()*.18;grass.push([x,s*.7,z,s*.6,s*1.6,s*.45,0,rng()*6,0])}instanced('sphere',grassMat,grass,false);
let leafMatColors=['#82a747','#a5be54','#668d4f','#bbc572'];for(let col of leafMatColors)treeMats.push(mat(col));let trunkItems=[],branchItems=[],foliage=[[],[],[],[]];
let trees=[[-6,1,-1],[6,1,-2],[-8,1,-7],[7,1,-11],[-12,1,-15],[13,1,-17],[-4,1,-18],[4,1,-23],[-15,1,-24],[17,1,-24],[-11,1,8],[11,1,9],[-18,1,-3],[19,1,-5]];
for(let [tx,_,tz]of trees){let h=4.5+rng()*3;trunkItems.push([tx,h/2,tz,.15+rng()*.06,h,.18,0,(rng()-.5)*.2,(rng()-.5)*.07]);for(let i=0;i<8;i++){let a=i*2.4,l=1.3+rng()*1.7,by=h*(.35+i*.07),bx=tx+Math.cos(a)*l,bz=tz+Math.sin(a)*l;let aa=new T.Vector3(tx,by,tz),bb=new T.Vector3(bx,by+1.3,bz),mid=aa.clone().add(bb).multiplyScalar(.5),q=new T.Quaternion().setFromUnitVectors(new T.Vector3(0,1,0),bb.clone().sub(aa).normalize()),e=new T.Euler().setFromQuaternion(q);branchItems.push([mid.x,mid.y,mid.z,.07,aa.distanceTo(bb),.07,e.x,e.y,e.z]);for(let j=0;j<9;j++){let s=.35+rng()*.55;foliage[i%4].push([bx+(rng()-.5)*1.9,by+1+(rng()-.5)*1.4,bz+(rng()-.5)*1.9,s,s*.75,s*.85,0,rng()*6,0])}}}
instanced('cyl',wood,trunkItems);instanced('cyl',wood,branchItems);for(let i=0;i<4;i++)leaves.push(instanced('leaf',treeMats[i],foliage[i]));
// A weathered arch and a powered gate sit beyond the foreground instrument.
let arch=new T.Group();arch.position.set(0,0,-10.5);group.add(arch);for(let side of [-1,1])for(let j=0;j<7;j++)mesh('box',j%2?stone:stoneEdge,side*2.0,.25+j*.48,0,.8,.45,.85,arch);for(let i=0;i<10;i++){let a=Math.PI*i/10,b=Math.PI*(i+1)/10,mid=(a+b)/2,o=mesh('box',i%2?stone:stoneEdge,Math.cos(mid)*2,3+Math.sin(mid)*2,0,.72,.68,.83,arch);o.rotation.z=mid-Math.PI/2}for(let i=0;i<9;i++)mesh('box',stone,-4-i*.65,.55+(i%3)*.25,-11.3,.6,.9+(i%3)*.5,.75);let gate=new T.Group();arch.add(gate);let gateL=new T.Group(),gateR=new T.Group();gate.add(gateL,gateR);for(let side of [-1,1]){let g=side<0?gateL:gateR;for(let i=0;i<5;i++)mesh('box',wood,side*(.2+i*.32),1.4,.08,.18,2.7,.12,g);for(let y of [.55,2.25])mesh('box',bronze,side*.82,y,.17,1.7,.1,.08,g)}
let tower=new T.Group();tower.position.set(-8,0,-18);group.add(tower);for(let j=0;j<9;j++)mesh('box',j%2?stone:stoneEdge,0,j*.44+.2,0,1.5-j*.05,.42,1.5-j*.05,tower);mesh('box',bronze,0,4.1,0,1.2,.3,1.2,tower);let laser=new T.Mesh(new T.CylinderGeometry(.018,.035,70,7),lit);laser.position.set(-8,39,-18);laser.visible=false;group.add(laser);let beaconLamp=mesh('sphere',lit,-8,4.5,-18,.18,.18,.18);beaconLamp.visible=false;
// Stand, bevelled instrument housing, individual screws and power cable.
const stand=new T.Group();group.add(stand);mesh('box',dark,0,.95,-.2,.23,1.9,.3,stand);mesh('box',bronze,0,.12,-.2,1.15,.14,.65,stand);mesh('box',bronze,0,2.45,-.15,3.68,3.68,.24,stand);mesh('box',dark,0,2.45,.005,3.42,3.42,.055,stand);let texture=new T.CanvasTexture(document.createElement('canvas'));texture.image.width=texture.image.height=1024;texture.encoding=T.sRGBEncoding;texture.minFilter=T.LinearFilter;texture.magFilter=T.LinearFilter;let panelMesh=new T.Mesh(new T.PlaneGeometry(3.22,3.22),new T.MeshBasicMaterial({map:texture,toneMapped:false}));panelMesh.position.set(0,2.45,.045);stand.add(panelMesh);for(let x of [-1.73,1.73])for(let y of [.72,4.18]){let bolt=mesh('cyl',stoneEdge,x,y,.08,.045,.035,.045,stand);bolt.rotation.x=Math.PI/2;mesh('box',dark,x,y,.105,.046,.012,.008,stand)}let led=mesh('box',new T.MeshBasicMaterial({color:'#454b30'}),1.74,2.45,.065,.035,.23,.02,stand);let wireCurve=new T.CatmullRomCurve3([new T.Vector3(1.82,1.3,-.18),new T.Vector3(2.0,.25,-.8),new T.Vector3(2.8,.1,-3),new T.Vector3(2.4,.1,-7),new T.Vector3(2.3,.3,-9),new T.Vector3(1.85,2.0,-10.5)]);let cable=new T.Mesh(new T.TubeGeometry(wireCurve,50,.055,7,false),wiremat);group.add(cable);let poweredCable=new T.Mesh(new T.TubeGeometry(wireCurve,50,.018,6,false),lit);poweredCable.visible=false;group.add(poweredCable);let pulse=new T.Mesh(new T.SphereGeometry(.09,10,8),lit);pulse.visible=false;group.add(pulse);
let dustgeo=new T.BufferGeometry(),dustpos=new Float32Array(60*3);for(let i=0;i<60;i++){dustpos[i*3]=(rng()-.5)*22;dustpos[i*3+1]=rng()*7+.1;dustpos[i*3+2]=-rng()*22}dustgeo.setAttribute('position',new T.BufferAttribute(dustpos,3));let dust=new T.Points(dustgeo,new T.PointsMaterial({color:'#f4d396',size:.045,transparent:true,opacity:.55,depthWrite:false}));group.add(dust);
// Merge opaque, stationary meshes by material; keep animated gates and the face separate.
function batchStatics(){group.updateMatrixWorld(true);let buckets=new Map(),skip=new Set([panelMesh,gateL,gateR,laser,beaconLamp,led,pulse,poweredCable]);function excluded(o){for(let p=o;p&&p!==group;p=p.parent)if(skip.has(p))return true;return false}group.traverse(o=>{if(o.isMesh&&!o.isInstancedMesh&&!excluded(o)&&!o.material.transparent){let a=buckets.get(o.material)||[];a.push(o);buckets.set(o.material,a)}});for(let [material,objects]of buckets){if(objects.length<2)continue;let pp=[],nn=[],uv=[];for(let o of objects){let g=o.geometry.clone().applyMatrix4(o.matrixWorld);if(g.index)g=g.toNonIndexed();pp.push(...g.attributes.position.array);nn.push(...g.attributes.normal.array);if(g.attributes.uv)uv.push(...g.attributes.uv.array);g.dispose()}let g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(pp,3));g.setAttribute('normal',new T.Float32BufferAttribute(nn,3));if(uv.length===pp.length/3*2)g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.computeBoundingSphere();let m=new T.Mesh(g,material);m.castShadow=m.receiveShadow=true;scene.add(m);objects.forEach(o=>o.parent.remove(o))}}batchStatics();
const palettes=[{ground:'#c8bf85',grass:'#819d50',trees:['#80a544','#a4bd53','#638d49','#c0c875'],fog:'#bddece',sun:'#fff0c5'},{ground:'#caa263',grass:'#a18945',trees:['#cc6228','#ef9d37','#bc4b21','#e9be55'],fog:'#dacba9',sun:'#ffdfad'},{ground:'#c0bbaa',grass:'#698272',trees:['#709186','#9ba997','#486e66','#c7c7ad'],fog:'#c7d7d0',sun:'#fff3d7'},{ground:'#c4bd9c',grass:'#7c9b60',trees:['#df88a1','#f4b1ba','#b96185','#f8d0c5'],fog:'#e0d4cd',sun:'#fff0e0'}];
function setBiome(b){biome=b;if(b===oldBiome)return;oldBiome=b;let p=palettes[b];ground.color.set(p.ground);grassMat.color.set(p.grass);treeMats.forEach((m,i)=>m.color.set(p.trees[i]));scene.fog.color.set(p.fog);sun.color.set(p.sun);dust.material.color.set(b===3?'#ffd4e2':b===1?'#f3aa54':'#cce9b1');stone.color.set(b===2?'#d1d0bf':b===3?'#e8d6bd':'#d5c8a7');renderer.shadowMap.needsUpdate=true}
function reset(b){setBiome(b);solved=false;power=0;gateL.position.x=gateR.position.x=0;poweredCable.visible=pulse.visible=false;laser.visible=beaconLamp.visible=false;led.material.color.set('#454b30');view=false;look=0;travel=0;renderer.shadowMap.needsUpdate=true}
function solve(milestone){solved=true;power=0;poweredCable.visible=pulse.visible=true;led.material.color.set('#fff3a0');if(milestone){laser.visible=beaconLamp.visible=true}}
function resize(){let w=innerWidth,h=innerHeight;renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}
let ray=new T.Raycaster(),v=new T.Vector2();function hit(x,y){v.set(x/innerWidth*2-1,1-y/innerHeight*2);ray.setFromCamera(v,camera);let h=ray.intersectObject(panelMesh,false)[0];return h?{x:h.uv.x*1024,y:(1-h.uv.y)*1024}:null}function project(u,v){let p=new T.Vector3((u/1024-.5)*3.22,2.45+(.5-v/1024)*3.22,.045);p.project(camera);return {x:(p.x*.5+.5)*innerWidth,y:(.5-p.y*.5)*innerHeight}}
function draw(dt){time+=dt;wm.uniforms.time.value=time;travel+=dt;if(solved){power=Math.min(1,power+dt*.7);let ease=power*power*(3-2*power);gateL.position.x=-ease*1.7;gateR.position.x=ease*1.7;pulse.position.copy(wireCurve.getPoint(Math.min(.999,power)));pulse.visible=power<1;if(power>=1&&power-dt*.7<1)renderer.shadowMap.needsUpdate=true}dust.rotation.y=Math.sin(time*.05)*.025;let a=dustgeo.attributes.position;for(let i=0;i<60;i++){let y=a.getY(i)-dt*.055;if(y<.1)y=6;a.setY(i,y)}a.needsUpdate=true;
let aspect=innerWidth/innerHeight,dist=Math.max(7.7,3.22/(Math.tan(21*Math.PI/180)*aspect)*.61,(innerWidth<600&&innerHeight>500)?3.68*innerHeight/(2*Math.tan(21*Math.PI/180)*Math.max(210,innerHeight-370)):0),portrait=innerWidth<600&&innerHeight>500,baseY=portrait?2.8:2.85,scenic=(view||solved)?1:0,ang=scenic*(.55+look);let desired=new T.Vector3(Math.sin(ang)*dist,baseY+scenic*1.1,Math.cos(ang)*dist),aim=new T.Vector3(0,2.45-scenic*.55,-scenic*3);let k=1-Math.exp(-dt*3);if(travel<.02){camera.position.copy(desired)}else camera.position.lerp(desired,k);camera.lookAt(aim);renderer.render(scene,camera)}
addEventListener('resize',resize);camera.position.set(0,2.85,9);camera.lookAt(0,2.45,0);reset(0);return {renderer,texture,panel:panelMesh,hit,project,draw,reset,solve,view:v=>{view=v},look:d=>{look=Math.max(-.65,Math.min(.75,look+d))},info:()=>({calls:renderer.info.render.calls,triangles:renderer.info.render.triangles}),resize};
})();

}catch(e){document.getElementById('world').innerHTML=`<div style="position:absolute;inset:35% 10%;text-align:center;font:20px Georgia">This garden needs WebGL.<br><small>Please open it in Safari, Chrome or Edge with graphics acceleration enabled.</small></div>`;console.error(e)}
