'use strict';
(()=>{if(!window.IsleArt)return;const M=IsleModel,A=IsleArt,$=id=>document.getElementById(id),C=A.texture.image,c=C.getContext('2d'),names=['THE SUNLIT GLADE','THE AMBER ORCHARD','THE STONE QUARTER','THE BLOSSOM GARDEN'],backgrounds=['#c8d8a2','#e8bc6a','#c5cfbf','#e4b8c2'];let saved={};try{saved=JSON.parse(localStorage.getItem('quiet-isle-v1')||'{}')}catch{}let done=new Set(saved.done||[]),unlocked=done.size?Math.min(15,Math.max(...done)+1):0,index=Math.min(15,saved.index||0),path=[],errors=[],phase='play',look=false,hintAt=null,timer=0,toastTime=0,drawPointer=false,lastPoint=null,sound=saved.sound!==false,audio=null,last=performance.now(),worker=null,hintBusy=false;
function save(){try{localStorage.setItem('quiet-isle-v1',JSON.stringify({done:[...done],index,sound}))}catch{}}
function tone(freq,duration=.12,gain=.035,type='sine',delay=0){if(!sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime+delay);g.gain.setValueAtTime(0,audio.currentTime+delay);g.gain.linearRampToValueAtTime(gain,audio.currentTime+delay+.012);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+delay+duration);o.connect(g);g.connect(audio.destination);o.start(audio.currentTime+delay);o.stop(audio.currentTime+delay+duration)}catch{}}
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');toastTime=3.5}
const L=()=>M.levels[index],pitch=()=>744/L().n,point=p=>[140+p[0]*pitch(),140+p[1]*pitch()];
function round(x,y,r,color){c.fillStyle=color;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill()}
function star(x,y,r,color){c.fillStyle=color;c.beginPath();for(let i=0;i<16;i++){let a=i*Math.PI/8-Math.PI/2,v=i%2?r*.43:r;c.lineTo(x+Math.cos(a)*v,y+Math.sin(a)*v)}c.closePath();c.fill()}
function paint(){let l=L(),p=pitch();c.clearRect(0,0,1024,1024);c.fillStyle=backgrounds[l.biome];c.fillRect(0,0,1024,1024);let grad=c.createLinearGradient(0,0,1024,1024);grad.addColorStop(0,'#ffffff28');grad.addColorStop(.5,'#ffffff00');grad.addColorStop(1,'#302b2518');c.fillStyle=grad;c.fillRect(0,0,1024,1024);c.strokeStyle='#344134';c.lineWidth=15;c.lineCap='round';for(let k=0;k<=l.n;k++){c.beginPath();c.moveTo(140,140+k*p);c.lineTo(884,140+k*p);c.moveTo(140+k*p,140);c.lineTo(140+k*p,884);c.stroke()}for(let [a,b]of l.blocked){let [x,y]=point(a),[u,v]=point(b);c.strokeStyle=backgrounds[l.biome];c.lineWidth=23;c.beginPath();c.moveTo(x+(u-x)*.38,y+(v-y)*.38);c.lineTo(x+(u-x)*.62,y+(v-y)*.62);c.stroke()}round(...point(l.start),33,'#344134');c.strokeStyle='#344134';c.lineWidth=16;c.beginPath();c.moveTo(884,140);c.lineTo(930,140);c.stroke();round(934,140,16,'#344134');
for(let d of l.dots){let [x,y]=point(d);c.fillStyle='#192f28';c.beginPath();for(let i=0;i<6;i++)c.lineTo(x+Math.cos(i*Math.PI/3)*17,y+Math.sin(i*Math.PI/3)*17);c.fill()}
let cells=new Map;for(let [type,items]of [['color',l.colors],['triangle',l.triangles],['star',l.stars]])for(let v of items){let k=M.nk(v.at),a=cells.get(k)||[];a.push({type,...v});cells.set(k,a)}for(let items of cells.values()){for(let [j,v]of items.entries()){let [x,y]=point(v.at);x+=p/2;y+=p/2;let offset=(j-(items.length-1)/2)*48;x+=offset;let r=items.length>1?17:23;if(v.type==='color'){c.fillStyle=['#f7f5e6','#3b4661','#aa524d'][v.color];c.fillRect(x-r,y-r,r*2,r*2);c.strokeStyle='#23372a50';c.lineWidth=2;c.strokeRect(x-r,y-r,r*2,r*2)}if(v.type==='star')star(x,y,r+4,'#34818a');if(v.type==='triangle'){for(let k=0;k<v.count;k++){let xx=x+(k-(v.count-1)/2)*22;c.fillStyle='#b57624';c.beginPath();c.moveTo(xx,y-12);c.lineTo(xx-10,y+8);c.lineTo(xx+10,y+8);c.fill()}}}}
if(path.length){c.strokeStyle=phase==='solved'?'#fffad4':'#f9f8dc';c.lineWidth=20;c.shadowColor='#fffbd8';c.shadowBlur=phase==='solved'?22:8;c.beginPath();path.forEach((v,i)=>{let [x,y]=point(v);i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke();round(...point(path[0]),25,c.strokeStyle);round(...point(path[path.length-1]),11,c.strokeStyle);c.shadowBlur=0}
for(let e of errors){if(!e.at)continue;let [x,y]=point(e.at);if(e.type!=='dot'){x+=p/2;y+=p/2}c.strokeStyle='#ae413b';c.lineWidth=5;c.beginPath();c.arc(x,y,e.type==='dot'?28:Math.min(65,p*.35),0,Math.PI*2);c.stroke()}
if(hintAt){let [x,y]=point(hintAt);c.strokeStyle='#fcf7db';c.lineWidth=5;c.beginPath();c.arc(x,y,30+Math.sin(timer*4)*4,0,Math.PI*2);c.stroke()}
c.fillStyle='#34413477';c.font='16px sans-serif';c.textAlign='center';c.fillText('SIGNAL '+String(index+1).padStart(2,'0'),512,978);A.texture.needsUpdate=true}
function rule(){let t=L().type,r=[];if(t.includes('dots'))r.push('Visit every dot');if(t.includes('colors'))r.push('Separate square colours');if(t.includes('triangles'))r.push('Triangles count line edges');if(t.includes('stars'))r.push('Two stars per region');return r.join(' · ')+'.'}
function load(i){worker?.terminate();worker=null;hintBusy=false;index=i;phase='play';path=[];errors=[];hintAt=null;look=false;A.reset(L().biome);$('reward').hidden=true;$('look').querySelector('span').textContent='LOOK';$('chapter').textContent=names[L().biome]+' · '+String(index+1).padStart(2,'0')+' / 16';$('title').textContent=L().name.toLowerCase().replace(/\b\w/g,s=>s.toUpperCase());$('rule').textContent=rule();$('tip').textContent='Drag from the circle. Reach the open end.';$('progress').innerHTML=M.levels.map((l,j)=>'<i class="seed '+(done.has(j)?'done ':'')+(j===index?'current':'')+'"></i>').join('');$('hint').disabled=false;paint();save()}
function step(p){if(phase!=='play')return;let k=path.findIndex(q=>M.nk(q)===M.nk(p));if(k>=0){if(k===path.length-1)return;path=path.slice(0,k+1);errors=[];hintAt=null;paint();tone(180);return}if(!M.validStep(L(),path,p))return;path.push(p);errors=[];hintAt=null;paint();tone(260+path.length*24,.075,.025)}
function finish(){if(phase!=='play'||!path.length||M.nk(path[path.length-1])!==M.nk(L().end))return;let result=M.check(L(),path);if(!result.ok){errors=result.errors;let types=new Set(errors.map(e=>e.type));toast(types.has('dot')?'Visit the marked dots.':types.has('color')?'Different square colours need separate rooms.':types.has('triangle')?'Count the sides beside each triangle.':'Stars belong in pairs, in the same region.');tone(110,.22,.045,'triangle');paint();return}phase='solved';done.add(index);document.querySelectorAll('.seed')[index].classList.add('done');unlocked=Math.min(15,Math.max(unlocked,index+1));save();A.solve(index%4===3);paint();[392,494,587,784].forEach((f,j)=>tone(f,.65,.04,'sine',j*.12));$('rewardLabel').textContent=index%4===3?'GARDEN BEACON LIT':'SIGNAL RESTORED';$('rewardTitle').textContent=index===15?'The island is awake.':index%4===3?'A whole garden, glowing.':'A little more light.';$('next').textContent=index===15?'EXPLORE AGAIN ↺':'NEXT SIGNAL →';setTimeout(()=>{if(phase==='solved')$('reward').hidden=false},1100);$('tip').textContent='The line becomes light. The gate opens.';$('hint').disabled=true}
function nodeAt(e){let h=A.hit(e.clientX,e.clientY);if(!h)return null;let p=pitch(),x=Math.round((h.x-140)/p),y=Math.round((h.y-140)/p);if(x<0||x>L().n||y<0||y>L().n||Math.hypot(h.x-140-x*p,h.y-140-y*p)>p*.34)return null;return [x,y]}
let canvas=A.renderer.domElement;canvas.style.touchAction='none';canvas.addEventListener('pointerdown',e=>{if(phase!=='play'&&!look)return;canvas.setPointerCapture(e.pointerId);drawPointer=true;lastPoint={x:e.clientX,y:e.clientY};if(!look){let n=nodeAt(e);if(n)step(n)}});canvas.addEventListener('pointermove',e=>{if(!drawPointer)return;if(look){A.look((e.clientX-lastPoint.x)*.004);lastPoint={x:e.clientX,y:e.clientY};return}let count=Math.ceil(Math.hypot(e.clientX-lastPoint.x,e.clientY-lastPoint.y)/8);for(let j=1;j<=count;j++){let n=nodeAt({clientX:lastPoint.x+(e.clientX-lastPoint.x)*j/count,clientY:lastPoint.y+(e.clientY-lastPoint.y)*j/count});if(n)step(n)}lastPoint={x:e.clientX,y:e.clientY}});function release(){drawPointer=false;lastPoint=null;if(!look)finish()}canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',()=>{drawPointer=false;lastPoint=null});
$('clear').onclick=()=>{if(phase!=='play')return;path=[];errors=[];hintAt=null;paint();tone(200)};$('undo').onclick=()=>{if(phase!=='play')return;path.pop();errors=[];hintAt=null;paint();tone(170)};$('look').onclick=()=>{if(phase==='solved')return;look=!look;A.view(look);$('look').querySelector('span').textContent=look?'RETURN':'LOOK';$('tip').textContent=look?'Drag to look around. RETURN to your panel.':'Drag from the circle. Reach the open end.'};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'♪':'♩';save();if(sound)tone(440)};
$('hint').onclick=()=>{if(hintBusy||phase!=='play')return;hintBusy=true;$('hint').disabled=true;toast('Looking for a quiet way through…');let prefix=path.length?path:[L().start],id=index,src='const M=('+createIsleModel.toString()+')();onmessage=e=>postMessage(M.solve(M.levels[e.data.i],e.data.p));';try{worker=new Worker(URL.createObjectURL(new Blob([src],{type:'text/javascript'})));worker.onmessage=e=>{if(index!==id)return;hintBusy=false;$('hint').disabled=false;worker.terminate();worker=null;if(JSON.stringify(path.length?path:[L().start])!==JSON.stringify(prefix)){toast('Your line changed. Ask for another hint.');return}if(e.data){hintAt=e.data[Math.min(prefix.length,e.data.length-1)];toast('Follow the glowing ring.');paint()}else{toast('This line is boxed in. Undo a few steps.')}};worker.onerror=()=>{hintBusy=false;$('hint').disabled=false;toast('Clear the line to try a fresh route.')};worker.postMessage({i:id,p:prefix})}catch{hintBusy=false;$('hint').disabled=false;let matches=prefix.every((p,j)=>L().answer[j]&&M.nk(p)===M.nk(L().answer[j]));if(matches){hintAt=L().answer[prefix.length];paint()}else toast('Clear the line to try a fresh route.')}};
$('next').onclick=()=>load(index===15?0:index+1);$('close').onclick=()=>$('map').close();$('gallery').onclick=()=>{$('stamps').innerHTML='';for(let [i,l]of M.levels.entries()){let b=document.createElement('button');b.disabled=i>unlocked;b.setAttribute('aria-label','Signal '+(i+1)+(done.has(i)?', complete':''));let q=document.createElement('canvas');q.width=q.height=80;let g=q.getContext('2d');g.fillStyle=backgrounds[l.biome];g.fillRect(0,0,80,80);g.strokeStyle='#344134';g.lineWidth=2;for(let k=0;k<=l.n;k++){g.beginPath();g.moveTo(14,14+k*52/l.n);g.lineTo(66,14+k*52/l.n);g.moveTo(14+k*52/l.n,14);g.lineTo(14+k*52/l.n,66);g.stroke()}b.append(q);let label=document.createElement('span');label.textContent=String(i+1).padStart(2,'0');b.append(label);if(done.has(i)){let check=document.createElement('b');check.textContent='✓';b.append(check)}b.onclick=()=>{$('map').close();load(i)};$('stamps').append(b)}$('mapNote').textContent=done.size+' / 16 signals restored · '+Math.floor(done.size/4)+' / 4 gardens explored.';$('map').showModal()};
addEventListener('keydown',e=>{if($('map').open||phase!=='play'||look)return;let d={ArrowUp:[0,-1],ArrowRight:[1,0],ArrowDown:[0,1],ArrowLeft:[-1,0]}[e.key];if(d){e.preventDefault();if(!path.length)step(L().start);else {let p=path[path.length-1];step([p[0]+d[0],p[1]+d[1]]);finish()}}if(e.key==='Backspace'){e.preventDefault();$('undo').click()}if(e.key==='Escape')$('clear').click()});
let lastTouchButton=null,lastTouchTime=0;document.addEventListener('pointerup',e=>{if(e.pointerType!=='touch')return;let b=e.target.closest?.('button');if(!b||b.disabled)return;e.preventDefault();lastTouchButton=b;lastTouchTime=performance.now();b.click()},true);document.addEventListener('click',e=>{if(e.isTrusted&&e.target.closest?.('button')===lastTouchButton&&performance.now()-lastTouchTime<500){e.preventDefault();e.stopImmediatePropagation()}},true);
function tick(dt){timer+=dt;if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('toast').classList.remove('show')}if(hintAt)paint();A.draw(dt)}function frame(t){let dt=Math.min(.04,(t-last)/1000);last=t;if(!document.hidden)tick(dt);requestAnimationFrame(frame)}load(index);$('sound').textContent=sound?'♪':'♩';requestAnimationFrame(frame);window.__isle={state:()=>({index,phase,path:path.map(p=>[...p]),errors,done:[...done],look,hintAt}),node:p=>{let [x,y]=point(p);return A.project(x,y)},step:tick,info:A.info};
})();
