'use strict';
function createIsleModel(){
const dirs={U:[0,-1],R:[1,0],D:[0,1],L:[-1,0]},nk=p=>p.join(','),ek=(a,b)=>[nk(a),nk(b)].sort().join('|');
function trace(n,code){let p=[0,n],out=[[...p]];for(let k of code){let d=dirs[k];p=[p[0]+d[0],p[1]+d[1]];if(p[0]<0||p[1]<0||p[0]>n||p[1]>n||out.some(q=>nk(q)===nk(p)))throw Error('Invalid authored line '+code);out.push([...p])}if(nk(p)!==nk([n,0]))throw Error('Line does not reach its goal');return out}
function walls(path){return new Set(path.slice(1).map((p,i)=>ek(path[i],p)))}
function regions(n,path){let cuts=walls(path),seen=new Set(),out=[];for(let y=0;y<n;y++)for(let x=0;x<n;x++){if(seen.has(nk([x,y])))continue;let q=[[x,y]],r=[];seen.add(nk([x,y]));for(let i=0;i<q.length;i++){let [a,b]=q[i];r.push([a,b]);for(let [dx,dy]of Object.values(dirs)){let xx=a+dx,yy=b+dy;if(xx<0||yy<0||xx>=n||yy>=n||seen.has(nk([xx,yy])))continue;let edge=dx===1?ek([a+1,b],[a+1,b+1]):dx===-1?ek([a,b],[a,b+1]):dy===1?ek([a,b+1],[a+1,b+1]):ek([a,b],[a+1,b]);if(!cuts.has(edge)){seen.add(nk([xx,yy]));q.push([xx,yy])}}}out.push(r)}return out}
function edgeCount(path,cell){let [x,y]=cell,s=walls(path);return [[[x,y],[x+1,y]],[[x+1,y],[x+1,y+1]],[[x+1,y+1],[x,y+1]],[[x,y+1],[x,y]]].filter(([a,b])=>s.has(ek(a,b))).length}
let specs=[
[3,'UUURRR','FIRST LIGHT','dots'],[3,'RUURDRUU','A TURN OF THOUGHT','dots'],[3,'RURULURR','THE LONG WAY','dots'],[4,'URURDRUULURR','A QUIET DETOUR','dots'],
[3,'RUURDRUU','TWO COLOURS','colors'],[3,'UURDRURU','A LINE BETWEEN','colors'],[4,'RURULURRDRUU','ORCHARD ROOMS','colors'],[4,'RRRULLURRRULLURR','THE GOLDEN DIVIDE','colors+dots'],
[3,'RURULURR','COUNT THE EDGES','triangles'],[3,'URDRUUUR','THREE SIDES','triangles'],[4,'UURDRUULURRR','THE STONE QUARTER','triangles+dots'],[4,'RRRULLURRRULLURR','THE CARVED WAY','triangles+colors'],
[3,'RUURDRUU','A PAIR OF STARS','stars'],[4,'RURULURRDRUU','SEPARATE TWINS','stars'],[4,'URURDRUULURR','BLOSSOM CONSTELLATION','stars+colors'],[4,'RRRULLURRRULLURR','THE LAST SIGNAL','stars+triangles+dots']
];
const levels=specs.map(([n,code,name,type],index)=>{let answer=trace(n,code),r=regions(n,answer),L={n,name,type,biome:Math.floor(index/4),start:[0,n],end:[n,0],dots:[],colors:[],triangles:[],stars:[],blocked:[],answer};if(type.includes('dots')){let count=index===0?1:Math.min(5,Math.floor(answer.length/3));for(let i=1;i<=count;i++)L.dots.push(answer[Math.floor(i*answer.length/(count+1))]);if(index>0){let cuts=walls(answer);outer:for(let y=1;y<n;y++)for(let x=0;x<n;x++){let a=[x,y],b=[x+1,y];if(!cuts.has(ek(a,b))){L.blocked.push([a,b]);break outer}}}}
if(type.includes('colors')){for(let [i,reg]of r.entries()){if(reg.length===1){L.colors.push({at:reg[0],color:i%3});continue}L.colors.push({at:reg[0],color:i%3},{at:reg[reg.length-1],color:i%3})}}
if(type.includes('triangles')){let cells=[];for(let y=0;y<n;y++)for(let x=0;x<n;x++){let count=edgeCount(answer,[x,y]);if(count>0)cells.push({at:[x,y],count})}if(index===8)L.triangles=cells.filter(c=>c.count===1).slice(0,2);else if(index===9)L.triangles=cells.sort((a,b)=>b.count-a.count).slice(0,3);else L.triangles=cells.filter((c,i)=>i%2===0).slice(0,index===15?3:5)}
if(type.includes('stars')){let groups=r.filter(r=>r.length>=2);for(let reg of groups.slice(0,index===12?1:2)){let a=reg[Math.floor(reg.length*.25)],b=reg[Math.floor(reg.length*.75)];if(nk(a)===nk(b))b=reg[reg.length-1];L.stars.push({at:a,color:0},{at:b,color:0})}}return L});
function check(L,path){let errors=[],nodes=new Set(path.map(nk));for(let i=0;i<path.length;i++)if(!validStep(L,path.slice(0,i),path[i])){errors.push({type:'line'});break}if(!path.length||nk(path[0])!==nk(L.start)||nk(path[path.length-1])!==nk(L.end))errors.push({type:'end'});for(let p of L.dots)if(!nodes.has(nk(p)))errors.push({type:'dot',at:p});for(let t of L.triangles)if(edgeCount(path,t.at)!==t.count)errors.push({type:'triangle',at:t.at});for(let reg of regions(L.n,path)){let cells=new Set(reg.map(nk)),sq=L.colors.filter(s=>cells.has(nk(s.at))),cs=new Set(sq.map(s=>s.color));if(cs.size>1)for(let s of sq)errors.push({type:'color',at:s.at});let stars=L.stars.filter(s=>cells.has(nk(s.at)));for(let color of new Set(stars.map(s=>s.color))){let group=stars.filter(s=>s.color===color);if(group.length!==2)for(let s of group)errors.push({type:'star',at:s.at})}}return {ok:errors.length===0,errors}}
function validStep(L,path,p){let last=path[path.length-1];if(!last)return nk(p)===nk(L.start);if(Math.abs(last[0]-p[0])+Math.abs(last[1]-p[1])!==1)return false;if(p[0]<0||p[1]<0||p[0]>L.n||p[1]>L.n)return false;if(L.blocked.some(([a,b])=>ek(a,b)===ek(last,p)))return false;return !path.some(q=>nk(q)===nk(p))}
function solve(L,prefix=[L.start],cap=500000){let nodes=0,out=null;function dfs(path){if(nodes++>cap)return false;let last=path[path.length-1];if(nk(last)===nk(L.end)){if(check(L,path).ok){out=path;return true}return false}for(let d of [[1,0],[0,-1],[-1,0],[0,1]]){let p=[last[0]+d[0],last[1]+d[1]];if(validStep(L,path,p)&&dfs([...path,p]))return true}return false}dfs(prefix.map(p=>[...p]));return out}
return {levels,regions,check,validStep,solve,edgeCount,nk,ek}}
window.IsleModel=createIsleModel();
