(function(){'use strict';const GateArt=window.GateArt;if(!GateArt?.ready)return;const $=id=>document.getElementById(id),KEY='hollow-gate-v1',ALBUM='hollow-gate-album-v1';let s,meta={wins:0,bestRelics:0};try{let d=JSON.parse(localStorage.getItem(KEY));if(Gate.valid(d))s=d;Object.assign(meta,JSON.parse(localStorage.getItem(ALBUM)||'{}'))}catch(e){}let fresh=!s;s=s||Gate.start();let modal=null,path=[],joy={x:0,z:0},keys=new Set,holding=false,busy=false,sound=false,audio,last=0,timer=0,savetimer=0,toastTimer,wonSeen=s.finished,joyPointer=null,slashPointer=null,castTime=0;
function save(){try{let q=JSON.parse(JSON.stringify(s));q.events=[];localStorage.setItem(KEY,JSON.stringify(q));localStorage.setItem(ALBUM,JSON.stringify(meta))}catch(e){}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2600)}
function tone(f,d=.15,type='triangle',vol=.035){if(!audio||!sound)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}function chime(){tone(392,.3);setTimeout(()=>tone(523,.4),110);setTimeout(()=>tone(659,.5),240)}
function ui(){const p=s.p,r=s.rooms[s.room],data=Gate.ROOMS[s.room];$('district').textContent=data.tag;$('room').textContent=data.name;$('objective').textContent=r.cleared?'The gate is open. Your journey continues.':data.objective;$('hearts').innerHTML=Array.from({length:p.max},(_,i)=>'<i class="'+(i<p.hp?'on':'')+'"></i>').join('');$('hearts').setAttribute('aria-label','Health '+p.hp+' of '+p.max);$('mana').innerHTML=Array.from({length:3},(_,i)=>'<i class="'+(i<p.mana&&s.bow?'on':'')+'"></i>').join('');$('mana').hidden=!s.bow;$('souls').textContent='✧ '+s.souls;$('seals').innerHTML=Array.from({length:3},(_,i)=>'<i class="'+(i<s.seals?'on':'')+'"></i>').join('');$('spell').disabled=!s.bow||p.mana===0||s.paused||p.hp<=0;$('slash').disabled=$('roll').disabled=s.paused||p.hp<=0;$('trail').textContent=s.guide?'Trail on':'Trail off';$('pause').textContent=s.paused?'▶':'Ⅱ';let use=null;if(p.hp>0&&!s.paused){if(Math.hypot(p.x,p.z-5.5)<1.5)use='Rest at the shrine';else if(s.room===3&&!r.bell&&Math.hypot(p.x-Gate.ROOMS[3].bell[0],p.z-Gate.ROOMS[3].bell[1])<1.4)use='Ring the bell';else if(p.z< -5.9&&Math.abs(p.x)<2.5&&r.cleared)use=s.room===5?'Step beyond →':'Enter the gate →';else if(p.z>6.3&&Math.abs(p.x)<2.5&&s.room>0)use='Return →'}$('use').hidden=!use;$('use').textContent=use||'Use';$('forge').hidden=Math.hypot(p.x,p.z-5.5)>1.5||s.paused||p.hp<=0;const boss=r.enemies.find(e=>e.type==='boss'&&e.hp>0);$('bossbar').hidden=!boss;if(boss)$('bossbar').querySelector('i').style.width=(boss.hp/boss.max*100)+'%';drawMap()}
function drawMap(){const c=$('map').getContext('2d'),r=s.rooms[s.room];c.clearRect(0,0,120,120);c.strokeStyle='#b9aa85';c.lineWidth=1;c.strokeRect(15,15,90,90);const map=(v)=>60+v*5.5;for(const o of Gate.OBSTACLES){c.fillStyle='#8a846a';c.fillRect(map(o[0])-3,map(o[1])-3,6,6)}c.fillStyle=r.cleared?'#bbd7ac':'#e0976b';c.fillRect(54,12,12,4);for(const e of r.enemies)if(e.hp>0){c.fillStyle='#d69076';c.beginPath();c.arc(map(e.x),map(e.z),e.type==='boss'?5:2,0,Math.PI*2);c.fill()}if(!r.relic){const a=Gate.ROOMS[s.room].relic;c.fillStyle='#e4cf87';c.fillRect(map(a[0])-2,map(a[1])-2,4,4)}c.fillStyle='#eeead0';c.beginPath();c.arc(map(s.p.x),map(s.p.z),3,0,Math.PI*2);c.fill()}
function panel(type){modal=type;holding=false;keys.clear();joy={x:0,z:0};$('knob').style.transform='';$('overlay').hidden=false;let html='<small class="kicker">HOLLOW GATE / A CROW\'S SMALL JOURNEY</small>';
if(type==='intro')html+='<h2>A small soul.<br>A very old gate.</h2><p>Six places beyond the autumn garden. Find three seals, learn the ember bow, and face the Last Gardener.</p><div class="instructions"><div><b>╱</b><small>Slash · refill ember</small></div><div><b>◌</b><small>Roll · evade danger</small></div><div><b>↗</b><small>Ember · ignite braziers</small></div></div><p>Drag the stick to move, or tap the ground. The pale trail ring marks your next goal. Shrines heal and sell upgrades.</p><button data-act="close" class="primary">Enter the garden →</button>';
if(type==='pause')html+='<h2>A moment between doors.</h2><p>Your journey is saved. Rest for a moment.</p><button data-act="resume" class="primary">Continue →</button><button data-act="journal">Journal</button><button data-act="restart">New journey</button>';
if(type==='dead')html+='<h2>Not your last door.</h2><p>You keep your souls, relics and cleared guardians. The shrine will bring you back. The Gardener returns at full strength.</p><button data-act="revive" class="primary">Return to the shrine →</button>';
if(type==='forge')html+='<h2>The quiet forge.</h2><p>✧ '+s.souls+' souls · Earned from guardians, old urns and hidden relics.</p>'+[['blade','Sharpen the blade','+1 damage on each sword and ember hit'],['heart','A stronger soul','+2 maximum health, and a full heal']].map(a=>'<div class="row"><div>'+a[1]+'<small>'+a[2]+' · '+s.upgrades[a[0]]+'/2</small></div><button data-act="upgrade:'+a[0]+'" '+(s.upgrades[a[0]]>=2||s.souls<18+12*s.upgrades[a[0]]?'disabled':'')+'>✧ '+(18+12*s.upgrades[a[0]])+'</button></div>').join('')+'<button data-act="close">Back to the garden</button>';
if(type==='journal')html+='<h2>Notes from beyond.</h2><p>'+s.seals+'/3 seals · '+s.relics+'/6 hidden relics · '+s.kills+' guardians · '+s.deaths+' returns</p>'+Gate.ROOMS.map((r,i)=>'<div class="row"><div>'+r.name+'<small>'+ (s.rooms[i].cleared?'Gate open':i>s.room?'Still ahead':r.objective)+'</small></div><span>'+(s.rooms[i].relic?'✧':'·')+'</span></div>').join('')+'<p>'+meta.wins+' victories. Best collection: '+meta.bestRelics+'/6 relics.</p><p>Keyboard: WASD / arrows to move. J or Space to slash. K to roll. L to fire ember. E to use. Escape to pause.</p><button data-act="close">Continue →</button>';
if(type==='win')html+='<h2>The gate remembers you.</h2><p>The Gardener lays down its staff. A small crow carries the last light into the morning.</p><div class="badge">'+s.relics+'/6 HIDDEN RELICS</div><div class="badge">'+s.kills+' GUARDIANS</div><div class="badge">'+s.deaths+' RETURNS</div><p>The path stays open. Explore for missing relics, or return to the Gardener for a stronger rematch.</p><button data-act="close" class="primary">Keep exploring</button><button data-act="rematch">Gardener rematch →</button><button data-act="restart">New journey</button>';
if(type==='restart')html+='<h2>Begin again?</h2><p>This replaces the current journey. Your completed-journey record stays.</p><button data-act="new" class="primary">A new journey →</button><button data-act="close">Stay here</button>';
$('panel').innerHTML=html;$('panel').scrollTop=0;$('panel').querySelector('button')?.focus()}
function close(){modal=null;$('overlay').hidden=true;$('panel').innerHTML='';ui();save()}
function events(){for(const e of s.events.splice(0)){GateArt?.event(e);if(e.type==='hit'){tone(125,.06,'sawtooth',.022)}if(e.type==='slash')tone(180+e.combo*40,.065,'triangle',.012);if(e.type==='pot')tone(650,.11,'triangle');if(e.type==='roll')tone(155,.12,'sine',.018);if(e.type==='hurt'){tone(90,.25,'sawtooth',.027);$('app').classList.remove('hurt');void $('app').offsetWidth;$('app').classList.add('hurt')}if(e.type==='clear'){chime();toast('GATE OPEN · Follow the pale ring.')}if(e.type==='seal')toast('AN OLD SEAL · '+e.n+' / 3');if(e.type==='bow')toast('EMBER BOW · Sword hits refill your arrows.');if(e.type==='relic'){if(s.finished)meta.bestRelics=Math.max(meta.bestRelics,s.relics);chime();toast('HIDDEN RELIC · '+e.n+' / 6')}if(e.type==='rest'){chime();toast('Health and ember restored.')}if(e.type==='torch'){chime();toast('A flame remembered.')}if(e.type==='bell'){chime();toast('The village wakes.')}if(e.type==='wave')toast('THE ORCHARD · Wave '+e.n+' / 3');if(e.type==='room'){path=[];GateArt.build(s);toast(Gate.ROOMS[s.room].name);save()}if(e.type==='dead'){holding=false;path=[];panel('dead');save()}if(e.type==='win'){if(!wonSeen){wonSeen=true;meta.wins++;meta.bestRelics=Math.max(meta.bestRelics,s.relics);chime()}panel('win');save()}}ui()}
function act(id){const [a,arg]=id.split(':');if(a==='close'){close();return}if(a==='resume'){s.paused=false;close();return}if(a==='journal'){panel('journal');return}if(a==='restart'){panel('restart');return}if(a==='new'){s=Gate.start();wonSeen=false;path=[];GateArt.build(s);close();toast('A small soul. An open path.');return}if(a==='revive'){Gate.revive(s);close();events();return}if(a==='upgrade'){if(Gate.upgrade(s,arg)){chime();save();panel('forge');ui()}return}if(a==='rematch'){s.finished=false;wonSeen=false;s.trial++;s.room=5;const relicFound=s.rooms[5].relic;s.rooms[5]=Gate.start().rooms[5];s.rooms[5].relic=relicFound;path=[];s.rooms[5].enemies[0].hp=s.rooms[5].enemies[0].max=60+s.trial*12;s.p.x=0;s.p.z=6;s.p.hp=s.p.max;s.p.mana=3;GateArt.build(s);close();toast('THE GARDENER · Rematch '+s.trial);return}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.act){act(b.dataset.act);return}if(b.id==='book')panel('journal');if(b.id==='pause'){s.paused=!s.paused;s.paused?panel('pause'):close();save();ui()}if(b.id==='mute'){sound=!sound;if(sound){try{audio=audio||new(window.AudioContext||window.webkitAudioContext);audio.resume();tone(330,.25)}catch(e){}}$('mute').textContent=sound?'Sound on':'Sound off'}if(b.id==='trail'){s.guide=!s.guide;ui();save()}if(modal||s.paused)return;if(b.id==='use'){Gate.interact(s);events()}if(b.id==='forge')panel('forge');if(b.id==='roll'){Gate.roll(s,joy.x,joy.z);events()}if(b.id==='spell'){Gate.cast(s);events()}if(b.id==='slash'){Gate.attack(s);events()}});
// Hold slash for successive swings; release always ends the action, including outside the button.
$('slash').addEventListener('pointerdown',e=>{if(modal||s.paused)return;holding=true;slashPointer=e.pointerId;$('slash').setPointerCapture(e.pointerId);Gate.attack(s);events()});window.addEventListener('pointerup',e=>{if(e.pointerId===slashPointer){holding=false;slashPointer=null}});window.addEventListener('pointercancel',()=>{holding=false;joy={x:0,z:0};joyPointer=null;$('knob').style.transform=''});
function updateJoy(e){const r=$('joystick').getBoundingClientRect();let x=(e.clientX-r.left-r.width/2)/(r.width*.4),y=(e.clientY-r.top-r.height/2)/(r.height*.4),n=Math.hypot(x,y);if(n>1){x/=n;y/=n}joy={x:x*.747+y*.665,z:-x*.665+y*.747};$('knob').style.transform='translate('+x*r.width*.25+'px,'+y*r.height*.25+'px)';path=[]}
$('joystick').addEventListener('pointerdown',e=>{if(modal||s.paused)return;e.preventDefault();joyPointer=e.pointerId;$('joystick').setPointerCapture(e.pointerId);updateJoy(e)});$('joystick').addEventListener('pointermove',e=>{if(e.pointerId===joyPointer)updateJoy(e)});$('joystick').addEventListener('pointerup',e=>{if(e.pointerId===joyPointer){joyPointer=null;joy={x:0,z:0};$('knob').style.transform=''}});
let touchButton=null,blockUntil=0;document.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'){const b=e.target.closest('button');touchButton=b?{b,id:e.pointerId,x:e.clientX,y:e.clientY}:null}},true);document.addEventListener('pointerup',e=>{const a=touchButton;if(!a||a.id!==e.pointerId)return;touchButton=null;if(a.b.isConnected&&!a.b.disabled&&Math.hypot(e.clientX-a.x,e.clientY-a.y)<12){e.preventDefault();blockUntil=Date.now()+600;a.b.click()}},true);document.addEventListener('click',e=>{if(e.isTrusted&&Date.now()<blockUntil){e.preventDefault();e.stopImmediatePropagation()}},true);
let startPoint;$('world').addEventListener('pointerdown',e=>startPoint={x:e.clientX,y:e.clientY});$('world').addEventListener('pointerup',e=>{if(modal||s.paused||!startPoint||Math.hypot(e.clientX-startPoint.x,e.clientY-startPoint.y)>14)return;const t=GateArt.pick(e.clientX,e.clientY);if(t)path=Gate.path(s,t.x,t.z)});
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(e.key==='Escape'){if(modal){if(s.paused)s.paused=false;close()}else{s.paused=true;panel('pause');ui()}return}if(modal||s.paused)return;keys.add(e.key.toLowerCase());path=[];if(e.key.toLowerCase()==='k')Gate.roll(s,joy.x,joy.z);if(e.key.toLowerCase()==='l')Gate.cast(s);if(e.key.toLowerCase()==='e')Gate.interact(s);events()});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();holding=false;joy={x:0,z:0}});document.addEventListener('visibilitychange',()=>{if(document.hidden){s.paused=true;keys.clear();holding=false;save();ui()}});
function frame(ms){const dt=Math.min(.05,(ms-last)/1000||0);last=ms;timer+=dt;savetimer+=dt;if(!modal&&!s.paused){let x=joy.x,z=joy.z;const kx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),ky=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(kx||ky){x=kx*.747+ky*.665;z=-kx*.665+ky*.747}if(path.length){let p=path[0],dx=p.x-s.p.x,dz=p.z-s.p.z,n=Math.hypot(dx,dz);if(n<.16)path.shift();else{x=dx/n;z=dz/n}}Gate.tick(s,dt,{x,z,attack:holding||keys.has('j')||keys.has(' ')});events()}
if(timer>=1/30){GateArt?.update(s,timer,ms/1000);timer=0;ui()}if(savetimer>2){savetimer=0;save()}requestAnimationFrame(frame)}
if(!GateArt?.ready)return;GateArt.build(s);ui();requestAnimationFrame(frame);if(fresh)panel('intro');else if(s.p.hp<=0)panel('dead');else if(s.paused)panel('pause');
window.Hollow={get state(){return JSON.parse(JSON.stringify(s))},get records(){return JSON.parse(JSON.stringify(meta))},project:(x,z)=>GateArt.project(x,z)};
})();
