(function(root){'use strict';
const D=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z),TAU=Math.PI*2;
const node=(id,name,type,x,z,extra={})=>({id,name,type,x,z,r:.72,...extra});
const LEVELS=[
 {title:'A Little Detour',hint:'Tap a nearby shadow.',theme:0,par:5,nodes:[node('start','Doorstep','door',-2,4),node('mail','Mailbox','mail',-2,1.3),node('tree','Linden Tree','tree',1,-.7),node('gift','Lost Paper Plane','bench',-4,0,{gift:true}),node('goal','Home','goal',2,-3.8)]},
 {title:'Rain or Shine',hint:'Ride the umbrella. Turn it.',theme:1,par:4,nodes:[node('start','Cafe Shade','bench',-2,4),node('umbrella','Cafe Umbrella','umbrella',0,.8,{angle:Math.PI/2,length:2.2}),node('gift','Lost Glove','lamp',-3,-2,{gift:true}),node('goal','Home','goal',1.8,-4)]},
 {title:'A Dog Day',hint:'Hop onto the dog. Enjoy the ride.',theme:2,par:5,nodes:[node('start','Doorstep','door',-2,4),node('bench','Park Bench','bench',-2,1.5),node('dog','Good Dog','dog',0,0,{z0:1.2,z1:-3.4,period:10}),node('gift','Lost Collar','bin',-3,-2.5,{gift:true}),node('goal','Home','goal',2,-4.6)]},
 {title:'The Domino Effect',hint:'Push one sign. Watch the street change.',theme:3,par:6,nodes:[node('start','Doorstep','door',-2,4),node('switch','Street Switch','lamp',-2,1.3,{switch:true}),node('sign0','First Sign','sign',-.8,.2,{domino:0}),node('sign1','Second Sign','sign',.1,-1.6,{domino:1,gift:true}),node('sign2','Third Sign','sign',1,-3.4,{domino:2}),node('goal','Home','goal',2.5,-5.4)]},
 {title:'Special Delivery',hint:'Turn the umbrella. Catch the bicycle.',theme:4,par:5,nodes:[node('start','Bus Stop','bench',-2.8,4.8),node('umbrella','Parcel Umbrella','umbrella',-1.2,1.8,{angle:Math.PI/2,length:2.2}),node('bike','Paper Bicycle','bike',1.2,0,{z0:1,z1:-3.8,period:11}),node('gift','Lost Letter','mail',-3.3,-2.1,{gift:true}),node('goal','Home','goal',2.8,-5.5)]},
 {title:'Golden Hour',hint:'A little chain reaction. A little shade.',theme:5,par:8,nodes:[node('start','Doorstep','door',-3,4),node('switch','Street Switch','lamp',-3,1.5,{switch:true}),node('sign0','First Sign','sign',-1.9,.8,{domino:0}),node('sign1','Second Sign','sign',-1,-.5,{domino:1}),node('umbrella','Sunset Umbrella','umbrella',.2,-1.2,{angle:Math.PI/2,length:2.2}),node('gift','Lost Camera','tree',-2.5,-3.8,{gift:true}),node('goal','Home','goal',2.8,-5)]}
];
class Game{
 constructor(index=0){this.index=Math.max(0,Math.min(5,index));this.time=0;this.current='start';this.phase='run';this.hops=0;this.mistakes=0;this.gift=false;this.angles={};this.domino=-1;this.dominoTime=0;this.pending=null;this.events=[];this.history=[];this.visited=['start'];const l=LEVELS[this.index];for(const n of l.nodes)if(n.angle!==undefined)this.angles[n.id]=n.angle;}
 get level(){return LEVELS[this.index];}
 emit(type,extra={}){this.events.push({type,...extra});}
 position(id,time=this.time){const n=this.level.nodes.find(n=>n.id===id);if(!n)return null;if(n.type==='umbrella'){const angle=this.angles[id];return {...n,x:n.x+Math.cos(angle)*n.length,z:n.z+Math.sin(angle)*n.length,angle};}if(n.type==='dog'||n.type==='bike'){const t=(1-Math.cos(time/n.period*TAU))/2;return {...n,x:n.x+Math.sin(time/n.period*TAU)*.18,z:n.z0+(n.z1-n.z0)*t,heading:Math.sin(time/n.period*TAU)>=0?Math.PI:0};}return {...n};}
 active(n){return n.domino===undefined||this.dominoTime>=(n.domino+1)*.32;}
 reachable(id){const n=this.position(id),a=this.position(this.current);return !!n&&this.active(n)&&D(a,n)<=3.65+.001&&id!==this.current;}
 pushHistory(){this.history.push(this.snapshot(false));if(this.history.length>20)this.history.shift();}
 hop(id){if(this.phase!=='run'||this.pending||id===this.current)return false;const to=this.position(id),from=this.position(this.current);if(!to||!this.active(to)||!this.reachable(id)){this.sunlight(to||from);return false;}this.pushHistory();this.pending={from:{x:from.x,z:from.z},to:id,t:0,fail:false};this.hops++;this.emit('hop',{from:this.current,to:id});return true;}
 sunlight(point){if(this.phase!=='run'||this.pending)return;this.pushHistory();this.pending={from:this.position(this.current),target:point,t:0,fail:true};this.mistakes++;this.emit('sun');}
 rotate(id,angle,remember=true){const n=this.level.nodes.find(n=>n.id===id);if(this.phase!=='run'||this.pending||!n||n.type!=='umbrella'||D(this.position(this.current),this.position(id))>4.1)return false;if(remember)this.pushHistory();this.angles[id]=((angle%TAU)+TAU)%TAU;this.emit('turn',{id});return true;}
 interact(){const n=this.position(this.current);if(this.pending||this.phase!=='run')return false;if(n.type==='umbrella')return this.rotate(n.id,this.angles[n.id]+Math.PI/2);if(n.switch&&this.domino<0){this.pushHistory();this.domino=0;this.dominoTime=.001;this.emit('push');return true;}return false;}
 step(dt){if(this.phase!=='run')return;dt=Math.min(.04,dt);this.time+=dt;if(this.domino>=0){const old=Math.floor(this.dominoTime/.32);this.dominoTime=Math.min(2,this.dominoTime+dt);const next=Math.floor(this.dominoTime/.32);if(next!==old)this.emit('clack');}if(this.pending){const p=this.pending;p.t+=dt;if(p.t>=(p.fail?.65:.45)){if(!p.fail){this.current=p.to;if(!this.visited.includes(p.to))this.visited.push(p.to);const n=this.position(p.to);this.emit('land',{id:p.to});if(n.gift&&!this.gift){this.gift=true;this.emit('gift');}if(n.type==='goal'){this.phase='win';this.emit('win');}}else this.emit('return');this.pending=null;}}}
 player(){if(!this.pending){const n=this.position(this.current);return{x:n.x,z:n.z,y:.09};}const p=this.pending,d=p.fail?.65:.45,t=Math.min(1,p.t/d),to=p.fail?p.target:this.position(p.to,this.time),u=p.fail?Math.sin(t*Math.PI)*.65:t;return{x:p.from.x+(to.x-p.from.x)*u,z:p.from.z+(to.z-p.from.z)*u,y:.09+Math.sin(t*Math.PI)*(p.fail?.75:1.4)};}
 undo(){if(!this.history.length||this.pending)return false;const state=this.history.pop(),remaining=this.history;Object.assign(this,state);this.history=remaining;this.events=[];this.emit('undo');return true;}
 stars(){return 1+(this.gift?1:0)+(this.mistakes===0&&this.hops<=this.level.par?1:0);}
 snapshot(includeHistory=true){const s={index:this.index,time:this.time,current:this.current,phase:this.phase,hops:this.hops,mistakes:this.mistakes,gift:this.gift,angles:{...this.angles},domino:this.domino,dominoTime:this.dominoTime,pending:this.pending?JSON.parse(JSON.stringify(this.pending)):null,visited:[...this.visited]};if(includeHistory)s.history=JSON.parse(JSON.stringify(this.history));return s;}
 static restore(s){if(!s||!Number.isInteger(s.index)||s.index<0||s.index>5||!LEVELS[s.index].nodes.some(n=>n.id===s.current))throw Error('Invalid saved walk');const g=new Game(s.index);Object.assign(g,s);g.events=[];g.history=s.history||[];return g;}
}
const API={Game,LEVELS,D};root.SP=API;if(typeof module!=='undefined')module.exports=API;
})(typeof window!=='undefined'?window:globalThis);
