(function(){'use strict';const $=id=>document.getElementById(id),KEY='shade-parade-v1';let profile={unlocked:0,records:[],sound:true},saved=null;try{const d=JSON.parse(localStorage.getItem(KEY));if(d){profile={...profile,...d.profile};saved=d.run;}}catch(e){}let game=new SP.Game(),art,paused=true,panel='intro',returnPanel='intro',buttons=new Map(),handles=new Map(),ctx=null,muted=!profile.sound,lastPointer=0,finishAt=0,toastAt=0,hintAt=0,drag=null;
try{art=new ShadeArt($('world'));art.build(game);}catch(e){$('overlay').hidden=true;$('error').hidden=false;console.error(e);return;}
function save(){try{localStorage.setItem(KEY,JSON.stringify({profile:{...profile,sound:!muted},run:saved||game.snapshot()}));}catch(e){}}
function tone(f,d=.14,v=.08,slide=1){if(muted)return;try{ctx=ctx||new(window.AudioContext||window.webkitAudioContext)();ctx.resume();const o=ctx.createOscillator(),a=ctx.createGain(),t=ctx.currentTime;o.type='sine';o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(f*slide,t+d);a.gain.setValueAtTime(v,t);a.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(a);a.connect(ctx.destination);o.start(t);o.stop(t+d);}catch(e){}}
function sound(e){if(e.type==='hop')tone(360,.17,.06,1.65);if(e.type==='land')tone(220,.12,.07,.65);if(e.type==='sun')tone(170,.25,.08,.5);if(e.type==='gift')[660,880,1100].forEach((f,i)=>setTimeout(()=>tone(f,.2,.075),i*85));if(e.type==='win')[440,550,660,880].forEach((f,i)=>setTimeout(()=>tone(f,.3,.075),i*150));if(e.type==='clack')tone(130,.055,.10,.6);if(e.type==='turn')tone(260,.035,.02,1.1);}
function wire(el,fn){el.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();});el.addEventListener('pointerup',e=>{e.preventDefault();e.stopPropagation();lastPointer=performance.now();fn();});el.addEventListener('click',e=>{if(e.detail===0||performance.now()-lastPointer>600)fn();});}
document.addEventListener('click',e=>{if(e.isTrusted&&e.detail>0&&performance.now()-lastPointer<600){e.preventDefault();e.stopImmediatePropagation();}},true);
function show(name){panel=name;paused=true;drag=null;$('overlay').hidden=false;for(const id of ['intro','paused','result','collection'])$(id).hidden=id!==name;$('targets').hidden=true;$('controls').hidden=true;save();}
function play(){saved=null;panel='';paused=false;finishAt=game.phase==='win'?performance.now()+Math.max(100,2300*(1-art.color)):0;$('overlay').hidden=true;$('targets').hidden=false;$('controls').hidden=false;$('hud').hidden=false;save();}
function targets(){buttons.clear();handles.clear();$('targets').innerHTML='';for(const n of game.level.nodes){const b=document.createElement('button');b.className='target';b.innerHTML='<i class="dot"></i>';b.setAttribute('aria-label','Hop to '+n.name);b.dataset.node=n.id;const initial=art.screen(game.position(n.id).x,game.position(n.id).z);b.style.left=initial.x+'px';b.style.top=initial.y+'px';b.hidden=!game.active(n);$('targets').append(b);buttons.set(n.id,b);wire(b,()=>{if(!paused){if(game.current===n.id)game.interact();else game.hop(n.id);}});
if(n.type==='umbrella'){const h=document.createElement('button');h.className='target handle';h.textContent='↻';h.setAttribute('aria-label','Rotate '+n.name);const initialHandle=art.screen(n.x,n.z,2.5);h.style.left=initialHandle.x+'px';h.style.top=(initialHandle.y-44)+'px';$('targets').append(h);handles.set(n.id,h);h.addEventListener('pointerdown',e=>{if(paused||!enabledHandle(n.id))return;e.preventDefault();e.stopPropagation();drag={id:n.id,pointer:e.pointerId,x:e.clientX,y:e.clientY,start:game.angles[n.id],moved:false};h.setPointerCapture(e.pointerId);});h.addEventListener('pointermove',e=>{if(!drag||drag.pointer!==e.pointerId)return;e.preventDefault();const d=drag,dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.hypot(dx,dy)>6&&!d.moved){game.pushHistory();d.moved=true;}if(d.moved)game.rotate(d.id,d.start+dx*.027-dy*.017,false);});h.addEventListener('pointerup',e=>{if(!drag||drag.pointer!==e.pointerId)return;e.preventDefault();e.stopPropagation();lastPointer=performance.now();if(!drag.moved)game.rotate(drag.id,game.angles[drag.id]+Math.PI/2);drag=null;save();});h.addEventListener('pointercancel',()=>{drag=null;save();});h.addEventListener('click',e=>{if(e.detail===0&&enabledHandle(n.id))game.rotate(n.id,game.angles[n.id]+Math.PI/2);});}}
}
function enabledHandle(id){return !game.pending&&SP.D(game.position(game.current),game.position(id))<=4.1&&game.phase==='run';}
function load(index){saved=null;game=new SP.Game(index);art.build(game,!!profile.records[index]);targets();play();tone(440,.16);}
function start(){if(saved){try{game=SP.Game.restore(saved);saved=null;art.build(game,!!profile.records[game.index]);targets();if(game.phase==='win')result();else play();return;}catch(e){saved=null;}}load(Math.min(profile.unlocked,5));}
function toast(text,ms=950){$('toast').textContent=text;toastAt=performance.now()+ms;}
function result(){const stars=game.stars(),old=profile.records[game.index]||{stars:0,gift:false,bestHops:Infinity};profile.records[game.index]={stars:Math.max(old.stars,stars),gift:old.gift||game.gift,bestHops:Math.min(old.bestHops,game.hops)};profile.unlocked=Math.min(5,Math.max(profile.unlocked,game.index+1));show('result');$('resultTitle').textContent=game.index===5?'The city remembers.':'A little more color.';$('stars').textContent=Array.from({length:3},(_,i)=>i<stars?'★':'☆').join(' ');$('resultText').textContent=`${game.hops} hops · ${game.mistakes===0?'A clean walk':game.mistakes+' gentle returns'}${game.gift?' · Memory found':''}`;$('next').textContent=game.index===5?'THE STREET ALBUM →':'NEXT STREET →';save();}
const stamps=['➤','♧','◉','♢','✉','▣'];function album(){returnPanel=panel||'play';show('collection');$('chapters').innerHTML='';for(let i=0;i<6;i++){const r=profile.records[i],b=document.createElement('button');b.className='chapter'+(i>profile.unlocked?' locked':'');b.disabled=i>profile.unlocked;b.setAttribute('aria-label','Street '+(i+1)+' '+SP.LEVELS[i].title);b.innerHTML=`<span class="stamp">${r&&r.gift?stamps[i]:'○'}</span><b>${String(i+1).padStart(2,'0')} · ${SP.LEVELS[i].title}</b><small>${r?'★'.repeat(r.stars)+'☆'.repeat(3-r.stars):i>profile.unlocked?'LOCKED':'A NEW WALK'}</small>`;$('chapters').append(b);wire(b,()=>load(i));}}
function hint(){hintAt=performance.now()+5000;const n=game.position(game.current);if(n.type==='umbrella')$('tip').textContent='Turn the umbrella until a new shadow glows.';else if(n.switch&&game.domino<0)$('tip').textContent='Push the switch. Watch the signs fall.';else if(n.type==='dog'||n.type==='bike')$('tip').textContent='Enjoy the ride. Nearby shadows glow.';else $('tip').textContent=game.level.hint;}
for(const [id,fn]of Object.entries({start,resume:play,pause:()=>{if(!panel)show('paused');else if(panel==='paused')play();},retry:()=>load(game.index),replay:()=>load(game.index),next:()=>game.index===5?album():load(game.index+1),undo:()=>{if(!paused&&game.undo()){tone(260);save();}},action:()=>{if(!paused){game.interact();save();}},hint,album,introAlbum:album,resultAlbum:album,back:()=>{if(returnPanel==='play')play();else show(returnPanel);},help:()=>{$('helpText').hidden=!$('helpText').hidden;},sound:()=>{muted=!muted;updateSound();tone(550);save();}}))wire($(id),fn);
function updateSound(){$('sound').textContent=muted?'♪̸':'♪';$('sound').setAttribute('aria-pressed',String(!muted));}updateSound();if(saved)$('start').textContent='KEEP WANDERING →';
$('world').addEventListener('pointerup',e=>{if(!paused&&!drag){lastPointer=performance.now();const p=art.ground(e.clientX,e.clientY);if(Math.abs(p.x)<5.7&&Math.abs(p.z)<7.3)game.sunlight(p);}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(panel==='paused')play();else if(!panel)show('paused');}if(paused)return;if(e.key==='z'||e.key==='Backspace'){e.preventDefault();game.undo();}if(e.key==='r'){e.preventDefault();game.interact();}if(e.key==='h')hint();});window.addEventListener('blur',()=>{if(!paused&&game.phase==='run')show('paused');});document.addEventListener('visibilitychange',()=>{if(document.hidden&&!paused&&game.phase==='run')show('paused');});window.addEventListener('resize',()=>art.resize());window.addEventListener('pagehide',save);
targets();$('targets').hidden=true;let last=performance.now(),nextSave=0;function loop(now){requestAnimationFrame(loop);const dt=Math.min(.065,(now-last)/1000);if(dt<1/32)return;last=now;if(!paused){game.step(Math.min(.04,dt));const events=game.events.splice(0);for(const e of events){sound(e);art.event(e,game);if(e.type==='gift')toast('A little memory.');if(e.type==='sun')toast('Too sunny!',650);if(e.type==='win'){toast('Welcome home.',1300);finishAt=now+2300;}}if(game.phase==='win'&&finishAt&&now>finishAt)result();if(now>nextSave){save();nextSave=now+2200;}}art.render(game,paused?0:dt,paused);
if(!paused){for(const n of game.level.nodes){const pos=game.position(n.id),s=art.screen(pos.x,pos.z),b=buttons.get(n.id);b.style.left=s.x+'px';b.style.top=s.y+'px';b.hidden=!game.active(n);b.className='target '+(n.id===game.current?'current':game.reachable(n.id)?'reachable':'distant')+(n.type==='goal'?' goal':'')+(n.gift&&!game.gift?' gift':'');b.setAttribute('aria-current',n.id===game.current?'true':'false');if(handles.has(n.id)){const h=handles.get(n.id),p=art.screen(n.x,n.z,2.5);h.style.left=p.x+'px';h.style.top=(p.y-44)+'px';h.className='target handle'+(enabledHandle(n.id)?' enabled':'');}}
const n=game.position(game.current);$('action').hidden=!!game.pending||(n.type!=='umbrella'&&!(n.switch&&game.domino<0));$('action').textContent=n.type==='umbrella'?'TURN ↻':'PUSH ↓';$('undo').disabled=!game.history.length||!!game.pending;$('title').textContent=game.level.title;$('episode').textContent=String(game.index+1).padStart(2,'0')+' / 06';$('memory').textContent=game.gift?'◆':'◇';$('memory').setAttribute('aria-label',game.gift?'Memory collected':'Memory not collected');if(now>hintAt)$('tip').textContent=game.hops===0?'Tap a glowing shadow.':n.type==='umbrella'?'Drag the ↻ handle or tap TURN.':n.switch&&game.domino<0?'A tiny push changes the street.':n.type==='dog'||n.type==='bike'?'Your ride keeps moving.':'';}
if(now>toastAt)$('toast').textContent='';}
requestAnimationFrame(loop);window.__shade={state:()=>game.snapshot(),profile:()=>JSON.parse(JSON.stringify(profile)),nodes:()=>game.level.nodes.map(n=>{const p=game.position(n.id);return{...p,active:game.active(n),reachable:game.reachable(n.id),screen:art.screen(p.x,p.z),handle:handles.has(n.id)?{x:parseFloat(handles.get(n.id).style.left),y:parseFloat(handles.get(n.id).style.top)}:null};}),player:()=>({...game.player(),screen:art.screen(game.player().x,game.player().z,game.player().y)}),ui:()=>({panel,paused}),renderer:()=>({calls:art.renderer.info.render.calls,triangles:art.renderer.info.render.triangles})};
})();
