/* Button Boots: original toy-foot walking. No network or external artwork. */
(()=>{'use strict';const $=s=>document.querySelector(s),E=Boots,key='button-boots-v1';let saved;try{saved=JSON.parse(localStorage.getItem(key));}catch{}let state=E.restore(saved?.state)||E.fresh(),best=Array.from({length:8},(_,i)=>Math.max(0,Math.min(3,Number(saved?.best?.[i])||0))),theme=['classic','sage','berry'].includes(saved?.theme)?saved.theme:'classic',muted=!!saved?.muted,paused=true,drag=null,fx=[],time=state.t,cam=0,scale=1,off=0,W=0,H=0,body={x:90,y:255,vx:0,vy:0},ac=null,voices=new Set(),lastSave=0;
const total=()=>best.reduce((a,b)=>a+b,0);if(theme==='sage'&&total()<6||theme==='berry'&&total()<15)theme='classic';
function save(){try{localStorage.setItem(key,JSON.stringify({state,best,theme,muted}));}catch{}}
function tone(f=380,d=.12){if(muted||paused)return;try{ac??=new(window.AudioContext||window.webkitAudioContext)();ac.resume();if(voices.size>12)return;const o=ac.createOscillator(),v=ac.createGain();o.type='sine';o.frequency.setValueAtTime(f,ac.currentTime);o.frequency.exponentialRampToValueAtTime(f*.76,ac.currentTime+d);v.gain.setValueAtTime(.07,ac.currentTime);v.gain.exponentialRampToValueAtTime(.001,ac.currentTime+d);o.connect(v);v.connect(ac.destination);o.start();o.stop(ac.currentTime+d);voices.add(o);o.onended=()=>voices.delete(o);}catch{}}
function silence(){for(const o of voices)try{o.stop();}catch{}voices.clear();}
function effect(x,y,color,celebrate=false){fx.push({x,y,color,type:'ring',t:time});for(let i=0;i<(celebrate?22:5);i++)fx.push({x,y:y-10,color:i%2?color:'#e2ba62',type:'bit',seed:i*2.4,t:time});fx=fx.slice(-100);}
function sync(){ $('#route').textContent=String(state.n+1).padStart(2,'0')+' / 08';$('#title').textContent=E.titles[state.n].toUpperCase();$('#bells').textContent='●'.repeat(state.bells.length)+'○'.repeat(3-state.bells.length);$('#undo').disabled=!state.history.length;$('#sound').textContent=muted?'♪̸':'♫';$('#hint').textContent=state.slips>0?'Stay within the dotted reach · Undo anytime':state.steps?(state.n>=4?'Colored steps need the matching boot':'Bring both boots to the little house'):'Drag one boot onto the next step';}
function panel(html){drag=null;paused=true;silence();save();$('#panel').innerHTML=html;$('#overlay').hidden=false;sync();}
function resume(){drag=null;paused=false;$('#overlay').hidden=true;sync();}
function resetBody(){const a=E.foot(state,0),b=E.foot(state,1);body={x:(a.x+b.x)/2,y:(a.y+b.y)/2-91,vx:0,vy:0};cam=body.x-W/scale*.4;fx=[];time=state.t;}
function start(n){state=E.fresh(n);resetBody();save();resume();}
function intro(){panel('<small>A LITTLE WALK</small><div class="sticker"><i></i><i></i></div><h1>Button Boots</h1><p>Two little boots. One big journey.<br>Drag a boot onto the next step.<br>Bring both boots home.</p><button class="primary" data-act="resume">'+(state.steps?'CONTINUE':'LET’S WALK')+'</button><button data-act="journal">ROUTES</button><p style="font-size:11px">Collect 3 bells · Gentle landings earn stars</p>');}
function journal(){const unlocked=Math.min(7,best.findIndex(x=>!x)<0?7:best.findIndex(x=>!x));panel('<small>THE WALKING CLUB · '+total()+' / 24 ★</small><h1>Little journeys</h1><div class="routes">'+E.titles.map((x,i)=>'<button data-level="'+i+'" '+(i>unlocked?'disabled':'')+' aria-label="'+x+'">'+(i>unlocked?'·':String(i+1).padStart(2,'0'))+'<em>'+'★'.repeat(best[i])+'☆'.repeat(3-best[i])+'</em></button>').join('')+'</div><div class="swatches">'+[['classic','CLASSIC',0],['sage','SAGE HAT',6],['berry','BERRY HAT',15]].map(([id,label,t])=>'<button data-theme="'+id+'" '+(total()<t?'disabled':'')+'>'+label+(total()<t?' · '+t+'★':id===theme?' ✓':'')+'</button>').join('')+'</div><button data-act="resume" class="primary">BACK TO WALK</button>');}
function postcard(){const source=$('#canvas canvas'),out=document.createElement('canvas');out.width=source.width;out.height=source.height+100;const c=out.getContext('2d');c.drawImage(source,0,0);c.fillStyle='#f6f3e7';c.fillRect(0,source.height,out.width,100);c.textAlign='center';c.fillStyle='#435c50';c.font='22px Georgia';c.fillText('BUTTON BOOTS',out.width/2,source.height+35);c.font='14px Georgia';c.fillText(E.titles[state.n]+' · '+'★'.repeat(E.stars(state)),out.width/2,source.height+65);const a=document.createElement('a');a.download='button-boots-route-'+(state.n+1)+'.png';a.href=out.toDataURL('image/png');a.click();}
function win(){const stars=E.stars(state);best[state.n]=Math.max(best[state.n],stars);save();panel('<small>ROUTE '+String(state.n+1).padStart(2,'0')+' · HOME AT LAST</small><h1>'+E.titles[state.n]+'</h1><div class="stars">'+'★'.repeat(stars)+'☆'.repeat(3-stars)+'</div><p>'+state.bells.length+' / 3 bells · '+state.steps+' steps<br>'+state.slips+' missed landings</p><button class="primary" data-act="next">'+(state.n===7?'WALK AGAIN':'NEXT JOURNEY')+'</button><button data-act="retry">REPLAY</button><button data-act="journal">JOURNAL · '+total()+'★</button><button data-act="postcard">SAVE POSTCARD ↓</button><p style="font-size:11px">Finish · All bells · At most 2 missed landings</p>');}
function finishDrop(x,y){if(!drag)return;const k=drag.k;drag=null;const result=E.drop(state,k,x,y),f=E.foot(state,k);if(result.miss){tone(150,.17);effect(x,y,'#a0afa1');}else if(!result.idle){tone(result.bell?650:k?310:260,result.bell?.28:.12);effect(f.x,f.y,result.bell?'#d8ac55':k?'#719ca8':'#dd806b',result.bell);body.vy+=45;}sync();save();if(result.won){[520,650,780].forEach((f,i)=>setTimeout(()=>tone(f,.25),i*110));effect(f.x,f.y,'#d8ac55',true);setTimeout(()=>{if(state.won&&!paused)win();},650);}}
function world(e){const rect=$('#canvas canvas').getBoundingClientRect();return{x:(e.clientX-rect.left)/scale+cam,y:(e.clientY-rect.top)/scale-off};}
function bootDown(e){if(paused||state.won||drag)return;e.preventDefault();const p=world(e),fs=[E.foot(state,0),E.foot(state,1)],dist=fs.map(f=>Math.hypot(p.x-f.x,p.y-f.y+5));let k=dist[0]<dist[1]?0:1;if(dist[k]>48)return;drag={k,id:e.pointerId,x:fs[k].x,y:fs[k].y};e.currentTarget.setPointerCapture(e.pointerId);tone(k?420:350,.05);}
function bootMove(e){if(!drag||e.pointerId!==drag.id||paused)return;e.preventDefault();const p=world(e),a=E.foot(state,1-drag.k),dx=p.x-a.x,dy=p.y-a.y,d=Math.hypot(dx,dy),clamp=d>254?254/d:1;drag.x=a.x+dx*clamp;drag.y=a.y+dy*clamp;}
function bootUp(e){if(!drag||e.pointerId!==drag.id)return;e.preventDefault();bootMove(e);finishDrop(drag.x,drag.y);}
function pause(){if(state.won){win();return;}panel('<small>TAKE YOUR TIME</small><h1>A little rest</h1><p>Your boots will wait right here.</p><button class="primary" data-act="resume">CONTINUE</button><button data-act="journal">ROUTES</button><button data-act="retry">RESTART</button>');}
$('#pause').onclick=pause;$('#journal').onclick=journal;$('#recall').onclick=()=>panel('<small>FRESH FOOTSTEPS</small><h1>Start this walk again?</h1><button data-act="retry" class="primary">RESTART</button><button data-act="resume">KEEP WALKING</button>');$('#sound').onclick=()=>{muted=!muted;if(muted)silence();save();sync();};$('#undo').onclick=()=>{if(paused||state.won)return;drag=null;if(E.undo(state)){resetBody();tone(250);save();sync();}};
$('#panel').onclick=e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.level!==undefined){start(+b.dataset.level);return;}if(b.dataset.theme){theme=b.dataset.theme;save();journal();return;}switch(b.dataset.act){case'resume':state.won?win():resume();break;case'journal':journal();break;case'postcard':postcard();break;case'retry':start(state.n);break;case'next':start((state.n+1)%8);break;}};
// Some mobile browsers suppress a compatibility click after a canvas drag.
let touches=new Map(),lastButton=null,lastAt=0;document.addEventListener('pointerdown',e=>{const b=e.target.closest('button');if(e.pointerType==='touch'&&b&&!b.disabled){e.preventDefault();touches.set(e.pointerId,b);}},{capture:true,passive:false});document.addEventListener('pointerup',e=>{const b=touches.get(e.pointerId);touches.delete(e.pointerId);if(!b)return;e.preventDefault();const r=b.getBoundingClientRect();if(b.isConnected&&!b.disabled&&e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom){lastButton=b;lastAt=performance.now();b.click();}},{capture:true,passive:false});document.addEventListener('pointercancel',e=>touches.delete(e.pointerId),true);document.addEventListener('click',e=>{if(e.isTrusted&&e.target.closest('button')===lastButton&&performance.now()-lastAt<600){e.preventDefault();e.stopImmediatePropagation();}},true);
document.addEventListener('visibilitychange',()=>{if(document.hidden&&!paused)pause();});window.addEventListener('pagehide',save);document.addEventListener('keydown',e=>{if(e.key==='Escape')paused&&!state.won?resume():pause();if(e.key.toLowerCase()==='z'&&!paused)$('#undo').click();});
new p5(p=>{p.setup=()=>{const el=$('#canvas');W=el.clientWidth;H=el.clientHeight;p.createCanvas(W,H).parent(el);p.pixelDensity(Math.min(1.5,window.devicePixelRatio||1));p.frameRate(45);fit();resetBody();const cv=el.querySelector('canvas');cv.addEventListener('pointerdown',bootDown,{passive:false});cv.addEventListener('pointermove',bootMove,{passive:false});cv.addEventListener('pointerup',bootUp,{passive:false});cv.addEventListener('pointercancel',()=>{drag=null;});cv.addEventListener('contextmenu',e=>e.preventDefault());intro();};function fit(){scale=Math.min(W/440,H/(W>H?320:520));off=H/scale*.59-350;drag=null;}p.windowResized=()=>{W=$('#canvas').clientWidth;H=$('#canvas').clientHeight;p.resizeCanvas(W,H);fit();resetBody();};p.draw=()=>{const dt=Math.min(.035,p.deltaTime/1000);if(!paused){E.tick(state,dt);time+=dt;const a=E.foot(state,0),b=E.foot(state,1),f=drag?{x:drag.x,y:drag.y}:null,tx=(a.x+b.x+(f?f.x-E.foot(state,drag.k).x:0))/2,ty=(a.y+b.y+(f?f.y-E.foot(state,drag.k).y:0))/2-91;body.vx+=(tx-body.x)*90*dt;body.vy+=(ty-body.y)*90*dt;body.vx*=Math.exp(-12*dt);body.vy*=Math.exp(-12*dt);body.x+=body.vx*dt;body.y+=body.vy*dt;if(!drag)cam+=(body.x-W/scale*.4-cam)*Math.min(1,dt*7);fx=fx.filter(e=>time-e.t<1.2);if(performance.now()-lastSave>1500){lastSave=performance.now();save();}}BootArt.draw(p.drawingContext,{W,H,scale,cam,off,state,time,drag,body,effects:fx,theme});};});
window.game={get state(){return state;},get paused(){return paused;},get drag(){return drag;},get best(){return best.slice();},get theme(){return theme;},get voices(){return voices.size;},get view(){return{W,H,scale,cam,off,body:{...body}};},worldToScreen(x,y){const r=$('#canvas canvas').getBoundingClientRect();return{x:(x-cam)*scale+r.left,y:(y+off)*scale+r.top};}};
})();
