(function(root){'use strict';
const titles=['First footsteps','Cloud promenade','Tea-time terraces','The sleepy ferry','Moonbeam steps','Little pendulums','Pistachio parade','The grand crossing'];
function route(n){return Array.from({length:8+n},(_,i)=>({x:90+i*(n<2?98:105),y:350+Math.sin(i*.9+n)*((n>1)?30:12),w:i===0||i===7+n?106:82-n*3,m:(n>=3&&i>1&&i<7+n&&i%3===2)?12+n:0,s:(i%2?1:-1)*(.55+n*.035),seed:i*.81,need:n>=4&&i>1&&i<7+n&&i%3===0?(i+1)%2:null,bell:i===2||i===Math.floor((8+n)/2)||i===6+n}));}
function fresh(n=0){const r=route(n);return{v:1,n,t:0,feet:[{p:0,dx:-23},{p:0,dx:23}],steps:0,slips:0,bells:[],won:false,history:[]};}
function pad(s,i){const a=route(s.n)[i];return{...a,x:a.x+Math.sin(s.t*a.s+a.seed)*a.m,y:a.y+Math.cos(s.t*a.s+a.seed)*a.m*.35};}
function foot(s,k){const f=s.feet[k],p=pad(s,f.p);return{x:p.x+f.dx,y:p.y};}
function tick(s,dt){if(!s.won)s.t+=Math.min(.04,Math.max(0,dt));}
function snapshot(s){const{history,...a}=s;return JSON.parse(JSON.stringify(a));}
function drop(s,k,x,y){if(s.won||![0,1].includes(k)||!Number.isFinite(x+y))return{ok:false};const other=foot(s,1-k),r=route(s.n);let best=-1,d=Infinity;for(let i=0;i<r.length;i++){const p=pad(s,i);if((p.need===null||p.need===k)&&Math.abs(x-p.x)<=p.w/2+8&&Math.abs(y-p.y)<32&&Math.hypot(x-other.x,y-other.y)<=242){const dist=Math.hypot(x-p.x,y-p.y);if(dist<d){d=dist;best=i;}}}if(best<0){s.slips++;return{ok:false,miss:true};}const p=pad(s,best),dx=Math.max(-p.w/2+12,Math.min(p.w/2-12,x-p.x));if(s.feet[k].p===best&&Math.abs(s.feet[k].dx-dx)<5)return{ok:true,idle:true};s.history.push(snapshot(s));if(s.history.length>60)s.history.shift();s.feet[k]={p:best,dx};if(s.feet[1-k].p===best){s.feet[k].dx=k?23:-23;s.feet[1-k].dx=k?-23:23;}s.steps++;let bell=false;if(r[best].bell&&!s.bells.includes(best)){s.bells.push(best);bell=true;}s.won=s.feet.every(f=>f.p===r.length-1);return{ok:true,bell,won:s.won,p:best};}
function undo(s){if(!s.history.length||s.won)return false;const a=s.history.pop(),h=s.history;Object.assign(s,a,{history:h});return true;}
function stars(s){return s.won?1+(s.bells.length===3?1:0)+(s.slips<=2?1:0):0;}
function restore(a){if(!a||a.v!==1||!Number.isInteger(a.n)||a.n<0||a.n>7||!Number.isFinite(a.t)||a.t<0||!Array.isArray(a.feet)||a.feet.length!==2||!Array.isArray(a.bells))return null;const len=route(a.n).length;if(a.feet.some(f=>!f||!Number.isInteger(f.p)||f.p<0||f.p>=len||!Number.isFinite(f.dx)||Math.abs(f.dx)>60)||a.bells.some(i=>!route(a.n)[i]?.bell)||new Set(a.bells).size!==a.bells.length||!Number.isInteger(a.steps)||a.steps<0||!Number.isInteger(a.slips)||a.slips<0)return null;const s=JSON.parse(JSON.stringify(a));s.won=s.feet.every(f=>f.p===len-1);s.history=(Array.isArray(a.history)?a.history:[]).slice(-60).map(h=>restore({...h,history:[]})).filter(Boolean).map(snapshot);return s;}
const api={titles,route,fresh,pad,foot,tick,drop,undo,stars,restore,snapshot};if(typeof module!=='undefined')module.exports=api;else root.Boots=api;
})(typeof window==='undefined'?globalThis:window);
