(()=>{'use strict';
const $=s=>document.getElementById(s),canvas=$('canvas'),overlay=$('overlay'),panel=$('panel');Art.init(canvas);
let saveKey='iron-instinct-v1',meta={records:[],unlocked:1,palette:0,mute:false,active:null},store=true;
try{let o=JSON.parse(localStorage.getItem(saveKey)||'null');if(o&&Array.isArray(o.records)){meta={...meta,...o};meta.unlocked=Iron.clamp(meta.unlocked||1,1,8);}}catch{store=false;}
let game;try{game=meta.active?Iron.Engine.restore(meta.active):new Iron.Engine();}catch{game=new Iron.Engine();meta.active=null;}
let paused=true,menu='home',input={x:0,y:0},keys=new Set(),joystick=null,holding=false,acc=0,last=performance.now(),savedAt=0,shownResult=false,toastLife=0,toastText='',mode='campaign';Art.palette=meta.palette;SFX.mute=meta.mute;
function total(){return meta.records.reduce((sum,r)=>sum+(r?r.medals.filter(Boolean).length:0),0);}
function persist(){meta.active=game.snapshot();meta.mute=SFX.mute;meta.palette=Art.palette;try{localStorage.setItem(saveKey,JSON.stringify(meta));store=true;}catch{store=false;}}
function release(){keys.clear();input={x:0,y:0};joystick=null;holding=false;game.input={x:0,y:0};game.player.vx=game.player.vy=0;$('stick').querySelector('i').style.transform='';$('shove').classList.remove('pressed');$('grab').classList.remove('pressed');}
function bind(id,fn){let el=$(id);if(!el)return;let down=null;el.addEventListener('pointerdown',e=>{e.stopPropagation();down={id:e.pointerId,x:e.clientX,y:e.clientY};try{el.setPointerCapture(e.pointerId);}catch{}});el.addEventListener('pointerup',e=>{if(down&&down.id===e.pointerId&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<14){fn();}down=null;});el.addEventListener('pointercancel',()=>down=null);el.addEventListener('click',e=>{e.preventDefault();if(e.detail===0)fn();});}
function show(type,html){menu=type;paused=true;release();SFX.stop();overlay.hidden=false;panel.innerHTML=html;panel.scrollTop=0;}
function resume(){SFX.init();paused=false;menu=null;overlay.hidden=true;release();acc=0;last=performance.now();persist();}
const poster=`<div class="poster"><svg viewBox="0 0 110 80"><path d="M8 68L12 35 29 22 35 10 69 5 85 19 101 35 106 65 88 71 78 43 67 40 70 67 57 72 40 63 34 74 20 73 25 42 18 48 17 68ZM43 20L44 32 68 34 73 25 65 17Z"/></svg><span>BREAK THE CAGE.<br>BREAK THE RULES.</span></div>`;
function home(){show('home',`<span class="eyebrow">A PRIMAL ESCAPE</span><h1>IRON<br>INSTINCT.</h1>${poster}<div class="lesson"><b>↗</b><span>Move. Find the green exit.</span></div><div class="lesson"><b>✋</b><span>Grab a guard. Block a shot. Throw him.</span></div><div class="lesson"><b>➜</b><span>Shove guards into walls and crates.</span></div><button class="primary" id="play">${meta.active&&game.state==='play'?'CONTINUE ESCAPE':'BREAK OUT'}</button><div class="row"><button id="floors">FLOORS · ${meta.unlocked}/8</button><button id="help">HOW TO</button></div><small>${total()} / 24 medals · ${store?'Progress saved on this device':'Storage unavailable · session play'}</small>`);bind('play',()=>{if(!meta.active||game.state!=='play')start(0);else resume();});bind('floors',floors);bind('help',help);}
function start(index,cycle=0){game=new Iron.Engine(index,cycle);mode=cycle?'wild':'campaign';shownResult=false;Art.fx=[];Art.focus(game);toastLife=2.5;toastText=game.plan.name;resume();hud();}
function floors(){show('floors',`<span class="eyebrow">THE ESCAPE ROUTE</span><h2>EIGHT FLOORS.</h2><div class="floors">${Iron.PLANS.map((p,i)=>`<button id="f${i}" ${i>=meta.unlocked?'disabled':''}>${i< meta.unlocked?String(i+1).padStart(2,'0'):'⌑'}<small>${meta.records[i]?meta.records[i].medals.map(x=>x?'◆':'◇').join(''):'◇◇◇'}</small></button>`).join('')}</div><p>◆ Escape · ◆ Free every captive · ◆ Beat the floor time</p><div class="row"><button id="coat">INK · ${['IVORY','AMBER','JADE'][Art.palette]}</button><button id="back">BACK</button></div>${meta.unlocked===8&&meta.records[7]?'<button class="primary" id="wild">WILD SHIFT ↗</button>':''}<small>${total()}/24 medals · Amber at 6 · Jade at 12</small>`);for(let i=0;i<8;i++)bind('f'+i,()=>{if(i<meta.unlocked){if(game.state==='play'&&meta.active&&(game.index!==i||game.time>3))confirmFloor(i);else start(i);}});bind('coat',()=>{let max=total()>=12?3:total()>=6?2:1;Art.palette=(Art.palette+1)%max;Art.render(game,0);persist();floors();});bind('back',home);bind('wild',()=>start(0,1));}
function confirmFloor(i){show('confirm',`<span class="eyebrow">START A NEW ESCAPE?</span><h2>FLOOR ${i+1}</h2><p>Your medals stay. The current floor will restart.</p><button id="yes" class="primary">START FLOOR</button><button id="back">BACK</button>`);bind('yes',()=>start(i));bind('back',floors);}
function help(){let from=game.state==='play'&&meta.active;show('help',`<span class="eyebrow">NO KEYS. NO WAITING.</span><h2>GET OUT.</h2><div class="lesson"><b>↗</b><span>Drag the pad or screen to move.<br>Desktop: WASD / arrows.</span></div><div class="lesson"><b>➜</b><span>SHOVE / Space knocks guards away.<br>Walls, crates and guards stop the throw.</span></div><div class="lesson"><b>✋</b><span>GRAB / E takes a nearby guard.<br>He blocks two shots. SHOVE throws him.</span></div><div class="lesson"><b>▥</b><span>Shove cages to free friends.<br>Gold-armoured guards need a shove first.</span></div><p>White beams warn before a shot. Glass breaks; barrels burst. The green door is always open.</p><button class="primary" id="back">${from?'BACK TO ESCAPE':'GOT IT'}</button>`);bind('back',()=>from?resume():home());}
function pause(){if(paused)return;release();persist();show('pause',`<span class="eyebrow">TAKE A BREATH</span><h2>PAUSED.</h2><p>Floor ${game.index+1} · ${game.plan.name}</p><button class="primary" id="resume">KEEP GOING</button><div class="row"><button id="help">HOW TO</button><button id="retry">RESTART</button></div><div class="row"><button id="floors">FLOORS</button><button id="photo">SAVE POSTER</button></div>`);bind('resume',resume);bind('help',help);bind('retry',()=>confirmFloor(game.index));bind('floors',floors);bind('photo',photo);}
function result(){shownResult=true;let win=game.state==='won',med=game.medals();if(win&&game.cycle===0){let old=meta.records[game.index];meta.records[game.index]={medals:med.map((m,i)=>m||!!old?.medals[i]),best:Math.min(old?.best||1e9,game.time),combo:Math.max(old?.combo||0,game.bestCombo)};meta.unlocked=Math.max(meta.unlocked,Math.min(8,game.index+2));}persist();show('result',`<span class="eyebrow">${win?'THE DOOR WAS NEVER THE LIMIT.':'ONE MORE TRY.'}</span><h2>${win?'FREEDOM.':'STILL IN.'}</h2>${win?`<div class="medals">${med.map(m=>m?'◆':'◇').join('')}</div>`:''}<div class="stats"><div>${Math.floor(game.time)}s<small>ESCAPE</small></div><div>${game.released}/${game.plan.cages.length}<small>FRIENDS</small></div><div>${game.bestCombo}×<small>BEST CHAIN</small></div></div><p>${win?`Escape ◆ · Friends ${med[1]?'◆':'◇'} · Under ${game.plan.par}s ${med[2]?'◆':'◇'}`:'The white beam warns you. Grab a guard for cover.'}</p><button class="primary" id="next">${!win?'TRY AGAIN':game.index<7?'NEXT FLOOR →':game.cycle?'ANOTHER SHIFT →':'WILD SHIFT →'}</button><div class="row"><button id="retry">REPLAY</button><button id="floors">FLOORS</button><button id="photo">POSTER ↓</button></div><small>${total()}/24 medals ${total()>=12?'· Jade ink unlocked':total()>=6?'· Amber ink unlocked':''}</small>`);bind('next',()=>{if(!win)start(game.index,game.cycle);else if(game.index<7)start(game.index+1,game.cycle);else start(0,game.cycle+1);});bind('retry',()=>start(game.index,game.cycle));bind('floors',floors);bind('photo',photo);}
function photo(){let a=document.createElement('canvas');a.width=900;a.height=1200;let c=a.getContext('2d');c.fillStyle='#172a22';c.fillRect(0,0,900,1200);let sh=canvas.height/canvas.width,dw=820,dh=Math.min(900,dw*sh);c.drawImage(canvas,40,100,dw,dh);c.fillStyle='#edf0cb';c.font='900 66px Arial';c.fillText('IRON INSTINCT.',40,75);c.font='900 23px Arial';c.fillText(`FLOOR ${game.index+1}   /   ${game.plan.name}`,40,1100);c.font='18px Arial';c.fillText(`${Math.floor(game.time)}s · ${game.released} friends freed · ${game.bestCombo}× chain`,40,1140);a.toBlob(blob=>{if(!blob)return;let u=URL.createObjectURL(blob),link=document.createElement('a');link.href=u;link.download='iron-instinct-poster.png';link.click();setTimeout(()=>URL.revokeObjectURL(u),3000);});}
function hud(){$('health').textContent='●'.repeat(game.player.hp)+'○'.repeat(4-game.player.hp);$('floor').textContent=String(game.index+1).padStart(2,'0')+' / 08';$('rescues').textContent='▥ '+game.released+'/'+game.plan.cages.length;$('grab').querySelector('span').textContent=game.player.held!==null?'RELEASE':'GRAB';$('shove').querySelector('span').textContent=game.player.held!==null?'THROW':'SHOVE';$('guide').textContent=game.time<5&&game.index===0?'DRAG TO MOVE · SHOVE TO SMASH':game.player.held!==null?'SHIELD READY · SHOVE TO THROW':'FIND THE GREEN EXIT ↑';$('guide').style.opacity=game.time<8||game.player.held!==null?'1':'.55';$('toast').textContent=toastLife>0?toastText:'';$('sound').textContent=SFX.mute?'♪̸':'♪';$('sound').setAttribute('aria-label',SFX.mute?'Enable sound':'Mute sound');}
function act(kind){if(paused)return;SFX.init();game.action(kind);persist();}
function pressAction(id,kind){let el=$(id);el.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();if(paused)return;try{el.setPointerCapture(e.pointerId);}catch{}el.classList.add('pressed');if(kind==='shove')holding=true;act(kind);});let end=()=>{el.classList.remove('pressed');if(kind==='shove')holding=false;};el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);el.addEventListener('click',e=>{e.preventDefault();if(e.detail===0)act(kind);});}
pressAction('shove','shove');pressAction('grab','grab');bind('pause',()=>paused?resume():pause());bind('sound',()=>{SFX.init();SFX.mute=!SFX.mute;if(SFX.mute)SFX.stop();persist();hud();});document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();if(!paused)pause();});
function stickDown(e){if(paused||joystick||e.button>0)return;e.preventDefault();SFX.init();joystick={id:e.pointerId,x:e.clientX,y:e.clientY};try{e.currentTarget.setPointerCapture(e.pointerId);}catch{}}
function stickMove(e){if(!joystick||e.pointerId!==joystick.id)return;let dx=e.clientX-joystick.x,dy=e.clientY-joystick.y,len=Math.hypot(dx,dy),max=42;input={x:dx/Math.max(max,len),y:dy/Math.max(max,len)};let r=Math.min(max,len);$('stick').querySelector('i').style.transform=`translate(${input.x*r}px,${input.y*r}px)`;}
function stickUp(e){if(joystick?.id===e.pointerId){joystick=null;input={x:0,y:0};$('stick').querySelector('i').style.transform='';}}
for(let el of [canvas,$('stick')]){el.addEventListener('pointerdown',stickDown);el.addEventListener('pointermove',stickMove);el.addEventListener('pointerup',stickUp);el.addEventListener('pointercancel',stickUp);el.addEventListener('contextmenu',e=>{e.preventDefault();act('shove');});}
document.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Escape'].includes(e.key))e.preventDefault();if(e.key==='Escape'){if(paused&&menu==='pause')resume();else if(!paused)pause();return;}if(paused)return;keys.add(e.key.toLowerCase());if(!e.repeat){if(e.key===' ')act('shove');if(e.key.toLowerCase()==='e')act('grab');}});document.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
window.addEventListener('resize',()=>{release();Art.resize();Art.focus(game);Art.render(game,0);});window.addEventListener('blur',()=>{if(!paused)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&!paused)pause();});window.addEventListener('pagehide',()=>{release();persist();});
function frame(now){let dt=Math.min(.05,(now-last)/1000);last=now;if(!paused){acc+=dt;while(acc>=1/60){let keyboard={x:(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),y:(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)};if(holding&&game.player.cool<=0)game.action('shove');game.update(1/60,joystick?input:keyboard);acc-=1/60;}for(let e of game.events.splice(0)){Art.event(e);SFX.play(e);if(e.type==='rescue'){toastText='FRIEND FREE';toastLife=1.3;}if(['impact','friendly','shield','blast'].includes(e.type)&&e.n>1){toastText=e.n+'× BREAKOUT';toastLife=1;}if(e.type==='block'){toastText='SHOT BLOCKED';toastLife=.8;}if(e.type==='armour'){toastText='STUN → GRAB';toastLife=.9;}}
Art.render(game,dt);toastLife=Math.max(0,toastLife-dt);hud();if(now-savedAt>1000){persist();savedAt=now;}if(game.state!=='play'&&!shownResult)result();}else if(!Art.once){Art.render(game,0);Art.once=true;}requestAnimationFrame(frame);}
Art.focus(game);Art.render(game,0);Art.once=true;if(game.state==='won'||game.state==='lost'){shownResult=true;result();}else home();hud();requestAnimationFrame(frame);
// Read-only inspection for browser QA. No teleport, invulnerability or test commands shipped.
window.ironInspect=()=>({paused,menu,store,game:game.snapshot(),meta:JSON.parse(JSON.stringify(meta)),camera:{...Art.cam,s:Art.s},voices:SFX.voices.length});
})();
