(()=>{'use strict';const E=BeatEngine,A=BeatArt,M=BeatAudio,$=q=>document.querySelector(q),storage='beatbreak-v1';let s,hasSave=false,muted=false,soft=true,started=false,paused=true,gesture=null,target=null,keys={},fx=[],trail=[],countIn=0,announcementTime=0,toastTime=0,last=0,acc=0,saveTime=0,trailTime=0,ui='',scoreShown=0,lastPhase=-1;
try{let raw=localStorage.getItem(storage);hasSave=!!raw;s=E.restore(JSON.parse(raw));muted=localStorage.getItem(storage+'-mute')==='1';soft=localStorage.getItem(storage+'-motion')!=='full';}catch{s=E.fresh();}A.init($('#world'));let initial=A.viewport();E.resize(s,initial.w,initial.h);scoreShown=s.score;
function save(){try{localStorage.setItem(storage,JSON.stringify(s));localStorage.setItem(storage+'-mute',muted?'1':'0');localStorage.setItem(storage+'-motion',soft?'soft':'full');}catch{}}
function clear(){gesture=null;target=null;keys={};$('#dash').classList.remove('held');}
function show(html){$('#card').innerHTML=html;$('#veil').classList.remove('hidden');}function hide(){$('#veil').classList.add('hidden');}function btn(id,label,cls=''){return `<button id="${id}" class="${cls}">${label}</button>`;}function bind(b,fn){if(!b)return;let down=null;b.addEventListener('pointerdown',e=>down={id:e.pointerId,x:e.clientX,y:e.clientY});b.addEventListener('pointercancel',()=>down=null);b.addEventListener('pointerup',e=>{if(down&&down.id===e.pointerId&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<9){e.preventDefault();down=null;fn();}else down=null;});b.addEventListener('click',e=>{if(e.detail===0)fn();});}function on(id,fn){bind($('#'+id),fn);}function toast(text){$('#toast').textContent=text;toastTime=2;}
function announce(text,duration=1.5){$('#announcement').textContent=text;announcementTime=duration;}
function startAudio(){M.mute(muted);M.start(s);}
function resume(count=false){started=true;paused=false;clear();hide();countIn=count?60/E.tracks[s.n].bpm*3:0;if(!countIn){$('#countdown').textContent='';startAudio();}save();}
function intro(){show(`<div class="eyebrow">MOVE · DODGE · FEEL THE DROP</div><div class="symbol"></div><h1>BEAT<span>BREAK</span></h1><div class="legend"><span><b>■</b>You</span><span><b>●</b>Avoid</span><span><b>➜</b>Dash through</span></div>${btn('start',hasSave?'Continue':'Press play','primary')}<p class="tiny">Six original tracks · Headphones recommended<br>Drag to move · Tap ➜ to dash</p>`);on('start',()=>{if(s.mode==='win'){started=true;win();}else if(s.mode==='lose'){started=true;lose();}else resume(!hasSave);});}
function pause(){if(!started)return;if(s.mode==='win'){win();return;}if(s.mode==='lose'){lose();return;}paused=true;clear();M.stop();save();show(`<div class="eyebrow">${E.tracks[s.n].name}</div><h2>On pause.</h2>${btn('continue','Keep playing','primary')}<div class="row">${btn('sound',muted?'Sound off':'Sound on')}${btn('motion',soft?'Motion: soft':'Motion: full')}</div><div class="row">${btn('restart','Restart track')}${btn('help','How to play')}</div>`);on('continue',()=>resume(false));on('sound',()=>{muted=!muted;M.mute(muted);save();$('#sound').textContent=muted?'Sound off':'Sound on';});on('motion',()=>{soft=!soft;save();$('#motion').textContent=soft?'Motion: soft':'Motion: full';});on('restart',confirmRestart);on('help',help);}
function help(){show(`<h2>Avoid pink. Follow blue.</h2><p>Drag anywhere to steer your little blue shape.<br>Tap <b>➜</b> to dash through danger.<br>Dotted pink lines warn before lasers fire.<br>Blue notes and close dodges build your score.</p><div class="legend"><span><b>★</b>Finish</span><span><b>♪</b>5 notes</span><span><b>◆</b>2 hits or fewer</span></div><p class="tiny">WASD / arrows · Space to dash · Esc to pause<br>Checkpoints every 32 beats. No lives or retry limit.</p>${btn('back','Got it','primary')}`);on('back',pause);}
function confirmRestart(){show('<h2>Rewind this track?</h2><p>Keep your best ranks. Restart from the first beat.</p>'+btn('yes','Rewind','primary')+btn('no','Go back'));on('yes',()=>load(s.n,s.encore));on('no',pause);}
function library(){paused=true;clear();M.stop();save();let total=s.profile.best.reduce((a,b)=>a+b,0);show(`<div class="eyebrow">YOUR MIXTAPE · ${total}/18 BADGES${s.profile.encore?' · BEST MIX '+s.profile.encore:''}</div><h2>Pick a feeling.</h2><div class="tracks">${E.tracks.map((t,i)=>`<button data-track="${i}" ${i>s.profile.unlocked?'disabled':''}>${i>s.profile.unlocked?'⌑':String(i+1).padStart(2,'0')+' '+t.name}<small>${t.bpm} BPM · ${Math.round(t.beats*60/t.bpm)}s</small><b>${'★'.repeat(s.profile.best[i])||'· · ·'} ${s.profile.scores[i]||''}</b></button>`).join('')}</div><div class="skins">${['Square','Diamond','Ring'].map((name,i)=>`<button data-skin="${i}" ${total<[0,6,12][i]?'disabled':''} aria-label="${name} shape">${name} ${s.profile.skin===i?'✓':''}<small>${[0,6,12][i]?[0,6,12][i]+' ★':''}</small></button>`).join('')}</div><div class="row">${s.profile.best[5]?btn('encore','Encore mix'):''}${btn('back','Back','primary')}</div>`);document.querySelectorAll('[data-track]').forEach(b=>bind(b,()=>load(+b.dataset.track)));document.querySelectorAll('[data-skin]').forEach(b=>bind(b,()=>{s.profile.skin=+b.dataset.skin;save();library();}));on('encore',()=>load(0,1));on('back',()=>s.mode==='win'?win():s.mode==='lose'?lose():resume(false));}
function load(n,encore=0){M.stop();let v=A.viewport();s=E.fresh(n,v.w,v.h,s.profile,encore);fx=[];trail=[];scoreShown=0;ui='';lastPhase=-1;resume(true);}
function win(){let celebrate=!paused;paused=true;clear();M.stop();if(celebrate)M.finish();save();let final=s.n===5;show(`<div class="eyebrow">${E.tracks[s.n].name} · TRACK COMPLETE</div><div class="rank">${s.rank}</div><div class="medals">${'★'.repeat(s.medal)}${'☆'.repeat(3-s.medal)}</div><div class="facts"><span><b>${s.score}</b>score</span><span><b>${s.notes}</b>notes</span><span><b>${s.grazes}</b>grazes</span></div>${btn('next',s.encore?'Next mix':final?'Encore mix':'Next track','primary')}<div class="row">${btn('replay','Replay')}${btn('tracks','Mixtape')}${btn('postcard','Save cover')}</div><p class="tiny">${s.hits} hits · Best ${s.profile.scores[s.n]}${s.encore?' · Encore '+s.encore:''}<br>${final?'Encore remixes the six tracks with faster projectiles.':'Collect 5 notes and take at most 2 hits for all 3 badges.'}</p>`);on('next',()=>load(s.encore?(s.n+1)%6:final?0:s.n+1,s.encore?s.encore+1:final?1:0));on('replay',()=>load(s.n));on('tracks',library);on('postcard',postcard);}
function lose(){paused=true;clear();M.stop();save();show(`<div class="eyebrow">${E.tracks[s.n].name}</div><h2>Find your rhythm.</h2><p>Back to beat ${s.checkpoint}. You’ve got this.</p>${btn('retry','Try again','primary')}<div class="row">${btn('rewind','Start over')}${btn('tracks','Mixtape')}</div><p class="tiny">Unlimited retries · Checkpoints every 32 beats</p>`);on('retry',()=>{s=E.retry(s);fx=[];trail=[];scoreShown=s.score;resume(true);});on('rewind',()=>load(s.n,s.encore));on('tracks',library);}
function postcard(){let cv=document.createElement('canvas');cv.width=900;cv.height=900;let g=cv.getContext('2d');g.fillStyle='#080e19';g.fillRect(0,0,900,900);g.drawImage($('#world'),40,110,820,620);g.fillStyle='#5debf0';g.font='900 44px Arial';g.fillText('BEATBREAK',40,70);g.fillStyle='#ff86b9';g.font='bold 60px Arial';g.fillText(s.rank+'   '+s.score,40,814);g.fillStyle='#a5d5df';g.font='18px monospace';g.fillText(E.tracks[s.n].name+' / '+s.notes+' NOTES / '+s.grazes+' GRAZES',40,858);cv.toBlob(b=>{if(!b)return;let a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='beatbreak-'+E.tracks[s.n].name.toLowerCase().replaceAll(' ','-')+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500);});}
function event(e){M.fx(e.type);if(e.type==='beat')return;let color=e.type==='hit'?'#ff70a5':'#8cffff',count=e.type==='hit'?24:e.type==='note'?14:e.type==='dash'?8:4;for(let i=0;i<count;i++){let a=Math.random()*7,v=20+Math.random()*140,l=.2+Math.random()*.5;fx.push({x:e.x,y:e.y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:l,max:l,size:2+Math.random()*3,color,kind:'chip'});}fx.push({x:e.x,y:e.y,vx:0,vy:0,life:.35,max:.35,color,kind:'ring'});if(e.type==='note')fx.push({x:e.x,y:e.y,vx:0,vy:-30,life:.6,max:.6,color,text:'+100',kind:'text'});if(e.type==='checkpoint')announce('CHECKPOINT',1.3);if(e.type==='graze'&&e.value%5===0)toast(e.value+' CHAIN');if(e.type==='hit')toast('Breathe. Keep moving.');fx=fx.slice(-160);}
function doDash(){if(paused||countIn>0||!started)return;let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);if(!dx&&!dy&&target){dx=target.x-s.p.x;dy=target.y-s.p.y;}let length=Math.hypot(dx,dy);if(length>.05){s.p.dx=dx/length;s.p.dy=dy/length;}if(E.dash(s)){event({type:'dash',x:s.p.x,y:s.p.y});s.events=[];}}
function coords(e){let r=$('#world').getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*s.w,y:(e.clientY-r.top)/r.height*s.h};}
$('#world').addEventListener('pointerdown',e=>{if(paused||!started||gesture)return;e.preventDefault();let p=coords(e);gesture={id:e.pointerId,sx:p.x,sy:p.y,x:p.x,y:p.y,px:s.p.x,py:s.p.y};target={x:s.p.x,y:s.p.y};$('#world').setPointerCapture(e.pointerId);$('#touchHint').textContent='';});$('#world').addEventListener('pointermove',e=>{if(!gesture||gesture.id!==e.pointerId)return;let p=coords(e);gesture.x=p.x;gesture.y=p.y;target={x:E.clamp(gesture.px+(p.x-gesture.sx)*1.25,16,s.w-16),y:E.clamp(gesture.py+(p.y-gesture.sy)*1.25,16,s.h-16)};});let release=e=>{if(gesture?.id===e.pointerId){gesture=null;target=null;save();}};for(let type of ['pointerup','pointercancel','lostpointercapture'])$('#world').addEventListener(type,release);
$('#dash').addEventListener('click',e=>{if(e.detail===0)doDash();});$('#dash').addEventListener('pointerdown',e=>{e.preventDefault();$('#dash').setPointerCapture(e.pointerId);$('#dash').classList.add('held');doDash();});for(let type of ['pointerup','pointercancel','lostpointercapture'])$('#dash').addEventListener(type,()=>$('#dash').classList.remove('held'));
document.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();if(e.key==='Escape'){if(paused&&started&&s.mode==='play')resume(false);else pause();return;}keys[e.key.toLowerCase()]=true;if(e.key===' '&&!e.repeat)doDash();if(['w','a','s','d','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))$('#touchHint').textContent='';});document.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);function fastButton(id,fn){$('#'+id).addEventListener('pointerdown',e=>{e.preventDefault();fn();});$('#'+id).addEventListener('click',e=>{if(e.detail===0)fn();});}fastButton('pause',pause);fastButton('library',()=>{started=true;library();});window.addEventListener('blur',()=>{M.stop();if(started&&!paused)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){M.stop();if(started&&!paused)pause();}});window.addEventListener('pagehide',save);
function resize(){let v=A.viewport();if(Math.abs(v.w-s.w)>.01||Math.abs(v.h-s.h)>.01){E.resize(s,v.w,v.h);clear();fx=[];trail=[];save();}}window.addEventListener('resize',resize);
function hud(){let beat=s.time*E.tracks[s.n].bpm/60;$('#progress i').style.width=Math.min(100,beat/E.tracks[s.n].beats*100)+'%';$('#dash i').style.width=Math.max(0,(1-s.p.cool/1.05)*100)+'%';$('#dashLabel').textContent=s.p.cool>0?'CHARGING':'READY';let q=[s.n,s.hp,s.notes,s.grazes,s.score,s.encore].join();if(q===ui)return;ui=q;$('#trackName').textContent=String(s.n+1).padStart(2,'0')+' / '+E.tracks[s.n].name+(s.encore?' · MIX '+s.encore:'');$('#hearts').textContent='◆'.repeat(Math.max(0,s.hp))+'◇'.repeat(4-Math.max(0,s.hp));$('#hearts').setAttribute('aria-label',s.hp+' hearts');$('#notes').textContent='♪ '+s.notes;$('#chain').textContent=s.grazes+' GRAZE';}
function frame(ts){let dt=Math.min(.05,(ts-last)/1000||0);last=ts;resize();if(!paused&&started){if(countIn>0){countIn=Math.max(0,countIn-dt);$('#countdown').textContent=countIn?Math.ceil(countIn/(60/E.tracks[s.n].bpm)):'';if(!countIn){startAudio();announce('LET IT FLOW',1);}}else{acc+=dt;while(acc>=1/60){let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);if(!dx&&!dy&&target){dx=(target.x-s.p.x)/26;dy=(target.y-s.p.y)/26;let len=Math.hypot(dx,dy);if(len>1){dx/=len;dy/=len;}}E.step(s,1/60,{dx,dy});for(let e of s.events)event(e);s.events=[];acc-=1/60;trailTime+=1/60;if(trailTime>.035){trailTime=0;trail.push({x:s.p.x,y:s.p.y,life:s.p.dash?.3:.16,max:s.p.dash?.3:.16,angle:Math.atan2(s.p.dy,s.p.dx),dash:s.p.dash>0});}if(s.mode!=='play')break;}M.sync(s);if(s.phase!==lastPhase){lastPhase=s.phase;if(s.phase===2)announce('BUILD UP',1);if(s.phase===3||s.phase===5)announce('DROP',1);if(s.phase===4)announce('BREATHE',1);}for(let f of fx){f.life-=dt;f.x+=f.vx*dt;f.y+=f.vy*dt;}fx=fx.filter(f=>f.life>0);for(let t of trail)t.life-=dt;trail=trail.filter(t=>t.life>0).slice(-24);toastTime=Math.max(0,toastTime-dt);if(!toastTime)$('#toast').textContent='';announcementTime=Math.max(0,announcementTime-dt);if(!announcementTime)$('#announcement').textContent='';scoreShown+=(s.score-scoreShown)*Math.min(1,dt*10);$('#score').textContent=String(Math.round(scoreShown)).padStart(5,'0');saveTime+=dt;if(saveTime>1){saveTime=0;save();}if(s.mode!=='play'){scoreShown=s.score;$('#score').textContent=String(s.score).padStart(5,'0');hud();A.draw(s,fx,trail,gesture,soft);s.mode==='win'?win():lose();}}}else acc=0;hud();A.draw(s,fx,trail,gesture,soft);requestAnimationFrame(frame);}
window.BeatDebug={snapshot:()=>JSON.parse(JSON.stringify(s)),stats:()=>({paused,started,countIn,gesture:!!gesture,keys:{...keys},audio:M.stats(),fx:fx.length}),view:()=>A.viewport()};intro();requestAnimationFrame(frame);
})();
