(function(root){'use strict';
const tracks=[{name:'FIRST LIGHT',bpm:108,beats:96,kind:0,key:48},{name:'SIDECHAIN',bpm:116,beats:128,kind:1,key:45},{name:'ORBIT CRUSH',bpm:120,beats:128,kind:2,key:48},{name:'GLASS TEETH',bpm:126,beats:128,kind:3,key:50},{name:'AFTERIMAGE',bpm:132,beats:128,kind:4,key:45},{name:'HEARTBREAKER',bpm:136,beats:160,kind:5,key:48}];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function profile(){return{best:Array(6).fill(0),scores:Array(6).fill(0),unlocked:0,skin:0,encore:0};}
function fresh(n=0,w=480,h=640,pf,encore=0){n=clamp(n|0,0,5);return{v:1,n,w,h,time:0,mode:'play',p:{x:w*.18,y:h*.62,r:11,dx:1,dy:0,dash:0,cool:0,inv:1},hp:4,hits:0,score:0,notes:0,grazes:0,combo:0,maxCombo:0,entities:[],notesOn:[],events:[],id:1,lastBeat:-1,checkpoint:0,bank:{score:0,notes:0,grazes:0},profile:pf||profile(),medal:0,rank:'',encore:encore|0,shake:0,flash:0,phase:0};}
function emit(s,type,x,y,value){s.events.push({type,x,y,value});}
function entity(s,o){if(s.entities.length>=180)return;s.entities.push({id:s.id++,age:0,dead:false,grazed:false,warn:0,life:8,...o});}
function bullet(s,x,y,vx,vy,r=10,warn=0){entity(s,{type:'ball',x,y,vx,vy,r,warn,life:9});}
function laser(s,vertical,pos,warn=1,duration=.5){entity(s,{type:'laser',vertical,x:vertical?pos:0,y:vertical?0:pos,width:22,warn,life:warn+duration});}
function fan(s,x,y,tx,ty,count=5,speed=145){let angle=Math.atan2(ty-y,tx-x);for(let i=0;i<count;i++){let a=angle+(i-(count-1)/2)*.19;bullet(s,x,y,Math.cos(a)*speed,Math.sin(a)*speed,9,.35);}}
function ring(s,x,y,phase,speed){let count=16;for(let i=0;i<count;i++){if((i+phase)%count<4)continue;let a=i/count*Math.PI*2;bullet(s,x,y,Math.cos(a)*speed,Math.sin(a)*speed,9,.55);}}
function wall(s,vertical,gap,reverse=false){let length=vertical?s.h:s.w,spacing=length/7,sp=110+Math.min(60,s.encore*7);for(let i=0;i<7;i++){if(Math.abs(i-gap)<=.55)continue;let v=spacing*(i+.5);if(vertical)bullet(s,reverse?s.w+24:-24,v,(reverse?-1:1)*sp,0,13,.45);else bullet(s,v,reverse?s.h+24:-24,0,(reverse?-1:1)*sp,13,.45);}}
function choreography(s,b){const t=tracks[s.n],w=s.w,h=s.h,d=60/t.bpm,p=s.p,late=b>=32,drop=b>=48&&b<80||b>=96,fast=1+Math.min(.35,s.encore*.035);s.phase=b<16?0:b<32?1:b<48?2:b<80?3:b<96?4:5;
 if(b%8===4){let places=[[.3,.28],[.7,.7],[.28,.75],[.72,.3],[.5,.52],[.2,.45],[.8,.55],[.5,.8]],o=places[(Math.floor(b/8)+s.n)%places.length];s.notesOn.push({id:s.id++,x:w*o[0],y:h*o[1],life:5,taken:false});}
 if(b%32===0&&b>0){s.checkpoint=b;s.bank={score:s.score,notes:s.notes,grazes:s.grazes};emit(s,'checkpoint',w*.5,h*.5,b);}
 if(b<4)return;
 if(s.n===0){if(b%8===0)wall(s,true,Math.floor(b/8)%7,false);if(late&&b%8===4)laser(s,false,p.y,d*2,.48);if(drop&&b%16===8)fan(s,w*.86,h*.22,p.x,p.y,3,135);}
 if(s.n===1){if(b%8===0)laser(s,true,clamp(p.x,45,w-45),d*2,.52);if(b%8===4)laser(s,false,clamp(p.y,45,h-45),d*2,.52);if(late&&b%8===2)wall(s,false,(Math.floor(b/8)+2)%7,b%16>7);if(drop&&b%16===6)fan(s,w*.85,h*.2,p.x,p.y,3,145);}
 if(s.n===2){if(b%8===0)ring(s,w*.5,h*.5,(b/8)%16,110*fast);if(late&&b%16===4)entity(s,{type:'bar',x:w*.5,y:h*.5,r:Math.min(w,h)*.38,angle:b*.09,spin:.38*fast,width:18,warn:1.2,life:5});if(drop&&b%8===6)laser(s,true,w*(.2+(b%5)*.15),d*2,.45);}
 if(s.n===3){if(b%8===0)wall(s,false,Math.floor(b/8)%7,false);if(b%8===4)wall(s,true,(Math.floor(b/8)+3)%7,true);if(late&&b%16===2)entity(s,{type:'saw',x:w*.15,y:-45,vx:0,vy:125*fast,r:27,warn:.7,life:9,wiggle:true,origin:w*.15});if(drop&&b%16===10)laser(s,false,p.y,d*2,.5);}
 if(s.n===4){if(b%8===0)fan(s,w*.5,-20,p.x,p.y,5,160*fast);if(b%8===4)fan(s,w*.5,h+20,p.x,p.y,5,160*fast);if(late&&b%16===6){laser(s,true,w*.33,d*2,.55);laser(s,true,w*.67,d*2,.55);}if(drop&&b%16===12)ring(s,w*.8,h*.4,(b/4)%16,115*fast);}
 if(s.n===5){if(b%8===0)fan(s,w*.5,h*.17,p.x,p.y,late?7:5,155*fast);if(b%16===4)laser(s,false,p.y,d*2,.6);if(late&&b%16===8){laser(s,true,w*.25,d*2,.55);laser(s,true,w*.75,d*2,.55);}if(b>=64&&b%16===12)ring(s,w*.5,h*.35,b/4%16,115*fast);if(b>=112&&b%16===6)entity(s,{type:'bar',x:w*.5,y:h*.3,r:Math.min(w,h)*.43,angle:b*.12,spin:-.5,width:20,warn:1.2,life:4});}
}
function dash(s){let p=s.p;if(s.mode!=='play'||p.cool>0)return false;p.dash=.23;p.cool=1.05;p.inv=Math.max(p.inv,.27);emit(s,'dash',p.x,p.y);return true;}
function distanceTo(s,e,x,y,future=0){if(e.type==='laser')return Math.abs((e.vertical?x:y)-(e.vertical?e.x:e.y))-e.width/2;
 if(e.type==='bar'){let a=e.angle+e.spin*future,dx=Math.cos(a)*e.r,dy=Math.sin(a)*e.r,ax=e.x-dx,ay=e.y-dy,bx=e.x+dx,by=e.y+dy,t=clamp(((x-ax)*(bx-ax)+(y-ay)*(by-ay))/((bx-ax)**2+(by-ay)**2),0,1);return Math.hypot(x-ax-t*(bx-ax),y-ay-t*(by-ay))-e.width/2;}
 let ex=e.x+(e.age>=e.warn?(e.vx||0)*future:0),ey=e.y+(e.age>=e.warn?(e.vy||0)*future:0);return Math.hypot(x-ex,y-ey)-(e.r||0);}
function step(s,dt,input={}){s.events=[];if(s.mode!=='play')return;s.time+=dt;s.shake=Math.max(0,s.shake-dt);s.flash=Math.max(0,s.flash-dt);let p=s.p;p.cool=Math.max(0,p.cool-dt);p.inv=Math.max(0,p.inv-dt);p.dash=Math.max(0,p.dash-dt);let dx=input.dx||0,dy=input.dy||0,len=Math.hypot(dx,dy);if(len>.02){dx/=Math.max(1,len);dy/=Math.max(1,len);if(!p.dash){let l=Math.hypot(dx,dy);p.dx=dx/l;p.dy=dy/l;}}if(input.dash)dash(s);let speed=p.dash?650:230;p.x=clamp(p.x+(p.dash?p.dx:dx)*speed*dt,16,s.w-16);p.y=clamp(p.y+(p.dash?p.dy:dy)*speed*dt,16,s.h-16);
 const beat=Math.floor(s.time*tracks[s.n].bpm/60);while(s.lastBeat<beat){s.lastBeat++;choreography(s,s.lastBeat);emit(s,'beat',p.x,p.y,s.lastBeat);}
 for(let e of s.entities){e.age+=dt;if(e.age>=e.warn){if(e.type==='bar')e.angle+=e.spin*dt;else{e.x+=(e.vx||0)*dt;e.y+=(e.vy||0)*dt;if(e.wiggle)e.x=e.origin+Math.sin(e.age*2)*s.w*.24;}}e.life-=dt;if(e.life<=0||e.x< -150||e.x>s.w+150||e.y< -150||e.y>s.h+150){e.dead=true;continue;}if(e.age<e.warn)continue;let d=distanceTo(s,e,p.x,p.y);if(d<p.r&&p.inv<=0){s.hp--;s.hits++;s.combo=0;p.inv=1.25;s.shake=.2;s.flash=.08;emit(s,'hit',p.x,p.y);if(s.hp<=0){s.mode='lose';emit(s,'lose',p.x,p.y);break;}}else if(d>p.r&&d<p.r+18&&!e.grazed){e.grazed=true;s.grazes++;s.score+=15;s.combo++;s.maxCombo=Math.max(s.maxCombo,s.combo);p.cool=Math.max(0,p.cool-.1);emit(s,'graze',p.x,p.y,s.combo);}}
 s.entities=s.entities.filter(e=>!e.dead);for(let n of s.notesOn){n.life-=dt;if(dist(p,n)<p.r+16){n.taken=true;s.notes++;s.score+=100+s.combo*3;s.combo++;s.maxCombo=Math.max(s.maxCombo,s.combo);emit(s,'note',n.x,n.y);}}s.notesOn=s.notesOn.filter(n=>!n.taken&&n.life>0);
 if(s.mode==='play'&&beat>=tracks[s.n].beats){s.mode='win';s.medal=1+(s.notes>=5?1:0)+(s.hits<=2?1:0);s.rank=s.hits===0&&s.notes>=5?'S':s.hits<=2?'A':s.notes>=5?'B':'C';s.score+=s.hp*100+s.grazes*5;let pf=s.profile;pf.best[s.n]=Math.max(pf.best[s.n],s.medal);pf.scores[s.n]=Math.max(pf.scores[s.n],s.score);pf.unlocked=Math.max(pf.unlocked,Math.min(5,s.n+1));if(s.encore)pf.encore=Math.max(pf.encore,s.encore);emit(s,'win',p.x,p.y);}}
function retry(s){let q=fresh(s.n,s.w,s.h,s.profile,s.encore);q.time=s.checkpoint*60/tracks[s.n].bpm;q.lastBeat=s.checkpoint-1;q.checkpoint=s.checkpoint;q.bank=s.bank||{score:0,notes:0,grazes:0};q.score=q.bank.score;q.notes=q.bank.notes;q.grazes=q.bank.grazes;q.hits=s.hits;q.p.inv=2;q.hp=4;q.retried=true;return q;}
function resize(s,w,h){if(w===s.w&&h===s.h)return;let rx=w/s.w,ry=h/s.h;s.p.x*=rx;s.p.y*=ry;for(let e of s.entities){e.x*=rx;e.y*=ry;if(e.vx)e.vx*=rx;if(e.vy)e.vy*=ry;if(e.origin)e.origin*=rx;if(e.type==='bar')e.r=Math.min(w,h)*.38;}for(let n of s.notesOn){n.x*=rx;n.y*=ry;}s.w=w;s.h=h;}
function restore(o){try{if(!o||o.v!==1||!Number.isInteger(o.n)||o.n<0||o.n>5||!['play','win','lose'].includes(o.mode))throw 0;for(let k of ['w','h','time','hp','hits','score','notes','id','lastBeat','checkpoint'])if(!Number.isFinite(o[k]))throw 0;if(o.w<200||o.h<200||o.w>3000||o.h>3000||o.time<0||o.hp>4||o.hp<0)throw 0;if(!o.p||!['x','y','dx','dy','cool','dash','inv'].every(k=>Number.isFinite(o.p[k]))||!Array.isArray(o.entities)||o.entities.length>180||!Array.isArray(o.notesOn)||o.notesOn.length>20)throw 0;for(let e of o.entities)if(!['x','y','age','warn','life'].every(k=>Number.isFinite(e[k]))||!['ball','laser','bar','saw'].includes(e.type))throw 0;let pf=o.profile;if(!pf||!Array.isArray(pf.best)||pf.best.length!==6||pf.best.some(v=>!Number.isInteger(v)||v<0||v>3)||!Array.isArray(pf.scores)||pf.scores.length!==6||pf.scores.some(v=>!Number.isFinite(v)||v<0)||!Number.isInteger(pf.unlocked)||pf.unlocked<0||pf.unlocked>5||![0,1,2].includes(pf.skin))throw 0;if(!Number.isInteger(o.hp)||o.p.r!==11||o.p.x<0||o.p.x>o.w||o.p.y<0||o.p.y>o.h||!['','S','A','B','C'].includes(o.rank)||!Number.isInteger(o.encore)||o.encore<0||o.encore>100000)throw 0;
 for(let k of ['notes','score','grazes'])if(!Number.isFinite(o.bank?.[k])||o.bank[k]<0)throw 0;
 for(let n of o.notesOn)if(!['x','y','life'].every(k=>Number.isFinite(n[k])))throw 0;
 for(let e of o.entities){if(e.type==='bar'&&!['angle','spin','r','width'].every(k=>Number.isFinite(e[k])))throw 0;if(e.type==='laser'&&!Number.isFinite(e.width))throw 0;if(['ball','saw'].includes(e.type)&&!['vx','vy','r'].every(k=>Number.isFinite(e[k])))throw 0;}
 let q=JSON.parse(JSON.stringify(o));q.events=[];return q;}catch{return fresh();}}
const api={tracks,fresh,step,dash,retry,resize,restore,distanceTo,clamp};if(typeof module!=='undefined')module.exports=api;root.BeatEngine=api;
})(typeof window!=='undefined'?window:globalThis);
