(function(root){'use strict';const clone=x=>JSON.parse(JSON.stringify(x)),clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const ROUTES=[{name:'First light',need:3,boats:2,pace:3.6},{name:'Coral express',need:4,boats:3,pace:3.5},{name:'Glasswater',need:4,boats:3,pace:3.1},{name:'The red channel',need:5,boats:4,pace:3.2},{name:'Golden hour',need:5,boats:4,pace:2.8},{name:'Ghost current',need:6,boats:4,pace:2.8},{name:'Afterglow',need:6,boats:5,pace:2.7},{name:'Homeward',need:7,boats:5,pace:2.6}];
const UPGRADES=[{id:'hull',name:'Lifeboat',icon:'♡',desc:'One extra hull point'},{id:'engine',name:'Hydrofoil',icon:'↗',desc:'Move 18% faster'},{id:'dive',name:'Deep breath',icon:'≈',desc:'Dive recharges faster'},{id:'magnet',name:'Tow hook',icon:'⌁',desc:'Pick up cargo from farther away'}];
function lineDistance(p,a,b){let dx=b.x-a.x,dy=b.y-a.y,t=clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1),0,1);return Math.hypot(p.x-a.x-dx*t,p.y-a.y-dy*t);}
class WakeRun{
 constructor(route=1,mods={}){this.route=clamp(Math.floor(route),1,999);this.mods=Object.fromEntries(UPGRADES.map(u=>[u.id,clamp(Math.floor(mods[u.id]||0),0,3)]));this.w=720;this.h=900;this.phase='play';this.time=0;this.id=0;this.player={x:360,y:738,vx:0,vy:0,angle:0,hp:4+this.mods.hull,inv:2,dive:0,cool:0,cargo:false};this.target=null;this.enemies=[];this.cargo=[];this.beams=[];this.mines=[];this.delivered=0;this.kills=0;this.combo=0;this.comboTime=0;this.maxCombo=0;this.score=0;this.hits=0;this.dives=0;this.dodges=0;this.nextCargo=0;this.respawn=0;this.events=[];this.seed=route*113+91;this.paid=false;let cfg=this.config;for(let i=0;i<cfg.boats;i++)this.spawnEnemy(i);this.spawnCargo();}
 get config(){return ROUTES[(this.route-1)%8];}get dock(){return{x:this.w*.5,y:this.h*.9,r:Math.min(this.w,this.h)*.14};}
 random(){this.seed=(this.seed*1664525+1013904223)>>>0;return this.seed/4294967296;}
 resize(w,h){if(!Number.isFinite(w)||!Number.isFinite(h)||w<400||w>1600||h<400||h>1600)return;let sx=w/this.w,sy=h/this.h;for(let p of [this.player,...this.enemies,...this.cargo,...this.mines]){p.x*=sx;p.y*=sy;if(p.aim){p.aim.x*=sx;p.aim.y*=sy;}}for(let b of this.beams){b.a.x*=sx;b.a.y*=sy;b.b.x*=sx;b.b.y*=sy;}this.w=w;this.h=h;this.target=null;}
 spawnEnemy(i){let slots=[[.22,.22],[.78,.22],[.5,.39],[.19,.51],[.81,.51]],q=slots[i%5];let e={id:++this.id,x:this.w*q[0],y:this.h*q[1],baseX:q[0],baseY:q[1],state:'idle',clock:2.5+i*1.1,aim:null,kind:this.route>=3&&i%3===2?'burst':'laser',alive:true,angle:0};this.enemies.push(e);return e;}
 spawnCargo(){if(this.cargo.length||this.player.cargo||this.delivered>=this.config.need)return;let q=[[.50,.57],[.27,.43],[.73,.43],[.50,.26],[.2,.64],[.8,.64]][this.delivered%6];this.cargo.push({id:++this.id,x:this.w*q[0],y:this.h*q[1],spin:0});this.events.push({type:'cargo',x:this.w*q[0],y:this.h*q[1]});}
 steer(x,y){if(this.phase!=='play'||!Number.isFinite(x)||!Number.isFinite(y))return;this.target={x:clamp(x,55,this.w-55),y:clamp(y,65,this.h-65)};}
 dive(){let p=this.player;if(this.phase!=='play'||p.cool>0||p.dive>0)return false;p.dive=1.15+.12*this.mods.dive;p.cool=4.4-.65*this.mods.dive;this.dives++;this.events.push({type:'dive',x:p.x,y:p.y});return true;}
 hit(){let p=this.player;if(p.inv>0||p.dive>0||this.phase!=='play')return false;p.hp--;this.hits++;p.inv=1.9;this.combo=0;this.events.push({type:'hit',x:p.x,y:p.y});if(p.hp<=0){this.phase='lost';this.target=null;this.events.push({type:'lost'});}return true;}
 sink(e){if(!e.alive)return;e.alive=false;this.respawn=Math.max(this.respawn,2.2);this.kills++;this.comboTime=4;this.combo++;this.maxCombo=Math.max(this.maxCombo,this.combo);this.score+=100*Math.min(5,this.combo);this.events.push({type:'sink',x:e.x,y:e.y,combo:this.combo});}
 fire(e,dx=0){let a={x:e.x,y:e.y},aim=e.aim||this.player,angle=Math.atan2(aim.y-e.y,aim.x-e.x)+dx,b={x:e.x+Math.cos(angle)*2200,y:e.y+Math.sin(angle)*2200};let beam={a,b,life:.33};this.beams.push(beam);for(let other of this.enemies)if(other!==e&&other.alive&&lineDistance(other,a,b)<31)this.sink(other);if(this.player.dive>0&&lineDistance(this.player,a,b)<35){this.dodges++;this.score+=50;this.events.push({type:'dodge',x:this.player.x,y:this.player.y});}else if(lineDistance(this.player,a,b)<26)this.hit();this.events.push({type:'fire',x:e.x,y:e.y});}
 update(dt){if(this.phase!=='play')return;dt=clamp(dt,0,.05);this.time+=dt;let p=this.player;p.inv=Math.max(0,p.inv-dt);p.dive=Math.max(0,p.dive-dt);p.cool=Math.max(0,p.cool-dt);this.comboTime=Math.max(0,this.comboTime-dt);if(!this.comboTime)this.combo=0;
 let vx=0,vy=0;if(this.target){let dx=this.target.x-p.x,dy=this.target.y-p.y,d=Math.hypot(dx,dy),speed=(310+this.mods.engine*56)*(p.dive>0?1.22:1);if(d>3){vx=dx/d*Math.min(speed,d/dt);vy=dy/d*Math.min(speed,d/dt);}}p.vx+=(vx-p.vx)*Math.min(1,dt*12);p.vy+=(vy-p.vy)*Math.min(1,dt*12);p.x=clamp(p.x+p.vx*dt,45,this.w-45);p.y=clamp(p.y+p.vy*dt,55,this.h-55);if(Math.hypot(p.vx,p.vy)>10){let desired=Math.atan2(p.vx,-p.vy);let diff=Math.atan2(Math.sin(desired-p.angle),Math.cos(desired-p.angle));p.angle+=diff*Math.min(1,dt*8);p.angle=Math.atan2(Math.sin(p.angle),Math.cos(p.angle));}
 for(let c of this.cargo){c.spin+=dt;if(!p.cargo&&p.dive<=0&&Math.hypot(c.x-p.x,c.y-p.y)<49+this.mods.magnet*19){p.cargo=true;this.cargo=[];this.events.push({type:'pickup',x:p.x,y:p.y});break;}}
 let d=this.dock;if(p.cargo&&p.dive<=0&&Math.hypot(p.x-d.x,p.y-d.y)<d.r){p.cargo=false;this.delivered++;this.score+=250;this.nextCargo=.65;this.events.push({type:'deliver',x:d.x,y:d.y});if(this.delivered>=this.config.need){this.phase='won';this.target=null;this.events.push({type:'won'});return;}}
 if(!p.cargo&&!this.cargo.length){this.nextCargo-=dt;if(this.nextCargo<=0)this.spawnCargo();}
 for(let e of this.enemies){if(!e.alive)continue;e.clock-=dt;if(e.state==='idle'){e.angle=Math.atan2(p.x-e.x,-(p.y-e.y));if(e.clock<=0){e.state='aim';e.clock=1.25;e.aim={x:p.x,y:p.y};this.events.push({type:'aim',x:e.x,y:e.y});}}
 else if(e.state==='aim'){if(e.clock>.4)e.aim={x:p.x,y:p.y};e.angle=Math.atan2(e.aim.x-e.x,-(e.aim.y-e.y));if(e.clock<=0){this.fire(e);if(e.kind==='burst'){this.fire(e,.18);this.fire(e,-.18);}e.state='idle';e.clock=this.config.pace+this.random()*1.1;}}
 if(e.alive&&p.dive<=0&&Math.hypot(p.x-e.x,p.y-e.y)<46)this.hit();}
 this.enemies=this.enemies.filter(e=>e.alive);this.respawn=Math.max(0,this.respawn-dt);if(this.enemies.length<this.config.boats&&this.respawn<=0){let used=new Set(this.enemies.map(e=>Math.round(e.baseX*10)+':'+Math.round(e.baseY*10))),positions=[[.22,.22],[.78,.22],[.5,.39],[.19,.51],[.81,.51]];let i=positions.findIndex(q=>!used.has(Math.round(q[0]*10)+':'+Math.round(q[1]*10)));this.spawnEnemy(i<0?0:i);this.enemies.at(-1).clock=3.8;this.respawn=2;}
 if(this.route>=4&&this.mines.length<2&&this.time>5&&Math.floor((this.time-dt)/9)!==Math.floor(this.time/9)){let q=this.random()>.5?.3:.7;this.mines.push({id:++this.id,x:this.w*q,y:this.h*.68,life:6});}
 for(let m of this.mines){m.life-=dt;if(m.life<.25&&m.life+dt>=.25){for(let e of this.enemies)if(e.alive&&Math.hypot(m.x-e.x,m.y-e.y)<115)this.sink(e);if(Math.hypot(m.x-p.x,m.y-p.y)<110)this.hit();this.events.push({type:'mine',x:m.x,y:m.y});}}
 this.mines=this.mines.filter(m=>m.life>0);for(let b of this.beams)b.life-=dt;this.beams=this.beams.filter(b=>b.life>0);}
 get stars(){return this.phase==='won'?1+(this.hits===0?1:0)+(this.kills>=2?1:0):0;}
 snapshot(){return clone(Object.fromEntries(['route','mods','w','h','phase','time','id','player','enemies','cargo','beams','mines','delivered','kills','combo','comboTime','maxCombo','score','hits','dives','dodges','nextCargo','respawn','seed','paid'].map(k=>[k,this[k]])));}
 static restore(o){try{let finite=(n,a,b)=>Number.isFinite(n)&&n>=a&&n<=b,integer=(n,a,b)=>Number.isInteger(n)&&finite(n,a,b),point=p=>p&&finite(p.x,-2500,4000)&&finite(p.y,-2500,4000);if(!o||!integer(o.route,1,999)||!finite(o.w,400,1600)||!finite(o.h,400,1600)||!['play','won','lost'].includes(o.phase)||!o.mods||!UPGRADES.every(u=>integer(o.mods[u.id],0,3))||!point(o.player)||!integer(o.player.hp,0,7)||!['vx','vy','angle','inv','dive','cool'].every(k=>finite(o.player[k],-1000,1000))||typeof o.player.cargo!=='boolean'||!finite(o.time,0,1e7)||!integer(o.seed,0,4294967295)||typeof o.paid!=='boolean')return null;
 for(let k of ['id','delivered','kills','combo','maxCombo','score','hits','dives','dodges'])if(!integer(o[k],0,1e8))return null;for(let k of ['comboTime','nextCargo','respawn'])if(!finite(o[k],-1,10))return null;
 if(!Array.isArray(o.enemies)||o.enemies.length>5||!o.enemies.every(e=>point(e)&&integer(e.id,1,1e8)&&['idle','aim'].includes(e.state)&&['laser','burst'].includes(e.kind)&&finite(e.clock,-.1,20)&&finite(e.angle,-1000,1000)&&finite(e.baseX,0,1)&&finite(e.baseY,0,1)&&(e.aim===null||point(e.aim))&&typeof e.alive==='boolean')||!Array.isArray(o.cargo)||o.cargo.length>1||!o.cargo.every(c=>point(c)&&integer(c.id,1,1e8)&&finite(c.spin,0,1e7))||!Array.isArray(o.mines)||o.mines.length>2||!o.mines.every(m=>point(m)&&finite(m.life,0,6))||!Array.isArray(o.beams)||o.beams.length>15||!o.beams.every(b=>point(b.a)&&point(b.b)&&finite(b.life,0,.34)))return null;
 let g=new WakeRun(o.route,o.mods);for(let k of Object.keys(g.snapshot()))g[k]=clone(o[k]);g.target=null;g.events=[];if(g.player.hp>4+g.mods.hull||g.paid&&g.phase!=='won'||g.phase==='won'&&g.player.hp===0||g.delivered>g.config.need||g.phase==='won'&&g.delivered!==g.config.need||g.phase==='lost'&&g.player.hp!==0||g.phase==='play'&&g.player.hp===0||g.player.cargo&&g.cargo.length)return null;return g;}catch{return null;}}
}
let API={WakeRun,ROUTES,UPGRADES,lineDistance};if(typeof module!=='undefined')module.exports=API;else Object.assign(root,API);
})(typeof window!=='undefined'?window:globalThis);
