(()=>{'use strict';const $=id=>document.getElementById(id),KEY='petal-ronin-v1';let profile={best:Array(8).fill(0),skin:0,sound:true},s=Ronin.create(),paused=true,screen='intro',clock=0,anim=0,old=null,fx=[],hits=[],hurt=false,toastEnd=0,ctx=null,voices=[],canvas,art,touch=null;
try{const a=JSON.parse(localStorage.getItem(KEY));if(a){profile.best=Array.from({length:8},(_,i)=>Math.max(0,Math.min(3,a.best?.[i]|0)));profile.sound=a.sound!==false;profile.skin=[0,1,2].includes(a.skin)?a.skin:0;s=Ronin.restore(a.state)||s}}catch{}
const stars=()=>profile.best.reduce((a,b)=>a+b,0),allowed=i=>stars()>=[0,6,15][i];if(!allowed(profile.skin))profile.skin=0;
function save(){try{localStorage.setItem(KEY,JSON.stringify({...profile,state:{...s,events:[]}}))}catch{}}
function hush(){for(const o of voices)try{o.stop()}catch{}voices=[]}
function wake(){if(!profile.sound)return;try{ctx??=new(window.AudioContext||window.webkitAudioContext)();ctx.resume()}catch{}}
function tone(f,len=.1,vol=.025,type='sine'){if(paused||!ctx||!profile.sound)return;try{while(voices.length>13){try{voices.shift().stop()}catch{}}const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(f*.55,ctx.currentTime+len);g.gain.setValueAtTime(vol,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+len);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+len);voices.push(o);o.onended=()=>{const i=voices.indexOf(o);if(i>=0)voices.splice(i,1)}}catch{}}
function toast(t){$('toast').textContent=t;toastEnd=clock+1.4}
function resume(){paused=false;screen='play';touch=null;$('overlay').hidden=true;wake();save()}
function start(n){s=Ronin.create(n);anim=0;old=null;fx=[];hits=[];clock=0;resume();toast(Ronin.chapters[n].name)}
function mark(){profile.best[s.level]=Math.max(profile.best[s.level],s.rating);save()}
function sparks(pos,n=12,col='#fff0b9'){for(let i=0;i<n;i++)fx.push({kind:i%4===0?'leaf':'spark',x:90+pos*90,y:570,vx:(Math.random()-.5)*180,vy:-40-Math.random()*120,life:.45+Math.random()*.55,size:3+Math.random()*4,col})}
function effects(){for(const e of s.events){if(e.type==='step'||e.type==='enemy-step')tone(e.type==='step'?160:100,.04,.012,'triangle');if(e.type==='cut'){tone(560,.1,.025,'triangle');fx.push({kind:'arc',x:90+e.pos*90,y:568,vx:0,vy:0,life:.5,col:'#fff3c5'})}if(e.type==='hit'){hits.push(e.id);sparks(e.pos,e.dead?23:10,e.dead?'#e9cfa7':'#fff2b9');tone(e.dead?240:350,.09,.028,'triangle');if(e.friendly)toast('Crossfire!')}if(e.type==='arrow'){tone(740,.08,.018);fx.push({kind:'line',x:90+e.from*90,y:566,tx:90+e.to*90,ty:566,vx:0,vy:0,life:.35,col:'#fff1bf'})}if(e.type==='attack'){for(const n of e.targets)fx.push({kind:'line',x:90+e.from*90,y:580,tx:90+n*90,ty:585,vx:0,vy:0,life:.25,col:'#edb39b'});tone(170,.12,.015,'triangle')}if(e.type==='hurt'){hurt=true;sparks(e.pos,12,'#df9a84');tone(90,.22,.04,'sawtooth');toast('Try another step ↶')}if(e.type==='leaf'){sparks(e.pos,16,'#edd18f');tone(880,.25,.02);toast('A golden leaf')}if(e.type==='wave'){toast('New shadows');tone(300,.3,.025)}if(e.type==='undo'){tone(460,.2,.02);toast('One step back')}if(e.type==='win'){mark();for(let i=0;i<7;i++)sparks(i,9,['#d6aa72','#e8c1a8','#f8e8b6'][i%3]);setTimeout(()=>tone(660,.3,.025),90);setTimeout(()=>tone(880,.4,.025),230);setTimeout(()=>{if(s.won&&screen==='play')modal('win')},900)}}s.events=[];if(fx.length>180)fx.splice(0,fx.length-180)}
function action(a){if(paused||anim>.01||s.won||s.dead)return;wake();const before=JSON.parse(JSON.stringify(s));if(!Ronin.act(s,a)){toast(a==='bow'?'Let the bow rest':a==='cut'?'Step closer':'That path is blocked');return}old=before;anim=1;hits=[];hurt=false;effects();save();if(s.dead)setTimeout(()=>{if(s.dead&&screen==='play')modal('dead')},450)}
function rewind(){if(s.won)return;const before=JSON.parse(JSON.stringify(s));if(Ronin.undo(s)){old=before;anim=1;hits=[];hurt=false;fx=[];resume();effects();save()}}
const hero='<svg viewBox="0 0 110 95" aria-hidden="true"><path d="M35 77l5-28h31l7 28" fill="#74998b"/><path d="M33 39l-2-21 17 11h18l15-11-2 21" fill="#f1e5c5" stroke="#657b6b" stroke-width="2"/><ellipse cx="55" cy="41" rx="25" ry="19" fill="#f1e5c5"/><path d="M22 29L55 6l34 23z" fill="#d6c48f" stroke="#9c9c72" stroke-width="2"/><circle cx="64" cy="43" r="2" fill="#4f6556"/><path d="M34 59l-22 5 15 7 18-7" fill="#abc6ad"/><path d="M78 67L98 39" stroke="#8a9d89" stroke-width="4"/><path d="M77 65l9 3" stroke="#c9a569" stroke-width="4"/></svg>';
function modal(kind){paused=true;screen=kind;touch=null;hush();save();$('overlay').hidden=false;const p=$('panel');if(kind==='intro')p.innerHTML='<div class="eyebrow">ONE SMALL STEP</div><div class="hero">'+hero+'</div><h1>Petal<br>Ronin</h1><p>Read the red tiles. Step out, or strike first.<br>The world waits for your next move.</p><button class="primary" data-act="resume">'+(s.turn?'CONTINUE':'ENTER THE GARDEN')+'</button><button class="secondary" data-act="help">HOW TO PLAY</button><button class="secondary" data-act="book">JOURNAL</button>';
if(kind==='pause')p.innerHTML='<div class="eyebrow">A QUIET BREATH</div><h2>'+Ronin.chapters[s.level].name+'</h2><p>Nothing moves until you do.</p><button class="primary" data-act="resume">CONTINUE</button><button class="secondary" data-act="help">HOW TO PLAY</button><button class="secondary" data-act="book">JOURNAL</button><button class="secondary" data-act="restart-menu">RESTART</button>';
if(kind==='help')p.innerHTML='<div class="eyebrow">WATCH. STEP. STRIKE.</div><div class="legend"><span class="gold">GOLD = WINDING UP</span><span class="red">RED = STRIKES NEXT</span></div><div class="help">‹ › Step one tile. Each action gives the masks a turn.<br><br>CUT hits one adjacent mask and interrupts its attack. BOW hits the nearest mask within three tiles, then rests for three actions.<br><br>WAIT lets the masks act while you stay still. Use ↶ to undo a mistake, even after falling.<br><br>Clear each chapter. Keep all hearts and collect the three leaves for ★★★. No timer.<br><br>Arrows / A D move. Space cuts. E shoots. W waits. Z undoes. Escape pauses.</div><button class="primary" data-act="back">GOT IT</button>';
if(kind==='restart')p.innerHTML='<div class="eyebrow">A FRESH APPROACH</div><h2>Begin this chapter again?</h2><p>Your journal stays safe.</p><button class="primary" data-act="restart">RESTART CHAPTER</button><button class="secondary" data-act="back">KEEP PLAYING</button>';
if(kind==='dead')p.innerHTML='<div class="eyebrow">EVERY STEP TEACHES</div><h2>Take one step back.</h2><p>Undo the last action and try another move.</p><button class="primary" data-act="undo">UNDO ↶</button><button class="secondary" data-act="restart">RESTART CHAPTER</button><button class="secondary" data-act="help">HOW TO PLAY</button>';
if(kind==='book')p.innerHTML='<div class="eyebrow">EIGHT QUIET GARDENS</div><h2>The petal path</h2><p>'+stars()+' / 24 ★ · Maple at 6 · Wisteria at 15</p><div class="grid">'+Ronin.chapters.map((y,i)=>'<button data-act="level" data-n="'+i+'" '+(i&&!profile.best[i-1]?'disabled':'')+' aria-label="'+y.name+'">'+(i+1)+'<small>'+'★'.repeat(profile.best[i])+'☆'.repeat(3-profile.best[i])+'</small></button>').join('')+'</div><div class="skins">'+['Jade','Maple','Wisteria'].map((n,i)=>'<button data-act="skin" data-n="'+i+'" '+(!allowed(i)?'disabled':'')+'>'+n+(profile.skin===i?' ✓':'')+'</button>').join('')+'</div><button class="primary" data-act="back">RETURN</button>';
if(kind==='win')p.innerHTML='<div class="eyebrow">CHAPTER '+(s.level+1)+' / 8</div><h2>A calm victory.</h2><div class="stars">'+'★'.repeat(s.rating)+'☆'.repeat(3-s.rating)+'</div><p>'+s.turn+' steps · '+s.kills+' masks<br>'+(s.damage===0?'All three hearts kept.':'Try another route with ↶.')+'</p><button class="primary" data-act="next">'+(s.level<7?'NEXT GARDEN':'WALK THE PATH AGAIN')+'</button><button class="secondary" data-act="restart">PLAY AGAIN</button><button class="secondary" data-act="book">JOURNAL</button>';
}
function back(){s.won?modal('win'):s.dead?modal('dead'):resume()}
$('panel').onclick=e=>{const b=e.target.closest('[data-act]');if(!b)return;wake();const n=+b.dataset.n;switch(b.dataset.act){case'resume':case'back':back();break;case'next':start((s.level+1)%8);break;case'restart':start(s.level);break;case'restart-menu':modal('restart');break;case'undo':rewind();break;case'book':modal('book');break;case'help':modal('help');break;case'level':if(!n||profile.best[n-1])start(n);break;case'skin':if(allowed(n)){profile.skin=n;save();modal('book')}break}};
for(const b of document.querySelectorAll('[data-action]'))b.onclick=()=>action(b.dataset.action);$('undo').onclick=()=>{if(!paused)rewind()};$('book').onclick=()=>modal('book');$('pause').onclick=()=>paused?back():modal(s.won?'win':s.dead?'dead':'pause');$('sound').onclick=()=>{profile.sound=!profile.sound;if(profile.sound)wake();else hush();save()};$('finish').onclick=()=>{if(!paused&&anim<=.01&&Ronin.finish(s))effects()};
function sync(){const locked=paused||anim>.01||s.won||s.dead;$('level').textContent=String(s.level+1).padStart(2,'0');$('name').textContent=Ronin.chapters[s.level].name.toUpperCase();$('health').textContent='♥ '.repeat(s.hp)+'♡ '.repeat(3-s.hp);$('wave').textContent=(s.wave+1)+' / '+Ronin.chapters[s.level].waves.length;$('leaves').textContent=s.leaves.map(p=>p.found?'◆':'◇').join(' ');$('undo').disabled=paused||!s.history.length||s.won||anim>.01;$('finish').hidden=!!s.enemies.length||s.won||s.dead;$('cooldown').textContent=s.cd?'·'.repeat(s.cd):'BOW';for(const b of document.querySelectorAll('[data-action]')){const a=b.dataset.action;let invalid=a==='left'?(s.pos===0||s.enemies.some(e=>e.pos===s.pos-1)):a==='right'?(s.pos===6||s.enemies.some(e=>e.pos===s.pos+1)):a==='cut'?!s.enemies.some(e=>Math.abs(e.pos-s.pos)===1):a==='bow'?(s.cd>0||!s.enemies.some(e=>Math.abs(e.pos-s.pos)<=3)):false;b.disabled=locked||invalid}$('sound').textContent=profile.sound?'♫':'♪';$('hint').textContent=!s.enemies.length?'Gather the leaves, or tap DONE':s.enemies.some(e=>e.intent==='attack')?'Red tiles strike next · Move or interrupt':'Gold outlines = winding up';if(clock>toastEnd)$('toast').textContent=''}
new p5(p=>{p.setup=()=>{p.pixelDensity(Math.min(1.5,devicePixelRatio||1));canvas=p.createCanvas(720,900).parent('canvas').elt;art=RoninArt(p.drawingContext);p.frameRate(45);resize();window.addEventListener('resize',resize);canvas.onpointerdown=e=>{if(paused)return;touch={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)};canvas.onpointerup=e=>{if(!touch||touch.id!==e.pointerId)return;const dx=e.clientX-touch.x,dy=e.clientY-touch.y;touch=null;if(Math.abs(dx)>25&&Math.abs(dx)>Math.abs(dy))action(dx>0?'right':'left')};canvas.onpointercancel=()=>touch=null;modal(s.won?'win':s.dead?'dead':'intro');sync()};function resize(){const r=$('canvas').getBoundingClientRect(),scale=Math.min(r.width/720,r.height/900);canvas.style.width=scale*720+'px';canvas.style.height=scale*900+'px'}
p.draw=()=>{if(!paused){const dt=Math.min(.05,p.deltaTime/1000);clock+=dt;anim=Math.max(0,anim-dt/.35);for(const f of fx){f.life-=dt;f.x+=f.vx*dt;f.y+=f.vy*dt;if(f.kind==='leaf'||f.kind==='spark')f.vy+=90*dt}fx=fx.filter(f=>f.life>0)}art.draw(s,{clock,anim,old,fx,hits,hurt,skin:profile.skin});sync()}});
// Dispatch touch buttons on release. Some mobile browsers suppress the compatibility click after a canvas swipe.
const touches=new Map();let lastButton=null,lastButtonTime=0;
document.addEventListener('pointerdown',e=>{const b=e.target.closest('button');if(e.pointerType==='touch'&&b&&!b.disabled){e.preventDefault();touches.set(e.pointerId,b)}},true);
document.addEventListener('pointerup',e=>{const b=touches.get(e.pointerId);touches.delete(e.pointerId);if(!b)return;e.preventDefault();const r=b.getBoundingClientRect();if(b.isConnected&&!b.disabled&&e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom){lastButton=b;lastButtonTime=performance.now();b.click()}},true);
document.addEventListener('pointercancel',e=>touches.delete(e.pointerId),true);
document.addEventListener('click',e=>{if(e.isTrusted&&e.target.closest('button')===lastButton&&performance.now()-lastButtonTime<600){e.preventDefault();e.stopImmediatePropagation()}},true);
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(e.repeat)return;const a={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',' ':'cut',e:'bow',w:'wait'}[e.key];if(a)action(a);if(e.key==='z'&&!paused&&anim<=.01)rewind();if(e.key==='Escape')paused?back():modal('pause')});window.addEventListener('blur',()=>{if(!paused)modal(s.won?'win':s.dead?'dead':'pause')});document.addEventListener('visibilitychange',()=>{if(document.hidden){if(!paused)modal(s.won?'win':s.dead?'dead':'pause');save();hush()}});window.addEventListener('pagehide',save);setInterval(save,2000);
window.game={get state(){return s},get profile(){return profile},get paused(){return paused},get locked(){return anim>.01},get voices(){return voices.length}};
})();
