(function(root,f){if(typeof module==='object')module.exports=f();else root.Clover=f();})(typeof globalThis!=='undefined'?globalThis:this,()=>{
'use strict';const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),copy=v=>JSON.parse(JSON.stringify(v));
const layout=[['wall',520],['tower',680],['garden',830],['forge',970],['tower',1120],['wall',1280]];
class Run{
 constructor(){this.n=1;this.state='day';this.t=0;this.x=900;this.dir=0;this.facing=1;this.coins=16;this.camp=100;this.buildings=layout.map(([type,x],id)=>({id,type,x,level:0,hp:0,cd:0}));this.enemies=[];this.shots=[];this.drops=[];this.baskets=[{x:260,taken:false},{x:1540,taken:false}];this.timer=0;this.spawned=0;this.kills=0;this.pulseCd=0;this.pulseHits=0;this.broken=0;this.campHurt=0;this.hurt=0;this.light=0;this.stars=0;this.events=[];this.dawn=null;this.nextId=1;}
 emit(type,o={}){this.events.push({type,x:this.x,y:0,...o});}
 wallMax(b){return[0,140,260,400][b.level];}
 near(){return this.buildings.reduce((best,b)=>Math.abs(b.x-this.x)<88&&(!best||Math.abs(b.x-this.x)<Math.abs(best.x-this.x))?b:best,null);}
 offer(b=this.near()){if(!b)return null;if(b.type==='wall'&&b.level&&b.hp<this.wallMax(b)-1)return{cost:2,label:'Repair',id:b.id};if(b.level>=3)return{cost:0,label:'Complete',id:b.id};if(b.type==='forge'&&this.n<2)return{cost:0,label:'Night 2',id:b.id};if(b.level===1&&this.n<3)return{cost:0,label:'Night 3',id:b.id};if(b.level===2&&this.n<6)return{cost:0,label:'Night 6',id:b.id};return{cost:(b.type==='wall'?[2,3,5]:b.type==='tower'?[3,4,6]:b.type==='garden'?[3,4,6]:[4,6,9])[b.level],label:b.level?'Upgrade':'Build',id:b.id};}
 pay(){if(!['day','night'].includes(this.state))return false;const b=this.near(),o=this.offer(b);if(!o||!o.cost)return false;if(this.coins<o.cost){this.emit('poor');return false;}this.coins-=o.cost;if(o.label==='Repair')b.hp=this.wallMax(b);else{b.level++;if(b.type==='wall')b.hp=this.wallMax(b);}this.emit('build',{x:b.x,typeName:b.type,level:b.level,repair:o.label==='Repair'});return true;}
 move(d){this.dir=clamp(Number(d)||0,-1,1);}
 cancel(){this.dir=0;}
 night(){if(this.state!=='day')return false;this.cancel();this.dawn=this.snapshot(false);this.state='night';this.timer=0;this.spawned=0;this.kills=0;this.pulseHits=0;this.broken=0;this.campHurt=0;this.pulseCd=0;this.emit('night');return true;}
 pulse(){if(!['day','night'].includes(this.state)||this.pulseCd>0)return false;const f=this.buildings[3].level;this.pulseCd=4.2-f*.45;let hits=0;for(const e of this.enemies)if(Math.abs(e.x-this.x)<200+f*25&&e.hp>0){e.hp-=38+f*14;e.x+=e.side*65;e.stun=.8;hits++;this.pulseHits++;this.emit('hit',{x:e.x,y:e.y});}this.emit('pulse',{radius:200+f*25,hits});this.cleanEnemies();return true;}
 waveCount(){return Math.min(24,4+this.n);}
 spawn(){const k=this.spawned,side=k%2?-1:1,n=this.n;let kind=n>=8&&k===this.waveCount()-1?'brute':n>=5&&k%4===2?'fly':n>=3&&k%4===1?'shield':k%3===2?'runner':'mote';const hp=(kind==='brute'?145:kind==='shield'?68:kind==='fly'?35:kind==='runner'?34:42)+Math.min(30,Math.max(0,n-3)*3);this.enemies.push({id:this.nextId++,x:side===1?1740:60,y:kind==='fly'?-78:-13,side,hp,max:hp,kind,cd:0,stun:0});this.spawned++;this.emit('spawn',{side});}
 cleanEnemies(){for(const e of this.enemies)if(e.hp<=0){this.kills++;this.emit('pop',{x:e.x,y:e.y,kind:e.kind});this.drops.push({x:e.x,y:e.y-15,vx:(e.id%2?1:-1)*35,vy:-100,value:e.kind==='brute'?4:1});}this.enemies=this.enemies.filter(e=>e.hp>0);if(this.drops.length>40)this.drops.splice(0,this.drops.length-40);}
 step(dt){if(!['day','night'].includes(this.state))return;this.t+=dt;this.x=clamp(this.x+this.dir*245*dt,100,1700);if(this.dir)this.facing=Math.sign(this.dir);this.pulseCd=Math.max(0,this.pulseCd-dt);this.hurt=Math.max(0,this.hurt-dt);this.light=clamp(this.light+(this.state==='night'?dt*.6:-dt*.6),0,1);
 if(this.state==='day')for(const b of this.baskets)if(!b.taken&&Math.abs(b.x-this.x)<45){b.taken=true;this.coins=Math.min(120,this.coins+3);this.emit('coin',{x:b.x,amount:3});}
 for(const d of this.drops){if(Math.abs(d.x-this.x)<115){d.x+=(this.x-d.x)*dt*8;d.y+=(-30-d.y)*dt*8;if(Math.abs(d.x-this.x)<20){this.coins=Math.min(120,this.coins+d.value);d.value=0;this.emit('coin',{x:d.x,amount:1});}}else{d.x+=d.vx*dt;d.y+=d.vy*dt;d.vy+=300*dt;if(d.y>0){d.y=0;d.vy=-d.vy*.28;d.vx*=.7;}}}this.drops=this.drops.filter(d=>d.value>0);
 if(this.state!=='night')return;this.timer+=dt;if(this.spawned<this.waveCount()&&this.timer>=1+this.spawned*1.9)this.spawn();
 for(const e of this.enemies){e.cd=Math.max(0,e.cd-dt);e.stun=Math.max(0,e.stun-dt);if(e.stun>0)continue;const speed=e.kind==='fly'?85:e.kind==='runner'?72:37+Math.min(15,this.n)*1.6;let target=900;if(e.kind!=='fly'){const wall=this.buildings[e.side===1?5:0];if(wall.level&&wall.hp>0&&(e.side===1?e.x>=wall.x-16:e.x<=wall.x+16))target=wall.x;}if(Math.abs(e.x-target)>16)e.x-=e.side*speed*dt;else if(e.cd<=0){e.cd=1.05;const wall=this.buildings[e.side===1?5:0],damage=(e.kind==='brute'?22:6)+Math.min(10,Math.floor(this.n/3)*2);if(target!==900){wall.hp=Math.max(0,wall.hp-damage);this.emit('wallhit',{x:wall.x});if(wall.hp===0){this.broken++;this.emit('break',{x:wall.x});}}else{this.camp=Math.max(0,this.camp-damage);this.campHurt+=damage;this.emit('camphit',{x:900});}}
 if(e.kind!=='fly'&&this.hurt===0&&Math.abs(e.x-this.x)<27){this.hurt=1.2;this.x=clamp(this.x-e.side*25,100,1700);this.emit('bonk');}}
 for(const b of this.buildings.filter(b=>b.type==='tower'&&b.level)){b.cd=Math.max(0,b.cd-dt);if(b.cd<=0){const targets=this.enemies.filter(e=>e.hp>0&&Math.abs(e.x-b.x)<480).sort((a,z)=>Math.abs(a.x-900)-Math.abs(z.x-900));if(targets[0]&&this.shots.length<24){b.cd=[0,1.9,1.45,1.05][b.level];this.shots.push({x:b.x,y:-83-b.level*12,target:targets[0].id,damage:14+b.level*8,life:3});this.emit('shot',{x:b.x,y:-83-b.level*12});}}}
 for(const a of this.shots){a.life-=dt;const e=this.enemies.find(e=>e.id===a.target&&e.hp>0);if(!e){a.life=0;continue;}const dx=e.x-a.x,dy=e.y-a.y,d=Math.hypot(dx,dy);if(d<20){e.hp-=a.damage*(e.kind==='shield'?.65:1);a.life=0;this.emit('hit',{x:e.x,y:e.y});}else{a.x+=dx/d*460*dt;a.y+=dy/d*460*dt;}}
 this.shots=this.shots.filter(a=>a.life>0);this.cleanEnemies();if(this.camp<=0){this.state='lost';this.cancel();this.emit('lost');return;}if(this.spawned===this.waveCount()&&!this.enemies.length){this.coins=Math.min(120,this.coins+this.drops.reduce((s,d)=>s+d.value,0));this.drops=[];this.shots=[];this.stars=1+(this.campHurt===0?1:0)+(this.broken===0?1:0);this.state='won';this.light=.2;this.cancel();this.emit('won');}
 }
 next(){if(this.state!=='won')return false;this.n=Math.min(999,this.n+1);this.state='day';this.coins=Math.min(120,this.coins+6+this.buildings[2].level*2);this.camp=100;for(const b of this.buildings){b.cd=0;if(b.type==='wall')b.hp=this.wallMax(b);}this.x=900;this.dir=0;this.timer=0;this.pulseCd=0;this.baskets.forEach(b=>b.taken=false);this.enemies=[];this.shots=[];this.drops=[];this.dawn=null;this.stars=0;this.light=0;this.emit('dawn');return true;}
 retry(){if(!this.dawn)return new Run();return Run.restore(this.dawn)||new Run();}
 snapshot(includeDawn=true){const o={};for(const k of ['n','state','t','x','facing','coins','camp','buildings','enemies','shots','drops','baskets','timer','spawned','kills','pulseCd','pulseHits','broken','campHurt','hurt','light','stars','nextId'])o[k]=this[k];o.dawn=includeDawn?this.dawn:null;return copy(o);}
 static restore(s){try{if(!s||!Number.isInteger(s.n)||s.n<1||s.n>999||!['day','night','won','lost'].includes(s.state))return null;const r=new Run();for(const k of ['t','x','coins','camp','timer','spawned','kills','pulseCd','pulseHits','broken','campHurt','hurt','light','stars','nextId'])if(!Number.isFinite(s[k])||Math.abs(s[k])>1e8)return null;if(s.x<100||s.x>1700||s.coins<0||s.coins>120||s.camp<0||s.camp>100)return null;if(!Array.isArray(s.buildings)||s.buildings.length!==6)return null;for(let i=0;i<6;i++){const b=s.buildings[i];if(b.id!==i||b.type!==layout[i][0]||b.x!==layout[i][1]||!Number.isInteger(b.level)||b.level<0||b.level>3||!Number.isFinite(b.hp)||b.hp<0||b.hp>400||!Number.isFinite(b.cd))return null;}for(const [k,max]of [['enemies',24],['shots',24],['drops',40],['baskets',2]])if(!Array.isArray(s[k])||s[k].length>max||s[k].some(o=>!o||Object.values(o).some(v=>typeof v==='number'&&!Number.isFinite(v))))return null;Object.assign(r,copy(s));r.dir=0;r.events=[];return r;}catch{return null;}}
}
return {Run,layout};});


