(function(root){'use strict';function make(){let ctx=null,master=null,at=0,next=0,active=false,mute=false,level=0,beat=.66,voices=new Set(),scheduled=0;const semis=[0,3,7,10,12,15,19,22];
function init(){if(!ctx)try{ctx=new(window.AudioContext||window.webkitAudioContext)({latencyHint:'interactive'});master=ctx.createGain();master.gain.value=0;master.connect(ctx.destination)}catch{}if(ctx?.state==='suspended')ctx.resume().catch(()=>{})}
function tone(freq,start,dur=.16,gain=.15,type='sine'){if(!ctx||!active||mute)return;const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,start);g.gain.setValueAtTime(.0001,start);g.gain.exponentialRampToValueAtTime(gain,start+.012);g.gain.exponentialRampToValueAtTime(.0001,start+dur);o.connect(g);g.connect(master);o.start(start);o.stop(start+dur+.02);voices.add(o);scheduled++;o.onended=()=>{voices.delete(o);o.disconnect();g.disconnect()}}
function stop(){active=false;if(master){master.gain.cancelScheduledValues(0);master.gain.value=0}for(let o of voices)try{o.stop()}catch{}voices.clear()}
function begin(s,p){init();stop();active=true;mute=p.mute;level=s.level;beat=s.beat;at=(ctx?ctx.currentTime:performance.now()/1000)-s.time;next=Math.ceil(s.time/beat*2+.01);for(let n of s.notes)if(n.at-2*beat>s.time)n.cued=false;if(master){master.gain.cancelScheduledValues(0);master.gain.value=mute?0:.32}}
function clock(){return(ctx?ctx.currentTime:performance.now()/1000)-at}
function pump(s){if(!active||!ctx)return;const now=clock();while(next*beat/2<now+.12){const step=next++,time=step*beat/2,when=at+time;if(when<ctx.currentTime-.01)continue;const b=Math.floor(step/2),root=DreamEngine.tracks[level].key,base=130.81*Math.pow(2,(root+[0,5,3,7][Math.floor(b/4)%4])/12);if(step%2===0){tone(base,when,.24,.13,'triangle');tone(b%4===0?82:110,when,.065,.13,'sine');tone(523.25*Math.pow(2,(root+semis[b%8])/12),when,.19,.045,'sine');if(b%4===0)for(let k of [0,3,7])tone(base*Math.pow(2,(k+12)/12),when,beat*3.5,.025,'sine')}else tone(1500,when,.035,.018,'triangle');}for(let n of s.notes){if(!n.cued&&n.at-2*beat<now+.12){n.cued=true;let when=at+n.at-2*beat;if(when>ctx.currentTime)tone(660*Math.pow(2,n.kind/12),when,.13,.08,'sine')}}}
function hit(g){if(!ctx||!active)return;const f=g==='perfect'?880:g==='nice'?660:190;tone(f,ctx.currentTime,.14,g==='early'?.06:.18,g==='early'?'triangle':'sine');if(g==='perfect')tone(f*1.25,ctx.currentTime+.06,.22,.07)}
function celebrate(){stop();active=true;if(master){master.gain.cancelScheduledValues(0);master.gain.value=mute?0:.32};if(ctx)for(let i=0;i<4;i++)tone([523,659,784,1047][i],ctx.currentTime+i*.09,.3,.12)}
function setMute(v){mute=v;if(master){master.gain.cancelScheduledValues(0);master.gain.value=active&&!v?.32:0}}
return{init,begin,stop,pump,clock,hit,setMute,celebrate,get ready(){return!!ctx},get info(){return{gain:master?.gain.value||0,voices:voices.size,scheduled,active,context:ctx?.state||'none'}}}}
root.DreamAudio={make};})(window);
