(()=>{'use strict';const E=StillEngine,$=id=>document.getElementById(id),storage='stillframe-v1';let s=E.create(),art=new StillArt($('scene')),canvas=art.canvas,paused=true,modal='start',last=0,acc=0,paint=0,worldPaint=0,celebrate=0,dirty=true,pointer=null,point=null,pending=null,moved=false,fireIds=new Set(),keys=new Set(),events=[],lastMode='play',saveTick=0,toastEnd=5,replay=null,audio=null,master=null,voices=[];let saved=null;try{saved=E.restore(localStorage.getItem(storage));if(saved)s=saved}catch{}
function save(){try{localStorage.setItem(storage,JSON.stringify(s))}catch{}}
function release(){pointer=null;point=null;pending=null;fireIds.clear();keys.clear();$('fire').classList.remove('active');dirty=true}
function silence(){if(master)master.gain.value=0;for(const o of voices)try{o.stop()}catch{}voices=[]}
function sound(type){if(s.p.mute||paused||replay)return;try{if(!audio){audio=new(window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.connect(audio.destination)}audio.resume();master.gain.value=.13;const notes={fire:[100,60],enemyfire:[160],shatter:[500,390,240,130],glass:[720,500,280],blast:[70,42],crack:[240,120],punch:[120,60],slice:[450,170],pickup:[330,440],throw:[160,90],token:[660,880,1100],hurt:[120,75],win:[220,330,440,660]};for(const[n,f]of(notes[type]||[200]).entries()){if(voices.length>=18)try{voices.shift().stop()}catch{}const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+n*.035;o.type=['fire','shatter','blast','crack','punch','glass'].includes(type)?'triangle':'sine';o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(Math.max(30,f*.5),t+.17);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.55,t+.006);g.gain.exponentialRampToValueAtTime(.001,t+.2);o.connect(g);g.connect(master);o.start(t);o.stop(t+.22);voices.push(o);o.onended=()=>{const i=voices.indexOf(o);if(i>=0)voices.splice(i,1);o.disconnect();g.disconnect()}}}catch{}}
function toast(t){$('toast').textContent=t;toastEnd=s.time+2.5;dirty=true}
function handle(e){events.push(e);sound(e.type);if(e.type==='pickup')toast('Weapon acquired');if(e.type==='token')toast('Memory recovered');if(e.type==='disarm')toast('Disarmed');if(e.type==='hurt')toast('Stop. Read the next shot.');if(e.type==='blast')toast('Chain reaction');}
function hud(){const p=s.player,w=p.weapon;$('chapter').textContent=s.wave?'ENDLESS / WAVE '+s.wave:String(s.level+1).padStart(2,'0')+' / '+s.map.title.toUpperCase();$('clock').textContent=s.rate>0?'TIME FLOWS':'TIME HELD';$('clock').classList.toggle('live',s.rate>0);$('health').textContent='◆'.repeat(Math.max(0,p.hp))+'◇'.repeat(3-Math.max(0,p.hp));$('weapon').textContent=w?w.kind.toUpperCase():'UNARMED';$('ammo').textContent=!w?'—':w.ammo<0?'∞':w.ammo===0?'EMPTY':'● '.repeat(w.ammo).trim();$('fireLabel').textContent=!w||w.ammo===0?'STRIKE':w.kind==='blade'?'SLICE':'FIRE';$('throw').disabled=!w;$('tokens').textContent='◇ '+s.map.tokens.filter(o=>o.done).length+' / 2';$('sound').textContent=s.p.mute?'♩':'♫';if(s.time>toastEnd)$('toast').textContent=s.enemies.filter(o=>o.alive).length+' red figures remain';
const dirs=$('directions');dirs.innerHTML='';const off=s.enemies.filter(o=>o.alive).map(o=>({o,pos:art.screen(o,40)})).filter(({pos})=>pos.x<12||pos.x>art.w-12||pos.y<12||pos.y>art.h-12).sort((a,b)=>E.dist(s.player,a.o)-E.dist(s.player,b.o))[0];if(off){const a=document.createElement('i');a.textContent='➤';const cx=art.w/2,cy=art.h/2,dx=off.pos.x-cx,dy=off.pos.y-cy,k=Math.min((cx-22)/Math.max(1,Math.abs(dx)),(cy-22)/Math.max(1,Math.abs(dy)));a.style.left=cx+dx*k+'px';a.style.top=cy+dy*k+'px';a.style.transform='translate(-50%,-50%) rotate('+Math.atan2(dy,dx)+'rad)';dirs.appendChild(a)}const map=$('map');map.innerHTML='';const dot=(x,y,w,h,color)=>{const i=document.createElement('i');Object.assign(i.style,{left:x/s.map.W*100+'%',top:y/s.map.H*100+'%',width:Math.max(2,w/s.map.W*100)+'%',height:Math.max(2,h/s.map.H*100)+'%',background:color});map.appendChild(i)};for(const o of s.map.covers)dot(o.x,o.y,o.w,o.h,'#bbc6cd');for(const e of s.enemies)if(e.alive)dot(e.x-9,e.y-9,18,18,'#d62a38');for(const t of s.map.tokens)if(!t.done)dot(t.x-6,t.y-6,12,12,'#6bafbf');dot(p.x-12,p.y-12,24,24,'#263544');}
function button(t,fn,cls=''){const b=document.createElement('button');b.textContent=t;b.className=cls;b.onclick=fn;return b}
function show(kind,html){release();paused=true;modal=kind;silence();$('overlay').classList.remove('hidden');$('card').innerHTML=html;dirty=true;save()}
function add(t,fn,cls=''){const b=button(t,fn,cls);$('card').appendChild(b);return b}
function resume(){release();modal='';paused=false;$('overlay').classList.add('hidden');dirty=true;last=0;acc=0;save()}
const hero='<div class="hero"><svg viewBox="0 0 280 115" aria-hidden="true"><path d="M17 92H264" stroke="#d5dcdf" stroke-width="2"/><g fill="#d52c3b"><path d="M164 13L177 7L189 19L184 36L168 35Z M165 39L185 35L194 61L177 76L156 61Z M174 72L182 73L184 104L175 104Z M160 65L172 73L155 100L147 96Z M187 40L196 45L216 33L221 39L197 59Z"/><path d="M116 48L122 41L127 52Z M219 78L229 73L224 86Z M206 15L213 8L215 20Z"/></g><g fill="#283440"><path d="M67 32L76 27L86 34L82 47L70 48Z M68 50L83 48L90 70L76 82L62 70Z M63 72L72 79L62 105L55 102Z M77 80L84 77L90 105L81 105Z M85 53L107 54L109 62L87 65Z"/><path d="M105 49H135V56H114V64H107Z"/></g><path d="M140 55H153" stroke="#d22e38" stroke-width="3"/></svg></div>';
function start(){show('start','<span class="eyebrow">A SMALL CINEMATIC TIME PUZZLE</span><h1>STILL<br>FRAME.</h1>'+hero+'<p>Move, and the world moves.<br>Stop, and the next moment is yours.</p>');add(saved?'Continue':'Enter the moment',()=>s.mode==='win'?result():s.mode==='lost'?lost():resume(),'primary');add('How to play',help);add('Scene archive',archive);$('card').insertAdjacentHTML('beforeend','<p class="notes">9 scenes · real-time replays · endless after scene 3</p>')}
function pause(){if(replay){endReplay();return}if(paused)return;show('pause','<span class="eyebrow">EVERY SECOND IS YOURS</span><h2>Hold that thought.</h2>');add('Continue',resume,'primary');add('How to play',help);add('Scene archive',archive);add('Restart scene',confirmRestart)}
function help(){show('help','<span class="eyebrow">READ. MOVE. REACT.</span><h2>Own the moment.</h2><div class="rule"><b>↔</b><span>Drag to move. Release to freeze the world.<br>Tap a red figure or black barrel to aim.</span></div><div class="rule"><b>◎</b><span>Hold Fire to shoot and keep time flowing.<br>Empty-handed? Get close and Strike.</span></div><div class="rule"><b>↗</b><span>Throw a weapon to crack or disarm a foe.<br>Walk over black weapons when empty.</span></div><p>Shatter every red figure. Blue memories are optional. Stop to read the red targeting lines and suspended bullets.</p><p class="notes">WASD / arrows: move · Space / E: fire · Q: throw · P: pause<br>Actions briefly advance time, even while standing.</p>');add('Got it',()=>s.mode==='win'?result():s.mode==='lost'?lost():resume(),'primary')}
function restart(){s=E.create(s.level,s.p,s.wave);art.invalidate();lastMode='play';resume();toast('A fresh moment')}
function confirmRestart(){show('confirm','<h2>Replay this moment?</h2><p>Your archive stays. The current scene resets.</p>');add('Restart',restart,'primary');add('Go back',()=>{paused=false;pause()})}
function lost(){show('lost','<span class="eyebrow">A MOMENT TOO LATE</span><h2>Try another angle.</h2><p>Release your finger to freeze the bullets.<br>Cover blocks shots. Fallen weapons are yours.</p>');add('Retry scene',restart,'primary');add('Watch this attempt',beginReplay);add('Scene archive',archive)}
function result(){const stars=s.wave?null:s.p.best[s.level];show('win','<span class="eyebrow">'+(s.wave?'WAVE '+s.wave+' CLEARED':'SCENE '+(s.level+1)+' COMPLETE')+'</span><h2>'+(s.level===8&&!s.wave?'You owned every moment.':'A beautiful exit.')+'</h2>'+(stars?'<div class="rating">'+'✦'.repeat(stars)+'<span style="opacity:.18">'+'✦'.repeat(3-stars)+'</span></div>':'')+'<p>'+s.kills+' shattered · '+s.shots+' shots · '+s.time.toFixed(1)+' world seconds<br>'+s.map.tokens.filter(o=>o.done).length+' / 2 memories · '+(s.damage?'Vitality lost: '+s.damage:'Untouched')+'</p>');add('Watch replay',beginReplay,'primary');if(s.wave)add('Next wave',()=>{s=E.create(0,s.p,s.wave+1);art.invalidate();lastMode='play';resume()});else if(s.level<8)add('Next scene',()=>{s=E.create(s.level+1,s.p);art.invalidate();lastMode='play';resume();toast('Read the room')});add('Scene archive',archive);add('Save frame',postcard);save()}
function archive(){const before=s.mode;show('archive','<span class="eyebrow">SCENE ARCHIVE · '+s.p.best.reduce((a,b)=>a+b,0)+' / 27</span><h2>Another angle.</h2><div class="grid" id="scenes"></div><div class="row" id="accents"></div>');E.titles.forEach((t,i)=>{const b=button('',()=>{show('revisit','<h2>'+t+'</h2><p>Enter a fresh scene? Your ratings stay.</p>');add('Enter scene',()=>{s=E.create(i,s.p);art.invalidate();lastMode='play';resume()},'primary');add('Go back',archive)});b.setAttribute('aria-label','Scene '+(i+1)+': '+t);b.innerHTML=String(i+1).padStart(2,'0')+' / '+t+'<small>'+(s.p.best[i]?'✦'.repeat(s.p.best[i]):i>s.p.unlocked?'LOCKED':'READY')+'</small>';b.disabled=i>s.p.unlocked;$('scenes').appendChild(b)});['Ice','Gold','Violet'].forEach((t,i)=>{const b=button(t,()=>{s.p.accent=i;save();dirty=true;archive()});b.setAttribute('aria-label',t+' accent');const stars=s.p.best.reduce((a,b)=>a+b,0);b.disabled=stars<i*6;if(b.disabled)b.textContent=t+' / '+i*6+'✦';if(s.p.accent===i)b.style.borderColor='#d32839';$('accents').appendChild(b)});const endless=add('Endless / best '+s.p.bestWave,()=>{show('endless','<h2>Keep the moment.</h2><p>Repeating arenas, fresh crossfire.<br>Three vitality and a new pistol each wave.</p>');add('Begin endless',()=>{s=E.create(0,s.p,1);art.invalidate();lastMode='play';resume()},'primary');add('Go back',archive)});endless.disabled=s.p.unlocked<3;if(endless.disabled)endless.textContent='Endless / finish scene 3';add('Back',()=>before==='win'?result():before==='lost'?lost():resume(),'primary')}
function beginReplay(){if(s.record.length<2)return;art.fx=[];release();paused=true;silence();$('overlay').classList.add('hidden');$('replayBar').hidden=false;replay={t:s.record[0].t,idx:0,lastIdx:-1};dirty=true}
function endReplay(){art.fx=[];replay=null;$('replayBar').hidden=true;dirty=true;s.mode==='win'?result():s.mode==='lost'?lost():pause()}
$('closeReplay').onclick=endReplay;
function postcard(){art.render(s,[],0);const c=document.createElement('canvas');c.width=1000;c.height=660;const x=c.getContext('2d');x.fillStyle='#fafaf8';x.fillRect(0,0,1000,660);x.drawImage(canvas,25,25,950,525);x.fillStyle='#d32a39';x.font='bold 33px Arial';x.fillText('STILLFRAME / '+s.map.title.toUpperCase(),30,598);x.fillStyle='#657580';x.font='12px monospace';x.fillText(s.kills+' SHATTERED / '+s.time.toFixed(1)+' WORLD SECONDS / OWN THE MOMENT',33,630);const a=document.createElement('a');a.download='stillframe-'+(s.wave?'wave-'+s.wave:'scene-'+(s.level+1))+'.png';a.href=c.toDataURL('image/png');a.click()}
function candidate(x,y){let found=null,best=34;for(const e of s.enemies.filter(o=>o.alive).map(o=>({...o,type:'enemy',height:43})).concat(s.map.barrels.filter(o=>!o.broken).map(o=>({...o,type:'barrel',height:25})))){const p=art.screen(e,e.height),d=Math.hypot(p.x-x,p.y-y);if(d<best){best=d;found={kind:e.type,id:e.id}}}return found}
function bindCanvas(){canvas=art.canvas;canvas.addEventListener('pointerdown',e=>{if(paused||s.mode!=='play'||pointer!==null)return;pointer=e.pointerId;canvas.setPointerCapture(e.pointerId);const b=canvas.getBoundingClientRect();pending=candidate(e.clientX-b.x,e.clientY-b.y);moved=!pending;point={x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY};if(pending){s.selected=pending;dirty=true}e.preventDefault()});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==pointer)return;if(point&&Math.hypot(e.clientX-point.sx,e.clientY-point.sy)>12)moved=true;if(point){point.x=e.clientX;point.y=e.clientY}});for(const n of['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(n,e=>{if(pointer===e.pointerId){pointer=null;point=null;pending=null;dirty=true}})}bindCanvas();
$('fire').addEventListener('pointerdown',e=>{if(paused)return;fireIds.add(e.pointerId);$('fire').setPointerCapture(e.pointerId);$('fire').classList.add('active');dirty=true;e.preventDefault()});for(const n of['pointerup','pointercancel','lostpointercapture'])$('fire').addEventListener(n,e=>{fireIds.delete(e.pointerId);if(!fireIds.size)$('fire').classList.remove('active');dirty=true});function doThrow(){if(paused)return;if(E.toss(s)){s.events.forEach(handle);s.events=[];dirty=true}}$('throw').addEventListener('pointerdown',e=>{doThrow();e.preventDefault()});$('pause').onclick=pause;$('sound').onclick=()=>{s.p.mute=!s.p.mute;if(s.p.mute)silence();save();hud()};
window.addEventListener('keydown',e=>{if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();if(['p','P','Escape'].includes(e.key)&&!e.repeat){if(paused&&modal==='pause')resume();else pause();return}if(paused)return;keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==='q'&&!e.repeat)doThrow();dirty=true});window.addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());dirty=true});function resize(){release();art.resize();art.render(s,[],0);dirty=true}window.addEventListener('resize',resize);if(window.ResizeObserver)new ResizeObserver(resize).observe($('stage'));window.addEventListener('still-render-fallback',()=>{bindCanvas();pause();toast('Canvas compatibility mode is ready')});window.addEventListener('blur',()=>{if(!replay)pause();else endReplay();release();save()});document.addEventListener('visibilitychange',()=>{if(document.hidden){if(replay)endReplay();else pause();release();save()}});window.addEventListener('pagehide',save);
function input(){const k=a=>keys.has(a),dx=(k('d')||k('arrowright')?1:0)-(k('a')||k('arrowleft')?1:0),dy=(k('s')||k('arrowdown')?1:0)-(k('w')||k('arrowup')?1:0);let target=null;if(point&&moved){const b=canvas.getBoundingClientRect();target=art.world(point.x-b.x,point.y-b.y)}return{dx,dy,target,fire:fireIds.size>0||k(' ')||k('e')}}
function drawReplay(dt){replay.t+=dt;const fs=s.record;if(replay.t>=fs.at(-1).t+.1){endReplay();return}while(replay.idx<fs.length-2&&fs[replay.idx+1].t<replay.t)replay.idx++;const a=fs[replay.idx],b=fs[Math.min(fs.length-1,replay.idx+1)],k=E.clamp((replay.t-a.t)/(b.t-a.t||1),0,1),q=E.applyFrame(s,a);q.time=replay.t;const lerp=(o,z)=>{o.x+=(z.x-o.x)*k;o.y+=(z.y-o.y)*k};lerp(q.player,b.p);q.enemies.forEach(o=>{const z=b.e.find(e=>e.id===o.id);if(z&&z.alive===o.alive)lerp(o,z)});q.bullets.forEach(o=>{const z=b.b.find(e=>e.id===o.id);if(z)lerp(o,z)});const fx=[];if(replay.lastIdx!==replay.idx&&replay.idx>0){const prev=fs[replay.idx-1];for(const e of a.e)if(!e.alive&&prev.e.find(o=>o.id===e.id)?.alive)fx.push({type:'shatter',x:e.x,y:e.y})}replay.lastIdx=replay.idx;art.render(q,fx,dt);}
function frame(now){requestAnimationFrame(frame);if(!last)last=now;const dt=Math.min(.08,(now-last)/1000);last=now;if(replay){paint+=dt;if(paint>=1/40){drawReplay(paint);paint=0}return}if(!paused){acc+=dt;let world=0;while(acc>=1/60){if(s.mode==='play'){const t=s.time;E.step(s,input());world+=s.time-t;s.events.forEach(handle);s.events=[]}acc-=1/60}worldPaint+=world;if(celebrate>0){celebrate-=dt;worldPaint+=dt;dirty=true;if(celebrate<=0){result();return}}if(world>0)dirty=true;saveTick+=dt;if(saveTick>2){saveTick=0;save()}paint+=dt;if(dirty&&paint>=1/40){art.render(s,events,worldPaint);worldPaint=0;events=[];hud();paint=0;dirty=false}if(s.mode!==lastMode){lastMode=s.mode;if(s.mode==='win'||s.mode==='lost'){save();art.render(s,events,.02);events=[];s.mode==='win'?(celebrate=.65,toast('MOMENT OWNED')):lost()}}}else if(dirty){art.render(s,[],0);hud();dirty=false}}
window.StillDebug={snapshot:()=>E.copy(s),stats:()=>({...art.stats(),paused,modal,replay:!!replay,replayTime:replay?.t,voices:voices.length}),screen:(o,h=0)=>art.screen(o,h),world:(x,y)=>art.world(x,y),input};art.render(s,[],0);hud();start();requestAnimationFrame(frame);
})();
