(function(root){'use strict';const copy=o=>JSON.parse(JSON.stringify(o)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),TAU=Math.PI*2;
const titles=['White Room','Crossfire','The Showroom','Glasshouse','Last Train','Paper Walls','Red Exchange','The Gallery','Executive Exit'];
function profile(){return{best:Array(9).fill(0),unlocked:0,bestWave:0,accent:0,mute:false}}
function room(i,wave=0){const W=1000,H=740,walls=[{x:0,y:0,w:W,h:25},{x:0,y:H-25,w:W,h:25},{x:0,y:0,w:25,h:H},{x:W-25,y:0,w:25,h:H}],covers=[],glass=[],barrels=[],tokens=[],enemies=[],guns=[];let id=0;const cover=(x,y,w,h)=>covers.push({x,y,w,h}),enemy=(x,y,kind='pistol')=>enemies.push({id:++id,x,y,kind,angle:Math.PI,alive:true,hp:kind==='guard'?2:1,stun:0,cool:.5+(id%3)*.15,aim:0,lockX:0,lockY:0,walk:0}),gun=(x,y,kind='pistol')=>guns.push({id:++id,x,y,kind,ammo:kind==='scatter'?2:kind==='blade'?-1:4,lock:0}),barrel=(x,y)=>barrels.push({id:++id,x,y,broken:false}),token=(x,y)=>tokens.push({x,y,done:false}),pane=(x,y,w,h)=>glass.push({x,y,w,h,broken:false});
 let start={x:155,y:545};
 if(i===0){cover(415,310,120,75);enemy(380,235);enemy(710,530);gun(315,550);token(280,205);token(665,605)}
 if(i===1){cover(330,250,90,210);cover(590,380,90,210);enemy(720,175);enemy(820,560);enemy(440,145,'rush');gun(480,560,'scatter');token(210,170);token(820,650)}
 if(i===2){cover(245,220,160,80);cover(535,400,170,70);cover(760,260,85,100);enemy(550,160,'scatter');enemy(830,555);enemy(430,570,'rush');barrel(590,200);gun(450,350,'blade');token(250,360);token(780,160)}
 if(i===3){cover(460,225,55,90);cover(460,475,55,90);pane(460,315,20,160);enemy(770,210);enemy(780,550,'guard');enemy(650,360,'rush');gun(290,430,'scatter');barrel(740,370);token(275,170);token(815,635)}
 if(i===4){start={x:130,y:370};cover(225,165,95,115);cover(225,460,95,115);cover(450,165,95,115);cover(450,460,95,115);cover(680,165,95,115);cover(680,460,95,115);enemy(810,210,'guard');enemy(835,540,'pistol');enemy(620,370,'rush');enemy(420,370,'pistol');gun(365,370,'scatter');token(115,130);token(875,620)}
 if(i===5){cover(300,150,30,190);cover(300,435,30,170);pane(300,340,20,95);cover(660,150,30,190);cover(660,435,30,170);pane(660,340,20,95);enemy(500,200,'scatter');enemy(840,200,'guard');enemy(850,550);enemy(510,555,'rush');gun(200,350,'blade');barrel(820,370);token(420,370);token(810,650)}
 if(i===6){cover(320,250,100,100);cover(560,420,100,100);cover(690,185,100,80);enemy(500,150,'guard');enemy(835,340,'scatter');enemy(810,585);enemy(325,550,'rush');enemy(650,160);gun(220,390,'scatter');barrel(780,305);barrel(865,450);token(260,160);token(480,650)}
 if(i===7){cover(250,215,70,270);cover(470,215,70,270);cover(700,215,70,270);enemy(415,140,'guard');enemy(830,130);enemy(845,570,'guard');enemy(600,580,'rush');enemy(600,360,'scatter');gun(370,380,'blade');token(120,150);token(855,650)}
 if(i===8){cover(310,210,160,65);cover(310,455,160,65);cover(660,320,90,100);pane(520,310,20,150);enemy(760,155,'guard');enemy(850,540,'guard');enemy(540,160,'scatter');enemy(475,590,'rush');enemy(840,365);enemy(680,600);barrel(640,155);gun(220,350,'scatter');gun(565,580,'blade');token(180,135);token(860,655)}
 if(wave){enemies.length=0;const spots=[[770,155],[850,580],[560,130],[600,620],[830,370],[440,130],[440,625],[780,280]];spots.slice(0,Math.min(8,3+wave)).forEach(([x,y],j)=>enemy(x,y,wave>2&&j%3===0?'guard':j%3===1?'rush':j%3===2?'scatter':'pistol'));}
 return{W,H,title:wave?'ENDLESS / '+wave:titles[i],walls,covers,glass,barrels,tokens,enemies,guns,start,theme:i%3};}
function create(level=0,p=profile(),wave=0){const map=room(wave?(wave-1)%3+3:clamp(level|0,0,8),wave);return{version:1,level,wave,p:copy(p),map,player:{...map.start,vx:0,vy:0,angle:-.5,hp:3,inv:0,cool:0,weapon:{kind:'pistol',ammo:4}},enemies:copy(map.enemies),guns:copy(map.guns),bullets:[],mode:'play',time:0,rate:0,budget:0,events:[],damage:0,shots:0,kills:0,awarded:false,selected:null,nextId:100,record:[],recordClock:0}}
const solid=s=>s.map.walls.concat(s.map.covers,s.map.glass.filter(o=>!o.broken));
const inside=(x,y,r,pad=0)=>x>=r.x-pad&&x<=r.x+r.w+pad&&y>=r.y-pad&&y<=r.y+r.h+pad;
function clear(s,a,b){const n=Math.ceil(dist(a,b)/10),rs=solid(s);for(let i=1;i<n;i++)if(rs.some(r=>inside(a.x+(b.x-a.x)*i/n,a.y+(b.y-a.y)*i/n,r)))return false;return true}
function collide(s,o,r){for(const b of solid(s)){const x=clamp(o.x,b.x,b.x+b.w),y=clamp(o.y,b.y,b.y+b.h),dx=o.x-x,dy=o.y-y,d=Math.hypot(dx,dy);if(d<r&&d>.001){o.x+=dx/d*(r-d);o.y+=dy/d*(r-d)}else if(d<=.001){const q=[{d:Math.abs(o.x-b.x),x:b.x-r,y:o.y},{d:Math.abs(o.x-b.x-b.w),x:b.x+b.w+r,y:o.y},{d:Math.abs(o.y-b.y),x:o.x,y:b.y-r},{d:Math.abs(o.y-b.y-b.h),x:o.x,y:b.y+b.h+r}].sort((a,b)=>a.d-b.d)[0];o.x=q.x;o.y=q.y}}}
function emit(s,type,x,y,extra={}){s.events.push({type,x,y,...extra})}
function target(s){if(s.selected){const o=s.selected.kind==='barrel'?s.map.barrels.find(o=>o.id===s.selected.id&&!o.broken):s.enemies.find(o=>o.id===s.selected.id&&o.alive);if(o)return o}return s.enemies.filter(o=>o.alive&&clear(s,s.player,o)).sort((a,b)=>dist(s.player,a)-dist(s.player,b))[0]||null}
function bullet(s,x,y,a,owner,kind='pistol'){s.bullets.push({id:s.nextId++,x,y,px:x,py:y,vx:Math.cos(a)*(kind==='throw'?420:owner==='player'?780:215),vy:Math.sin(a)*(kind==='throw'?420:owner==='player'?780:215),owner,kind,life:4})}
function hit(s,e,n=1){if(!e.alive)return;e.hp-=n;if(e.hp<=0){e.alive=false;s.kills++;emit(s,'shatter',e.x,e.y,{id:e.id});s.guns.push({id:s.nextId++,x:e.x,y:e.y,kind:e.kind==='scatter'?'scatter':'pistol',ammo:e.kind==='scatter'?2:4,lock:.2})}else{e.stun=1.2;e.aim=0;emit(s,'crack',e.x,e.y)}}
function hurt(s){if(s.player.inv>0||s.mode!=='play')return;s.player.hp--;s.player.inv=.8;s.damage++;emit(s,'hurt',s.player.x,s.player.y);if(s.player.hp<=0){s.mode='lost';emit(s,'lost',s.player.x,s.player.y)}}
function blast(s,o){if(o.broken)return;o.broken=true;emit(s,'blast',o.x,o.y);for(const e of s.enemies)if(e.alive&&dist(e,o)<125&&clear(s,o,e))hit(s,e,3);if(dist(s.player,o)<95&&clear(s,o,s.player))hurt(s);for(const b of s.map.barrels)if(!b.broken&&dist(b,o)<150)blast(s,b);for(const g of s.map.glass)if(!g.broken&&dist(o,{x:g.x+g.w/2,y:g.y+g.h/2})<130){g.broken=true;emit(s,'glass',g.x,g.y)}}
function fire(s){const p=s.player;if(s.mode!=='play'||p.cool>0)return false;const o=target(s);if(o)p.angle=Math.atan2(o.y-p.y,o.x-p.x);const w=p.weapon;if(!w||w.ammo===0){const e=s.enemies.filter(o=>o.alive&&dist(p,o)<64&&clear(s,p,o)).sort((a,b)=>dist(p,a)-dist(p,b))[0];if(!e)return false;hit(s,e,1);p.cool=.4;s.budget=.35;emit(s,'punch',e.x,e.y);return true}
 if(w.kind==='blade'){const near=s.enemies.filter(e=>e.alive&&dist(p,e)<104&&clear(s,p,e));if(!near.length)return false;near.forEach(e=>hit(s,e,2));emit(s,'slice',p.x,p.y);p.cool=.45;s.budget=.35;return true}
 const spread=w.kind==='scatter'?[-.16,-.08,0,.08,.16]:[0];spread.forEach(a=>bullet(s,p.x+Math.cos(p.angle)*23,p.y+Math.sin(p.angle)*23,p.angle+a,'player',w.kind));w.ammo--;p.cool=w.kind==='scatter'?.65:.4;s.budget=Math.max(s.budget,.36);s.shots++;emit(s,'fire',p.x,p.y);return true}
function toss(s){const p=s.player;if(s.mode!=='play'||!p.weapon||p.cool>0)return false;const t=target(s);if(t)p.angle=Math.atan2(t.y-p.y,t.x-p.x);bullet(s,p.x+Math.cos(p.angle)*24,p.y+Math.sin(p.angle)*24,p.angle,'player','throw');const b=s.bullets.at(-1);b.weapon=copy(p.weapon);p.weapon=null;p.cool=.25;s.budget=Math.max(s.budget,.45);emit(s,'throw',p.x,p.y);return true}
function frame(s){return{t:s.time,p:copy(s.player),e:copy(s.enemies),b:copy(s.bullets),g:copy(s.guns),glass:s.map.glass.map(o=>o.broken),barrels:s.map.barrels.map(o=>o.broken),tokens:s.map.tokens.map(o=>o.done)}}
function applyFrame(s,f){const q=copy({...s,record:[]});q.time=f.t;q.player=copy(f.p);q.enemies=copy(f.e);q.bullets=copy(f.b);q.guns=copy(f.g);q.map.glass.forEach((o,i)=>o.broken=f.glass[i]);q.map.barrels.forEach((o,i)=>o.broken=f.barrels[i]);q.map.tokens.forEach((o,i)=>o.done=f.tokens[i]);q.mode='play';q.events=[];q.record=[];return q}
function finish(s){if(s.awarded||s.mode!=='play')return;s.awarded=true;s.mode='win';if(s.wave)s.p.bestWave=Math.max(s.p.bestWave,s.wave);else{s.p.best[s.level]=Math.max(s.p.best[s.level],1+(s.damage===0?1:0)+(s.map.tokens.every(o=>o.done)?1:0));s.p.unlocked=Math.max(s.p.unlocked,Math.min(8,s.level+1))}emit(s,'win',s.player.x,s.player.y);s.record.push(frame(s));if(s.record.length>180)s.record.shift()}
function step(s,input={},realDt=1/60){s.events=[];if(s.mode!=='play')return;realDt=clamp(realDt,0,1/30);let dx=input.dx||0,dy=input.dy||0;if(input.target){dx=input.target.x-s.player.x;dy=input.target.y-s.player.y;if(Math.hypot(dx,dy)<12)dx=dy=0}const n=Math.hypot(dx,dy),moving=n>0;if(n>0){dx/=n;dy/=n}s.rate=moving?1:input.fire?.65:s.budget>0?1:0;const dt=realDt*s.rate;if(!dt)return;s.budget=Math.max(0,s.budget-dt);s.time+=dt;const p=s.player;p.cool=Math.max(0,p.cool-dt);p.inv=Math.max(0,p.inv-dt);p.vx=dx*165;p.vy=dy*165;if(moving)p.angle=Math.atan2(dy,dx);p.x+=p.vx*dt;p.y+=p.vy*dt;collide(s,p,17);if(input.fire)fire(s);
 for(const g of s.guns)g.lock=Math.max(0,g.lock-dt);if(!p.weapon||p.weapon.ammo===0){const g=s.guns.find(g=>g.lock<=0&&g.ammo!==0&&dist(g,p)<37&&clear(s,p,g));if(g){p.weapon={kind:g.kind,ammo:g.ammo};s.guns=s.guns.filter(o=>o!==g);emit(s,'pickup',g.x,g.y)}}
 for(const t of s.map.tokens)if(!t.done&&dist(t,p)<29){t.done=true;emit(s,'token',t.x,t.y)}
 for(const e of s.enemies){if(!e.alive)continue;e.stun=Math.max(0,e.stun-dt);e.cool=Math.max(0,e.cool-dt);if(e.stun>0)continue;e.angle=Math.atan2(p.y-e.y,p.x-e.x);const sees=clear(s,e,p);if(e.kind==='rush'||!sees){let a=e.angle;if(!sees){const a1=e.angle+.9,a2=e.angle-.9,v1={x:e.x+Math.cos(a1)*55,y:e.y+Math.sin(a1)*55},v2={x:e.x+Math.cos(a2)*55,y:e.y+Math.sin(a2)*55};a=clear(s,e,v1)?a1:clear(s,e,v2)?a2:e.angle}const speed=e.kind==='rush'?91:53;e.x+=Math.cos(a)*speed*dt;e.y+=Math.sin(a)*speed*dt;collide(s,e,17);e.walk+=dt*speed;if(e.kind==='rush'&&dist(e,p)<35)hurt(s);e.aim=0}else if(e.cool<=0){if(e.aim===0){e.lockX=p.x;e.lockY=p.y}e.aim+=dt;if(e.aim>.6){const a=Math.atan2(e.lockY-e.y,e.lockX-e.x);for(const spread of e.kind==='scatter'?[-.13,0,.13]:[0])bullet(s,e.x+Math.cos(a)*24,e.y+Math.sin(a)*24,a,'enemy',e.kind);e.aim=0;e.cool=e.kind==='scatter'?1.65:1.1;emit(s,'enemyfire',e.x,e.y)}}}
 const done=new Set();for(const b of s.bullets){b.life-=dt;b.px=b.x;b.py=b.y;const n=Math.max(1,Math.ceil(Math.hypot(b.vx,b.vy)*dt/7));for(let i=0;i<n&&!done.has(b);i++){b.x+=b.vx*dt/n;b.y+=b.vy*dt/n;const gl=s.map.glass.find(g=>!g.broken&&inside(b.x,b.y,g,3));if(gl){gl.broken=true;emit(s,'glass',b.x,b.y);done.add(b);break}if(s.map.walls.concat(s.map.covers).some(o=>inside(b.x,b.y,o,2))){emit(s,'impact',b.x,b.y);done.add(b);break}const can=s.map.barrels.find(o=>!o.broken&&dist(o,b)<20);if(can){blast(s,can);done.add(b);break}if(b.owner==='enemy'&&dist(b,p)<20){hurt(s);done.add(b);break}const e=s.enemies.find(e=>e.alive&&dist(e,b)<19);if(e){hit(s,e,b.kind==='throw'?1:1);if(b.kind==='throw'&&e.alive){e.stun=1.5;e.kind='rush';e.aim=0;emit(s,'disarm',e.x,e.y)}done.add(b);break}}if(b.life<=0)done.add(b)}
 for(const b of done)if(b.kind==='throw'&&b.weapon){s.guns.push({id:s.nextId++,x:b.x,y:b.y,...b.weapon,lock:.3})}s.bullets=s.bullets.filter(b=>!done.has(b)).slice(-48);s.guns=s.guns.slice(-28);
 s.recordClock+=dt;if(s.recordClock>=.08){s.recordClock-=.08;s.record.push(frame(s));if(s.record.length>180)s.record.shift()}
 if(s.mode==='play'&&s.enemies.every(e=>!e.alive))finish(s);
}
function restore(raw){try{const s=typeof raw==='string'?JSON.parse(raw):copy(raw);if(s.version!==1||s.level<0||s.level>8||!Array.isArray(s.enemies)||!Array.isArray(s.record)||!Number.isFinite(s.player.x)||!Number.isFinite(s.player.y)||!Array.isArray(s.p.best)||s.p.best.length!==9||!['play','lost','win'].includes(s.mode))return null;s.events=[];return s}catch{return null}}
const api={copy,dist,clamp,profile,room,create,step,fire,toss,solid,clear,target,hit,hurt,frame,applyFrame,restore,titles};if(typeof module!=='undefined')module.exports=api;root.StillEngine=api;
})(typeof window!=='undefined'?window:globalThis);
