(function(root){'use strict';const copy=x=>JSON.parse(JSON.stringify(x)),clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const names=['Apricot Air','Fernfall','Honeywind','Blue Hour','Rose Canyon','Snowglow','Lantern Drift','Aurora Reach'];
class Flight{
 constructor(n=1,seed=n*1717){this.n=clamp(n|0,1,9999);this.seed=seed>>>0;this.theme=(this.n-1)%8;this.name=names[this.theme];this.x=0;this.y=5;this.z=12;this.tx=0;this.ty=5;this.vx=0;this.vy=0;this.time=0;this.state='fly';this.speed=23+Math.min(this.theme,5)*.6;this.hurt=0;this.bumps=0;this.score=0;this.combo=0;this.bestCombo=0;this.gems=0;this.gatesHit=0;this.next=0;this.grazed=[];this.draft=0;this.events=[];this.stars=0;this.gates=[];this.pillars=[];this.bank=null;this.trail=[];
  const phase=(this.seed%997)/997,amplitude=this.theme===0?1.5:2.3+this.theme*.28;for(let i=0;i<12;i++){const x=i<2?Math.sin(i*.7)*1.1:Math.sin(i*.81+phase)*amplitude,y=i<2?5:4.8+Math.sin(i*.65+phase*2)*(1+this.theme*.12);this.gates.push({x,y,z:-22-i*35,r:2.5,gem:[2,5,8].includes(i),wind:i%4===3,passed:false,hit:false,perfect:false});const offset=4.5;for(let side of [-1,1]){const h=9+(i*7+this.theme*3+(side+1)*2)%12;this.pillars.push({id:this.pillars.length,x:x+side*(offset+1.3),z:-25-i*35,w:3.1,d:10,h,side});}}
 this.makeBank();
 }
 aim(x,y){if(this.state!=='fly')return;this.tx=clamp(x,-8.2,8.2);this.ty=clamp(y,1.8,10.5);}
 emit(type,x=this.x,y=this.y,z=this.z,amount=0){this.events.push({type,x,y,z,amount});if(this.events.length>40)this.events.shift();}
 makeBank(){this.bank={x:this.x,y:this.y,z:this.z,next:this.next,score:this.score,gems:this.gems,gatesHit:this.gatesHit,combo:this.combo,bestCombo:this.bestCombo,grazed:[...this.grazed],gates:copy(this.gates)};}
 rescue(){if(this.state!=='fly'||!this.bank)return false;const bumps=this.bumps+1;for(const k of ['x','y','z','next','score','gems','gatesHit','combo','bestCombo','grazed','gates'])this[k]=copy(this.bank[k]);this.tx=this.x;this.ty=this.y;this.vx=this.vy=0;this.bumps=bumps;this.hurt=1.5;this.draft=0;this.trail=[];this.emit('bump');return true;}
 update(dt){if(this.state!=='fly'||!Number.isFinite(dt)||dt<=0)return;dt=Math.min(dt,.04);this.time+=dt;this.hurt=Math.max(0,this.hurt-dt);this.draft=Math.max(0,this.draft-dt);const oldz=this.z;this.vx+=(this.tx-this.x)*35*dt-this.vx*9*dt;this.vy+=(this.ty-this.y)*35*dt-this.vy*9*dt;this.x=clamp(this.x+this.vx*dt,-8.5,8.5);this.y=clamp(this.y+this.vy*dt,1.6,10.7);this.z-=this.speed*(this.draft>0?1.23:1)*dt;
 for(const p of this.pillars){const dx=Math.abs(this.x-p.x)-p.w/2,dz=Math.abs(this.z-p.z)-p.d/2;if(dx<1.1&&dz<.48&&this.y<p.h+.3&&!this.hurt){this.rescue();return;}if(dx>=1.1&&dx<2.6&&dz<1.2&&this.y<p.h+1&&!this.grazed.includes(p.id)){this.grazed.push(p.id);this.score+=75;this.emit('graze',this.x,this.y,this.z,75);}}
 while(this.next<12&&oldz>=this.gates[this.next].z&&this.z<=this.gates[this.next].z){const gate=this.gates[this.next],dist=Math.hypot(this.x-gate.x,this.y-gate.y);gate.passed=true;if(dist<=gate.r-.3){gate.hit=true;gate.perfect=dist<.72;this.gatesHit++;this.combo++;this.bestCombo=Math.max(this.bestCombo,this.combo);const pts=(gate.perfect?150:80)+Math.min(this.combo,12)*15;this.score+=pts;this.emit(gate.perfect?'perfect':'gate',gate.x,gate.y,gate.z,pts);if(gate.gem){this.gems++;this.emit('gem',gate.x,gate.y,gate.z);}if(gate.wind){this.draft=1.7;this.emit('wind',gate.x,gate.y,gate.z);}}else{this.combo=0;this.emit('miss',gate.x,gate.y,gate.z);}this.next++;if(this.next===4||this.next===8){this.makeBank();this.emit('checkpoint');}}
 if(this.next===12&&this.z<this.gates[11].z-14){this.state='won';this.stars=1+(this.gems===3?1:0)+(this.bumps<=2&&this.gatesHit>=10?1:0);this.emit('win');}
 this.trail.push({x:this.x,y:this.y,z:this.z});if(this.trail.length>30)this.trail.shift();
 }
 snapshot(){const s=copy(this);s.events=[];return s;}
 static restore(s){if(!s||!Number.isInteger(s.n)||s.n<1||s.n>9999||!Number.isInteger(s.seed)||s.seed<0||s.seed>4294967295||!['fly','won'].includes(s.state))return null;const g=new Flight(s.n,s.seed),finite=(v,min=-1e7,max=1e7)=>Number.isFinite(v)&&v>=min&&v<=max;const counters={score:10000000,bumps:1000000,combo:12,bestCombo:12,gems:3,gatesHit:12,next:12};for(const [k,max]of Object.entries(counters))if(!Number.isInteger(s[k])||s[k]<0||s[k]>max)return null;if(s.time<0||s.hurt<0||s.hurt>1.6||s.draft<0||s.draft>1.8||s.tx<-8.3||s.tx>8.3||s.ty<1.7||s.ty>10.6)return null;for(const k of ['x','y','z','tx','ty','vx','vy','time','hurt','bumps','score','combo','bestCombo','gems','gatesHit','next','draft'])if(!finite(s[k]))return null;if(s.x<-9||s.x>9||s.y<1||s.y>12||s.z>13||s.z<-500||s.next<0||s.next>12||!Number.isInteger(s.next)||!Array.isArray(s.gates)||s.gates.length!==12||!Array.isArray(s.grazed)||s.grazed.some(i=>!Number.isInteger(i)||i<0||i>=24)||!s.bank||!Array.isArray(s.bank.gates)||s.bank.gates.length!==12)return null;
 function gates(raw){return raw.map((t,i)=>({...g.gates[i],passed:!!t.passed,hit:!!t.hit,perfect:!!t.perfect}));}for(const t of [...s.gates,...s.bank.gates])if(!t||typeof t.passed!=='boolean'||typeof t.hit!=='boolean'||typeof t.perfect!=='boolean')return null;
 for(const k of ['x','y','z','next','score','gems','gatesHit','combo','bestCombo'])if(!finite(s.bank[k]))return null;for(const k of ['score','gems','gatesHit','combo','bestCombo','next'])if(!Number.isInteger(s.bank[k])||s.bank[k]<0||s.bank[k]>counters[k])return null;if(s.bank.x<-9||s.bank.x>9||s.bank.y<1||s.bank.y>12||s.bank.z>13||s.bank.z<-500)return null;if(s.state==='won'&&s.next!==12)return null;if(s.bank.next<0||s.bank.next>12||!Array.isArray(s.bank.grazed)||s.bank.grazed.some(i=>!Number.isInteger(i)||i<0||i>=24))return null;
 for(const k of ['x','y','z','tx','ty','vx','vy','time','state','hurt','bumps','score','combo','bestCombo','gems','gatesHit','next','draft','grazed'])g[k]=copy(s[k]);g.gates=gates(s.gates);g.bank={};for(const k of ['x','y','z','next','score','gems','gatesHit','combo','bestCombo','grazed'])g.bank[k]=copy(s.bank[k]);g.bank.gates=gates(s.bank.gates);g.trail=[];g.stars=g.state==='won'?1+(g.gems===3?1:0)+(g.bumps<=2&&g.gatesHit>=10?1:0):0;return g;
 }
}
root.Flight=Flight;root.FLIGHT_NAMES=names;if(typeof module!=='undefined')module.exports={Flight,names};
})(typeof window==='undefined'?globalThis:window);
