'use strict';
const A=LootArt,$=s=>document.querySelector(s),cv=$('#game'),c=cv.getContext('2d');const WW=512,WH=384;let Vw=512,Vh=384,cam={x:0,y:0},scene='shop',tier=0,depth=1,room=null,bag=[],p={x:256,y:293,hp:6,face:1,dir:{x:0,y:-1},inv:0,attack:0,dash:0,dashCD:0},time=0,last=0,accum=0,saveTimer=0,uiTimer=0,hitstop=0,shake=0,toastTimer,toastCooldown=0,ac=null,parts=[],floats=[],shots=[],customers=[],shopOpen=false,shopTimer=0,spawnTimer=0,sales=0,saleCoins=0,shopArrivals=0,target=null,stick={x:0,y:0},keys=new Set(),intro=true;
let book={coins:0,day:1,stash:Array(12).fill(0),prices:Array(12).fill(1),racks:[],sword:0,pack:0,heart:0,shop:0,found:Array(12).fill(false),salesTotal:0,bestDepth:0,quest:{id:0,count:0,done:false},sound:true};
try{book={...book,...JSON.parse(localStorage.getItem('lantern-loot-v1')||'{}')}}catch{}
function cap(){return 8+book.pack*4}function hpMax(){return 6+book.heart*2}function save(){try{localStorage.setItem('lantern-loot-v1',JSON.stringify(book));localStorage.setItem('lantern-loot-run',JSON.stringify(scene==='ruins'?{tier,depth,room,bag,p}:null))}catch{}}
function sound(kind='pick'){if(!book.sound)return;try{ac??=new(window.AudioContext||window.webkitAudioContext)();ac.resume();const seq={pick:[750,1050],hit:[150,90],sword:[340,120],hurt:[140,70],coin:[900,1200,1450],door:[350,530,700],dash:[250,480],pot:[250,110],win:[520,660,880]}[kind]||[600];seq.forEach((f,i)=>{const at=ac.currentTime+i*.06,o=ac.createOscillator(),g=ac.createGain();o.type=kind==='hit'||kind==='hurt'?'triangle':'sine';o.frequency.setValueAtTime(f,at);o.frequency.exponentialRampToValueAtTime(f*.55,at+.1);g.gain.setValueAtTime(.045,at);g.gain.exponentialRampToValueAtTime(.001,at+.12);o.connect(g).connect(ac.destination);o.start(at);o.stop(at+.13)})}catch{}}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2300)}
function burst(x,y,col,n=15){for(let i=0;i<n;i++)parts.push({x,y,vx:(Math.random()-.5)*100,vy:-15-Math.random()*90,life:.4+Math.random()*.6,col,size:1+Math.floor(Math.random()*3)});if(parts.length>300)parts.splice(0,parts.length-300)}function label(text,x,y,col='#f1d79d'){floats.push({text,x,y,col,life:1.5})}
function setScene(s){scene=s;target=null;stick={x:0,y:0};keys.clear();parts=[];floats=[];shots=[];p.attack=0;p.dash=0;p.inv=0;ui()}
function ui(){const ruin=scene==='ruins';$('#coins').textContent=book.coins;$('#place').textContent=ruin?['MOSSKEEP RUINS','THE VIOLET VAULT','EMBER SANCTUM'][tier]:'THE LANTERN SHOP';$('#day').textContent=ruin?'ROOM '+depth:'DAY '+book.day;$('#mission').textContent=book.quest.done?'Order complete ✓':'Sell 3 '+A.items[book.quest.id].name+' · +40';$('#scene-tag').textContent=ruin?(depth===4?'THE KEEPER’S CHAMBER':'A LIGHT IN THE RUINS'):(shopOpen?'OPEN FOR LITTLE WONDERS':'HOME, SWEET SHOP');$('#health').textContent=ruin?'♥'.repeat(Math.max(0,p.hp))+'♡'.repeat(Math.max(0,hpMax()-p.hp)):'';$('#bag').textContent=ruin?'BAG · '+bag.length+' / '+cap():'STOCK · '+book.stash.reduce((a,b)=>a+b,0);$('#roomstatus').textContent=ruin?(room.enemies.filter(e=>!e.dead).length+' foes · '+room.drops.filter(d=>d.id>=0).length+' finds'):shopOpen?'Selling · '+sales+' sold · +'+saleCoins:'Stock shelves. Set prices. Go exploring.';$('#shop-controls').style.display=ruin?'none':'flex';$('#ruin-controls').style.display=ruin?'flex':'none';$('#return').style.display=ruin?'block':'none';['#joystick','#swing','#dash'].forEach(s=>$(s).style.display=ruin?'block':'none');$('#stock').disabled=shopOpen;$('#gear').disabled=shopOpen;$('#explore').disabled=shopOpen;$('#open').disabled=shopOpen;$('#open').textContent=shopOpen?'Shop open…':'Open shop';$('#deeper').disabled=ruin&&room.enemies.some(e=>!e.dead);$('#interact').textContent=ruin&&Math.hypot(p.x-room.chest.x,p.y-room.chest.y)<58&&!room.chest.open?'Open chest':'Interact';$('#tip').textContent=ruin?(bag.length>=cap()?'Bag full. Return home, or leave something behind.':room.enemies.every(e=>e.dead)?'Room clear. Open the chest or go deeper.':'Move · swing · dodge the warning marks'):(shopOpen?'Watch the customers. Their reactions tell you the price.':book.stash.some(n=>n>0)?'Your discoveries belong on the shelves.':'An empty shelf begins with a little adventure.')}
function rng(seed){let n=seed;return()=>{n=(Math.imul(n,1664525)+1013904223)|0;return(n>>>0)/4294967296}}
function makeRoom(){const r=rng(book.day*981+tier*331+depth*67);const count=depth===4?2:Math.min(4,1+depth);const places=[[352,128],[257,199],[124,277],[419,275]];room={pots:[[92,116],[312,103],[425,184],[95,252],[276,299],[412,265]].map(([x,y],i)=>({x,y,broken:false,id:(i+tier*3+depth-1)%Math.min(10,4+tier*3+depth)})),chest:{x:420,y:100,open:false},drops:[],enemies:Array.from({length:count},(_,i)=>{const boss=depth===4&&i===0;const kind=boss?1:(i+depth+tier)%3;const max=boss?7+2*tier:kind===1?3+tier:2+tier;return{x:places[i][0],y:places[i][1],kind,hp:max,max,dead:false,timer:.9+r()*.8,state:'roam',dx:0,dy:0,flash:0,boss,stun:0}})};p.x=256;p.y=317;p.hp=Math.max(1,p.hp);p.inv=1;parts=[];shots=[];target=null;book.bestDepth=Math.max(book.bestDepth,depth+tier*4);sound('door');save();ui()}
function start(t=0){tier=t;depth=1;bag=[];p.hp=hpMax();scene='ruins';makeRoom();setScene('ruins');toast('Break pottery. Find goods. Return with your bag.');}
function walkable(x,y){if(x<37||x>475||y<68||y>341)return false;return ![{x:154,y:148,r:22},{x:358,y:230,r:23},{x:53,y:218,r:18},{x:455,y:218,r:18}].some(o=>Math.hypot(x-o.x,y-o.y)<o.r+7)}
function setTarget(x,y,gate=false){if(scene==='shop'){target={x,y,gate};return}if(!walkable(x,y))return;const cols=32,rows=24,key=(x,y)=>y*cols+x,sx=Math.floor(p.x/16),sy=Math.floor(p.y/16),gx=Math.floor(x/16),gy=Math.floor(y/16),startKey=key(sx,sy),goal=key(gx,gy),queue=[startKey],prev=new Map([[startKey,-1]]);for(let q=0;q<queue.length;q++){const k=queue[q];if(k===goal)break;const xx=k%cols,yy=Math.floor(k/cols);for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=xx+dx,ny=yy+dy,nk=key(nx,ny);if(nx>=0&&nx<cols&&ny>=0&&ny<rows&&!prev.has(nk)&&walkable(nx*16+8,ny*16+8)){prev.set(nk,k);queue.push(nk)}}}if(!prev.has(goal)){target=null;return}const route=[];let k=goal;while(k!==startKey&&k!==-1){route.unshift({x:k%cols*16+8,y:Math.floor(k/cols)*16+8});k=prev.get(k)}route.push({x,y});target={x,y,gate,route}}
function move(a,dx,dy){const nx=a.x+dx,ny=a.y+dy;if(scene==='shop'){a.x=Math.max(49,Math.min(463,nx));a.y=Math.max(91,Math.min(337,ny));return}if(walkable(nx,a.y))a.x=nx;if(walkable(a.x,ny))a.y=ny}
function drop(id,x,y){room.drops.push({id,x,y,t:time,uid:Math.random()});burst(x,y,id<0?'#c99493':A.items[id].col,6)}
function attack(){if(scene!=='ruins'||$('#modal').open||p.attack>0)return;sound('sword');p.attack=.28;let nearest=null,best=70;for(const e of [...room.enemies.filter(e=>!e.dead),...room.pots.filter(e=>!e.broken)]){const d=Math.hypot(e.x-p.x,e.y-p.y);if(d<best){best=d;nearest=e}}if(nearest){const d=Math.hypot(nearest.x-p.x,nearest.y-p.y)||1;p.dir={x:(nearest.x-p.x)/d,y:(nearest.y-p.y)/d};p.face=p.dir.x<0?-1:1}let hits=0;for(const e of room.enemies){if(e.dead||Math.hypot(e.x-p.x,e.y-p.y)>57)continue;e.hp-=1+book.sword;e.flash=.15;e.stun=.25;move(e,p.dir.x*11,p.dir.y*11);burst(e.x,e.y-10,'#e4c391',13);label('-'+(1+book.sword),e.x,e.y-30);hits++;if(e.hp<=0){e.dead=true;drop((tier*3+depth+e.kind)%Math.min(11,5+tier*3+depth),e.x,e.y);if(e.boss)drop(11,e.x+12,e.y);if(Math.random()<.2)drop(-1,e.x-10,e.y)}}for(const pot of room.pots){if(!pot.broken&&Math.hypot(pot.x-p.x,pot.y-p.y)<58){pot.broken=true;drop(pot.id,pot.x,pot.y);burst(pot.x,pot.y-8,'#bc986e',18);sound('pot');hits++}}if(hits){sound('hit');shake=3;hitstop=.045;navigator.vibrate?.(12);save()}ui()}
function dodge(){if(scene!=='ruins'||$('#modal').open||p.dashCD>0)return;p.dash=.21;p.dashCD=1.1;p.inv=Math.max(p.inv,.3);sound('dash');burst(p.x,p.y,'#84b9b2',8)}
function hurt(){if(p.inv>0)return;p.hp--;p.inv=1.15;shake=5;sound('hurt');burst(p.x,p.y-15,'#d88e7d',14);label('-1',p.x,p.y-39,'#ecaaa0');navigator.vibrate?.(25);if(p.hp<=0)returnHome(true);ui()}
function interact(){if(scene!=='ruins'||$('#modal').open)return;const ch=room.chest;if(!ch.open&&Math.hypot(ch.x-p.x,ch.y-p.y)<65){ch.open=true;const id=Math.min(10,tier*3+depth+1);drop(id,ch.x-9,ch.y+14);drop(Math.min(10,id+1),ch.x+12,ch.y+10);sound('win');label('FOUND',ch.x,ch.y-39);save();ui();return}const pickup=room.drops.find(d=>Math.hypot(d.x-p.x,d.y-p.y)<50);if(pickup&&pickup.id>=0&&bag.length>=cap()){openBag();return}if(Math.hypot(p.x-256,p.y-70)<58&&room.enemies.every(e=>e.dead)){deeper();return}toast('Move near a chest, a find, or the north gate.')}
function deeper(){if(scene!=='ruins'||room.enemies.some(e=>!e.dead))return;if(depth>=4){returnHome();return}if(Math.hypot(p.x-256,p.y-70)>65){setTarget(256,76,true);toast('Follow the light to the north gate.');return}depth++;makeRoom()}
function returnHome(failed=false){const brought=failed?bag.slice(0,Math.ceil(bag.length/2)):bag.slice();for(const id of brought){book.stash[id]++;book.found[id]=true}bag=[];save();setScene('shop');p.x=256;p.y=292;p.hp=hpMax();customers=[];shopOpen=false;save();if(brought.length){$('#content').innerHTML='<div class="summary"><div class="eyebrow">'+(failed?'THE LANTERN GUIDED YOU HOME':'A POCKET FULL OF STORIES')+'</div><h1>'+ (failed?'A narrow escape.':'Welcome back, shopkeeper.')+'</h1><div class="big-num">'+brought.length+' finds</div><div class="legend" style="justify-content:center">'+[...new Set(brought)].map(id=>A.items[id].name+' ×'+brought.filter(n=>n===id).length).join(' · ')+'</div><p>'+(failed?'You kept half your haul. Your equipment is safe.':'Your haul is now in stock. Choose what goes on the shelves.')+'</p><button class="primary" id="stock-now">Stock the shelves →</button></div>';$('#modal').showModal();$('#stock-now').onclick=()=>{stockMenu()}}else toast(failed?'Home safe. Try a dodge before the next attack.':'Home safe. Your shelves are waiting.');ui()}
function show(html){target=null;stick={x:0,y:0};keys.clear();$('#content').innerHTML=html;if(!$('#modal').open)$('#modal').showModal()}
function iconHTML(id){return '<img width="44" height="44" style="image-rendering:pixelated" alt="'+A.items[id].name+'" src="'+A.icons[id].toDataURL()+'">'}
function stockMenu(){const stocked=book.racks;const ids=book.stash.map((n,i)=>n>0?i:-1).filter(i=>i>=0);show('<div class="eyebrow">YOUR FINDS. YOUR LITTLE SHOP.</div><h1>Stock & prices</h1><p>Choose '+(3+book.shop)+' shelf items. Prices affect the customers’ reactions.</p><div class="cards">'+(ids.length?ids.map(id=>{const s=A.items[id];return'<div class="card">'+iconHTML(id)+'<b>'+s.name+'</b><small>In stock: '+book.stash[id]+'</small><button data-rack="'+id+'" class="'+(stocked.includes(id)?'stocked':'')+'">'+(stocked.includes(id)?'On shelf ✓':'Place on shelf')+'</button><div class="prices">'+[.8,1,1.4].map((m,i)=>'<button data-price="'+id+'" data-m="'+m+'" class="'+(book.prices[id]===m?'chosen':'')+'">'+Math.round(s.value*m)+'<br>'+['Deal','Fair','Bold'][i]+'</button>').join('')+'</div></div>'}).join(''):'<p>The stockroom is empty. Explore the ruins first.</p>')+'</div><p class="legend">Warm hearts = a good price. A raised brow = too expensive.</p>');document.querySelectorAll('[data-rack]').forEach(b=>b.onclick=()=>{const id=+b.dataset.rack;if(book.racks.includes(id))book.racks=book.racks.filter(n=>n!==id);else if(book.racks.length<3+book.shop)book.racks.push(id);else{toast('All shelves are stocked. Remove one to make space.');return}sound('pick');save();stockMenu()});document.querySelectorAll('[data-price]').forEach(b=>b.onclick=()=>{book.prices[+b.dataset.price]=+b.dataset.m;sound('pick');save();stockMenu()})}
function openBag(){show('<div class="eyebrow">YOUR EXPEDITION BAG</div><h1>Make a little room</h1><p>Return home to keep everything, or discard one find to collect something better.</p><div class="cards">'+bag.map((id,i)=>'<div class="card">'+iconHTML(id)+'<b>'+A.items[id].name+'</b><small>Value: '+A.items[id].value+'</small><button data-discard="'+i+'">Discard</button></div>').join('')+'</div>');document.querySelectorAll('[data-discard]').forEach(b=>b.onclick=()=>{bag.splice(+b.dataset.discard,1);save();ui();openBag()})}
const upgrades=[{key:'sword',name:'Lantern blade',base:90,max:3,desc:()=> 'Damage '+(1+book.sword)+' → '+(2+book.sword)},{key:'pack',name:'Roomier backpack',base:70,max:3,desc:()=> cap()+' → '+(cap()+4)+' finds'},{key:'heart',name:'Travel coat',base:90,max:2,desc:()=> hpMax()+' → '+(hpMax()+2)+' hearts'},{key:'shop',name:'Extra display',base:120,max:2,desc:()=> (3+book.shop)+' → '+(4+book.shop)+' shelf choices'}];
function gearMenu(){show('<div class="eyebrow">EARN HERE. GO FURTHER.</div><h1>Tools for tomorrow</h1><p>'+book.coins+' coins · Blade upgrades unlock new ruins.</p><div class="upgrades">'+upgrades.map(u=>'<div class="card"><b>'+u.name+'</b><small>'+u.desc()+'</small><button data-upgrade="'+u.key+'" '+(book[u.key]>=u.max||book.coins<u.base*(book[u.key]+1)?'disabled':'')+'>'+(book[u.key]>=u.max?'Fully upgraded':u.base*(book[u.key]+1)+' coins')+'</button></div>').join('')+'</div>');document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>{const u=upgrades.find(u=>u.key===b.dataset.upgrade),cost=u.base*(book[u.key]+1);if(book.coins<cost||book[u.key]>=u.max)return;book.coins-=cost;book[u.key]++;sound('win');save();gearMenu();ui()})}
function exploreMenu(){show('<div class="eyebrow">ONE MORE LITTLE ADVENTURE</div><h1>Where will you wander?</h1><div class="choices">'+['Mosskeep ruins','The Violet Vault','Ember Sanctum'].map((s,i)=>'<button data-tier="'+i+'" '+(book.sword<i?'disabled':'')+'><b>'+s+'</b><small>'+['Moss, pottery and quiet little guardians.','Rarer goods. Charging stone sentries. Blade II required.','The keeper’s best treasures. Blade III required.'][i]+'</small></button>').join('')+'</div><p>Carry '+cap()+' finds · '+hpMax()+' hearts · Return home whenever you like.</p>');document.querySelectorAll('[data-tier]').forEach(b=>b.onclick=()=>{$('#modal').close();start(+b.dataset.tier)})}
const racks=[{x:137,y:151},{x:256,y:151},{x:375,y:151},{x:177,y:232},{x:334,y:232}];
function openShop(){book.racks=book.racks.filter(id=>book.stash[id]>0);if(!book.racks.length){toast('Place a find on a shelf first.');stockMenu();return}shopOpen=true;sales=0;saleCoins=0;shopArrivals=0;shopTimer=0;spawnTimer=0;customers=[];ui();sound('door')}
function closeShop(){shopOpen=false;book.day++;if(book.quest.done)book.quest={id:(book.quest.id+1)%10,count:0,done:false};const bonus=sales>=5?20:0;book.coins+=bonus;save();show('<div class="summary"><div class="eyebrow">THE LANTERN SHOP · DAY '+(book.day-1)+'</div><h1>'+(sales?'A lovely day of trade.':'Tomorrow is another day.')+'</h1><div class="big-num">+'+(saleCoins+bonus)+' coins</div><p>'+sales+' finds sold'+(bonus?' · Busy shop bonus +20':'')+'.<br>Buy better tools, then bring back something new.</p><button class="primary" id="upgrade-now">Plan tomorrow →</button><button id="explore-again">Explore again</button></div>');$('#upgrade-now').onclick=gearMenu;$('#explore-again').onclick=()=>{$('#modal').close();exploreMenu()};ui()}
function shopTick(dt){if(!shopOpen)return;shopTimer+=dt;spawnTimer-=dt;if(spawnTimer<=0&&shopArrivals<8&&book.racks.some(id=>book.stash[id]>0)){const options=book.racks.filter(id=>book.stash[id]>0),id=options[shopArrivals%options.length],rack=book.racks.indexOf(id);customers.push({x:256,y:347,id,rack,person:1+shopArrivals%7,state:'walk',timer:0,reaction:'',budget:1.05+(shopArrivals%3)*.07});shopArrivals++;spawnTimer=2.4}for(const n of customers){const a=n.state==='leave'?{x:256,y:350}:racks[n.rack],dx=a.x-n.x,dy=a.y+25-n.y,d=Math.hypot(dx,dy);if(n.state==='walk'||n.state==='leave'){if(d>3){n.x+=dx/d*69*dt;n.y+=dy/d*69*dt}else if(n.state==='walk'){n.state='think';n.timer=.8}else n.state='gone'}if(n.state==='think'){n.timer-=dt;if(n.timer<=0){if(book.stash[n.id]>0&&book.prices[n.id]<=n.budget){const value=Math.round(A.items[n.id].value*book.prices[n.id]);book.stash[n.id]--;book.coins+=value;sales++;saleCoins+=value;book.salesTotal++;n.reaction=book.prices[n.id]<1?'♥♥':'♥';label('+'+value,n.x,n.y-35,'#efd183');sound('coin');burst(n.x,n.y-20,'#dec77a',10);if(!book.quest.done&&n.id===book.quest.id){book.quest.count++;if(book.quest.count>=3){book.quest.done=true;book.coins+=40;label('ORDER +40',256,230);toast('Special order complete · +40 coins');sound('win')}}save();ui()}else n.reaction=book.stash[n.id]>0?'?!':'…';n.state='react';n.timer=1.2}}else if(n.state==='react'){n.timer-=dt;if(n.timer<=0)n.state='leave'}}customers=customers.filter(n=>n.state!=='gone');if((shopArrivals>=8||!book.racks.some(id=>book.stash[id]>0))&&!customers.length||shopTimer>55){closeShop()}}
function tick(dt){p.inv=Math.max(0,p.inv-dt);p.attack=Math.max(0,p.attack-dt);p.dash=Math.max(0,p.dash-dt);p.dashCD=Math.max(0,p.dashCD-dt);toastCooldown-=dt;let x=stick.x,y=stick.y;if(keys.has('ArrowLeft')||keys.has('a'))x=-1;if(keys.has('ArrowRight')||keys.has('d'))x=1;if(keys.has('ArrowUp')||keys.has('w'))y=-1;if(keys.has('ArrowDown')||keys.has('s'))y=1;if(target){const a=target.route?.[0]||target,dx=a.x-p.x,dy=a.y-p.y,d=Math.hypot(dx,dy);if(d<5){if(target.route?.length>1)target.route.shift();else{const gate=target.gate;target=null;if(gate)deeper()}}else{x=dx/d;y=dy/d}}const len=Math.hypot(x,y);if(len>.08){x/=Math.max(1,len);y/=Math.max(1,len);p.dir={x,y};p.face=x<-.1?-1:x>.1?1:p.face;move(p,x*(p.dash>0?340:100)*dt,y*(p.dash>0?340:100)*dt)}else if(p.dash>0)move(p,p.dir.x*340*dt,p.dir.y*340*dt);p.moving=len>.08||p.dash>0;if(scene==='shop'){shopTick(dt);return}
for(const e of room.enemies){if(e.dead)continue;e.flash=Math.max(0,e.flash-dt);e.stun=Math.max(0,e.stun-dt);if(e.stun>0)continue;const dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy)||1;e.timer-=dt;if(e.state==='roam'){if(d>25){move(e,dx/d*(e.kind===1?24:34)*dt,dy/d*(e.kind===1?24:34)*dt)}if(e.timer<=0){e.state='warn';e.timer=e.kind===2?.65:.7;e.dx=dx/d;e.dy=dy/d}}else if(e.state==='warn'&&e.timer<=0){if(e.kind===2){shots.push({x:e.x,y:e.y-7,vx:e.dx*95,vy:e.dy*95,life:3});e.state='roam';e.timer=2}else{e.state='rush';e.timer=.4}}else if(e.state==='rush'){move(e,e.dx*(e.kind===1?200:155)*dt,e.dy*(e.kind===1?200:155)*dt);if(e.timer<=0){e.state='roam';e.timer=1.4}}if(Math.hypot(p.x-e.x,p.y-e.y)<20)hurt();if(scene!=='ruins')return}
for(const s of shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(!walkable(s.x,s.y))s.life=0;if(Math.hypot(s.x-p.x,s.y-p.y)<13){s.life=0;hurt()}if(scene!=='ruins')return}shots=shots.filter(s=>s.life>0);
let picked=false;room.drops=room.drops.filter(d=>{const dist=Math.hypot(p.x-d.x,p.y-d.y);if(dist<25){if(d.id<0){p.hp=Math.min(hpMax(),p.hp+1);sound('pick');label('+♥',p.x,p.y-32);return false}if(bag.length<cap()){bag.push(d.id);book.found[d.id]=true;sound('pick');burst(d.x,d.y,A.items[d.id].col,6);label(A.items[d.id].name,d.x,d.y-20);picked=true;return false}else if(toastCooldown<0){toast('Bag full. Return home or tap BAG to discard.');toastCooldown=3}}return true});if(picked)save();if(target&&target.y<90&&Math.hypot(p.x-256,p.y-76)<10&&room.enemies.every(e=>e.dead)){target=null;deeper()}
saveTimer+=dt;if(saveTimer>1){saveTimer=0;save()}}
$('#stock').onclick=stockMenu;$('#gear').onclick=gearMenu;$('#explore').onclick=exploreMenu;$('#open').onclick=openShop;$('#return').onclick=()=>returnHome();$('#interact').onclick=interact;$('#deeper').onclick=deeper;$('#bag').onclick=()=>{if(scene==='ruins'&&bag.length)openBag()};$('#swing').onclick=attack;$('#dash').onclick=dodge;$('#sound').onclick=()=>{book.sound=!book.sound;$('#sound').style.opacity=book.sound?1:.4;save()};$('#help').onclick=()=>show('<div class="eyebrow">A SHOPKEEPER’S LITTLE GUIDE</div><h1>Find. Sell. Go further.</h1><p><b>Ruins:</b> Move with the thumb stick or WASD. Swing near monsters and pottery. Dodge red warning lines. Open nearby chests. Bring goods home with Return.</p><p><b>Shop:</b> Place goods on shelves, set a price and open the shop. Hearts mean a sale; raised brows mean a price is too high. Spend earnings on upgrades.</p><div class="legend">WASD / arrows · Space: swing · Shift: dodge · E: interact · R: return</div>');$('#close').onclick=()=>{$('#modal').close();keys.clear()};$('#modal').addEventListener('cancel',()=>{keys.clear();stick={x:0,y:0}});
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)||e.key===' ')e.preventDefault();if($('#modal').open)return;keys.add(e.key);if(e.repeat)return;if(e.key===' ')attack();if(e.key==='Shift')dodge();if(e.key==='e')interact();if(e.key==='r'&&scene==='ruins')returnHome()});window.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',()=>{keys.clear();stick={x:0,y:0};target=null});
let joyId=null;function joy(e){const r=$('#joystick').getBoundingClientRect(),dx=(e.clientX-r.x-r.width/2)/(r.width*.35),dy=(e.clientY-r.y-r.height/2)/(r.height*.35),d=Math.max(1,Math.hypot(dx,dy));stick={x:dx/d,y:dy/d};target=null;$('#joystick span').style.transform='translate('+stick.x*18+'px,'+stick.y*18+'px)'}$('#joystick').onpointerdown=e=>{joyId=e.pointerId;$('#joystick').setPointerCapture(e.pointerId);joy(e);sound('dash')};$('#joystick').onpointermove=e=>{if(e.pointerId===joyId)joy(e)};function joyEnd(){joyId=null;stick={x:0,y:0};$('#joystick span').style.transform='none'}$('#joystick').onpointerup=joyEnd;$('#joystick').onpointercancel=joyEnd;
cv.onpointerdown=e=>{if($('#modal').open)return;const r=cv.getBoundingClientRect();setTarget((e.clientX-r.left)*Vw/r.width+cam.x,(e.clientY-r.top)*Vh/r.height+cam.y)};
// Mobile action buttons fire explicitly after captured thumb-stick drags.
let tb=null,lb='',lt=0,allow=false;const bkey=b=>b?.id||b?.getAttribute('aria-label')||(b&&Object.keys(b.dataset).length?JSON.stringify(b.dataset):b?.textContent);document.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'){const b=e.target.closest('button');if(b&&!b.disabled){tb=b;e.preventDefault()}}});document.addEventListener('pointerup',e=>{if(e.pointerType==='touch'&&tb){const b=tb;tb=null;if(e.target.closest('button')===b&&!b.disabled){lb=bkey(b);lt=performance.now();allow=true;b.click();allow=false;e.preventDefault()}}});document.addEventListener('click',e=>{if(!allow&&bkey(e.target.closest('button'))===lb&&performance.now()-lt<450){e.preventDefault();e.stopImmediatePropagation()}},true);document.addEventListener('pointercancel',()=>tb=null);
function lights(x,y,col,radius){const g=c.createRadialGradient(x,y,2,x,y,radius);g.addColorStop(0,col+'36');g.addColorStop(1,col+'00');c.fillStyle=g;c.fillRect(x-radius,y-radius,radius*2,radius*2)}
function render(){cam.x=Vw>WW?-(Vw-WW)/2:Math.max(0,Math.min(WW-Vw,p.x-Vw/2));cam.y=Vh>WH?-(Vh-WH)/2:Math.max(0,Math.min(WH-Vh,p.y-Vh*.58));c.fillStyle='#14202b';c.fillRect(0,0,Vw,Vh);c.save();c.translate(-Math.round(cam.x)+(Math.random()-.5)*shake,-Math.round(cam.y)+(Math.random()-.5)*shake);c.drawImage(scene==='shop'?A.shop:A.ruins[tier],0,0);
if(scene==='shop'){racks.slice(0,3+book.shop).forEach((a,i)=>{const id=book.racks[i],stock=id!==undefined&&book.stash[id]>0?Array(Math.min(3,book.stash[id])).fill(id):[];A.shelf(c,a.x,a.y,i,stock);if(stock.length)A.text(c,Math.round(A.items[id].value*book.prices[id])+'c',a.x,a.y+13,6,'#6a5739','center')});A.person(c,103,259,7,time);A.torch(c,396,298,time);lights(397,284,'#ffb868',85);lights(131,65,'#ffce77',120);lights(381,65,'#ffce77',120);const actors=[...customers.map(n=>({...n,npc:true})),{...p,npc:false}].sort((a,b)=>a.y-b.y);for(const a of actors){A.person(c,a.x,a.y,a.npc?a.person:0,time,a.npc?a.state==='walk'||a.state==='leave':p.moving,a.npc?1:p.face);if(a.reaction){A.r(c,a.x-13,a.y-53,27,14,a.reaction.includes('♥')?'#ede2bb':'#ddc5aa');A.text(c,a.reaction,a.x,a.y-43,8,a.reaction.includes('♥')?'#a67064':'#805d5a','center')}}A.text(c,shopOpen?'OPEN':'CLOSED',255,346,7,'#e7d28e','center');}
else{room.pots.forEach(a=>A.pot(c,a.x,a.y,a.broken));A.chest(c,room.chest.x,room.chest.y,room.chest.open);for(const x of [75,441]){A.torch(c,x,47,time,tier===1);lights(x,28,tier===1?'#8bd1c4':'#f0b36e',95)}if(room.enemies.every(e=>e.dead)){lights(256,48,'#b8d294',70);A.text(c,depth===4?'RETURN HOME':'NEXT ROOM',256,33,7,'#bdd998','center')}else{A.text(c,'CLEAR THE ROOM',256,32,7,'#9c9f91','center')}for(const e of room.enemies){if(e.dead)continue;if(e.state==='warn'){c.strokeStyle='#da8b76';c.lineWidth=2;c.setLineDash([5,4]);c.beginPath();c.moveTo(e.x,e.y);c.lineTo(e.x+e.dx*85,e.y+e.dy*85);c.stroke();c.setLineDash([]);A.text(c,'!',e.x,e.y-39,12,'#efb294','center')}}for(const d of room.drops){const y=d.y+Math.sin(time*4+d.x)*2;if(d.id<0){A.text(c,'♥',d.x,y,13,'#dc9d8d','center')}else{A.ell(c,d.x,d.y+5,10,3,'#18233890');A.icon(c,d.id,d.x,y-7,22);if(Math.sin(time*3+d.x)>.8){A.r(c,d.x+9,y-17,1,5,'#f0d594');A.r(c,d.x+7,y-15,5,1,'#f0d594')}}}
const actors=[...room.enemies.filter(e=>!e.dead).map(e=>({...e,enemy:true})),{...p,enemy:false}].sort((a,b)=>a.y-b.y);for(const a of actors){if(a.enemy){if(a.boss){c.save();c.translate(a.x,a.y);c.scale(1.35,1.35);A.enemy(c,{...a,x:0,y:0},time);c.restore()}else A.enemy(c,a,time);if(a.boss)A.text(c,'KEEPER',a.x,a.y-45,7,'#d5b787','center')}else if(p.inv<=0||Math.floor(time*18)%2){A.person(c,p.x,p.y,0,time,p.moving,p.face)}}for(const s of shots){A.ell(c,s.x,s.y,4,4,'#ccb4d9');A.r(c,s.x-1,s.y-1,2,2,'#f5dba6')}if(p.attack>0){const a=Math.atan2(p.dir.y,p.dir.x),sweep=(1-p.attack/.28);c.save();c.translate(p.x,p.y-12);c.strokeStyle='#f0e4bf';c.lineWidth=4;c.beginPath();c.arc(0,0,31,a-1.1+sweep*.4,a+.6+sweep*.8);c.stroke();c.strokeStyle='#b8d3b4';c.lineWidth=2;c.beginPath();c.arc(0,0,35,a-.8,a+.6);c.stroke();c.restore()}}
for(const q of parts){c.globalAlpha=Math.min(1,q.life*2);A.r(c,q.x,q.y,q.size,q.size,q.col)}c.globalAlpha=1;for(const f of floats){c.globalAlpha=Math.min(1,f.life);A.text(c,f.text,f.x,f.y,8,f.col,'center')}c.globalAlpha=1;c.restore();const v=c.createRadialGradient(Vw/2,Vh/2,Math.min(Vw,Vh)*.2,Vw/2,Vh/2,Math.max(Vw,Vh)*.7);v.addColorStop(0,'#06142900');v.addColorStop(1,scene==='shop'?'#11202755':'#061329a0');c.fillStyle=v;c.fillRect(0,0,Vw,Vh)}
function resize(){const r=cv.getBoundingClientRect();Vw=Math.max(320,Math.round(r.width/r.height*384));Vh=Math.round(Vw*r.height/r.width);cv.width=Vw;cv.height=Vh;c.imageSmoothingEnabled=false;render()}window.addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{keys.clear();joyEnd();target=null;save()});
try{const old=JSON.parse(localStorage.getItem('lantern-loot-run')||'null');if(old?.room&&old.p?.hp>0){tier=old.tier;depth=old.depth;room=old.room;bag=old.bag;p={...p,...old.p};scene='ruins'}}catch{}ui();resize();
function frame(now){let dt=Math.min(.04,(now-last)/1000||0);last=now;if(!document.hidden&&!$('#modal').open){time+=dt;shake=Math.max(0,shake-dt*25);if(hitstop>0)hitstop-=dt;else{accum+=dt;while(accum>=1/60){tick(1/60);accum-=1/60}}for(const q of parts){q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=170*dt}parts=parts.filter(q=>q.life>0);for(const f of floats){f.life-=dt;f.y-=15*dt}floats=floats.filter(f=>f.life>0);uiTimer+=dt;if(uiTimer>.15){uiTimer=0;ui()}render()}requestAnimationFrame(frame)}requestAnimationFrame(frame);
window.__lantern={get scene(){return scene},get book(){return book},get player(){return p},get room(){return room},get bag(){return bag},get customers(){return customers},get camera(){return{...cam,Vw,Vh}},get shopOpen(){return shopOpen},get depth(){return depth},advance(seconds){for(let i=0;i<Math.ceil(seconds*60);i++){if(document.hidden||$('#modal').open)break;time+=1/60;tick(1/60)}ui();render()}};
