'use strict';
(()=>{
const M=InfinityModel,$=s=>document.querySelector(s),cv=$('#world'),c=cv.getContext('2d'),modal=$('#modal'),panel=$('#panel');let saved={unlocked:0,current:0,records:{},echo:false};try{Object.assign(saved,JSON.parse(localStorage.getItem('little-infinity-v1')||'{}'))}catch{}let index=Math.max(0,Math.min(11,saved.current||0)),L,S,phase='title',history=[],anim=null,particles=[],camera={x:.5,y:.5,size:1},target={...camera},W=innerWidth,H=innerHeight,dpr=1,side=400,center={x:W/2,y:H/2},peek=false,toastTime=0,time=0,shake=0,hintDir=null,hints=0,worker=null,muted=false,audio,lastDir=1;
const optimum=[3,5,4,6,8,9,20,12,9,8,19,19],names=['OUTER WORLD','EMERALD ROOM','VIOLET ROOM','AMBER ROOM'];
function save(){try{localStorage.setItem('little-infinity-v1',JSON.stringify(saved))}catch{}}
function tone(f=330,d=.13,type='sine',vol=.035){if(muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(f*.65,audio.currentTime+d);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function chord(){[330,440,550,660].forEach((f,i)=>setTimeout(()=>tone(f,.5,'triangle',.025),i*100))}
function say(t,d=4){$('#toast').textContent=t;$('#toast').classList.add('show');toastTime=d}
function show(html){modal.hidden=false;panel.innerHTML=html;$('#close')?.addEventListener('click',()=>{modal.hidden=true;phase=M.won(S)?'complete':'play'})}
function mapLevel(){let l=M.clone(M.levels[index]);if(saved.echo){for(let r of l.rooms)r.map=r.map.map(s=>s.split('').reverse().join(''));for(let e of [...(l.extra||[]),...(l.goals||[])])e.x=M.board(l,e.room).n-1-e.x}return l}
function startLevel(){L=mapLevel();S=M.initial(L);phase='play';history=[];anim=null;hintDir=null;peek=false;hints=0;particles=[];if(worker){worker.terminate();worker=null}$('#hint').disabled=false;$('#number').textContent=String(index+1).padStart(2,'0');$('#name').textContent=L.name+(saved.echo?' · ECHO':'');saved.current=index;save();target=focus(S,M.entity(S,'p').room);camera={...target};if(M.entity(S,'p').room!=='root'){camera={x:.5,y:.5,size:1};anim={from:M.clone(S),to:S,t:0,duration:1.05,transfer:true,camFrom:{...camera}}}update();draw();}
function allRects(s){let result={root:{x:0,y:0,size:1}};for(let d=0;d<10;d++){let changed=false;for(let e of s.entities.filter(e=>e.kind==='world'))if(!result[e.child]&&result[e.room]){let r=result[e.room],n=M.board(L,e.room).n;result[e.child]={x:r.x+(e.x+.15)*r.size/n,y:r.y+(e.y+.15)*r.size/n,size:r.size/n*.7};changed=true}if(!changed)break}return result}
function focus(s,r){let q=allRects(s)[r]||{x:0,y:0,size:1};return {x:q.x+q.size/2,y:q.y+q.size/2,size:q.size}}
function worldPoint(s,e){let q=allRects(s)[e.room],n=M.board(L,e.room).n;return {x:q.x+(e.x+.5)*q.size/n,y:q.y+(e.y+.5)*q.size/n}}
function filled(s){return s.goals.filter(g=>{let e=M.at(s,g.room,g.x,g.y);return e&&e.kind!=='player'}).length}
function update(){let p=M.entity(S,'p'),chain=[],r=p.room;for(let i=0;i<8;i++){chain.unshift(r);let o=M.owner(S,r);if(!o)break;r=o.room}$('#trail').innerHTML=chain.map((r,i)=>'<i class="'+(i===chain.length-1?'current':'')+'" style="color:'+M.board(L,r).color[0]+'" title="'+r+'"></i>').join('<span>›</span>');$('#moves').textContent=S.moves+' MOVES';$('#slots').innerHTML=S.goals.map(g=>'<i class="'+(M.at(S,g.room,g.x,g.y)&&M.at(S,g.room,g.x,g.y).kind!=='player'?'filled':'')+'"></i>').join('');$('#undo').disabled=!history.length;$('#peek').style.borderColor=peek?'#68b2ff':'#ffffff20'}
function advance(d){if(phase!=='play'||anim||!modal.hidden)return;let next=M.move(L,S,d);lastDir=d;if(!next){shake=.17;tone(110,.09,'sine',.018);return}let prev=S,p0=M.entity(prev,'p'),p1=M.entity(next,'p'),transfer=p0.room!==p1.room,pushed=next.entities.some(e=>e.kind!=='player'&&JSON.stringify(e)!==JSON.stringify(M.entity(prev,e.id)));history.push(M.clone(S));if(history.length>500)history.shift();S=next;peek=false;hintDir=null;target=focus(S,p1.room);anim={from:prev,to:S,t:0,duration:transfer?.68:.14,transfer,pushed,camFrom:{...camera}};if(transfer){tone(p1.room==='root'?220:550,.45,'triangle',.025);say(p1.room==='root'?'BACK OUTSIDE':names[['root','A','B','D'].indexOf(p1.room)]||'A WORLD WITHIN',1.2)}else tone(pushed?240:430,.09,'sine',pushed?.025:.011);if(filled(S)>filled(prev)){let e=S.goals.find(g=>{let a=M.at(prev,g.room,g.x,g.y),b=M.at(S,g.room,g.x,g.y);return b&&b.kind!=='player'&&(!a||a.kind==='player')});burst(worldPoint(S,e),24,'#ffcd55');tone(780,.26,'triangle',.025)}update()}
function check(){if(!M.won(S))return;phase='complete';saved.unlocked=Math.max(saved.unlocked,Math.min(11,index+1));let key=(saved.echo?'echo-':'')+index,stars=S.moves<=optimum[index]+2?3:S.moves<=optimum[index]*1.6+2?2:1,old=saved.records[key];if(!old||S.moves<old.moves)saved.records[key]={moves:S.moves,stars,hints};save();chord();burst(worldPoint(S,M.entity(S,'p')),75,'#84d7ff');setTimeout(()=>{if(phase==='complete')finish(stars)},800)}
function finish(stars){show('<span class="eyebrow">'+(index===11?'WORLDS, REMEMBERED':'A LITTLE REVELATION')+'</span><h2>'+L.name+'</h2><div class="badge">'+'✦'.repeat(stars)+'</div><p>'+S.moves+' moves · '+hints+' hints</p><div class="row"><button id="next" class="primary">'+(index===11?'EXPLORE THE COLLECTION':'NEXT WORLD →')+'</button><button id="replay">AGAIN</button></div>'+(index===11?'<p class="small">Echo journey unlocked. The worlds are mirrored.</p>':''));$('#next').onclick=()=>{if(index<11){index++;startLevel();modal.hidden=true;say(L.tip)}else gallery()};$('#replay').onclick=()=>{startLevel();modal.hidden=true}}
function gallery(){phase='menu';show('<span class="eyebrow">TWELVE LITTLE REVELATIONS</span><h2>Worlds remembered</h2><div class="levels">'+M.levels.map((l,i)=>'<button data-level="'+i+'" aria-label="Open world '+(i+1)+'" '+(i>saved.unlocked?'disabled':'')+' class="'+(saved.records[(saved.echo?'echo-':'')+i]?'done':'')+'">'+(i+1)+'</button>').join('')+'</div><div class="row"><button id="close">CONTINUE</button><button id="sound">SOUND '+(muted?'OFF':'ON')+'</button>'+(saved.records[11]?'<button id="echo">ECHO '+(saved.echo?'ON':'OFF')+'</button>':'')+'</div>');document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{index=+b.dataset.level;startLevel();modal.hidden=true;say(L.tip)});$('#sound').onclick=()=>{muted=!muted;$('#sound').textContent='SOUND '+(muted?'OFF':'ON')};$('#echo')?.addEventListener('click',()=>{saved.echo=!saved.echo;save();gallery()})}
function title(){show('<span class="eyebrow">WORLDS WITHIN WORLDS</span><h2>LITTLE<br>INFINITY</h2><div class="title-art"><div><span><i></i><i></i></span></div></div><p>Push a box. Step into its world.<br>Bring every box home. Find your own square.</p><div class="row"><button id="start" class="primary">STEP INSIDE →</button></div><p class="small">Twelve crafted puzzles · Undo any move<br>Arrow keys, swipes or the touch pad</p>');$('#start').onclick=()=>{startLevel();modal.hidden=true;tone();say(L.tip)}}
function hint(){if(phase!=='play'||anim||worker)return;$('#hint').disabled=true;say('Looking through the little worlds…');let level=index,stateKey=JSON.stringify(S);let blob=new Blob(['const M='+M.workerSource+';onmessage=e=>postMessage(M.solve(e.data.L,e.data.S,400000));'],{type:'text/javascript'}),url=URL.createObjectURL(blob);worker=new Worker(url);URL.revokeObjectURL(url);let end=()=>{worker?.terminate();worker=null;$('#hint').disabled=false};worker.onmessage=e=>{end();if(index!==level||JSON.stringify(S)!==stateKey)return;let route=e.data;if(route?.length){hintDir=route[0];hints++;say('Try '+['UP','RIGHT','DOWN','LEFT'][hintDir]+'.',3)}else say('This arrangement needs an undo. No rush.',4)};worker.onerror=()=>{end();say('Try Undo, or restart this little world.',4)};worker.postMessage({L,S})}
function burst(p,count,color){for(let i=0;i<count;i++)particles.push({x:p.x,y:p.y,vx:(Math.random()-.5)*.2*target.size,vy:(Math.random()-.5)*.2*target.size,life:.6+Math.random()*.5,color,size:target.size*.003})}
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio,2);cv.width=W*dpr;cv.height=H*dpr;cv.style.width=W+'px';cv.style.height=H+'px';if(H<500){side=Math.min(H-82,W-320,390);center={x:W/2,y:H/2+12}}else if(W<600){side=Math.min(W-46,H-410);center={x:W/2,y:230+(H-410)/2}}else{side=Math.min(W-330,H-230,590);center={x:W/2,y:H/2+7}}side=Math.max(side,150);if(L)draw()}
function screen(p){return {x:center.x+(p.x-camera.x)*side/camera.size,y:center.y+(p.y-camera.y)*side/camera.size}}
function bevel(x,y,s,color,hi,dark,b=6){c.fillStyle=dark;c.fillRect(x,y,s,s);c.fillStyle=color;c.fillRect(x,y,s-b,s-b);c.fillStyle=hi;c.beginPath();c.moveTo(x,y);c.lineTo(x+s,y);c.lineTo(x+s-b,y+b);c.lineTo(x+b,y+b);c.lineTo(x+b,y+s-b);c.lineTo(x,y+s);c.closePath();c.fill()}
function drawRoom(rid,rect,depth,state,from,k){if(depth>5)return;let r=M.board(L,rid),p=screen({x:rect.x,y:rect.y}),size=rect.size*side/camera.size;if(size<4)return;if(p.x>W+20||p.y>H+20||p.x+size<-20||p.y+size<-20)return;let [wall,floor,dark,hi]=r.color,n=r.n,u=size/n,b=Math.min(u*.12,8);c.fillStyle=dark;c.fillRect(p.x-u*.018,p.y-u*.018,size+u*.036,size+u*.036);c.fillStyle=floor;c.fillRect(p.x,p.y,size,size);c.strokeStyle='#ffffff04';c.lineWidth=1;if(u>16)for(let i=1;i<n;i++){c.beginPath();c.moveTo(p.x+i*u,p.y);c.lineTo(p.x+i*u,p.y+size);c.moveTo(p.x,p.y+i*u);c.lineTo(p.x+size,p.y+i*u);c.stroke()}
for(let y=0;y<n;y++)for(let x=0;x<n;x++)if(r.map[y][x]==='#'){let xx=p.x+x*u,yy=p.y+y*u;c.fillStyle=wall;c.fillRect(xx,yy,u+.6,u+.6);if(y===0||r.map[y-1][x]!=='#'){c.fillStyle=hi;c.fillRect(xx,yy,u+.6,b)}if(x===0||r.map[y][x-1]!=='#'){c.fillStyle=hi;c.fillRect(xx,yy,b,u+.6)}if(y===n-1||r.map[y+1][x]!=='#'){c.fillStyle=dark;c.fillRect(xx,yy+u-b,u+.6,b)}if(x===n-1||r.map[y][x+1]!=='#'){c.fillStyle=dark;c.fillRect(xx+u-b,yy,b,u+.6)}}
for(let g of state.goals.filter(g=>g.room===rid)){let xx=p.x+(g.x+.19)*u,yy=p.y+(g.y+.19)*u,e=M.at(state,rid,g.x,g.y),lit=e&&e.kind!=='player';c.strokeStyle=lit?'#ffdf86':hi;c.lineWidth=Math.max(1,u*.033);c.strokeRect(xx,yy,u*.62,u*.62);if(lit){c.fillStyle='#ffd06530';c.fillRect(xx,yy,u*.62,u*.62)}}let g=state.playerGoal;if(g.room===rid){let x=p.x+(g.x+.19)*u,y=p.y+(g.y+.19)*u;c.strokeStyle=hi;c.lineWidth=Math.max(1,u*.03);c.strokeRect(x,y,u*.62,u*.62);c.fillStyle=hi;for(let dx of [.36,.64]){c.beginPath();c.arc(p.x+(g.x+dx)*u,p.y+(g.y+.46)*u,Math.max(1,u*.045),0,7);c.fill()}}
for(let e of state.entities.filter(e=>e.room===rid&&e.kind!=='player')){let old=from?.entities.find(a=>a.id===e.id),x=e.x,y=e.y;if(old&&old.room===rid){x=old.x+(e.x-old.x)*k;y=old.y+(e.y-old.y)*k}let xx=p.x+(x+.08)*u,yy=p.y+(y+.08)*u,s=u*.84;if(e.kind==='crate'){c.fillStyle='#0005';c.fillRect(xx+u*.04,yy+u*.045,s,s);bevel(xx,yy,s,'#ffca43','#fff19c','#b97727',u*.07);if(u>30){c.fillStyle='#fff2';c.fillRect(xx+u*.17,yy+u*.1,u*.035,u*.56)}}else{let child=M.board(L,e.child),a=child.color;bevel(xx,yy,s,a[0],a[3],a[2],u*.06);drawRoom(e.child,{x:rect.x+(x+.15)*rect.size/n,y:rect.y+(y+.15)*rect.size/n,size:rect.size/n*.7},depth+1,state,from,k)}}
}
function draw(){if(!L||!S)return;c.setTransform(dpr,0,0,dpr,0,0);c.globalAlpha=1;let grad=c.createRadialGradient(W*.5,H*.48,0,W*.5,H*.5,Math.max(W,H)*.65);grad.addColorStop(0,'#17233a');grad.addColorStop(1,'#060b14');c.fillStyle=grad;c.fillRect(0,0,W,H);c.fillStyle='#718aac12';for(let i=0;i<34;i++){let x=(i*173.61+Math.sin(time*.15+i)*10)%W,y=(i*97.23+time*(2+i%4))%H,s=3+i%6;c.fillRect(x,y,s,s)}c.save();if(shake>0)c.translate(Math.sin(shake*100)*3,Math.cos(shake*80)*2);let k=anim?Math.min(1,anim.t/anim.duration):1;k=k*k*(3-2*k);let root=screen({x:0,y:0}),rs=side/camera.size;c.shadowColor='#0009';c.shadowBlur=45;c.fillStyle='#071329';c.fillRect(root.x,root.y,rs,rs);c.shadowBlur=0;drawRoom('root',{x:0,y:0,size:1},0,S,anim?.from,k);let player=M.entity(S,'p'),pos=worldPoint(S,player),cell=allRects(S)[player.room].size/M.board(L,player.room).n;if(anim){let old=M.entity(anim.from,'p'),a=worldPoint(anim.from,old);pos={x:a.x+(pos.x-a.x)*k,y:a.y+(pos.y-a.y)*k};if(anim.transfer){let ac=allRects(anim.from)[old.room].size/M.board(L,old.room).n;cell=ac*Math.pow(cell/ac,k)}}let q=screen(pos),s=cell*side/camera.size*.76,squash=anim&&!anim.transfer?1+Math.sin(k*Math.PI)*.09:1;c.save();c.translate(q.x,q.y);c.scale(lastDir%2?squash:1/squash,lastDir%2?1/squash:squash);c.fillStyle='#0005';c.fillRect(-s/2+3,-s/2+4,s,s);bevel(-s/2,-s/2,s,'#c51a79','#f750ab','#70164e',s*.06);let blink=Math.sin(time*.72)> .998;c.fillStyle='#520c3c';for(let dx of [-.22,.22]){c.beginPath();c.ellipse(s*dx,-s*.055,s*.074,blink?s*.014:s*.074,0,0,7);c.fill()}c.restore();if(hintDir!==null){let d=M.D[hintDir],p=screen({x:pos.x+d[0]*cell*.65,y:pos.y+d[1]*cell*.65});c.fillStyle='#ffffff';c.font='bold '+Math.max(15,s*.5)+'px Arial';c.textAlign='center';c.textBaseline='middle';c.fillText(['↑','→','↓','←'][hintDir],p.x,p.y)}for(let a of particles){let p=screen(a);c.globalAlpha=Math.max(0,a.life);c.fillStyle=a.color;let s=Math.max(2,a.size*side/camera.size);c.fillRect(p.x,p.y,s,s)}c.globalAlpha=1;c.restore()}
function step(dt){time+=dt;shake=Math.max(0,shake-dt);toastTime-=dt;if(toastTime<=0)$('#toast').classList.remove('show');particles=particles.filter(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;return p.life>0});if(anim&&modal.hidden){anim.t+=dt;let t=Math.min(1,anim.t/anim.duration),k=t*t*(3-2*t);camera={x:anim.camFrom.x+(target.x-anim.camFrom.x)*k,y:anim.camFrom.y+(target.y-anim.camFrom.y)*k,size:anim.camFrom.size*Math.pow(target.size/anim.camFrom.size,k)};if(t>=1){anim=null;camera={...target};check()}}else{let t=1-Math.exp(-dt*9);camera.x+=(target.x-camera.x)*t;camera.y+=(target.y-camera.y)*t;camera.size*=Math.pow(target.size/camera.size,t)}draw()}
document.querySelectorAll('[data-dir]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();advance(+b.dataset.dir)}));$('#menu').onclick=gallery;$('#hint').onclick=hint;$('#peek').onclick=()=>{if(anim||phase!=='play')return;peek=!peek;target=peek?{x:.5,y:.5,size:1}:focus(S,M.entity(S,'p').room);update()};$('#undo').onclick=()=>{if(anim||!history.length)return;S=history.pop();phase='play';peek=false;hintDir=null;target=focus(S,M.entity(S,'p').room);camera={...target};update();tone(220,.18);draw()};$('#reset').onclick=()=>{if(!modal.hidden||anim)return;startLevel();say('A fresh little world.',2)};
let lastTouchButton=null,lastTouchTime=0;document.addEventListener('pointerup',e=>{if(e.pointerType!=='touch')return;let b=e.target.closest?.('button');if(!b||b.disabled||b.dataset.dir!==undefined)return;e.preventDefault();lastTouchButton=b;lastTouchTime=performance.now();b.click()},true);document.addEventListener('click',e=>{if(e.isTrusted&&e.target.closest?.('button')===lastTouchButton&&performance.now()-lastTouchTime<500){e.preventDefault();e.stopImmediatePropagation()}},true);
let touchStart;cv.addEventListener('pointerdown',e=>{touchStart={x:e.clientX,y:e.clientY};cv.setPointerCapture(e.pointerId)});cv.addEventListener('pointerup',e=>{if(!touchStart)return;let dx=e.clientX-touchStart.x,dy=e.clientY-touchStart.y;touchStart=null;if(Math.hypot(dx,dy)>18)advance(Math.abs(dx)>Math.abs(dy)?dx>0?1:3:dy>0?2:0);else{let p=screen(worldPoint(S,M.entity(S,'p'))),dx=e.clientX-p.x,dy=e.clientY-p.y;if(Math.hypot(dx,dy)>8)advance(Math.abs(dx)>Math.abs(dy)?dx>0?1:3:dy>0?2:0)}});cv.addEventListener('pointercancel',()=>touchStart=null);
addEventListener('keydown',e=>{if(!modal.hidden)return;let d={ArrowUp:0,KeyW:0,ArrowRight:1,KeyD:1,ArrowDown:2,KeyS:2,ArrowLeft:3,KeyA:3}[e.code];if(d!==undefined){e.preventDefault();advance(d)}if(e.code==='KeyZ')$('#undo').click();if(e.code==='KeyR')$('#reset').click();if(e.code==='Space'){e.preventDefault();$('#peek').click()}});addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{if(document.hidden)audio?.suspend();else audio?.resume()});L=mapLevel();S=M.initial(L);target=focus(S,M.entity(S,'p').room);camera={...target};resize();startLevel();phase='title';title();let last=performance.now();function frame(t){let dt=Math.min(.05,(t-last)/1000);last=t;if(!document.hidden)step(dt);requestAnimationFrame(frame)}requestAnimationFrame(frame);
window.LittleInfinity={state:()=>M.clone({index,S,phase,anim:!!anim,hints,unlocked:saved.unlocked,echo:saved.echo,camera}),step:t=>{for(let i=0;i<Math.ceil(t*60);i++)step(1/60)}};
})();
