(function(root,f){let E=f();if(typeof module!=='undefined')module.exports=E;else root.SilkEngine=E})(typeof window==='undefined'?globalThis:window,()=>{const names=['The first thread','Fern hollow','The windy bough','Mushroom steps','Rain on silk','Firefly grove','The old canopy','Orchid home'];const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);function random(seed){return()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296}}function level(n,echo=false){let r=random(913+n*77+(echo?233:0)),anchors=[{id:0,x:80,y:520}],patterns=[[380,280,330,240,370,460],[330,230,310,170,320,410],[400,220,350,200,370,420],[390,280,180,300,240,430],[320,220,360,210,330,470],[390,220,300,170,360,460],[320,190,330,160,290,420],[390,270,200,300,190,400]],p=patterns[n%8];for(let i=0;i<6;i++)anchors.push({id:i+1,x:210+i*150,y:p[i]+(echo?Math.round(r()*50-25):0)});anchors.push({id:7,x:1120,y:510});let bugs=[2,4,6].map((id,i)=>({id:i,x:anchors[id].x,y:anchors[id].y+30,anchor:id,found:false})),pollen=[1,3,5].map((id,i)=>({id:i,x:anchors[id].x+28,y:anchors[id].y+24,found:false}));let plats=[{x:0,y:552,w:150,h:200},{x:1050,y:542,w:170,h:200}];for(let a of anchors.slice(1,7))plats.push({x:a.x-28,y:a.y+45,w:56,h:17});let mushrooms=n%8===3?[{x:440,y:550},{x:750,y:530}]:[];return{n,name:n<8?names[n]:`Wild trail ${n-7}`,width:1220,height:720,anchors,bugs,pollen,plats,mushrooms,wind:n%8===2?.8:0,rain:n%8===4,night:n%8===5,exit:{x:1120,y:493},start:{x:80,y:530},echo}}
function create(n=0,echo=false){let l=level(n,echo);return{v:1,n,echo,l,p:{x:80,y:530,vx:0,vy:0,r:11,ground:true},rope:null,threads:[],checkpoint:0,visited:[0],rescued:[],collected:[],time:0,falls:0,shots:0,complete:false,events:[],jumpCD:0}}
function attach(s,id){if(s.complete)return false;let a=s.l.anchors.find(a=>a.id===id);if(!a||dist(s.p,a)>460)return false;if(s.rope?.id===id){s.rope=null;return 'release'}s.rope={id,x:a.x,y:a.y,len:Math.max(23,dist(s.p,a)),pull:true};s.shots++;s.events.push({type:'attach',x:a.x,y:a.y});return true}
function release(s){if(!s.rope)return false;s.rope=null;s.events.push({type:'release',x:s.p.x,y:s.p.y});return true}
function weave(s,a,b){if(a===b||s.threads.length>=12)return false;let x=s.l.anchors[a],y=s.l.anchors[b];if(!x||!y||dist(x,y)>370||s.threads.some(t=>t.a===a&&t.b===b||t.a===b&&t.b===a))return false;s.threads.push({a,b});s.events.push({type:'weave',x:(x.x+y.x)/2,y:(x.y+y.y)/2});return true}
function jump(s){if(s.jumpCD>0)return false;if(s.p.ground||s.rope){let dx=s.rope?(s.p.x-s.rope.x)/Math.max(1,dist(s.p,s.rope)):0;s.p.vy=-255;s.p.vx+=dx*65;s.p.ground=false;s.rope=null;s.jumpCD=.2;s.events.push({type:'jump',x:s.p.x,y:s.p.y});return true}return false}
function perch(s,count=true){let a=s.l.anchors[s.checkpoint];s.p.x=a.x;s.p.y=a.y+20;s.p.vx=s.p.vy=0;s.rope={id:a.id,x:a.x,y:a.y,len:23,pull:false};s.p.ground=false;if(count)s.falls++;s.events.push({type:'perch',x:a.x,y:a.y})}
function tick(s,dt,input=0){if(s.complete)return;dt=Math.min(dt,.025);s.time+=dt;s.jumpCD=Math.max(0,s.jumpCD-dt);const p=s.p,old={x:p.x,y:p.y},acc=1000,wind=s.l.wind*Math.sin(s.time*.9)*70;p.vx+=(input*acc+wind)*dt;p.vx*=Math.exp(-(p.ground?5:1.1)*dt);p.vx=Math.max(-230,Math.min(230,p.vx));p.vy=Math.min(430,p.vy+500*dt);p.x+=p.vx*dt;p.y+=p.vy*dt;p.ground=false;
if(s.rope){let q=s.rope;if(q.pull)q.len=Math.max(23,q.len-190*dt);let dx=p.x-q.x,dy=p.y-q.y,d=Math.hypot(dx,dy);if(d>q.len){let nx=dx/d,ny=dy/d;p.x=q.x+nx*q.len;p.y=q.y+ny*q.len;let radial=p.vx*nx+p.vy*ny;if(radial>0){p.vx-=radial*nx;p.vy-=radial*ny}}if(q.len<=24){s.checkpoint=q.id;if(!s.visited.includes(q.id)){s.visited.push(q.id);s.events.push({type:'perch',x:q.x,y:q.y})}}}
for(let b of s.l.plats){if(p.x+p.r>b.x&&p.x-p.r<b.x+b.w&&old.y+p.r<=b.y+4&&p.y+p.r>=b.y&&p.vy>=0){p.y=b.y-p.r;p.vy=0;p.ground=true}}
for(let t of s.threads){let a=s.l.anchors[t.a],b=s.l.anchors[t.b];if(a.x>b.x)[a,b]=[b,a];if(p.x>=a.x&&p.x<=b.x){let y=a.y+(p.x-a.x)/(b.x-a.x)*(b.y-a.y);let oldY=a.y+(old.x-a.x)/(b.x-a.x)*(b.y-a.y);if(old.y+p.r<=oldY+3&&p.y+p.r>=y&&p.vy>=0){p.y=y-p.r;p.vy=(b.y-a.y)/(b.x-a.x)*p.vx;p.ground=true}}}
for(let m of s.l.mushrooms)if(Math.abs(p.x-m.x)<36&&old.y+p.r<=m.y+4&&p.y+p.r>=m.y&&p.vy>0){p.y=m.y-p.r;p.vy=-410;s.events.push({type:'bounce',x:m.x,y:m.y})}
p.x=Math.max(15,Math.min(s.l.width-15,p.x));if(p.y>s.l.height+80){perch(s);return}for(let b of s.l.bugs)if(!b.found&&dist(p,b)<49){b.found=true;s.rescued.push(b.id);s.events.push({type:'rescue',x:b.x,y:b.y})}for(let b of s.l.pollen)if(!b.found&&dist(p,b)<39){b.found=true;s.collected.push(b.id);s.events.push({type:'pollen',x:b.x,y:b.y})}if(s.rescued.length===3&&dist(p,s.l.exit)<55){s.complete=true;s.rope=null;s.events.push({type:'complete',x:p.x,y:p.y})}}
return{names,dist,level,create,attach,release,weave,jump,perch,tick}});
