'use strict';
const $=id=>document.getElementById(id),canvas=$('world'),ctx=canvas.getContext('2d');let save={floor:0,wallet:0,best:{},up:{magnet:0,heart:0,speed:0},sound:true};try{let s=JSON.parse(localStorage.getItem('pepper-panic-v1'));if(s&&Number.isInteger(s.floor))save={...save,...s,up:{...save.up,...s.up}};}catch{}
const GROUND=300;let floor=save.floor,phase='intro',paused=false,P,world,cam=0,W=360,H=420,scale=1,offsetY=80,time=0,runTime=0,score=0,coins=0,combo=0,maxCombo=0,comboTime=0,stars=0,damage=0,alarm=0,oven=0,particles=[],ragdolls=[],words=[],trails=[],freeze=0,shake=0,bannerTime=0,musicClock=0,beat=0,AC,last=0,acc=0;const controls={left:false,right:false,dash:false,jump:false},pointers=new Map();let jumpQueued=0,lap=1;
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v)),rnd=(a,b)=>a+Math.random()*(b-a),overlap=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
function persist(){try{localStorage.setItem('pepper-panic-v1',JSON.stringify(save));}catch{}}
function sound(f=260,d=.1,type='square',v=.025){if(!save.sound)return;try{if(!AC)AC=new(window.AudioContext||window.webkitAudioContext)();AC.resume();let o=AC.createOscillator(),g=AC.createGain();o.type=type;o.frequency.setValueAtTime(f,AC.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(30,f*.6),AC.currentTime+d);g.gain.setValueAtTime(v,AC.currentTime);g.gain.exponentialRampToValueAtTime(.001,AC.currentTime+d);o.connect(g).connect(AC.destination);o.start();o.stop(AC.currentTime+d);}catch{}}
function music(dt){musicClock-=dt;if(musicClock>0)return;musicClock+=phase==='escape'?.14:.19;const notes=[0,7,12,7,3,10,15,10,5,12,17,12,3,10,15,7];let root=[130.8,146.8,164.8][floor%3];if(beat%2===0)sound(root*Math.pow(2,(beat%8<4?0:5)/12),.15,'triangle',.025);sound(root*2*Math.pow(2,notes[beat%16]/12),.12,'square',.011);if(beat%4===0)sound(75,.04,'triangle',.06);beat++;}
function makeWorld(n){let platforms=[],blocks=[],enemies=[],pickups=[],pads=[],pits=[],length=4100+Math.min(n,8)*130;const add=(id,x,y)=>pickups.push({id,x,y,w:18,h:20,taken:false});for(let k=0,x=300;x<length-300;x+=430,k++){let type=(k+n)%4;for(let j=0;j<5;j++)add(j===2?'pizza':'coin',x+j*38,254);if(type===0){for(let j=0;j<3;j++)blocks.push({x:x+150+j*32,y:236,w:30,h:64,dead:false});enemies.push({type:'tomato',x:x+285,y:268,w:24,h:32,home:x+285,dir:-1,alive:true});}
if(type===1){platforms.push({x:x+40,y:222,w:120,h:15},{x:x+180,y:150,w:130,h:15});add('star',x+230,110);for(let j=0;j<4;j++)add('coin',x+60+j*26,194);enemies.push({type:'helmet',x:x+285,y:268,w:24,h:32,home:x+285,dir:-1,alive:true});}
if(type===2){pads.push({x:x+60,y:284,w:45,h:16});platforms.push({x:x+160,y:158,w:150,h:15});add('star',x+240,117);blocks.push({x:x+310,y:230,w:32,h:70,dead:false});enemies.push({type:'cheese',x:x+365,y:268,w:24,h:32,home:x+365,dir:-1,alive:true});}
if(type===3){for(let j=0;j<3;j++)enemies.push({type:j===1?'helmet':'tomato',x:x+100+j*65,y:268,w:24,h:32,home:x+100+j*65,dir:-1,alive:true});pits.push({x:x+310,w:75});add('heart',x+280,242);platforms.push({x:x+120,y:205,w:150,h:15});add('star',x+200,165);}
if(k%2===0)add('heart',x+380,245);if(k%3===0)platforms.push({x:x+355,y:248,w:50,h:52,solid:true});}
return {length,platforms,blocks,enemies,pickups,pads,pits,totalStars:pickups.filter(p=>p.id==='star').length};}
function resetInput(){for(let k in controls)controls[k]=false;pointers.clear();document.querySelectorAll('[data-control]').forEach(b=>b.classList.remove('held'));jumpQueued=0;}
function start(n){floor=n;lap=1;world=makeWorld(n);P={x:70,y:258,w:22,h:42,vx:0,vy:0,face:1,ground:true,coyote:.12,jumps:1,hp:4+save.up.heart,maxhp:4+save.up.heart,inv:0,dashTime:0,safe:70};cam=0;time=0;runTime=0;score=coins=combo=maxCombo=comboTime=stars=damage=alarm=0;particles=[];ragdolls=[];words=[];trails=[];freeze=shake=0;phase='play';paused=false;resetInput();$('overlay').hidden=true;$('guide').textContent='HOLD SMASH · GO WILD';$('guide').style.opacity=1;banner('SHIFT '+(n+1));sound(320,.14);update();}
function banner(s){$('banner').textContent=s;$('banner').style.opacity=1;bannerTime=1.2;}
function burst(x,y,color,n=15,speed=140){for(let i=0;i<n&&particles.length<220;i++)particles.push({x,y,vx:rnd(-speed,speed),vy:rnd(-speed,-20),life:rnd(.25,.75),r:rnd(2,5),color});}
function award(value,x,y,hit=true){if(hit){combo++;comboTime=5+save.up.heart*.8;maxCombo=Math.max(maxCombo,combo);}score+=Math.round(value*(1+Math.min(combo,30)*.065));words.push({x,y,life:.7,text:hit?['CRUNCH!','WHAM!','HOT!','BAM!'][combo%4]:'+'+value,col:PAL[floor%3].accent});if(combo===5||combo===10||combo===20)banner(['','NICE!','ON FIRE!'][Math.min(2,Math.floor(combo/10))]||'NICE!');update();}
function smash(b){if(b.dead)return;b.dead=true;award(60,b.x,b.y);burst(b.x+15,b.y+30,PAL[floor%3].top,22,200);freeze=.045;shake=5;sound(130,.09,'sawtooth',.04);}
function kill(e,stomp=false){e.alive=false;award(120,e.x,e.y);ragdolls.push({type:e.type,x:e.x,y:e.y,vx:P.face*rnd(180,290),vy:-rnd(160,260),rot:0,spin:P.face*rnd(8,15),life:1});burst(e.x+12,e.y+15,'#f8d089',18,150);freeze=.045;shake=4;sound(190,.08,'square',.035);if(stomp){P.vy=-350;P.jumps=1;P.ground=false;}if(navigator.vibrate)try{navigator.vibrate(12);}catch{}}
function hurt(){if(P.inv>0)return;P.hp--;damage++;P.inv=1.3;P.slam=false;P.vx=-P.face*180;P.vy=-220;combo=0;comboTime=0;shake=7;freeze=.055;burst(P.x,P.y,'#f3849c',15);sound(100,.2,'sawtooth',.045);score=Math.max(0,score-50);P.hp=Math.max(1,P.hp);update();}
function ring(){phase='escape';alarm=Math.max(18,32-floor*.8);oven=world.length+W;banner("IT’S PIZZA TIME!");$('guide').textContent='← GET BACK TO THE EXIT!';$('guide').style.opacity=1;shake=8;sound(850,.4,'triangle',.07);for(let k=0;k<5;k++)world.enemies.push({type:k%2&&floor>1?'helmet':'cheese',x:260+k*(world.length-650)/5,y:268,w:24,h:32,home:260+k*(world.length-650)/5,dir:1,alive:true});update();}
function extraLap(){if(phase!=='escape'||lap!==1||P.x>450)return;lap=2;P.x=world.length-220;P.y=258;P.vx=-180;P.face=-1;P.inv=1;P.safe=P.x;alarm=Math.max(18,alarm);oven=P.x+W+150;for(let e of world.enemies)e.alive=true;for(let p of world.pickups)if(p.id==='coin'||p.id==='pizza')p.taken=false;banner('LAP TWO!');score+=500;sound(950,.25,'triangle',.05);update();}
$('lap').onclick=extraLap;
function rankFor(){if(score>=6500&&damage===0&&stars===world.totalStars&&maxCombo>=15)return 'P';return score>=6500?'S':score>=4500?'A':score>=2500?'B':score>=1000?'C':'D';}
function end(win){phase=win?'win':'lose';resetInput();let gain=win?coins+20+stars*8:Math.floor(coins/2);save.wallet+=gain;if(win){score+=Math.round(Math.max(0,alarm)*10);save.floor=Math.max(save.floor,floor+1);let prev=save.best[floor];if(!prev||score>prev.score)save.best[floor]={score,rank:rankFor(),stars};}persist();$('eyebrow').textContent=win?'DELIVERY COMPLETE!':'THE OVEN GOT THE LAST LAUGH';$('title').innerHTML=win?'THAT WAS<br><em>SPICY!</em>':'ONE MORE<br><em>BITE?</em>';$('rank').textContent=win?rankFor():'OOPS!';$('message').textContent=win?score+' points · '+maxCombo+' combo · '+stars+'/'+world.totalStars+' secrets · +'+gain+' tips':'Pocketed '+gain+' tips. Jump on helmets. Smash everything else.';$('keys').textContent=win?'PICK A PERK FOR THE NEXT SHIFT':'DOUBLE JUMP · HOLD SMASH TO BUILD SPEED';$('primary').textContent=win?'NEXT SHIFT':'TRY AGAIN';$('secondary').textContent=win?'REPLAY':'NEW RUN';$('secondary').hidden=false;$('choices').innerHTML=win?[['magnet','◎','MAGNET','Pull treats from farther away'],['heart','ϟ','COMBO SAVER','Longer time between hits'],['speed','ϟ','HOT FEET','Faster smash, bigger chaos']].map(([id,ico,title,desc])=>`<button data-up="${id}"><b>${ico}</b>${save.up[id]>=3?'COIN STASH':title}<span>${save.up[id]>=3?'+30 tips':desc}</span></button>`).join(''):'';$('choices').querySelectorAll('button').forEach(b=>b.onclick=()=>{const key=b.dataset.up;if(save.up[key]<3)save.up[key]++;else save.wallet+=30;persist();start(floor+1);});$('overlay').hidden=false;sound(win?750:95,.3,'triangle',.06);update();}
$('primary').onclick=()=>{if(phase==='intro')start(save.floor);else if(phase==='win'){save.up.magnet=Math.min(3,save.up.magnet+1);persist();start(floor+1);}else if(phase==='lose')start(floor);else resume();};$('secondary').onclick=()=>start(phase==='win'?floor:0);
function pause(){if(!['play','escape'].includes(phase))return;paused=true;resetInput();$('eyebrow').textContent='PEPPER PANIC';$('title').innerHTML='TAKE A<br><em>BREATHER.</em>';$('rank').textContent='';$('message').textContent='Your combo and escape timer are on hold.';$('choices').innerHTML='';$('keys').textContent='← → MOVE · SPACE JUMP · X SMASH';$('primary').textContent='KEEP GOING';$('secondary').hidden=true;$('overlay').hidden=false;}
function resume(){paused=false;resetInput();$('overlay').hidden=true;}
$('pause').onclick=pause;$('sound').onclick=()=>{save.sound=!save.sound;persist();sound(330,.1);update();};document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
function set(k,v){if(v&&controls[k]===false&&k==='dash'&&P&&!P.ground){P.slam=true;P.vy=700;sound(110,.15,'sawtooth',.03);}if(v&&controls[k]===false&&k==='jump')jumpQueued=.15;controls[k]=v;if(k==='jump'&&!v&&P&&P.vy<-230)P.vy=-230;document.querySelector(`[data-control="${k}"]`)?.classList.toggle('held',v);}
document.querySelectorAll('[data-control]').forEach(b=>{b.onpointerdown=e=>{if(paused||!['play','escape'].includes(phase))return;e.preventDefault();let k=b.dataset.control;pointers.set(e.pointerId,k);set(k,true);b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=e=>{const k=pointers.get(e.pointerId);pointers.delete(e.pointerId);if(k&&!Array.from(pointers.values()).includes(k))set(k,false);};});const KEY={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',' ':'jump',ArrowUp:'jump',w:'jump',x:'dash',Shift:'dash'};window.addEventListener('keydown',e=>{if(e.key==='Escape'){paused?resume():pause();return;}let k=KEY[e.key];if(k&&!paused&&['play','escape'].includes(phase)){e.preventDefault();set(k,true);}});window.addEventListener('keyup',e=>{let k=KEY[e.key];if(k)set(k,false);});window.addEventListener('blur',()=>{if(!paused)pause();});
function update(){ $('wallet').textContent='● '+save.wallet;$('sound').style.opacity=save.sound?1:.4;if(!P)return;$('hearts').textContent=rankFor()+' · ★ '+stars+'/'+world.totalStars;$('score').textContent=String(score).padStart(5,'0');$('mission').textContent=phase==='escape'?(lap===2?'LAP 2 · ':'← ')+Math.max(0,Math.ceil(alarm))+'s · EXIT!':'→ BREAK THE PILLAR';$('mission').style.color=phase==='escape'?'#ff8d94':'#f4d69a';$('lap').hidden=!(phase==='escape'&&lap===1&&P.x<450);$('floor').hidden=!$('lap').hidden;$('floor').textContent='FLOOR '+String(floor+1).padStart(2,'0');drawTV();$('combo').style.opacity=combo>=2?1:0;$('combo').firstElementChild.textContent=combo+'×';$('combo').querySelector('small').textContent=combo>=20?'ABSOLUTE CHAOS':combo>=10?'ON FIRE':combo>=5?'GETTING SPICY':'KEEP IT GOING';$('combo').querySelector('i').style.transform='scaleX('+clamp(comboTime/(5+save.up.heart*.8),0,1)+')';$('progress').firstElementChild.style.width=clamp((phase==='escape'?1-P.x/world.length:P.x/world.length)*100,0,100)+'%';}
function step(dt){time+=dt;bannerTime-=dt;if(bannerTime<0)$('banner').style.opacity=0;shake=Math.max(0,shake-dt*18);if(freeze>0){freeze-=dt;return;}runTime+=dt;music(dt);comboTime-=dt;if(comboTime<=0)combo=0;P.inv=Math.max(0,P.inv-dt);P.coyote=Math.max(0,P.coyote-dt);jumpQueued=Math.max(0,jumpQueued-dt);let dir=(controls.right?1:0)-(controls.left?1:0);if(dir)P.face=dir;let dash=controls.dash;P.dashTime=dash?Math.min(1.5,P.dashTime+dt):Math.max(0,P.dashTime-dt*4);let target=dash?(dir||P.face)*(330+Math.min(1,P.dashTime)*170+save.up.speed*35):dir*165;P.vx+=(target-P.vx)*Math.min(1,dt*(dash?11:16));if(jumpQueued>0&&(P.ground||P.coyote>0||P.jumps>0)){let grounded=P.ground||P.coyote>0;P.vy=grounded?-460:-420;if(!grounded)P.jumps--;P.ground=false;P.coyote=0;jumpQueued=0;sound(450,.08,'triangle',.025);burst(P.x+10,P.y+42,'#ebddb0',6,60);}
let prev={x:P.x,y:P.y};P.vy=Math.min(680,P.vy+1100*dt);P.x+=P.vx*dt;P.x=clamp(P.x,8,world.length-55);for(let b of world.platforms.filter(b=>b.solid)){if(overlap(P,b)){if(prev.x+P.w<=b.x+5)P.x=b.x-P.w;else if(prev.x>=b.x+b.w-5)P.x=b.x+b.w;P.vx=0;if(runTime>2&&Math.floor(time*2)%2===0){$('guide').textContent='JUMP OVER STONE LEDGES';$('guide').style.opacity=1;}}}for(let b of world.blocks){if(b.dead||!overlap(P,b))continue;if(dash&&Math.abs(P.vx)>230)smash(b);else{if(prev.x+P.w<=b.x+3)P.x=b.x-P.w;else if(prev.x>=b.x+b.w-3)P.x=b.x+b.w;P.vx=0;}}
P.y+=P.vy*dt;P.ground=false;const pit=world.pits.some(p=>P.x+P.w*.7>p.x&&P.x+P.w*.3<p.x+p.w);if(!pit&&P.y+P.h>=GROUND&&prev.y+P.h<=GROUND+8&&P.vy>=0){P.y=GROUND-P.h;P.vy=0;P.ground=true;if(P.slam){P.slam=false;shake=9;freeze=.06;burst(P.x,300,'#f1c278',30,220);for(let e of world.enemies)if(e.alive&&Math.abs(e.x-P.x)<95)kill(e);sound(85,.2,'sawtooth',.04);}P.coyote=.12;P.jumps=1;P.safe=P.x;}
for(let b of [...world.platforms,...world.blocks.filter(b=>!b.dead)])if(P.vy>=0&&prev.y+P.h<=b.y+4&&P.y+P.h>=b.y&&P.x+P.w>b.x&&P.x<b.x+b.w){P.y=b.y-P.h;P.vy=0;P.ground=true;P.slam=false;P.coyote=.12;P.jumps=1;}
for(let pad of world.pads)if(P.ground&&P.x+P.w>pad.x&&P.x<pad.x+pad.w){P.vy=-610;P.ground=false;P.jumps=1;burst(P.x,P.y+42,'#90deb8',16);sound(680,.16);words.push({x:P.x,y:P.y,life:.8,text:'BOING!',col:'#9ce9b4'});}
for(let e of world.enemies){if(!e.alive)continue;e.x+=e.dir*27*dt;if(Math.abs(e.x-e.home)>40)e.dir*=-1;if(overlap(P,e)){if(P.vy>0&&prev.y+P.h<=e.y+12)kill(e,true);else if(dash&&Math.abs(P.vx)>220&&e.type!=='helmet')kill(e);else hurt();}}
for(let p of world.pickups){if(p.taken)continue;let range=p.id==='heart'?23:25+save.up.magnet*18;let d=Math.hypot(P.x+11-p.x-9,P.y+24-p.y-10);if(d>range)continue;if(p.id==='heart'&&P.hp===P.maxhp)continue;p.taken=true;burst(p.x,p.y,p.id==='heart'?'#ef90a4':'#ffdb8c',8,75);if(p.id==='heart'){P.hp=Math.min(P.maxhp,P.hp+1);words.push({x:P.x,y:P.y,life:.8,text:'+♥',col:'#ffc1b9'});}else{coins+=p.id==='pizza'?3:1;if(p.id==='star'){stars++;award(250,p.x,p.y,true);banner('SECRET!');}else{award(p.id==='pizza'?45:12,p.x,p.y,false);comboTime=Math.max(comboTime,2);}}sound(p.id==='star'?900:610,.06,'triangle',.02);}
if(P.y>425){P.x=clamp(P.safe-40,8,world.length-80);P.y=220;P.vy=0;P.vx=0;hurt();}
if(phase==='play'&&P.x>world.length-165&&controls.dash&&Math.abs(P.vx)>230){burst(world.length-100,220,'#bcb79d',45,260);freeze=.08;ring();}if(phase==='escape'){alarm-=dt;if(alarm<=0){oven-=Math.min(360,260+floor*10)*dt;}else oven=P.x+W+150;if(P.x<135)end(true);else if(P.x+P.w>=oven&&oven<world.length)end(false);}
let targetCam=clamp(P.x-W*(P.face>0?.3:.65),0,world.length-W);cam+=(targetCam-cam)*Math.min(1,dt*10);if(dash&&Math.abs(P.vx)>250&&Math.floor(time*40)!==Math.floor((time-dt)*40)){trails.push({x:P.x,y:P.y,face:P.face,life:.17});if(trails.length>8)trails.shift();}for(let t of trails)t.life-=dt;trails=trails.filter(t=>t.life>0);for(let p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=450*dt;}particles=particles.filter(p=>p.life>0);for(let r of ragdolls){r.life-=dt;r.x+=r.vx*dt;r.y+=r.vy*dt;r.vy+=500*dt;r.rot+=r.spin*dt;}ragdolls=ragdolls.filter(r=>r.life>0);for(let t of words){t.life-=dt;t.y-=55*dt;}words=words.filter(t=>t.life>0);if(runTime>4&&Math.abs(P.vx)>40)$('guide').style.opacity=phase==='escape'&&alarm>Math.max(18,32-floor*.8)-3?1:0;update();}
function resize(){let r=canvas.getBoundingClientRect();W=clamp(r.width/r.height*300,360,960);H=Math.round(r.height/r.width*W);scale=r.width/W;canvas.width=Math.round(W);canvas.height=H;offsetY=H-335;ctx.imageSmoothingEnabled=false;}new ResizeObserver(resize).observe(canvas);
function sprite(name,x,y,width=48,height=60,face=1,f=0){let art=SPR[name][f%SPR[name].length];ctx.save();ctx.translate(Math.round(x),Math.round(y));if(face<0){ctx.translate(width,0);ctx.scale(-1,1);}ctx.drawImage(art,0,0,width,height);ctx.restore();}
let bgCache=[];
function sceneBackground(n){if(bgCache[n])return bgCache[n];const c=document.createElement('canvas');c.width=720;c.height=520;const g=c.getContext('2d'),t=PAL[n];g.fillStyle=t.sky;g.fillRect(0,0,720,520);g.strokeStyle=t.far;g.lineWidth=1;for(let y=0;y<520;y+=34)for(let x=-(y/34%2)*36;x<720;x+=72){g.beginPath();g.moveTo(x+2,y+1);g.lineTo(x+68,y);g.lineTo(x+70,y+31);g.lineTo(x+4,y+33);g.closePath();g.stroke();g.fillStyle=t.far;g.fillRect(x+14,y+6,16,1);}
g.strokeStyle=t.back;for(let i=0;i<21;i++){let x=(i*137)%700,y=40+(i*79)%420;g.beginPath();g.moveTo(x,y);g.lineTo(x+3,y+11);g.lineTo(x-1,y+16);g.lineTo(x+5,y+24);g.stroke();}
for(let i=0;i<2;i++){g.fillStyle=t.far;g.beginPath();g.ellipse(185+i*330,265-i%2*100,58,64,.2,0,7);g.fill();g.fillStyle=t.sky;g.beginPath();g.ellipse(168+i*330,250-i%2*100,12,16,0,0,7);g.ellipse(200+i*330,251-i%2*100,12,16,0,0,7);g.fill();g.fillRect(167+i*330,286-i%2*100,39,14);}
g.globalAlpha=.72;g.drawImage(SCENE.poster,43,312,80,91);g.drawImage(SCENE.pipes,380,292,105,210);g.drawImage(SCENE.statue,570,313,95,108);g.globalAlpha=1;
g.fillStyle=t.back;g.font='italic bold 28px serif';g.save();g.translate(208,353);g.rotate(-.08);g.fillText(n===0?'NO REFUNDS':n===1?'KEEP OUT!':'ICE COLD',0,0);g.restore();bgCache[n]=c;return c;}
function background(){const t=PAL[floor%3],bg=sceneBackground(floor%3);ctx.fillStyle=t.sky;ctx.fillRect(0,0,W,H);let y=H-520;for(let x=-720;x<W+720;x+=720)ctx.drawImage(bg,Math.round(x-(cam*.3)%720),y);ctx.fillStyle=t.back;ctx.fillRect(0,H-104,W,110);ctx.strokeStyle=t.wall;ctx.lineWidth=1;for(let y2=H-96;y2<H;y2+=26)for(let x=-40;x<W+40;x+=48){let px=x-(cam*.52)%48+(y2%52===0?20:0);ctx.strokeRect(px,y2,47,25);}
for(let i=-1;i<W/460+2;i++){let x=Math.round(i*460-(cam*.55)%460);ctx.drawImage(SCENE.statue,x,H-203,100,113);ctx.fillStyle=t.wall;ctx.fillRect(x-9,H-93,119,21);ctx.fillStyle=t.top;ctx.fillRect(x-6,H-93,113,3);}}
function drawTV(){const tv=$('tv');if(!tv)return;const g=tv.getContext('2d');g.imageSmoothingEnabled=false;g.clearRect(0,0,100,80);g.fillStyle='#29142b';g.fillRect(0,0,100,80);g.fillStyle=P.inv>.8?'#d23f49':phase==='escape'?'#c35624':'#d79616';g.fillRect(4,4,92,72);const pose=P.inv>.8?'chef-hurt':phase==='escape'||controls.dash?'chef-dash':'chef-idle';const frame=SPR[pose][Math.floor(time*9)%8];g.drawImage(frame,10,0,47,53,4,-8,90,98);if(phase==='escape'){g.strokeStyle='#fff2aa';g.lineWidth=2;g.beginPath();g.moveTo(76,8);g.lineTo(81,19);g.lineTo(74,21);g.stroke();}}
function draw(){ctx.save();ctx.clearRect(0,0,W,H);if(!world){ctx.fillStyle=PAL[0].sky;ctx.fillRect(0,0,W,H);ctx.restore();return;}background();ctx.translate(Math.round(rnd(-shake,shake)),Math.round(rnd(-shake,shake)));ctx.translate(-Math.round(cam),offsetY);let t=PAL[floor%3],left=Math.floor(cam/32)*32;for(let x=left;x<cam+W+40;x+=32){if(world.pits.some(p=>x+32>p.x&&x<p.x+p.w))continue;ctx.fillStyle=t.floor;ctx.fillRect(x,300,32,Math.max(100,H));ctx.fillStyle=t.top;ctx.fillRect(x,300,32,7);ctx.fillStyle=t.tile;ctx.fillRect(x+2,310,27,21);ctx.fillStyle='#231e3f';ctx.fillRect(x,334,32,2);ctx.fillRect(x+14,312,3,17);ctx.fillStyle='#ffffff16';ctx.fillRect(x+3,312,9,2);}for(let p of world.pits){ctx.fillStyle='#ff7d7c';ctx.fillRect(p.x,328,p.w,8);ctx.fillStyle='#ffbb81';for(let x=p.x;x<p.x+p.w;x+=15)ctx.fillRect(x,322+Math.sin(time*4+x)*3,10,8);}
for(let b of world.platforms){ctx.fillStyle='#1d1b34';ctx.fillRect(b.x-2,b.y-2,b.w+4,b.h+4);ctx.fillStyle=b.solid?'#7f8b89':t.tile;ctx.fillRect(b.x,b.y,b.w,b.h);if(b.solid){ctx.strokeStyle='#38474b';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(b.x+15,b.y+10);ctx.lineTo(b.x+21,b.y+23);ctx.lineTo(b.x+15,b.y+29);ctx.lineTo(b.x+25,b.y+42);ctx.stroke();}ctx.fillStyle=b.solid?'#b5bab0':t.top;ctx.fillRect(b.x,b.y,b.w,4);for(let x=b.x+4;x<b.x+b.w;x+=18){ctx.fillStyle=t.floor;ctx.fillRect(x,b.y+7,10,4);}}
for(let b of world.blocks){if(b.dead||b.x<cam-60||b.x>cam+W+60)continue;ctx.fillStyle='#191a34';ctx.fillRect(b.x-2,b.y-2,b.w+4,b.h+4);ctx.fillStyle=t.top;ctx.fillRect(b.x,b.y,b.w,b.h);for(let y=b.y;y<b.y+b.h;y+=16){ctx.fillStyle=t.tile;ctx.fillRect(b.x+2,y+2,b.w-4,11);ctx.fillStyle='#f2d9aa';ctx.fillRect(b.x+4,y+3,8,2);}ctx.fillStyle='#fff0ba';ctx.font='bold 19px monospace';ctx.textAlign='center';ctx.fillText('▰',b.x+b.w/2,b.y+34);}
for(let p of world.pads){ctx.fillStyle='#1e2039';ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle='#8fc6a4';ctx.fillRect(p.x+2,p.y+2,p.w-4,5);ctx.fillStyle='#d3e7b2';for(let x=p.x+5;x<p.x+p.w-5;x+=8)ctx.fillRect(x,p.y+8,3,6);}
ctx.drawImage(SCENE.door,10,158,120,142);if(phase==='escape'&&lap===1){ctx.strokeStyle='#9ffe86';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(240,269,19,28,0,0,7);ctx.stroke();ctx.fillStyle='#9ffe86';ctx.font='bold 10px monospace';ctx.fillText('LAP 2',223,229);}
if(phase==='escape'){ctx.fillStyle='#9ffe86';ctx.font='bold italic 17px serif';ctx.textAlign='center';ctx.fillText('EXIT!',70,151+Math.sin(time*7)*4);}
let bx=world.length-135;if(phase==='play'){ctx.drawImage(SCENE.pillar,bx-22,154,104,147);ctx.fillStyle='#ffe3a7';ctx.font='bold italic 16px serif';ctx.textAlign='center';ctx.fillText('SMASH!',bx+31,143+Math.sin(time*5)*3);}else{ctx.fillStyle='#858774';for(let j=0;j<5;j++)ctx.fillRect(bx+j*15,284+(j%2)*5,12,11);}
for(let p of world.pickups){if(p.taken||p.x<cam-60||p.x>cam+W+60)continue;sprite(p.id,p.x-11,p.y-17+Math.sin(time*5+p.x)*3,39,49);if(p.id==='star'){ctx.fillStyle='#ffebaa';ctx.fillRect(p.x-12,p.y-8,2,2);ctx.fillRect(p.x+26,p.y+9,2,2);}}
for(let e of world.enemies)if(e.alive&&e.x>cam-80&&e.x<cam+W+80){sprite(e.type,e.x-11,e.y-20+Math.sin(time*7+e.home)*1,44,52,e.dir);if(e.type==='helmet'){ctx.fillStyle='#f1d69c';ctx.font='bold 12px monospace';ctx.fillText('↓',e.x+12,e.y-23);}}
for(let r of ragdolls){ctx.save();ctx.translate(r.x+15,r.y+15);ctx.rotate(r.rot);sprite(r.type,-22,-26,44,52);ctx.restore();}for(let tr of trails){ctx.globalAlpha=tr.life*.9;sprite('chef-dash',tr.x-21,tr.y-32,64,76,tr.face);ctx.globalAlpha=1;}
let pose=P.inv>.8?'chef-hurt':!P.ground?'chef-jump':controls.dash&&Math.abs(P.vx)>230?'chef-dash':Math.abs(P.vx)>20?'chef-run':'chef-idle';if(P.inv<=0||Math.floor(time*18)%2===0)sprite(pose,P.x-21,P.y-32,64,76,P.face,Math.floor(time*(pose==='chef-run'?18:12)));if(controls.dash&&Math.abs(P.vx)>300){ctx.fillStyle=t.accent;for(let j=0;j<3;j++)ctx.fillRect(P.x-P.face*(18+j*10),P.y+9+j*8,12,2);}
if(phase==='escape'&&oven<cam+W+100){let fx=oven+70,fy=155+Math.sin(time*4)*30;ctx.fillStyle='#ec47351b';ctx.fillRect(oven,0,4000,420);ctx.beginPath();ctx.ellipse(fx,fy,67,67,0,0,7);ctx.fillStyle='#d98e46';ctx.fill();ctx.strokeStyle='#331929';ctx.lineWidth=3;ctx.stroke();ctx.beginPath();ctx.ellipse(fx,fy,56,57,0,0,7);ctx.fillStyle='#e9c866';ctx.fill();for(let j=0;j<7;j++){let a=j*1.4;ctx.beginPath();ctx.arc(fx+Math.cos(a)*43,fy+Math.sin(a)*43,7,0,7);ctx.fillStyle='#c84842';ctx.fill();}ctx.fillStyle='#fff3d2';ctx.beginPath();ctx.ellipse(fx-17,fy-12,14,19,.2,0,7);ctx.ellipse(fx+14,fy-12,14,19,-.2,0,7);ctx.fill();ctx.fillStyle='#251a26';ctx.fillRect(fx-20,fy-15,6,14);ctx.fillRect(fx+10,fy-15,6,14);ctx.beginPath();ctx.ellipse(fx,fy+24,33,17,0,0,7);ctx.fill();ctx.fillStyle='#fff3d2';for(let j=-2;j<=2;j++)ctx.fillRect(fx+j*10-4,fy+11,8,11);}
for(let p of particles){ctx.globalAlpha=Math.min(1,p.life*3);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.r,p.r);}ctx.globalAlpha=1;ctx.textAlign='center';ctx.font='bold italic 16px monospace';for(let t of words){ctx.globalAlpha=Math.min(1,t.life*3);ctx.strokeStyle='#2b2040';ctx.lineWidth=4;ctx.strokeText(t.text,t.x,t.y);ctx.fillStyle=t.col;ctx.fillText(t.text,t.x,t.y);}ctx.globalAlpha=1;ctx.restore();}
function frame(ts){let dt=Math.min(.05,(ts-last)/1000);last=ts;if(!paused&&['play','escape'].includes(phase)){acc+=dt;while(acc>=1/120){step(1/120);acc-=1/120;if(!['play','escape'].includes(phase))break;}}draw();requestAnimationFrame(frame);}resize();world=makeWorld(floor);P={x:70,y:258,w:22,h:42,face:1,hp:4,maxhp:4,vx:0,vy:0,inv:0};update();requestAnimationFrame(frame);
window.__pepper={state:()=>JSON.parse(JSON.stringify({P,world,floor,lap,phase,paused,score,coins,combo,maxCombo,stars,damage,alarm,oven,cam,W,H,save,runTime,controls})),advance:s=>{for(let i=0;i<s*120;i++)if(!paused&&['play','escape'].includes(phase))step(1/120);draw();}};
