(()=>{'use strict';const A=LanternArt,$=id=>document.getElementById(id),cv=$('world'),ctx=cv.getContext('2d'),map=document.createElement('canvas');map.width=A.BW;map.height=A.BH;const c=map.getContext('2d'),KEY='lantern-line-v1',positions=[[104,175],[399,175],[257,386],[92,530],[431,519],[249,105],[73,354],[455,357],[268,552]],names=['MOON CAFE','STEAM HOUSE','PETAL SHOP','NIGHT LIBRARY'];
let state,record={best:0,night:1},selected=0,editing=null,fx=[],notes=[],toastLeft=0,time=0,last=0,acc=0,saveClock=0,W=0,H=0,NW=0,NH=0,view={x:0,y:0,scale:1},soundOn=true,AC=null,gain=null,recentPointer=-1000,musicClock=0,wide=false;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));function rnd(){state.seed=(Math.imul(state.seed,1664525)+1013904223)>>>0;return state.seed/4294967296}
function station(i){return{id:i,x:positions[i][0],y:positions[i][1],type:i<3?i:i===3?3:i%4,queue:[],light:0,alarm:0}}
function fresh(){state={version:1,seed:(Math.random()*4294967295)>>>0,mode:'play',night:1,score:0,shift:0,goal:8,lives:3,elapsed:0,spawn:4,uid:0,lost:0,combo:0,lastDelivery:-100,capacity:4,speed:75,patience:145,stations:[station(0),station(1),station(2)],lines:Array.from({length:3},()=>({path:[],train:{at:0,dir:1,p:0,dwell:.4,cargo:[]}})),rush:false};for(let i=0;i<3;i++)spawnGuest(state.stations[i],(i+1)%3);selected=0;fx=[];notes=[];editing=null;save();hud()}
function valid(s){return s?.version===1&&['play','upgrade','over'].includes(s.mode)&&s.stations?.length>=3&&s.stations.length<=9&&s.lines?.length===3&&s.lines.every(l=>Array.isArray(l.path)&&l.path.every(id=>s.stations[id])&&l.train&&Array.isArray(l.train.cargo))&&s.stations.every((v,i)=>v.id===i&&Array.isArray(v.queue))}
try{const v=JSON.parse(localStorage.getItem(KEY));if(valid(v?.state)){state=v.state;record=v.record||record;soundOn=v.sound!==false}}catch{}if(!state)fresh();
function save(){try{localStorage.setItem(KEY,JSON.stringify({state,record,sound:soundOn}))}catch{}}
function unlocked(i){return i===0||state.score>=(i===1?8:20)}function playable(){return $('intro').hidden&&$('menu').hidden&&state.mode==='play'&&!document.hidden}
function toast(s,seconds=2.8){$('toast').textContent=s;$('toast').classList.add('show');toastLeft=seconds}
function audio(){if(!soundOn)return;try{if(!AC){AC=new(window.AudioContext||window.webkitAudioContext)();gain=AC.createGain();gain.gain.value=.55;gain.connect(AC.destination)}if(AC.state==='suspended')AC.resume().catch(()=>{})}catch{}}
function tone(freq,duration=.15,vol=.035,delay=0,type='sine'){if(!soundOn||!AC||AC.state!=='running')return;const o=AC.createOscillator(),g=AC.createGain(),start=AC.currentTime+delay;o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.001,start);g.gain.exponentialRampToValueAtTime(vol,start+.012);g.gain.exponentialRampToValueAtTime(.001,start+duration);o.connect(g);g.connect(gain);o.start(start);o.stop(start+duration+.02)}
function sparkle(x,y,col,count=20){for(let i=0;i<count;i++){const a=Math.random()*6.28,v=16+Math.random()*55;fx.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v-15,life:.6+Math.random()*.6,col})}if(fx.length>200)fx.splice(0,fx.length-200)}
function floating(x,y,label,col='#ffe0a5'){notes.push({x,y,label,col,life:1.7});if(notes.length>16)notes.shift()}
function spawnGuest(s,type){if(type==null){const types=[...new Set(state.stations.map(v=>v.type))].filter(t=>t!==s.type);type=types[Math.floor(rnd()*types.length)]}s.queue.push({id:state.uid++,type,look:Math.floor(rnd()*6),age:0});sparkle(s.x,s.y+27,'#c4d7ce',3)}
function V(p){return wide?{x:p.x*1.5,y:p.y*.62+30}:p}function anchor(id){const s=state.stations[id];return{x:s.x,y:s.y+16}}
function graph(){const out=state.stations.map(()=>new Set());for(let i=0;i<3;i++){if(!unlocked(i))continue;const path=state.lines[i].path;for(let j=1;j<path.length;j++){out[path[j-1]].add(path[j]);out[path[j]].add(path[j-1])}}return out}
function distances(type,g){const d=state.stations.map(()=>Infinity),q=[];for(const s of state.stations)if(s.type===type){d[s.id]=0;q.push(s.id)}for(let k=0;k<q.length;k++){const id=q[k];for(const next of g[id])if(d[next]>d[id]+1){d[next]=d[id]+1;q.push(next)}}return d}
function nextIndex(line){const t=line.train,n=line.path.length;if(n<2)return 0;return t.at+t.dir}
function position(line){if(line.path.length<2)return null;const t=line.train,a=anchor(line.path[t.at]),b=anchor(line.path[nextIndex(line)]);return{x:a.x+(b.x-a.x)*t.p,y:a.y+(b.y-a.y)*t.p,angle:Math.atan2(b.y-a.y,b.x-a.x)}}
function deliver(g,s){state.score++;state.shift++;s.light=Math.min(6,s.light+1);state.combo=state.elapsed-state.lastDelivery<6?Math.min(5,state.combo+1):1;state.lastDelivery=state.elapsed;record.best=Math.max(record.best,state.score);record.night=Math.max(record.night,state.night);sparkle(s.x,s.y-25,A.ticket[s.type],22);fx.push({kind:'guest',guest:g,x:s.x,y:s.y+43,toY:s.y-9,life:1.1});floating(s.x,s.y-80,state.combo>1?'HAPPY ×'+state.combo:'HOME ♥');const tune=[523,659,784,880,1047];tone(tune[state.combo-1],.22,.045);tone(tune[state.combo-1]*1.5,.3,.02,.07);if(navigator.vibrate)try{navigator.vibrate(10)}catch{}if(state.score===8||state.score===20){toast((state.score===8?'Mint':'Lilac')+' train is ready. Select its color.');tone(1047,.4,.04,.1)} }
function unload(line){const t=line.train,s=state.stations[line.path[t.at]];for(const passenger of t.cargo){if(passenger.type===s.type)deliver(passenger,s);else s.queue.push(passenger)}t.cargo=[]}
function board(line,g){const t=line.train,s=state.stations[line.path[t.at]],next=line.path[nextIndex(line)];for(let i=s.queue.length-1;i>=0;i--){const guest=s.queue[i];if(guest.type===s.type){s.queue.splice(i,1);deliver(guest,s)}}for(let i=0;i<s.queue.length&&t.cargo.length<state.capacity;){const guest=s.queue[i],dist=distances(guest.type,g);if(Number.isFinite(dist[s.id])&&dist[next]===dist[s.id]-1){t.cargo.push(guest);s.queue.splice(i,1);sparkle(s.x,s.y+26,'#e4d6b7',3)}else i++}}
function build(path){if(path.length<2){toast('Visit two stations to lay a route.');return}const l=state.lines[selected];if(l.path.join(',')===path.join(','))return;const oldStation=l.path[l.train.at];if(oldStation!=null&&l.train.cargo.length)state.stations[oldStation].queue.push(...l.train.cargo);l.path=[...path];l.train={at:0,dir:1,p:0,dwell:.25,cargo:[]};sparkle(anchor(path[0]).x,anchor(path[0]).y,A.colors[selected],15);tone(330+selected*110,.2,.04);tone(660+selected*110,.25,.02,.09);$('hint').textContent='Extend from an end. Tap a moving train: ding & dash.';save();hud()}
function bell(i){const l=state.lines[i],t=l.train;if((t.bellCD||0)>0){toast('Bell is warming up.',1.1);return}t.boost=2.8;t.bellCD=12;const p=position(l);if(p){sparkle(p.x,p.y,A.colors[i],20);floating(p.x,p.y-23,'DING!')}tone(880,.45,.045);tone(1320,.5,.025,.09);if(navigator.vibrate)try{navigator.vibrate([12,35,12])}catch{}save()}function clear(){if(!playable())return;const l=state.lines[selected],id=l.path[l.train.at];if(id!=null)state.stations[id].queue.push(...l.train.cargo);l.path=[];l.train={at:0,dir:1,p:0,dwell:.4,cargo:[]};editing=null;toast('Guests are safe on the platform.');save();hud()}
function nightDone(){state.mode='upgrade';editing=null;const stars=state.lost===0?3:state.lost<3?2:1;$('stars').textContent=Array.from({length:3},(_,i)=>i<stars?'✦':'·').join(' ');$('shift-tag').textContent='NIGHT '+String(state.night).padStart(2,'0')+' · COMPLETE';$('shift-summary').textContent=state.shift+' happy arrivals. '+(state.stations.length<9?'A new stop opens tomorrow.':'The city keeps dreaming.')+' Choose one gift.';$('upgrade').hidden=false;choices();tone(523,.4,.035);tone(659,.4,.03,.12);tone(784,.6,.03,.24);save();hud()}
function choices(){const offers=[{key:'capacity',icon:'▤',name:state.capacity<10?'Room for one more':'A fresh lantern',detail:state.capacity<10?'Every train gains one seat.':'Restore one heart.'},{key:'speed',icon:'≫',name:state.speed<160?'Night express':'A warm welcome',detail:state.speed<160?'All trains travel 12% faster.':'Restore one heart.'},{key:'patience',icon:'♡',name:state.patience<320?'Cozy waiting rooms':'A little extra care',detail:state.patience<320?'Guests wait 25 seconds longer.':'Restore one heart.'}];$('choices').replaceChildren();for(const o of offers){const btn=document.createElement('button'),icon=document.createElement('b'),body=document.createElement('span'),title=document.createElement('strong'),detail=document.createElement('small');icon.textContent=o.icon;title.textContent=o.name;detail.textContent=o.detail;body.append(title,detail);btn.append(icon,body);action(btn,()=>gift(o.key));$('choices').append(btn)}}
function gift(key){if(state.mode!=='upgrade')return;if(key==='capacity'&&state.capacity<10)state.capacity++;else if(key==='speed'&&state.speed<160)state.speed=Math.min(160,state.speed*1.12);else if(key==='patience'&&state.patience<320)state.patience=Math.min(320,state.patience+25);else state.lives=Math.min(3,state.lives+1);state.lives=Math.min(3,state.lives+1);state.night++;record.night=Math.max(record.night,state.night);state.shift=0;state.goal=8+(state.night-1)*3;state.lost=0;state.spawn=3;state.rush=false;state.mode='play';for(const s of state.stations)s.alarm=0;if(state.stations.length<9){const s=station(state.stations.length);state.stations.push(s);spawnGuest(s);sparkle(s.x,s.y-30,'#ffe1b0',45);toast(names[s.type]+' opens. Add it to a route.',4)}else toast('A new night. Your trains and guests carry on.');$('upgrade').hidden=true;save();hud()}
function gameOver(){state.mode='over';editing=null;$('over').hidden=false;$('final-score').textContent=state.score+' ✦';$('final-note').textContent='Night '+state.night+' · Best '+record.best+' deliveries. Try shorter routes and shared transfer stops.';save();hud();tone(220,.5,.04);tone(165,.6,.03,.15)}
function hud(){$('night').textContent='NIGHT '+String(state.night).padStart(2,'0');$('score').textContent='✦ '+state.score;$('hearts').textContent=Array.from({length:3},(_,i)=>i<state.lives?'♥':'·').join(' ');$('quota').textContent=state.shift+' / '+state.goal;$('progress').style.width=clamp(state.shift/state.goal*100,0,100)+'%';document.querySelectorAll('[data-line]').forEach((b,i)=>{b.classList.toggle('selected',i===selected);b.classList.toggle('locked',!unlocked(i));b.setAttribute('aria-pressed',i===selected?'true':'false');b.querySelector('span').textContent=['PEACH','MINT','LILAC'][i]+(!unlocked(i)?' · '+(i===1?8:20):'')});$('sound').style.opacity=soundOn?1:.45;$('best').textContent=record.best?'BEST · '+record.best+' HAPPY ARRIVALS':'A tiny transport game with a warm heart.';$('clear').disabled=!state.lines[selected].path.length}
function action(button,fn){let id=null;button.addEventListener('pointerdown',e=>{if(e.button===0&&!button.disabled)id=e.pointerId});button.addEventListener('pointercancel',()=>id=null);button.addEventListener('pointerup',e=>{if(id!==e.pointerId)return;id=null;e.preventDefault();recentPointer=performance.now();const b=button.getBoundingClientRect();if(e.clientX>=b.left&&e.clientX<=b.right&&e.clientY>=b.top&&e.clientY<=b.bottom&&!button.disabled){audio();fn()}});button.onclick=e=>{if(e.detail!==0&&performance.now()-recentPointer<700)return;audio();fn()}}
function select(i){if(!playable())return;if(!unlocked(i)){toast('Unlocks at '+(i===1?8:20)+' happy arrivals.');return}selected=i;editing=null;tone(260+i*80,.1,.025);hud()}
action($('start'),()=>{$('intro').hidden=true;if(state.mode==='upgrade')nightDone();else if(state.mode==='over')gameOver();else if(!state.lines.some(l=>l.path.length>1))toast('Connect all three stops. Follow the ticket symbols.',4);hud()});action($('clear'),clear);document.querySelectorAll('[data-line]').forEach((b,i)=>action(b,()=>select(i)));action($('pause'),()=>{if(!$('intro').hidden)return;editing=null;$('menu').hidden=false;save()});action($('resume'),()=>{$('menu').hidden=true});function restart(){fresh();$('menu').hidden=true;$('over').hidden=true;$('upgrade').hidden=true;$('intro').hidden=true;toast('A new little town. Connect its three stops.',3)}action($('restart'),restart);action($('again'),restart);action($('sound'),()=>{soundOn=!soundOn;if(!soundOn&&AC)AC.suspend().catch(()=>{});else audio();hud();save()});
function screenPoint(e){const p={x:(e.clientX*NW/W-view.x)/view.scale,y:(e.clientY*NH/H-view.y)/view.scale};return wide?{x:p.x/1.5,y:(p.y-30)/.62}:p}
function hit(point){let best=null,distance=50;for(const s of state.stations){const d=Math.hypot(point.x-s.x,(point.y-(s.y-13))*.8);if(d<distance){best=s.id;distance=d}}return best}
cv.addEventListener('pointerdown',e=>{if(!playable()||e.button!==0)return;audio();const point=screenPoint(e),id=hit(point);if(id==null){let nearest=-1,d=29;state.lines.forEach((l,i)=>{const p=position(l);if(p){const distance=Math.hypot(p.x-point.x,p.y-point.y);if(distance<d){nearest=i;d=distance}}});if(nearest>=0){e.preventDefault();bell(nearest)}return}e.preventDefault();cv.setPointerCapture(e.pointerId);const old=state.lines[selected].path;let path=[id];if(old.length>1&&id===old[old.length-1])path=[...old];else if(old.length>1&&id===old[0])path=[...old].reverse();editing={id:e.pointerId,path,point};tone(440,.07,.025)});
cv.addEventListener('pointermove',e=>{if(!editing||e.pointerId!==editing.id)return;editing.point=screenPoint(e);const id=hit(editing.point),path=editing.path;if(id==null||id===path[path.length-1])return;if(path.length>1&&id===path[path.length-2])path.pop();else if(!path.includes(id)){path.push(id);tone(440+path.length*65,.09,.025);sparkle(state.stations[id].x,state.stations[id].y+16,A.colors[selected],7)}});
cv.addEventListener('pointerup',e=>{if(!editing||e.pointerId!==editing.id)return;const path=editing.path;editing=null;build(path)});cv.addEventListener('pointercancel',()=>editing=null);cv.addEventListener('contextmenu',e=>e.preventDefault());
addEventListener('keydown',e=>{if(e.key==='Escape'&&$('intro').hidden){$('menu').hidden=!$('menu').hidden;editing=null}if(['1','2','3'].includes(e.key))select(+e.key-1)});addEventListener('blur',()=>editing=null);document.addEventListener('visibilitychange',()=>{editing=null;last=0;save();if(document.hidden&&AC)AC.suspend().catch(()=>{})});addEventListener('pagehide',save);
function step(dt){time+=dt;toastLeft-=dt;if(toastLeft<=0)$('toast').classList.remove('show');if(!playable())return;state.elapsed+=dt;state.spawn-=dt;if(state.spawn<=0){const candidates=state.stations.filter(s=>s.queue.length<12),source=candidates[Math.floor(rnd()*candidates.length)];if(source)spawnGuest(source);state.spawn=Math.max(1.7,4.6-state.night*.24)+(rnd()*.8)}const g=graph();for(const l of state.lines){if(l.path.length<2)continue;const t=l.train;t.boost=Math.max(0,(t.boost||0)-dt);t.bellCD=Math.max(0,(t.bellCD||0)-dt);for(const passenger of t.cargo)passenger.age+=dt;if(t.dwell>0){t.dwell-=dt;if(t.dwell<=0)board(l,g);continue}const a=anchor(l.path[t.at]),b=anchor(l.path[nextIndex(l)]),len=Math.hypot(a.x-b.x,a.y-b.y);t.p+=state.speed*(t.boost>0?1.85:1)*dt/Math.max(1,len);if(t.p>=1){t.at=nextIndex(l);t.p=0;if(t.at===0)t.dir=1;if(t.at===l.path.length-1)t.dir=-1;unload(l);t.dwell=.65;if(state.shift>=state.goal){nightDone();return}}}
for(const s of state.stations){for(const guest of s.queue)guest.age+=dt;const stress=s.queue.length>=8||s.queue.some(v=>v.age>state.patience);s.alarm=stress?s.alarm+dt:Math.max(0,s.alarm-dt*2);if(s.alarm>=12){const leaving=s.queue.splice(0,Math.min(3,s.queue.length));state.lost+=leaving.length;state.lives--;s.alarm=0;sparkle(s.x,s.y+20,'#cf97a4',16);floating(s.x,s.y-78,'MISSED THE TRAIN','#e9afbb');toast('A missed ride. Shorten routes or add another train.');tone(146,.32,.04);if(state.lives<=0){gameOver();return}save();hud()}}
for(let i=fx.length-1;i>=0;i--){const f=fx[i];f.life-=dt;if(f.kind==='guest'){f.y+=(f.toY-f.y)*dt*4}else{f.x+=f.vx*dt;f.y+=f.vy*dt;f.vy+=dt*19;}if(f.life<=0)fx.splice(i,1)}for(let i=notes.length-1;i>=0;i--){notes[i].life-=dt;notes[i].y-=dt*10;if(notes[i].life<=0)notes.splice(i,1)}saveClock+=dt;if(saveClock>4){saveClock=0;save()}musicClock+=dt;if(musicClock>3.8&&AC?.state==='running'){musicClock=0,wide=false;const tune=[220,261.63,329.63,293.66,246.94,196];tone(tune[Math.floor(time/4)%6],1.5,.009)} }
function resize(){W=innerWidth;H=innerHeight;const reduction=W<600?1.4:2;NW=Math.ceil(W/reduction);NH=Math.ceil(H/reduction);cv.width=NW;cv.height=NH;ctx.imageSmoothingEnabled=false;wide=W>H&&H<550;map.width=wide?780:A.BW;map.height=wide?460:A.BH;const top=wide?80:103,bottom=wide?12:120,availableH=(H-top-bottom)/reduction,availableW=NW-(wide?320/reduction:12);view.scale=Math.min(availableW/map.width,availableH/map.height);view.x=(availableW-map.width*view.scale)/2+(wide?6:6);view.y=top/reduction+(availableH-map.height*view.scale)/2;}
addEventListener('resize',resize);
function render(){A.sky(ctx,NW,NH,time,state.night);c.clearRect(0,0,map.width,map.height);if(wide){A.rect(c,0,0,map.width,map.height,'#243c50');c.save();c.translate(0,30);c.scale(1.5,.62);A.town(c,state,time);c.restore()}else A.town(c,state,time);for(let i=0;i<3;i++){const path=state.lines[i].path;for(let j=1;j<path.length;j++)A.rail(c,V(anchor(path[j-1])),V(anchor(path[j])),A.colors[i],time)}if(editing){for(let j=1;j<editing.path.length;j++)A.rail(c,V(anchor(editing.path[j-1])),V(anchor(editing.path[j])),A.colors[selected],time,true);if(editing.path.length){A.rail(c,V(anchor(editing.path.at(-1))),V(editing.point),A.colors[selected],time,true)}}
for(const original of [...state.stations].sort((a,b)=>a.y-b.y)){const s={...original,...V(original)};A.building(c,s,time);const a=V(anchor(s.id)),inRoute=state.lines.some(l=>l.path.includes(s.id));A.rect(c,a.x-8,a.y-6,16,12,inRoute?'#ddd6b5':'#738692');A.rect(c,a.x-5,a.y-3,10,6,inRoute?'#526a78':'#2a4559');A.text(c,names[s.type],s.x,s.y-91,7,s.light?'#f4d7a2':'#c0c7bf');const n=s.queue.length;for(let i=0;i<Math.min(8,n);i++){const guest=s.queue[i],gx=s.x-32+(i%4)*19,gy=s.y+43+Math.floor(i/4)*24;A.ghost(c,gx,gy,guest,time,.92);A.rect(c,gx-5,gy-25,11,10,'#1e354c');A.symbol(c,guest.type,gx,gy-20,.42);if(guest.age>state.patience*.75)A.rect(c,gx-5,gy+5,10,2,'#e6a895')}if(n>8)A.text(c,'+'+(n-8),s.x+43,s.y+52,10,'#efd3ab');if(s.alarm>0){A.rect(c,s.x-27,s.y-82,54,4,'#263547');A.rect(c,s.x-27,s.y-82,54*s.alarm/12,4,Math.sin(time*8)>0?'#eeb598':'#b97f99');A.text(c,'!',s.x+40,s.y-40,18,'#ffcd9c')} }
for(let i=0;i<3;i++){const l=state.lines[i],p=position(l);if(p){const v=V(p),a=V(anchor(l.path[l.train.at])),b=V(anchor(l.path[nextIndex(l)]));A.train(c,v.x,v.y,Math.atan2(b.y-a.y,b.x-a.x),A.colors[i],l.train.cargo,time);if((l.train.bellCD||0)<=0)A.text(c,'♪',v.x,v.y-29,10,'#ffd49b');if(l.train.boost>0){for(let j=0;j<4;j++)A.rect(c,v.x-5+j*3,v.y-22-j*2,2,2,'#f5d39b')}}}for(const f of fx){c.globalAlpha=Math.min(1,f.life*2);const v=V(f);if(f.kind==='guest')A.ghost(c,v.x,v.y,f.guest,time,.95);else A.rect(c,v.x,v.y,2,2,f.col)}c.globalAlpha=1;for(const note of notes){c.globalAlpha=Math.min(1,note.life*2);const v=V(note);A.text(c,note.label,v.x,v.y,10,note.col)}c.globalAlpha=1;
// Frame keeps the miniature separate from the night sky.
A.rect(ctx,view.x-3,view.y-3,map.width*view.scale+6,map.height*view.scale+6,'#5c728080');ctx.drawImage(map,Math.round(view.x),Math.round(view.y),Math.round(map.width*view.scale),Math.round(map.height*view.scale));}
let paint=0;function frame(now){requestAnimationFrame(frame);if(document.hidden){last=0;return}if(!last)last=now;acc+=Math.min(.08,(now-last)/1000);last=now;while(acc>=.02){step(.02);acc-=.02}if(now-paint>(W<600?33:16)){render();paint=now;hud()}}
resize();hud();A.cover($('cover').getContext('2d'));if(state.score||state.lines.some(l=>l.path.length))$('start').textContent='CONTINUE THE NIGHT →';requestAnimationFrame(frame);
window.__lantern={build:'1.0',get state(){return state},get record(){return record},get view(){return view},get sound(){return AC?.state||'not-started'},advance(seconds){for(let i=0;i<Math.min(seconds,400)*50;i++)step(.02);hud()},graph,distances,position,screen(id){const s=state.stations[id],v=V({x:s.x,y:s.y-13});return{x:(view.x+v.x*view.scale)*W/NW,y:(view.y+v.y*view.scale)*H/NH}},save};
})();
