/* Original miniature road-trip RPG. No commercial assets or network dependencies. */
(function(){
'use strict';
const $=id=>document.getElementById(id),KEY='last-cassette-v1',META='last-cassette-album-v1';
const glyphs=['◇','◎','+','♥'],names=['Grip','Focus','Care','Heart'],tapes=['OPEN WINDOWS','SUMMER STATIC','THE LONG WAY'];
let meta={stamps:[],photos:[],trips:0,color:0,best:0};try{Object.assign(meta,JSON.parse(localStorage.getItem(META)||'{}'));if(!Array.isArray(meta.stamps))meta.stamps=[];if(!Array.isArray(meta.photos))meta.photos=[];meta.photos=meta.photos.filter(i=>Number.isInteger(i)&&Road.PLACES[i]);meta.stamps=meta.stamps.filter(x=>['festival','coast','mountain','rescue'].includes(x));meta.trips=Number.isFinite(meta.trips)?Math.max(0,meta.trips):0;meta.best=Number.isFinite(meta.best)?Math.max(0,meta.best):0;meta.color=Number.isInteger(meta.color)&&meta.color>=0&&meta.color<=3?meta.color:0}catch(e){}
let state;try{const d=JSON.parse(localStorage.getItem(KEY));if(Road.valid(d))state=d}catch(e){}const fresh=!state;state=state||Road.start(undefined,'festival',meta);let modal=null,busy=false,audio=null,sound=false,lastSave=0,lastTime=0,toastTimer,melodyStep=0,nextNote=0;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(META,JSON.stringify(meta))}catch(e){}}
function icon(type){const i=Road.TYPES.indexOf(type);return '<span class="symbol '+type+'" title="'+names[i]+'">'+glyphs[i]+'</span>'}
function pattern(arr){return arr.map((n,i)=>Array.from({length:n},()=>icon(Road.TYPES[i])).join('')).join('')}
function note(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2200)}
function tone(f=440,d=.12,kind='triangle',vol=.035){if(!sound||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=kind;o.frequency.value=f;g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function chime(){tone(392,.25);setTimeout(()=>tone(523,.35),90);setTimeout(()=>tone(659,.4),180)}
function unlockAudio(){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume()}catch(e){note('Audio is unavailable in this browser.')}}
function button(action,html,cl='action',disabled=false,extra=''){return '<button data-act="'+action+'" class="'+cl+'" '+(disabled?'disabled':'')+' '+extra+'>'+html+'</button>'}
function action(id,title,sub,type='',disabled=false){return button(id,(type?icon(type):'')+'<span><b>'+title+'</b><small>'+sub+'</small></span>','action',disabled)}
function update(){
 const s=state;$('app').classList.toggle('in-event',s.stage==='event');const p=Road.PLACES[s.stage==='travel'||s.stage==='event'?s.route.place:s.place];$('region').textContent=p.name.toUpperCase()+' / '+p.label;$('place').textContent=s.stage==='event'?Road.EVENTS[s.event.id].name:s.stage==='travel'?'The road is yours.':s.stage==='end'?'A summer to remember.':s.leg===0?'The long way home.':p.name;$('caption').textContent=s.stage==='event'?Road.EVENTS[s.event.id].note:p.subtitle;
 for(const n of['energy','car'])$(n).innerHTML=Array.from({length:10},(_,i)=>'<i class="'+(i<Math.ceil(s[n]/10)?'on':'')+'"></i>').join('');$('cash').textContent='$'+s.money;$('fuel').textContent=Math.round(s.fuel);$('gauge').firstElementChild.style.transform='rotate('+(-75+s.fuel*1.5)+'deg)';$('date').textContent='DAY '+s.day+' · '+String(s.hour).padStart(2,'0')+':00';$('track').textContent='SIDE '+String.fromCharCode(65+s.tape)+' / '+tapes[s.tape];$('pause').textContent=s.paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',s.paused?'Resume game':'Pause game');$('status').textContent=s.paused?'PAUSED':s.stage==='event'?'ROAD ENCOUNTER · '+names.join(' / '):p.name+' · Stop '+s.leg+' / 6';$('odometer').textContent=String(s.km).padStart(3,'0')+' KM';$('skip').hidden=s.stage!=='travel';$('skip').disabled=s.paused;
 $('crew').innerHTML=['driver',...s.crew].map(id=>'<div class="seat"><canvas class="portrait" data-person="'+id+'"></canvas><small>'+ (id==='driver'?'YOU':Road.PEOPLE.find(p=>p.id===id).name.toUpperCase())+'</small></div>').join('');document.querySelectorAll('[data-person]').forEach(c=>RoadArt.portrait(c.dataset.person,c));
 let controls='';if(s.stage==='stop'){controls=button('map','<span><b>Choose a road →</b><small>Next stop · '+(6-s.leg)+' roads to go</small></span>','action primary')+action('services','Pit stop','Fuel · repair · rest','care')+action('people','Road company',s.crew.length+'/2 seats occupied','heart')+action('bag','Glovebox','Snacks · tools · coffee','focus');$('roadNote').textContent='PARKED · Take your time.'}
 if(s.stage==='travel'){controls='<div class="travelbox"><p>'+ (s.progress<5?'Windows down. A new road ahead.':s.event&&s.event.log==='CLEAR ROAD'?'The road opens up. Nice work.':'Back on the road.')+'</p><div class="progress"><i style="width:'+(s.progress/18*100)+'%"></i></div>'+button('fast','Cruise ahead →','secondary')+'</div>';$('roadNote').textContent=s.route.kind.toUpperCase()+' ROAD · '+s.route.km+' KM'}
 if(s.stage==='event'){const e=s.event;controls='<div class="eventbox"><div class="event-head"><div><h2>'+Road.EVENTS[e.id].name+'</h2><p>Match symbols. Each skill has two uses.</p></div>'+button('detour','Detour<br>−5 fuel','secondary')+'</div><div class="needs" aria-label="Remaining road challenges">'+pattern(e.need)+'</div><div class="skills">'+Road.cards(s).map(c=>{const used=e.uses[c.id]||0,noMatch=!c.pattern.some((n,i)=>n&&e.need[i]);return button('skill:'+c.id,c.name+'<div class="patterns">'+pattern(c.pattern)+'</div><small>'+ (c.cost?'−'+c.cost+' energy · ':'consumable · ')+(c.limit-used)+' left</small>','skill',used>=c.limit||noMatch||s.energy<c.cost||busy)}).join('')+'</div></div>';$('roadNote').textContent=e.log}
 if(s.stage==='end'){controls=button('end','<span><b>Open your travel album →</b><small>'+s.km+' km · '+s.crew.length+' road friends</small></span>','action primary')+button('new','Another summer →','action');$('roadNote').textContent=s.ending==='rescue'?'A tow home is still a story.':'YOU MADE IT · Keep this feeling.'}
 $('controls').innerHTML=controls; if(s.paused)$('controls').querySelectorAll('button').forEach(b=>b.disabled=true); save();
}
function top(title){return '<div class="panel-top"><h2>'+title+'</h2>'+button('close','×','secondary','', 'aria-label="Close panel"')+'</div>'}
function open(type){modal=type;$('overlay').hidden=false;renderPanel();$('panel').scrollTop=0;$('panel').querySelector('button')?.focus()}
function close(){modal=null;$('overlay').hidden=true;$('panel').innerHTML=''}
function mapArt(){let v=state.visited;return '<div class="map"><svg viewBox="0 0 600 120" aria-label="Travel route"><path d="M30 74 Q110 25 195 68 T355 56 T560 67" fill="none" stroke="#8b9977" stroke-width="3" stroke-dasharray="5 5"/>'+Array.from({length:7},(_,i)=>{let x=30+i*88,y=65+Math.sin(i*2)*15;return '<circle cx="'+x+'" cy="'+y+'" r="'+(i===state.leg?8:5)+'" fill="'+(i<=state.leg?'#576e53':'#abb594')+'"/><text x="'+x+'" y="'+(y+24)+'" text-anchor="middle" font-size="9" fill="#445f43">'+(v[i]!=null?Road.PLACES[v[i]].name:i===6?'DESTINATION':'·')+'</text>'}).join('')+'</svg></div>'}
function renderPanel(){const s=state;let html='';
 if(modal==='welcome'||modal==='new'){html=top('A summer without a plan.')+'<p>Pick a destination. Take six roads to get there. Look after your car, meet strangers, and bring home a story.</p>'+mapArt()+'<div class="routes">'+[['festival','THE LAST SHOW','A town full of music.'],['coast','SALT & SUN','The sea at the end of the road.'],['mountain','ABOVE THE PINES','A sunrise worth the climb.']].map(x=>button('start:'+x[0],'<small class="tag">YOUR DESTINATION</small><h3>'+x[1]+'</h3><p>'+x[2]+'</p>','route')).join('')+'</div><p class="tip">'+(modal==='new'?'Starting again replaces this trip. Your album stays.':'Progress saves automatically. No timer. No rush.')+'</p>'}
 if(modal==='map'){html=top('Take the long way.')+mapArt()+'<p>Choose a route. All roads reach a stop with fuel, rest, and repairs.</p><div class="routes">'+Road.routes(s).map((r,i)=>button('route:'+i,'<small class="tag">'+r.kind.toUpperCase()+' ROAD</small><h3>'+Road.PLACES[r.place].name+'</h3><p>'+r.km+' km · '+r.hours+' h · '+r.weather+'</p><p>Fuel −'+r.fuel+' · Car −'+r.wear+'</p><b>'+({snack:'A free trail snack',cash:'Delivery job +$14',postcard:'A scenic album stop'}[r.gift])+'</b>','route',s.fuel<r.fuel||s.paused)).join('')+'</div><p class="tip">You have '+s.fuel+' fuel. Scenic roads take longer; express roads wear the car faster.</p>'}
 if(modal==='services'){html=top('A little roadside care.')+'<p>Cash $'+s.money+' · Fuel '+s.fuel+' · Energy '+s.energy+' · Car '+s.car+'</p><div class="inventory">'+[
 ['fuel','Fill the tank','+38 fuel · $12',s.fuel===100||s.money<12],['repair','Garage repair','+35 car · $15',s.car===100||s.money<15],['rest','Take a nap','+38 energy · free',s.energy===100],['work','Help at the diner','+$24 · −12 energy',s.worked||s.energy<18],['snack','Trail snack','+1 snack · $5',s.money<5],['tools','Tool roll','+1 repair item · $9',s.money<9],['coffee','Hot coffee','+1 coffee · $5',s.money<5],['assist','Roadside assistance','Up to $10 · +1 day',s.fuel>=12&&s.car>=10]
 ].map(x=>button('service:'+x[0],x[1]+'<p>'+x[2]+'</p>','',x[3]||s.paused)).join('')+'</div><p class="tip">Work is available once per stop. Rest is always free.</p>'}
 if(modal==='people'){const p=Road.PEOPLE.find(p=>p.id===s.offer);html=top('Room for one more?')+'<p>Two passenger seats. Each friend brings one powerful skill to every road encounter.</p><div class="person"><canvas class="portrait" data-person="'+p.id+'"></canvas><div><strong>'+p.name+'</strong><small>'+p.role+'</small><p>'+p.line+'</p><div class="patterns">'+pattern(p.pattern)+'</div></div>'+button('recruit:'+p.id,s.crew.includes(p.id)?'Already riding':'Offer a ride →','',s.crew.includes(p.id)||s.crew.length>=2||s.paused)+'</div>'+s.crew.map(id=>{let p=Road.PEOPLE.find(x=>x.id===id);return '<div class="log">'+p.name+' · '+p.role+' '+button('release:'+id,'Say goodbye','secondary',s.paused)+'</div>'}).join('')}
 if(modal==='bag'){html=top('The glovebox.')+'<p>Consumables are used during road encounters. Skill symbols show exactly what each item clears.</p><div class="inventory">'+[['snack','Trail snack',[0,0,0,3],'Also restores 10 energy'],['tools','Tool roll',[1,0,3,0],'For a car that keeps going'],['coffee','Hot coffee',[0,3,0,1],'Also restores 6 energy']].map(x=>'<div class="stamp"><b>'+x[1]+' ×'+s.bag[x[0]]+'</b><div class="patterns">'+pattern(x[2])+'</div><p>'+x[3]+'</p></div>').join('')+'</div><p class="tip">Grip ◇ · Focus ◎ · Care + · Heart ♥</p>'}
 if(modal==='journal'){html=top('Your travel album.')+mapArt()+'<p>'+meta.trips+' completed trips · Best distance '+meta.best+' km</p><div class="stamps">'+ (meta.stamps.length?meta.stamps.map(x=>'<div class="stamp">'+({festival:'♫ THE LAST SHOW',coast:'≈ SALT & SUN',mountain:'△ ABOVE THE PINES',rescue:'↗ A KIND STRANGER'}[x]||x)+'</div>').join(''):'<p>Your first postcard is waiting at the end of the road.</p>')+'</div><h3>Scenic postcards</h3><div class="photo-grid">'+meta.photos.map(i=>'<div><canvas width="720" height="360" data-photo="'+i+'"></canvas><small>'+Road.PLACES[i].name+'</small></div>').join('')+'</div><h3>Car paint</h3>'+['#c7b996','#758b82','#ad7460','#698599'].map((col,i)=>button('paint:'+i,'','swatch',i>meta.stamps.length,'style="background:'+col+'" aria-label="Choose car paint '+i+'"')).join('')+'<p class="tip">Each different ending unlocks a paint colour.</p>'+s.history.map(x=>'<div class="log">'+x.km+' KM / '+Road.PLACES[x.place].name+'<p>'+Road.EVENTS[x.event].name+'</p></div>').join('')+button('new','Start another summer','secondary')}
 if(modal==='end'){const titles={festival:'You found your song.',coast:'Nothing but the horizon.',mountain:'Above everything.',rescue:'Someone stopped for you.'};html=top(titles[s.ending])+'<canvas id="postcard" class="result-art" width="720" height="360"></canvas><p>'+({festival:'A band is playing somewhere beyond the diner. You turn off the engine and follow the sound.',coast:'Salt on the windows. Sand in your shoes. You stay until the light is gone.',mountain:'You park above the clouds. For a moment, the whole world is quiet.',rescue:'The car did not make it. A stranger did. Some journeys end with a different kind of kindness.'}[s.ending])+'</p><div class="stamps"><div class="stamp">'+s.km+' KM</div><div class="stamp">'+s.crew.length+' ROAD FRIENDS</div><div class="stamp">'+s.perfect+' SMOOTH ENCOUNTERS</div></div><p>Trip saved to your album. '+(meta.stamps.length>1?'More colours in your journal.':'Your next car colour is unlocked.')+'</p>'+button('new','Another summer →','primary')}
 $('panel').innerHTML=html;document.querySelectorAll('#panel [data-person]').forEach(c=>RoadArt.portrait(c.dataset.person,c));document.querySelectorAll('[data-photo]').forEach(c=>{const shot={...s,place:+c.dataset.photo,stage:'stop',route:null};RoadArt.draw(c.getContext('2d'),shot,0,0)});if($('postcard'))RoadArt.draw($('postcard').getContext('2d'),s,0,0);
}
function reward(){if(state.rewarded)return;state.rewarded=true;meta.trips++;meta.best=Math.max(meta.best,state.km);if(!meta.stamps.includes(state.ending))meta.stamps.push(state.ending);save();chime();open('end')}
function dispatch(act){if(busy)return;const [a,arg]=act.split(':');if(['close','journal','sound','pause','radio','new','end'].includes(a)){}else if(state.paused)return;
 if(a==='close'){close();return}if(a==='sound'){sound=!sound;if(sound)unlockAudio();$('sound').textContent=sound?'Sound on':'Sound off';tone(330,.2);return}if(a==='pause'){state.paused=!state.paused;update();note(state.paused?'Parked for a moment.':'Back on the road.');return}if(a==='radio'){unlockAudio();sound=true;$('sound').textContent='Sound on';state.tape=(state.tape+1)%3;melodyStep=0;tone(220,.06);update();note('SIDE '+String.fromCharCode(65+state.tape)+' / '+tapes[state.tape]);return}if(a==='journal'){open('journal');return}if(a==='new'){open('new');return}if(a==='end'){open('end');return}
 if(a==='start'){state=Road.start((Date.now()+Math.floor(Math.random()*100000))>>>0,arg,meta);close();update();note('A fresh tank. An open road.');return}
 if(['map','services','people','bag'].includes(a)){open(a);return}
 if(a==='route'){if(Road.choose(state,+arg)){close();update();tone(110,.22);note('Next stop: '+Road.PLACES[state.route.place].name)}return}
 if(a==='service'){if(Road.service(state,arg)){chime();note({fuel:'Tank topped up. +38 fuel',repair:'Engine sounds better. +35 car',rest:'A good nap. +38 energy',work:'A little honest work. +$24',snack:'Trail snack packed.',tools:'Tools tucked away.',coffee:'Coffee in the cup holder.',assist:'A kind stranger got you moving. +1 day'}[arg]);update();renderPanel()}return}
 if(a==='recruit'){if(Road.recruit(state,arg)){chime();note(Road.PEOPLE.find(x=>x.id===arg).name+' is riding with you.');update();renderPanel()}return}
 if(a==='release'){state.crew=state.crew.filter(x=>x!==arg);update();renderPanel();return}
 if(a==='paint'){const i=+arg;if(i<=meta.stamps.length){state.color=i;meta.color=i;save();note('A fresh coat of paint.');renderPanel()}return}
 if(a==='fast'){state.progress=state.event?17.95:4.95;save();return}
 if(a==='detour'){if(Road.detour(state)){note('A little longer. A little safer.');update()}return}
 if(a==='skill'){const before=state.event?.need.slice(),result=Road.skill(state,arg);if(!result)return;busy=true;let left=0;$('controls').querySelectorAll('.need').forEach(n=>{});const tokens=[...$('controls').querySelectorAll('.needs .symbol')];for(let i=0;i<4;i++){for(let k=0;k<before[i];k++){const token=tokens[left++];if(k<before[i]-state.event.need[i])token?.classList.add('removed')}}tone(330+result.matched*65,.18);save();setTimeout(()=>{busy=false;if(result.clear){chime();note('CLEAR ROAD · '+result.matched+' symbols cleared');}else note(result.matched+' symbols cleared');update()},280)}
}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;let a=b.dataset.act;if(!a)a={journal:'journal',sound:'sound',pause:'pause',radio:'radio',skip:'fast'}[b.id];if(a)dispatch(a)});
// A native touch-up may otherwise lose its click after a drag or hit the newly exposed panel.
let touchButton=null,blockUntil=0;document.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'){const b=e.target.closest('button');touchButton=b?{b,id:e.pointerId,x:e.clientX,y:e.clientY}:null}},true);document.addEventListener('pointerup',e=>{const t=touchButton;if(!t||t.id!==e.pointerId)return;touchButton=null;if(t.b.isConnected&&!t.b.disabled&&Math.hypot(e.clientX-t.x,e.clientY-t.y)<12){e.preventDefault();blockUntil=Date.now()+600;t.b.click()}},true);document.addEventListener('pointercancel',()=>touchButton=null,true);document.addEventListener('click',e=>{if(e.isTrusted&&Date.now()<blockUntil){e.preventDefault();e.stopImmediatePropagation()}},true);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(modal)close();else dispatch('pause')}if(e.key===' '&&e.target===document.body){e.preventDefault();dispatch(state.stage==='travel'?'fast':'map')}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){state.paused=true;save();update()}});
const ctx=$('scene').getContext('2d');let accum=0;
function frame(ms){let dt=Math.min(.1,(ms-lastTime)/1000||0);lastTime=ms;accum+=dt;if(!modal&&!busy){const prev=state.stage;Road.tick(state,dt);if(prev!==state.stage){update();if(state.stage==='end')reward();else if(state.stage==='stop'){if(state.route.gift==='postcard'&&!meta.photos.includes(state.place))meta.photos.push(state.place);save();chime();note('ARRIVED · '+Road.PLACES[state.place].name+' · +$'+(state.route.gift==='cash'?14:6)+(state.route.gift==='postcard'?' · Postcard saved':''))}}}
 if(accum>=1/30){RoadArt.draw(ctx,state,ms/1000,state.paused||modal?0:accum);accum=0;if(state.stage==='travel'){$('controls').querySelector('.progress i')?.style.setProperty('width',(state.progress/18*100)+'%')}}
 if(sound&&audio&&!state.paused&&!modal&&audio.currentTime>nextNote){nextNote=audio.currentTime+.28;const notes=[[220,0,330,392,440,330,0,294,220,0,262,330,392,294,0,196],[196,294,0,330,392,0,294,262,220,0,262,294,330,0,294,196],[165,220,262,0,330,262,220,0,196,247,294,0,330,294,247,0]][state.tape];let n=notes[melodyStep++%16];if(n)tone(n,.25,'triangle',.016);if(melodyStep%4===0)tone(82,.3,'sine',.014)}
 if(ms-lastSave>3000){lastSave=ms;save()}requestAnimationFrame(frame)}
update();requestAnimationFrame(frame);if(fresh)open('welcome');if(state.stage==='end'&&!state.rewarded)reward();
// Read-only debugging snapshot for package validation and support.
window.Cassette={get state(){return JSON.parse(JSON.stringify(state))},get album(){return JSON.parse(JSON.stringify(meta))}};
})();
