(function(root){'use strict';const names=['A letter to the moon','Comet tea service','The violet relay','Satellite gardens','Cloudberry crossing','The wandering office','Aurora express','Last light delivery'];
function config(n){return{stations:[{x:102+(n%2)*15,y:180,r:25,m:n>2?12:0,need:n<2?2:3},{x:295-(n%3)*12,y:240,r:25,m:n>4?20:0,need:n<2?2:3},{x:190+(n%2)*24,y:347,r:27,m:n>1?14:0,need:n<2?2:3}],coins:[{x:200,y:112},{x:62,y:245},{x:333,y:405}],bumpers:[{x:65,y:360,r:18},{x:335,y:156,r:18}],gate:n>3};}
function fresh(n=0){return{v:1,n,t:0,ball:{x:200,y:500,vx:0,vy:0},angles:[.24,Math.PI-.24],hits:[0,0,0],coins:[],score:0,combo:0,lastHit:-10,cooldown:0,losses:0,launches:0,ready:true,cleared:false,won:false,seed:12345+n*97,events:[]};}
function rnd(s){s.seed=(Math.imul(s.seed,1664525)+1013904223)>>>0;return s.seed/4294967296;}
function pos(s,i){const p=config(s.n).stations[i];return{...p,x:p.x+Math.sin(s.t*.85+i*2)*p.m,y:p.y+Math.cos(s.t*.7+i)*p.m*.45};}
function flipper(s,k){const x=k?290:110,y=535,a=s.angles[k];return{x,y,tx:x+Math.cos(a)*78,ty:y+Math.sin(a)*78};}
function emit(s,type,x,y,extra={}){s.events.push({type,x,y,...extra});if(s.events.length>30)s.events.shift();}
function launch(s){if(!s.ready||s.won)return false;s.ready=false;s.launches++;s.ball={x:200,y:500,vx:(rnd(s)-.5)*140,vy:-665};emit(s,'launch',200,500);return true;}
function nudge(s){if(s.won||s.ready||s.cooldown>0)return false;s.cooldown=3;s.ball.vy=Math.min(s.ball.vy,-400);s.ball.vx+=(s.ball.x<200?1:-1)*120;emit(s,'nudge',s.ball.x,s.ball.y);return true;}
function segment(s,ax,ay,bx,by,r=6,k=-1,omega=0){const b=s.ball,dx=bx-ax,dy=by-ay,l=dx*dx+dy*dy,t=Math.max(0,Math.min(1,((b.x-ax)*dx+(b.y-ay)*dy)/l)),px=ax+dx*t,py=ay+dy*t,xx=b.x-px,yy=b.y-py,d=Math.hypot(xx,yy);if(d>=r+10)return;const nx=d>.01?xx/d:0,ny=d>.01?yy/d:-1;b.x=px+nx*(r+10+.1);b.y=py+ny*(r+10+.1);const sx=-omega*(py-ay),sy=omega*(px-ax),vn=(b.vx-sx)*nx+(b.vy-sy)*ny;if(vn<0){b.vx-=(1.75)*vn*nx;b.vy-=(1.75)*vn*ny;if(k>=0&&Math.abs(omega)>1.5&&b.y<ay+12){const spread=(b.x-200)*-1.9;b.vx=spread+(rnd(s)-.5)*120;b.vy=-530-rnd(s)*75;emit(s,'flip',px,py,{k});}}}
function circle(s,p,i){const b=s.ball,dx=b.x-p.x,dy=b.y-p.y,d=Math.hypot(dx,dy),rr=p.r+10;if(d>=rr)return;const nx=d>.001?dx/d:0,ny=d>.001?dy/d:-1;b.x=p.x+nx*(rr+.2);b.y=p.y+ny*(rr+.2);const vn=b.vx*nx+b.vy*ny;if(vn>=0)return;const speed=Math.max(350,Math.min(540,Math.hypot(b.vx,b.vy)*1.04));b.vx=nx*speed+(rnd(s)-.5)*70;b.vy=ny*speed-35;
if(s.t-s.lastHit<2)s.combo=Math.min(12,s.combo+1);else s.combo=1;s.lastHit=s.t;s.score+=25*s.combo;if(i>=0){s.hits[i]=Math.min(p.need,s.hits[i]+1);emit(s,'stamp',p.x,p.y,{i,combo:s.combo,done:s.hits[i]===p.need});}else emit(s,'bump',p.x,p.y,{combo:s.combo});}
function step(s,dt,input={}){if(s.won)return;dt=Math.min(1/60,Math.max(0,dt));s.t+=dt;s.cooldown=Math.max(0,s.cooldown-dt);const omega=[];for(let k=0;k<2;k++){const old=s.angles[k],target=input[k]?(k?Math.PI+.57:-.57):(k?Math.PI-.24:.24);s.angles[k]+=Math.max(-dt*14,Math.min(dt*14,target-old));omega[k]=(s.angles[k]-old)/dt||0;}if(s.ready)return;const b=s.ball;b.vy+=360*dt;b.vx*=Math.exp(-.018*dt);const speed=Math.hypot(b.vx,b.vy);if(speed>780){b.vx*=780/speed;b.vy*=780/speed;}b.x+=b.vx*dt;b.y+=b.vy*dt;
if(b.x<35){b.x=35;b.vx=Math.abs(b.vx)*.9;}if(b.x>365){b.x=365;b.vx=-Math.abs(b.vx)*.9;}if(b.y<80){b.y=80;b.vy=Math.abs(b.vy)*.88;}
segment(s,35,438,110,535,8);segment(s,365,438,290,535,8);
for(let k=0;k<2;k++){const f=flipper(s,k);segment(s,f.x,f.y,f.tx,f.ty,9,k,omega[k]);}
const cfg=config(s.n);for(let i=0;i<3;i++)circle(s,pos(s,i),i);for(const p of cfg.bumpers)circle(s,p,-1);
if(cfg.gate){const a=Math.sin(s.t*.8)*.4;segment(s,200-Math.cos(a)*42,278-Math.sin(a)*42,200+Math.cos(a)*42,278+Math.sin(a)*42,4);}
cfg.coins.forEach((p,i)=>{if(!s.coins.includes(i)&&Math.hypot(b.x-p.x,b.y-p.y)<27){s.coins.push(i);s.score+=200;emit(s,'coin',p.x,p.y);}});
s.cleared=s.hits.every((h,i)=>h>=cfg.stations[i].need);if(s.cleared&&s.coins.length===3){finish(s);return;}
if(b.y>615){s.losses++;s.combo=0;s.ready=true;s.ball={x:200,y:500,vx:0,vy:0};emit(s,'drain',200,575);}}
function finish(s){if(!s.cleared||s.won)return false;s.won=true;emit(s,'win',s.ball.x,s.ball.y);return true;}
function stars(s){return s.won?1+(s.coins.length===3?1:0)+(s.losses<=2?1:0):0;}
function restore(a){if(!a||a.v!==1||!Number.isInteger(a.n)||a.n<0||a.n>7||!Number.isFinite(a.t)||a.t<0||!a.ball||['x','y','vx','vy'].some(k=>!Number.isFinite(a.ball[k]))||Math.abs(a.ball.x)>2000||Math.abs(a.ball.y)>2000||!Array.isArray(a.hits)||a.hits.length!==3||a.hits.some((h,i)=>!Number.isInteger(h)||h<0||h>config(a.n).stations[i].need)||!Array.isArray(a.angles)||a.angles.length!==2||a.angles.some(x=>!Number.isFinite(x)||Math.abs(x)>7)||!Array.isArray(a.coins)||a.coins.some(i=>!Number.isInteger(i)||i<0||i>2)||new Set(a.coins).size!==a.coins.length||!Number.isFinite(a.cooldown)||a.cooldown<0||a.cooldown>3||!Number.isInteger(a.losses)||a.losses<0||!Number.isInteger(a.score)||a.score<0||!Number.isInteger(a.launches)||a.launches<0||!Number.isInteger(a.seed)||!Number.isFinite(a.combo)||!Number.isFinite(a.lastHit))return null;const s=JSON.parse(JSON.stringify(a));s.events=[];s.cleared=s.hits.every((h,i)=>h>=config(s.n).stations[i].need);s.won=!!a.won&&s.cleared;s.ready=!!a.ready;return s;}
const api={names,config,fresh,pos,flipper,step,launch,nudge,finish,stars,restore};if(typeof module!=='undefined')module.exports=api;else root.Post=api;
})(typeof window==='undefined'?globalThis:window);
