(function(root){'use strict';const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));function rand(seed){return()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};}const POWERS=[['Magazine','+3 shots','ammo'],['Heavy soles','+1 damage','damage'],['Twin flare','Wider shots','spread'],['Gem magnet','Pull nearby gems','magnet'],['Red heart','+1 max heart','heart'],['Quick spark','Faster fire','speed']];
class Game{constructor(zone=0,seed=7,powers={}){this.zone=zone;this.seed=seed;this.powers={ammo:0,damage:0,spread:0,magnet:0,heart:0,speed:0,...powers};this.maxHp=4+this.powers.heart;this.hp=this.maxHp;this.ammo=this.capacity();this.p={x:180,y:90,vy:0,vx:0};this.time=0;this.phase='run';this.gems=0;this.kills=0;this.combo=0;this.bestCombo=0;this.cool=0;this.invuln=0;this.bullets=[];this.hostile=[];this.events=[];this.particles=[];this.length=1000+Math.min(4,zone)*70;this.platforms=[];this.enemies=[];this.loot=[];this.boss=zone%3===2;const r=rand(seed+zone*9001);this.platforms.push({x:130,y:150,w:100,age:0,spent:false});for(let y=285;y<this.length-240;y+=125){const x=r()>.5?34:230;this.platforms.push({x,y,w:96,age:0,spent:false});this.enemies.push({x:x+48,y:y-20,base:x+48,hp:zone>5?2:1,kind:Math.floor(r()*3),alive:true,hit:0});for(let i=0;i<3;i++)this.loot.push({x:80+r()*200,y:y-65+i*12,alive:true});if(zone>0)this.enemies.push({x:180+r()*50,y:y+40,base:180+r()*50,hp:1,kind:1,alive:true,hit:0});}if(this.boss){this.platforms.push({x:22,y:this.length-180,w:316,bossFloor:true,age:0,spent:false});this.enemies.push({x:180,y:this.length-98,base:180,hp:12+Math.min(zone,34)*2,kind:3,alive:true,hit:0});}}
capacity(){return 8+this.powers.ammo*3;}event(type,x=this.p.x,y=this.p.y,n=1){this.events.push({type,x,y,n});}hurt(){if(this.invuln>0||this.phase!=='run')return;this.hp--;this.invuln=1.15;this.combo=0;this.event('hurt');if(this.hp<=0){this.phase='dead';this.event('dead');}}
step(dt,input={}){if(this.phase!=='run')return;dt=Math.min(.04,dt);this.time+=dt;this.invuln=Math.max(0,this.invuln-dt);this.cool-=dt;const p=this.p,oldY=p.y;p.vx=clamp(input.move||0,-1,1)*195;p.x=clamp(p.x+p.vx*dt,32,328);if(input.fire&&this.cool<=0&&this.ammo>0){this.cool=Math.max(.075,.19-this.powers.speed*.024);this.ammo--;p.vy=Math.min(p.vy,60)-95;if(p.vy< -160)p.vy=-160;const count=this.powers.spread>0?3:1;for(let i=0;i<count;i++)this.bullets.push({x:p.x+(i-(count-1)/2)*7,y:p.y+16,vx:(i-(count-1)/2)*85,vy:620,life:1.5,damage:1+this.powers.damage});this.event('shot',p.x,p.y+16);}
p.vy=Math.min(390,p.vy+750*dt);p.y+=p.vy*dt;for(const f of this.platforms){if(f.spent)continue;if(f.age>0){f.age+=dt;if(f.age>.5&&!f.bossFloor){f.spent=true;this.event('crumble',f.x+f.w/2,f.y);continue;}}if(p.vy>=0&&oldY+12<=f.y+3&&p.y+12>=f.y&&p.x+9>f.x&&p.x-9<f.x+f.w){p.y=f.y-12;p.vy=0;this.ammo=this.capacity();if(!f.age){f.age=.001;this.event('land');this.bestCombo=Math.max(this.bestCombo,this.combo);this.combo=0;}}}
for(const e of this.enemies){if(!e.alive)continue;e.hit=Math.max(0,e.hit-dt);if(e.kind===1)e.x=e.base+Math.sin(this.time*2+e.y)*35;else if(e.kind===3){e.x=180+Math.sin(this.time*.85)*62;if(Math.floor(this.time/.9)!==Math.floor((this.time-dt)/.9)&&Math.abs(p.y-e.y)<450){const dx=p.x-e.x,dy=p.y-e.y,dist=Math.hypot(dx,dy)||1;this.hostile.push({x:e.x,y:e.y,vx:dx/dist*140,vy:dy/dist*140,life:4});this.event('warning',e.x,e.y);}}if(Math.abs(p.x-e.x)<(e.kind===3?32:18)&&Math.abs(p.y-e.y)<(e.kind===3?32:20)){if(p.vy>70&&oldY<e.y-12){this.hit(e,2+this.powers.damage);p.vy=-245;this.ammo=this.capacity();this.event('stomp');}else this.hurt();}}
for(const b of this.bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;for(const e of this.enemies){if(e.alive&&Math.abs(b.x-e.x)<(e.kind===3?36:19)&&Math.abs(b.y-e.y)<(e.kind===3?32:18)){this.hit(e,b.damage);b.life=0;break;}}}this.bullets=this.bullets.filter(b=>b.life>0&&b.x>22&&b.x<338&&b.y<this.length+20).slice(-80);for(const b of this.hostile){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(Math.hypot(b.x-p.x,b.y-p.y)<14){this.hurt();b.life=0;}}this.hostile=this.hostile.filter(b=>b.life>0).slice(-30);for(const l of this.loot){if(!l.alive)continue;const d=Math.hypot(l.x-p.x,l.y-p.y);if(d<55+this.powers.magnet*50){const f=Math.min(1,dt*8);l.x+=(p.x-l.x)*f;l.y+=(p.y-l.y)*f;}if(d<19){l.alive=false;this.gems++;this.event('gem',l.x,l.y);}}
if(this.boss&&!this.enemies.some(e=>e.kind===3&&e.alive)){const f=this.platforms.find(f=>f.bossFloor);if(f)f.bossFloor=false;}if(this.phase==='run'&&p.y>this.length+20){this.phase='clear';this.bestCombo=Math.max(this.bestCombo,this.combo);this.event('clear');}this.loot=this.loot.filter(l=>l.alive);}
hit(e,n){e.hp-=n;e.hit=.12;this.event('hit',e.x,e.y);if(e.hp<=0){e.alive=false;this.kills++;this.combo++;this.bestCombo=Math.max(this.bestCombo,this.combo);for(let i=0;i<(e.kind===3?12:3);i++)this.loot.push({x:e.x+(i%3-1)*12,y:e.y-Math.floor(i/3)*10,alive:true});this.event('pop',e.x,e.y,this.combo);}}
choices(){const shift=this.zone%2?3:0,all=[...POWERS.slice(shift),...POWERS.slice(0,shift)].filter(p=>this.powers[p[2]]<4);return all.length?all.slice(0,3):[['Keep going','Fully charged','continue']];}upgrade(key){if(this.phase==='clear'&&key==='continue')return true;if(this.phase!=='clear'||!Object.hasOwn(this.powers,key))return false;this.powers[key]=Math.min(4,this.powers[key]+1);return true;}snapshot(){const d={};for(const k of Object.keys(this))if(k!=='events')d[k]=this[k];return JSON.parse(JSON.stringify(d));}static restore(s){const g=new Game(s.zone,s.seed,s.powers);Object.assign(g,JSON.parse(JSON.stringify(s)));g.events=[];return g;}}
const api={Game,POWERS};if(typeof module!=='undefined')module.exports=api;else root.SD=api;
})(typeof window==='undefined'?globalThis:window);
