/* Quiet Kiln — original software-rendered pottery studio. */
const N=72,KEY='quiet-kiln-v1',clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const glazes=[['Celadon','#8bad91'],['Honey','#c58b47'],['Cloud','#d7d9d1'],['Midnight','#456779'],['Rose','#b98079'],['Lilac','#9992b1']];
const orders=[['Morning vessel',0],['Moon jar',1],['Little bud',2],['Tea at dusk',3],['River bowl',4],['Tall story',5],['Pebble vase',6],['Open sky',7],['Honey pot',8],['Quiet lantern',9],['Soft shoulders',10],['Last light',11]];
function target(k){return Array.from({length:N},(_,i)=>{let t=i/(N-1);switch(k%12){case 0:return 42+32*Math.sin(Math.PI*t)-17*t;case 1:return 27+55*Math.sin(Math.PI*t)**.8;case 2:return 21+42*Math.exp(-(((t-.67)/.27)**2));case 3:return 50+19*Math.sin(Math.PI*t);case 4:return 83-52*t+8*Math.sin(Math.PI*t);case 5:return 32+17*Math.sin(Math.PI*t*1.2);case 6:return 29+51*Math.sin(Math.PI*t)**1.4;case 7:return 85-49*t;case 8:return 45+33*Math.sin(Math.PI*t);case 9:return 37+28*Math.sin(Math.PI*t*2)**2;case 10:return 27+54*Math.exp(-(((t-.43)/.3)**2));default:return 26+26*t+20*Math.sin(Math.PI*t)}})}
let saved;try{saved=JSON.parse(localStorage.getItem(KEY))}catch{}let S={day:0,phase:'shape',r:Array(N).fill(65),paint:Array(N).fill(-1),glaze:0,pattern:0,collection:[],mute:false,...saved},history=[],pointer=null,fx=[],time=0,heat=0,ctxAudio,master,lastSound=0,paused=false,confirmReset=0;
if(!Array.isArray(S.r)||S.r.length!==N)S.r=Array(N).fill(65);if(!Array.isArray(S.paint)||S.paint.length!==N)S.paint=Array(N).fill(-1);if(S.phase==='fire')S.phase='glaze';
const $=id=>document.getElementById(id);function save(){try{localStorage.setItem(KEY,JSON.stringify(S))}catch{}}
function score(){let t=target(S.day),err=S.r.reduce((a,r,i)=>a+Math.abs(r-t[i]),0)/N;return Math.round(clamp(100-err*2.1,0,100))}
function note(f=300,len=.08){if(S.mute||paused||document.hidden)return;try{ctxAudio??=new(window.AudioContext||window.webkitAudioContext)();ctxAudio.resume();master??=ctxAudio.createGain();master.connect(ctxAudio.destination);master.gain.value=.15;let o=ctxAudio.createOscillator(),g=ctxAudio.createGain();o.type='sine';o.frequency.setValueAtTime(f,ctxAudio.currentTime);g.gain.setValueAtTime(.25,ctxAudio.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctxAudio.currentTime+len);o.connect(g);g.connect(master);o.start();o.stop(ctxAudio.currentTime+len)}catch{}}
function checkpoint(){history.push({r:S.r.slice(),paint:S.paint.slice()});if(history.length>15)history.shift()}
function update(){let k=S.day%12;$('day').textContent=`PIECE ${String(S.day+1).padStart(2,'0')}`;$('stage').textContent={shape:'01 / SHAPE',glaze:'02 / GLAZE',fire:'03 / FIRE',done:'04 / KEEP'}[S.phase];$('name').textContent=orders[k][0];$('match').textContent=`Shape harmony · ${score()}%`;$('meter').style.width=score()+'%';$('action').textContent={shape:'Glaze →',glaze:'Fire in the kiln ✦',fire:'Firing…',done:'Make another →'}[S.phase];$('action').disabled=S.phase==='fire';$('undo').disabled=!history.length||['fire','done'].includes(S.phase);$('reset').disabled=S.phase==='fire';$('hint').textContent={shape:'Drag the clay sideways to shape',glaze:'Brush the spinning clay · tap a glaze below',fire:'A little warmth. A little patience.',done:'Made by you. One of a kind.'}[S.phase];$('sound').textContent=S.mute?'♩':'♪';$('tools').innerHTML='';if(S.phase==='shape'){let b=document.createElement('button');b.textContent='↔';b.className='selected';b.setAttribute('aria-label','Sculpt tool');$('tools').append(b)}if(S.phase==='glaze')glazes.forEach((g,i)=>{let b=document.createElement('button');b.style.background=g[1];b.className=S.glaze===i?'selected':'';b.setAttribute('aria-label',g[0]);b.onclick=()=>{S.glaze=i;update();save();note(330+i*55)};$('tools').append(b)});if(S.phase==='done')$('tools').textContent='✦'.repeat(score()>=90?3:score()>=75?2:1);drawTarget();}
function drawTarget(){if(S.phase==='glaze'){[['Plain','○'],['Stardust','∴'],['Petal glaze','✿']].forEach((a,i)=>{let b=document.createElement('button'),need=i===1?2:i===2?4:0;b.disabled=S.collection.length<need;b.textContent=b.disabled?'⌑':a[1];b.setAttribute('aria-label',a[0]);b.title=b.disabled?'Finish '+need+' pieces to unlock':a[0];b.className=S.pattern===i?'selected':'';b.onclick=()=>{S.pattern=i;save();update();note(523)};$('tools').append(b)})}$('note').textContent=S.phase==='glaze'&&S.collection.length<4?'Stardust at 2 pieces · Petal glaze at 4':'No clock. Just a little room to make something.';if(S.phase==='done'&&[2,4].includes(S.collection.length))$('note').textContent=S.collection.length===2?'Stardust glaze unlocked ✦':'Petal glaze unlocked ✿';let c=$('target').getContext('2d'),r=target(S.day);c.clearRect(0,0,170,160);c.fillStyle='#d0d6c5';c.strokeStyle='#7d8c72';c.lineWidth=1.3;c.beginPath();for(let i=0;i<N;i++)c.lineTo(85+r[i]*.52,15+i*1.7);for(let i=N-1;i>=0;i--)c.lineTo(85-r[i]*.52,15+i*1.7);c.closePath();c.fill();c.stroke();c.beginPath();c.ellipse(85,15,r[0]*.52,6,0,0,Math.PI*2);c.fillStyle='#b1bda6';c.fill();c.stroke();}
function vase(c,r,paint,x,y,scale,spin=0,ghost=false,pattern=0){c.save();c.translate(x,y);c.scale(scale,scale);if(ghost){c.setLineDash([4,5]);c.strokeStyle='#fff9';c.lineWidth=1.5;c.beginPath();for(let i=0;i<N;i++)c.lineTo(r[i],i*3);for(let i=N-1;i>=0;i--)c.lineTo(-r[i],i*3);c.closePath();c.stroke();c.restore();return}c.save();c.beginPath();for(let i=0;i<N;i++)c.lineTo(r[i],i*3);for(let i=N-1;i>=0;i--)c.lineTo(-r[i],i*3);c.closePath();c.clip();for(let i=N-1;i>=0;i--){let color=paint[i]>=0?glazes[paint[i]][1]:'#be8865';let g=c.createLinearGradient(-r[i],0,r[i],0);g.addColorStop(0,shade(color,-39));g.addColorStop(.18,shade(color,-8));g.addColorStop(.43,shade(color,34));g.addColorStop(.58,shade(color,18));g.addColorStop(1,shade(color,-44));c.fillStyle=g;c.fillRect(-105,i*3,210,3.5);c.strokeStyle=paint[i]>=0?'#fff1':'#40220d13';c.lineWidth=.6;c.beginPath();c.ellipse(0,i*3,r[i],5,0,0,Math.PI*2);c.stroke();if(paint[i]>=0){c.fillStyle='#fff2';let xx=Math.sin(spin+i*.014)*r[i]*.72;c.fillRect(xx,i*3,2,3.5);if(i%13<2){c.fillStyle='#fff4';c.fillRect(-r[i],i*3,r[i]*2,1)}}}if(pattern){for(let i=4;i<N-3;i+=pattern===1?4:10){for(let j=0;j<10;j++){let a=spin+j*Math.PI/5+i*.23,xx=Math.sin(a)*r[i];if(Math.cos(a)<0)continue;c.globalAlpha=Math.cos(a)*.6;c.fillStyle=pattern===2?'#f5e8ba':'#faf5df';c.beginPath();c.ellipse(xx,i*3,pattern===1?1.2:3,pattern===2?6:2,pattern===2?Math.sin(a):0,0,7);c.fill()}}c.globalAlpha=1}c.restore();let rr=r[0];c.fillStyle=shade(paint[0]>=0?glazes[paint[0]][1]:'#be8865',-28);c.beginPath();c.ellipse(0,0,rr,11,0,0,Math.PI*2);c.fill();c.strokeStyle=shade(paint[0]>=0?glazes[paint[0]][1]:'#be8865',28);c.lineWidth=4;c.stroke();c.fillStyle='#342f2b';c.beginPath();c.ellipse(0,1,Math.max(4,rr-6),7,0,0,Math.PI*2);c.fill();c.restore()}
function shade(hex,v){let n=parseInt(hex.slice(1),16);return`rgb(${clamp((n>>16)+v,0,255)},${clamp((n>>8&255)+v,0,255)},${clamp((n&255)+v,0,255)})`}
let art;new p5(p=>{let w,h,scale,cx,top;p.setup=()=>{let d=$('canvas');p.createCanvas(d.clientWidth,d.clientHeight).parent(d);p.pixelDensity(Math.min(devicePixelRatio,1.5));p.frameRate(45);resize();art={project:(x,i)=>({x:cx+x*scale,y:top+i*3*scale}),metrics:()=>({cx,top,scale}),p};update();install()};function resize(){let d=$('canvas');w=d.clientWidth;h=d.clientHeight;p.resizeCanvas(w,h);scale=Math.min(w/440,h/470);cx=w*.5;top=h*.29}p.windowResized=resize;
 p.draw=()=>{if(paused||document.hidden)return;let dt=Math.min(p.deltaTime/1000,.04);time+=dt;let c=p.drawingContext;c.clearRect(0,0,w,h);let g=c.createLinearGradient(0,0,w,h);g.addColorStop(0,'#e2e7d8');g.addColorStop(1,'#aebaac');c.fillStyle=g;c.fillRect(0,0,w,h);c.fillStyle='#f7f8e943';c.beginPath();c.moveTo(w*.08,0);c.lineTo(w*.47,0);c.lineTo(w*.8,h);c.lineTo(w*.18,h);c.fill();
 // Quiet studio architecture, hanging shelves and a little leafy plant.
 c.strokeStyle='#7b8b7025';c.lineWidth=2;c.beginPath();c.moveTo(0,h*.68);c.lineTo(w,h*.68);c.stroke();c.fillStyle='#a2ae9928';c.fillRect(w*.06,h*.17,w*.2,7);c.fillRect(w*.76,h*.23,w*.19,7);for(let j=0;j<5;j++){let xx=w*.85+Math.sin(j*2)*17,yy=h*.19-j*10;c.strokeStyle='#77896c';c.beginPath();c.moveTo(w*.85,h*.23);c.quadraticCurveTo(xx+10,yy,xx,yy-10);c.stroke();c.fillStyle=j%2?'#839b76':'#98ab88';c.beginPath();c.ellipse(xx,yy-10,10,4,j,0,7);c.fill()}c.fillStyle='#c8a17e';c.fillRect(w*.815,h*.20,w*.07,h*.035);
 let by=top+N*3*scale+15*scale;c.save();c.translate(cx,by);c.scale(scale,scale);c.fillStyle='#344a3520';c.beginPath();c.ellipse(7,35,159,30,0,0,7);c.fill();c.fillStyle='#877e69';c.beginPath();c.ellipse(0,11,139,37,0,0,7);c.fill();c.fillStyle='#c5bca5';c.beginPath();c.ellipse(0,0,139,37,0,0,7);c.fill();for(let j=0;j<5;j++){c.strokeStyle='#827b6333';c.beginPath();c.ellipse(0,0,50+j*20,10+j*5,0,0,7);c.stroke()}for(let j=0;j<8;j++){let a=time*1.7+j*Math.PI/4;c.fillStyle='#fff4';c.beginPath();c.ellipse(Math.cos(a)*120,Math.sin(a)*28,3,1,0,0,7);c.fill()}c.restore();
 if(S.phase==='shape')vase(c,target(S.day),[],cx,top,scale,time,true);vase(c,S.r,S.paint,cx,top,scale,time*1.7,false,S.pattern);if(pointer){let g=c.createRadialGradient(pointer.x,pointer.y,0,pointer.x,pointer.y,30);g.addColorStop(0,'#fff8');g.addColorStop(1,'#fff0');c.fillStyle=g;c.fillRect(pointer.x-30,pointer.y-30,60,60)}
 for(let f of fx){f.x+=f.vx*dt;f.y+=f.vy*dt;f.vy+=40*dt;f.life-=dt;c.globalAlpha=Math.max(0,f.life);c.fillStyle=f.col;c.beginPath();c.ellipse(f.x,f.y,f.size,f.size*.45,time,0,7);c.fill()}c.globalAlpha=1;fx=fx.filter(f=>f.life>0).slice(-100);
 if(S.phase==='fire'){heat+=dt;c.fillStyle=`rgba(124,56,28,${Math.min(.65,heat*.15)})`;c.fillRect(0,0,w,h);c.fillStyle='#fff3dd';c.font='italic 22px Georgia';c.textAlign='center';c.fillText(heat<2?'Warming the kiln…':'Something beautiful is coming.',cx,h*.16);if(heat>3.3)finish()}if(S.phase==='done'){c.textAlign='center';c.fillStyle='#536347';c.font='italic 21px Georgia';c.fillText(score()>=90?'A lovely little masterpiece.':'A little imperfect. Entirely yours.',cx,h*.17)} };
 const canvas=()=>$('canvas').querySelector('canvas');p.mousePressed=()=>false;
 function install(){let el=canvas();el.addEventListener('pointerdown',e=>{if(!['shape','glaze'].includes(S.phase)||paused||$('modal').open||!e.isPrimary)return;let b=el.getBoundingClientRect(),x=e.clientX-b.left,y=e.clientY-b.top;if(y<top-15||y>top+N*3*scale+15)return;checkpoint();pointer={id:e.pointerId,x,y};el.setPointerCapture(e.pointerId);apply(x,y);e.preventDefault()});el.addEventListener('pointermove',e=>{if(pointer?.id!==e.pointerId)return;let b=el.getBoundingClientRect();pointer.x=e.clientX-b.left;pointer.y=e.clientY-b.top;apply(pointer.x,pointer.y);e.preventDefault()});const release=e=>{if(pointer?.id===e.pointerId){pointer=null;save();update()}};el.addEventListener('pointerup',release);el.addEventListener('pointercancel',release)}
 function apply(x,y){let idx=clamp(Math.round((y-top)/(3*scale)),0,N-1),r=clamp(Math.abs(x-cx)/scale,18,99);for(let i=0;i<N;i++){let weight=Math.exp(-(((i-idx)/5)**2));if(S.phase==='shape')S.r[i]+=(r-S.r[i])*weight*.72;else if(weight>.25)S.paint[i]=S.glaze}for(let i=1;i<N-1;i++)S.r[i]=S.r[i]*.8+(S.r[i-1]+S.r[i+1])*.1;if(fx.length<100)for(let j=0;j<2;j++)fx.push({x,y,vx:(Math.random()-.5)*90,vy:-Math.random()*60,life:.5,size:1+Math.random()*3,col:S.phase==='shape'?'#c29170':glazes[S.glaze][1]});if(time-lastSound>.09){note(160+idx*3,.055);lastSound=time}updateMeter()}
});
function updateMeter(){$('match').textContent=`Shape harmony · ${score()}%`;$('meter').style.width=score()+'%'}
function finish(){S.phase='done';let stars=score()>=90?3:score()>=75?2:1;S.collection.push({r:S.r.slice(),paint:S.paint.slice(),name:orders[S.day%12][0],stars,score:score(),pattern:S.pattern});if(S.collection.length>36)S.collection.shift();save();update();[261,329,392,523].forEach((f,i)=>setTimeout(()=>note(f,.7),i*120));let m=art.metrics();for(let j=0;j<75;j++)fx.push({x:m.cx,y:m.top+100*m.scale,vx:(Math.random()-.5)*260,vy:-Math.random()*200,life:1+Math.random(),size:2+Math.random()*3,col:['#eadb9c','#f6efcd','#98b394'][j%3]})}
$('action').onclick=()=>{note();pointer=null;if(S.phase==='shape'){S.phase='glaze';history=[]}else if(S.phase==='glaze'){S.paint=S.paint.map(v=>v<0?S.glaze:v);S.phase='fire';heat=0;history=[]}else if(S.phase==='done'){S.day++;S.phase='shape';S.r=Array(N).fill(65);S.paint=Array(N).fill(-1);S.pattern=0;history=[]}save();update()};$('undo').onclick=()=>{let h=history.pop();if(h){S.r=h.r;S.paint=h.paint;save();update();note(220)}};$('reset').onclick=()=>{if(Date.now()>confirmReset){confirmReset=Date.now()+2500;$('reset').textContent='Really?';setTimeout(()=>$('reset').textContent='Start over',2500);return}S.phase='shape';S.r=Array(N).fill(65);S.paint=Array(N).fill(-1);S.pattern=0;history=[];pointer=null;save();update();$('reset').textContent='Start over'};$('sound').onclick=()=>{S.mute=!S.mute;if(master)master.gain.value=S.mute?0:.15;save();update();note(392)};
$('shelf').onclick=()=>{pointer=null;paused=true;if(master)master.gain.value=0;$('collection').innerHTML='';if(!S.collection.length)$('collection').textContent='Your first piece is waiting on the wheel.';S.collection.slice().reverse().forEach(o=>{let d=document.createElement('div');d.className='card';let c=document.createElement('canvas');c.width=180;c.height=220;vase(c.getContext('2d'),o.r,o.paint,90,20,.75,0,false,o.pattern||0);let title=document.createElement('span');title.textContent=o.name;let stars=document.createElement('b');stars.textContent='✦'.repeat(o.stars)+' · '+o.score+'%';d.append(c,title,stars);$('collection').append(d)});$('modal').showModal()};$('close').onclick=()=>$('modal').close();$('modal').addEventListener('close',()=>{paused=false});document.addEventListener('visibilitychange',()=>{pointer=null;if(master)master.gain.value=0;save()});window.addEventListener('pagehide',save);window.kilnDebug={get state(){return S},target,score,get art(){return art},get paused(){return paused}};




