'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],A=AtlasArt;
const TYPES=['forest','village','water','meadow'],NAMES={forest:'Blossom Grove',village:'Little Village',water:'Quiet Harbour',meadow:'Flower Garden'},ICONS={forest:'♣',village:'⌂',water:'≈',meadow:'✿',links:'↝',placed:'◇'},DIRS=[[1,0],[0,1],[-1,1],[-1,0],[0,-1],[1,-1]],SEASONS=['SPRING','SUMMER','AUTUMN','WINTER'];
const SAVE='little-atlas-v1',META='little-atlas-journal',BEST='little-atlas-best';
const STAMPS=[['✿','First Bloom'],['♣','Old Grove'],['⌂','Windmill'],['⚑','Harbour'],['✧','Night Lights'],['♧','Clocktower'],['❄','Snow Day'],['♡','Grand Garden']];
let run=null,phase='intro',selected=0,preview=null,undoSnap=null,frontier=[],map=new Map(),particles=[],floats=[],rings=[],meta={stamps:[],best:0},audio=null,muted=false,toastTimer,celebrateTimer;
const canvas=$('#world'),ctx=canvas.getContext('2d'),cam={x:0,y:0,scale:1,tx:0,ty:0,ts:1};let W=1,H=1,dpr=1,last=0,acc=0,time=0,renderAt=0,scoreVis=0;
const pointers=new Map();let gesture=null,pinch=null;
const key=(q,r)=>q+','+r,clone=x=>JSON.parse(JSON.stringify(x)),clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),rand=a=>a[Math.floor(Math.random()*a.length)],world=(q,r)=>({x:q*A.R*1.5,y:(r+q*.5)*Math.sqrt(3)*A.R*A.Y}),distance=(q,r)=>Math.max(Math.abs(q),Math.abs(r),Math.abs(q+r));
function safeGet(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}function safeSet(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
meta=safeGet(META,meta);if(!Array.isArray(meta.stamps))meta.stamps=[];
function season(){return Math.floor((run.chapter-1)/2)%4}
function makeTile(type){let roads=rand([[0,3],[0,2],[0,1],[0,2,4],[0,3,5]]);return {type,rot:Math.floor(Math.random()*6),roads:[...roads],seed:Math.floor(Math.random()*1e8),rank:0,landmark:false,born:0}}
function starter(){let layout=[[0,0,'village'],[1,0,'meadow'],[1,-1,'forest'],[0,-1,'forest'],[-1,0,'water'],[-1,1,'meadow'],[0,1,'village']];return layout.map(([q,r,type],n)=>({...makeTile(type),q,r,born:n-7,rank:0,roads:n===0?[0,2,4]:[0,3],rot:n%6}))}
function save(){if(run)safeSet(SAVE,run);safeSet(META,meta)}
function rebuild(){map=new Map(run.board.map(t=>[key(t.q,t.r),t]));let open=new Map();for(let t of run.board)DIRS.forEach(([q,r])=>{q+=t.q;r+=t.r;if(!map.has(key(q,r))&&distance(q,r)<=6)open.set(key(q,r),{q,r})});frontier=[...open.values()]}
function roadAt(t,i){return t.roads.some(n=>(n+t.rot)%6===i)}
function evaluate(q,r,t){let terrain=0,links=0,touch=[],perfect=true;DIRS.forEach(([u,v],i)=>{let n=map.get(key(q+u,r+v));if(!n)return;let same=t.type===n.type,road=roadAt(t,i)&&roadAt(n,(i+3)%6),agree=roadAt(t,i)===roadAt(n,(i+3)%6);terrain+=same?1:0;links+=road?1:0;touch.push({i,n,same,road,agree});if(!same||!agree)perfect=false});let good=terrain+links>=2,multi=good?1+Math.min(run.combo,4)*.15:1;perfect=perfect&&touch.length>=2;let wonder=touch.filter(e=>e.n.special).length*10+(t.special?10:0);return {terrain,links,touch,good,perfect,wonder,score:Math.round((5+terrain*8+links*12+(perfect?20:0)+wonder)*multi)}}
function components(type){let visited=new Set(),groups=[];for(let t of run.board){let k=key(t.q,t.r);if(t.type!==type||visited.has(k))continue;let group=[],stack=[t];visited.add(k);while(stack.length){let a=stack.pop();group.push(a);for(let [u,v] of DIRS){let b=map.get(key(a.q+u,a.r+v));if(b&&b.type===type&&!visited.has(key(b.q,b.r))){visited.add(key(b.q,b.r));stack.push(b)}}}groups.push(group)}return groups}
function biggest(type){return Math.max(0,...components(type).map(g=>g.length))}
function questValue(q){return TYPES.includes(q.kind)?biggest(q.kind):run.stats[q.kind]||0}
function quest(kind,initial=false){let v=TYPES.includes(kind)?biggest(kind):run.stats[kind]||0;return {kind,base:TYPES.includes(kind)?0:v,goal:TYPES.includes(kind)?v+(initial?1:2+Math.min(2,Math.floor(run.chapter/4))):v+(kind==='links'?3+Math.floor(run.chapter/3):4)}}
function questLabel(q){return {forest:'Grove',village:'Village',water:'Harbour',meadow:'Garden',links:'Paths',placed:'New land'}[q.kind]}
function grow(){let events=[];for(let type of TYPES)for(let group of components(type)){let rank=group.length>=10?3:group.length>=6?2:group.length>=3?1:0,old=Math.max(...group.map(t=>t.rank));if(rank>old){let base=group.slice().sort((a,b)=>a.born-b.born)[0];base.landmark=true;run.seeds+=rank===3?3:2;run.score+=rank*30;events.push({type,rank,tile:base});let stamp={forest:1,village:rank===1?2:5,water:3,meadow:rank===3?7:0}[type];unlock(stamp);run.stats.growth++}group.forEach(t=>t.rank=Math.max(t.rank,rank))}return events}
function unlock(n){if(!meta.stamps.includes(n)){meta.stamps.push(n);safeSet(META,meta)}}
function questsAfter(){let done=[],used=[];run.quests=run.quests.map((q,n)=>{if(questValue(q)>=q.goal){run.seeds+=2;run.score+=30;run.stats.quests++;done.push(q.kind);let occupied=used.concat(run.quests.filter((x,j)=>j!==n).map(x=>x.kind));let available=[...TYPES,'links','placed'].filter(k=>!occupied.includes(k));let next=rand(available.filter(t=>TYPES.includes(t)));if(run.stats.quests%3===0&&available.includes('links'))next='links';if(run.stats.quests%5===0&&available.includes('placed'))next='placed';next=next||rand(available);used.push(next);return quest(next)}used.push(q.kind);return q});return done}
function note(kind='place',combo=0){if(muted)return;try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();audio.resume();let notes=kind==='grow'?[523.25,659.25,783.99,1046.5]:kind==='star'?[392,523.25,659.25,783.99,1046.5]:kind==='tap'?[392]:[329.63,392,440,523.25,659.25].slice(Math.min(4,combo),Math.min(4,combo)+1);notes.forEach((f,n)=>{let o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+n*.095;o.type='sine';o.frequency.value=f;o.connect(g);g.connect(audio.destination);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.045,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+.6);o.start(t);o.stop(t+.65)})}catch{}}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2300)}
function celebrate(title,sub){let el=$('#celebration');el.innerHTML='<strong>'+title+'</strong><small>'+sub+'</small>';el.classList.remove('show');void el.offsetWidth;el.classList.add('show');clearTimeout(celebrateTimer);celebrateTimer=setTimeout(()=>el.classList.remove('show'),2400)}
function burst(t,n=16,colour='#f7d495'){let p=world(t.q,t.r);for(let i=0;i<n;i++){let a=Math.random()*A.TAU,s=14+Math.random()*44;particles.push({x:p.x,y:p.y-13,vx:Math.cos(a)*s,vy:Math.sin(a)*s-45,life:1+Math.random()*.6,max:1.6,color:colour,size:1.7+Math.random()*2})}rings.push({x:p.x,y:p.y,life:.75});if(particles.length>160)particles.splice(0,particles.length-160)}
function float(t,text,color='#f7f7d9'){let p=world(t.q,t.r);floats.push({x:p.x,y:p.y-26,text,life:1.4,color})}
function chapterAdvance(){let count=0;while(run.score>=run.target){run.chapter++;run.floor=run.target;run.target+=Math.round(100+run.chapter*35);run.seeds+=2;count++;unlock(run.chapter===2?0:run.chapter>=7?6:run.chapter>=5?4:0)}if(count){note('star');celebrate(SEASONS[season()].toLowerCase()+' wonders','CHAPTER '+run.chapter+' · +'+count*2+' TILES');AtlasArt.clear()}return count}
function nextType(){let types=TYPES.filter(t=>run.hand.filter(c=>c.type===t).length<2);return rand(types.length?types:TYPES)}
function place(){if(phase!=='play'||!preview)return;let {q,r}=preview;if(map.has(key(q,r))||!frontier.some(p=>p.q===q&&p.r===r)){toast('Find a space next to your island');return}undoSnap=clone(run);let t={...clone(run.hand[selected]),q,r,born:run.stats.placed+1},result=evaluate(q,r,t);t.animAt=time;run.board.push(t);if(run.mode!=='zen')run.seeds--;run.score+=result.score;run.stats.placed++;run.stats.links+=result.links;run.combo=result.good?run.combo+1:0;if(result.perfect){run.seeds++;run.stats.perfect++;float(t,'PERFECT +1 ❧','#fff0b3')}else float(t,'+'+result.score,result.good?'#fff1b8':'#f4f6dc');if(run.combo>1&&run.combo%3===0){run.seeds++;float(t,'CHAIN +1 ❧','#f9eac3')}
 rebuild();let grown=grow(),completed=questsAfter(),chap=chapterAdvance();run.seeds=Math.min(24,run.seeds);run.hand[selected]=makeTile(nextType());if(run.chapter>=2&&run.stats.placed%5===0)run.hand[selected].special=true;preview=null;burst(t,result.good?22:10,result.perfect?'#f6d993':'#f1c2b6');if(grown.length){let g=grown[0];burst(g.tile,24,'#f5dab1');if(!chap)celebrate(growthName(g.type,g.rank),'+ '+(g.rank*30)+' POINTS · NEW WONDER');note('grow');if(navigator.vibrate)navigator.vibrate(15)}else{note('place',Math.min(4,run.combo));if(result.perfect&&navigator.vibrate)navigator.vibrate(10)}if(completed.length&&!grown.length&&!chap)toast('Little wish granted · +'+completed.length*2+' tiles');if(run.mode!=='zen'){meta.best=Math.max(meta.best||0,run.score)}save();renderUI();maybeFollow(t);if(!frontier.length){setTimeout(()=>travelPrompt(true),800)}else if(run.seeds<=0&&run.mode!=='zen'){phase='end';setTimeout(()=>{if(phase==='end')endScreen()},1100)}}
function growthName(type,rank){return {forest:['A grove awakens','The old tree blooms','A woodland sanctuary'],village:['A windmill rises','The village finds its clock','A little café opens'],water:['A harbour comes alive','A lighthouse shines','A sailing sanctuary'],meadow:['A fountain blossoms','The garden gets a gazebo','A grand flower garden']}[type][rank-1]}
function renderUI(){if(!run)return;$('#seeds').textContent=run.mode==='zen'?'∞':run.seeds;$('#best').textContent=run.mode==='zen'?'FREE BUILD':'BEST '+(meta.best||0);$('#chapter').textContent=SEASONS[season()]+' · '+run.chapter;$('#progress-text').textContent=(run.score-run.floor)+' / '+(run.target-run.floor);$('#progress').style.width=clamp((run.score-run.floor)/(run.target-run.floor)*100,0,100)+'%';$('#combo').textContent=run.combo>=2?'✦ '+run.combo+' LINK CHAIN':'MATCH EDGES · GROW WONDERS';$('#world-name').textContent=['PETAL COAST','HONEY HOLLOW','LANTERN BAY','MAPLE REACH','FROST HARBOUR'][(run.island-1)%5];$('#world-tip').textContent=run.stats.placed<2?'Tap a space. Rotate. Place.':'Drag to explore · Pinch to zoom';$('#undo').disabled=!undoSnap;$('#shuffle').disabled=phase!=='play'||run.mode!=='zen'&&run.seeds<3;
 $('#quests').innerHTML=run.quests.map(q=>{let v=questValue(q)-q.base,g=q.goal-q.base;return '<button class="quest" data-quest="'+q.kind+'"><span class="q-icon">'+ICONS[q.kind]+'</span><div><strong>'+questLabel(q)+'</strong><small>+2 tiles</small></div><span class="q-progress">'+Math.min(v,g)+'/'+g+'</span></button>'}).join('');$$('[data-quest]').forEach(b=>b.onclick=()=>{let q=run.quests.find(t=>t.kind===b.dataset.quest),msg=TYPES.includes(q.kind)?'Connect '+q.goal+' '+questLabel(q).toLowerCase()+' tiles.':q.kind==='links'?'Join '+(q.goal-q.base)+' golden path edges.':'Place '+(q.goal-q.base)+' new tiles.';toast(msg)});
 $('#deck').innerHTML=run.hand.map((t,n)=>'<button class="tile-card '+(n===selected?'selected':'')+'" data-card="'+n+'" aria-label="Choose '+NAMES[t.type]+'"><small>'+(t.special?'✦':ICONS[t.type])+'</small><canvas aria-hidden="true"></canvas><b>'+(t.special?{forest:'Ancient Grove',village:'Windmill',water:'Lighthouse',meadow:'Gazebo'}[t.type]:NAMES[t.type])+'</b></button>').join('');$$('[data-card]').forEach(b=>{A.card(b.querySelector('canvas'),run.hand[+b.dataset.card],season());b.onclick=()=>{if(phase!=='play')return;selected=+b.dataset.card;note('tap');renderUI()}});updatePreview();let sail=$('#sail');if(!sail){sail=document.createElement('button');sail.id='sail';sail.textContent='⚑';sail.title='Explore a new island';sail.setAttribute('aria-label','Explore a new island');$('.view-controls').append(sail);sail.onclick=()=>travelPrompt(false)}sail.classList.toggle('hidden',run.board.length<28)}
function updatePreview(){let valid=phase==='play'&&preview&&!map.has(key(preview.q,preview.r));$('#place').disabled=!valid;$('#placement-tip').classList.toggle('hidden',!valid);if(valid){let e=evaluate(preview.q,preview.r,run.hand[selected]);$('#place').innerHTML='Place +'+e.score+' <span>➜</span>';$('#placement-tip').textContent=(e.perfect?'✦ Perfect · ':e.terrain+e.links>=2?'✧ Lovely links · ':'')+'+'+e.score+(e.perfect?' · +1 tile':'')}else $('#place').innerHTML='Choose a space <span>➜</span>'}
function newWorld(mode){run={mode,board:starter(),hand:['forest','village','water'].map(makeTile),seeds:12,score:0,chapter:1,floor:0,target:100,island:1,combo:0,stats:{placed:0,links:0,perfect:0,growth:0,quests:0},quests:[]};rebuild();run.quests=[quest('forest',true),quest('links'),quest('placed')];selected=0;preview=null;undoSnap=null;particles=[];floats=[];phase='play';closeModal();renderUI();fit();scoreVis=0;save();toast('Choose a tile. Tap a glowing hex. Make it yours.')}
function undo(){if(!undoSnap)return;run=undoSnap;undoSnap=null;phase='play';preview=null;particles=[];floats=[];rings=[];rebuild();renderUI();closeModal();save();note('tap');toast('One little step back.')}
function rotate(){if(phase!=='play')return;run.hand[selected].rot=(run.hand[selected].rot+1)%6;note('tap');renderUI();save()}
function shuffle(){if(phase!=='play'||run.mode!=='zen'&&run.seeds<3)return;undoSnap=null;if(run.mode!=='zen')run.seeds-=2;run.hand=TYPES.slice().sort(()=>Math.random()-.5).slice(0,3).map(makeTile);note('tap');renderUI();save();toast('Fresh possibilities · '+(run.mode==='zen'?'free':'−2 tiles'))}
function modal(html){$('#modal-card').innerHTML=html;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}
function intro(){phase='intro';modal('<div class="eyebrow">A TINY WORLD. A LITTLE WONDER.</div><h1>Little Atlas</h1><canvas class="intro-art" id="intro-art" width="540" height="330" aria-label="Miniature blossom village"></canvas><p>Fit the pieces. Follow the paths.<br>Watch your little world come alive.</p><div class="mode-row"><button class="primary" id="start">Grow an atlas</button><button id="zen">Free build</button></div><p style="font-size:9px;margin-bottom:0">NO TIMER · ORIGINAL MINIATURE ART · TOUCH FRIENDLY</p>');let c=$('#intro-art').getContext('2d');c.scale(2,2);let decor=[{...makeTile('forest'),q:0,r:-1,rank:1},{...makeTile('village'),q:0,r:0,rank:1,landmark:true},{...makeTile('meadow'),q:1,r:-1,rank:1,landmark:true},{...makeTile('water'),q:-1,r:0,rank:1}];decor.sort((a,b)=>world(a.q,a.r).y-world(b.q,b.r).y).forEach(t=>{let p=world(t.q,t.r);A.draw(c,t,137+p.x*.78,126+p.y*.78,.78,0,0)});$('#start').onclick=()=>newWorld('challenge');$('#zen').onclick=()=>newWorld('zen')}
function endScreen(){modal('<div class="eyebrow">YOUR LITTLE WORLD, PRESERVED</div><h1>'+run.score+' points</h1><p>'+run.stats.placed+' new tiles · '+run.stats.growth+' growing wonders<br>Every atlas begins with a little possibility.</p><button class="primary" id="again">A new atlas</button><div class="close-row"><button id="keep">Keep building freely</button> '+(undoSnap?'<button id="take-back">Undo last tile</button>':'')+'</div><p style="font-size:10px">Your island stays saved until you start another.</p>');$('#again').onclick=intro;$('#keep').onclick=()=>{run.mode='zen';phase='play';closeModal();renderUI();save()};if($('#take-back'))$('#take-back').onclick=undo}
function travelPrompt(forced){modal('<div class="eyebrow">THE HORIZON IS CALLING</div><h2>A fresh little shore?</h2><p>Keep your score and your collection.<br>Start a new island with 4 extra tiles.</p><button class="primary" id="travel">Sail onward</button>'+(!forced?' <button id="stay">Stay here</button>':''));$('#travel').onclick=()=>{run.island++;run.board=starter();run.seeds=Math.min(45,run.seeds+4);run.combo=0;run.quests=[];undoSnap=null;preview=null;rebuild();run.quests=[quest('village',true),quest('water',true),quest('placed')];phase='play';closeModal();renderUI();fit();save();celebrate('A little new beginning','ISLAND '+run.island+' · +4 TILES')};if($('#stay'))$('#stay').onclick=closeModal}
function help(){modal('<div class="eyebrow">THREE LITTLE STEPS</div><h2>A world that rewards care</h2><div class="guide-row"><span>1</span><div><b>Choose & fit</b><small>Choose a miniature tile. Tap an empty hex.<br>Rotate its paths, then Place.</small></div></div><div class="guide-row"><span>2</span><div><b>Make lovely links</b><small>Matching terrain: +8. Joined paths: +12.<br>Several good placements build a chain.</small></div></div><div class="guide-row"><span>3</span><div><b>Watch it grow</b><small>Connect 3, 6, then 10 tiles of one terrain.<br>Wishes and wonders award more tile charges.</small></div></div><p>Drag to explore. Pinch or scroll to zoom.<br>Press R to rotate, Space to place, Z to undo.<br>✦ Wonder tiles add +10 for nearby placements.</p><button class="primary" id="close">Let it bloom</button> <button id="field-journal">Field journal</button>');$('#close').onclick=closeModal;$('#field-journal').onclick=journal}
function journal(){modal('<div class="eyebrow">LITTLE SOUVENIRS</div><h2>Your field journal</h2><div class="stamps">'+STAMPS.map(([icon,name],n)=>'<div class="stamp '+(meta.stamps.includes(n)?'':'locked')+'"><span>'+icon+'</span><small>'+name+'</small></div>').join('')+'</div><p>'+meta.stamps.length+' / '+STAMPS.length+' collected<br>Grow different landscapes and discover seasons.</p><button class="primary" id="close">Back to my world</button>');$('#close').onclick=closeModal}
function cubeRound(q,r){let s=-q-r,x=Math.round(q),z=Math.round(r),y=Math.round(s);if(Math.abs(x-q)>Math.abs(z-r)&&Math.abs(x-q)>Math.abs(y-s))x=-z-y;else if(Math.abs(z-r)>Math.abs(y-s))z=-x-y;return{q:x,r:z}}
function hit(x,y){let wx=(x-W/2)/cam.scale+cam.x,wy=(y-H/2)/cam.scale+cam.y,q=(2/3*wx)/A.R,r=(-wx/3+Math.sqrt(3)/3*wy/A.Y)/A.R;return cubeRound(q,r)}
function local(e){let r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
canvas.onpointerdown=e=>{if(phase!=='play'||!$('#modal').classList.contains('hidden'))return;e.preventDefault();canvas.setPointerCapture(e.pointerId);let p=local(e);pointers.set(e.pointerId,p);if(pointers.size===1)gesture={sx:p.x,sy:p.y,cx:cam.tx,cy:cam.ty,moved:false,blocked:false};if(pointers.size===2){let [a,b]=[...pointers.values()],mx=(a.x+b.x)/2,my=(a.y+b.y)/2;pinch={dist:Math.hypot(a.x-b.x,a.y-b.y),scale:cam.scale,anchor:{x:(mx-W/2)/cam.scale+cam.x,y:(my-H/2)/cam.scale+cam.y}};gesture.blocked=true}};
canvas.onpointermove=e=>{let p=local(e);if(pointers.has(e.pointerId)){pointers.set(e.pointerId,p);if(pointers.size===2&&pinch){let [a,b]=[...pointers.values()],mx=(a.x+b.x)/2,my=(a.y+b.y)/2;cam.ts=clamp(pinch.scale*Math.hypot(a.x-b.x,a.y-b.y)/pinch.dist,.3,2.8);cam.tx=pinch.anchor.x-(mx-W/2)/cam.ts;cam.ty=pinch.anchor.y-(my-H/2)/cam.ts;cam.x=cam.tx;cam.y=cam.ty;cam.scale=cam.ts;preview=null;updatePreview();return}if(gesture&&!gesture.blocked){if(Math.hypot(p.x-gesture.sx,p.y-gesture.sy)>6)gesture.moved=true;if(gesture.moved){cam.tx=gesture.cx-(p.x-gesture.sx)/cam.scale;cam.ty=gesture.cy-(p.y-gesture.sy)/cam.scale;preview=null;updatePreview()}}}else if(e.pointerType==='mouse'&&phase==='play'){let h=hit(p.x,p.y);if(frontier.some(t=>t.q===h.q&&t.r===h.r)){preview=h;updatePreview()}}};
canvas.onpointerup=e=>{let p=local(e),g=gesture;pointers.delete(e.pointerId);if(!pointers.size){pinch=null;gesture=null;if(g&&!g.moved&&!g.blocked){let h=hit(p.x,p.y);if(frontier.some(t=>t.q===h.q&&t.r===h.r)){if(preview&&preview.q===h.q&&preview.r===h.r&&e.pointerType!=='mouse')place();else{preview=h;updatePreview();note('tap')}}else if(map.has(key(h.q,h.r))){let t=map.get(key(h.q,h.r));toast(NAMES[t.type]+(t.landmark?' · '+growthName(t.type,t.rank):' · '+biggest(t.type)+' connected'))}}}};
canvas.onpointercancel=e=>{pointers.delete(e.pointerId);if(!pointers.size){gesture=null;pinch=null}};
canvas.addEventListener('wheel',e=>{e.preventDefault();let p=local(e),wx=(p.x-W/2)/cam.scale+cam.x,wy=(p.y-H/2)/cam.scale+cam.y;cam.ts=clamp(cam.ts*Math.exp(-e.deltaY*.0014),.3,2.8);cam.tx=wx-(p.x-W/2)/cam.ts;cam.ty=wy-(p.y-H/2)/cam.ts},{passive:false});
function bounds(includeFrontier=false){let pts=run.board.map(t=>world(t.q,t.r));if(includeFrontier)pts.push(...frontier.map(t=>world(t.q,t.r)));return{minx:Math.min(...pts.map(t=>t.x))-57,maxx:Math.max(...pts.map(t=>t.x))+57,miny:Math.min(...pts.map(t=>t.y))-85,maxy:Math.max(...pts.map(t=>t.y))+49}}
function fit(){if(!run)return;let b=bounds(run.board.length<15);cam.tx=(b.minx+b.maxx)/2;cam.ty=(b.miny+b.maxy)/2;cam.ts=clamp(Math.min((W-44)/(b.maxx-b.minx),(H-60)/(b.maxy-b.miny)),.35,1.3);cam.x=cam.tx;cam.y=cam.ty;cam.scale=cam.ts}
function maybeFollow(t){let p=world(t.q,t.r),sx=(p.x-cam.tx)*cam.ts+W/2,sy=(p.y-cam.ty)*cam.ts+H/2;if(sx<50||sx>W-50||sy<60||sy>H-60){cam.tx=p.x;cam.ty=p.y}}
function resize(){let r=canvas.getBoundingClientRect();W=Math.max(1,r.width);H=Math.max(1,r.height);dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);if(run){fit();$$('[data-card]').forEach(b=>A.card(b.querySelector('canvas'),run.hand[+b.dataset.card],season()))}}
new ResizeObserver(resize).observe($('#world-wrap'));
function backdrop(c,w,h){let g=c.createLinearGradient(0,0,0,h);let s=run?season():0;g.addColorStop(0,['#e8efdd','#e6ecd6','#f0e7d2','#e4eae5'][s]);g.addColorStop(1,['#9bcac4','#93c3c5','#c0cfbd','#afc8d0'][s]);c.fillStyle=g;c.fillRect(0,0,w,h);A.ellipse(c,w*.76,h*.17,27,27,'#fff6d53a');for(let k=0;k<4;k++){let x=(w*(.14+k*.27)+Math.sin(time*.025+k)*12)%(w+150),y=h*(.13+(k%2)*.23);A.ellipse(c,x,y,47,8,'#fffce527');A.ellipse(c,x+24,y+1,32,6,'#fffce52d')}for(let k=0;k<23;k++){let x=(k*173.7+17)%w,y=h*.46+(k*67.3)%(h*.52),s=4+((k*7)%18);c.globalAlpha=.13+.06*Math.sin(time*.7+k);A.line(c,[[x,y],[x+s,y-.5],[x+s+4,y]],'#e8f5df',1);c.globalAlpha=1}c.globalAlpha=.16;A.poly(c,[[w*.02,h*.32],[w*.1,h*.28],[w*.17,h*.32],[w*.1,h*.35]],'#6d9c8c');A.poly(c,[[w*.78,h*.6],[w*.89,h*.56],[w*.97,h*.6],[w*.89,h*.64]],'#7da992');c.globalAlpha=1}
function drawScene(c,w,h,camera,photo=false){backdrop(c,w,h);if(!run)return;c.save();c.translate(w/2,h/2);c.scale(camera.scale,camera.scale);c.translate(-camera.x,-camera.y);
 if(!photo){for(let p of frontier){let v=world(p.q,p.r);c.save();c.translate(v.x,v.y+4);c.globalAlpha=.42;A.poly(c,A.hex(), '#d8edc022', '#f7f5d799',1);c.setLineDash([2,5]);A.poly(c,A.hex(48),null,'#698e7c77',.7);c.setLineDash([]);c.globalAlpha=.5;A.line(c,[[-3,0],[3,0]],'#658c78',1);A.line(c,[[0,-3],[0,3]],'#658c78',1);c.restore()}}
 let board=run.board.slice().sort((a,b)=>world(a.q,a.r).y-world(b.q,b.r).y||a.q-b.q);for(let t of board){let p=world(t.q,t.r),age=time-(t.animAt??-10),s=1;if(age>=0&&age<.5)s=1+Math.sin(age*9)*.07*(1-age*2);A.draw(c,t,p.x,p.y,s,season(),time,1,true)}
 if(preview&&!photo&&phase==='play'){let t={...run.hand[selected],q:preview.q,r:preview.r},p=world(t.q,t.r),ev=evaluate(t.q,t.r,t);A.draw(c,t,p.x,p.y-4,1+.018*Math.sin(time*4),season(),time,.76,false);c.save();c.translate(p.x,p.y-4);A.poly(c,A.hex(53),null,ev.perfect?'#faf0ba':'#f7fae0',2);for(let edge of ev.touch){let i=edge.i,a=i*A.TAU/6,b=(i+1)*A.TAU/6;A.line(c,[[Math.cos(a)*52,Math.sin(a)*52*A.Y],[Math.cos(b)*52,Math.sin(b)*52*A.Y]],edge.road?'#edc46d':edge.same?'#ebf4c2':'#d6c7a455',3)}c.restore()}
 if(!photo){for(let r of rings){c.globalAlpha=r.life/.75;A.ellipse(c,r.x,r.y,25+(1-r.life/.75)*70,10+(1-r.life/.75)*26,'#f5e3a922')}c.globalAlpha=1;for(let p of particles){c.globalAlpha=Math.min(1,p.life);A.ellipse(c,p.x,p.y,p.size,p.size*.65,p.color)}c.globalAlpha=1;for(let f of floats){c.save();c.globalAlpha=Math.min(1,f.life*1.6);c.font='bold 14px Georgia';c.textAlign='center';c.lineWidth=3;c.strokeStyle='#578575aa';c.strokeText(f.text,f.x,f.y);c.fillStyle=f.color;c.fillText(f.text,f.x,f.y);c.restore()}}
 c.restore(); // Tiny birds cross the horizon rather than obstructing the tile choices.
 for(let k=0;k<3;k++){let bx=w*.17+((time*8+k*51)%(w*.66)),by=h*.16+Math.sin(time*.6+k)*6;c.globalAlpha=.32;A.line(c,[[bx-4,by+Math.sin(time*4+k)*2],[bx,by],[bx+4,by+Math.sin(time*4+k)*2]],'#557c71',1);c.globalAlpha=1}}
function step(dt){time+=dt;for(let p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=55*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);for(let f of floats){f.y-=20*dt;f.life-=dt}floats=floats.filter(f=>f.life>0);for(let r of rings)r.life-=dt;rings=rings.filter(r=>r.life>0);cam.x+=(cam.tx-cam.x)*Math.min(1,dt*12);cam.y+=(cam.ty-cam.y)*Math.min(1,dt*12);cam.scale+=(cam.ts-cam.scale)*Math.min(1,dt*12)}
function frame(now){let dt=Math.min(.1,(now-last)/1000);last=now;if(!document.hidden){acc+=dt;while(acc>=1/60){step(1/60);acc-=1/60}if(now-renderAt>=1000/(innerWidth<700?30:60)){renderAt=now;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,W,H);drawScene(ctx,W,H,cam);if(run&&Number.isFinite(run.score)&&scoreVis!==run.score){scoreVis+=Math.sign(run.score-scoreVis)*Math.max(1,Math.ceil(Math.abs(run.score-scoreVis)*.16));if(Math.abs(run.score-scoreVis)<2)scoreVis=run.score;$('#score').textContent=scoreVis}}}requestAnimationFrame(frame)}requestAnimationFrame(frame);
function photo(){if(!run)return;let out=document.createElement('canvas');out.width=1440;out.height=1000;let c=out.getContext('2d'),b=bounds(),s=Math.min(1250/(b.maxx-b.minx),780/(b.maxy-b.miny));AtlasArt.quality(Math.min(3,Math.max(1.5,s*1.25)));drawScene(c,1440,1000,{x:(b.minx+b.maxx)/2,y:(b.miny+b.maxy)/2,scale:s},true);AtlasArt.quality(1.5);c.fillStyle='#48715e';c.font='italic 40px Georgia';c.fillText('Little Atlas',60,77);c.font='12px sans-serif';c.fillText($('#world-name').textContent+'  ·  '+run.score+' POINTS',63,104);c.fillStyle='#658b76';c.font='11px sans-serif';c.fillText('A WORLD WORTH GROWING',62,948);out.toBlob(blob=>{let url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='little-atlas-island-'+run.island+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)});toast('Your little postcard is ready.')}
$('#place').onclick=place;$('#rotate').onclick=rotate;$('#undo').onclick=undo;$('#shuffle').onclick=shuffle;$('#fit').onclick=fit;$('#zoom-in').onclick=()=>cam.ts=clamp(cam.ts*1.25,.3,2.8);$('#zoom-out').onclick=()=>cam.ts=clamp(cam.ts/1.25,.3,2.8);$('#photo').onclick=photo;$('#sound').onclick=()=>{muted=!muted;$('#sound').textContent=muted?'♫̸':'♪';$('#sound').setAttribute('aria-label',muted?'Enable sound':'Mute sound');if(!muted)note('tap')};$('#help').onclick=help;$('#journal').onclick=journal;$('#new').onclick=()=>{modal('<h2>A new little beginning?</h2><p>Your collection stays. Your current island will be replaced.</p><button class="primary" id="confirm">New atlas</button> <button id="close">Stay here</button>');$('#confirm').onclick=intro;$('#close').onclick=closeModal};$('.logo').onclick=e=>{e.preventDefault();fit()};window.addEventListener('keydown',e=>{if(phase!=='play'||!$('#modal').classList.contains('hidden'))return;if(e.key.toLowerCase()==='r')rotate();if(e.code==='Space'){e.preventDefault();place()}if(e.key.toLowerCase()==='z')undo();if(e.key==='Escape'){preview=null;updatePreview()}});document.addEventListener('visibilitychange',()=>{last=performance.now();acc=0});
let raw=safeGet(SAVE,null);if(raw&&Array.isArray(raw.board)&&raw.board.length&&raw.board.every(t=>TYPES.includes(t.type))&&raw.hand?.length===3&&raw.quests?.length===3){run=raw;phase=run.seeds<=0&&run.mode!=='zen'?'end':'play';rebuild();renderUI();resize();scoreVis=run.score;$('#score').textContent=run.score;if(phase==='end')endScreen();else{modal('<div class="eyebrow">YOUR WORLD IS WAITING</div><h1>Welcome back</h1><p>'+run.score+' points · '+run.board.length+' little tiles</p><button class="primary" id="resume">Let it grow</button> <button id="fresh">New atlas</button>');$('#resume').onclick=closeModal;$('#fresh').onclick=intro}}else{run={board:starter(),hand:['forest','village','water'].map(makeTile),chapter:1};rebuild();resize();intro()}
window.__atlas={get run(){return run},get phase(){return phase},get preview(){return preview},get camera(){return cam},get dimensions(){return{W,H}},get frontier(){return frontier},evaluate,world,components,hit};


