(function(root){'use strict';const names=['The first night','Creative department','Coffee catastrophe','The late meeting','Accounts & crumbs','Greenhouse overtime','The midnight archive','The last light'];const layouts=[[[3,3],[7,3],[3,7],[7,7]],[[2,4],[7,4],[3,8],[7,8],[2,10]],[[3,3],[7,3],[3,6],[7,9],[3,10]],[[2,3],[6,3],[8,6],[2,8],[6,10]],[[3,2],[7,4],[2,6],[7,8],[3,10]],[[2,3],[7,3],[4,6],[2,9],[7,10]],[[2,3],[7,3],[3,6],[7,8],[2,10]],[[3,2],[7,4],[2,6],[7,7],[4,10]]];const cache=[];
const point=p=>({x:(p%12)*40+20,y:Math.floor(p/12)*40+20});
function path(n,a,b){const blocked=config(n).blocked,q=[a],prev=new Map([[a,null]]);for(let i=0;i<q.length;i++){const p=q[i];if(p===b){const out=[];let j=b;while(j!==null){out.push(j);j=prev.get(j);}return out.reverse();}for(const d of[-12,12,-1,1]){const j=p+d;if(j<0||j>=168||Math.abs(d)===1&&Math.floor(j/12)!==Math.floor(p/12)||blocked.includes(j)||prev.has(j))continue;prev.set(j,p);q.push(j);}}return[];}
function config(n){if(cache[n])return cache[n];const blocked=[];for(let p=0;p<168;p++)if(p%12===0||p%12===11||p<12||p>=156)blocked.push(p);const desks=layouts[n];for(const[x,y]of desks){blocked.push(y*12+x,y*12+x+1);}const free=Array.from({length:168},(_,i)=>i).filter(p=>!blocked.includes(p)),c={blocked,desks,free,exit:150,patches:[],keeps:[],routes:[]};cache[n]=c;let seed=971+n*199;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};const shuffled=free.filter(p=>p!==150&&p!==138).map(p=>({p,k:rand()})).sort((a,b)=>a.k-b.k).map(a=>a.p);c.patches=shuffled.slice(0,12+n);c.keeps=shuffled.slice(25,28);const corners=[26,33,141,134];for(let i=0;i<Math.min(4,1+Math.floor((n+1)/2));i++){const stops=[corners[(i+n)%4],corners[(i+n+2)%4],corners[(i+n+1)%4]];let route=[];for(let j=0;j<3;j++)route.push(...path(n,stops[j],stops[(j+1)%3]).slice(0,-1));c.routes.push(route);}return c;}
function fresh(n=0){const c=config(n),p=point(c.exit);return{v:1,n,t:0,player:{...p,face:-Math.PI/2,hidden:false,walking:false},dirt:c.patches.map((p,i)=>({...point(p),progress:0,type:i%3,id:i})),keeps:[],npc:c.routes.map((r,i)=>({...point(r[0]),at:1,face:0,alert:0,stun:0,cool:0})),howl:0,alarms:0,spills:0,combo:0,lastClean:-10,score:0,won:false,events:[]};}
function emit(s,type,x,y,extra={}){s.events.push({type,x,y,...extra});s.events=s.events.slice(-40);}
function clear(s){return s.dirt.every(d=>d.progress>=1);}
function solid(n,x,y,r=12){return config(n).blocked.some(p=>{const q=point(p);return x+r>q.x-20&&x-r<q.x+20&&y+r>q.y-20&&y-r<q.y+20;});}
function sight(s,a){const p=s.player,dx=p.x-a.x,dy=p.y-a.y,dist=Math.hypot(dx,dy);if(dist>110+s.n*6||p.hidden)return false;if(dist>25&&Math.cos(Math.atan2(dy,dx)-a.face)<.65)return false;for(let i=14;i<dist-10;i+=12)if(solid(s.n,a.x+dx*i/dist,a.y+dy*i/dist,0))return false;return true;}
function spill(s,a){if(s.spills>=6)return;const p=Math.floor(a.y/40)*12+Math.floor(a.x/40),q=point(p);if(config(s.n).blocked.includes(p))return;s.dirt.push({...q,progress:0,type:0,id:100+s.spills});s.spills++;emit(s,'spill',q.x,q.y);}
function howl(s){if(s.won||s.howl>0)return false;s.howl=6;emit(s,'howl',s.player.x,s.player.y);s.npc.forEach(a=>{if(Math.hypot(a.x-s.player.x,a.y-s.player.y)<145){a.stun=3.8;a.alert=0;spill(s,a);}});return true;}
function step(s,dt,input={}){if(s.won)return;dt=Math.min(1/30,Math.max(0,dt));s.t+=dt;s.howl=Math.max(0,s.howl-dt);const p=s.player,x=Number.isFinite(input.x)?input.x:0,y=Number.isFinite(input.y)?input.y:0,len=Math.hypot(x,y),v=(input.hide?67:155)*dt/Math.max(1,len);p.hidden=!!input.hide;p.walking=len>.1;if(len>.1)p.face=Math.atan2(y,x);let xx=p.x+x*v,yy=p.y+y*v;if(!solid(s.n,xx,p.y))p.x=xx;if(!solid(s.n,p.x,yy))p.y=yy;
if(!p.hidden)for(const d of s.dirt){if(d.progress>=1||Math.hypot(p.x-d.x,p.y-d.y)>29)continue;d.progress=Math.min(1,d.progress+dt*2.7);if(d.progress===1){s.combo=s.t-s.lastClean<2?Math.min(9,s.combo+1):1;s.lastClean=s.t;s.score+=100+25*s.combo;emit(s,'clean',d.x,d.y,{combo:s.combo});}}
config(s.n).keeps.forEach((q,i)=>{const a=point(q);if(!s.keeps.includes(i)&&Math.hypot(p.x-a.x,p.y-a.y)<24){s.keeps.push(i);s.score+=250;emit(s,'keep',a.x,a.y);}});
s.npc.forEach((a,i)=>{a.cool=Math.max(0,a.cool-dt);if(a.stun>0){a.stun=Math.max(0,a.stun-dt);a.alert=0;return;}const r=config(s.n).routes[i],target=point(r[a.at]),dx=target.x-a.x,dy=target.y-a.y,dist=Math.hypot(dx,dy),speed=31+s.n*2;if(dist<2){a.at=(a.at+1)%r.length;}else{a.x+=dx/dist*Math.min(dist,speed*dt);a.y+=dy/dist*Math.min(dist,speed*dt);a.face=Math.atan2(dy,dx);}a.alert=Math.max(0,Math.min(1,a.alert+(sight(s,a)?dt*1.3:-dt*2)));if(a.alert>=1&&a.cool<=0){s.alarms++;a.cool=8;a.alert=0;a.stun=1.6;spill(s,a);emit(s,'notice',a.x,a.y);}});
if(clear(s)&&Math.hypot(p.x-point(config(s.n).exit).x,p.y-point(config(s.n).exit).y)<24){s.won=true;emit(s,'win',p.x,p.y);}}
function stars(s){return s.won?1+(s.keeps.length===3?1:0)+(s.alarms<=2?1:0):0;}
function restore(a){if(!a||a.v!==1||!Number.isInteger(a.n)||a.n<0||a.n>7||!Number.isFinite(a.t)||a.t<0||!a.player||!Number.isFinite(a.player.x+a.player.y+a.player.face)||a.player.x<32||a.player.x>448||a.player.y<32||a.player.y>528||solid(a.n,a.player.x,a.player.y)||!Array.isArray(a.dirt)||a.dirt.length<config(a.n).patches.length||a.dirt.length>config(a.n).patches.length+6||a.dirt.some(d=>!d||!Number.isFinite(d.x+d.y+d.progress)||d.progress<0||d.progress>1||d.x<0||d.x>480||d.y<0||d.y>560)||!Array.isArray(a.keeps)||a.keeps.some(i=>![0,1,2].includes(i))||new Set(a.keeps).size!==a.keeps.length||!Array.isArray(a.npc)||a.npc.length!==config(a.n).routes.length||a.npc.some((d,i)=>!d||!Number.isFinite(d.x+d.y+d.face+d.alert+d.stun+d.cool)||!Number.isInteger(d.at)||d.at<0||d.at>=config(a.n).routes[i].length)||!Number.isInteger(a.spills)||a.spills<0||a.spills>6||!Number.isInteger(a.alarms)||a.alarms<0||!Number.isFinite(a.howl)||a.howl<0||a.howl>6||!Number.isInteger(a.score)||a.score<0||!Number.isFinite(a.combo+a.lastClean))return null;const s=JSON.parse(JSON.stringify(a));s.events=[];s.won=!!a.won&&clear(s);return s;}
const api={names,config,point,path,fresh,clear,solid,sight,spill,howl,step,stars,restore};if(typeof module!=='undefined')module.exports=api;else root.Howl=api;
})(typeof window==='undefined'?globalThis:window);
