(function(root){'use strict';
const NAMES=['Peach Highway','Canyon Express','Mint Interchange','Golden Hour','Blue Hour','Cloud Freight','Midnight Mail','The Last Mile'];
const LANES=[[175,245,175,245],[190,260,210,150,230,270],[210,160,245,190,260,180],[170,230,280,210,150,200],[210,270,200,150,220,180],[180,255,210,155,235,280],[210,150,240,275,210,160],[175,255,200,145,220,280,235]];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function level(n){n=clamp(n|0,0,7);const count=7+n, trucks=[];
 for(let r=0;r<=count;r++){let x=LANES[n][r%LANES[n].length];const kind=r===count?'goal':r===0?'start':r===3||(r+n)%6===3?'bounce':(r+n)%4===2?'soft':(r+n)%3===0?'van':'truck';
 trucks.push({id:trucks.length,row:r,x,y:-r*125,w:kind==='van'?66:84,h:kind==='goal'?122:104,kind,phase:r*1.71+n,amp:r===0||r===count?0:12+n*2,speed:.65+n*.08,parcel:false});
 if(r>0&&r<count){const side=x>210?75:345;trucks.push({id:trucks.length,row:r,x:side,y:-r*125-8,w:80,h:106,kind:r%3===1?'bus':'truck',phase:r*.91,amp:8+n,speed:.8,parcel:[2,Math.floor(count/2),count-1].includes(r)});}}
 return {n,name:NAMES[n],count,trucks};}
function position(a,t){return{x:a.x+Math.sin(t*a.speed+a.phase)*a.amp,y:a.y-t*18+Math.sin(t*.72+a.phase)*6};}
class Run{
 constructor(n=0){this.map=level(n);this.t=0;this.roof=0;this.offset={x:0,y:0};this.p=position(this.map.trucks[0],0);this.jump=null;this.state='ready';this.falls=0;this.parcels=[];this.visited=[0];this.checkpoint=0;this.combo=0;this.bestCombo=0;this.score=0;this.stand=0;this.events=[];this.jumps=0;}
 event(type,data={}){this.events.push({type,...data});if(this.events.length>24)this.events.shift();}
 start(){if(this.state==='ready')this.state='playing';}
 get maxJump(){return this.map.trucks[this.roof]?.kind==='bounce'?295:222;}
 target(x,y){if(this.state!=='playing'||this.jump)return null;let best=null;
 for(const a of this.map.trucks){if(a.id===this.roof||a.row<this.map.trucks[this.roof].row-1)continue;const now=position(a,this.t);let ox=clamp(x-now.x,-a.w/2+10,a.w/2-10),oy=clamp(y-now.y,-a.h/2+12,a.h/2-12);let d=Math.hypot(x-now.x,y-now.y);if(Math.abs(x-now.x)>a.w/2+18||Math.abs(y-now.y)>a.h/2+18)continue;const duration=.58+Math.hypot(now.x+ox-this.p.x,now.y+oy-this.p.y)/900;const future=position(a,this.t+duration);const length=Math.hypot(future.x+ox-this.p.x,future.y+oy-this.p.y);if(length>this.maxJump)continue;if(!best||d<best.d)best={id:a.id,x:future.x+ox,y:future.y+oy,ox,oy,d,duration};}return best;}
 launch(x,y){if(this.state!=='playing'||this.jump||!Number.isFinite(x)||!Number.isFinite(y))return false;const current=this.map.trucks[this.roof],at=position(current,this.t);if(Math.abs(x-at.x)<current.w/2&&Math.abs(y-at.y)<current.h/2)return false;const target=this.target(x,y),dist=Math.hypot(x-this.p.x,y-this.p.y);if(dist<12)return false;const ratio=Math.min(1,this.maxJump/dist);this.jump={from:{...this.p},to:target?{x:target.x,y:target.y}:{x:this.p.x+(x-this.p.x)*ratio,y:this.p.y+(y-this.p.y)*ratio},target,elapsed:0,duration:target?.duration||.76};this.stand=0;this.jumps++;this.event('jump',{boost:this.maxJump>250});return true;}
 recover(){this.falls++;this.combo=0;this.roof=this.checkpoint;this.offset={x:0,y:0};this.p=position(this.map.trucks[this.roof],this.t);this.jump=null;this.stand=0;this.event('fall');}
 step(dt){if(this.state!=='playing')return;dt=clamp(dt,0,.04);this.t+=dt;
 if(this.jump){const j=this.jump;j.elapsed+=dt;const f=Math.min(1,j.elapsed/j.duration),e=f*f*(3-2*f);this.p={x:j.from.x+(j.to.x-j.from.x)*e,y:j.from.y+(j.to.y-j.from.y)*e};if(f>=1){const a=j.target&&this.map.trucks[j.target.id],pos=a&&position(a,this.t);if(a&&Math.abs(this.p.x-pos.x)<a.w/2-3&&Math.abs(this.p.y-pos.y)<a.h/2-3){this.roof=a.id;this.offset={x:this.p.x-pos.x,y:this.p.y-pos.y};this.jump=null;this.stand=0;const perfect=Math.hypot(this.offset.x,this.offset.y)<22;this.combo=perfect?this.combo+1:0;this.bestCombo=Math.max(this.combo,this.bestCombo);this.score+=perfect?100+this.combo*20:60;if(!this.visited.includes(a.id))this.visited.push(a.id);if(a.parcel&&!this.parcels.includes(a.id)){this.parcels.push(a.id);this.score+=250;this.event('parcel');}if(a.row%3===0&&a.kind!=='soft'&&a.row>this.map.trucks[this.checkpoint].row)this.checkpoint=a.id;this.event('land',{perfect,combo:this.combo});if(a.kind==='goal'){this.state='won';this.event('won');}}else this.recover();}}
 else{const a=this.map.trucks[this.roof],pos=position(a,this.t);this.p={x:pos.x+this.offset.x,y:pos.y+this.offset.y};this.stand+=dt;if(a.kind==='soft'&&this.stand>2.3)this.recover();}}
 get stars(){return this.state==='won'?1+(this.parcels.length===3?1:0)+(this.falls===0?1:0):0;}
 snapshot(){return JSON.stringify({n:this.map.n,t:this.t,roof:this.roof,offset:this.offset,p:this.p,jump:this.jump,state:this.state,falls:this.falls,parcels:this.parcels,visited:this.visited,checkpoint:this.checkpoint,combo:this.combo,bestCombo:this.bestCombo,score:this.score,stand:this.stand,jumps:this.jumps});}
 static restore(s){try{const d=JSON.parse(s);if(!Number.isInteger(d.n)||d.n<0||d.n>7)throw 0;const r=new Run(d.n);for(const k of ['t','falls','checkpoint','score','stand','combo','bestCombo','jumps'])if(!Number.isFinite(d[k])||d[k]<0)throw 0;if(!r.map.trucks[d.roof]||!r.map.trucks[d.checkpoint]||!['playing','won','ready'].includes(d.state))throw 0;for(const a of [d.offset,d.p])if(!a||!Number.isFinite(a.x)||!Number.isFinite(a.y))throw 0;if(!Array.isArray(d.parcels)||!d.parcels.every(id=>r.map.trucks[id]?.parcel)||new Set(d.parcels).size!==d.parcels.length)throw 0;if(d.jump){const j=d.jump;if(!j.from||!j.to||![j.from.x,j.from.y,j.to.x,j.to.y,j.elapsed,j.duration].every(Number.isFinite)||j.duration<=0||j.elapsed<0||j.elapsed>j.duration||j.target&&!r.map.trucks[j.target.id])throw 0;}if(!Array.isArray(d.visited)||!d.visited.every(id=>r.map.trucks[id]))throw 0;Object.assign(r,d);return r;}catch{return null;}}
}
const api={Run,level,position,clamp,NAMES};if(typeof module!=='undefined')module.exports=api;else root.Skyway=api;
})(typeof window==='undefined'?globalThis:window);
