'use strict';
const airport=new Airport(),$=id=>document.getElementById(id),places=[['Palm Cove','#80c3c8','#529ba8','#b5c59b','#efd7a3'],['Apricot Bay','#b7c8b1','#80aba8','#b8b889','#ecd0a0'],['Cloud Harbour','#91b8d1','#5d91b5','#a7bdb2','#e2debf'],['Starlit Port','#3c7087','#295770','#789c8e','#c6c5a0']];let paused=true,started=false,muted=true,frame=0,acc=0,last=0,view={x:0,y:0,s:1},saved=null,audio=null,noticeTime=0,bookOpen=false;
try{saved=JSON.parse(localStorage.getItem('azure-airport-v1'));if(saved?.profile){airport.profile=saved.profile;$('resume').hidden=false}}catch(e){}
function save(){try{localStorage.setItem('azure-airport-v1',JSON.stringify(airport.snapshot()))}catch(e){}}
function notice(t){$('notice').textContent=t;noticeTime=150}
function tone(kind){if(muted)return;try{audio||=new(window.AudioContext||window.webkitAudioContext);audio.resume();let seq=kind==='land'?[460,610,770]:kind==='incident'?[140,100]:[380];seq.forEach((f,i)=>{let t=audio.currentTime+i*.08,o=audio.createOscillator(),g=audio.createGain();o.type=kind==='incident'?'triangle':'sine';o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(f*.85,t+.18);g.gain.setValueAtTime(.05,t);g.gain.exponentialRampToValueAtTime(.001,t+.21);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.23)})}catch(e){}}
function sync(){ $('day').textContent='DAY '+String(airport.day).padStart(2,'0');$('count').textContent=airport.landed+' / '+airport.goal();$('progress').style.width=airport.landed/airport.goal()*100+'%';$('lives').textContent='♥ '.repeat(Math.max(0,airport.lives));$('coins').textContent='● '+airport.profile.coins;$('pause').textContent=paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',paused?'Play':'Pause');$('sound').style.opacity=muted?'.45':'1';let p=airport.planes.find(p=>p.id===airport.selected);$('detail').textContent=p?'A'+String(p.id).padStart(2,'0')+' · '+(p.side===0?'TRIANGLE':'CIRCLE')+' · '+Math.ceil(p.fuel)+'s FUEL · '+p.phase.toUpperCase()+(p.emergency?' · PRIORITY':''):'TAP A PLANE → TAP ITS RUNWAY';$('hold').querySelector('small').textContent=p?'A'+String(p.id).padStart(2,'0'):'SELECT A PLANE';$('hold').style.opacity=p?1:.6}
function card(eye,title,copy){$('eyebrow').textContent=eye;$('title').textContent=title;$('copy').innerHTML=copy;$('reward').innerHTML='';$('shop').innerHTML='';$('shop').hidden=true;$('overlay').hidden=false;$('start').hidden=false;$('resume').hidden=true;$('close').hidden=true}
function launch(){started=true;paused=false;acc=0;bookOpen=false;$('overlay').hidden=true;sync();save();if(airport.day===1)notice('Pick a plane, then the matching symbol.');else if(airport.day===3)notice('Gold flights have less fuel.');tone('start')}
$('start').onclick=()=>{if(airport.state==='win')airport.begin(airport.day+1);else if(airport.state==='lose')airport.begin(airport.day);else if(!started)airport.begin(1);launch()};$('resume').onclick=()=>{airport.restore(saved);started=true;if(airport.state==='play')launch();else outcome();sync()};$('pause').onclick=()=>{if(!started||bookOpen||airport.state!=='play')return;paused=!paused;acc=0;if(paused){card('A QUIET SKY','Take a breather.','Your flights are saved.');$('start').textContent='Back to the tower →';save()}else $('overlay').hidden=true;sync()};$('sound').onclick=()=>{muted=!muted;sync();tone('start')};$('hold').onclick=()=>{if(paused)return;if(airport.hold(airport.selected)){notice('Going around · runway released');tone('hold');sync()}else notice('Select a flying aircraft first.')};
function shop(){ $('shop').hidden=false;$('shop').innerHTML='';for(let[k,title,desc]of[['fuel','Fuel reserve','More time to arrange each arrival.'],['radar','Radar tower','Warn about closer flights earlier.'],['turn','Ground crew','Clear the landing strip faster.']]){let lv=airport.profile.gear[k],price=airport.cost(k),b=document.createElement('button');b.className='upgrade';b.setAttribute('aria-label',title);b.innerHTML='<div>'+title+' '+('●'.repeat(lv)+'○'.repeat(3-lv))+'<small>'+desc+'</small></div><span>'+(lv===3?'MAX':'● '+price)+'</span>';b.onclick=()=>{if(airport.buy(k)){tone('land');save();shop();$('reward').innerHTML='★'.repeat(airport.stars)+'<div style="font-size:12px">● '+airport.profile.coins+' available</div>';sync()}else if(lv<3)$('copy').textContent='Need '+price+' coins. Keep the next day moving.'};$('shop').appendChild(b)}}
function outcome(){paused=true;save();sync();if(airport.state==='win'){card('DAY COMPLETE','All safely down.','Clear skies earn more stars.<br>Expand the airport, or keep your coins.');$('reward').innerHTML='★'.repeat(airport.stars)+'<div style="font-size:12px">+'+airport.reward+' coins · ● '+airport.profile.coins+' available</div>';$('start').textContent=airport.day>=4?'Next shift →':'Next island →';shop()}else{card('TIME FOR A RESET','A fresh approach.','Keep your upgrades and coins.<br>Hold a flight when paths get too close.');$('start').textContent='Retry day →'}}
$('book').onclick=()=>{paused=true;bookOpen=true;card('ISLAND LOG','Airport book.','Collect stars across the island skies.');$('start').hidden=true;$('close').hidden=false;$('shop').hidden=false;for(let i=1;i<=Math.max(4,Math.min(12,airport.profile.best+1));i++){let b=document.createElement('button');b.className='dayEntry';b.setAttribute('aria-label','Day '+i);b.innerHTML='<span>'+String(i).padStart(2,'0')+' · '+places[(i-1)%4][0]+'</span><i>'+('★'.repeat(airport.profile.stars[i]||0)||'○')+'</i>';b.onclick=()=>{if(i>airport.profile.best+1){$('copy').textContent='Complete the previous day first.';return}if(started&&airport.state==='play'&&airport.tick>0&&b.dataset.confirm!=='yes'){b.dataset.confirm='yes';b.innerHTML='<span>Restart on day '+i+'?</span><i>Tap again</i>';return}airport.begin(i);launch()};$('shop').appendChild(b)}sync()};$('close').onclick=()=>{bookOpen=false;if(started&&airport.state==='play')launch();else if(airport.state==='win'||airport.state==='lose')outcome();else{card('THE LITTLE ISLAND AIR SERVICE','Welcome aboard.','Tap a plane, then its matching runway.<br>Hold a flight to leave room for another.');$('start').textContent='Open the airport →';if(saved)$('resume').hidden=false}};
let press=null,lastTouch=0;document.addEventListener('pointerdown',e=>{let b=e.target.closest('button');if(e.pointerType==='touch'&&b)press={b,id:e.pointerId,x:e.clientX,y:e.clientY}});document.addEventListener('pointerup',e=>{if(!press||e.pointerId!==press.id)return;let q=press;press=null;if(Math.hypot(e.clientX-q.x,e.clientY-q.y)<12&&e.target.closest('button')===q.b){lastTouch=performance.now();q.b.click()}});document.addEventListener('pointercancel',()=>press=null);document.addEventListener('click',e=>{if(e.isTrusted&&lastTouch&&performance.now()-lastTouch<700){e.preventDefault();e.stopImmediatePropagation()}},true);
function choose(x,y){let p=airport.planes.filter(p=>p.phase!=='landing').sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y))[0];if(p&&Math.hypot(p.x-x,p.y-y)<Math.max(36,23/view.s)){airport.selected=p.id;sync();tone('select');return}let r=airport.runways.find(r=>Math.hypot(r.x-x,r.y-y)<62);if(r&&airport.selected!==null){let result=airport.assign(airport.selected,r.id);notice(result===true?'Cleared to land.':result);tone('select');sync()}}
function canvasInput(c){let start=null;function pos(e){let r=c.getBoundingClientRect();return{x:(e.clientX-r.left-view.x)/view.s,y:(e.clientY-r.top-view.y)/view.s}}c.addEventListener('pointerdown',e=>{if(paused)return;e.preventDefault();c.setPointerCapture(e.pointerId);start=pos(e);choose(start.x,start.y)});c.addEventListener('pointerup',e=>{if(!start||paused)return;let q=pos(e);if(Math.hypot(q.x-start.x,q.y-start.y)>35)choose(q.x,q.y);start=null});c.addEventListener('pointercancel',()=>start=null)}
window.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();$('hold').click()}if(e.code==='KeyP')$('pause').click();if(e.code==='Digit1'||e.code==='Digit2'){let r=airport.assign(airport.selected,e.code==='Digit1'?0:1);if(r!==true)notice(r)}if(e.code==='Tab'&&!paused){e.preventDefault();let ids=airport.planes.filter(p=>p.phase!=='landing').map(p=>p.id),i=ids.indexOf(airport.selected);airport.selected=ids[(i+1)%ids.length]??null;sync()}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&started&&!paused&&airport.state==='play')$('pause').click()});
function rect(c,x,y,w,h,r,fill,stroke){c.beginPath();c.roundRect(x,y,w,h,r);c.fillStyle=fill;c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=2;c.stroke()}}function oval(c,x,y,rx,ry,col){c.beginPath();c.ellipse(x,y,Math.max(.1,rx),Math.max(.1,ry),0,0,6.283);c.fillStyle=col;c.fill()}function line(c,x,y,a,b,col,w=2){c.beginPath();c.moveTo(x,y);c.lineTo(a,b);c.strokeStyle=col;c.lineWidth=w;c.stroke()}function text(c,t,x,y,size,col){c.font='bold '+size+'px Trebuchet MS';c.textAlign='center';c.fillStyle=col;c.fillText(t,x,y)}
function island(c,x,y,rx,ry,col,stroke){let pts=[];for(let i=0;i<16;i++){let a=i/16*6.283,r=1+Math.sin(i*2.1+x)*.08;pts.push({x:x+Math.cos(a)*rx*r,y:y+Math.sin(a)*ry*r})}c.beginPath();let f=pts[0],last=pts[15];c.moveTo((f.x+last.x)/2,(f.y+last.y)/2);for(let i=0;i<16;i++){let p=pts[i],q=pts[(i+1)%16];c.quadraticCurveTo(p.x,p.y,(p.x+q.x)/2,(p.y+q.y)/2)}c.closePath();c.fillStyle=col;c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=2;c.stroke()}}
function palm(c,x,y,size=1){c.save();c.translate(x,y);c.scale(size,size);oval(c,5,7,14,5,'#597d6a20');line(c,0,10,3,-10,'#ad9b70',4);for(let i=0;i<5;i++){let a=i*1.256;c.beginPath();c.moveTo(3,-10);c.quadraticCurveTo(3+Math.cos(a)*12,-10+Math.sin(a)*12,3+Math.cos(a)*20,-10+Math.sin(a)*20);c.quadraticCurveTo(3+Math.cos(a+.3)*12,-10+Math.sin(a+.3)*12,3,-10);c.fillStyle=i%2?'#789b72':'#5b8a70';c.fill()}c.restore()}
function building(c,x,y,w,h,roof){oval(c,x+w/2,y+h+5,w*.53,7,'#53765d24');rect(c,x,y,w,h,5,'#efdfb6','#88a18b');rect(c,x-3,y-7,w+6,16,4,roof,'#829883');for(let i=0;i<Math.floor(w/17);i++)rect(c,x+7+i*17,y+15,9,11,2,'#76a8aa');rect(c,x+w/2-5,y+h-13,10,13,2,'#91afa0')}
function scene(c){let t=places[(airport.day-1)%4],sea=c.createLinearGradient(0,0,600,760);sea.addColorStop(0,t[1]);sea.addColorStop(1,t[2]);c.fillStyle=sea;c.fillRect(-400,-300,1400,1300);for(let i=0;i<50;i++){let x=((i*137+Math.sin(airport.tick*.008+i)*9)%660)-30,y=(i*83)%780;line(c,x,y,x+13+i%4*3,y,t[4]+'20',1)}
 island(c,178,425,145,222,'#c5dfc13d');island(c,421,420,142,216,'#c5dfc13d');island(c,183,424,135,209,t[4],'#cce6c2');island(c,421,420,132,205,t[4],'#cce6c2');island(c,184,426,122,192,t[3]);island(c,421,421,119,188,t[3]);island(c,300,518,103,93,t[4]);island(c,300,513,92,79,t[3]);island(c,72,66,44,31,t[4]);island(c,76,61,35,23,t[3]);island(c,547,667,41,35,t[4]);island(c,548,664,31,25,t[3]);
 // Coastal rocks, harbour, planted beds and warm miniature buildings.
 for(let i=0;i<12;i++){let a=i*.52;oval(c,185+Math.cos(a)*135,426+Math.sin(a)*207,5+i%3,3+i%2,'#9da990');oval(c,425+Math.cos(a)*126,420+Math.sin(a)*201,5+i%3,3+i%2,'#9da990')}
 for(let p of [[135,245],[241,264],[100,500],[191,610],[494,259],[479,520],[365,269],[430,599],[75,66],[549,661]])palm(c,...p,.7+(p[0]%3)*.1);
 rect(c,249,519,108,67,5,'#c9bd8f');for(let i=0;i<7;i++)line(c,249,527+i*8,356,527+i*8,'#f5dfb155',1);building(c,238,492,66,47,'#b78b72');building(c,305,492,57,40,'#86aca2');for(let i=0;i<airport.profile.gear.turn;i++)building(c,234+i*36,557,30,24,'#c5a36e');
 rect(c,286,448,32,44,5,'#edddb2','#7d9687');rect(c,279,436,46,22,6,'#729c9a','#507b80');for(let j=0;j<3;j++)rect(c,285+j*11,441,7,10,2,'#bde2d5');let lv=airport.profile.gear.radar;line(c,302,435,302,424-lv*8,'#69837e',3);c.save();c.translate(302,424-lv*8);c.rotate(Math.sin(airport.tick*.025)*.5);line(c,-14-lv*2,0,14+lv*2,0,'#e9d6a8',3);c.restore();
 for(let i=0;i<1+airport.profile.gear.fuel;i++){oval(c,421+(i%2)*24,523+Math.floor(i/2)*27,10,5,'#7b948733');rect(c,412+(i%2)*24,506+Math.floor(i/2)*27,18,17,3,'#d9d6b3','#8eaa99');oval(c,421+(i%2)*24,506+Math.floor(i/2)*27,9,4,'#edf0ca')}
 for(let x of [243,359]){line(c,x,585,x,655,'#a3a57d',10);for(let i=0;i<6;i++)line(c,x-7,600+i*9,x+7,600+i*9,'#e4d0a0',2)}
 // A ferry and its tiny wake.
 let boatX=305+Math.sin(airport.tick*.002)*36,boatY=671;c.save();c.translate(boatX,boatY);oval(c,-9,11,14,4,'#e8edc52a');rect(c,-14,-8,28,39,12,'#e9deb6','#6b9b9b');rect(c,-10,-1,20,20,4,'#a4c4bb');rect(c,-6,0,12,8,2,'#6c959b');c.restore();
 for(let r of airport.runways){let dx=r.end.x-r.x,dy=r.end.y-r.y,a=Math.atan2(dy,dx);c.save();c.translate(r.x,r.y);c.rotate(a);rect(c,-25,-22,130,44,9,'#a29f80');rect(c,-20,-17,118,34,5,'#547e83','#dce2b7');for(let i=0;i<6;i++)line(c,-10+i*18,0,i*18,0,'#e2e8c0',2);for(let i=0;i<4;i++){line(c,-13+i*4,-12,-13+i*4,-5,'#eff0cc',2);line(c,-13+i*4,5,-13+i*4,12,'#eff0cc',2)}for(let i=0;i<7;i++){let glow=places[(airport.day-1)%4]===places[3]?'#f5d697':'#ecddb1';oval(c,-18+i*18,-20,1.8,1.8,glow);oval(c,-18+i*18,20,1.8,1.8,glow)}c.restore();let color=r.id===0?'#d7947b':'#6daaba';badge(c,r.x,r.y,r.id,18);rect(c,r.x-40,r.y+32,80,18,6,r.busy!==null||r.cool?'#887b6c':'#718f79');text(c,r.busy!==null||r.cool?'OCCUPIED':'READY',r.x,r.y+45,8,'#f6e8bf')}
 for(let i=0;i<14;i++){let x=220+i*13,y=595+Math.sin(i*1.7)*5;oval(c,x,y,3,3,i%3===0?'#dfa99c':'#e7d8a4')}
 // Painted taxi lanes, hangars, little service carts and coastal gardens.
 for(let side=0;side<2;side++){let r=airport.runways[side],xx=side===0?255:345;line(c,r.end.x,r.end.y,xx,485,'#d9cd9d',13);line(c,r.end.x,r.end.y,xx,485,'#9eac85',8);building(c,side===0?121:438,442,39,31,side===0?'#be8f78':'#83aaa6');rect(c,side===0?159:410,488,22,12,3,'#e2d3a4','#91a187');oval(c,side===0?163:414,500,3,3,'#648c8a');oval(c,side===0?177:428,500,3,3,'#648c8a');for(let i=0;i<3;i++){let x=side===0?151+i*19:419+i*19,y=371;line(c,x,y,x+9,y+16,'#e0d9ac',1);rect(c,x+6,y+12,10,4,1,'#72958b')}}
 for(let i=0;i<18;i++){let x=136+(i%6)*20,y=302+Math.floor(i/6)*16;c.save();c.translate(x,y);c.rotate(-.3);oval(c,0,0,5,2.5,i%2?'#819e78':'#93af81');c.restore()}
 for(let i=0;i<15;i++){let x=370+(i%5)*22,y=294+Math.floor(i/5)*19;oval(c,x,y,4,4,i%3===0?'#c1b17c':'#89a47c');oval(c,x-1,y-1,1.5,1.5,'#dbc594')}
 for(let x of [278,324]){line(c,x,416,x,397,'#9aa87d',2);c.beginPath();c.moveTo(x,397);c.lineTo(x+18,401+Math.sin(airport.tick*.07)*2);c.lineTo(x+18,405);c.lineTo(x,402);c.closePath();c.fillStyle='#d8a385';c.fill();line(c,x+5,398,x+5,403,'#f6deb6',2)}
 text(c,places[(airport.day-1)%4][0].toUpperCase(),300,623,9,'#f0e6bd');
}
function badge(c,x,y,side,r){oval(c,x,y,r,r,side===0?'#d68e78':'#71aabb');if(side===0){c.beginPath();c.moveTo(x,y-r*.52);c.lineTo(x+r*.48,y+r*.36);c.lineTo(x-r*.48,y+r*.36);c.closePath();c.fillStyle='#fff0ce';c.fill()}else{c.strokeStyle='#edf2d5';c.lineWidth=2;c.beginPath();c.arc(x,y,r*.46,0,6.283);c.stroke()}}
function plane(c,p){let selected=p.id===airport.selected,sideCol=p.side===0?'#ca8d7a':'#6597ad',size=(p.phase==='landing'?Math.max(.55,1-p.landTick/200):1)*Math.max(1,.48/view.s);c.save();c.translate(p.x,p.y);if(selected){c.strokeStyle='#fff2bd';c.lineWidth=2;c.beginPath();c.arc(0,0,Math.max(29,17/view.s),0,6.283);c.stroke()}if(p.emergency&&p.fuel<25){c.strokeStyle='#efd192';c.lineWidth=2;c.beginPath();c.arc(0,0,24+Math.sin(airport.tick*.1)*3,0,6.283);c.stroke()}c.rotate(p.angle);c.scale(size,size);oval(c,-4,6,19,10,'#2c6b8320');c.beginPath();c.moveTo(15,0);c.quadraticCurveTo(11,-6,-7,-5);c.lineTo(-14,-16);c.lineTo(-18,-16);c.lineTo(-15,-4);c.lineTo(-19,-3);c.lineTo(-20,3);c.lineTo(-15,4);c.lineTo(-18,16);c.lineTo(-14,16);c.lineTo(-7,5);c.quadraticCurveTo(11,6,15,0);c.fillStyle=p.emergency?'#f2d493':'#f4e9cc';c.fill();c.strokeStyle='#577f89';c.lineWidth=1.5;c.stroke();c.beginPath();c.moveTo(2,-3);c.lineTo(-1,-22);c.lineTo(-7,-22);c.lineTo(-9,-3);c.lineTo(-9,3);c.lineTo(-7,22);c.lineTo(-1,22);c.lineTo(2,3);c.closePath();c.fillStyle=sideCol;c.fill();c.strokeStyle='#507e88';c.stroke();rect(c,7,-3,4,6,2,'#6794a2');line(c,16,-8,16,8,'#91b4b899',2);line(c,-18,-6,-18,6,sideCol,3);c.restore();c.save();c.translate(p.x,p.y);text(c,'A'+String(p.id).padStart(2,'0'),0,-34,Math.max(10,8/view.s),'#f5f0ce');badge(c,23,-23,p.side,7);let fuel=(p.fuel/((p.emergency?42:80)+airport.profile.gear.fuel*15));rect(c,-15,29,30,3,2,'#366b7f55');rect(c,-15,29,30*Math.min(1,fuel),3,2,p.fuel<25?'#e9b58c':'#d1e2bc');c.restore()}
new p5(p=>{p.setup=()=>{let host=$('host'),cv=p.createCanvas(host.clientWidth,host.clientHeight);cv.parent(host);p.pixelDensity(Math.min(devicePixelRatio,1.5));p.frameRate(60);canvasInput(cv.elt);new ResizeObserver(()=>p.resizeCanvas(host.clientWidth,host.clientHeight)).observe(host);last=performance.now();sync()};p.draw=()=>{frame++;let now=performance.now(),dt=Math.min(.05,(now-last)/1000);last=now;if(!paused&&!document.hidden&&airport.state==='play'){acc+=dt;let z=0;while(acc>=1/60&&z++<4){airport.step();for(let e of airport.events){if(e.type==='land'){notice(e.label);tone('land')}if(e.type==='incident'){notice('Too close · send a flight around');tone('incident')}if(e.type==='divert'){notice('Fuel low · flight diverted');tone('incident')}}acc-=1/60}if(airport.tick%180===0)save();if(airport.state!=='play')outcome();sync()}else acc=0;if(noticeTime>0&&!paused&&--noticeTime===0)$('notice').textContent='';let c=p.drawingContext,ratio=p.pixelDensity(),s=Math.min(p.width/590,p.height/750);view={x:(p.width-600*s)/2,y:(p.height-760*s)/2,s};c.save();c.setTransform(ratio,0,0,ratio,0,0);c.fillStyle=places[(airport.day-1)%4][1];c.fillRect(0,0,p.width,p.height);c.translate(view.x,view.y);c.scale(s,s);scene(c);
 let chosen=airport.planes.find(p=>p.id===airport.selected);if(chosen){c.save();c.setLineDash([5,7]);for(let r of airport.runways)if(r.id===chosen.side){let pts=airport.routePoints(chosen,r);c.strokeStyle='#ffefbd99';c.lineWidth=2;c.beginPath();pts.forEach((q,i)=>i?c.lineTo(q.x,q.y):c.moveTo(q.x,q.y));c.stroke()}c.setLineDash([]);c.restore()}
 for(let i=0;i<airport.planes.length;i++)for(let j=i+1;j<airport.planes.length;j++){let a=airport.planes[i],b=airport.planes[j];if(['landing','recover'].includes(a.phase)||['landing','recover'].includes(b.phase))continue;let d=Math.hypot(a.x-b.x,a.y-b.y);if(d<65+airport.profile.gear.radar*20){line(c,a.x,a.y,b.x,b.y,d<45?'#e7a789':'#f0d7a880',2);oval(c,(a.x+b.x)/2,(a.y+b.y)/2,5,5,'#eaca8e')}}
 for(let p of airport.planes){c.strokeStyle=(p.side===0?'#ffe8c2':'#e0f4dc')+'55';c.lineWidth=2;c.beginPath();p.trail.forEach((q,i)=>i?c.lineTo(q.x,q.y):c.moveTo(q.x,q.y));c.stroke();if(p.phase==='hold'){c.setLineDash([3,7]);c.strokeStyle='#e6e9c748';c.lineWidth=1;c.beginPath();c.arc(p.home.x,p.home.y,32,0,6.283);c.stroke();c.setLineDash([])}if(p.phase==='route'&&p.path){c.strokeStyle=p.side===0?'#efd09b44':'#d0ecea55';c.lineWidth=1.5;c.beginPath();c.moveTo(p.x,p.y);p.path.slice(p.segment+1).forEach(q=>c.lineTo(q.x,q.y));c.stroke()}plane(c,p)}
 for(let e of airport.effects){let t=e.t/70;if(e.type==='land'){c.globalAlpha=1-t;text(c,'✦',e.x,e.y-15-t*35,25,'#ffe2a2');for(let j=0;j<8;j++){let a=j*.785;oval(c,e.x+Math.cos(a)*t*50,e.y+Math.sin(a)*t*40,2*(1-t),2*(1-t),'#f5e5b5')}c.globalAlpha=1}else if(e.type==='touchdown'){c.strokeStyle='#edf2d0';c.lineWidth=2*(1-t);c.beginPath();c.arc(e.x,e.y,10+t*30,0,6.283);c.stroke()}else if(e.type==='incident'){c.globalAlpha=1-t;c.strokeStyle='#f2c3a2';c.lineWidth=2;c.beginPath();c.arc(e.x,e.y,10+t*55,0,6.283);c.stroke();c.globalAlpha=1}}
 c.restore()};});
window.airportDebug={airport,getState:()=>({frame,paused,started,view,rect:document.querySelector('canvas').getBoundingClientRect().toJSON(),snapshot:airport.snapshot()})};
