'use strict';const game=new Putt(PUTT_LEVELS),$=id=>document.getElementById(id),themes=[['Clover coast','#d7dec3','#accdb6','#80aa80','#467b69','#eedbc0'],['Apricot terrace','#ead8b8','#c7d4ba','#a9b777','#70876a','#f1d6a9'],['Lavender lagoon','#d7d6e3','#b7c6d7','#a7b6a2','#72898e','#e8e0ca'],['Moonlit conservatory','#344d65','#587a84','#84a499','#527b7d','#bcc7b8']],skins=['#fff3d9','#efb5a6','#c8bddb','#f2d38f'];let paused=true,started=false,muted=true,frame=0,time=0,last=performance.now(),noticeUntil=0,anim=null,celebration=null,view={s:1,x:0,y:0},saved=null,hintDir=null,audio=null,resetConfirm=false,book=false;
try{saved=JSON.parse(localStorage.getItem('petal-putt-v1'));if(saved?.profile){game.profile=saved.profile;$('resume').hidden=false}}catch(e){}
function save(){try{localStorage.setItem('petal-putt-v1',JSON.stringify(game.snapshot()))}catch(e){}}
function tone(kind){if(muted)return;try{audio||=new(window.AudioContext||window.webkitAudioContext);audio.resume();let frequencies=kind==='win'?[392,494,587,784]:kind==='blocked'?[180]:kind==='portal'?[510,720]:[360,460];frequencies.forEach((f,i)=>{let t=audio.currentTime+i*.07,o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(f*.95,t+.15);g.gain.setValueAtTime(.04,t);g.gain.exponentialRampToValueAtTime(.001,t+.2);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.21)})}catch(e){}}
function notice(msg){$('notice').textContent=msg;noticeUntil=time+2.8}
function sync(){ $('level').textContent='GARDEN '+String(game.day).padStart(2,'0');$('name').textContent=game.level.name;$('caption').textContent=game.selected===null?'No cards left · undo a move.':game.level.cards[game.selected].kind==='jump'?'JUMP · land after '+game.level.cards[game.selected].n+' steps':'ROLL · '+game.level.cards[game.selected].n+' steps';$('pause').setAttribute('aria-label',paused?'Play':'Pause');$('pause').textContent=paused?'▶':'Ⅱ';$('sound').style.opacity=muted?.5:1;$('caption').style.color=game.level.theme===3?'#dce3ca':'#3e625b';$('notice').style.color=game.level.theme===3?'#eee9ce':'#3e625b';let deck=$('deck');deck.innerHTML='';game.level.cards.forEach((c,i)=>{let b=document.createElement('button');b.className='stroke'+(game.selected===i?' selected':'')+(game.used&(1<<i)?' used':'');b.setAttribute('aria-label','Card '+(i+1)+' '+c.kind+' '+c.n);b.dataset.card=i;b.innerHTML=(c.kind==='jump'?'⌒':'•')+c.n+'<small>'+c.kind.toUpperCase()+'</small>';b.onclick=()=>{if(paused||anim||celebration)return;game.select(i);hintDir=null;resetConfirm=false;sync();tone('select')};deck.appendChild(b)});document.querySelectorAll('[data-dir]').forEach(b=>b.classList.toggle('hinted',Number(b.dataset.dir)===hintDir));}
function panel(eye,title,copy){$('overlay').hidden=false;$('eyebrow').textContent=eye;$('title').innerHTML=title;$('copy').innerHTML=copy;$('reward').innerHTML='';$('shop').hidden=true;$('shop').innerHTML='';$('start').hidden=false;$('resume').hidden=true;$('back').hidden=true}
function launch(){started=true;paused=false;book=false;anim=null;celebration=null;hintDir=null;resetConfirm=false;$('overlay').hidden=true;sync();save();if(game.day===1)notice('Two little steps to the flag.');if(game.day===2)notice('Sand stops a rolling ball.');if(game.day===4)notice('Jump cards cross water.');if(game.day===5)notice('Flowers lead to their matching flower.')}
function start(){if(game.state==='win')game.begin(game.day+1);else if(!started)game.begin(1);launch()}$('start').onclick=start;$('resume').onclick=()=>{game.restore(saved);started=true;if(game.state==='win')outcome();else launch();sync()};$('pause').onclick=()=>{if(!started||book||game.state!=='play'||anim)return;paused=!paused;if(paused){panel('A QUIET MOMENT','Take your time.','Your garden is saved.');$('start').textContent='Back to the garden →';save()}else $('overlay').hidden=true;sync()};$('sound').onclick=()=>{muted=!muted;sync();tone('select')};
function outcome(){paused=true;panel('GARDEN COMPLETE','A lovely little putt.','A new garden is waiting.');$('reward').innerHTML='★'.repeat(game.stars)+'<small>+'+game.reward+' petals · '+game.profile.coins+' saved</small>';$('start').textContent=game.day===24?'Garden remix →':'Next garden →';$('shop').hidden=false;for(let i=0;i<4;i++){let b=document.createElement('button');b.className='skin';b.setAttribute('aria-label','Ball style '+i);b.innerHTML='<span style="color:'+skins[i]+';text-shadow:0 1px 3px #7d8f71">●</span><small>'+(game.profile.skins.includes(i)?game.profile.skin===i?'WORN':'WEAR':[0,12,24,36][i]+' petals')+'</small>';b.onclick=()=>{if(game.buy(i)){tone('select');save();outcome()}else $('copy').textContent='Keep exploring to collect more petals.'};$('shop').appendChild(b)}save();sync()}
function move(d){if(paused||anim||celebration)return;let old={...game.pos};if(!game.move(d)){notice('Try another card or direction.');tone('blocked');return}hintDir=null;resetConfirm=false;anim={points:[old,...game.lastPath],elapsed:0,duration:.38+game.lastPath.length*.07,jump:game.level.cards.find((c,i)=>game.used&(1<<i)&&!(game.history.at(-1).used&(1<<i)))?.kind==='jump'};tone(game.lastPath.some(p=>p.portal)?'portal':'move');save();sync()}
document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>move(Number(b.dataset.dir)));$('undo').onclick=()=>{if(paused||anim||celebration)return;if(game.undo()){hintDir=null;resetConfirm=false;sync();save();tone('select')}else notice('This is the first step.')};$('reset').onclick=()=>{if(paused||anim||celebration)return;if(!resetConfirm&&game.moves>0){resetConfirm=true;notice('Tap restart again to start fresh.');return}let hinted=game.hinted;game.begin(game.day);game.hinted=hinted;launch()};$('hint').onclick=()=>{if(paused||anim||celebration)return;let path=game.hint();if(path?.length){game.select(path[0].card);hintDir=path[0].dir;notice('The glowing arrow is your next step.');sync();save()}else{notice('Undo a move to open a new route.');save()}};
$('album').onclick=()=>{if(anim||celebration)return;paused=true;book=true;panel('POSTCARDS FROM THE GARDEN','Your little collection.','Three stars: clear, no hint, perfect steps.');$('start').hidden=true;$('back').hidden=false;$('shop').hidden=false;for(let i=1;i<=Math.max(6,Math.min(24,game.profile.best+1));i++){let b=document.createElement('button');b.className='garden';b.setAttribute('aria-label','Garden '+i);b.innerHTML=i+'<small>'+('★'.repeat(game.profile.stars[i]||0)||'○')+'</small>';b.onclick=()=>{if(i>game.profile.best+1){notice('Complete the previous garden first.');$('copy').textContent='Complete the previous garden first.';return}if(started&&game.state==='play'&&game.moves>0&&b.dataset.confirm!=='yes'){b.dataset.confirm='yes';b.innerHTML='Restart?<small>Tap again</small>';return}game.begin(i);launch()};$('shop').appendChild(b)}sync()};$('back').onclick=()=>{book=false;if(game.state==='win')outcome();else if(started)launch();else{panel('A POCKET GARDEN PUZZLE','A little<br>way to bloom.','Pick a step card, then a direction.<br>Reach the flag. Take your time.');$('start').textContent='Into the garden →';if(saved)$('resume').hidden=false}};
let press=null,lastTouch=0;document.addEventListener('pointerdown',e=>{let b=e.target.closest('button');if(e.pointerType==='touch'&&b)press={b,id:e.pointerId,x:e.clientX,y:e.clientY}});document.addEventListener('pointerup',e=>{if(!press||e.pointerId!==press.id)return;let q=press;press=null;if(Math.hypot(e.clientX-q.x,e.clientY-q.y)<12&&e.target.closest('button')===q.b){lastTouch=performance.now();q.b.click()}});document.addEventListener('pointercancel',()=>press=null);document.addEventListener('click',e=>{if(e.isTrusted&&lastTouch&&performance.now()-lastTouch<700){e.preventDefault();e.stopImmediatePropagation()}},true);
window.addEventListener('keydown',e=>{let d={ArrowUp:0,KeyW:0,ArrowRight:1,KeyD:1,ArrowDown:2,KeyS:2,ArrowLeft:3,KeyA:3}[e.code];if(d!==undefined){e.preventDefault();move(d)}if(e.code==='KeyZ')$('undo').click();if(e.code==='KeyR')$('reset').click();if(e.code==='KeyH')$('hint').click();if(e.code==='KeyP'||e.code==='Escape')$('pause').click();if(e.code.startsWith('Digit')){let i=Number(e.code.at(-1))-1;if(i>=0&&i<game.level.cards.length&&!paused&&!anim){game.select(i);hintDir=null;sync()}}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&started&&!paused){paused=true;anim=null;if(game.state==='win')outcome();else{panel('A QUIET MOMENT','Take your time.','Your garden is saved.');$('start').textContent='Back to the garden →';save();sync()}}});
function iso(x,y){return{x:300+(x-y)*37,y:230+(x+y)*19}}function canvasInput(c){let down=null;function local(e){let r=c.getBoundingClientRect();return{x:(e.clientX-r.left-view.x)/view.s,y:(e.clientY-r.top-view.y)/view.s}}c.addEventListener('pointerdown',e=>{if(paused||anim||celebration)return;e.preventDefault();c.setPointerCapture(e.pointerId);down=local(e)});c.addEventListener('pointerup',e=>{if(!down||paused||anim)return;let q=local(e),dx=q.x-down.x,dy=q.y-down.y;if(Math.hypot(dx,dy)>25){let gx=dx/37+dy/19,gy=dy/19-dx/37;move(Math.abs(gx)>Math.abs(gy)?gx>0?1:3:gy>0?2:0)}else if(game.selected!==null){for(let d=0;d<4;d++){let t=transition(game.level,game.pos,game.level.cards[game.selected],d);if(!t)continue;let p=iso(t.x,t.y);if(Math.hypot(q.x-p.x,q.y-p.y)<25){move(d);break}}}down=null});c.addEventListener('pointercancel',()=>down=null)}
function oval(c,x,y,rx,ry,fill){c.beginPath();c.ellipse(x,y,Math.max(.1,rx),Math.max(.1,ry),0,0,Math.PI*2);c.fillStyle=fill;c.fill()}function line(c,x,y,a,b,fill,w=2){c.beginPath();c.moveTo(x,y);c.lineTo(a,b);c.strokeStyle=fill;c.lineWidth=w;c.lineCap='round';c.stroke()}function poly(c,pts,fill,stroke){c.beginPath();pts.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.closePath();c.fillStyle=fill;c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=1;c.stroke()}}function label(c,s,x,y,size,fill){c.font='bold '+size+'px Trebuchet MS';c.fillStyle=fill;c.textAlign='center';c.fillText(s,x,y)}
function flower(c,x,y,col,size=1){for(let i=0;i<5;i++){let a=i*Math.PI*.4;oval(c,x+Math.cos(a)*4*size,y+Math.sin(a)*3*size,3*size,2.5*size,col)}oval(c,x,y,2*size,1.6*size,'#efd39d')}
function tree(c,x,y,size,t){c.save();c.translate(x,y);c.scale(size,size);oval(c,9,6,22,9,'#55785a22');line(c,0,0,-1,-30,'#8e9b78',7);line(c,0,-15,12,-29,'#8e9b78',4);for(let [xx,yy,r]of[[-12,-43,19],[14,-40,18],[1,-57,21],[-1,-36,23]]){oval(c,xx,yy,r,r*.8,t);oval(c,xx-5,yy-6,r*.65,r*.5,'#dce5b22b')}for(let i=0;i<6;i++)oval(c,-15+i*6,-42+Math.sin(i)*10,2.5,3,'#f2dbaf44');c.restore()}
function scene(c){let t=themes[game.level.theme],g=c.createLinearGradient(0,0,0,640);g.addColorStop(0,t[1]);g.addColorStop(1,t[2]);c.fillStyle=g;c.fillRect(-700,-500,2000,1600);let light=c.createRadialGradient(155,85,0,155,85,350);light.addColorStop(0,'#fff4d25c');light.addColorStop(1,'#fff4d200');c.fillStyle=light;c.fillRect(-300,-300,1200,1000);
 for(let i=0;i<15;i++){let x=(i*83+time*3)%750-75,y=90+i*31;oval(c,x,y,28+i%3*12,5,'#f0edcf15')}
 // Distant garden hills and soft clouds frame the miniature without hiding its route.
 for(let i=0;i<4;i++){let x=20+i*175,y=130+i%2*28;poly(c,[[x-120,y+36],[x-70,y-10],[x-25,y+12],[x+30,y-32],[x+100,y+36]],t[4]+'13');poly(c,[[x-90,y+55],[x-50,y+8],[x+20,y-4],[x+75,y+55]],t[3]+'26')}
 for(let i=0;i<5;i++){let x=35+i*130+Math.sin(time*.08+i)*7,y=64+(i%3)*20;oval(c,x,y,38,8,'#f9f2dc28');oval(c,x-14,y-4,19,10,'#f9f2dc25');oval(c,x+15,y-3,23,8,'#f9f2dc25')}
 if(game.level.theme===3)for(let i=0;i<22;i++)oval(c,(i*71)%600,35+(i*43)%170,1.2,1.2,'#e5dcc86b');
 // A suspended pocket of earth, with layered stone and grass edges.
 oval(c,300,470,195,38,'#66887517');oval(c,300,449,164,26,'#78936e18');
 for(let sum=0;sum<=12;sum++)for(let y=0;y<7;y++){let x=sum-y,cell=game.level.grid[y]?.[x];if(!cell||cell===' ')continue;let p=iso(x,y),a=[[p.x,p.y-19],[p.x+37,p.y],[p.x,p.y+19],[p.x-37,p.y]];poly(c,[[p.x-37,p.y],[p.x,p.y+19],[p.x,p.y+43],[p.x-37,p.y+24]],'#acaf93');poly(c,[[p.x,p.y+19],[p.x+37,p.y],[p.x+37,p.y+24],[p.x,p.y+43]],'#859b85');for(let j=0;j<3;j++)line(c,p.x+10+j*8,p.y+26-j*4,p.x+16+j*8,p.y+22-j*4,'#c1c6a21c',1);
 let grass=cell==='S'?t[5]:cell==='W'?'#7fb3b1':t[3];poly(c,a,grass,'#d4dfb533');if(cell==='W'){poly(c,[[p.x,p.y-13],[p.x+27,p.y],[p.x,p.y+13],[p.x-27,p.y]],'#9dcccc');for(let k=0;k<2;k++)line(c,p.x-10+k*9,p.y-3+k*6,p.x+5+k*9,p.y-3+k*6,'#e2e7c955',1.5);if((x+y)%2===0){oval(c,p.x-13,p.y+2,7,3,'#698e74');flower(c,p.x-14,p.y-2,'#e7b9bc',.55)}}else if(cell==='S'){for(let k=0;k<10;k++){let xx=p.x+(k*11%43)-21,yy=p.y+(k*7%17)-8;oval(c,xx,yy,.9,.5,'#c2a36d')}line(c,p.x-12,p.y+7,p.x+5,p.y+7,'#dfbf8744',1)}else{for(let k=0;k<4;k++){let xx=p.x+(k*17%39)-19,yy=p.y+(k*9%15)-7;line(c,xx,yy,xx+2,yy-3,'#e5e8b144',1)}if((x*3+y)%7===0)flower(c,p.x-22,p.y,t[5],.35)}
 if(cell==='#'){poly(c,[[p.x-17,p.y],[p.x-12,p.y-22],[p.x+8,p.y-25],[p.x+21,p.y-8],[p.x+13,p.y+9]],'#8d9d8a');poly(c,[[p.x-17,p.y],[p.x-12,p.y-22],[p.x+3,p.y-15],[p.x+1,p.y+5]],'#b1b69c');poly(c,[[p.x-12,p.y-22],[p.x+8,p.y-25],[p.x+3,p.y-15]],'#cad0b0');oval(c,p.x+9,p.y-22,10,4,t[4]);flower(c,p.x+12,p.y-25,'#ebd5aa',.4)}
 if(cell==='P'){oval(c,p.x,p.y,21,10,'#76908055');for(let k=0;k<8;k++){let a=k*.785+time*.16;oval(c,p.x+Math.cos(a)*14,p.y+Math.sin(a)*7,7,4,'#c4a6c7')}oval(c,p.x,p.y,11,6,'#efd39c');oval(c,p.x,p.y,6,3,'#a08bb1');for(let k=0;k<3;k++){let a=time+k*2;oval(c,p.x+Math.cos(a)*19,p.y-8+Math.sin(a)*6,1.5,1.5,'#fff3c8')}}
 if(x===game.level.hole.x&&y===game.level.hole.y){oval(c,p.x,p.y,13,6,'#4c7464');oval(c,p.x,p.y,8,3,'#254e49');line(c,p.x+3,p.y-2,p.x+3,p.y-46,'#eee6bd',2.5);poly(c,[[p.x+3,p.y-46],[p.x+24,p.y-40+Math.sin(time*3)*1.5],[p.x+3,p.y-32]],'#dd9a79');flower(c,p.x-20,p.y-3,'#f6dbb1',.6)} }
 // Hand-built surroundings: cypresses, pergola, pots, woven fence and a little bench.
 for(let [x,y,s]of[[120,239,.85],[426,230,.8],[493,340,.7],[89,379,.65],[177,453,.45],[414,459,.55]])tree(c,x,y,s,t[4]);for(let x of [208,231,254]){line(c,x,190,x,163,'#9eaa86',3);line(c,x,180,x+18,189,'#aab390',3)}line(c,205,161,274,189,'#b7b596',5);for(let i=0;i<9;i++)flower(c,210+i*7,158+i*2.9,i%2?'#e6c49f':'#c7bbaa',.7);
 c.save();c.translate(458,404);poly(c,[[-18,-3],[9,-16],[32,-4],[5,9]],'#d8be99');line(c,-12,1,-12,12,'#83967e',3);line(c,25,-2,25,10,'#83967e',3);line(c,-19,-13,8,-27,'#ceb897',5);line(c,-19,-13,-19,-2,'#83967e',2);line(c,8,-27,8,-16,'#83967e',2);c.restore();
 for(let [x,y]of[[103,328],[388,197],[394,473]]){poly(c,[[x-8,y-12],[x+8,y-12],[x+6,y],[x-6,y]],'#b39b80');oval(c,x,y-12,8,3,'#d3ba91');tree(c,x,y-13,.35,t[4]);flower(c,x+1,y-31,'#ecc9b1',.6)}
 for(let i=0;i<5;i++){let x=115+i*79+Math.sin(time*.6+i)*12,y=180+Math.cos(time*.7+i)*12;oval(c,x,y,2.5,1.5,'#ebd0a0');oval(c,x-2,y-2,2,2,'#f8efca66')}
 let ink=game.level.theme===3?'#c7d8c0':t[4];label(c,themes[game.level.theme][0].toUpperCase(),300,513,10,ink);label(c,'PAR '+game.level.par+'  ·  '+game.moves+' STEPS',300,535,10,ink);
}
function ball(c,x,y,scale=1){oval(c,x+2,y+6,11,5,'#4b7a6833');let g=c.createRadialGradient(x-5,y-10,1,x,y-4,13);g.addColorStop(0,'#fffbea');g.addColorStop(1,skins[game.profile.skin]);oval(c,x,y-6,12*scale,12*scale,g);c.strokeStyle='#8da58c';c.lineWidth=1;c.stroke();oval(c,x-4,y-8,1.3,2,'#536f63');oval(c,x+4,y-8,1.3,2,'#536f63');c.beginPath();c.arc(x,y-4,2.2,0,Math.PI);c.strokeStyle='#7f9b7b';c.stroke();oval(c,x-8,y-3,2,1,'#deb9a555');oval(c,x+8,y-3,2,1,'#deb9a555');if(game.profile.skin===3){poly(c,[[x-7,y-16],[x-8,y-24],[x-3,y-20],[x,y-27],[x+3,y-20],[x+8,y-24],[x+7,y-16]],'#d4b36f')}}
new p5(p=>{p.setup=()=>{let host=$('host'),cv=p.createCanvas(host.clientWidth,host.clientHeight);cv.parent(host);p.pixelDensity(Math.min(devicePixelRatio,1.5));p.frameRate(45);canvasInput(cv.elt);new ResizeObserver(()=>p.resizeCanvas(host.clientWidth,host.clientHeight)).observe(host);sync()};p.draw=()=>{frame++;let now=performance.now(),dt=Math.min(.05,(now-last)/1000);last=now;if(!paused&&!document.hidden){time+=dt;if(noticeUntil&&time>noticeUntil){$('notice').textContent='';noticeUntil=0}if(anim){anim.elapsed+=dt;if(anim.elapsed>=anim.duration){anim=null;if(game.state==='win'){tone('win');celebration={t:0}}}}}if(celebration&&!paused){celebration.t+=dt;if(celebration.t>.8){celebration=null;outcome()}}let c=p.drawingContext,ratio=p.pixelDensity(),s=Math.min(p.width/490,p.height/570);view={s,x:(p.width-600*s)/2,y:(p.height-600*s)/2};c.save();c.setTransform(ratio,0,0,ratio,0,0);c.translate(view.x,view.y);c.scale(s,s);scene(c);if(!paused&&game.state==='play'&&!anim&&game.selected!==null){for(let d=0;d<4;d++){let r=transition(game.level,game.pos,game.level.cards[game.selected],d);if(!r)continue;let a=iso(game.pos.x,game.pos.y),z=iso(r.x,r.y);c.setLineDash([3,5]);line(c,a.x,a.y,z.x,z.y,hintDir===d?'#e9bf74':'#f8ecd19a',2);c.setLineDash([]);oval(c,z.x,z.y,15,9,hintDir===d?'#edc782bb':'#f5e7c85c');label(c,['↗','↘','↙','↖'][d],z.x,z.y+4,14,'#67896d')}}let bp=iso(game.pos.x,game.pos.y),height=0;if(anim){let t=Math.min(.999,anim.elapsed/anim.duration),n=anim.points.length-1,z=t*n,k=Math.floor(z),u=z-k,a=anim.points[k],b=anim.points[k+1];if(b.portal){bp=iso(u<.5?a.x:b.x,u<.5?a.y:b.y);height=8*Math.sin(u*Math.PI)}else{let aa=iso(a.x,a.y),bb=iso(b.x,b.y);bp={x:aa.x+(bb.x-aa.x)*u,y:aa.y+(bb.y-aa.y)*u};height=anim.jump?Math.sin(t*Math.PI)*35:Math.sin(u*Math.PI)*2}oval(c,bp.x,bp.y+4,13,5,'#7b937933')};if(game.state!=='win'||anim)ball(c,bp.x,bp.y-height);if(celebration){let z=celebration.t/.8;for(let j=0;j<16;j++){let a=j*Math.PI/8;flower(c,bp.x+Math.cos(a)*z*90,bp.y+Math.sin(a)*z*50-40*z,j%2?'#f4dfaa':'#e6bfb4',Math.max(.1,1-z))}label(c,'Lovely!',bp.x,bp.y-30-z*30,19,'#fff0c6')}c.restore()};});
window.puttDebug={game,getState:()=>({paused,started,anim:!!anim||!!celebration,time,view,rect:document.querySelector('canvas').getBoundingClientRect().toJSON(),snapshot:game.snapshot()})};
