(()=>{'use strict';
const $=s=>document.querySelector(s),canvas=$('#board'),ctx=canvas.getContext('2d'),W=540,H=600,KEY='chimeworks-v1';
let S={coins:0,total:0,stage:0,value:0,flow:0,auto:0,hits:0,slots:Array(12).fill(null)};try{const v=JSON.parse(localStorage.getItem(KEY));if(v&&Array.isArray(v.slots)&&v.slots.length===12)S={...S,...v}}catch{}
let selected='bell',balls=[],effects=[],sparks=[],clock=0,feed=0,last=performance.now(),acc=0,dropCd=0,sound=false,audio,rate=0,rateEarn=0,rateTime=0,toastTimer,saveTime=0,aim=W/2;
const sockets=Array.from({length:12},(_,i)=>({x:90+(i%3)*180+(Math.floor(i/3)%2?25:-25),y:145+Math.floor(i/3)*105,r:20}));
const base=Array.from({length:20},(_,i)=>({x:65+(i%5)*100+(Math.floor(i/5)%2?45:5),y:92+Math.floor(i/5)*112,r:9,kind:'peg',id:'p'+i}));
function save(){try{localStorage.setItem(KEY,JSON.stringify(S))}catch{}}function fmt(n){return n>=1e6?(n/1e6).toFixed(1)+'m':n>=10000?(n/1000).toFixed(1)+'k':Math.floor(n).toLocaleString('en-US')}
function cost(type){return Math.floor(type==='part'?15*Math.pow(1.48,S.slots.filter(Boolean).length):type==='auto'?30:type==='value'?45*Math.pow(1.7,S.value):60*Math.pow(1.7,S.flow))}
function goal(){return 800*Math.pow(2.6,S.stage)}function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),1900)}
function tone(kind,x){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=[261.63,293.66,329.63,392,440,523.25][Math.floor(x/90)%6]*(kind==='prism'?2:1);g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.23);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.25)}catch{}}
function earn(n,x,y){S.coins+=n;S.total+=n;rateEarn+=n;effects.push({x,y,t:.75,n});if(effects.length>45)effects.shift()}
function spawn(x=aim,split=false,parent){if(balls.length>=55)return;balls.push({x,y:split?parent.y:24,vx:split?(Math.random()>.5?85:-85):(Math.random()-.5)*70,vy:split?-140:35,r:7,age:0,m:parent?.m||1,split:split,contacts:new Map(),trail:[]})}
function drop(){if(dropCd>0)return;dropCd=.12;spawn();tone('drop',aim);$('#tip').textContent='Choose a part. Tap a glowing socket.'}
function install(i){if(S.slots[i]){toast('That socket is already fitted');return}const price=cost('part');if(S.coins<price){toast('Need '+fmt(price)+' brass');return}S.coins-=price;S.slots[i]=selected;const p=sockets[i];for(let j=0;j<24;j++)sparks.push({x:p.x,y:p.y,vx:(Math.random()-.5)*190,vy:(Math.random()-.5)*190,t:.65});tone('prism',p.x);toast(selected[0].toUpperCase()+selected.slice(1)+' installed');save();ui()}
function ui(){$('#coins').textContent=fmt(S.coins);$('#rate').textContent=rate.toFixed(1);$('#level').textContent=String(S.stage+1).padStart(2,'0');$('#parts').textContent=S.slots.filter(Boolean).length+' / 12';$('#hits').textContent=fmt(S.hits)+' chimes';$('#install span').firstChild.textContent='Install '+selected[0].toUpperCase()+selected.slice(1);$('#install b').textContent=fmt(cost('part'));$('#auto b').textContent=S.auto?'ON':fmt(cost('auto'));$('#auto').disabled=!!S.auto||S.coins<cost('auto');for(const t of ['value','flow']){$('#'+t+' b').textContent=fmt(cost(t));$('#'+t).disabled=S.coins<cost(t)||(t==='flow'&&!S.auto)}$('#goal').textContent='Earn '+fmt(goal())+' brass';$('#goalPct').textContent=Math.min(100,Math.floor(S.total/goal()*100))+'%';$('#progress').style.width=Math.min(100,S.total/goal()*100)+'%';$('#rebuild').disabled=S.total<goal();$('#rebuild span').textContent='Permanent ×'+Math.pow(2,S.stage+1)}
function tick(dt){clock+=dt;dropCd=Math.max(0,dropCd-dt);if(S.auto){feed+=dt;if(feed>=Math.max(.28,2.3*Math.pow(.78,S.flow))){feed=0;spawn(70+(Math.sin(clock*.7)+1)*200)}}const pegs=[...base,...sockets.map((p,i)=>S.slots[i]?{...p,kind:S.slots[i],id:'s'+i}:null).filter(Boolean)];
for(const b of [...balls]){b.age+=dt;b.vy+=360*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;b.vx*=Math.pow(.995,dt*60);if(b.x<22){b.x=22;b.vx=Math.abs(b.vx)*.8}if(b.x>W-22){b.x=W-22;b.vx=-Math.abs(b.vx)*.8}if(b.y<16){b.y=16;b.vy=Math.abs(b.vy)*.6}for(const p of pegs){let dx=b.x-p.x,dy=b.y-p.y,d=Math.hypot(dx,dy),rr=b.r+p.r;if(d<rr){if(d<.001){dx=1;dy=0;d=1}let nx=dx/d,ny=dy/d;b.x=p.x+nx*(rr+.5);b.y=p.y+ny*(rr+.5);const dot=b.vx*nx+b.vy*ny;if(dot<0){b.vx-=1.77*dot*nx;b.vy-=1.77*dot*ny;b.vx+=(Math.random()-.5)*18}if(clock-(b.contacts.get(p.id)??-10)>.22){b.contacts.set(p.id,clock);S.hits++;const n=(p.kind==='bell'?5:p.kind==='prism'?2:1)*(1+S.value)*Math.pow(2,S.stage)*b.m;earn(n,p.x,p.y);p.flash=1;flashes.set(p.id,clock);tone(p.kind,p.x);for(let j=0;j<4;j++)sparks.push({x:p.x,y:p.y,vx:(Math.random()-.5)*120,vy:-Math.random()*100,t:.35});if(p.kind==='boost'){b.vy=-290;b.vx+=(b.x<W/2?1:-1)*85}if(p.kind==='prism'&&!b.split){b.split=true;spawn(b.x,true,b)}}}}b.vx=Math.max(-330,Math.min(330,b.vx));b.vy=Math.max(-360,Math.min(520,b.vy));if(b.y>548){const bucket=Math.min(4,Math.max(0,Math.floor(b.x/(W/5))));earn((bucket===2?8:3)*(1+S.value)*Math.pow(2,S.stage)*b.m,b.x,552);balls.splice(balls.indexOf(b),1);tone('bell',b.x)}else if(b.age>18){earn(2*(1+S.value),b.x,b.y);balls.splice(balls.indexOf(b),1)}b.trail.push({x:b.x,y:b.y});if(b.trail.length>8)b.trail.shift()}
effects.forEach(e=>{e.t-=dt;e.y-=30*dt});effects=effects.filter(e=>e.t>0);sparks.forEach(p=>{p.t-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=100*dt});sparks=sparks.filter(p=>p.t>0);if(sparks.length>180)sparks.splice(0,sparks.length-180);rateTime+=dt;if(rateTime>=2){rate=rateEarn/rateTime;rateEarn=0;rateTime=0;ui()}saveTime+=dt;if(saveTime>=3){saveTime=0;save();ui()}}
const flashes=new Map();function circle(x,y,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}function line(x,y,x2,y2,color,width=1){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke()}function text(t,x,y,size,color){ctx.font='bold '+size+'px Trebuchet MS';ctx.fillStyle=color;ctx.textAlign='center';ctx.fillText(t,x,y)}
function draw(){ctx.clearRect(0,0,W,H);let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#173540');g.addColorStop(1,'#0b202b');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let y=20;y<540;y+=30)for(let x=20;x<W;x+=30)circle(x,y,1,'#33525b');ctx.strokeStyle='#846d4b';ctx.lineWidth=3;ctx.strokeRect(14,12,W-28,H-25);for(const x of [23,W-23])for(const y of [21,H-22]){circle(x,y,4,'#a58962');line(x-2,y,x+2,y,'#433c32',1)}
ctx.save();ctx.translate(aim,29);ctx.fillStyle='#6b8790';ctx.fillRect(-16,-30,32,21);ctx.fillStyle='#c29b60';ctx.fillRect(-21,-10,42,10);ctx.fillStyle='#eac589';ctx.beginPath();ctx.moveTo(-18,0);ctx.lineTo(18,0);ctx.lineTo(8,13);ctx.lineTo(-8,13);ctx.fill();ctx.restore();for(let i=0;i<12;i++){const p=sockets[i];if(!S.slots[i]){ctx.setLineDash([3,5]);ctx.strokeStyle=S.coins>=cost('part')?'#b799625c':'#52697060';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,23,0,7);ctx.stroke();ctx.setLineDash([]);text('+',p.x,p.y+5,17,'#77909b')}}
for(const p of [...base,...sockets.map((p,i)=>S.slots[i]?{...p,kind:S.slots[i],id:'s'+i}:null).filter(Boolean)]){const flash=Math.max(0,1-(clock-(flashes.get(p.id)??-10))*4);if(flash){circle(p.x,p.y,p.r+12*flash,'#ffdba42a');ctx.strokeStyle='#ffd89c';ctx.globalAlpha=flash;ctx.beginPath();ctx.arc(p.x,p.y,p.r+18*(1-flash),0,7);ctx.stroke();ctx.globalAlpha=1}circle(p.x+2,p.y+4,p.r+2,'#06182090');const col=p.kind==='prism'?'#7ed4c7':p.kind==='boost'?'#c595da':'#f1c17a';g=ctx.createRadialGradient(p.x-4,p.y-6,1,p.x,p.y,p.r+2);g.addColorStop(0,'#fff1cf');g.addColorStop(.3,col);g.addColorStop(1,p.kind==='peg'?'#765736':'#806d50');circle(p.x,p.y,p.r,g);ctx.strokeStyle='#fff1b870';ctx.lineWidth=1;ctx.beginPath();ctx.arc(p.x,p.y,p.r-3,0,7);ctx.stroke();if(p.kind!=='peg'){text(p.kind==='bell'?'◉':p.kind==='boost'?'↟':'◇',p.x,p.y+6,23,'#28414c')}}
for(let i=0;i<5;i++){const x=i*W/5;ctx.fillStyle=i===2?'#775836':'#29414c';ctx.fillRect(x+4,549,W/5-8,36);text(i===2?'×8':'×3',x+W/10,573,15,i===2?'#f7d298':'#adc4cb');line(x+4,548,x+W/5-4,548,'#b2915e',3)}
for(const b of balls){for(let j=0;j<b.trail.length;j++)circle(b.trail[j].x,b.trail[j].y,2+j*.35,'#ffd48a'+Math.floor(8+j*5).toString(16).padStart(2,'0'));circle(b.x,b.y,b.r+3,'#f5b65724');g=ctx.createRadialGradient(b.x-2,b.y-3,1,b.x,b.y,7);g.addColorStop(0,'#fff6cf');g.addColorStop(.6,b.split?'#94e7d0':'#ffcc6b');g.addColorStop(1,'#a76b30');circle(b.x,b.y,7,g);line(b.x-2,b.y-3,b.x-2,b.y+2,'#fffbe3',1)}for(const p of sparks){ctx.globalAlpha=Math.min(1,p.t*3);circle(p.x,p.y,2,'#ffe6ac')}ctx.globalAlpha=1;for(const e of effects){ctx.globalAlpha=Math.min(1,e.t*2);text('+'+fmt(e.n),e.x,e.y-12,14,'#ffde9b')}ctx.globalAlpha=1;
const rotor=clock*(S.auto?2:.5);for(const x of [50,490]){ctx.save();ctx.translate(x,594);ctx.rotate(rotor);ctx.strokeStyle='#b6935f';ctx.lineWidth=3;for(let i=0;i<8;i++){ctx.rotate(Math.PI/4);ctx.strokeRect(-4,-24,8,13)}circle(0,0,16,'#506572');circle(0,0,6,'#c4a273');ctx.restore()}}
function resize(){const d=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(W*d);canvas.height=Math.round(H*d);ctx.setTransform(d,0,0,d,0,0)}resize();window.addEventListener('resize',resize);
canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*W,y=(e.clientY-r.top)/r.height*H;const i=sockets.findIndex(p=>Math.hypot(x-p.x,y-p.y)<38);if(i>=0){install(i);return}aim=Math.max(40,Math.min(W-40,x));drop()});$('#drop').onclick=drop;document.addEventListener('keydown',e=>{if(e.code==='Space'&&!$('#guide').open){e.preventDefault();drop()}});document.querySelectorAll('[data-kind]').forEach(el=>el.onclick=()=>{selected=el.dataset.kind;document.querySelectorAll('[data-kind]').forEach(b=>b.classList.toggle('selected',b===el));ui()});$('#install').onclick=()=>{const i=S.slots.indexOf(null);if(i<0){toast('All sockets fitted');return}install(i)};
for(const type of ['auto','value','flow'])$('#'+type).onclick=()=>{const price=cost(type);if(S.coins<price||(type==='flow'&&!S.auto))return;S.coins-=price;S[type]++;toast(type==='auto'?'Feeder is running':type==='value'?'Every hit pays more':'Faster drops');tone('prism',250);save();ui()};$('#rebuild').onclick=()=>{if(S.total<goal())return;S.stage++;S.coins=35;S.total=0;S.value=0;S.flow=0;S.auto=0;S.slots=Array(12).fill(null);balls=[];toast('Workshop '+(S.stage+1)+' · permanent ×'+Math.pow(2,S.stage));save();ui()};$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent='♫ '+(sound?'On':'Off');tone('bell',150)};$('#help').onclick=()=>$('#guide').showModal();$('#close').onclick=()=>$('#guide').close();document.addEventListener('visibilitychange',()=>{save();last=performance.now();acc=0});
function frame(now){let dt=Math.min(.05,(now-last)/1000);last=now;if(!document.hidden&&!$('#guide').open){acc+=dt;while(acc>=1/120){tick(1/120);acc-=1/120}draw()}requestAnimationFrame(frame)}ui();requestAnimationFrame(frame);window.__chime={get state(){return S},get balls(){return balls},sockets,advance(t){for(let i=0;i<t*120;i++)tick(1/120);ui();draw()}};
})();
