(()=>{'use strict';
const $=id=>document.getElementById(id),canvas=$('world'),overlay=$('overlay'),panel=$('panel'),KEY='doodle-drive-v1',COLORS=['#f49676','#f1cf69','#81bca9','#8ca5ce','#ba9dc8','#f8f3df'];Art.init(canvas);
let meta={records:[],unlocked:1,paint:Array(200).fill(null),hub:0,mute:false,active:null},storage=true;try{let o=JSON.parse(localStorage.getItem(KEY)||'null');if(o&&Array.isArray(o.records)){meta={...meta,...o};meta.records=meta.records.slice(0,8).map(r=>r&&Array.isArray(r.medals)?{medals:r.medals.slice(0,3).map(Boolean),best:Number.isFinite(r.best)?r.best:1e6}:null);meta.unlocked=Doodle.clamp(+meta.unlocked||1,1,8);meta.paint=Array.from({length:200},(_,i)=>typeof o.paint?.[i]==='string'&&/^#[0-9a-f]{6}$/i.test(o.paint[i])?o.paint[i]:null);meta.hub=Doodle.clamp(+meta.hub||0,0,2);}}catch{storage=false;}
let g;try{g=meta.active?Doodle.Engine.restore(meta.active):new Doodle.Engine();}catch{g=new Doodle.Engine();meta.active=null;}Art.paint=meta.paint;Art.hub=meta.hub;Sound.mute=meta.mute;
let paused=true,menu='home',keys=new Set(),pointers=new Map(),toast='',toastLife=0,acc=0,last=performance.now(),savedAt=0,resultShown=false,brush=COLORS[0],paintUndo=[],paintDrag=null,garageReturn=null,garageMap=null;
function total(){return meta.records.reduce((n,r)=>n+(r?r.medals.filter(Boolean).length:0),0);}
function persist(){meta.active=g.snapshot();meta.paint=Art.paint.slice();meta.hub=Art.hub;meta.mute=Sound.mute;try{localStorage.setItem(KEY,JSON.stringify(meta));storage=true;}catch{storage=false;}}
function clearInput(){keys.clear();pointers.clear();paintDrag=null;g.input={drive:0,squish:false,float:false};for(let id of ['left','right','squish','float'])$(id).classList.remove('pressed');}
function input(){let vals=[...pointers.values()],left=keys.has('a')||keys.has('arrowleft')||vals.includes('left'),right=keys.has('d')||keys.has('arrowright')||vals.includes('right');return{drive:(right?1:0)-(left?1:0),squish:keys.has('s')||keys.has('arrowdown')||vals.includes('squish'),float:keys.has(' ')||keys.has('w')||keys.has('arrowup')||vals.includes('float')};}
function bind(id,fn){let el=$(id);if(!el)return;let start=null;el.addEventListener('pointerdown',e=>{start={id:e.pointerId,x:e.clientX,y:e.clientY};e.stopPropagation();try{el.setPointerCapture(e.pointerId);}catch{}});el.addEventListener('pointerup',e=>{if(start&&start.id===e.pointerId&&Math.hypot(e.clientX-start.x,e.clientY-start.y)<14)fn();start=null;});el.addEventListener('pointercancel',()=>start=null);el.addEventListener('click',e=>{e.preventDefault();if(e.detail===0)fn();});}
function show(type,html){paused=true;menu=type;clearInput();Sound.stop();overlay.hidden=false;panel.innerHTML=html;panel.scrollTop=0;}
function resume(){Sound.init();clearInput();paused=false;menu=null;overlay.hidden=true;last=performance.now();acc=0;persist();}
function start(i,remix=0){g=new Doodle.Engine(i,remix);resultShown=false;Art.fx=[];Art.focus(g);toast=g.plan.name;toastLife=2;resume();hud();}
function home(){show('home',`<span class="eyebrow">A LITTLE SOFT ADVENTURE</span><h1>doodle<br>DRIVE!</h1><canvas id="title-car" class="title-car" aria-hidden="true"></canvas><div class="lesson"><b>◀ ▶</b><span>A squishy car. A scribbly world.</span></div><div class="lesson"><b>⇣⇡</b><span>Squeeze through. Float over.</span></div><button class="primary" id="play">${meta.active&&g.state==='play'?'KEEP ROLLING':'LET’S ROLL →'}</button><div class="row"><button id="book">ROUTE BOOK</button><button id="garage">PAINT MY CAR</button></div><div class="row"><button id="help">HOW TO</button></div><span class="status-small">${total()}/24 badges · ${storage?'Saved on this device':'Storage unavailable · session play'}</span>`);Art.preview($('title-car'));bind('play',()=>{if(meta.active&&g.state==='play')resume();else start(0);});bind('book',book);bind('garage',()=>garage(home));bind('help',()=>help(home));}
function help(back){show('help',`<span class="eyebrow">HOLD. SQUISH. WHOOSH.</span><h2>IT’S SOFT.</h2><div class="lesson"><b>◀ ▶</b><span>Hold an arrow to drive.<br>Keyboard: A / D or left / right.</span></div><div class="lesson"><b>⇣⇡</b><span>Hold SQUISH before a low tunnel.<br>Keyboard: S / down.</span></div><div class="lesson"><b>♧</b><span>Hold FLOAT over a gap.<br>Keyboard: Space / W / up.</span></div><div class="lesson"><b>↶</b><span>Stuck? Recall to the last flag.<br>Keyboard: R. Stars stay collected.</span></div><p>Balloon fuel refills on the road. Yellow pads bounce you. No lives, no time limit.</p><button class="primary" id="back">GOT IT</button>`);bind('back',back);}
function book(){show('book',`<span class="eyebrow">THE FLIPBOOK</span><h2>EIGHT LITTLE TRIPS.</h2><div class="book">${Doodle.LEVELS.map((l,i)=>`<button id="level${i}" ${i>=meta.unlocked?'disabled':''}>${i<meta.unlocked?i+1:'⌑'}<small>${meta.records[i]?meta.records[i].medals.map(v=>v?'★':'☆').join(''):'☆☆☆'}</small></button>`).join('')}</div><p>★ Finish · ★ Find three stars · ★ Clean & quick</p><div class="row"><button id="back">BACK</button><button id="garage">MY CAR</button></div>${meta.records[7]?'<button class="primary" id="remix">WINDY REMIX ↗</button>':''}<span class="status-small">Star wheels at 6 badges · Spiral wheels at 12</span>`);for(let i=0;i<8;i++)bind('level'+i,()=>{if(i<meta.unlocked){if(meta.active&&g.state==='play'&&g.time>3)confirmStart(i);else start(i);}});bind('back',home);bind('garage',()=>garage(book));bind('remix',()=>start(0,1));}
function confirmStart(i){show('confirm',`<span class="eyebrow">A FRESH PAGE?</span><h2>TRIP ${i+1}</h2><p>Your badges and car painting stay. This starts a new ride.</p><button id="yes" class="primary">LET’S GO</button><button id="back">BACK</button>`);bind('yes',()=>start(i));bind('back',book);}
function pausePanel(){show('pause',`<span class="eyebrow">PARKED FOR A MOMENT</span><h2>TAKE A BREATHER.</h2><p>${g.index+1}. ${g.plan.name}</p><button id="resume" class="primary">KEEP ROLLING</button><div class="row"><button id="garage">PAINT MY CAR</button><button id="help">HOW TO</button></div><div class="row"><button id="book">ROUTE BOOK</button><button id="photo">POSTCARD ↓</button></div>`);bind('resume',resume);bind('garage',()=>garage(pausePanel));bind('help',()=>help(pausePanel));bind('book',book);bind('photo',postcard);}
function pause(){if(paused)return;clearInput();persist();pausePanel();}
function win(){let fresh=!resultShown;resultShown=true;let m=g.medals();if(!g.remix){let r=meta.records[g.index];meta.records[g.index]={medals:m.map((v,i)=>v||!!r?.medals[i]),best:Math.min(r?.best||1e9,g.time)};meta.unlocked=Math.max(meta.unlocked,Math.min(8,g.index+2));}persist();show('result',`<span class="eyebrow">ONE HAPPY LITTLE CAR</span><h2>NAILED IT!</h2><div class="medals">${m.map(x=>x?'★':'☆').join('')}</div><div class="stats"><div>${g.time.toFixed(1)}s<small>ROAD TIME</small></div><div>${g.starred.filter(Boolean).length}/3<small>STARS FOUND</small></div><div>${g.resets}<small>RECALLS</small></div></div><p>Finish ${m[0]?'★':'☆'} · Stars ${m[1]?'★':'☆'} · Under ${g.plan.par}s, ≤1 recall ${m[2]?'★':'☆'}</p><button class="primary" id="next">${g.index<7?'NEXT LITTLE TRIP →':'WINDY REMIX →'}</button><div class="row"><button id="retry">REPLAY</button><button id="garage">MY CAR</button><button id="book">BOOK</button></div><button id="photo">SAVE POSTCARD ↓</button><p class="status-small">${total()}/24 badges ${total()>=12?'· Spiral wheels unlocked':total()>=6?'· Star wheels unlocked':''}</p>`);bind('next',()=>g.index<7?start(g.index+1,g.remix):start(0,g.remix+1));bind('retry',()=>start(g.index,g.remix));bind('garage',()=>garage(win));bind('book',book);bind('photo',postcard);if(fresh)Sound.play({type:'win'});}
function garage(back){garageReturn=back;show('garage',`<span class="eyebrow">THE LITTLE PAINT SHOP</span><h2>MAKE IT YOURS.</h2><canvas id="paint" class="garage-canvas" aria-label="Draw on the car body"></canvas><div class="swatches">${COLORS.map((color,i)=>`<button aria-label="${['Coral','Honey','Mint','Blue','Lavender','Cream'][i]} paint" id="color${i}" style="background:${color}" ${color===brush?'class="selected"':''}></button>`).join('')}</div><div class="row"><button id="erase">ERASER</button><button id="undo">UNDO</button><button id="clear">CLEAR</button></div><div class="chips"><button id="hub0">SPOKES</button><button id="hub1" ${total()<6?'disabled':''}>★ 6 BADGES</button><button id="hub2" ${total()<12?'disabled':''}>◎ 12 BADGES</button></div><p class="status-small">Draw on the body. Your car keeps it on every trip.</p><button class="primary" id="back">DONE ✓</button>`);paintUndo=[];garageMap=Art.preview($('paint'));for(let i=0;i<6;i++)bind('color'+i,()=>{brush=COLORS[i];updateSwatch();});bind('erase',()=>{brush=null;updateSwatch();});bind('undo',()=>{if(paintUndo.length){Art.paint=paintUndo.pop();garageMap=Art.preview($('paint'));persist();Art.render(g,0);}});bind('clear',()=>{paintUndo.push(Art.paint.slice());if(paintUndo.length>25)paintUndo.shift();Art.paint=Array(200).fill(null);garageMap=Art.preview($('paint'));persist();Art.render(g,0);});for(let i=0;i<3;i++)bind('hub'+i,()=>{if(i===0||total()>=i*6){Art.hub=i;garageMap=Art.preview($('paint'));persist();Art.render(g,0);}});bind('back',()=>{persist();Art.render(g,0);garageReturn();});
let can=$('paint');function dot(e){let r=can.getBoundingClientRect(),x=(e.clientX-r.x-garageMap.cx)/garageMap.s,y=(e.clientY-r.y-garageMap.cy)/garageMap.s,col=Math.floor((x+48)/4.8),row=Math.floor((y+45)/5);if(col>=0&&col<20&&row>=0&&row<10){Art.paint[row*20+col]=brush;garageMap=Art.preview(can);}}
can.addEventListener('pointerdown',e=>{e.preventDefault();paintUndo.push(Art.paint.slice());if(paintUndo.length>25)paintUndo.shift();paintDrag=e.pointerId;can.setPointerCapture(e.pointerId);dot(e);});can.addEventListener('pointermove',e=>{if(paintDrag===e.pointerId)dot(e);});let end=e=>{if(paintDrag===e.pointerId){paintDrag=null;persist();Art.render(g,0);}};can.addEventListener('pointerup',end);can.addEventListener('pointercancel',end);}
function updateSwatch(){for(let i=0;i<6;i++)$('color'+i).classList.toggle('selected',COLORS[i]===brush);$('erase').classList.toggle('selected',brush===null);}
function postcard(){let out=document.createElement('canvas');out.width=1000;out.height=760;let c=out.getContext('2d');c.fillStyle='#fff9ec';c.fillRect(0,0,1000,760);let dw=920,dh=Math.min(555,dw*canvas.height/canvas.width);c.drawImage(canvas,40,85,dw,dh);c.fillStyle='#2f4038';c.font='900 40px "Comic Sans MS","Chalkboard SE","Trebuchet MS",sans-serif';c.fillText('doodle DRIVE!',40,58);c.font='900 22px Arial';c.fillText(`${g.index+1}. ${g.plan.name}`,40,695);c.font='16px Arial';c.fillText(`${g.time.toFixed(1)}s · ${g.starred.filter(Boolean).length}/3 stars · ${g.resets} recalls`,40,730);out.toBlob(blob=>{if(!blob)return;let u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='doodle-drive-postcard.png';a.click();setTimeout(()=>URL.revokeObjectURL(u),3000);});}
function hud(){$('route').textContent=String(g.index+1).padStart(2,'0')+' / 08';$('stars').textContent=g.starred.map(x=>x?'★':'☆').join('');$('progress').querySelector('i').style.width=Doodle.clamp(g.car.x/g.plan.end*100,0,100)+'%';$('fuel').style.transform=`scaleX(${g.fuel/1.9})`;$('toast').textContent=toastLife>0?toast:'';$('sound').textContent=Sound.mute?'♪̸':'♪';$('sound').setAttribute('aria-label',Sound.mute?'Enable sound':'Mute sound');let it=input();for(let id of ['left','right','squish','float'])$(id).classList.toggle('pressed',!paused&&(id==='left'?it.drive<0:id==='right'?it.drive>0:it[id]));$('hint').textContent=g.time<4&&g.index===0?'HOLD ▶ · FOLLOW THE STARS':it.squish?'NICE AND SMALL':it.float&&g.fuel>0?'UP, UP…':g.fuel<.3?'LAND TO REFILL':g.index===1&&g.car.x<650?'HOLD SQUISH FOR THE TUNNEL':'↶ RECALL ANYTIME';$('hint').style.opacity=g.time<8||it.squish||it.float||g.fuel<.3?'1':'.5';}
for(let id of ['left','right','squish','float']){let el=$(id);el.addEventListener('pointerdown',e=>{e.preventDefault();if(paused)return;Sound.init();pointers.set(e.pointerId,id);el.setPointerCapture(e.pointerId);if(id==='squish'||id==='float')Sound.play({type:id==='float'?'puff':'squish'});hud();});let end=e=>{pointers.delete(e.pointerId);hud();};el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);el.addEventListener('contextmenu',e=>e.preventDefault());}
bind('recall',()=>{if(!paused){g.recall();persist();}});bind('pause',()=>{if(!paused)pause();});bind('sound',()=>{Sound.init();Sound.mute=!Sound.mute;if(Sound.mute)Sound.stop();persist();hud();});$('brand').addEventListener('click',e=>{e.preventDefault();if(!paused)pause();});
document.addEventListener('keydown',e=>{let k=e.key.toLowerCase();if(k==='escape'){e.preventDefault();if(!paused)pause();else if(menu==='pause')resume();return;}if(paused)return;if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys.add(k);if(k==='r'&&!e.repeat){g.recall();persist();}if(!e.repeat&&(k===' '||k==='s')){Sound.init();Sound.play({type:k===' '?'puff':'squish'});}});document.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
window.addEventListener('resize',()=>{clearInput();Art.resize();Art.focus(g);Art.render(g,0);if(menu==='garage')garageMap=Art.preview($('paint'));if(menu==='home'&&$('title-car'))Art.preview($('title-car'));});window.addEventListener('blur',()=>{Sound.stop();if(!paused)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){Sound.stop();if(!paused)pause();}});window.addEventListener('pagehide',()=>{clearInput();persist();});
function frame(now){let dt=Math.min(.05,(now-last)/1000);last=now;if(!paused){acc+=dt;while(acc>=1/60){g.update(1/60,input());acc-=1/60;}for(let e of g.events.splice(0)){Art.event(e);Sound.play(e);if(e.type==='star'){toast='GOT IT!';toastLife=.8;}if(e.type==='spring'){toast='BOING!';toastLife=.8;}if(e.type==='flag'){toast='CHECKPOINT ✓';toastLife=1.1;}if(e.type==='recall'){Art.focus(g);toast='BACK ON TRACK';toastLife=1;}}Art.render(g,dt);toastLife=Math.max(0,toastLife-dt);hud();if(now-savedAt>1000){persist();savedAt=now;}if(g.state==='won'&&!resultShown)win();}requestAnimationFrame(frame);}
Art.focus(g);Art.render(g,0);if(g.state==='won')win();else home();hud();requestAnimationFrame(frame);
window.doodleInspect=()=>({game:g.snapshot(),car:{...g.car},paused,menu,storage,meta:JSON.parse(JSON.stringify(meta)),camera:{...Art.cam,s:Art.s},held:pointers.size,voices:Sound.voices.length});
})();
