(()=>{
 'use strict';
 const E=WeaveEngine,L=WeaveLevels.levels,C=WeaveLevels.chapters,A=WeaveArt,$=id=>document.getElementById(id),canvas=$('board'),SAVE='pip-and-pea-v1',reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 let data={version:1,completed:{},best:{},gold:{},charm:0,sound:false,index:0,game:null,history:[],usedHint:false,guide:null};
 try{const d=JSON.parse(localStorage.getItem(SAVE));if(d?.version===1&&Number.isInteger(d.index)&&d.index>=0&&d.index<L.length&&d.game?.w===12&&d.game?.h===12&&Array.isArray(d.game.birds)&&Array.isArray(d.game.grid)&&d.game.birds.length>0&&d.game.birds.every(b=>Array.isArray(b.body)&&b.body.every(p=>Array.isArray(p)&&Number.isFinite(p[0])&&Number.isFinite(p[1]))))data={...data,...d}}catch{}
 let index=data.index,state=data.game?E.clone(data.game):E.clone(L[index].initial),history=data.history||[],usedHint=!!data.usedHint,guide=data.guide,started=false,panelType='intro',hintPage=0,winTimer=0,winAward=null,toastTimer=0,lastMove=0;
 const view={positions:{},departures:[],shake:0},particles=[];let t=0,frameTime=performance.now(),audio=null,musicTimer=0;
 const collected=()=>Object.keys(data.completed).length;
 const unlocked=c=>c===0||Object.keys(data.completed).filter(i=>L[i]?.chapter===c-1).length>=4;
 const charmUnlocked=n=>n===0||collected()>=[0,4,10,18][n];
 if(!charmUnlocked(data.charm))data.charm=0;E.settle(state);
 function save(){data.index=index;data.game=E.clone(state);data.history=history.slice(-100);data.usedHint=usedHint;data.guide=guide;try{localStorage.setItem(SAVE,JSON.stringify(data))}catch{}}
 function tone(freq,len=.1,vol=.024,type='triangle',delay=0,end=freq){if(!data.sound||!audio)return;try{const o=audio.createOscillator(),g=audio.createGain(),at=audio.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,at);o.frequency.exponentialRampToValueAtTime(end,at+len);g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(vol,at+.009);g.gain.exponentialRampToValueAtTime(.0001,at+len);o.connect(g);g.connect(audio.destination);o.start(at);o.stop(at+len+.03)}catch{}}
 function sound(kind){if(kind==='walk')tone(205+(state.moves%5)*12,.075,.012,'sine',0,170);if(kind==='eat'){tone(640,.08,.032,'triangle',0,920);tone(1050,.15,.018,'sine',.045,700)}if(kind==='land')tone(126,.12,.024,'sine',0,77);if(kind==='push')tone(185,.09,.016,'triangle',0,140);if(kind==='home')[392,523,659].forEach((f,i)=>tone(f,.25,.025,'triangle',i*.06));if(kind==='win')[523,659,784,1047].forEach((f,i)=>tone(f,.32,.03,'triangle',i*.1));if(kind==='oops')tone(350,.22,.022,'sine',0,180);if(kind==='undo'){tone(500,.1,.02,'sine',0,290);tone(330,.14,.016,'triangle',.06)}}
 function music(){clearTimeout(musicTimer);if(!data.sound)return;let at=0;const patterns=[[196,0,294,0,247,0,330,0],[220,0,330,0,262,0,392,0],[196,0,262,0,294,0,392,0]];function beat(){if(!data.sound)return;const notes=patterns[L[index].chapter];if(!document.hidden){const f=notes[at++%notes.length];if(f)tone(f,.8,.0055,'sine')}musicTimer=setTimeout(beat,900)}beat()}
 const wantedSound=data.sound;data.sound=false;$('sound').setAttribute('aria-pressed','false');
 async function toggleSound(){data.sound=!data.sound;if(data.sound){try{audio??=new(window.AudioContext||window.webkitAudioContext)();await audio.resume();music();tone(523,.12,.025)}catch{data.sound=false}}else clearTimeout(musicTimer);$('sound').setAttribute('aria-pressed',data.sound);$('sound').setAttribute('aria-label',data.sound?'Mute sound':'Enable sound');save()}
 function puff(pos,color,n=10){for(let i=0;i<n;i++){const a=i/n*Math.PI*2;particles.push({x:pos[0]*32+16,y:pos[1]*32+16,vx:Math.cos(a)*(18+Math.random()*25),vy:Math.sin(a)*(18+Math.random()*25)-10,life:.5+Math.random()*.3,max:.8,size:2+(i%2),color})}}
 function message(text,ms=2000){clearTimeout(toastTimer);$('burst').textContent=text;$('burst').classList.add('show');toastTimer=setTimeout(()=>$('burst').classList.remove('show'),ms)}
 function select(id){if(panelType||state.failed||state.won)return;const b=state.birds.find(b=>b.id===id&&!b.done);if(!b)return;state.active=id;update();save()}
 function switchBird(){const live=state.birds.filter(b=>!b.done);if(live.length<2)return;const at=live.findIndex(b=>b.id===state.active);select(live[(at+1)%live.length].id)}
 function update(){const lv=L[index],ch=lv.chapter;$('place').textContent=C[ch].place;$('place').style.color=C[ch].color;$('levelName').textContent=lv.name;$('levelNumber').innerHTML=String(index+1).padStart(2,'0')+' <i>/ 18</i>';$('moves').textContent=state.moves;$('best').textContent=data.best[index]!=null?'BEST '+data.best[index]+' · GOLD '+lv.solution.length+' OR LESS':'A fresh little adventure';
  $('snacks').innerHTML='<span style="color:#d98e98">●</span> <b>'+state.fruit.length+'</b> TO NIBBLE';$('homeState').textContent=state.fruit.length?'HOME IS SLEEPING':'HOME IS READY';document.querySelector('.snack-status').classList.toggle('ready',!state.fruit.length);
  $('hintText').textContent=state.failed?'A little tumble. Undo brings you back.':guide?'Follow the golden arrow. Take your time.':state.birds.length>1?'Tap a friend to switch. Bring both home.':index===0?'Swipe to waddle. Fruit makes you longer.':'Nibble the fruit. Keep a tail on land.';$('hintText').classList.toggle('lost-hint',state.failed);
  $('undo').disabled=!history.length;$('birds').classList.toggle('solo',state.birds.length===1);$('birds').innerHTML=state.birds.map(b=>'<button data-bird="'+b.id+'" aria-label="Play as '+['Pip','Pea','Plum'][b.id]+'" '+(b.done?'disabled':'')+' class="'+(b.id===state.active?'selected ':'')+(b.done?'home':'')+'"><canvas id="bird-'+b.id+'" width="64" height="64"></canvas><small>'+['PIP','PEA','PLUM'][b.id]+(b.done?' ✓':'')+'</small></button>').join('');state.birds.forEach(b=>{A.portrait($('bird-'+b.id),b.color,data.charm);document.querySelector('[data-bird="'+b.id+'"]').onclick=()=>select(b.id)});
  $('chapterText').textContent=C[ch].name;$('pips').innerHTML=L.filter(l=>l.chapter===ch).map(l=>'<i class="'+(data.completed[L.indexOf(l)]?'done':'')+'"></i>').join('');$('collection').textContent=collected()+' / 18 MEADOW MOMENTS';
  const next=guide?lv.solution[guide.at]:null;document.querySelectorAll('[data-dir]').forEach(b=>{const preferred=next&&Number(b.dataset.dir)===next[1];b.style.borderColor=preferred?'#eacb83':'';b.style.boxShadow=preferred?'0 0 12px #eacb8344':''})}
 function show(type,html){panelType=type;$('panel').innerHTML=html;$('modal').hidden=false;$('panel').scrollTop=0}
 function hide(){panelType=null;$('modal').hidden=true;canvas.focus({preventScroll:true})}
 function panelHero(){if($('hero'))A.hero($('hero'),data.charm)}
 function intro(){show('intro','<small class="eyebrow">A LITTLE STRETCH. A LITTLE WONDER.</small><div class="intro-logo">PIP <i>&</i> <b>PEA</b></div><canvas id="hero" class="hero"></canvas><p>Nibble. Stretch.<br>Find your way home.</p><button class="primary" id="start">'+(data.game?'KEEP WADDLING →':"LET’S WADDLE →")+'</button><button class="secondary" id="chooseIntro">MEADOW JOURNAL</button><small class="intro-foot">18 little adventures · Undo anytime · No timer</small>');panelHero();$('start').onclick=start;$('chooseIntro').onclick=journal}
 async function start(){started=true;hide();if(wantedSound&&!audio&&!data.sound)await toggleSound();update();if(state.won)victory();save()}
 function load(i,allow=false){if(!allow&&!unlocked(L[i].chapter))return;clearTimeout(winTimer);clearTimeout(toastTimer);$('burst').classList.remove('show');winAward=null;index=i;state=E.clone(L[i].initial);E.settle(state);history=[];usedHint=false;guide=null;hintPage=0;view.positions={};view.departures=[];view.shake=0;particles.length=0;started=true;hide();update();save()}
 function record(){const was=collected();data.completed[index]=true;data.best[index]=Math.min(data.best[index]??Infinity,state.moves);if(!usedHint&&state.moves<=L[index].solution.length)data.gold[index]=true;save();return{was,now:collected()}}
 function act(dir){if(!started||panelType||state.won||state.failed)return false;const id=state.active,before=state,result=E.move(state,id,dir);lastMove=performance.now();if(!result.changed){view.shake=reduced?0:.7;return false}history.push({state:E.clone(state),guide:guide?{...guide}:null});if(history.length>100)history.shift();state=result.s;sound('walk');
  for(const event of result.events){if(event.type==='eat'){sound('eat');puff(event.pos,'#f1ce98',15);view.shake=reduced?0:1;message('MUNCH! A LITTLE LONGER.',1200)}if(event.type==='push')sound('push');if(event.type==='land'){sound('land');view.shake=reduced?0:.9;const b=state.birds.find(b=>b.id===state.active);if(b&&!b.done)puff(b.body.at(-1),'#829d77',5)}if(event.type==='home'){sound('home');puff(event.pos,'#e6cf8d',20);view.departures.push({bird:before.birds.find(b=>b.id===event.bird),body:event.body,life:.65,max:.65})}}
  if(before.fruit.length&&!state.fruit.length){message('HOME IS READY!',1900);puff(state.nest,'#f2d88f',16)}if(state.failed){sound('oops');message('A LITTLE TUMBLE. TRY UNDO.',2400);view.shake=reduced?0:1.5}
  if(guide){const next=L[index].solution[guide.at];if(next?.[0]===id&&next?.[1]===dir){guide.at++;if(guide.at>=L[index].solution.length)guide=null;else state.active=L[index].solution[guide.at][0]}else{guide=null;message('A new path! Hints are still here.')}}
  if(state.won)winAward=record();update();save();if(state.won){sound('win');for(let i=0;i<42;i++)particles.push({x:40+Math.random()*300,y:35+Math.random()*200,vx:(Math.random()-.5)*44,vy:-15+Math.random()*20,life:1.8,max:1.8,size:2,color:['#edce8f','#b8cca3','#dba8b9','#a6bed4'][i%4]});winTimer=setTimeout(()=>{if(state.won&&!panelType)victory()},650)}return true}
 function undo(){if(!history.length)return;if(panelType==='win')hide();else if(panelType)return;clearTimeout(winTimer);const snap=history.pop();state=snap.state;guide=snap.guide;view.departures=[];sound('undo');for(const b of state.birds)if(!b.done)puff(b.body[0],'#bba4ca',6);update();save()}
 function restart(){clearTimeout(winTimer);winAward=null;state=E.clone(L[index].initial);E.settle(state);history=[];guide=null;usedHint=false;hintPage=0;view.positions={};view.departures=[];particles.length=0;hide();update();save();message('A fresh little adventure.')}
 function victory(){const stats=winAward||record();winAward=null;const gold=!!data.gold[index],newCharm=[4,10,18].includes(stats.now)&&stats.was<stats.now;update();show('win','<small class="eyebrow">A MEADOW MOMENT, FOUND</small><canvas id="hero" class="hero"></canvas><h2>'+['A lovely little stretch.','Home under the moon.','Better, together.'][L[index].chapter]+'</h2><p>'+L[index].name+'</p><div class="win-stats"><div><b>'+state.moves+'</b><small>STEPS</small></div><div><b>'+(gold?'◆':'◇')+'</b><small>'+(gold?'GOLDEN FEATHER':'HOME SAFE')+'</small></div><div><b>'+collected()+'/18</b><small>FOUND</small></div></div>'+(newCharm?'<div class="reward">NEW BIRD CHARM · '+['','Sprout crown','Moon feather','Golden crown'][[0,4,10,18].indexOf(stats.now)]+'</div>':'')+(collected()===18?'<p class="all-done">Every little adventure, shared.<br>Revisit your favorites for golden feathers.</p>':'')+'<button class="primary" id="next">'+(index===17?'OPEN THE JOURNAL →':'ONE MORE LITTLE ADVENTURE →')+'</button><button class="secondary" id="again">WADDLE AGAIN</button><button class="secondary" id="winUndo">↶ UNDO & TRY A NEW PATH</button>');panelHero();$('next').onclick=()=>index===17||!unlocked(L[index+1].chapter)?journal():load(index+1);$('again').onclick=restart;$('winUndo').onclick=undo}
 function journal(){let html='<button class="close" id="closePanel" aria-label="Close journal">×</button><small class="eyebrow">THE LITTLE MEADOW JOURNAL</small><h2>Little journeys.<br>Lovely company.</h2><div class="album-progress">'+collected()+' / 18 moments · '+Object.keys(data.gold).length+' golden feathers</div><div class="feather-row">';['○','♧','☾','♛'].forEach((v,i)=>html+='<button data-charm="'+i+'" class="'+(data.charm===i?'selected':'')+'" '+(!charmUnlocked(i)?'disabled':'')+' aria-label="'+['Plain birds','Sprout crown. Unlock at four moments','Moon feather. Unlock at ten moments','Golden crown. Unlock at eighteen moments'][i]+'">'+v+'</button>');html+='</div>';
  C.forEach((ch,c)=>{html+='<div class="chapter-title"><strong>'+String(c+1).padStart(2,'0')+' · '+ch.name+'</strong><small>'+L.filter((l,i)=>l.chapter===c&&data.completed[i]).length+'/6</small></div>';if(!unlocked(c))html+='<div class="locked-chapter">Find four moments in the previous garden to visit.</div>';else{html+='<div class="level-grid">';L.forEach((l,i)=>{if(l.chapter===c)html+='<button data-level="'+i+'" class="'+(i===index?'current':'')+'"><i>'+(data.gold[i]?'◆':data.completed[i]?'✓':'')+'</i><b>'+String(i+1).padStart(2,'0')+'</b><small>'+l.name+'</small></button>'});html+='</div>'}});
  const daily=(Math.floor(Date.now()/86400000)*7+5)%L.length;html+='<button class="daily" id="daily">TODAY’S LITTLE STRETCH · '+L[daily].name+' →</button><button class="secondary" id="backJournal">BACK TO WADDLING</button>';show('journal',html);$('closePanel').onclick=$('backJournal').onclick=()=>{if(!started)intro();else if(state.won)victory();else hide()};document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>load(Number(b.dataset.level)));document.querySelectorAll('[data-charm]').forEach(b=>b.onclick=()=>{data.charm=Number(b.dataset.charm);save();journal()});$('daily').onclick=()=>load(daily,true)}
 function hints(){if(!started){help();return}usedHint=true;save();show('hints','<button class="close" id="closePanel" aria-label="Close hint">×</button><small class="eyebrow">A GENTLE LITTLE NUDGE</small><h2>A different little curl.</h2><p>'+L[index].hints[hintPage]+'</p><div class="hint-options"><button id="moreHint">'+(hintPage<2?'A LITTLE MORE →':'FIRST HINT ↻')+'</button><button id="backHint">LET ME THINK</button></div><p class="help-note">Or follow a golden trail from a fresh board.<br>You still make every move. Friends switch automatically.</p><button class="secondary" id="trail">RESTART WITH A STEP-BY-STEP TRAIL</button>');$('closePanel').onclick=$('backHint').onclick=hide;$('moreHint').onclick=()=>{hintPage=(hintPage+1)%3;hints()};$('trail').onclick=()=>{restart();usedHint=true;guide={at:0};state.active=L[index].solution[0][0];update();save();message('Follow the golden arrow.')}}
 function help(){show('help','<button class="close" id="closePanel" aria-label="Close help">×</button><small class="eyebrow">SMALL BIRDS. BIG LITTLE ADVENTURES.</small><h2>Nibble. Stretch.<br>Think together.</h2><div class="steps"><div><b>01 · NIBBLE</b><span>Swipe or use the arrows. Each fruit grows your tail by one tile.</span></div><div><b>02 · STRETCH</b><span>One piece of your body resting on land keeps the whole bird up. Curl into a bridge or climb a little step.</span></div><div><b>03 · SHARE</b><span>Tap Pip or Pea to switch. You can stand on a friend, or push their whole body.</span></div><div><b>04 · GO HOME</b><span>Collect every fruit, then bring every friend to the glowing nest.</span></div></div><div class="legend"><span>NO TIMER</span><span>NO LIFE LIMIT</span><span>UNDO ANYTIME</span></div><p class="help-note">Thorns and long falls mean a tumble; Undo restores the exact board.<br>Fruit can support a bird until it is eaten. Z undoes. Q switches friends.</p><button class="primary" id="backHelp">GOT IT →</button>');$('closePanel').onclick=$('backHelp').onclick=()=>{if(!started)intro();else if(state.won)victory();else hide()}}
 function resetConfirm(){if(state.won){restart();return}show('reset','<small class="eyebrow">A FRESH LITTLE ADVENTURE</small><h2>Start this garden over?</h2><p>Your collected moments stay safe.</p><button class="primary" id="confirmReset">A FRESH START →</button><button class="secondary" id="cancelReset">KEEP WADDLING</button>');$('confirmReset').onclick=restart;$('cancelReset').onclick=hide}
 $('sound').onclick=toggleSound;$('journal').onclick=journal;$('brand').onclick=e=>{e.preventDefault();journal()};$('help').onclick=help;$('hint').onclick=hints;$('undo').onclick=undo;$('reset').onclick=resetConfirm;
 let touchButton=null,lastTouchAt=0;document.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'){lastTouchAt=0;return}const b=e.target.closest('button,a');touchButton=b&&!b.dataset.dir?{b,x:e.clientX,y:e.clientY}:null},true);document.addEventListener('pointerup',e=>{if(e.pointerType!=='touch'||!touchButton)return;const q=touchButton;touchButton=null;const b=e.target.closest('button,a');if(q.b===b&&!b.disabled&&Math.hypot(e.clientX-q.x,e.clientY-q.y)<12){e.preventDefault();lastTouchAt=performance.now();b.click()}},true);document.addEventListener('pointercancel',()=>touchButton=null,true);document.addEventListener('click',e=>{if(e.isTrusted&&e.detail>0&&performance.now()-lastTouchAt<800){e.preventDefault();e.stopImmediatePropagation()}},true);
 let held=null,repeatTimer=0;function stopHeld(){clearTimeout(repeatTimer);held=null}function hold(d){stopHeld();held=d;act(d);repeatTimer=setTimeout(function again(){if(held===null)return;act(held);repeatTimer=setTimeout(again,180)},320)}document.querySelectorAll('[data-dir]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);hold(Number(b.dataset.dir))});['pointerup','pointercancel','lostpointercapture'].forEach(n=>b.addEventListener(n,stopHeld))});
 let pointer=null;canvas.addEventListener('pointerdown',e=>{if(!started||panelType)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);pointer={id:e.pointerId,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false}});canvas.addEventListener('pointermove',e=>{if(!pointer||pointer.id!==e.pointerId)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y,threshold=Math.max(18,canvas.getBoundingClientRect().width/12*.65);if(Math.max(Math.abs(dx),Math.abs(dy))<threshold)return;act(Math.abs(dx)>Math.abs(dy)?dx>0?1:3:dy>0?2:0);pointer.x=e.clientX;pointer.y=e.clientY;pointer.moved=true});canvas.addEventListener('pointerup',e=>{if(!pointer)return;const q=pointer;pointer=null;if(!q.moved&&Math.hypot(e.clientX-q.startX,e.clientY-q.startY)<12){const box=canvas.getBoundingClientRect(),gx=(e.clientX-box.x)/box.width*12,gy=(e.clientY-box.y)/box.height*12;const b=state.birds.find(b=>!b.done&&b.body.some(p=>Math.abs(p[0]+.5-gx)<.65&&Math.abs(p[1]+.5-gy)<.65));if(b)select(b.id)}});canvas.addEventListener('pointercancel',()=>pointer=null);
 const keys={ArrowUp:0,w:0,ArrowRight:1,d:1,ArrowDown:2,s:2,ArrowLeft:3,a:3};document.addEventListener('keydown',e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;if(k in keys){e.preventDefault();if(e.repeat&&performance.now()-lastMove<140)return;act(keys[k])}else if(k==='z'){e.preventDefault();if(!e.repeat)undo()}else if(k==='q'&&!panelType){e.preventDefault();if(!e.repeat)switchBird()}else if(k==='Tab'&&!panelType&&started&&(document.activeElement===canvas||document.activeElement===document.body)){e.preventDefault();switchBird()}else if(k==='r'&&!e.repeat&&started&&!panelType)resetConfirm();else if(k==='Escape'&&panelType&&panelType!=='intro'&&panelType!=='win'){e.preventDefault();if(!started)intro();else hide()}});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){stopHeld();pointer=null;save()}frameTime=performance.now()});window.addEventListener('blur',()=>{stopHeld();pointer=null;save()});
 function frame(now){requestAnimationFrame(frame);if(document.hidden)return;const rate=now-lastMove<400||particles.length||view.departures.length?16:32;if(now-frameTime<rate)return;const dt=Math.min((now-frameTime)/1000,.06);frameTime=now;t+=dt;const aliveKeys=new Set();for(const b of state.birds)if(!b.done)for(let i=0;i<b.body.length;i++){const key=b.id+'-'+i,p=b.body[i];aliveKeys.add(key);let v=view.positions[key];if(!v)v=view.positions[key]=[...p];const f=reduced?1:1-Math.exp(-dt*22);v[0]+=(p[0]-v[0])*f;v[1]+=(p[1]-v[1])*f}for(const key of Object.keys(view.positions))if(!aliveKeys.has(key))delete view.positions[key];view.shake*=Math.exp(-dt*12);for(let i=view.departures.length-1;i>=0;i--){view.departures[i].life-=dt;if(view.departures[i].life<=0)view.departures.splice(i,1)}for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=dt*35;if(p.life<=0)particles.splice(i,1)}A.draw(canvas,state,L[index].chapter,t,view,particles,data.charm,L[index].initial.fruit,guide?L[index].solution[guide.at]:null)}
 update();intro();requestAnimationFrame(frame);
 window.__weave={get state(){return state},get data(){return data},get history(){return history},get index(){return index},get guide(){return guide},get panel(){return panelType},start,move:act,select,switchBird,load,undo,restart,hints,journal,help,save,engine:E,levels:L};
})();
