(function(root){'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
const plots=[['keep',0,0],['farm',-3.8,3.8],['farm',3.8,3.8],['tower',-4,-3.8],['tower',4,-3.8],['gate',0,-6],['gate',-7,0],['gate',7,0],['barracks',-4,.5],['smith',4,.5],['tower',-7,3],['tower',7,3]];
const names={keep:'Royal keep',farm:'Windmill & fields',tower:'Archer tower',gate:'Palisade',barracks:'Guard quarters',smith:'Royal forge'};
const costs={keep:9,farm:4,tower:5,gate:4,barracks:6,smith:7};
const perks=[{id:'harvest',name:'Golden harvest',line:'+3 gold every dawn',icon:'sun'},{id:'reach',name:'Longbow king',line:'Attack farther · +3 damage',icon:'bow'},{id:'stone',name:'Stone & steel',line:'+40 keep health · stronger walls',icon:'shield'}];
function maxhp(b,s){return b.type==='keep'?120+b.level*40+(s.perks.includes('stone')?40:0):b.type==='gate'?60+b.level*35+(s.perks.includes('stone')?35:0):35+b.level*20}
function fresh(meta={}){const s={v:1,phase:'day',night:1,gold:17,perks:[],buildings:plots.map((p,id)=>({id,type:p[0],x:p[1],z:p[2],level:id===0?1:0,hp:0,cd:0})),p:{x:0,z:2,hp:70,angle:0,cd:0,dash:0,boost:0,down:0,flash:0},enemies:[],troops:[],coins:[],shots:[],spawn:[],clock:0,kills:0,rally:false,uid:0,earned:0,lastIncome:0,meta:{best:Number(meta.best)||0,wins:Number(meta.wins)||0,mute:!!meta.mute},checkpoint:null};s.buildings[0].hp=maxhp(s.buildings[0],s);return s}
function cost(b){return costs[b.type]*(b.level+1)}
function income(s){return 7+s.buildings.filter(b=>b.type==='farm'&&b.hp>0).reduce((v,b)=>v+3+b.level*2,0)+(s.perks.includes('harvest')?3:0)}
function event(events,type,o={}){events.push({type,...o})}
function buy(s,id,events=[]){const b=s.buildings[id];if(s.phase!=='day'||!b)return false;if(b.level&&b.hp<maxhp(b,s)-.1){const c=Math.max(1,Math.ceil((maxhp(b,s)-b.hp)/20));if(s.gold<c)return false;s.gold-=c;b.hp=maxhp(b,s);event(events,'build',{x:b.x,z:b.z,repair:true});return true}if(b.level>=3||s.gold<cost(b))return false;s.gold-=cost(b);b.level++;b.hp=maxhp(b,s);event(events,'build',{x:b.x,z:b.z});return true}
function troops(s){const b=s.buildings.find(b=>b.type==='barracks');s.troops=[];if(b.level&&b.hp>0)for(let i=0;i<2+b.level;i++)s.troops.push({id:++s.uid,x:b.x+(i%2)*.8,z:b.z+Math.floor(i/2)*.7,hp:32+b.level*10,max:32+b.level*10,cd:0,angle:0,flash:0})}
function wave(s){const n=s.night,arr=[],count=Math.min(40,4+n*3),lanes=n<=2?[0]:n<=4?[0,n%2?1:2]:[0,1,2];for(let i=0;i<count;i++){const lane=lanes[i%lanes.length],type=n>=3&&i%7===6?'brute':n>=2&&i%5===3?'archer':'raider';arr.push({at:i*(n<3?1.15:.82)+1,lane,type})}if(n%6===0)arr.push({at:6,lane:0,type:'boss'});return arr}
function start(s,events=[]){if(s.phase!=='day')return false;s.checkpoint=JSON.stringify({...s,checkpoint:null});s.phase='night';s.clock=0;s.spawn=wave(s);s.enemies=[];s.shots=[];s.coins=[];s.p.hp=70;s.p.down=0;s.p.dash=0;troops(s);event(events,'night');return true}
function spawn(s,q,events){const pos=[{x:0,z:-12},{x:-13,z:0},{x:13,z:0}][q.lane],n=s.night,k=q.type,hp=k==='boss'?160+n*5:k==='brute'?45+n*3:k==='archer'?17+n*2:14+n*2,e={id:++s.uid,type:k,lane:q.lane,x:pos.x+((s.uid%3)-1)*.65,z:pos.z,hp,max:hp,cd:0,flash:0,wind:0,angle:0};s.enemies.push(e);event(events,'spawn',{x:e.x,z:e.z})}
function damage(s,e,n,events){if(e.hp<=0)return;e.hp-=n;e.flash=.1;event(events,'hit',{x:e.x,z:e.z,n});if(e.hp<=0){s.kills++;s.coins.push({id:++s.uid,x:e.x,z:e.z,value:e.type==='boss'?10:e.type==='brute'?3:1});event(events,'kill',{x:e.x,z:e.z,big:e.type==='boss'||e.type==='brute'})}}
function shot(s,a,b,damage,owner){let d=dist(a,b)||1;s.shots.push({x:a.x,z:a.z,dx:(b.x-a.x)/d*15,dz:(b.z-a.z)/d*15,life:d/15+.15,damage,owner,target:b.id})}
function charge(s,events=[]){if(s.phase!=='night'||s.p.down>0||s.p.dash>0)return false;s.p.dash=4;s.p.boost=.6;for(const e of s.enemies)if(e.hp>0&&dist(e,s.p)<3.5)damage(s,e,25+forge(s)*4,events);event(events,'charge',{x:s.p.x,z:s.p.z});return true}
function forge(s){const b=s.buildings.find(b=>b.type==='smith');return b.hp>0?b.level:0}
function dawn(s,events){const coins=s.coins.reduce((v,c)=>v+c.value,0);s.gold+=coins;s.coins=[];s.lastIncome=income(s);s.gold+=s.lastIncome;s.earned+=s.lastIncome+coins;s.meta.best=Math.max(s.meta.best,s.night);if(s.night%6===0)s.meta.wins++;s.night++;s.phase=(s.night===4||s.night===7)&&s.perks.length<(s.night===4?1:2)?'reward':'day';s.enemies=[];s.shots=[];s.spawn=[];s.p.hp=70;s.p.down=0;s.p.boost=0;for(const b of s.buildings)if(b.level)b.hp=Math.min(maxhp(b,s),Math.max(1,b.hp)+maxhp(b,s)*.3);troops(s);event(events,'dawn',{income:s.lastIncome,coins})}
function pick(s,id,events=[]){if(s.phase!=='reward'||!perks.some(p=>p.id===id)||s.perks.includes(id))return false;s.perks.push(id);if(id==='stone')for(const b of s.buildings)if(b.level)b.hp=Math.min(maxhp(b,s),b.hp+40);s.phase='day';event(events,'reward');return true}
function step(s,input,dt,events=[]){dt=clamp(dt,0,.05);if(!['night','day'].includes(s.phase))return;s.p.flash=Math.max(0,s.p.flash-dt);s.p.dash=Math.max(0,s.p.dash-dt);s.p.boost=Math.max(0,s.p.boost-dt);s.p.cd=Math.max(0,s.p.cd-dt);s.p.down=Math.max(0,s.p.down-dt);
let dx=input.x||0,dz=input.z||0,d=Math.hypot(dx,dz);if(d>1){dx/=d;dz/=d}if(s.p.down<=0){const speed=s.p.boost>0?13:5.5;s.p.x=clamp(s.p.x+dx*speed*dt,-12,12);s.p.z=clamp(s.p.z+dz*speed*dt,-11,10);if(d>.08)s.p.angle=Math.atan2(dx,dz)}if(s.phase==='day')return;s.clock+=dt;while(s.spawn.length&&s.spawn[0].at<=s.clock)spawn(s,s.spawn.shift(),events);
if(s.p.hp<=0&&s.p.down<=0){s.p.hp=70;s.p.x=0;s.p.z=2;s.p.down=4;event(events,'down')}
const smith=forge(s),reach=s.perks.includes('reach')?5:2.8;if(s.p.down<=0&&s.p.cd<=0){let e=s.enemies.filter(e=>e.hp>0&&dist(e,s.p)<reach).sort((a,b)=>dist(a,s.p)-dist(b,s.p))[0];if(e){s.p.cd=.52;s.p.angle=Math.atan2(e.x-s.p.x,e.z-s.p.z);if(reach>3)shot(s,s.p,e,12+smith*4,'ally');else{damage(s,e,10+smith*4,events);event(events,'slash',{x:s.p.x,z:s.p.z,angle:s.p.angle})}}}
for(const b of s.buildings){b.cd=Math.max(0,b.cd-dt);if(b.type==='tower'&&b.level&&b.hp>0&&b.cd<=0){const e=s.enemies.filter(e=>e.hp>0&&dist(e,b)<6+b.level).sort((a,c)=>dist(a,b)-dist(c,b))[0];if(e){b.cd=1-.1*b.level;shot(s,b,e,8+b.level*4,'ally')}}}
for(const t of s.troops){if(t.hp<=0)continue;t.cd=Math.max(0,t.cd-dt);t.flash=Math.max(0,t.flash-dt);const e=s.enemies.filter(e=>e.hp>0&&dist(e,t)<(s.rally?4:8)).sort((a,b)=>dist(a,t)-dist(b,t))[0],goal=s.rally?{x:s.p.x+(t.id%3-1)*.9,z:s.p.z+1.3}:e||{x:(t.id%3-1)*1.2,z:-2},dd=dist(t,goal);if(dd>1){t.x+=(goal.x-t.x)/dd*3.8*dt;t.z+=(goal.z-t.z)/dd*3.8*dt;t.angle=Math.atan2(goal.x-t.x,goal.z-t.z)}if(e&&dist(e,t)<1.5&&t.cd<=0){t.cd=.8;damage(s,e,8+smith*2,events)}}
for(const e of s.enemies){if(e.hp<=0)continue;e.cd=Math.max(0,e.cd-dt);e.flash=Math.max(0,e.flash-dt);e.wind=Math.max(0,e.wind-dt);const gate=s.buildings[[5,6,7][e.lane]],keep=s.buildings[0];let target=gate.level&&gate.hp>0?gate:keep;const nearby=s.buildings.filter(b=>b.id!==0&&b.level&&b.hp>0&&dist(e,b)<3).sort((a,b)=>dist(e,a)-dist(e,b))[0];if(nearby)target=nearby;const ally=s.troops.filter(t=>t.hp>0&&dist(t,e)<2.8).sort((a,b)=>dist(e,a)-dist(e,b))[0];if(ally)target=ally;else if(s.p.down<=0&&dist(e,s.p)<(e.type==='boss'?5:3.2))target=s.p;const dd=dist(e,target),range=e.type==='archer'?5:e.type==='boss'?2:1.2,speed=e.type==='boss'?1.35:e.type==='brute'?1.7:e.type==='archer'?2:2.5;e.angle=Math.atan2(target.x-e.x,target.z-e.z);if(dd>range){e.x+=(target.x-e.x)/dd*speed*dt;e.z+=(target.z-e.z)/dd*speed*dt}else if(e.cd<=0){e.cd=e.type==='boss'?2.5:1.25;e.wind=.3;if(e.type==='archer')shot(s,e,target,4,'enemy');else{const damage=e.type==='boss'?13:e.type==='brute'?7:3;if(target!==s.p||s.p.boost<=0){target.hp-=damage;target.flash=.12;event(events,'hurt',{x:target.x,z:target.z,castle:target===keep})}}}}
for(const q of s.shots){q.life-=dt;q.x+=q.dx*dt;q.z+=q.dz*dt;if(q.owner==='ally'){const e=s.enemies.find(e=>e.id===q.target&&e.hp>0);if(e&&dist(e,q)<.6){damage(s,e,q.damage,events);q.life=0}}else{const candidates=[s.p,...s.troops,...s.buildings.filter(b=>b.level&&b.hp>0)],t=candidates.find(t=>t.hp>0&&dist(t,q)<.65);if(t&&(t!==s.p||s.p.down<=0)){if(t!==s.p||s.p.boost<=0)t.hp-=q.damage;t.flash=.1;q.life=0}}}s.shots=s.shots.filter(q=>q.life>0);s.enemies=s.enemies.filter(e=>e.hp>0);for(let i=s.coins.length-1;i>=0;i--){const c=s.coins[i];if(s.p.down<=0&&dist(c,s.p)<2){s.gold+=c.value;event(events,'coin',{x:c.x,z:c.z,n:c.value});s.coins.splice(i,1)}}
if(s.buildings[0].hp<=0){s.phase='lost';event(events,'lost');return}if(!s.spawn.length&&!s.enemies.length)dawn(s,events)}
function retry(s){if(!s.checkpoint)return fresh(s.meta);const r=restore(JSON.parse(s.checkpoint));r.meta={...s.meta};return r}
function restore(s){if(!s||s.v!==1||!Array.isArray(s.buildings)||s.buildings.length!==12||!['day','night','reward','lost'].includes(s.phase))return fresh();for(const b of s.buildings){if(!Number.isFinite(b.hp)||!Number.isFinite(b.x)||!Number.isFinite(b.z)||b.level<0||b.level>3)return fresh()}return s}
const api={fresh,plots,names,cost,income,maxhp,buy,start,step,charge,pick,perks,retry,restore,wave};if(typeof module!=='undefined')module.exports=api;root.Keep=api;
})(typeof window!=='undefined'?window:globalThis);
