(function(root){'use strict';const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));class ShakeGame{constructor(level=1){this.level=clamp(level|0,1,999);this.state='ready';this.time=0;this.limit=27-Math.min(7,(this.level-1)*.4);this.input={x:0,z:0};this.tilt={x:0,z:0};this.seed=713+this.level*177;this.events=[];this.count=8+Math.min(4,Math.floor((this.level-1)/2));this.saved=0;this.bonks=0;this.open=false;this.openTime=0;this.chain=0;this.lastExit=-10;this.maxChain=0;this.impactDelay=0;let flip=this.level%2===0?-1:1;this.cells=[{x:-1.65*flip,z:1.65,on:false},{x:1.65*flip,z:-.25,on:false},{x:-1.4*flip,z:-2.2,on:false}];this.bumpers=[{x:-.68*flip,z:-.25,r:.39},{x:.8*flip,z:1.05,r:.39}];if(this.level>=4)this.bumpers.push({x:.7*flip,z:-1.75,r:.32});this.bodies=Array.from({length:this.count},(_,i)=>({x:(i%4-1.5)*.67,z:1.75+Math.floor(i/4)*.61,y:0,vx:0,vz:0,vy:0,spin:0,roll:0,squish:0,ejected:false,fly:0,color:i%12}));}
random(){this.seed=(1664525*this.seed+1013904223)>>>0;return this.seed/4294967296;}setInput(x,z){this.input.x=clamp(Number(x)||0,-1,1);this.input.z=clamp(Number(z)||0,-1,1);if(this.state==='ready'&&(Math.abs(x)+Math.abs(z)>.03)){this.state='playing';this.events.push({type:'start'})}}
impact(b,speed){if(speed<1.1)return;b.squish=Math.min(.45,speed*.05);b.vy=Math.max(b.vy,Math.min(2.8,speed*.35));b.spin+=(this.random()-.5)*speed*1.4;this.bonks++;if(this.impactDelay<=0){this.events.push({type:'bonk',x:b.x,z:b.z,power:speed});this.impactDelay=.11;}}
step(dt){dt=clamp(dt,0,.025);if(this.state!=='playing')return;this.time+=dt;this.impactDelay-=dt;this.tilt.x+=(this.input.x-this.tilt.x)*Math.min(1,dt*12);this.tilt.z+=(this.input.z-this.tilt.z)*Math.min(1,dt*12);if(this.open)this.openTime+=dt;
for(let b of this.bodies){if(b.ejected){b.fly+=dt;continue;}b.squish*=Math.exp(-dt*10);b.spin*=Math.exp(-dt*.8);b.roll+=b.spin*dt;b.vx+=this.tilt.x*12*dt;b.vz+=this.tilt.z*12*dt;if(this.open){let dx=-b.x,dz=-3.5-b.z,d=Math.hypot(dx,dz);b.vx+=dx/Math.max(.1,d)*dt*7;b.vz+=dz/Math.max(.1,d)*dt*7;}b.vx*=Math.exp(-dt*1.1);b.vz*=Math.exp(-dt*1.1);let speed=Math.hypot(b.vx,b.vz);if(speed>7.5){b.vx*=7.5/speed;b.vz*=7.5/speed}b.x+=b.vx*dt;b.z+=b.vz*dt;b.vy-=dt*8;b.y+=b.vy*dt;if(b.y<0){b.y=0;b.vy=Math.abs(b.vy)>.4?-b.vy*.25:0;}if(Math.abs(b.x)>2.28){b.x=clamp(b.x,-2.28,2.28);this.impact(b,Math.abs(b.vx));b.vx*=-.78;}if(b.z>3.17){b.z=3.17;this.impact(b,Math.abs(b.vz));b.vz*=-.78;}if(this.open&&b.z<-3.02&&Math.abs(b.x)<.83){b.ejected=true;b.fly=0;this.saved++;this.chain=this.time-this.lastExit<.8?this.chain+1:1;this.lastExit=this.time;this.maxChain=Math.max(this.maxChain,this.chain);this.events.push({type:'eject',x:b.x,z:b.z,chain:this.chain});continue;}if(b.z< -3.17){b.z=-3.17;this.impact(b,Math.abs(b.vz));b.vz*=-.8;}for(let p of this.bumpers){let dx=b.x-p.x,dz=b.z-p.z,d=Math.hypot(dx,dz),r=p.r+.27;if(d<r){let nx=d>.001?dx/d:1,nz=d>.001?dz/d:0;b.x=p.x+nx*r;b.z=p.z+nz*r;let dot=b.vx*nx+b.vz*nz;if(dot<0){this.impact(b,-dot+1);b.vx-=dot*2.1*nx;b.vz-=dot*2.1*nz;}}}for(let c of this.cells)if(!c.on&&Math.hypot(b.x-c.x,b.z-c.z)<.56){c.on=true;this.events.push({type:'cell',x:c.x,z:c.z,count:this.cells.filter(c=>c.on).length});}}
// Two position/impulse passes resolve the soft crewmate swarm.
for(let pass=0;pass<2;pass++)for(let i=0;i<this.bodies.length;i++)for(let j=i+1;j<this.bodies.length;j++){let a=this.bodies[i],b=this.bodies[j];if(a.ejected||b.ejected)continue;let dx=b.x-a.x,dz=b.z-a.z,d=Math.hypot(dx,dz);if(d<.55){let nx=d>.001?dx/d:1,nz=d>.001?dz/d:0,p=(.55-d)*.5;a.x-=nx*p;a.z-=nz*p;b.x+=nx*p;b.z+=nz*p;let dot=(b.vx-a.vx)*nx+(b.vz-a.vz)*nz;if(dot<0){let k=-dot*.84;a.vx-=k*nx;a.vz-=k*nz;b.vx+=k*nx;b.vz+=k*nz;if(pass===0){this.impact(a,-dot);this.impact(b,-dot)}}}}
if(!this.open&&this.cells.every(c=>c.on)){this.open=true;this.events.push({type:'open'});}if(this.saved===this.count){this.state='won';this.input={x:0,z:0};this.events.push({type:'won'});}else if(this.time>=this.limit){this.state='lost';this.input={x:0,z:0};this.events.push({type:'lost'});}}
drain(){let v=this.events;this.events=[];return v;}}
root.ShakeGame=ShakeGame;if(typeof module!=='undefined')module.exports=ShakeGame;})(typeof window==='undefined'?globalThis:window);
