/* Fixed-step platform physics also drives offline route validation. */
const Motion=(()=>{
function solid(r,x,y){const cx=Math.floor(x/16),cy=Math.floor(y/16);if(cx<0||cx>=15)return true;if(cy<0)return false;if(cy>=16)return false;const t=r.map[cy][cx];return t==='#'||t==='C'&&!r.blocks.some(b=>b.x===cx*16&&b.y===cy*16&&b.gone>0)}
function overlaps(r,p){return solid(r,p.x-4,p.y-13)||solid(r,p.x+3,p.y-13)||solid(r,p.x-4,p.y-1)||solid(r,p.x+3,p.y-1)}
function axis(r,p,amount,vertical){let n=Math.max(1,Math.ceil(Math.abs(amount)/2)),step=amount/n;for(let i=0;i<n;i++){let old=vertical?p.y:p.x;if(vertical)p.y+=step;else p.x+=step;if(overlaps(r,p)){if(vertical){p.y=old;if(step>0)p.ground=true;p.vy=0}else{p.x=old;p.vx=0}return true}}return false}
function create(r,assist){return{x:r.spawn.x,y:r.spawn.y,vx:0,vy:0,dir:r.spawn.x<120?1:-1,ground:true,wall:0,dashes:assist?2:1,dash:0,dashCD:0,dx:1,dy:0,coyote:.12,jumpBuffer:0,dashBuffer:0,lock:0,dead:false,win:false,hair:Array.from({length:5},()=>({x:r.spawn.x-5,y:r.spawn.y-11})),events:[]}}
function aim(p,i){let dx=i.x||0,dy=i.y||0;if(Math.hypot(dx,dy)<.25)dx=p.dir;const a=Math.round(Math.atan2(dy,dx)/(Math.PI/4))*Math.PI/4;return{x:Math.cos(a),y:Math.sin(a)}}
function tick(r,p,i,dt,assist=false){if(p.dead||p.win)return;p.events=[];p.dashCD=Math.max(0,p.dashCD-dt);p.lock=Math.max(0,p.lock-dt);p.jumpBuffer=Math.max(0,p.jumpBuffer-dt);p.dashBuffer=Math.max(0,p.dashBuffer-dt);p.coyote=p.ground?.12:Math.max(0,p.coyote-dt);if(i.jump)p.jumpBuffer=.14;if(i.dash)p.dashBuffer=.12;
for(let b of r.blocks){if(b.gone>0){b.gone=Math.max(0,b.gone-dt);if(!b.gone)b.timer=0}else if(b.timer>0){b.timer+=dt;if(b.timer>.46){b.gone=2;b.timer=0;p.events.push({kind:'crumble',x:b.x+8,y:b.y+8})}}}for(let k of r.crystals)k.cool=Math.max(0,k.cool-dt);for(let s of r.springs)s.bounce=Math.max(0,s.bounce-dt);
if(p.jumpBuffer>0&&p.dash<=0){if(p.coyote>0){p.vy=-210;p.ground=false;p.coyote=0;p.jumpBuffer=0;p.events.push({kind:'jump',x:p.x,y:p.y})}else if(p.wall){p.vy=-210;p.vx=-p.wall*130;p.dir=-p.wall;p.lock=.15;p.jumpBuffer=0;p.events.push({kind:'wall',x:p.x,y:p.y-7})}}
if(p.dashBuffer>0&&p.dashCD<=0&&p.dashes>0){let a=aim(p,i);p.dx=a.x;p.dy=a.y;p.dash=.155;p.dashCD=.21;p.dashes--;p.dashBuffer=0;p.vx=p.dx*285;p.vy=p.dy*285;if(Math.abs(p.dx)>.1)p.dir=Math.sign(p.dx);p.events.push({kind:'dash',x:p.x,y:p.y-8})}
const wasGround=p.ground;p.ground=false;if(p.dash>0){p.dash=Math.max(0,p.dash-dt);p.vx=p.dx*285;p.vy=p.dy*285}else{if(p.lock<=0){const target=Math.abs(i.x)>.25?Math.sign(i.x)*86:0;p.vx+=(target-p.vx)*Math.min(1,dt*(wasGround?22:11));if(target)p.dir=Math.sign(target)}p.vy=Math.min(260,p.vy+560*dt);p.vx+=(r.wind||0)*dt}
let hitX=axis(r,p,p.vx*dt,false),hitY=axis(r,p,p.vy*dt,true);if(p.y<10){p.y=10;p.vy=Math.max(0,p.vy)}p.wall=solid(r,p.x-5,p.y-7)?-1:solid(r,p.x+4,p.y-7)?1:0;if(!p.ground&&p.wall&&p.vy>55&&p.dash<=0)p.vy=55;if((hitX||hitY)&&p.dash>0){p.dash=0;p.vx*=.2;p.vy*=.2}if(p.ground&&p.dash<=0){const max=assist?2:1;if(p.dashes<max)p.events.push({kind:'refill',x:p.x,y:p.y-8});p.dashes=max;if(!wasGround)p.events.push({kind:'land',x:p.x,y:p.y})}
for(let b of r.blocks)if(!b.gone&&!b.timer&&p.ground&&Math.abs(p.y-b.y)<2&&p.x>=b.x-3&&p.x<b.x+19)b.timer=.001;
for(let s of r.springs)if(p.vy>=0&&Math.abs(p.x-s.x)<11&&p.y>=s.y-7&&p.y<s.y+3){p.y=s.y-7;p.vy=-325;p.ground=false;p.coyote=0;p.dashes=assist?2:1;s.bounce=.22;p.events.push({kind:'spring',x:s.x,y:s.y})}
for(let k of r.crystals)if(k.cool<=0&&Math.abs(p.x-k.x)<10&&Math.abs(p.y-7-k.y)<13){p.dashes=assist?2:1;k.cool=2.2;p.events.push({kind:'crystal',x:k.x,y:k.y})}
for(let cy=Math.max(0,Math.floor((p.y-12)/16));cy<=Math.min(15,Math.floor(p.y/16));cy++)for(let cx=Math.max(0,Math.floor((p.x-3)/16));cx<=Math.min(14,Math.floor((p.x+3)/16));cx++)if(r.map[cy][cx]==='^'&&p.y>cy*16+5&&p.y-12<cy*16+16)p.dead=true;
if(p.y>273)p.dead=true;if(Math.abs(p.x-r.goal.x)<11&&Math.abs(p.y-r.goal.y)<17&&!p.dead)p.win=true;
for(let j=0;j<p.hair.length;j++){let target=j===0?{x:p.x-p.dir*3,y:p.y-12}:p.hair[j-1];p.hair[j].x+=(target.x-p.dir*2-p.hair[j].x)*Math.min(1,dt*18);p.hair[j].y+=(target.y+1-p.hair[j].y)*Math.min(1,dt*18)}return p}
return{create,tick,solid};})();
(()=>{'use strict';const $=s=>document.querySelector(s),canvas=$('#scene'),ctx=canvas.getContext('2d'),world=document.createElement('canvas'),wc=world.getContext('2d'),KEY='summit-thread-v1';world.width=240;world.height=256;
let save;try{save=JSON.parse(localStorage.getItem(KEY)||'null')}catch{}let data={unlocked:1,current:1,records:{},assist:false,ghost:true,outfit:0,muted:false,...save},room,p,terrain,phase='menu',keys={},sources=new Map(),stick={x:0,y:0,id:null},jumpQueued=false,dashQueued=false,particles=[],trails=[],snow=[],clock=0,elapsed=0,deaths=0,totalDeaths=0,respawn=0,shake=0,freeze=0,toast=0,fade=0,pendingBerry=0,ghostSamples=[],sampleTimer=0,last=0,acc=0,audio=null,noteTimer=0,layout={x:0,y:0,scale:1},recordBefore=null;
function persist(){try{localStorage.setItem(KEY,JSON.stringify(data))}catch{}}function rec(index=room.index){return data.records[index]||{berry:false,best:0,medal:0,ghost:[]}}function resetInput(){keys={};sources.clear();stick={x:0,y:0,id:null};jumpQueued=false;dashQueued=false;$('#knob').style.transform='';$('#jump').classList.remove('held');$('#dash').classList.remove('held')}
function sound(f=.0,d=.1,type='sine',vol=.035,to=0){if(!audio||data.muted||audio.state!=='running')return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,audio.currentTime);if(to)o.frequency.exponentialRampToValueAtTime(Math.max(30,f+to),audio.currentTime+d);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}function unlock(){try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{})}catch{}}function chime(){[523.25,659.25,783.99].forEach((n,i)=>sound(n,.5,'sine',.025-i*.004))}
function burst(x,y,col,n=10,s=55){for(let j=0;j<n&&particles.length<160;j++){const a=Math.random()*Math.PI*2;particles.push({x,y,vx:Math.cos(a)*s*(.4+Math.random()),vy:Math.sin(a)*s,life:.35+Math.random()*.4,col})}}
function enter(index){data.current=index;room=buildRoom(index);if(room.loop%2){room.map=room.map.map(row=>row.slice().reverse());for(let obj of[room.spawn,room.goal,room.berry,...room.crystals,...room.springs])obj.x=240-obj.x;for(let b of room.blocks)b.x=224-b.x;room.wind=-(room.wind||0);room.name='Sky Loop · '+room.name}terrain=Pixel.bake(room);p=Motion.create(room,data.assist);pendingBerry=0;deaths=0;elapsed=0;respawn=0;fade=.35;toast=2.3;particles=[];trails=[];ghostSamples=[];sampleTimer=0;room.berry.taken=rec(index).berry;recordBefore=rec(index).best;persist();$('#roomName').textContent=room.name;$('#region').textContent=['SNOWLINE','OLD RUINS','STAR SUMMIT'][room.zone];$('#progress').textContent=index<=12?index+' / 12':'LOOP '+(index-12);$('#hint').textContent=room.tip;resize();hud()}
function play(){phase='play';resetInput();document.body.classList.remove('menu');$('#overlay').classList.add('hidden');last=performance.now()}
function modal(html){resetInput();$('#panel').innerHTML=html;$('#overlay').classList.remove('hidden');document.body.classList.add('menu')}
function title(){phase='menu';modal(`<div class="mountainIcon">▲ ▴ ▲</div><div class="eyebrow">A LITTLE HIGHER</div><h1>SUMMIT<br>THREAD</h1><p>Jump. Kick off walls. Dash into the sky.<br>Small rooms. Quick retries. Secret strawberries.</p><button class="primary" id="start">${data.unlocked>1?'CONTINUE CLIMBING':'START CLIMBING'}</button><button class="quiet" id="select">Choose a trail</button><div class="settings"><button id="assist" class="${data.assist?'assist-on':''}">Assist ${data.assist?'ON':'OFF'}</button><button id="ghost">Ghost ${data.ghost?'ON':'OFF'}</button></div><div class="outfits">${Pixel.outfits.map((o,i)=>`<button data-outfit="${i}" class="${data.outfit===i?'selected':''}" ${data.unlocked<(i===0?1:i*4+1)?'disabled':''} aria-label="${o.name}" style="color:${o.hair}">◆</button>`).join('')}</div><p>← → Move · ↑ ↓ Aim · Space Jump · X Dash<br>Assist: slower motion & two air dashes.</p>`);$('#start').onclick=()=>{unlock();enter(data.current);play()};$('#select').onclick=select;$('#assist').onclick=()=>{data.assist=!data.assist;persist();title()};$('#ghost').onclick=()=>{data.ghost=!data.ghost;persist();title()};document.querySelectorAll('[data-outfit]').forEach(b=>b.onclick=()=>{data.outfit=+b.dataset.outfit;persist();title()})}
function select(){phase='select';modal(`<div class="eyebrow">YOUR MOUNTAIN</div><h2>Choose a trail</h2><div class="levels">${Rooms.map((r,i)=>{const rr=rec(i+1);return`<button data-room="${i+1}" ${i+1>data.unlocked?'disabled':''} class="${rr.best?'complete':''}" aria-label="${r.name}">${String(i+1).padStart(2,'0')}<em>${rr.berry?'♥':rr.medal?'★':''}</em></button>`}).join('')}</div><p>Collect strawberries. Beat your ghost.<br>Gold: a clean run under 30 seconds.</p><button class="primary" id="back">BACK</button>`);document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>{unlock();enter(+b.dataset.room);play()});$('#back').onclick=title}
function pause(){if(phase!=='play')return;phase='pause';modal(`<div class="eyebrow">JUST BREATHE</div><h2>${room.name}</h2><p>Land or touch a green crystal to refill your dash.<br>Wall jumps can help you find another route.</p><div class="settings"><button id="assist" class="${data.assist?'assist-on':''}">Assist ${data.assist?'ON':'OFF'}</button><button id="ghost">Ghost ${data.ghost?'ON':'OFF'}</button></div><button class="primary" id="resume">KEEP CLIMBING</button><button class="quiet" id="retry">Restart room</button><button class="quiet" id="home">Trail map</button>`);$('#resume').onclick=play;$('#retry').onclick=()=>{enter(room.index);play()};$('#home').onclick=select;$('#assist').onclick=()=>{data.assist=!data.assist;p.dashes=data.assist?Math.max(p.dashes,2):Math.min(p.dashes,1);persist();pauseUI()};$('#ghost').onclick=()=>{data.ghost=!data.ghost;persist();pauseUI()}}
function pauseUI(){phase='play';pause()}
function finish(){if(phase!=='play')return;if(pendingBerry){room.berry.taken=true;pendingBerry=0}const old=rec(),medal=deaths===0&&elapsed<30?3:deaths<=2?2:1,personal=!old.best||elapsed<old.best;data.records[room.index]={berry:old.berry||room.berry.taken,best:personal?elapsed:old.best,medal:Math.max(old.medal,medal),ghost:personal?ghostSamples:old.ghost};for(const key of Object.keys(data.records))if(+key>12&&+key<room.index-12)data.records[key].ghost=[];data.unlocked=Math.min(13,Math.max(data.unlocked,room.index+1));data.current=room.index+1;persist();phase='complete';chime();burst(p.x,p.y-10,'#fff0ba',34,100);const summit=room.index===12;modal(`<div class="eyebrow">${summit?'YOU MADE IT':'ONE STEP CLOSER'}</div><h2>${summit?'The sky is yours':room.name}</h2><div style="font-size:31px;color:${medal===3?'#ffd78b':medal===2?'#d7e4f0':'#caa4a3'}">${'★'.repeat(medal)}</div><div class="results"><span><b>${elapsed.toFixed(1)}s</b>${personal?'PERSONAL BEST':'TIME'}</span><span><b>${deaths}</b>RETRIES</span><span><b>${room.berry.taken?'♥':'◇'}</b>STRAWBERRY</span></div>${[4,8,12].includes(room.index)?'<p>A new trail colour is unlocked ◆</p>':''}<button class="primary" id="next">${summit?'ENTER SKY LOOP':'CLIMB HIGHER'}</button><button class="quiet" id="again">Try a cleaner run</button><button class="quiet" id="map">Trail map</button>`);$('#next').onclick=()=>{enter(room.index+1);play()};$('#again').onclick=()=>{enter(room.index);play()};$('#map').onclick=select}
function die(){if(respawn>0)return;deaths++;totalDeaths++;p.dead=true;respawn=.32;pendingBerry=0;freeze=.035;shake=2.5;burst(p.x,p.y-8,Pixel.outfits[data.outfit].hair,18,100);sound(120,.18,'triangle',.035,-65)}
function step(dt){if(['pause','complete','select'].includes(phase))return;clock+=dt;for(let f of particles){f.life-=dt;f.x+=f.vx*dt;f.y+=f.vy*dt;f.vy+=80*dt}particles=particles.filter(f=>f.life>0);for(let t of trails)t.life-=dt;trails=trails.filter(t=>t.life>0);shake=Math.max(0,shake-dt*15);toast=Math.max(0,toast-dt);fade=Math.max(0,fade-dt);if(phase!=='play')return;if(freeze>0){freeze-=dt;return}elapsed+=dt;
if(respawn>0){respawn-=dt;if(respawn<=0){room=buildRoom(room.index);if(room.loop%2){room.map=room.map.map(row=>row.slice().reverse());for(let o of[room.spawn,room.goal,room.berry,...room.crystals,...room.springs])o.x=240-o.x;for(let b of room.blocks)b.x=224-b.x;room.wind=-(room.wind||0)}room.berry.taken=rec().berry;p=Motion.create(room,data.assist);sampleTimer=0;fade=.13}hud();return}
const ix=stick.id!==null?stick.x:(keys.right?1:0)-(keys.left?1:0),iy=stick.id!==null?stick.y:(keys.down?1:0)-(keys.up?1:0),jump=jumpQueued,dash=dashQueued;jumpQueued=false;dashQueued=false;Motion.tick(room,p,{x:ix,y:iy,jump,dash},dt*(data.assist?.8:1),data.assist);
if(p.dash>0&&trails.length<14)trails.push({x:p.x,y:p.y,dir:p.dir,life:.17,max:.17,dashes:0,hair:p.hair.map(h=>({...h}))});for(let e of p.events){if(e.kind==='dash'){burst(e.x,e.y,'#cfbdeb',8,65);sound(620,.12,'triangle',.02,-400)}if(e.kind==='land'||e.kind==='jump'||e.kind==='wall')burst(e.x,e.y,'#d8e6ef',5,25);if(e.kind==='spring'){burst(e.x,e.y,'#ffafd3',15,65);sound(320,.2,'sine',.03,400)}if(e.kind==='crystal'||e.kind==='refill'){burst(e.x,e.y,'#8ef0cb',e.kind==='crystal'?15:6,35);sound(e.kind==='crystal'?880:520,.11,'sine',.018,100)}if(e.kind==='crumble'){burst(e.x,e.y,'#b5a4bb',8,35);sound(95,.06,'triangle',.017)}}
if(p.dead){die();hud();return}if(!room.berry.taken&&!pendingBerry&&Math.abs(p.x-room.berry.x)<10&&Math.abs(p.y-8-room.berry.y)<13){pendingBerry=.001;sound(880,.15,'sine',.025);burst(room.berry.x,room.berry.y,'#ffd7d9',8,40)}if(pendingBerry){pendingBerry+=dt;if(p.ground&&p.dash<=0&&pendingBerry>.3){pendingBerry=0;room.berry.taken=true;const rr=rec();data.records[room.index]={...rr,berry:true};persist();chime();burst(p.x,p.y-15,'#ffb4cb',24,65)}}
sampleTimer+=dt;if(sampleTimer>=.08&&ghostSamples.length<900){sampleTimer=0;ghostSamples.push({t:elapsed,x:Math.round(p.x),y:Math.round(p.y),dir:p.dir,dashes:p.dashes})}if(p.win){finish();return}noteTimer+=dt;if(noteTimer>2.7){noteTimer=0;sound([196,261.63,293.66,392,329.63,261.63][Math.floor(clock/2.7)%6],1.4,'sine',.012)}hud()}
function hud(){const count=Object.values(data.records).filter(r=>r.berry).length;$('#berries').textContent='🍓 '+count;$('#dashStatus').textContent=p.dashes>0?'◆'.repeat(p.dashes):'◇';$('#dashStatus').style.color=p.dashes>0?Pixel.outfits[data.outfit].hair:'#7caacf';$('#dash').classList.toggle('spent',p.dashes<=0);$('#audio').textContent=data.muted?'♫̸':'♪';if(deaths>=3)$('#hint').textContent='Need a breath? Pause → Assist';else if(elapsed>12)$('#hint').textContent=''}
function resize(){const w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);const wide=w/h>1.5;const availableH=wide?h-90:h-220;layout.scale=Math.min((w-26)/240,availableH/256,3);layout.x=(w-240*layout.scale)/2;layout.y=wide?70:(h-256*layout.scale-120)/2+10;layout.y=Math.max(wide?65:110,layout.y);render()}
function render(){if(!p)return;const w=canvas.clientWidth,h=canvas.clientHeight,dpr=canvas.width/w;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=false;const bg=render.bg||(render.bg=document.createElement('canvas'));const bw=Math.ceil(w/3),bh=Math.ceil(h/3);if(bg.width!==bw||bg.height!==bh){bg.width=bw;bg.height=bh}Pixel.backdrop(bg.getContext('2d'),bw,bh,room.zone,clock);ctx.drawImage(bg,0,0,w,h);
wc.clearRect(0,0,240,256);wc.drawImage(terrain,0,0);for(let b of room.blocks)if(!b.gone){Pixel.rect(wc,b.x,b.y,16,16,'#78678a');Pixel.rect(wc,b.x,b.y,16,2,'#d5c2df');Pixel.poly(wc,[[b.x+5,b.y+2],[b.x+8,b.y+6],[b.x+5,b.y+11],[b.x+10,b.y+14]],'#352b50');if(b.timer>0){wc.fillStyle='#ead5e6';wc.globalAlpha=b.timer*1.3;wc.fillRect(b.x,b.y,16,16);wc.globalAlpha=1}}
Pixel.flag(wc,room.goal,clock);for(let k of room.crystals)Pixel.crystal(wc,k,clock);for(let s of room.springs)Pixel.spring(wc,s);if(!room.berry.taken)Pixel.berry(wc,pendingBerry?p.x-p.dir*12:room.berry.x,pendingBerry?p.y-24:room.berry.y,clock);
const ghost=rec().ghost;if(data.ghost&&ghost?.length&&phase==='play'){let lo=0,hi=ghost.length-1;while(lo<hi){const mid=Math.ceil((lo+hi)/2);if(ghost[mid].t<=elapsed)lo=mid;else hi=mid-1}const g=ghost[lo];if(g&&elapsed<=ghost.at(-1).t)Pixel.character(wc,{...p,...g,hair:[],ground:false,wall:0},clock,data.outfit,.22)}for(let t of trails)Pixel.character(wc,{...p,...t,ground:false,wall:0},clock,data.outfit,t.life/t.max*.25);if(!p.dead)Pixel.character(wc,p,clock,data.outfit);for(let f of particles){wc.globalAlpha=Math.min(1,f.life*3);Pixel.rect(wc,f.x,f.y,2,2,f.col)}wc.globalAlpha=1;
if(deaths>=3&&phase==='play'){wc.globalAlpha=.35;Pixel.rect(wc,room.goal.x,room.goal.y-42,1,2,'#f3e6a5');Pixel.rect(wc,room.goal.x-2,room.goal.y-40,5,1,'#f3e6a5');wc.globalAlpha=1}ctx.save();ctx.translate(layout.x+(Math.random()-.5)*shake*layout.scale,layout.y+(Math.random()-.5)*shake*layout.scale);ctx.globalAlpha=Math.max(.15,1-fade/.35);ctx.drawImage(world,0,0,240*layout.scale,256*layout.scale);ctx.restore();$('#roomToast').textContent=room.name;$('#roomToast').style.opacity=toast>1.5?Math.min(1,(2.3-toast)*3):toast/1.5}
function frame(now){const dt=Math.min(.075,(now-last)/1000||0);last=now;acc+=dt;let n=0;while(acc>=1/60&&n<5){step(1/60);acc-=1/60;n++}render();requestAnimationFrame(frame)}
function keySource(source,key,on){if(on)sources.set(source,key);else sources.delete(source);keys={};for(let k of sources.values())keys[k]=true}function act(k){unlock();if(phase!=='play')return;if(k==='jump')jumpQueued=true;if(k==='dash')dashQueued=true}
const map={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',' ':'jump',z:'jump',x:'dash',c:'dash',Shift:'dash'};addEventListener('keydown',e=>{if(e.key==='Escape'){phase==='play'?pause():phase==='pause'?play():null;return}const k=map[e.key];if(!k)return;e.preventDefault();if(phase!=='play')return;const source='key:'+e.code,fresh=!sources.has(source);keySource(source,k,true);if(fresh)act(k)});addEventListener('keyup',e=>{if(map[e.key]){keySource('key:'+e.code,map[e.key],false);e.preventDefault()}});
for(let k of['jump','dash']){let b=$('#'+k);b.addEventListener('pointerdown',e=>{e.preventDefault();if(phase!=='play')return;b.setPointerCapture(e.pointerId);b.classList.add('held');act(k)});const up=e=>{e.preventDefault();b.classList.remove('held')};b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('lostpointercapture',()=>b.classList.remove('held'))}
function joystick(e){const box=$('#stick').getBoundingClientRect(),radius=box.width/2-10,dx=e.clientX-box.x-box.width/2,dy=e.clientY-box.y-box.height/2,len=Math.hypot(dx,dy),mul=len>radius?radius/len:1;stick.x=dx*mul/radius;stick.y=dy*mul/radius;$('#knob').style.transform=`translate(${dx*mul}px,${dy*mul}px)`}$('#stick').addEventListener('pointerdown',e=>{e.preventDefault();if(phase!=='play'||stick.id!==null)return;unlock();stick.id=e.pointerId;$('#stick').setPointerCapture(e.pointerId);joystick(e)});$('#stick').addEventListener('pointermove',e=>{if(e.pointerId===stick.id)joystick(e)});const release=e=>{if(e.pointerId===stick.id){stick={x:0,y:0,id:null};$('#knob').style.transform=''}};$('#stick').addEventListener('pointerup',release);$('#stick').addEventListener('pointercancel',release);$('#stick').addEventListener('lostpointercapture',release);
$('#audio').onclick=()=>{unlock();data.muted=!data.muted;persist();hud()};$('#pause').onclick=pause;addEventListener('blur',()=>{resetInput();if(phase==='play')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden){resetInput();if(phase==='play')pause();persist()}});new ResizeObserver(resize).observe(canvas);
window.SummitThread={state:()=>({phase,data:JSON.parse(JSON.stringify(data)),room:{index:room.index,name:room.name,zone:room.zone},player:JSON.parse(JSON.stringify(p)),elapsed,deaths,pendingBerry,layout}),step:t=>{for(let i=0;i<Math.round(t*60);i++)step(1/60);render()}};
enter(data.current);title();last=performance.now();requestAnimationFrame(frame);
})();
