'use strict';
(()=>{
const $=s=>document.querySelector(s), modal=$('#modal'),panel=$('#panel'), keys={},touch={x:0,y:0}, themes=[['THE VELVET ROOM',0x543044,0xffca70,0x4ed6d2],['ELECTRIC PALACE',0x282957,0xfc6bb8,0x7be9ff],['EMERALD LOUNGE',0x204b43,0xf2cd71,0xa1ec94],['THE SKY VAULT',0x402c58,0xffb184,0xbba5ff]];
let saved={best:0,tickets:0,hat:0};try{Object.assign(saved,JSON.parse(localStorage.getItem('after-hours-v1')||'{}'))}catch{}
let state={day:1,bank:120,quota:180,time:300,phase:'title',bet:10,plays:0,wins:0,insured:0,lucky:0,boost:0,loan:false,paid:0}, yaw=0,pitch=0,elapsed=0,near=null,uiTime=0,toastTime=0,anim=null,game=null,stake=0,resultTime=0,shake=0;
function save(){try{localStorage.setItem('after-hours-v1',JSON.stringify(saved))}catch{}}
let audio;function tone(f=440,d=.1,type='sine',v=.04){try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(f*.7,audio.currentTime+d);g.gain.setValueAtTime(v,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function notify(s){$('#toast').textContent=s;$('#toast').classList.add('show');toastTime=3}
function burst(n=22){for(let i=0;i<n;i++){let e=document.createElement('i');e.className='coin';e.textContent=['✦','●','$'][i%3];e.style.setProperty('--x',(Math.random()-.5)*500+'px');e.style.setProperty('--y',(-40-Math.random()*300)+'px');$('#payout').append(e);setTimeout(()=>e.remove(),1050)}[0,1,2,3].forEach((n)=>setTimeout(()=>tone(420+n*180,.16),n*75))}
let renderer,scene,camera,world=new THREE.Group(), machines=[],colliders=[],buddies=[],chips=[],floating=[];
try{renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputEncoding=THREE.sRGBEncoding;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.85;$('#world').appendChild(renderer.domElement)}catch(e){panel.innerHTML='<h2>WebGL unavailable</h2><p>Open this page in Safari, Chrome or Edge with graphics acceleration enabled.</p>';return}
scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.08,60);camera.rotation.order='YXZ';camera.position.set(0,1.65,8);scene.add(world);scene.add(new THREE.HemisphereLight(0xcddcfa,0x302333,.5));let light=new THREE.DirectionalLight(0xffd4a3,.65);light.position.set(4,7,5);scene.add(light);
const geom={box:new THREE.BoxGeometry(1,1,1),sphere:new THREE.SphereGeometry(1,12,8),cyl:new THREE.CylinderGeometry(1,1,1,16)};const materials=new Map();
function mat(c,em=false){let k=c+'_'+em;if(!materials.has(k))materials.set(k,new THREE.MeshStandardMaterial({color:c,roughness:.8,emissive:em?c:0,emissiveIntensity:em?1.2:0}));return materials.get(k)}
function mesh(g,c,x,y,z,sx,sy,sz,parent=world,em=false){let m=new THREE.Mesh(geom[g],mat(c,em));m.position.set(x,y,z);m.scale.set(sx,sy,sz);parent.add(m);return m}
function box(c,x,y,z,sx,sy,sz,p=world,em=false){return mesh('box',c,x,y,z,sx,sy,sz,p,em)}
function label(text,c,w=3,h=.6,parent=world){let cv=document.createElement('canvas');cv.width=512;cv.height=128;let a=cv.getContext('2d');a.fillStyle='#211629';a.fillRect(0,0,512,128);a.strokeStyle=c;a.lineWidth=7;a.strokeRect(8,8,496,112);a.font='bold 48px Trebuchet MS';a.textAlign='center';a.fillStyle=c;a.fillText(text,256,82);let tex=new THREE.CanvasTexture(cv),m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:tex,side:THREE.DoubleSide}));parent.add(m);return m}
function carpet(){let cv=document.createElement('canvas');cv.width=cv.height=256;let a=cv.getContext('2d');a.fillStyle='#152537';a.fillRect(0,0,256,256);for(let x=0;x<256;x+=64)for(let y=0;y<256;y+=64){a.save();a.translate(x+32,y+32);a.rotate((x+y)/64%2?.4:-.4);a.strokeStyle='#bc5c45';a.lineWidth=6;a.beginPath();a.ellipse(0,0,24,12,0,0,7);a.stroke();a.fillStyle='#dca355';a.beginPath();a.arc(7,0,5,0,7);a.fill();a.restore()}let t=new THREE.CanvasTexture(cv);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(12,12);return t}
const rug=carpet();
function shadow(x,z,r=1,parent=world){let cv=document.createElement('canvas');cv.width=cv.height=64;let c=cv.getContext('2d'),g=c.createRadialGradient(32,32,0,32,32,32);g.addColorStop(0,'#07040bd0');g.addColorStop(1,'#07040b00');c.fillStyle=g;c.fillRect(0,0,64,64);let m=new THREE.Mesh(new THREE.PlaneGeometry(r*2,r*2),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(cv),transparent:true,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.set(x,.015,z);parent.add(m);return m}const machineTypes=[['slots','LUCKY 777','✦'],['roulette','RED / BLACK','◉'],['dice','DICE DUET','⚄'],['blackjack','TWENTY ONE','♠'],['crash','MOON ROCKET','↗']];
function build(){world.clear();machines=[];colliders=[];buddies=[];chips=[];floating=[];let th=themes[(state.day-1)%4];$('#floor').textContent=th[0];scene.background=new THREE.Color(0x191225);scene.fog=new THREE.Fog(0x24182f,13,40);let floor=new THREE.Mesh(new THREE.BoxGeometry(24,.15,24),new THREE.MeshStandardMaterial({map:rug,roughness:1}));floor.position.y=-.1;world.add(floor);box(th[1],0,3,-12,24,6,.3);box(th[1],-12,3,0,.3,6,24);box(th[1],12,3,0,.3,6,24);box(th[1],0,3,12,24,6,.3);box(0x251d2b,0,5.8,0,24,.2,24);
for(let x=-10;x<=10;x+=4){box(0xc99764,x,2.8,-11.7,.22,5.5,.3);box(0x8a4248,x,.65,-11.65,3.6,1.2,.35);box(th[2],x,4.8,-11.45,2.8,.06,.06,world,true)}for(let z=-8;z<10;z+=6){for(let x of [-11.5,11.5]){box(0xb08558,x,1.1,z,.3,2.2,.3);box(th[3],x,3.3,z,.1,1.5,2.8,world,true)}}
let title=label('AFTER HOURS','#ffd185',7,1.2);title.position.set(0,4.2,-11.4);let sub=label('PAY UP. GO UP.','#f794b7',4,.55);sub.position.set(0,3,-11.4);
for(let x of [-7,0,7]){mesh('cyl',0xbc9b62,x,5,1,.85,.18,.85);for(let a=0;a<6;a++){let q=a*Math.PI/3;mesh('sphere',th[2],x+Math.cos(q)*.75,4.8,1+Math.sin(q)*.75,.14,.14,.14,world,true)}mesh('cyl',0x98764d,x,5.45,1,.035,.9,.035)}
const places=[[-7,-7,-.15],[-2.5,-7,0],[3,-7,0],[7.5,-6,-.2],[-8,2,Math.PI/2]];
machineTypes.forEach((it,i)=>{let [x,z,r]=places[i],g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=r;world.add(g);let color=[0xcc7b47,0xae3e67,0x648a70,0x7b68a7,0x417d9b][i];box(0x161320,0,.45,0,2.1,.9,1.3,g);box(color,0,1.25,0,2,1.5,1.15,g);box(0xcba16b,0,2.05,0,2.25,.22,1.3,g);let l=label(it[1],'#ffe2a7',2.05,.42,g);l.position.set(0,2.4,.5);box(0x171927,0,1.5,.6,1.75,.8,.12,g);let sign=label(i===0?'★  7  ★':i===1?'RED   ◉   BLACK':i===2?'⚄    ⚂':i===3?'A ♠   K ♥':'↗  TO THE MOON','#96f3d6',1.6,.65,g);sign.position.set(0,1.55,.68);box(0x321e37,0,.85,.85,2,.14,.8,g);for(let k=-.7;k<=.7;k+=.35)mesh('cyl',th[2],k,1,.8,.1,.05,.1,g,true);if(i===0){mesh('sphere',0xea545b,1.25,1.4,0,.16,.16,.16,g);box(0xd6c2a6,1.25,1.05,0,.06,.6,.06,g)}let seat=mesh('cyl',0x8c3d56,x,.72,z+1.5,.42,.2,.42);mesh('cyl',0xba986d,x,.35,z+1.5,.06,.6,.06);machines.push({type:it[0],name:it[1],x,z,g});colliders.push({x,z,r:1.3});shadow(x,z+1,1.5);});
for(let i=0;i<4;i++){let x=5+(i%2)*3,z=1+Math.floor(i/2)*3;mesh('cyl',0x7e8a69,x,1,z,1,.16,1);mesh('cyl',0xba9c75,x,.5,z,.12,1,.12);for(let n=0;n<8;n++){let a=n*Math.PI/4;mesh('cyl',n%2?0xcc5665:0xe6be69,x+Math.cos(a)*.65,1.12,z+Math.sin(a)*.65,.12,.06,.12)}colliders.push({x,z,r:1.25})}
const util=[['shop','ODDS & ENDS',-7,8],['cashier','DEBT WINDOW',0,-10],['lift','NEXT FLOOR',8,9]];util.forEach(([type,name,x,z])=>{let g=new THREE.Group();g.position.set(x,0,z);world.add(g);box(type==='lift'?0x746280:0x6e4348,0,1.2,0,2.8,2.4,.7,g);box(0xd8aa6e,0,2.6,0,3,.2,1,g);let l=label(name,'#ffce87',2.7,.55,g);l.position.set(0,2.3,.45);if(type==='lift'){box(0x18273a,0,1,.45,1.9,2,.05,g);box(0xeec17a,0,1,.5,.04,2,.04,g)}else{box(0x161925,0,1.4,.45,2,1,.08,g);box(0xe3b469,0,.85,.5,3,.14,1,g)}machines.push({type,name,x,z,g});colliders.push({x,z,r:1.5})});
for(let i=0;i<3;i++){let g=new THREE.Group();world.add(g);let c=[0x6ac4d8,0xe896b1,0xabcf83][i];mesh('sphere',c,0,1.1,0,.36,.58,.3,g);mesh('sphere',c,0,1.75,0,.45,.4,.36,g);for(let x of [-.19,.19]){mesh('sphere',0xfff4ce,x,1.85,.3,.17,.19,.09,g);mesh('sphere',0x262136,x,1.84,.39,.055,.075,.04,g);mesh('sphere',c,x,.45,0,.12,.33,.12,g);mesh('sphere',c,x*2.3,1.2,0,.12,.32,.12,g)}if(i===1)mesh('cyl',0xd5ad67,0,2.13,0,.5,.07,.4,g);if(i===2)box(0x645576,0,2.14,0,.52,.22,.5,g);let tag=label(['PIP · SCAVENGER','MOMO · SCOUT','BEAN · CHEER'][i],'#f8e0b2',1.4,.22,g);tag.position.set(0,2.65,0);shadow(0,0,.55,g);buddies.push({g,x:-3+i*3,z:3,t:i*2})}
for(let i=0;i<18;i++){let x=(Math.random()-.5)*19,z=(Math.random()-.5)*19;if(colliders.some(o=>Math.hypot(x-o.x,z-o.z)<1.8)){i--;continue}let g=mesh('cyl',0xffd467,x,.15,z,.14,.05,.14,world,true);chips.push(g)}camera.position.set(0,1.65,8);yaw=0;pitch=0;}
function hud(){ $('#bank').textContent='$'+Math.floor(state.bank);$('#clock').textContent=Math.floor(state.time/60)+':'+String(Math.ceil(state.time%60)).padStart(2,'0');$('#objective').textContent='DAY '+state.day+' · $'+state.quota+' TO CLEAR';$('#progress').style.width=Math.min(100,state.bank/state.quota*100)+'%';}
function show(html){modal.hidden=false;panel.innerHTML=html;touch.x=touch.y=0;for(let k in keys)keys[k]=false;$('#stick i').style.transform='';}
function close(){if(anim||game?.kind==='crash'&&game.running||game?.kind==='blackjack'&&!game.done){notify('Finish this hand first');return}modal.hidden=true;game=null;state.phase='walk'}
function title(){show('<span class="tag">THE DEBT CLUB</span><h1>AFTER<br>HOURS</h1><p class="lead">One bank. Five minutes.<br>A whole tower of terrible ideas.</p><div class="stats"><div><strong>5</strong>machines</div><div><strong>4</strong>night clubs</div><div><strong>∞</strong>days</div></div><div class="row"><button class="primary" id="start">ENTER THE CLUB →</button></div><p class="subtle">Move with WASD. Drag to look. E to interact.<br>Touch: left stick + swipe right to look.<br>Solo with AI companions · Fictional chips only</p><p class="subtle">Best day '+saved.best+' · '+saved.tickets+' tickets</p>');$('#start').onclick=()=>{state.phase='walk';modal.hidden=true;tone(300,.2);notify('Collect floor chips. Reach $180. Pay at the Debt Window.')}}
function betUI(){return '<div class="bet"><button id="less" aria-label="Decrease bet">−</button><b id="bet">$'+state.bet+'</b><button id="more" aria-label="Increase bet">+</button></div>'}
function bindBet(){ $('#less').onclick=()=>{if(anim||game?.running||game?.kind==='blackjack'&&!game.done)return;state.bet=Math.max(5,state.bet-5);$('#bet').textContent='$'+state.bet};$('#more').onclick=()=>{if(anim||game?.running||game?.kind==='blackjack'&&!game.done)return;state.bet=Math.min(100,state.bet+5);$('#bet').textContent='$'+state.bet};$('#back').onclick=close;}
function begin(){if(anim||game?.running)return false;if(state.bank<state.bet){notify('Not enough chips. Collect some or visit the shop.');tone(110);return false}stake=state.bet;state.bank-=stake;state.plays++;hud();tone(190,.1,'square');return true}
function settle(mult,text){let amount=Math.round(stake*mult);if(amount===0&&state.insured>0){state.insured--;amount=Math.round(stake*.5);text+=' · HALF REFUNDED'}if(amount>0&&state.boost>0){amount=Math.round(amount*1.25);state.boost--}state.bank+=amount;state.wins+=mult>1?1:0;$('#result').textContent=text+' · '+(amount?'$'+amount:'−$'+stake);if(mult>1){burst();shake=.16}else tone(130,.2,'triangle');hud();if(state.plays%5===0){saved.tickets++;save();notify('5 plays · +1 ticket')}resultTime=2;}
function machine(type){state.phase='machine';game={kind:type,done:true};let html='<span class="tag">FLOOR '+state.day+'</span><h2>'+machineTypes.find(x=>x[0]===type)[1]+'</h2>';if(type==='slots')html+='<div class="reels"><div class="reel">★</div><div class="reel">7</div><div class="reel">★</div></div><p class="subtle">Pair ×2 · Triple ×8 · Triple 7 ×15</p>'+betUI()+'<button id="play" class="primary">PULL THE LEVER</button>';
if(type==='roulette')html+='<div class="roulette"><b id="wheel">?</b></div><p class="subtle">Red / Black ×2 · Green ×12</p>'+betUI()+'<div class="row"><button id="red" style="background:#aa4059">RED</button><button id="black">BLACK</button><button id="green" style="background:#286b56">GREEN</button></div>';
if(type==='dice')html+='<div class="reels"><div class="reel">⚄</div><div class="reel">⚂</div></div><p class="subtle">High: 8–12 · Low: 2–6 · ×2.2<br>Double: matching dice · ×5</p>'+betUI()+'<div class="row"><button id="low">LOW</button><button id="high">HIGH</button><button id="double">DOUBLE</button></div>';
if(type==='blackjack')html+='<div id="dealer" class="reels"></div><div id="hand" class="reels"></div><p class="subtle">Beat the dealer. Stay at 21 or below. Win ×2.2</p>'+betUI()+'<div class="row"><button id="deal" class="primary">DEAL</button><button id="hit" disabled>HIT</button><button id="stand" disabled>STAND</button></div>';
if(type==='crash')html+='<div class="chart" id="chart">1.00×</div><p class="subtle">Take off. Cash out before the rocket bursts.<br>It can crash immediately. The next peak is hidden.</p>'+betUI()+'<div class="row"><button id="launch" class="primary">LAUNCH</button><button id="cash" disabled>CASH OUT</button></div>';
html+='<div id="result" class="result"></div><div class="row"><button id="back">← WALK AWAY</button></div>';show(html);bindBet();let choice=null;
function spin(kind,pick){if(!begin())return;choice=pick;game.running=true;let final, mult=0,text='';if(kind==='slots'){final=Array.from({length:3},()=>Math.floor(Math.random()*5));if(state.lucky){state.lucky--;final[1]=final[0]}let count=Math.max(...[0,1,2,3,4].map(x=>final.filter(v=>v===x).length));mult=count===3?(final[0]===1?15:8):count===2?2:0;text=count===3?'JACKPOT':count===2?'A PAIR!':'SO CLOSE'}else if(kind==='dice'){final=[1+Math.floor(Math.random()*6),1+Math.floor(Math.random()*6)];let sum=final[0]+final[1];mult=pick==='double'?(final[0]===final[1]?5:0):((pick==='high'?sum>=8:sum<=6)?2.2:0);text='ROLLED '+sum}else{let n=Math.floor(Math.random()*13);final=[n];let color=n===0?'green':n%2?'red':'black';mult=color===pick?(pick==='green'?12:2):0;text=color.toUpperCase()+' '+n}anim={time:0,duration:1.5,kind,final,mult,text};}
if(type==='slots')$('#play').onclick=()=>spin(type);if(type==='roulette')for(let c of ['red','black','green'])$('#'+c).onclick=()=>spin(type,c);if(type==='dice')for(let c of ['low','high','double'])$('#'+c).onclick=()=>spin(type,c);
if(type==='blackjack'){const draw=()=>Math.min(10,1+Math.floor(Math.random()*13)),sum=a=>{let s=a.reduce((x,y)=>x+y,0);return a.includes(1)&&s+10<=21?s+10:s},render=(hidden=true)=>{$('#dealer').innerHTML=game.d.map((v,i)=>'<span class="card">'+(hidden&&i?'?':v===1?'A':v)+'</span>').join('');$('#hand').innerHTML=game.h.map(v=>'<span class="card">'+(v===1?'A':v)+'</span>').join('');$('#result').textContent='YOUR HAND · '+sum(game.h)};function finish(){game.done=true;$('#hit').disabled=$('#stand').disabled=true;$('#deal').disabled=false;render(false);let h=sum(game.h),d=sum(game.d);settle(h>21?0:d>21||h>d?2.2:h===d?1:0,h>21?'BUST':d>21?'DEALER BUST':h>d?'YOU WIN':h===d?'PUSH':'DEALER WINS')}
$('#deal').onclick=()=>{if(!game.done||!begin())return;game.done=false;game.h=[draw(),draw()];game.d=[draw(),draw()];$('#hit').disabled=$('#stand').disabled=false;$('#deal').disabled=true;render();if(sum(game.h)===21){while(sum(game.d)<17)game.d.push(draw());finish()}};$('#hit').onclick=()=>{if(game.done)return;game.h.push(draw());tone(500);render();if(sum(game.h)>21)finish()};$('#stand').onclick=()=>{if(game.done)return;while(sum(game.d)<17)game.d.push(draw());finish()};}
if(type==='crash'){$('#launch').onclick=()=>{if(!begin())return;game.running=true;game.value=1;game.t=0;game.peak=Math.random()<.08?1:Math.min(18,.98/(1-Math.random()));$('#launch').disabled=true;$('#cash').disabled=false;$('#result').textContent='';};$('#cash').onclick=()=>{if(!game.running)return;game.running=false;$('#cash').disabled=true;$('#launch').disabled=false;settle(game.value,'ESCAPED AT '+game.value.toFixed(2)+'×')}}}
function shop(){state.phase='shop';show('<span class="tag">ODDS & ENDS</span><h2>Sketchy little helpers</h2><p class="subtle">'+saved.tickets+' tickets · '+(state.loan?'Emergency advance used':'One emergency advance each run')+'</p><div class="shop"><button id="insurance"><b>☂  $20</b>Safety net<small>Next two losses refund half.</small></button><button id="magnet"><b>✦  $25</b>Pair magnet<small>Next slot spin guarantees a pair.</small></button><button id="boost"><b>↗  $30</b>Golden cup<small>Next three payouts +25%.</small></button><button id="loan"><b>⊕  $60</b>Emergency advance<small>Free chips. Next quota +$70.</small></button><button id="hat"><b>♛  3 tickets</b>Party hat<small>Give Pip a ridiculous crown.</small></button><button id="work"><b>▣  +$12</b>Bus the tables<small>Reliable chips. Takes 8 seconds.</small></button></div><div class="row"><button id="back">← WALK AWAY</button></div>');$('#back').onclick=close;function buy(cost,fn){if(state.bank<cost){notify('Not enough chips');return}state.bank-=cost;fn();hud();notify('Packed and ready');tone(700);shop()}$('#insurance').onclick=()=>buy(20,()=>state.insured+=2);$('#magnet').onclick=()=>buy(25,()=>state.lucky++);$('#boost').onclick=()=>buy(30,()=>state.boost+=3);$('#loan').disabled=state.loan;$('#loan').onclick=()=>{state.loan=true;state.bank+=60;state.quota+=70;hud();shop()};$('#hat').onclick=()=>{if(saved.tickets<3){notify('Need 3 tickets');return}saved.tickets-=3;saved.hat++;save();mesh('cyl',0xffd581,0,2.18,0,.4,.2,.4,buddies[0].g);shop()};$('#work').onclick=()=>{state.time=Math.max(0,state.time-8);state.bank+=12;hud();notify('Tables cleared · +$12');tone(600);if(state.time<=0)end(false);else shop()};}
function cashier(){state.phase='cashier';show('<span class="tag">THE DEBT WINDOW</span><h2>'+(state.bank>=state.quota?'You made it.':'The clock is ticking.')+'</h2><div class="stats"><div><strong>$'+Math.floor(state.bank)+'</strong>bank</div><div><strong>$'+state.quota+'</strong>quota</div></div><p class="subtle">Clear your quota to unlock the next floor.<br>Extra chips carry forward, with a $90 starting allowance.</p><div class="row"><button id="pay" class="primary" '+(state.bank<state.quota?'disabled':'')+'>PAY & GO UP →</button><button id="back">NOT YET</button></div>');$('#back').onclick=close;$('#pay').onclick=()=>{if(state.bank<state.quota)return;end(true)}}
function end(win){anim=null;if(game)game.running=false;game=null;state.phase=win?'cleared':'over';if(win){state.paid+=state.quota;saved.best=Math.max(saved.best,state.day);saved.tickets+=3;save();burst()}show('<span class="tag">'+(win?'DEBT CLEARED':'THE HOUSE CLOSES')+'</span><h2>'+(win?'Going up!':'Another night?')+'</h2><div class="stats"><div><strong>'+state.day+'</strong>day</div><div><strong>'+state.wins+'</strong>wins</div><div><strong>'+saved.tickets+'</strong>tickets</div></div><p>'+(win?'New room. New odds. Same terrible friends.':'Keep your tickets. Start fresh with a different plan.')+'</p><div class="row"><button id="next" class="primary">'+(win?'NEXT FLOOR →':'TRY AGAIN →')+'</button></div>');$('#next').onclick=()=>{if(win){state.bank=Math.max(90,state.bank-state.quota+90);state.day++;state.quota=Math.round(180*Math.pow(1.32,state.day-1));state.time=300;state.insured=state.lucky=state.boost=0;}else{Object.assign(state,{day:1,bank:120,quota:180,time:300,plays:0,wins:0,insured:0,lucky:0,boost:0,loan:false,paid:0})}build();hud();state.phase='walk';modal.hidden=true;notify(win?'Welcome to '+themes[(state.day-1)%4][0]:'A fresh start. Pip is finding loose chips.')};}
function interact(){if(state.phase!=='walk'||!near)return;tone(400);if(near.type==='shop')shop();else if(['cashier','lift'].includes(near.type))cashier();else machine(near.type)}
$('#use').onclick=interact;$('#mapbtn').onclick=()=>$('#map').hidden=!$('#map').hidden;$('#pause').onclick=()=>{if(state.phase==='title'||state.phase==='cleared'||state.phase==='over')return;if(state.phase==='pause'){modal.hidden=true;state.phase='walk';return}if(state.phase!=='walk')return;state.phase='pause';show('<span class="tag">TAKE A BREATHER</span><h2>Night paused</h2><p>Reach the quota. Pay at the window.<br>Pick up loose chips or bus tables for a safe return.</p><div class="row"><button id="resume" class="primary">RESUME</button><button id="sound">SOUND '+(muted?'OFF':'ON')+'</button></div>');$('#resume').onclick=()=>{modal.hidden=true;state.phase='walk'};$('#sound').onclick=()=>{muted=!muted;if(audio)audio.suspend();$('#sound').textContent='SOUND '+(muted?'OFF':'ON')}};
let muted=false;const originalTone=tone;tone=(...a)=>{if(!muted)originalTone(...a)};
addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys[e.code]=true;if(!e.repeat&&e.code==='KeyE')interact();if(e.code==='Escape'){$('#pause').click()}});addEventListener('keyup',e=>keys[e.code]=false);
let drag=null;renderer.domElement.addEventListener('pointerdown',e=>{if(state.phase!=='walk')return;drag={id:e.pointerId,x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;yaw-=(e.clientX-drag.x)*.006;pitch=Math.max(-.75,Math.min(.75,pitch-(e.clientY-drag.y)*.004));drag.x=e.clientX;drag.y=e.clientY});function stopDrag(){drag=null}renderer.domElement.addEventListener('pointerup',stopDrag);renderer.domElement.addEventListener('pointercancel',stopDrag);
let stick=$('#stick'),sid=null;stick.onpointerdown=e=>{sid=e.pointerId;stick.setPointerCapture(sid);moveStick(e)};function moveStick(e){if(sid!==e.pointerId)return;let r=stick.getBoundingClientRect(),dx=(e.clientX-r.left-r.width/2)/35,dy=(e.clientY-r.top-r.height/2)/35,l=Math.max(1,Math.hypot(dx,dy));touch.x=dx/l;touch.y=dy/l;$('#stick i').style.transform='translate('+touch.x*27+'px,'+touch.y*27+'px)'}stick.onpointermove=moveStick;function stopStick(){sid=null;touch.x=touch.y=0;$('#stick i').style.transform=''}stick.onpointerup=stick.onpointercancel=stopStick;
function blur(){for(let k in keys)keys[k]=false;stopStick();stopDrag()}addEventListener('blur',blur);document.addEventListener('visibilitychange',()=>{blur()});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
function drawMap(){if($('#map').hidden)return;let c=$('#map').getContext('2d');c.clearRect(0,0,220,170);c.strokeStyle='#ad7f9d';c.strokeRect(16,12,188,145);machines.forEach(o=>{let x=110+o.x*7.3,y=85+o.z*5.6;c.fillStyle=o.type==='cashier'||o.type==='lift'?'#ffe085':'#a8d9d5';c.fillRect(x-4,y-4,8,8)});c.fillStyle='#ff81aa';c.beginPath();c.arc(110+camera.position.x*7.3,85+camera.position.z*5.6,4,0,7);c.fill();c.strokeStyle='#fff';c.beginPath();c.moveTo(110+camera.position.x*7.3,85+camera.position.z*5.6);c.lineTo(110+camera.position.x*7.3-Math.sin(yaw)*10,85+camera.position.z*5.6-Math.cos(yaw)*10);c.stroke()}
function tick(dt){elapsed+=dt;toastTime-=dt;if(toastTime<=0)$('#toast').classList.remove('show');if(!['title','pause','over','cleared'].includes(state.phase)){state.time=Math.max(0,state.time-dt);if(state.time===0){end(state.bank>=state.quota);return}if(state.phase==='walk'){let x=touch.x+(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),z=touch.y+(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0),len=Math.max(1,Math.hypot(x,z));x/=len;z/=len;let dx=(x*Math.cos(yaw)+z*Math.sin(yaw))*dt*3.4,dz=(-x*Math.sin(yaw)+z*Math.cos(yaw))*dt*3.4;function can(px,pz){return Math.abs(px)<11.4&&Math.abs(pz)<11.4&&!colliders.some(o=>Math.hypot(px-o.x,pz-o.z)<o.r+.23)}if(can(camera.position.x+dx,camera.position.z))camera.position.x+=dx;if(can(camera.position.x,camera.position.z+dz))camera.position.z+=dz;camera.position.y=1.65+Math.sin(elapsed*9)*.035*(Math.abs(x)+Math.abs(z));near=null;let dist=3.2;for(let o of machines){let d=Math.hypot(camera.position.x-o.x,camera.position.z-o.z);if(d<dist){dist=d;near=o}}$('#use').textContent=near?near.name:'EXPLORE';$('#use').disabled=!near;for(let i=chips.length-1;i>=0;i--)if(Math.hypot(camera.position.x-chips[i].position.x,camera.position.z-chips[i].position.z)<.7){world.remove(chips[i]);chips.splice(i,1);state.bank+=3;tone(900,.06);notify('Loose chips · +$3')}}
// Companions scavenge, scout and cheer without silently wagering the shared bank.
buddies.forEach((b,i)=>{b.t+=dt;b.g.position.set(Math.sin(b.t*.3+i)*4+i-1,Math.sin(b.t*4)*.035,Math.cos(b.t*.24+i)*3+2);b.g.rotation.y=Math.sin(b.t*.2);});if(Math.floor(elapsed/14)>Math.floor((elapsed-dt)/14)){state.bank+=5;notify('Pip found loose chips · +$5');tone(650,.06)}
if(anim){anim.time+=dt;let reels=document.querySelectorAll('.reel'),symbols=['★','7','♦','♥','♣'];if(anim.kind==='roulette'){let w=$('#wheel');w.textContent=Math.floor(anim.time*35)%13;w.parentElement.style.transform='rotate('+Math.sin(anim.time*8)*3+'deg)'}else reels.forEach((r,i)=>r.textContent=anim.kind==='slots'?symbols[Math.floor(anim.time*17+i*2)%5]:String.fromCodePoint(0x2680+Math.floor(anim.time*20+i*3)%6));if(anim.time>=anim.duration){let a=anim;anim=null;game.running=false;if(a.kind==='roulette'){$('#wheel').textContent=a.final[0];$('#wheel').parentElement.style.transform=''}else reels.forEach((r,i)=>r.textContent=a.kind==='slots'?symbols[a.final[i]]:String.fromCodePoint(0x2680+a.final[i]-1));settle(a.mult,a.text)}}
if(game?.kind==='crash'&&game.running){game.t+=dt;game.value=Math.exp(game.t*.32);$('#chart').textContent=game.value.toFixed(2)+'×';if(game.value>=game.peak){game.running=false;$('#chart').textContent='BURST!';$('#cash').disabled=true;$('#launch').disabled=false;settle(0,'ROCKET LOST');shake=.25}}}
camera.rotation.set(pitch,yaw,0);shake=Math.max(0,shake-dt);if(shake)camera.rotation.z=Math.sin(elapsed*60)*shake*.05;chips.forEach(c=>{c.rotation.z=elapsed;c.position.y=.18+Math.sin(elapsed*2+c.position.x)*.06});uiTime+=dt;if(uiTime>.1){uiTime=0;hud();drawMap()}}
build();hud();title();let last=performance.now(),acc=0;function loop(now){let dt=Math.min(.05,(now-last)/1000);last=now;if(!document.hidden){acc+=dt;while(acc>=1/60){tick(1/60);acc-=1/60}renderer.render(scene,camera)}requestAnimationFrame(loop)}requestAnimationFrame(loop);
window.AfterHours={state:()=>JSON.parse(JSON.stringify({...state,game,camera:{x:camera.position.x,z:camera.position.z,yaw},tickets:saved.tickets,drawCalls:renderer.info.render.calls})),step:seconds=>{for(let i=0;i<Math.ceil(seconds*60);i++)tick(1/60)}};
})();
