(function(){'use strict';
const E=SeatEngine,A=SeatArt,$=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d'),main=$('game'),overlay=$('overlay'),panel=$('panel'),targets=$('targets');let data={best:Array(18).fill(0),last:0,sound:true},state,selected=-1,G,fx=[],drag=null,gesture=null,clock=0,winTimer=0,toastTimer=0,last=0,audio=null,voices=0,seen=false;
try{const d=JSON.parse(localStorage.getItem('seatmates-express-v1'));if(d){seen=true;if(Array.isArray(d.best))data.best=Array.from({length:18},(_,i)=>Number.isInteger(d.best[i])&&d.best[i]>=0&&d.best[i]<=3?d.best[i]:0);data.sound=d.sound!==false;data.last=Number.isInteger(d.last)&&d.last>=0&&d.last<18?d.last:0;state=E.restore(d.state)}}catch(_){}if(!state)state=E.newState(data.last);data.last=state.p.level;
function save(){try{localStorage.setItem('seatmates-express-v1',JSON.stringify({...data,state:E.pack(state)}))}catch(_){}}
function tone(kind='pick'){if(!data.sound)return;try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();if(voices>12)return;const seq=kind==='win'?[392,494,587,784]:kind==='happy'?[523,659]:kind==='bad'?[230,205]:[392];seq.forEach((f,i)=>{const o=audio.createOscillator(),g=audio.createGain(),start=audio.currentTime+i*.09;o.type='sine';o.frequency.setValueAtTime(f,start);g.gain.setValueAtTime(0,start);g.gain.linearRampToValueAtTime(.055,start+.014);g.gain.exponentialRampToValueAtTime(.001,start+.25);o.connect(g);g.connect(audio.destination);voices++;o.onended=()=>voices--;o.start(start);o.stop(start+.28)})}catch(_){}}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2200)}
function close(){overlay.hidden=true;panel.innerHTML='';update()}
function show(html){overlay.hidden=false;panel.innerHTML=html;drag=null;gesture=null;}
function point(ev){const r=canvas.getBoundingClientRect();return{x:(ev.clientX-r.left-G.ox)/G.scale,y:(ev.clientY-r.top-G.oy)/G.scale}}
function buildTargets(){targets.innerHTML='';for(let i=0;i<8;i++)target('seat-'+i,'Seat '+(i+1),()=>place(i));for(let i=0;i<state.p.n;i++)target('guest-'+i,state.p.guests[i].name,()=>{if(selected>=0&&selected!==i&&state.positions[i]>=0)move(selected,state.positions[i]);else select(i)});positionTargets()}
function target(id,label,act){let b=document.createElement('button');b.className='hit';b.id=id;b.setAttribute('aria-label',label);b.addEventListener('pointerdown',ev=>{if(!overlay.hidden||state.won)return;ev.preventDefault();b.setPointerCapture(ev.pointerId);const p=point(ev),guest=id.startsWith('guest')?Number(id.split('-')[1]):state.positions.indexOf(Number(id.split('-')[1]));gesture={guest,start:p,dragged:false};tone()});b.addEventListener('pointermove',ev=>{if(!gesture||gesture.guest<0)return;const p=point(ev);if(Math.hypot(p.x-gesture.start.x,p.y-gesture.start.y)>7)gesture.dragged=true;if(gesture.dragged){selected=gesture.guest;drag={id:gesture.guest,...p};update()}});b.addEventListener('pointerup',ev=>{if(!gesture)return;const g=gesture;gesture=null;const p=point(ev);if(g.dragged){const seat=G.seats.findIndex(a=>Math.abs(a.x-p.x)<44&&Math.abs(a.y-p.y)<62);if(seat>=0)move(g.guest,seat);else if((!G.wide&&p.y>455)||(G.wide&&p.x>535))move(g.guest,-1)}else act();drag=null;update()});b.addEventListener('pointercancel',()=>{gesture=null;drag=null});b.addEventListener('click',ev=>{if(ev.detail===0&&overlay.hidden&&!state.won){act();tone()}});targets.append(b)}
function positionTargets(){if(!G)return;for(let i=0;i<8;i++){const a=G.seats[i],b=$('seat-'+i);if(b)rect(b,a.x-36,a.y-27,72,81)}for(let i=0;i<state.p.n;i++){const seat=state.positions[i],a=seat<0?G.dock[i]:G.seats[seat],b=$('guest-'+i);rect(b,a.x-31,a.y-43,62,seat<0?83:80);b.setAttribute('aria-label',state.p.guests[i].name+(seat<0?' on platform':' in seat '+(seat+1)))}
}
function rect(b,x,y,w,h){b.style.left=(G.ox+x*G.scale)+'px';b.style.top=(G.oy+y*G.scale)+'px';b.style.width=Math.max(44,w*G.scale)+'px';b.style.height=Math.max(44,h*G.scale)+'px'}
function select(i){selected=selected===i?-1:i;update()}
function place(seat){if(selected<0){const i=state.positions.indexOf(seat);if(i>=0)select(i);else toast('Tap a passenger first.');return}move(selected,seat)}
function burst(i){let a=G.seats[state.positions[i]]||G.dock[i];for(let k=0;k<4;k++)fx.push({type:'heart',x:a.x+(k-1.5)*14,y:a.y-40,vx:(k-1.5)*8,age:0,life:1})}
function move(i,s){const before=state.p.guests.map((g,j)=>E.happy(state.p,state.positions,j));if(!E.place(state,i,s))return;let made=false;state.p.guests.forEach((g,j)=>{if(!before[j]&&E.happy(state.p,state.positions,j)){burst(j);made=true}});tone(made?'happy':'bad');if(navigator.vibrate&&made)navigator.vibrate(12);selected=i;update();save();if(state.won)win()}
function win(){selected=-1;const stars=E.stars(state);data.best[state.p.level]=Math.max(data.best[state.p.level],stars);data.last=Math.min(17,state.p.level+1);save();tone('win');for(let k=0;k<64;k++)fx.push({type:'confetti',x:G.vw/2,y:200,vx:(Math.random()-.5)*330,vy:-120-Math.random()*190,age:0,life:2.8,color:['#d69b6c','#89a587','#b995ac','#e1bf64'][k%4]});clearTimeout(winTimer);winTimer=setTimeout(winPanel,900);update()}
function winPanel(){const n=state.p.level,stars=E.stars(state),all=data.best.filter(Boolean).length,stamp=(n+1)%6===0;show(`<div class="eyebrow">DEPARTURE ${String(n+1).padStart(2,'0')} COMPLETE</div><h1>Everyone's happy.</h1><div class="starline">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><p>${state.moves} moves · ${state.hints} hints${stamp?'<br>A new travel stamp for your journal.':''}</p>${stamp?'<div class="stamp">'+['CLOVER<br>MEADOWS','PEACH<br>VALLEY','MOONLIT<br>COAST'][Math.floor(n/6)]+'</div>':''}<div class="actions"><button class="primary" id="next">${n<17?'Next departure':'Travel journal'} →</button><button id="replay">↶ Replay</button></div><p>${all} / 18 journeys · ${data.best.reduce((a,b)=>a+b,0)} stars</p>`);$('next').onclick=()=>n<17?start(n+1):journal();$('replay').onclick=()=>start(n)}
function start(level){clearTimeout(winTimer);state=E.newState(level);data.last=level;selected=-1;fx=[];buildTargets();close();save();toast(level===0?'Pip loves a window. Tap Pip, then seat 1.':'Tap a friend to see their wishes.');update()}
function update(){const p=state.p,yes=p.guests.filter((g,i)=>E.happy(p,state.positions,i)).length;$('level').textContent=String(p.level+1).padStart(2,'0')+' · '+p.title.toUpperCase();$('happiness').textContent='♥ '+yes+' / '+p.n;$('moves').textContent=state.moves+' MOVES';$('undo').disabled=!state.history.length||state.won;$('return').disabled=selected<0||state.positions[selected]<0||state.won;$('hint').disabled=state.won;$('sound').textContent=data.sound?'♪':'♪̸';$('sound').setAttribute('aria-pressed',String(data.sound));
if(selected>=0){const g=p.guests[selected],cs=E.checks(p,state.positions,selected);$('wish').innerHTML='<b>'+g.name+(g.music?' · Music lover':'')+'</b><div class="wish-chips">'+g.rules.map((r,k)=>'<span class="wish-chip '+(state.positions[selected]<0?'':cs[k]?'ok':'no')+'">'+(r.type==='buddy'?'♥ Beside '+p.guests[r.to].name:E.labels[r.type])+'</span>').join('')+'</div>'}else $('wish').innerHTML='<b>'+(state.won?'All aboard.':'A little room for everyone.')+'</b><small>Tap a friend, then a seat. Drag to swap.</small>';positionTargets();main.dataset.state=JSON.stringify({level:p.level,positions:state.positions,moves:state.moves,hints:state.hints,won:state.won,happy:yes,selected,best:data.best,guests:p.guests,geometry:G?{...G}:null});}
function journal(){clearTimeout(winTimer);const unlocked=Math.min(17,data.best.findIndex(x=>!x)===-1?17:data.best.findIndex(x=>!x));show('<div class="eyebrow">YOUR LITTLE ADVENTURE</div><h2>Travel journal</h2><div id="stamps">'+['CLOVER<br>MEADOWS','PEACH<br>VALLEY','MOONLIT<br>COAST'].map((s,i)=>'<div class="stamp '+(data.best.slice(i*6,i*6+6).every(Boolean)?'':'locked')+'">'+s+'</div>').join('')+'</div>'+['The Clover Bus','Peach Valley Rail','The Moon Ferry'].map((n,v)=>'<div class="eyebrow">'+n+'</div><div class="map">'+Array.from({length:6},(_,j)=>{let i=v*6+j;return'<button data-level="'+i+'" '+(i>unlocked?'disabled':'')+'>'+String(i+1).padStart(2,'0')+'<small>'+('★'.repeat(data.best[i])||'·')+'</small></button>'}).join('')+'</div>').join('')+'<button id="resume" class="primary">Back to carriage</button>');panel.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>start(Number(b.dataset.level)));$('resume').onclick=()=>{close();if(state.won)winPanel()}}
function help(intro=false){show('<div class="eyebrow">SMALL JOURNEYS · GOOD COMPANY</div><h1>Seatmates Express</h1><p>Tap a passenger. Tap a seat.<br>Make everyone happy to leave.</p><div class="legend"><div>▣ Window · ↑ Front · ↓ Back</div><div>♥ Sit in the same pair as your named friend.</div><div>♩̸ Keep away from music: beside or directly ahead/behind.</div><div>↔ Leave the other seat in your pair empty.</div></div><p>Drag to swap. ↶ Undo. ✦ Helpful seat.<br>Three stars: no hints, at most two extra moves.<br>No timer. Take the scenic route.</p><button id="begin" class="primary">'+(intro?'All aboard →':'Got it')+'</button>');$('begin').onclick=()=>{close();if(state.won)winPanel();else if(intro)toast('Tap Pip, then a window seat.')}}
$('journal').onclick=journal;$('help').onclick=()=>help();$('sound').onclick=()=>{data.sound=!data.sound;tone();save();update()};$('undo').onclick=()=>{if(E.undo(state)){selected=-1;update();save();tone()}};$('return').onclick=()=>selected>=0&&move(selected,-1);$('hint').onclick=()=>{const i=E.hint(state);if(i!==false){selected=i;burst(i);tone('happy');update();save();toast('One helpful seat. Keep going!');if(state.won)win()}};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!overlay.hidden){close();if(state.won)winPanel()}else if(e.key==='z'&&overlay.hidden)$('undo').click();else if(e.key==='h'&&overlay.hidden)$('hint').click()});document.addEventListener('visibilitychange',()=>{last=0;save();if(document.hidden&&audio)audio.suspend()});window.addEventListener('pagehide',save);
function resize(){const r=main.getBoundingClientRect(),d=Math.min(window.devicePixelRatio||1,1.5);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);G=A.geometry(r.width,r.height);ctx.setTransform(d*G.scale,0,0,d*G.scale,d*G.ox,d*G.oy);drag=null;gesture=null;update()}
new ResizeObserver(resize).observe(main);buildTargets();resize();update();if(!seen)help(true);else if(state.won)winPanel();let reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function frame(ms){requestAnimationFrame(frame);if(document.hidden)return;if(ms-last<25)return;const dt=Math.min(.06,(ms-last)/1000||0);last=ms;clock+=dt;fx=fx.filter(f=>(f.age+=dt)<f.life);const d=Math.min(devicePixelRatio||1,1.5);ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.setTransform(d*G.scale,0,0,d*G.scale,d*G.ox,d*G.oy);A.scene(ctx,G,state,selected,reduced?0:clock,reduced?[]:fx,drag)}requestAnimationFrame(frame);
})();



