'use strict';
(()=>{
const $=s=>document.querySelector(s),modal=$('#modal'),panel=$('#panel');let art;try{art=ChamberArt}catch{panel.innerHTML='<h2>Graphics unavailable</h2><p>Open in Chrome, Edge or Safari with WebGL enabled.</p>';return}
const fresh=()=>({screw:0,lensFound:false,lensOn:false,seenCode:false,seenBack:false,dial:{values:[0,0,0],solved:false},key:false,keyUsed:false,slides:[0,0,0],slideSolved:false,gear:false,gearUsed:false,lights:Array(12).fill(true),circuit:false,star:false,starUsed:false,rings:[0,0,0],ringSolved:false,open:false,time:0,moves:0,hints:0});let data=fresh(),phase='title',selected=null,messageTimer=0,active=null,hold=null,screen=null,stage=0;try{let s=JSON.parse(localStorage.getItem('brass-chamber-v1')||'null');if(s&&Array.isArray(s.slides)&&s.slides.length===3&&Array.isArray(s.lights)&&s.lights.length===12&&s.dial?.values?.length===3){Object.assign(data,s);data.lensOn=false}}catch{}
if(!data.gearUsed&&!data.circuit){data.lights=Array(12).fill(true);for(let i of [0,1,4,7,10])flip(i,false)}
const symbols=['☽','☉','✧'],items={key:['⚿','Brass key','Fits the small keyhole on the right.'],gear:['⚙','Missing cog','A fine-toothed brass cog. Something on the left needs it.'],star:['✧','Astral seal','Fits the star-shaped recess in the lid.']};
let audio,muted=false;function sound(f=420,d=.12,v=.06,type='sine'){if(muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(20,f*.7),audio.currentTime+d);g.gain.setValueAtTime(v,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function success(){[0,1,2,3].forEach((n)=>setTimeout(()=>sound(330*([1,1.25,1.5,2][n]),.3,.045),n*120))}
function save(){try{localStorage.setItem('brass-chamber-v1',JSON.stringify(data))}catch{}}
function notify(text){$('#message').textContent=text;$('#message').classList.add('show');messageTimer=4}
function progress(){stage=[data.lensFound,data.dial.solved,data.slideSolved,data.circuit,data.ringSolved,data.open].filter(Boolean).length;document.querySelectorAll('#stage i').forEach((e,i)=>e.classList.toggle('done',i<stage));$('#lens').disabled=!data.lensFound;$('#lens').classList.toggle('on',data.lensOn);document.body.classList.toggle('lens',data.lensOn);$('#items').innerHTML='';for(let [id,[icon,name]] of Object.entries(items))if(data[id]){let b=document.createElement('button');b.textContent=icon;b.title=name;b.setAttribute('aria-label','Select '+name);b.classList.toggle('selected',selected===id);b.classList.toggle('used',data[id+'Used']);b.onclick=()=>{if(data[id+'Used']){notify(name+' has been installed');return}selected=selected===id?null:id;progress();notify(selected?'Selected '+name:'Item put away')};$('#items').append(b)}}
function show(html,kind){screen=kind;modal.hidden=false;panel.innerHTML=html;hold=null;let close=$('#close');if(close)close.onclick=leave}
function leave(){hold=null;active=null;modal.hidden=true;screen=null;phase=data.open?'complete':'explore';save()}
const back='<div class="row"><button id="close" class="close">BACK TO THE CASKET</button></div>';
function intro(){phase='title';show('<span class="eyebrow">A MECHANICAL SECRET</span><h2>THE BRASS<br>CHAMBER</h2><div class="artifact">✧</div><p>A sealed casket. Six sleeping mechanisms.<br>Every discovery awakens another.</p><div class="row"><button id="start" class="primary">'+(stage>0?'CONTINUE EXAMINING':'EXAMINE THE CASKET')+'</button></div><p class="subtle">Drag to turn. Tap a brass marker to inspect.<br>No timer. Every discovery is saved.</p>','title');$('#start').onclick=()=>{leave();notify(data.lensFound?'Your discoveries are safe.':'The nameplate has a loose screw.')}}
function inspect(id){if(!modal.hidden||phase==='title')return;active=id;phase='inspect';sound(230,.07,.025,'triangle');if(id==='plaque'){if(data.lensFound){show('<span class="eyebrow">BENEATH THE NAMEPLATE</span><h2>An empty recess</h2><p>The revealing lens was hidden here.</p>'+back,'plaque');return}show('<span class="eyebrow">A. VESPER · 1893</span><h2>A loose screw</h2><div class="artifact" id="screw-art">⊕</div><p class="subtle">Hold to loosen the brass screw.</p><button class="hold" id="loosen"><i></i><span>TURN COUNTERCLOCKWISE</span></button>'+back,'plaque');bindHold('#loosen',2.2,()=>{data.lensFound=true;save();progress();success();show('<span class="eyebrow">DISCOVERED</span><h2>The revealing lens</h2><div class="artifact">◉</div><p>A second world hides beneath the varnish.<br>Use the lens button to see it.</p>'+back,'found');notify('A concealed lens. The box has more to tell.')});}
if(id==='front-clue'){if(!data.lensOn){notify('The varnish hides something. Try the lens.');leave();return}data.seenCode=true;save();show('<span class="eyebrow">REVEALING LENS</span><h2>Three celestial marks</h2><div class="clue">☽ II · ☉ V · ✧ I</div><p class="subtle">Moon, sun, star. Read in that order.</p>'+back,'clue');}
if(id==='back-clue'){data.seenBack=true;save();show('<span class="eyebrow">THE OBSERVATORY PLATE</span><h2>The maker’s diagram</h2><div class="clue">III · I · II</div><p class="subtle">Three sliding pins. Top is zero.</p>'+(data.lensOn?'<div class="clue">☽ 1 · ☉ 3 · ✧ 2</div><p class="subtle">The lid uses quarter-turns from its notch.</p>':'<p class="subtle">Something else is concealed beneath the diagram.</p>')+back,'back-clue');}
if(id==='dial'){if(data.dial.solved){show('<span class="eyebrow">THE FRONT LOCK</span><h2>The drawer is open</h2><div class="artifact">⚿</div><p>The brass key belongs to another face.</p>'+back,'dial');return}show('<span class="eyebrow">THE CELESTIAL LOCK</span><h2>Moon. Sun. Star.</h2><div class="dials">'+symbols.map((s,i)=>'<div><small>'+s+'</small><button class="dial" data-dial="'+i+'" aria-label="Turn '+['moon','sun','star'][i]+' dial">'+data.dial.values[i]+'</button></div>').join('')+'</div><p class="subtle">Turn each ring to its hidden mark.</p><button id="check-dial" class="primary">TEST THE LOCK</button><div id="status" class="status"></div>'+back,'dial');document.querySelectorAll('[data-dial]').forEach(b=>b.onclick=()=>{let i=+b.dataset.dial;data.dial.values[i]=(data.dial.values[i]+1)%6;data.moves++;b.textContent=data.dial.values[i];sound(370+i*70,.045,.045,'triangle');save()});$('#check-dial').onclick=()=>{if(data.dial.values.join()==='2,5,1'){data.dial.solved=true;data.key=true;selected='key';progress();save();success();show('<span class="eyebrow">A DRAWER SLIDES OPEN</span><h2>The brass key</h2><div class="artifact">⚿</div><p class="subtle">A second lock waits on the right.</p>'+back,'found');notify('A heavy click. Something has moved.')}else{$('#status').textContent='The rings resist. Something is misaligned.';sound(120,.15,.035,'triangle')}};}
if(id==='pins'){if(!data.keyUsed){show('<span class="eyebrow">THE RIGHT FACE</span><h2>A narrow keyhole</h2><div class="artifact">⚿</div><p class="subtle">'+(data.key?'The collected brass key fits this lock.':'Find the key in the front drawer.')+'</p><button id="insert-key" class="primary" '+(!data.key?'disabled':'')+'>INSERT BRASS KEY</button>'+back,'key');$('#insert-key').onclick=()=>{if(!data.key)return;data.keyUsed=true;selected=null;progress();save();success();leave();inspect('pins')};return}if(data.slideSolved){show('<h2>The pins are released</h2><p>A cog was hidden inside the channel.</p>'+back,'pins');return}show('<span class="eyebrow">THE SLIDING PINS</span><h2>Three heights</h2><div class="sliders">'+[0,1,2].map(i=>'<div><button data-up="'+i+'" aria-label="Raise pin '+(i+1)+'">▲</button><div class="rail"><i id="pin-'+i+'"></i></div><b id="height-'+i+'">'+data.slides[i]+'</b><button data-down="'+i+'" aria-label="Lower pin '+(i+1)+'">▼</button></div>').join('')+'</div><button id="test-pins" class="primary">RELEASE THE PINS</button><div class="status" id="status"></div>'+back,'pins');function paint(){data.slides.forEach((v,i)=>{$('#pin-'+i).style.top=(v/3*82)+'%';$('#height-'+i).textContent=v})}paint();for(let dir of ['up','down'])document.querySelectorAll('[data-'+dir+']').forEach(b=>b.onclick=()=>{let i=+b.dataset[dir];data.slides[i]=Math.max(0,Math.min(3,data.slides[i]+(dir==='up'?-1:1)));data.moves++;paint();sound(200+data.slides[i]*40,.06,.035,'triangle');save()});$('#test-pins').onclick=()=>{if(data.slides.join()==='3,1,2'){data.slideSolved=true;data.gear=true;selected='gear';progress();save();success();show('<span class="eyebrow">DISCOVERED</span><h2>The missing cog</h2><div class="artifact">⚙</div><p class="subtle">The left mechanism is missing a toothwheel.</p>'+back,'found')}else{$('#status').textContent='The pins have not reached their notches.';sound(130,.1)}};}
if(id==='gears'){if(!data.gearUsed){show('<span class="eyebrow">THE LEFT FACE</span><h2>A missing toothwheel</h2><div class="artifact">⚙</div><p class="subtle">'+(data.gear?'The collected cog belongs in this socket.':'The sliding channel may hide the missing part.')+'</p><button id="insert-gear" class="primary" '+(!data.gear?'disabled':'')+'>FIT THE COG</button>'+back,'gears');$('#insert-gear').onclick=()=>{if(!data.gear)return;data.gearUsed=true;selected=null;progress();save();success();leave();inspect('gears')};return}if(data.circuit){show('<h2>The machine is awake</h2><p>The astral seal belongs in the lid.</p>'+back,'gears');return}show('<span class="eyebrow">THE RESONANCE ENGINE</span><h2>Wake every node</h2><div class="maze">'+data.lights.map((v,i)=>'<button class="tile '+(v?'light':'')+'" data-node="'+i+'" aria-label="Toggle node '+(i+1)+'">'+(v?'✦':'·')+'</button>').join('')+'</div><p class="subtle">A node turns itself and its neighbours.</p><div class="row"><button id="reset-grid">RESET PATTERN</button></div>'+back,'circuit');document.querySelectorAll('[data-node]').forEach(b=>b.onclick=()=>{let i=+b.dataset.node;flip(i);data.moves++;sound(240+i*35,.09,.03,'triangle');paintGrid();if(data.lights.every(Boolean)){data.circuit=true;data.star=true;selected='star';save();progress();success();show('<span class="eyebrow">THE ENGINE SINGS</span><h2>The astral seal</h2><div class="artifact">✧</div><p class="subtle">Fit it into the star-shaped recess above.</p>'+back,'found')}else save()});$('#reset-grid').onclick=()=>{data.lights=Array(12).fill(true);for(let i of [0,1,4,7,10])flip(i,false);paintGrid();save()};}
if(id==='lid'){if(!data.starUsed){show('<span class="eyebrow">THE LID</span><h2>An empty star</h2><div class="artifact">✧</div><p class="subtle">'+(data.star?'The astral seal fits the recess.':'The resonance engine protects the seal.')+'</p><button id="insert-star" class="primary" '+(!data.star?'disabled':'')+'>FIT THE ASTRAL SEAL</button>'+back,'lid');$('#insert-star').onclick=()=>{if(!data.star)return;data.starUsed=true;selected=null;progress();save();success();leave();inspect('lid')};return}if(data.ringSolved){finalLock();return}show('<span class="eyebrow">THE OBSERVATORY</span><h2>Turn the heavens</h2><div class="dialgroup">'+symbols.map((s,i)=>'<div><small>'+s+'</small><button class="dial" data-ring="'+i+'" aria-label="Turn '+['moon','sun','star'][i]+' orbit">'+data.rings[i]+'</button></div>').join('')+'</div><p class="subtle">Quarter-turns from the north notch.<br>The lens reveals the maker’s orbit chart.</p><div class="row"><button id="test-orbits" class="primary">ALIGN THE HEAVENS</button></div><div id="status" class="status"></div>'+back,'orbits');document.querySelectorAll('[data-ring]').forEach(b=>b.onclick=()=>{let i=+b.dataset.ring;data.rings[i]=(data.rings[i]+1)%4;b.textContent=data.rings[i];data.moves++;sound(600+i*100,.09,.03);save()});$('#test-orbits').onclick=()=>{if(data.rings.join()==='1,3,2'){data.ringSolved=true;progress();save();success();finalLock()}else{$('#status').textContent='The constellation remains silent.';sound(160,.1)}};}
if(id==='core'){if(data.open)ending();else inspect('lid')}
}
function flip(i,count=true){let x=i%4,y=Math.floor(i/4);for(let [dx,dy] of [[0,0],[1,0],[-1,0],[0,1],[0,-1]]){let xx=x+dx,yy=y+dy;if(xx>=0&&xx<4&&yy>=0&&yy<3)data.lights[yy*4+xx]=!data.lights[yy*4+xx]}}
function paintGrid(){document.querySelectorAll('[data-node]').forEach((b,i)=>{b.classList.toggle('light',data.lights[i]);b.textContent=data.lights[i]?'✦':'·'})}
function bindHold(sel,duration,done){let b=$(sel);b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);hold={time:0,duration,done,button:b,id:e.pointerId};sound(170,.15,.03,'triangle')};b.onpointerup=b.onpointercancel=()=>{hold=null;let i=b.querySelector('i');if(i)i.style.width='0%'};b.onkeydown=e=>{if(e.code==='Space'||e.code==='Enter'){e.preventDefault();if(!hold)hold={time:0,duration,done,button:b,id:'keyboard'}}};b.onkeyup=()=>{hold=null};}
function finalLock(){show('<span class="eyebrow">THE LAST SEAL</span><h2>The chamber is listening</h2><div class="artifact">✧</div><button id="release" class="hold primary"><i></i><span>HOLD TO OPEN THE CHAMBER</span></button>'+back,'final');bindHold('#release',1.8,()=>{data.open=true;progress();save();success();leave();notify('The chamber opens.');setTimeout(()=>{if(phase==='complete'&&modal.hidden)ending()},1800)})}
function ending(){phase='complete';show('<span class="eyebrow">THE FIRST SECRET</span><h2>A light that remembers</h2><div class="artifact success">✧</div><p>The casket was never a prison.<br>It was a lantern waiting to be lit.</p><div class="plate"><span class="progress-text">6 SEALS OPEN · '+data.moves+' MOVES<br>'+Math.floor(data.time/60)+' MIN · '+data.hints+' HINTS</span></div><div class="row"><button id="admire" class="primary">ADMIRE THE OPEN CASKET</button><button id="again">NEW EXAMINATION</button></div><p class="subtle">A complete handcrafted puzzle box.</p>','ending');$('#admire').onclick=()=>{art.face(0);leave()};$('#again').onclick=confirmReset}
function confirmReset(){show('<h2>A fresh examination?</h2><p>This resets this casket’s discoveries.</p><div class="row"><button id="restart" class="primary">START FRESH</button><button id="close">KEEP MY DISCOVERIES</button></div>','reset');$('#restart').onclick=()=>{data=fresh();for(let i of [0,1,4,7,10])flip(i,false);selected=null;progress();save();leave();art.face(0);notify('The nameplate has a loose screw.')};}
$('#lens').onclick=()=>{if(!data.lensFound)return;data.lensOn=!data.lensOn;progress();sound(data.lensOn?780:330,.2,.025);notify(data.lensOn?'Hidden inscriptions emerge.':'Ordinary sight restored.')};
function journal(){show('<span class="eyebrow">THE MAKER’S JOURNAL</span><h2>Discoveries</h2><div class="journal">'+(data.lensFound?'<p>◉ The revealing lens sees beneath the varnish.</p>':'<p>No discoveries yet. Examine the nameplate.</p>')+(data.seenCode?'<p>☽ II · ☉ V · ✧ I<br>Moon, sun, star: the front lock.</p>':'')+(data.seenBack?'<p>Sliding pins: III · I · II.<br>Count downward from zero.</p>':'')+(data.seenBack&&data.lensFound?'<p>The hidden orbit chart can be read through the lens on the back face.</p>':'')+(data.circuit?'<p>✧ The engine protected an astral seal for the lid.</p>':'')+'</div>'+back,'journal')}
$('#journal').onclick=journal;
function hint(){data.hints++;save();let h=!data.lensFound?'Front: hold the nameplate screw until the lens is released.':!data.dial.solved?'Turn on the lens and read the front inscription: moon 2, sun 5, star 1.':!data.keyUsed?'Right: insert the brass key from the front drawer.':!data.slideSolved?'Back: III · I · II. Lower the pins to 3, 1 and 2.':!data.gearUsed?'Left: fit the cog from the sliding channel.':!data.circuit?'Reset the pattern. Press nodes 1, 2, 5, 8 and 11 once each.':!data.starUsed?'Top: fit the astral seal into the star recess.':!data.ringSolved?'The hidden back chart gives moon 1, sun 3, star 2.':'Hold the last seal to release the lid.';show('<span class="eyebrow">A GENTLE NUDGE</span><h2>Look a little closer</h2><p>'+h+'</p>'+back,'hint')}
$('#hint').onclick=hint;$('#menu').onclick=()=>showMenu();function showMenu(){show('<span class="eyebrow">THE BRASS CHAMBER</span><h2>Take your time</h2><div class="row"><button id="close" class="primary">CONTINUE</button><button id="sound">SOUND '+(muted?'OFF':'ON')+'</button><button id="reset">START FRESH</button></div><p class="subtle">English UI · Single handcrafted casket<br>Every discovery is saved on this device.</p>','menu');$('#sound').onclick=()=>{muted=!muted;$('#sound').textContent='SOUND '+(muted?'OFF':'ON')};$('#reset').onclick=confirmReset}
$('#left').onclick=()=>{art.rotate(-1);sound(180,.08,.02)};$('#right').onclick=()=>{art.rotate(1);sound(180,.08,.02)};
const points=[{id:'plaque',name:'Nameplate',p:[0,3.11,1.15],face:0},{id:'dial',name:'Celestial lock',p:[0,2.38,1.22],face:0},{id:'front-clue',name:'Hidden inscription',p:[0,1.87,1.16],face:0,secret:true},{id:'pins',name:'Sliding pins',p:[1.44,2.3,0],face:1},{id:'gears',name:'Resonance engine',p:[-1.47,2.35,0],face:3},{id:'back-clue',name:'Maker’s diagram',p:[0,2.35,-1.15],face:2},{id:'lid',name:'Observatory lid',p:[0,3.69,0],face:4}];points.forEach(o=>{let b=document.createElement('button');b.className='spot';b.textContent='+';b.setAttribute('aria-label','Inspect '+o.name);b.title=o.name;b.dataset.spot=o.id;const activate=()=>{art.face(o.face);inspect(o.id)};b.onclick=activate;b.onpointerdown=e=>{if(e.pointerType==='touch')b.setPointerCapture(e.pointerId)};b.onpointerup=e=>{if(e.pointerType==='touch'){e.preventDefault();activate()}};o.el=b;o.vector=new THREE.Vector3(...o.p);$('#spots').append(b)});
function markers(){let a=art.angle(),e=art.elevation();let idx=((Math.round(a/(Math.PI/2))%4)+4)%4;$('#face').textContent=e>.63?'TOP':['FRONT','RIGHT','BACK','LEFT'][idx];for(let o of points){let facing=o.face===4?e>.4:Math.cos(a-o.face*Math.PI/2)>.58&&e<.82;let v=o.vector.clone().project(art.camera);let visible=facing&&v.z<1&&v.x>-.85&&v.x<.85&&v.y>-.8&&v.y<.72&&(!o.secret||data.lensOn)&&!data.open;o.el.hidden=!visible;if(visible){o.el.style.left=((v.x+1)/2*innerWidth)+'px';o.el.style.top=((-v.y+1)/2*innerHeight)+'px';let available=o.id==='plaque'?!data.lensFound:o.id==='dial'?data.lensFound&&!data.dial.solved:o.id==='pins'?data.key&&!data.slideSolved:o.id==='gears'?data.gear&&!data.circuit:o.id==='lid'?data.star&&!data.open:false;o.el.classList.toggle('available',available)}}}
let pointers=new Map(),drag=null;const canvas=art.renderer.domElement;canvas.onpointerdown=e=>{if(!modal.hidden)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});drag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!modal.hidden||!pointers.has(e.pointerId))return;let old=pointers.get(e.pointerId);if(pointers.size===2){let other=[...pointers.entries()].find(([id])=>id!==e.pointerId)[1];let before=Math.hypot(old.x-other.x,old.y-other.y),after=Math.hypot(e.clientX-other.x,e.clientY-other.y);art.zoom((before-after)*.008)}else{art.orbit(e.clientX-old.x,e.clientY-old.y)}pointers.set(e.pointerId,{x:e.clientX,y:e.clientY})};canvas.onpointerup=canvas.onpointercancel=e=>{pointers.delete(e.pointerId);drag=null};canvas.onwheel=e=>{e.preventDefault();if(modal.hidden)art.zoom(e.deltaY*.004)};
addEventListener('keydown',e=>{if(!modal.hidden){if(e.code==='Escape')leave();return}if(e.code==='ArrowLeft'){$('#left').click();e.preventDefault()}if(e.code==='ArrowRight'){$('#right').click();e.preventDefault()}if(e.code==='ArrowUp'){art.face(4);e.preventDefault()}if(e.code==='KeyL')$('#lens').click();if(e.code==='KeyJ')journal()});addEventListener('blur',()=>{hold=null;pointers.clear()});document.addEventListener('visibilitychange',()=>{hold=null;pointers.clear();save()});addEventListener('resize',()=>art.resize());
progress();intro();let time=0,last=performance.now(),saveTimer=0;function step(dt){time+=dt;if(phase==='explore'||phase==='inspect')data.time+=dt;if(messageTimer>0){messageTimer-=dt;if(messageTimer<=0)$('#message').classList.remove('show')}if(hold){hold.time+=dt;hold.button.querySelector('i').style.width=Math.min(100,hold.time/hold.duration*100)+'%';if(screen==='plaque'){data.screw=hold.time;$('#screw-art').style.transform='rotate('+(-hold.time*160)+'deg)'}if(hold.time>=hold.duration){let done=hold.done;hold=null;done()}}saveTimer+=dt;if(saveTimer>10){saveTimer=0;save()}art.update(dt,time,data);markers()}
function frame(t){let dt=Math.min(.05,(t-last)/1000);last=t;if(!document.hidden)step(dt);requestAnimationFrame(frame)}requestAnimationFrame(frame);window.BrassChamber={state:()=>JSON.parse(JSON.stringify({...data,phase,screen,stage,angle:art.angle(),calls:art.renderer.info.render.calls})),step:s=>{for(let i=0;i<Math.ceil(s*60);i++)step(1/60)}};
})();
