'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],A=MunchArt;
const D={bolt:{rank:1,m:1,r:10,s:.62,n:'Loose bolt'},can:{rank:1,m:1,r:11,s:.7,n:'Soda can'},cup:{rank:1,m:1,r:12,s:.7,n:'Coffee cup'},duck:{rank:1,m:2,r:15,s:.7,n:'Rubber duck'},donut:{rank:1,m:1,r:14,s:.67,n:'Tiny doughnut'},gear:{rank:1,m:2,r:13,s:.68,n:'Steel gear'},ball:{rank:1,m:2,r:14,s:.75,n:'Beach ball'},battery:{rank:1,m:2,r:12,s:.7,n:'Battery'},cone:{rank:2,m:3,r:17,s:.85,n:'Traffic cone'},chair:{rank:2,m:4,r:19,s:.9,n:'Little chair'},crate:{rank:2,m:5,r:24,s:.86,n:'Crate'},barrel:{rank:2,m:5,r:22,s:.86,n:'Barrel'},bike:{rank:2,m:6,r:27,s:.82,n:'Bicycle'},robot:{rank:2,m:4,r:21,s:.85,n:'Toy robot'},car:{rank:3,m:12,r:38,s:.94,n:'Toy car'},fridge:{rank:3,m:12,r:27,s:.92,n:'Fridge'},arcade:{rank:3,m:14,r:31,s:.95,n:'Arcade machine'},lamp:{rank:3,m:8,r:21,s:.95,n:'Streetlight'},kiosk:{rank:4,m:22,r:43,s:1.02,n:'Snack kiosk'},bus:{rank:4,m:28,r:48,s:1.02,n:'Mini bus'},rocket:{rank:4,m:25,r:35,s:1,n:'Rocket'},tower:{rank:4,m:26,r:39,s:1,n:'Water tower'},carousel:{rank:4,m:28,r:48,s:.92,n:'Carousel'}};
const LEVELS=[{xp:0,cap:14,field:72},{xp:18,cap:28,field:87},{xp:62,cap:52,field:102},{xp:128,cap:84,field:119},{xp:220,cap:120,field:136}];
const TOYS=['duck','rocket','robot','gear','donut','ball','duck','rocket','robot','gear','donut','ball'];
const SKINS=[{name:'Coral Classic',cost:0},{name:'Mint Machine',cost:600},{name:'Berry Buddy',cost:1200},{name:'Moon Magnet',cost:1800}];
const SAVE='magnet-munch-run-v1',META='magnet-munch-meta-v1';
let run=null,phase='intro',meta={coins:0,skin:0,skins:[0],toys:[],best:0},input=null,keys=new Set(),coinsVis=0,W=1,H=1,dpr=1,view={x:240,y:275,scale:1},zoomed=false;
let sparks=[],rings=[],floats=[],time=0,acc=0,last=0,drawAt=0,hudAt=0,saveAt=0,toastTimer,celebrateTimer,audio,muted=false,lastAudio=0,pulseFlash=0;
const canvas=$('#world'),ctx=canvas.getContext('2d');
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=a=>a[Math.floor(Math.random()*a.length)],clone=x=>JSON.parse(JSON.stringify(x));
function get(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}}function put(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
meta=get(META,meta);if(!Array.isArray(meta.skins))meta.skins=[0];if(!Array.isArray(meta.toys))meta.toys=[];coinsVis=meta.coins;
function power(){return Math.min(5,LEVELS.filter(l=>run.xp>=l.xp).length)}
function cap(){return Math.round(LEVELS[power()-1].cap*(1+run.perks.cargo*.15))}
function field(){return LEVELS[power()-1].field*(1+run.perks.field*.12)*(run.boost>0?1.65:1)}
function cargo(){return run.items.filter(i=>i.state==='cargo')}
function mass(){return cargo().reduce((s,i)=>s+i.m,0)}
function theme(){return (run.district-1)%3}
function percent(){return Math.floor(run.banked/run.total*100)}
function save(){if(run&&phase!=='intro')put(SAVE,run);put(META,meta)}
function sound(kind='pickup',n=0){if(muted)return;try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();audio.resume();let t=audio.currentTime;if(kind==='pickup'&&t-lastAudio<.045)return;lastAudio=t;let freq=kind==='pickup'?[440,523.25,587.33,659.25,783.99][n%5]:kind==='cash'?[523.25,659.25,783.99,1046.5][n%4]:kind==='pulse'?100:kind==='drop'?180:kind==='tap'?500:kind==='reveal'?880:600;let notes=kind==='level'?[392,523.25,659.25,783.99,1046.5]:kind==='win'?[523.25,659.25,783.99,1046.5,1174.66]:[freq];notes.forEach((f,k)=>{let o=audio.createOscillator(),g=audio.createGain(),at=t+k*.09;o.type=kind==='pulse'?'triangle':'sine';o.frequency.setValueAtTime(f,at);if(kind==='pickup')o.frequency.exponentialRampToValueAtTime(f*1.3,at+.09);if(kind==='pulse')o.frequency.exponentialRampToValueAtTime(420,at+.18);o.connect(g);g.connect(audio.destination);g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(kind==='pulse'?.07:.045,at+.008);g.gain.exponentialRampToValueAtTime(.0001,at+.3);o.start(at);o.stop(at+.33)})}catch{}}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2400)}
function celebrate(title,sub){let e=$('#celebration');e.innerHTML='<strong>'+title+'</strong><small>'+sub+'</small>';e.classList.remove('show');void e.offsetWidth;e.classList.add('show');clearTimeout(celebrateTimer);celebrateTimer=setTimeout(()=>e.classList.remove('show'),2200)}
function burst(x,y,n=12,color='#f6d586'){for(let k=0;k<n;k++){let a=Math.random()*A.TAU,s=20+Math.random()*65;sparks.push({x,y:y*.8-22,vx:Math.cos(a)*s,vy:Math.sin(a)*s-30,life:.55+Math.random()*.5,color,size:1.5+Math.random()*2})}if(sparks.length>160)sparks.splice(0,sparks.length-160)}
function float(x,y,text,color='#fff4c7'){floats.push({x,y:y*.8-40,text,color,life:1.2})}
function generate(district=1,perks={field:0,cargo:0,speed:0}){let items=[],id=0,th=(district-1)%3,pools=[th===0?['can','bolt','cup','gear','duck']:th===1?['donut','ball','cup','duck','gear']:['bolt','battery','gear','can'],th===2?['barrel','crate','robot','cone']:['chair','crate','barrel','bike','cone'],th===1?['arcade','car','fridge','lamp']:th===2?['fridge','arcade','car','lamp']:['car','fridge','lamp','arcade'],th===1?['carousel','kiosk','bus','rocket']:th===2?['rocket','tower','bus','kiosk']:['kiosk','bus','tower','rocket']];
 let counts=[26+Math.min(6,Math.floor(district/2)),12,8,4];for(let rank=1;rank<=4;rank++){for(let n=0;n<counts[rank-1];n++){let kind=pools[rank-1][n%pools[rank-1].length],d=D[kind],x,y;for(let attempt=0;attempt<90;attempt++){x=25+Math.random()*430;y=145+Math.random()*425;if(y<205&&Math.abs(x-240)<92)continue;if(!items.some(j=>Math.hypot(x-j.x,y-j.y)<(d.r+j.radius)*.57))break}if(rank===1&&n<8){x=175+(n%4)*34;y=450+Math.floor(n/4)*42}items.push({id:++id,kind,x,y,ox:x,oy:y,vx:0,vy:0,z:0,angle:(Math.random()-.5)*.7,state:'ground',rank:d.rank,m:d.m,radius:d.r,size:d.s,flash:0,cling:n*.37})}}
 let cover=items.filter(i=>i.rank>=3);for(let n=0;n<2;n++){let parent=cover[n*3+1],toyId=((district-1)*2+n)%12,kind=TOYS[toyId];items.push({id:++id,kind,toy:true,toyId,cover:parent.id,x:parent.x,y:parent.y,vx:0,vy:0,z:0,angle:0,state:'hidden',rank:1,m:1,radius:11,size:.67,flash:0,cling:n})}
 return {district,perks:clone(perks),items,player:{x:240,y:535,vx:0,vy:0,tx:240,ty:535},xp:0,banked:0,total:items.reduce((s,i)=>s+i.m,0),combo:0,comboTime:0,boost:0,pulse:0,deposit:0,delivered:0,toys:0,perfect:false,complete:false,rewarded:false}}
function start(district=1,perks){run=generate(district,perks);phase='play';input=null;keys.clear();sparks=[];rings=[];floats=[];zoomed=false;closeModal();resize();hud();save();toast('Drag your magnet. Gather a haul. Feed Gus!')}
function pickup(i){if(i.state!=='ground'||i.rank>power()||mass()+i.m>cap())return;i.state='cargo';i.cling=cargo().length*2.399;i.flash=1;i.z=23;run.combo=run.comboTime>0?run.combo+1:1;run.comboTime=2;let multiplier=1+Math.min(8,Math.floor(run.combo/5))*.1;i.value=Math.round(i.m*10*multiplier);sound('pickup',run.combo);burst(i.x,i.y,5,i.toy?'#f1d065':'#f2d7a2');if(run.combo>=5&&run.combo%5===0){float(run.player.x,run.player.y,run.combo+' CLINGS!');if(navigator.vibrate)navigator.vibrate(8)}if(run.combo>0&&run.combo%12===0&&run.boost<=0){run.boost=3;celebrate('Magnetic mayhem!','SUPER FIELD · 3 SECONDS');sound('pulse');rings.push({x:run.player.x,y:run.player.y,life:1.1,max:1.1,r:field()})}save()}
function reveal(){for(let i of run.items){if(i.state!=='hidden')continue;let p=run.items.find(j=>j.id===i.cover);if(p.state!=='ground'||Math.hypot(p.x-p.ox,p.y-p.oy)>28){i.state='ground';i.flash=1;burst(i.x,i.y,20,'#f0ce77');float(i.x,i.y,'LOST TOY!','#ffe3a1');sound('reveal');toast('A lost toy! Bring it home to Gus.')}}}
function beginDeposit(){if(!cargo().length)return;run.deposit=Math.max(run.deposit,.08)}
function launchDeposit(){let i=cargo()[0];if(!i)return;i.state='delivery';i.flight=0;i.from={x:i.x,y:i.y,z:i.z};i.flash=1;run.deposit=cargo().length?.1:0}
function cash(i){let old=power();i.state='done';run.banked+=i.m;run.xp+=i.m;run.delivered++;meta.coins+=i.value||i.m*10;if(i.toy){run.toys++;if(!meta.toys.includes(i.toyId))meta.toys.push(i.toyId);burst(240,78,20,'#f4d784');float(240,80,'TOY FOUND!','#ffdf84');sound('reveal')}else{sound('cash',run.delivered);float(240,85,'+'+(i.value||i.m*10))}burst(240,78,5,'#c1e1bd');if(power()>old){celebrate('Bigger pull!','LEVEL '+power()+' · '+['','SMALL STUFF','CHAIRS & CRATES','CARS & MACHINES','THE BIG STUFF','EVERYTHING!'][power()]);sound('level');if(navigator.vibrate)navigator.vibrate([12,30,12]);rings.push({x:run.player.x,y:run.player.y,life:1,max:1,r:field()})}save();if(run.items.every(j=>j.state==='done'))finish(true)}
function pulse(){if(phase!=='play'||run.pulse>0||modalOpen())return;run.pulse=5;run.boost=2.6;pulseFlash=.5;rings.push({x:run.player.x,y:run.player.y,life:.8,max:.8,r:field()});sound('pulse');burst(run.player.x,run.player.y,22,'#eecb7e');if(navigator.vibrate)navigator.vibrate(15);for(let i of run.items){if(i.state!=='ground'||i.rank>power())continue;let dx=run.player.x-i.x,dy=run.player.y-i.y,d=Math.hypot(dx,dy);if(d<field()&&d>1){i.vx+=dx/d*140;i.vy+=dy/d*140;i.z=Math.max(i.z,8)}}hud()}
function drop(){if(phase!=='play'||modalOpen())return;let carried=cargo();for(let [n,i] of carried.entries()){let a=n*2.399;i.state='ground';i.vx=Math.cos(a)*95;i.vy=Math.sin(a)*95;i.z=0;i.flash=.5}run.combo=0;run.comboTime=0;sound('drop');save();hud();toast('A little breathing room.')}
function step(dt){if(!run||phase!=='play'||modalOpen())return;let p=run.player,oldx=p.x,oldy=p.y;run.pulse=Math.max(0,run.pulse-dt);run.boost=Math.max(0,run.boost-dt);run.comboTime=Math.max(0,run.comboTime-dt);if(!run.comboTime)run.combo=0;
 let ax=(keys.has('arrowright')||keys.has('d')?1:0)-(keys.has('arrowleft')||keys.has('a')?1:0),ay=(keys.has('arrowdown')||keys.has('s')?1:0)-(keys.has('arrowup')||keys.has('w')?1:0);let speed=280*(1+run.perks.speed*.1);if(ax||ay){let d=Math.hypot(ax,ay);p.tx=clamp(p.x+ax/d*60,10,470);p.ty=clamp(p.y+ay/d*60,110,584)}let dx=p.tx-p.x,dy=p.ty-p.y,dist=Math.hypot(dx,dy),vx=dist>1?dx/dist*Math.min(speed,dist*7):0,vy=dist>1?dy/dist*Math.min(speed,dist*7):0;p.vx+=(vx-p.vx)*Math.min(1,dt*11);p.vy+=(vy-p.vy)*Math.min(1,dt*11);p.x=clamp(p.x+p.vx*dt,8,472);p.y=clamp(p.y+p.vy*dt,100,586);
 let load=mass(),capacity=cap(),range=field(),attached=cargo();for(let i of run.items){i.flash=Math.max(0,i.flash-dt*3);if(i.state==='ground'){let rx=p.x-i.x,ry=p.y-i.y,d=Math.hypot(rx,ry),can=i.rank<=power()&&load+i.m<=capacity;if(d<range&&can){let force=clamp((range-d)/range,.15,1)*800/Math.pow(i.m,.2);i.vx+=rx/Math.max(1,d)*force*dt;i.vy+=ry/Math.max(1,d)*force*dt;i.z+=(12-i.z)*dt*8;if(d<20+i.radius*.15){pickup(i);load+=i.m;continue}}else i.z+=(0-i.z)*dt*8;i.x=clamp(i.x+i.vx*dt,5,475);i.y=clamp(i.y+i.vy*dt,125,587);i.vx*=Math.exp(-dt*3.5);i.vy*=Math.exp(-dt*3.5);i.angle+=i.vx*dt*.002;if(i.x<6||i.x>474)i.vx*=-.4;if(i.y<126||i.y>586)i.vy*=-.4}
 else if(i.state==='cargo'){let n=attached.indexOf(i),a=i.cling,rad=14+Math.sqrt(Math.max(0,n))*11,tx=p.x+Math.cos(a)*rad,ty=p.y+20+Math.sin(a)*rad*.65;let fx=(tx-i.x)*18-i.vx*6,fy=(ty-i.y)*18-i.vy*6;i.vx+=fx*dt;i.vy+=fy*dt;i.x+=i.vx*dt;i.y+=i.vy*dt;i.z+=(30+n%3*9-i.z)*dt*7;i.angle+=Math.sin(time*2+a)*dt*.5}
 else if(i.state==='delivery'){i.flight+=dt*2.2;let f=Math.min(1,i.flight),e=1-Math.pow(1-f,2);i.x=i.from.x+(240-i.from.x)*e;i.y=i.from.y+(78-i.from.y)*e;i.z=i.from.z+(54-i.from.z)*e+Math.sin(f*Math.PI)*45;if(f>=1)cash(i)}}
 // A spatial grid keeps gentle floor collisions inexpensive on phones.
 let buckets=new Map();for(let i of run.items){if(i.state!=='ground')continue;let gx=Math.floor(i.x/64),gy=Math.floor(i.y/64);for(let x=gx-1;x<=gx+1;x++)for(let y=gy-1;y<=gy+1;y++){let list=buckets.get(x+','+y);if(!list)continue;for(let j of list){let dx=i.x-j.x,dy=i.y-j.y,d=Math.hypot(dx,dy),min=(i.radius+j.radius)*.42;if(d>0&&d<min){let f=(min-d)*.4,ux=dx/d,uy=dy/d;i.x+=ux*f;i.y+=uy*f;j.x-=ux*f;j.y-=uy*f}}}let k=gx+','+gy;if(!buckets.has(k))buckets.set(k,[]);buckets.get(k).push(i)}reveal();
 if(Math.hypot(p.x-240,p.y-78)<65&&cargo().length){if(!run.deposit)beginDeposit()}if(run.deposit>0){run.deposit-=dt;if(run.deposit<=0){launchDeposit()}}
 if(Math.hypot(p.x-oldx,p.y-oldy)>2&&run.boost>0&&Math.random()<.3)burst(p.x,p.y,1,'#f2d793');if(zoomed){view.x+=(p.x-view.x)*dt*4;view.y+=(p.y*.8-view.y)*dt*4}}
function hud(){if(!run||phase==='intro')return;let lvl=power(),capacity=cap(),load=mass(),next=LEVELS[lvl];$('#power').textContent='PULL '+lvl;$('#power-hint').textContent=['SMALL STUFF','CHAIRS & CRATES','CARS & MACHINES','THE BIG STUFF','EVERYTHING!'][lvl-1];$('#power-bar').style.width=next?clamp((run.xp-LEVELS[lvl-1].xp)/(next.xp-LEVELS[lvl-1].xp)*100,0,100)+'%':'100%';$('#cargo').textContent=load+' / '+capacity;$('#cargo-hint').textContent=load>=capacity*.9?'ALMOST FULL':'CARGO';$('#cargo-bar').style.width=clamp(load/capacity*100,0,100)+'%';$('#district').textContent=['TIN CAN TERRACE','CANDY CORNER','MOONBASE MESS'][theme()]+' · '+run.district;$('#clean').textContent=percent()+'%';$('#clean-bar').style.width=percent()+'%';$('#drop').disabled=!load||phase!=='play';$('#pulse').disabled=run.pulse>0||phase!=='play';$('#pulse-bar').style.width=(1-run.pulse/5)*100+'%';$('#toys').textContent=run.toys+' / 2';$('#next').classList.toggle('hidden',percent()<85||run.complete);$('#gus-title').textContent=percent()>=85?'A lovely little place.':load>=capacity*.8?'That is quite a haul!':run.items.some(i=>i.state==='delivery')?'Crunch. Munch. Thank you!':'Gus is hungry.';$('#gus-line').textContent=percent()>=85?'Finish every piece for a perfect bonus.':load?'Bring your haul to the green recycler.':'Gather small things. Grow your pull.';
 $('#hero-tip').textContent=run.banked===0?'Drag anywhere to guide your magnet':'Bring your cargo to Gus at the top';let nearest=run.items.filter(i=>i.state==='ground'&&i.rank>lvl).sort((a,b)=>Math.hypot(a.x-run.player.x,a.y-run.player.y)-Math.hypot(b.x-run.player.x,b.y-run.player.y))[0];$('#pickup-label').textContent=run.boost>0?'ϟ SUPER FIELD':load>=capacity*.9?'FULL HAUL · FEED GUS':nearest&&Math.hypot(nearest.x-run.player.x,nearest.y-run.player.y)<80?'PULL '+nearest.rank+' TO LIFT '+D[nearest.kind].n.toUpperCase():run.combo>=3?run.combo+' CLINGS!':''}
function finish(perfect=false){if(run.complete)return;run.complete=true;run.perfect=perfect;phase='result';input=null;keys.clear();if(!run.rewarded){meta.coins+=perfect?150:80;run.rewarded=true;meta.best=Math.max(meta.best,run.district)}save();sound('win');celebrate(perfect?'Clean sweep!':'Nice & tidy!',perfect?'PERFECT BLOCK · +150 COINS':'NEW NEIGHBOURHOOD AHEAD');burst(240,240,45,'#f2cc80');setTimeout(()=>{if(phase==='result')rewardScreen()},1000)}
function rewardScreen(){modal('<div class="eyebrow">'+(run.perfect?'PERFECT LITTLE CLEANUP':'A MUCH NICER NEIGHBOURHOOD')+'</div><h1>'+(run.perfect?'Clean sweep!':'Nice & tidy!')+'</h1><p>'+run.delivered+' things recycled · '+run.toys+' lost toys found<br>Choose a little upgrade for the next block.</p><div class="perk-row"><button class="perk" data-perk="field"><span>◎</span><b>Wide field</b><small>+12% pull range</small></button><button class="perk" data-perk="cargo"><span>▣</span><b>Big pockets</b><small>+15% cargo room</small></button><button class="perk" data-perk="speed"><span>ϟ</span><b>Quick zip</b><small>+10% movement</small></button></div><p style="font-size:9px;margin-bottom:0">NEW SCENE · NEW CLUTTER · NEW LITTLE SECRETS</p>');$$('[data-perk]').forEach(b=>b.onclick=()=>{let perks=clone(run.perks),k=b.dataset.perk;perks[k]=Math.min(6,perks[k]+1);start(run.district+1,perks)})}
function modalOpen(){return !$('#modal').classList.contains('hidden')}
function modal(html){input=null;keys.clear();$('#modal-card').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
function intro(){phase='intro';run=generate(1);modal('<div class="eyebrow">A SMALL MAGNET. A VERY BIG APPETITE.</div><h1>Magnet Munch</h1><canvas id="intro-art" width="580" height="380" aria-label="A friendly magnet and recycling robot"></canvas><div class="intro-steps"><div><span>∩</span>COLLECT</div><div><span>▣</span>DELIVER</div><div><span>ϟ</span>SUPER SIZE</div></div><button class="primary" id="start">Let it cling!</button><p style="font-size:9px;margin-bottom:0">NO TIMER · JUST ONE MORE LITTLE THING</p>');let c=$('#intro-art').getContext('2d');c.scale(2,2);A.gus(c,184,140,0,true,0);A.magnet(c,89,92,2,meta.skin,0);[{kind:'can',x:55,y:180,size:.9},{kind:'duck',x:102,y:190,size:.7},{kind:'gear',x:92,y:140,size:.85},{kind:'car',x:58,y:231,size:.66}].forEach(i=>A.object(c,{...i,radius:12,z:0},0));$('#start').onclick=()=>start();resize()}
function how(){modal('<div class="eyebrow">ONE HAND. A LOT OF LITTLE THINGS.</div><h2>Make room for lovely.</h2><div class="guide-row"><span>∩</span><div><b>Drag your magnet</b><small>Loose items roll in and cling automatically.<br>Heavier stuff needs a stronger pull.</small></div></div><div class="guide-row"><span>▣</span><div><b>Feed Gus</b><small>Move to the green recycler at the top.<br>Your cargo pours in and powers you up.</small></div></div><div class="guide-row"><span>ϟ</span><div><b>Go big</b><small>Super Pull widens the field. Drop makes room.<br>Find toys under clutter. Restore each block.</small></div></div><p>Mouse or touch to move. WASD / arrows also work.<br>Space: Super Pull · X: Drop · Esc: Menu</p><button class="primary" id="close">Let it cling</button>');$('#close').onclick=closeModal}
function menu(){modal('<div class="eyebrow">TAKE A LITTLE BREATHER</div><h2>Magnet Munch</h2><div class="menu-buttons"><button id="continue">Keep collecting</button><button id="how">How to play</button><button id="toy-book">Lost toys</button><button id="wardrobe">Magnet garage</button><button id="restart">Start a new run</button></div><p style="font-size:9px;margin-bottom:0">Your neighbourhood saves automatically.</p>');$('#continue').onclick=closeModal;$('#how').onclick=how;$('#toy-book').onclick=collection;$('#wardrobe').onclick=wardrobe;$('#restart').onclick=()=>{modal('<h2>A fresh start?</h2><p>Your coins, magnets and lost toys stay.<br>Your current neighbourhood will be replaced.</p><button class="primary" id="yes">New run</button> <button id="close">Keep this one</button>');$('#yes').onclick=intro;$('#close').onclick=closeModal}}
function collection(){modal('<div class="eyebrow">THINGS WORTH BRINGING HOME</div><h2>The lost toy shelf</h2><div class="collection-grid">'+TOYS.map((kind,n)=>'<div class="toy-stamp '+(meta.toys.includes(n)?'':'locked')+'"><canvas data-toy="'+n+'" width="140" height="120"></canvas><small>No. '+String(n+1).padStart(2,'0')+'</small></div>').join('')+'</div><p>'+meta.toys.length+' / 12 found<br>Move the big clutter. Find what is hiding beneath.</p><button class="primary" id="close">Back to the block</button>');$$('[data-toy]').forEach(el=>{let c=el.getContext('2d');c.scale(1.3,1.3);A.object(c,{kind:TOYS[+el.dataset.toy],x:52,y:90,z:0,size:.66,toy:true,radius:15},Math.floor(+el.dataset.toy/4))});$('#close').onclick=closeModal}
function wardrobe(){modal('<div class="eyebrow">A LITTLE COLOUR GOES A LONG WAY</div><h2>Magnet garage</h2><p>'+meta.coins+' coins</p><div class="skins">'+SKINS.map((s,n)=>'<button class="skin '+(n===meta.skin?'selected':'')+'" data-skin="'+n+'"><canvas width="200" height="160"></canvas><b>'+s.name+'</b><small>'+ (meta.skins.includes(n)?n===meta.skin?'Equipped':'Equip':s.cost+' coins')+'</small></button>').join('')+'</div><button class="primary" id="close">Back to collecting</button>');$$('[data-skin]').forEach(b=>{let n=+b.dataset.skin,c=b.querySelector('canvas').getContext('2d');c.scale(1.7,1.7);A.magnet(c,58,66,3,n,0);b.onclick=()=>{if(!meta.skins.includes(n)){if(meta.coins<SKINS[n].cost){toast('A few more lovely little hauls.');return}meta.coins-=SKINS[n].cost;meta.skins.push(n)}meta.skin=n;sound('level');save();wardrobe()}});$('#close').onclick=closeModal}
function screenToWorld(e){let b=canvas.getBoundingClientRect();return{x:clamp((e.clientX-b.left-W/2)/view.scale+view.x,8,472),y:clamp(((e.clientY-b.top-H/2)/view.scale+view.y)/.8,100,586)}}
canvas.onpointerdown=e=>{if(phase!=='play'||modalOpen())return;e.preventDefault();canvas.setPointerCapture(e.pointerId);input=e.pointerId;let p=screenToWorld(e);run.player.tx=p.x;run.player.ty=p.y;if(!audio)sound('tap')};canvas.onpointermove=e=>{if(input!==e.pointerId)return;let p=screenToWorld(e);run.player.tx=p.x;run.player.ty=p.y};canvas.onpointerup=e=>{if(input===e.pointerId)input=null};canvas.onpointercancel=()=>input=null;
$('#pulse').onclick=pulse;$('#drop').onclick=drop;$('#next').onclick=()=>finish(false);$('#sound').onclick=()=>{muted=!muted;$('#sound').textContent=muted?'♫̸':'♪';if(!muted)sound('tap')};$('#collection').onclick=collection;$('#menu').onclick=()=>phase==='result'?rewardScreen():menu;$('#fit').onclick=()=>{zoomed=false;resize()};$('#zoom').onclick=()=>{zoomed=!zoomed;resize()};
window.addEventListener('keydown',e=>{let k=e.key.toLowerCase();if(k==='escape'){if(modalOpen()&&phase==='play')closeModal();else if(phase==='play')menu();return}if(phase!=='play'||modalOpen())return;if(e.code==='Space'){e.preventDefault();pulse()}if(k==='x')drop();if(['arrowleft','arrowright','arrowup','arrowdown','w','a','s','d'].includes(k)){e.preventDefault();keys.add(k)}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{input=null;keys.clear()});document.addEventListener('visibilitychange',()=>{last=performance.now();acc=0;if(document.hidden)save()});
function resize(){let r=canvas.getBoundingClientRect();W=Math.max(1,r.width);H=Math.max(1,r.height);dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);view.scale=Math.min((W-28)/550,(H-32)/650)*(zoomed?1.7:1);view.x=zoomed&&run?run.player.x:240;view.y=zoomed&&run?run.player.y*.8:237}
new ResizeObserver(resize).observe($('#world-wrap'));
function backdrop(){let th=run?theme():0,g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,['#edead1','#eadacb','#c2d0d1'][th]);g.addColorStop(1,['#abcdbf','#c4bbce','#94a8bd'][th]);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);A.ell(ctx,W*.81,H*.18,30,30,['#fdf0c655','#f6dfa155','#f1e3d866'][th]);for(let k=0;k<4;k++){let x=(W*(.12+k*.24)+Math.sin(time*.025+k)*12)%(W+100),y=H*(.15+k%2*.4);A.ell(ctx,x,y,43,6,'#fff4d326')}if(th===2){for(let k=0;k<23;k++){let x=k*137%W,y=k*61%H;A.ell(ctx,x,y,1+(.5*Math.sin(time+k)),1,'#edf2dc77')}}else{for(let k=0;k<10;k++){let x=k*171%W,y=H*.6+k*43%(H*.38);A.line(ctx,[[x,y],[x+11,y],[x+14,y-.5]],'#eaf2d52c',1)}}}
function draw(){ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,W,H);backdrop();if(!run)return;ctx.save();ctx.translate(W/2,H/2);ctx.scale(view.scale,view.scale);ctx.translate(-view.x,-view.y);let th=theme(),clean=run.banked/run.total;A.scene(ctx,th,clean,time);A.gus(ctx,240,62,time,run.items.some(i=>i.state==='delivery'),th);A.ell(ctx,240,119,53,16,Math.sin(time*3)>0?'#d5e6ac44':'#d5e6ac33');ctx.save();ctx.fillStyle='#61887a';ctx.font='bold 8px system-ui';ctx.textAlign='center';ctx.fillText('FEED GUS HERE',240,135);ctx.restore();
 let p=run.player,lvl=power(),range=field();ctx.save();ctx.globalAlpha=run.boost>0?.2:.09;A.ell(ctx,p.x,p.y*.8,range,range*.8,run.boost>0?'#f7d17c':'#faf1b0');ctx.globalAlpha=.5;ctx.setLineDash([4,8]);ctx.beginPath();ctx.ellipse(p.x,p.y*.8,range,range*.8,0,0,A.TAU);ctx.strokeStyle=run.boost>0?'#f0c269':'#719c97';ctx.lineWidth=1.5;ctx.stroke();ctx.setLineDash([]);ctx.restore();
 let active=run.items.filter(i=>i.state!=='done'&&i.state!=='hidden').sort((a,b)=>a.y*.8-a.z-(b.y*.8-b.z));for(let i of active){A.object(ctx,i,th,time);if(i.toy&&i.state==='ground'){let angle=time*2+i.id;A.star(ctx,i.x+Math.cos(angle)*19,i.y*.8-29+Math.sin(angle)*3,3.5,'#f0cf75')}if(i.state==='ground'&&i.rank>lvl&&Math.hypot(i.x-p.x,i.y-p.y)<range+20){A.ell(ctx,i.x+12,i.y*.8-12,7,7,'#fbebc8');ctx.fillStyle='#87948a';ctx.textAlign='center';ctx.font='bold 8px system-ui';ctx.fillText(i.rank,i.x+12,i.y*.8-9)}}
 // Short field lines make the physical attraction legible.
 let pulling=active.filter(i=>i.state==='ground'&&i.rank<=lvl&&Math.hypot(i.x-p.x,i.y-p.y)<range);for(let i of pulling.slice(0,10)){ctx.globalAlpha=.22;A.line(ctx,[[i.x,i.y*.8-5],[(i.x+p.x)/2,(i.y+p.y)*.4-12],[p.x,p.y*.8-12]],'#f8e8a8',1);ctx.globalAlpha=1}
 A.ell(ctx,p.x,p.y*.8+8,25+(lvl-1)*2,9,'#4a776e33');A.magnet(ctx,p.x,p.y*.8-18+Math.sin(time*3)*1.5,lvl,meta.skin,time);
 if(mass()>=cap()*.65&&Math.hypot(p.x-240,p.y-78)>90){let dx=240-p.x,dy=62-p.y*.8,d=Math.hypot(dx,dy),x=p.x+dx/d*65,y=p.y*.8+dy/d*65;ctx.save();ctx.translate(x,y);ctx.rotate(Math.atan2(dy,dx));A.poly(ctx,[[10,0],[-5,-7],[-2,0],[-5,7]],'#f2d58c','#caac77',1);ctx.restore()}
 for(let r of rings){ctx.globalAlpha=r.life/r.max*.7;ctx.beginPath();ctx.ellipse(r.x,r.y*.8,r.r*(1-r.life/r.max*.4),r.r*.8*(1-r.life/r.max*.4),0,0,A.TAU);ctx.strokeStyle='#ffe1a0';ctx.lineWidth=3;ctx.stroke();ctx.globalAlpha=1}for(let s of sparks){ctx.globalAlpha=Math.min(1,s.life*2);A.ell(ctx,s.x,s.y,s.size,s.size,s.color)}ctx.globalAlpha=1;for(let f of floats){ctx.save();ctx.globalAlpha=Math.min(1,f.life*2);ctx.font='900 13px system-ui';ctx.textAlign='center';ctx.lineWidth=3;ctx.strokeStyle='#557b74bb';ctx.strokeText(f.text,f.x,f.y);ctx.fillStyle=f.color;ctx.fillText(f.text,f.x,f.y);ctx.restore()}ctx.restore();if(pulseFlash>0){ctx.fillStyle='#fff1c422';ctx.fillRect(0,0,W,H)}}
function cosmetic(dt){time+=dt;pulseFlash=Math.max(0,pulseFlash-dt);for(let s of sparks){s.x+=s.vx*dt;s.y+=s.vy*dt;s.vy+=55*dt;s.life-=dt}sparks=sparks.filter(s=>s.life>0);for(let r of rings)r.life-=dt;rings=rings.filter(r=>r.life>0);for(let f of floats){f.y-=18*dt;f.life-=dt}floats=floats.filter(f=>f.life>0)}
function frame(now){let dt=Math.min(.1,(now-last)/1000);last=now;if(!document.hidden){acc+=dt;while(acc>=.02){step(.02);cosmetic(.02);acc-=.02}if(now-drawAt>1000/(innerWidth<700?30:60)){drawAt=now;draw();if(coinsVis!==meta.coins){coinsVis+=Math.sign(meta.coins-coinsVis)*Math.max(1,Math.ceil(Math.abs(meta.coins-coinsVis)*.2));if(Math.abs(coinsVis-meta.coins)<2)coinsVis=meta.coins;$('#coins').textContent=coinsVis>=1000000?(coinsVis/1000000).toFixed(1)+'m':coinsVis>=10000?(coinsVis/1000).toFixed(1)+'k':coinsVis}}if(now-hudAt>120){hudAt=now;hud();let icon=$('#gus-icon').getContext('2d');icon.clearRect(0,0,120,120);icon.save();icon.translate(60,100);icon.scale(.8,.8);A.gus(icon,0,0,time,run?.items.some(i=>i.state==='delivery'),run?theme():0);icon.restore()}if(now-saveAt>4000&&phase==='play'){saveAt=now;save()}}requestAnimationFrame(frame)}requestAnimationFrame(frame);
let saved=get(SAVE,null);if(saved&&Array.isArray(saved.items)&&saved.items.length&&saved.items.every(i=>D[i.kind])&&saved.player&&saved.perks){run=saved;run.items.forEach(i=>{if(i.state==='delivery'){i.state='cargo';i.vx=i.vy=0}});run.deposit=0;phase=run.complete?'result':'play';resize();hud();if(run.complete)rewardScreen();else{modal('<div class="eyebrow">A LITTLE HAUL IS WAITING</div><h1>Welcome back</h1><p>Block '+run.district+' · '+percent()+'% recycled<br>Your magnet misses you.</p><button class="primary" id="resume">Keep collecting</button>');$('#resume').onclick=closeModal}}else intro();
window.__munch={get run(){return run},get phase(){return phase},get view(){return view},get dimensions(){return{W,H}},get meta(){return meta},power,cap,field,mass,step:seconds=>{for(let t=0;t<seconds&&phase==='play';t+=.02)step(.02)}};



