/* Original Snack Shuriken rules. Rendering-independent, fixed-step simulation. */
(function(root){
'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
const PERKS=[['twin','Twin Slice','Two blades. One throw.'],['ice','Cool Touch','Hits slow rivals.'],['bounce','Wall Bounce','Blades bounce off cover.'],['pulse','Dash Burst','Dash knocks nearby rivals.'],['wide','Big Slice','A wider blade.'],['heart','Fresh Heart','Restore all three hearts.']];
function arena(n){const k=(n-1)%3;return {name:['Sakura Court','Picnic Garden','Moon Market'][k],kind:k,blocks:k===0?[{x:0,z:0,w:2.4,d:1.4,type:'shrine'},{x:-3,z:-1.8,w:.9,d:.9,type:'crate'},{x:3,z:1.8,w:.9,d:.9,type:'crate'}]:k===1?[{x:-1.9,z:0,w:1.2,d:3,type:'hedge'},{x:1.9,z:0,w:1.2,d:3,type:'hedge'},{x:0,z:-3,w:1,d:1,type:'crate'}]:[{x:-2.2,z:-1.5,w:2,d:1,type:'stall'},{x:2.2,z:1.5,w:2,d:1,type:'stall'},{x:0,z:0,w:.9,d:.9,type:'crate'}]};}
class Game{
 constructor(seed=Date.now()){this.seed=seed>>>0;this.round=1;this.perks={};this.avatar=0;this.phase='ready';this.time=0;this.totalKills=0;this.nextId=1;this.events=[];this.loadRound();}
 rand(){this.seed=(1664525*this.seed+1013904223)>>>0;return this.seed/4294967296;}
 emit(type,x,z,extra={}){this.events.push({type,x,z,...extra});if(this.events.length>80)this.events.shift();}
 loadRound(){this.map=arena(this.round);this.blocks=this.map.blocks.map((b,i)=>({...b,id:i,broken:false}));this.booms=[];this.time=0;this.count=1.25;this.player={id:0,x:0,z:4.2,dx:0,dz:-1,hp:3,alive:true,inv:0,dash:0,cd:0,freeze:0,kind:this.avatar};const num=Math.min(5,2+Math.floor((this.round-1)/2));const sp=[[-3.8,-3.7],[3.8,-3.7],[-4,1.5],[4,1.5],[0,-4.8]];this.enemies=Array.from({length:num},(_,i)=>({id:i+1,x:sp[i][0],z:sp[i][1],dx:0,dz:1,hp:this.round>6&&i===0?2:1,alive:true,inv:0,dash:0,cd:0,freeze:0,kind:(i+1)%5,think:1.5+i*.75,warn:0,side:i%2?1:-1}));this.phase='ready';this.slow=0;this.events=[];}
 start(){this.phase='run';}
 blocked(x,z,r=.2){return this.blocks.find(b=>!b.broken&&Math.abs(x-b.x)<b.w/2+r&&Math.abs(z-b.z)<b.d/2+r);}
 clear(a,b){for(let t=.08;t<1;t+=.06)if(this.blocked(a.x+(b.x-a.x)*t,a.z+(b.z-a.z)*t,.14))return false;return true;}
 walk(a,vx,vz,dt){const ox=a.x,oz=a.z;a.x=clamp(ox+vx*dt,-5.15,5.15);if(this.blocked(a.x,oz,.38))a.x=ox;a.z=clamp(oz+vz*dt,-5.55,5.55);if(this.blocked(a.x,a.z,.38))a.z=oz;}
 aim(a){const rivals=a.id===0?this.enemies.filter(e=>e.alive):[this.player].filter(e=>e.alive);rivals.sort((x,y)=>dist(a,x)-dist(a,y));return rivals.find(e=>this.clear(a,e))||rivals[0];}
 throw(a=this.player){if(this.phase!=='run'||this.count>0||!a.alive)return false;const active=this.booms.filter(b=>b.owner===a.id);if(active.length){active.forEach(b=>b.returning=true);this.emit('recall',a.x,a.z);return true;}if(a.cd>0)return false;const t=this.aim(a);let dx=t?t.x-a.x:a.dx,dz=t?t.z-a.z:a.dz;let l=Math.hypot(dx,dz)||1;dx/=l;dz/=l;a.dx=dx;a.dz=dz;a.cd=.38;const twin=a.id===0&&this.perks.twin;for(let i=0;i<(twin?2:1);i++){const angle=twin?(i?1:-1)*.12:0,ux=dx*Math.cos(angle)-dz*Math.sin(angle),uz=dx*Math.sin(angle)+dz*Math.cos(angle);this.booms.push({id:this.nextId++,owner:a.id,x:a.x+ux*.5,z:a.z+uz*.5,vx:ux*10,vz:uz*10,age:0,travel:0,returning:false,hits:[],bounce:0});}this.emit('throw',a.x,a.z,{owner:a.id});return true;}
 dash(mx,mz){const p=this.player;if(this.phase!=='run'||this.count>0||p.cdDash>0||!p.alive)return false;let l=Math.hypot(mx,mz);if(l<.1){mx=p.dx;mz=p.dz;l=1;}p.dash=.22;p.inv=Math.max(p.inv,.32);p.cdDash=1.45;p.dashX=mx/l;p.dashZ=mz/l;this.emit('dash',p.x,p.z);if(this.perks.pulse)for(const e of this.enemies)if(e.alive&&dist(p,e)<2.25)this.hit(e,{owner:0,x:p.x,z:p.z},true);return true;}
 hit(a,b,pulse=false){if(!a.alive||a.inv>0)return false;if(a.id===0&&a.dash>0){b.owner=0;b.returning=false;b.hits=[];b.vx=-b.vx;b.vz=-b.vz;this.emit('parry',a.x,a.z);return false;}a.hp--;a.inv=a.id===0?1.5:.25;if(b.owner===0&&this.perks.ice)a.freeze=2.2;if(a.hp<=0){a.alive=false;this.emit('slice',a.x,a.z,{kind:a.kind,owner:b.owner});if(b.owner===0)this.totalKills++;}else this.emit('hit',a.x,a.z,{owner:b.owner});this.slow=.11;return true;}
 step(dt,input={}){if(this.phase!=='run')return;dt=Math.min(dt,.025);if(this.slow>0){this.slow-=dt;dt*=.32;}this.time+=dt;this.count=Math.max(0,this.count-dt);if(this.count>0)return;const p=this.player;for(const a of [p,...this.enemies]){a.inv=Math.max(0,a.inv-dt);a.cd=Math.max(0,a.cd-dt);a.freeze=Math.max(0,a.freeze-dt);a.cdDash=Math.max(0,(a.cdDash||0)-dt);a.dash=Math.max(0,a.dash-dt);}
 let mx=input.x||0,mz=input.z||0,l=Math.hypot(mx,mz);if(l>1){mx/=l;mz/=l;}if(p.alive){if(p.dash>0)this.walk(p,p.dashX*13,p.dashZ*13,dt);else this.walk(p,mx*4.6,mz*4.6,dt);if(l>.15){p.dx=mx/Math.max(1,l);p.dz=mz/Math.max(1,l);}}
 for(const e of this.enemies){if(!e.alive)continue;let dx=p.x-e.x,dz=p.z-e.z,d=Math.hypot(dx,dz)||1,forward=d>4?1:d<2.7?-.7:.05;let vx=(dx/d*forward-dz/d*e.side*.65),vz=(dz/d*forward+dx/d*e.side*.65);const old={x:e.x,z:e.z};this.walk(e,vx*(e.freeze>0?.7:1.7),vz*(e.freeze>0?.7:1.7),dt);if(dist(old,e)<.003){e.side*=-1;this.walk(e,-dz/d*e.side*1.8,dx/d*e.side*1.8,dt);}e.think-=dt;if(e.warn>0){e.warn-=dt;if(e.warn<=0){this.throw(e);e.think=Math.max(1.45,3.25-this.round*.12)+this.rand();}}else if(e.think<=0&&p.alive&&this.clear(e,p)){e.warn=.65;this.emit('warn',e.x,e.z);} }
 for(const b of this.booms){b.age+=dt;const owner=b.owner===0?p:this.enemies.find(e=>e.id===b.owner);if(b.age>.65||b.travel>7)b.returning=true;if(b.returning){const dx=owner.x-b.x,dz=owner.z-b.z,d=Math.hypot(dx,dz)||1;if(d<.45){b.dead=true;this.emit('catch',owner.x,owner.z,{owner:b.owner});continue;}b.vx=dx/d*12;b.vz=dz/d*12;}
 const nx=b.x+b.vx*dt,nz=b.z+b.vz*dt,block=this.blocked(nx,nz,.12);if(block&&!b.returning){if(block.type==='crate'){block.broken=true;this.emit('crate',block.x,block.z);}if(b.owner===0&&this.perks.bounce&&b.bounce<3){const ox=Math.abs(b.x-block.x)>block.w/2;b[ox?'vx':'vz']*=-1;b.bounce++;this.emit('bounce',b.x,b.z);}else b.returning=true;}else {b.x=nx;b.z=nz;}b.travel+=Math.hypot(b.vx,b.vz)*dt;if(Math.abs(b.x)>5.5||Math.abs(b.z)>5.9)b.returning=true;
 const victims=b.owner===0?this.enemies:[p,...this.enemies.filter(e=>e.id!==b.owner)];for(const a of victims){if(a.id===b.owner||b.hits.includes(a.id)||!a.alive)continue;const rad=b.owner===0&&this.perks.wide?.87:.58;if(dist(a,b)<rad){if(a.id===0&&a.dash>0){b.owner=0;b.returning=false;b.age=0;b.hits=[];b.vx=-b.vx;b.vz=-b.vz;this.emit('parry',p.x,p.z);}else if(this.hit(a,b)){b.hits.push(a.id);}}}if(b.age>4)b.dead=true;}
 this.booms=this.booms.filter(b=>!b.dead);if(!p.alive){this.phase='lose';this.emit('lose',p.x,p.z);}else if(this.enemies.every(e=>!e.alive)){this.phase='win';this.emit('win',p.x,p.z);}}
 choose(key){if(this.phase!=='win'||!PERKS.some(p=>p[0]===key))return false;if(key!=='heart')this.perks[key]=true;this.round++;const hp=key==='heart'?3:Math.min(3,this.player.hp+1);this.loadRound();this.player.hp=hp;this.start();return true;}
 choices(){const pool=PERKS.filter(p=>p[0]==='heart'||!this.perks[p[0]]);if(pool.length<=2)return pool;const a=Math.floor(this.rand()*pool.length);const one=pool.splice(a,1)[0];return [one,pool[Math.floor(this.rand()*pool.length)]];}
 snapshot(){return JSON.parse(JSON.stringify({seed:this.seed,round:this.round,perks:this.perks,avatar:this.avatar,phase:this.phase,time:this.time,totalKills:this.totalKills,nextId:this.nextId,blocks:this.blocks,booms:this.booms,player:this.player,enemies:this.enemies,count:this.count,slow:this.slow,map:this.map}));}
 static restore(s){if(!s||!Number.isInteger(s.round)||s.round<1||s.round>10000||!Array.isArray(s.enemies))throw Error('Invalid save');const g=new Game(s.seed);Object.assign(g,s);g.events=[];return g;}
}
const API={Game,PERKS,arena};if(typeof module!=='undefined')module.exports=API;root.SS=API;
})(typeof window!=='undefined'?window:globalThis);
