'use strict';
(()=>{
const $=id=>document.getElementById(id), paper=$('paper'), canvas=$('stage'), art=new StoryArt(canvas), KEY='once-upon-v1';
let profile={best:Array(12).fill(0),unlocked:1,skin:0,discoveries:[],mute:false},story=new Story(),selected=-1,held=null,clue=null,erase=false,modal='',hidden=document.hidden,wonDelay=0,toastTime=0,last=performance.now(),acc=0,render=0,saveTime=0,audio=null,voices=0;
const total=()=>profile.best.reduce((a,b)=>a+b,0), skins=['Rose ink','Forest ink','Twilight ink'], colors=['#885454','#526e60','#6b6084'];
try{let o=JSON.parse(localStorage.getItem(KEY));if(o&&o.version===1){let p=o.profile,g=Story.restore(o.story);if(p&&Array.isArray(p.best)&&p.best.length===12&&p.best.every(n=>Number.isInteger(n)&&n>=0&&n<=3)&&Number.isInteger(p.unlocked)&&p.unlocked>=1&&p.unlocked<=12&&Number.isInteger(p.skin)&&p.skin>=0&&p.skin<3&&Array.isArray(p.discoveries)&&p.discoveries.length<=20&&p.discoveries.every(s=>['flower','love','key','cake','curse','cure','revive','crown','birthday','croak','royal','song'].includes(s))&&g&&g.n<=p.unlocked){profile={...p,mute:!!p.mute};story=g;}}}catch{}
function save(){try{localStorage.setItem(KEY,JSON.stringify({version:1,profile,story:story.snapshot()}));}catch{}}
function wake(){try{if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(!profile.mute&&!hidden)audio.resume().catch(()=>{});}catch{}}
function tone(type){if(profile.mute||hidden||modal==='pause'||!audio||audio.state!=='running'||voices>12)return;let notes=type==='won'?[523,659,784,1047]:type==='scene'?[392,494]:[270];for(let i=0;i<notes.length;i++){let o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+i*.11;o.type=type==='place'?'triangle':'sine';o.frequency.setValueAtTime(notes[i],t);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.09,t+.015);g.gain.exponentialRampToValueAtTime(.001,t+.24);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.26);voices++;o.onended=()=>{voices--;o.disconnect();g.disconnect();};}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');toastTime=2.8;}
function finish(){let old=profile.best[story.n-1];profile.best[story.n-1]=Math.max(old,story.stars);profile.unlocked=Math.max(profile.unlocked,Math.min(12,story.n+1));save();}
function events(){for(let e of story.events.splice(0)){if(e.type==='place'){art.event(e);tone('place');}if(e.type==='missing')toast('Add two characters to every frame');if(e.type==='scene'){art.event(e);tone('scene');let p=story.result.panels[e.panel];toast(p.text);if(!['quiet','hungry','locked'].includes(p.event)&&!profile.discoveries.includes(p.event))profile.discoveries.push(p.event);}if(e.type==='different'){toast('A different ending. Change the cast and try again.');}if(e.type==='won'){finish();tone('won');wonDelay=.8;}}sync();}
function sync(){ $('chapter').textContent='CHAPTER '+story.n+' / 12';$('help').textContent=story.n===1&&story.reads===0?'Milo + Ruby → birthday':story.chapter.name;$('read').disabled=story.phase!=='edit';$('undo').disabled=story.phase!=='edit'||!story.history.length;$('hint').disabled=story.phase!=='edit';$('erase').disabled=story.phase!=='edit';$('erase').setAttribute('aria-pressed',String(erase));$('sound').setAttribute('aria-pressed',String(!profile.mute));$('sound').textContent=profile.mute?'♫̸':'♪';
for(let p=0;p<4;p++)for(let s=0;s<2;s++){let b=$('slot-'+p+'-'+s),id=story.frames[p][s];if(b){b.setAttribute('aria-label',`Frame ${p+1}, ${PLACES[story.chapter.places[p]]}, ${s?'right':'left'}: ${id<0?'empty':CAST[id].name}`);b.disabled=story.phase!=='edit';}}for(let i=0;i<6;i++)$('cast-'+i)?.setAttribute('aria-pressed',String(selected===i));paper.dataset.state=JSON.stringify({chapter:story.n,phase:story.phase,time:Math.round(story.time*100)/100,frames:story.frames,stars:story.stars,best:profile.best,unlocked:profile.unlocked,selected,held:!!held,modal,discoveries:profile.discoveries.length,hints:story.hints,audio:audio?.state||'off'});}
function choose(id){if(story.phase!=='edit'||modal)return;wake();selected=id;erase=false;sync();}
function slot(p,s){if(story.phase!=='edit'||modal)return;wake();if(erase){story.remove(p,s);tone('place');}else if(selected>=0){story.place(selected,p,s);clue=null;}else if(story.frames[p][s]>=0){selected=story.frames[p][s];}events();save();}
function layout(){art.resize();$('hitboxes').innerHTML='';function hit(id,label,x,y,w,h,fn){let b=document.createElement('button');b.id=id;b.className='hit';b.setAttribute('aria-label',label);b.style.left=art.ox+x*art.s+'px';b.style.top=art.oy+y*art.s+'px';b.style.width=w*art.s+'px';b.style.height=h*art.s+'px';b.addEventListener('click',e=>{if(!held||!held.moved)fn();});$('hitboxes').appendChild(b);}art.slots.forEach(q=>{let r=art.cards[q.p];hit(`slot-${q.p}-${q.side}`,'Story role',r.x+r.w*.5*q.side,r.y+40,r.w*.5,r.h-40,()=>slot(q.p,q.side));});art.cast.forEach((q,i)=>hit('cast-'+i,'Cast '+CAST[i].name,q.x-76,q.y-72,152,art.wide?127:116,()=>choose(i)));sync();}
function atSlot(pt){return art.slots.find(q=>{let r=art.cards[q.p];return pt.x>=r.x+r.w*.5*q.side&&pt.x<r.x+r.w*.5*(q.side+1)&&pt.y>=r.y+40&&pt.y<=r.y+r.h;});}
paper.addEventListener('pointerdown',e=>{if(modal||story.phase!=='edit'||e.button!==0||held)return;let pt=art.point(e),el=e.target.closest('.hit'),id=el?.id,actor=-1;if(id?.startsWith('cast-'))actor=Number(id.split('-')[1]);else if(id?.startsWith('slot-')&&selected<0&&!erase){let q=atSlot(pt);if(q)actor=story.frames[q.p][q.side];}if(actor>=0){held={actor,x:pt.x,y:pt.y,startX:pt.x,startY:pt.y,moved:false,pointer:e.pointerId};paper.setPointerCapture(e.pointerId);wake();} });
paper.addEventListener('pointermove',e=>{if(!held||e.pointerId!==held.pointer)return;let p=art.point(e);held.x=p.x;held.y=p.y;if(Math.hypot(p.x-held.startX,p.y-held.startY)>14)held.moved=true;});
paper.addEventListener('pointerup',e=>{if(!held||e.pointerId!==held.pointer)return;let h=held;held=null;if(h.moved){let q=atSlot(art.point(e));if(q){selected=h.actor;slot(q.p,q.side);}else{selected=h.actor;sync();}}else{choose(h.actor);}if(paper.hasPointerCapture(e.pointerId))paper.releasePointerCapture(e.pointerId);if(h.moved){suppressClick=true;setTimeout(()=>suppressClick=false,0);}sync();});
let suppressClick=false;paper.addEventListener('click',e=>{if(suppressClick){e.preventDefault();e.stopImmediatePropagation();}},true);paper.addEventListener('pointercancel',release);paper.addEventListener('lostpointercapture',()=>{held=null;sync();});
function release(){if(held&&paper.hasPointerCapture(held.pointer))paper.releasePointerCapture(held.pointer);held=null;sync();}
function show(kind,html){release();modal=kind;$('panel').innerHTML=html;$('overlay').hidden=false;paper.inert=true;document.querySelector('footer').inert=true;document.querySelector('header').inert=true;sync();$('panel').querySelector('button')?.focus();art.draw(story,profile.skin,selected,held,clue,erase);}
function close(){if(modal==='pause')wake();modal='';$('overlay').hidden=true;paper.inert=false;document.querySelector('footer').inert=false;document.querySelector('header').inert=false;last=performance.now();sync();$('read').focus();}
function button(id,text,cls=''){return `<button id="${id}" class="${cls}">${text}</button>`;}
function welcome(){show('intro',`<div class="eyebrow">AN ILLUSTRATED STORY PUZZLE</div><h1>Once Upon</h1><div class="seal">✧</div><p>Cast the characters.<br>Watch the tale change.</p><div class="row">${button('begin','Open the book','primary')}${button('rules','How to play')}</div>`);}
function rules(){show('rules',`<div class="eyebrow">LITTLE CAUSES · LOVELY EFFECTS</div><h2>Tell it your way</h2><p>Tap a character, then a role. Or drag.<br>Read the four frames from left to right.</p><div class="rules"><div><b>Garden</b> Every friend gets a flower.</div><div><b>Pond</b> Pip finds keys for both friends.</div><div><b>Bakery</b> Milo gives a friend a cake.</div><div><b>Witch hut</b> Willow + flower → a new life.<br>Without a flower → ribbit!</div><div><b>Castle</b> A key + Ruby or Hugo → a crown.</div><div><b>Theatre</b> Milo + friend → a dance.<br>Add cake → a birthday!</div></div><div class="row">${button('back','Back','primary')}</div>`);}
function book(){let names={flower:'A flower for a friend',love:'Love blooms',key:'Golden keys',cake:'A little cake',curse:'Ribbit!',cure:'A prince at last',revive:'A second life',crown:'A new monarch',birthday:'Make a wish',croak:'Ribbit recital',royal:'Royal encore',song:'A lovely duet'};show('book',`<div class="eyebrow">${total()} / 36 STARS · ${profile.discoveries.length} REACTIONS</div><h2>Your storybook</h2><div class="chapters">${CHAPTERS.map((ch,i)=>`<button data-ch="${i+1}" ${i+1>profile.unlocked?'disabled':''}>${i+1}. ${ch.name}<small>${profile.best[i]?'★'.repeat(profile.best[i]):i+1>profile.unlocked?'Locked':'Unwritten'}</small></button>`).join('')}</div><div class="row swatches">${skins.map((s,i)=>`<button data-skin="${i}" ${total()<[0,6,18][i]?'disabled':''}><i style="background:${colors[i]}"></i>${total()<[0,6,18][i]?[0,6,18][i]+' ★':s}${profile.skin===i?' ✓':''}</button>`).join('')}</div><details><summary>Little discoveries</summary><p>${profile.discoveries.map(e=>names[e]).join(' · ')||'Every tale begins somewhere.'}</p></details><p>★ An ending · ★ No clues · ★ Four lively frames</p><div class="row">${button('back','Back','primary')}${button('rules','Story guide')}${button('picture','Save page')}</div>`);}
function won(){show('won',`<div class="eyebrow">CHAPTER ${story.n} · THE END</div><h2>${story.chapter.name}</h2><div class="stars">${'★'.repeat(story.stars)}${'☆'.repeat(3-story.stars)}</div><p>${story.n===12?'Twelve tales, a book full of little miracles.':'Another little tale for your collection.'}</p><div class="row">${button('next',story.n===12?'Storybook':'Next chapter','primary')}${button('rewrite','Rewrite')}${button('picture','Save page')}</div><p>${total()} / 36 stars · Ink colors unlock at 6 and 18</p>`);}
function start(n){$('toast').classList.remove('show');toastTime=0;story=new Story(n);selected=-1;erase=false;clue=null;wonDelay=0;art.fx=[];close();save();}
function pause(){if(modal)return;show('pause',`<div class="eyebrow">A BOOKMARK, JUST HERE</div><h2>Take your time</h2><div class="row">${button('resume','Continue','primary')}${button('book-modal','Storybook')}${button('rules','Story guide')}</div>`);audio?.suspend().then(sync).catch(()=>{});save();}
$('panel').addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;wake();if(b.dataset.ch){let n=Number(b.dataset.ch);if(n!==story.n&&story.history.length){show('confirm',`<h2>Turn the page?</h2><p>Your stars stay safe. This draft will be replaced.</p><div class="row">${button('ch-'+n,'Turn page','primary')}${button('book-modal','Keep draft')}</div>`);}else start(n);return;}if(b.dataset.skin){profile.skin=Number(b.dataset.skin);save();book();return;}let id=b.id;if(id==='begin'||id==='resume'||id==='back'){close();if(story.phase==='won')wonDelay=.6;}if(id==='rules')rules();if(id==='book-modal')book();if(id==='next'){if(story.n===12)book();else start(story.n+1);}if(id==='rewrite')start(story.n);if(id.startsWith('ch-'))start(Number(id.slice(3)));if(id==='picture'){let a=document.createElement('a');a.download=`once-upon-chapter-${story.n}.png`;a.href=canvas.toDataURL('image/png');a.click();toast('Your illustrated page is ready');}});
$('book').onclick=()=>book();$('pause').onclick=()=>pause();$('sound').onclick=()=>{profile.mute=!profile.mute;if(profile.mute)audio?.suspend().then(sync).catch(()=>{});else wake();sync();save();};$('undo').onclick=()=>{if(story.undo()){clue=null;tone('place');sync();save();}};$('erase').onclick=()=>{erase=!erase;selected=-1;sync();toast(erase?'Tap a role to remove it':'Choose a character');};$('hint').onclick=()=>{clue=story.hint();toast(clue?story.chapter.hint:'The cast is ready. Read your tale.');sync();save();};$('read').onclick=()=>{wake();selected=-1;erase=false;clue=null;story.read();events();save();};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();if(modal)close();else pause();return;}if(modal){if(e.key==='Tab'){let a=Array.from($('panel').querySelectorAll('button:not(:disabled),summary'));let first=a[0],end=a[a.length-1];if(e.shiftKey&&document.activeElement===first){end?.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===end){first?.focus();e.preventDefault();}}return;}if(/^[1-6]$/.test(e.key))choose(Number(e.key)-1);if(e.key.toLowerCase()==='z')$('undo').click();if(e.key.toLowerCase()==='h')$('hint').click();});
window.addEventListener('blur',()=>{release();hidden=true;audio?.suspend().then(sync).catch(()=>{});save();});window.addEventListener('focus',()=>{hidden=document.hidden;last=performance.now();if(!hidden&&!profile.mute&&modal!=='pause')wake();});document.addEventListener('visibilitychange',()=>{hidden=document.hidden;release();last=performance.now();if(hidden){audio?.suspend().then(sync).catch(()=>{});save();}else if(!profile.mute&&modal!=='pause')wake();});window.addEventListener('pagehide',save);new ResizeObserver(()=>{release();layout();art.draw(story,profile.skin,selected,held,clue,erase);}).observe(paper);
function loop(now){let dt=Math.min(.05,(now-last)/1000);last=now;if(!hidden&&!modal){acc+=dt;while(acc>=1/60){story.update(1/60);art.update(1/60);acc-=1/60;}if(story.events.length)events();if(wonDelay>0){wonDelay-=dt;if(wonDelay<=0)won();}if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('toast').classList.remove('show');}saveTime+=dt;if(saveTime>1){saveTime=0;save();}sync();}render+=dt;if(render>=1/40&&!hidden&&!modal){render=0;art.draw(story,profile.skin,selected,held,clue,erase);}requestAnimationFrame(loop);}
layout();$('overlay').hidden=true;if(story.phase==='won')won();else if(story.n===1&&story.reads===0&&story.history.length===0)welcome();requestAnimationFrame(loop);
})();
