(function(root){'use strict';
const copy=x=>JSON.parse(JSON.stringify(x));
const toys=[{name:'Paper boat',mass:.7,r:19,time:3.1,color:'#dfcf9b'},{name:'Corn',mass:.9,r:17,time:3.8,color:'#e3b556'},{name:'Robot',mass:1.7,r:21,time:5.2,color:'#91b4a8'},{name:'Moon',mass:.8,r:19,time:3.5,color:'#e8dc9e'},{name:'Rocket',mass:1.1,r:18,time:4.3,color:'#cd8c73'},{name:'Flower',mass:.6,r:18,time:3.6,color:'#c69ba8'},{name:'Teacup',mass:1.4,r:19,time:5,color:'#c0c5d0'},{name:'Music box',mass:1.5,r:22,time:4.9,color:'#bb9d76'}];
const recipes=[{name:'Movie night',pair:[1,2],color:'#e5c578'},{name:'Moon mail',pair:[0,3],color:'#9fbed1'},{name:'Star garden',pair:[4,5],color:'#d59fb5'},{name:'Tea for two',pair:[6,7],color:'#b5b1d4'},{name:'Space pop',pair:[1,4],color:'#e8b57b'},{name:'Tin lullaby',pair:[2,7],color:'#99c6b6'},{name:'Moonflower',pair:[3,5],color:'#e6cea0'},{name:'Sailing tea',pair:[0,6],color:'#a8c9c0'},{name:'Tin garden',pair:[2,5],color:'#b6c294'},{name:'Night music',pair:[3,7],color:'#b2b3ce'},{name:'Cornflower',pair:[1,5],color:'#e9c58b'},{name:'Rocket mail',pair:[0,4],color:'#d9aa8e'}];
const orders=[[0,1],[2,3],[4,5],[6,7],[8,9],[10,11],[0,6,3],[1,8,4]];
class Hearth{
 constructor(n=1){this.n=Math.max(1,Math.min(9999,n|0));this.time=0;this.state='play';this.items=[];this.nextId=1;this.events=[];this.found=[];this.ignited=[];this.drops=0;this.chain=0;this.bestChain=0;this.chainTimer=0;this.flame=0;this.sparks=0;this.reward=0;this.requests=[...orders[(this.n-1)%8]];this.goal=this.requests.length;this.par=this.goal*2+3;this.parTime=45+this.goal*15;this.stars=0;this.ash=[];this.wonAt=0;this.finishAt=0;}
 spawn(kind,x=180,y=90){if(this.state!=='play'||this.finishAt||!Number.isInteger(kind)||kind<0||kind>7||this.items.length>=16)return null;const spec=toys[kind],item={id:this.nextId++,kind,x:Math.max(28,Math.min(332,x)),y:Math.max(40,Math.min(276,y)),vx:0,vy:0,angle:0,spin:0,r:spec.r,heat:0,burn:0,age:0,burning:false,held:false,popped:false};this.items.push(item);this.drops++;this.emit('drop',item);return item;}
 grab(id){const t=this.items.find(t=>t.id===id);if(this.state!=='play'||!t)return false;t.held=true;t.vx=t.vy=0;return true;}
 move(id,x,y){const t=this.items.find(t=>t.id===id);if(!t||!t.held)return;t.x=Math.max(24,Math.min(336,x));t.y=Math.max(30,Math.min(282,y));t.vx=t.vy=0;}
 release(id,vx=0,vy=0){const t=this.items.find(t=>t.id===id);if(!t)return;t.held=false;t.vx=Math.max(-360,Math.min(360,vx));t.vy=Math.max(-260,Math.min(260,vy));}
 cancel(){for(const t of this.items){t.held=false;t.vx=t.vy=0;}}
 ignite(x=180,y=267){if(this.state!=='play')return false;this.flame=1.2;let hit=0;for(const t of this.items)if(Math.hypot(t.x-x,t.y-y)<95&&!t.burning){this.light(t);hit++;}this.emit('spark',{x,y,kind:-1});return hit>0;}
 light(t){if(t.burning)return;t.burning=true;t.heat=1;this.ignited.push({kind:t.kind,time:this.time,id:t.id});this.ignited=this.ignited.filter(e=>this.time-e.time<4).slice(-24);this.emit('ignite',t);for(let i=0;i<recipes.length;i++){if(this.found.includes(i))continue;const pair=recipes[i].pair;const a=[...this.ignited].reverse().find(e=>e.kind===pair[0]),b=[...this.ignited].reverse().find(e=>e.kind===pair[1]);if(a&&b&&a.id!==b.id&&Math.abs(a.time-b.time)<=3.5){this.found.push(i);this.chain=this.chainTimer>0?this.chain+1:1;this.chainTimer=5;this.bestChain=Math.max(this.bestChain,this.chain);this.emit('combo',{...t,recipe:i});}}}
 emit(type,t){this.events.push({type,x:t.x??180,y:t.y??180,kind:t.kind??-1,recipe:t.recipe??-1});if(this.events.length>80)this.events.shift();}
 update(dt){if(this.state!=='play'||!Number.isFinite(dt)||dt<=0)return;dt=Math.min(dt,.04);this.time+=dt;this.flame=Math.max(0,this.flame-dt);this.chainTimer=Math.max(0,this.chainTimer-dt);if(!this.chainTimer)this.chain=0;this.ignited=this.ignited.filter(e=>this.time-e.time<4);
 for(const t of this.items){t.age+=dt;if(!t.held){t.vy+=520*dt;t.x+=t.vx*dt;t.y+=t.vy*dt;t.angle+=t.spin*dt;t.spin*=Math.pow(.35,dt);t.vx*=Math.pow(.75,dt);if(t.y<t.r+12){t.y=t.r+12;t.vy=Math.abs(t.vy)*.3;}if(t.x<t.r+10){t.x=t.r+10;t.vx=Math.abs(t.vx)*.35;}if(t.x>350-t.r){t.x=350-t.r;t.vx=-Math.abs(t.vx)*.35;}if(t.y>297-t.r){t.y=297-t.r;if(Math.abs(t.vy)>45){this.emit('thud',t);t.spin=t.vx*.025;}t.vy=-Math.abs(t.vy)*.24;if(Math.abs(t.vy)<30)t.vy=0;t.vx*=Math.pow(.05,dt);}}
  if(!t.burning){let hot=0;for(const b of this.items)if(b!==t&&b.burning&&Math.hypot(t.x-b.x,t.y-b.y)<t.r+b.r+24)hot+=1.3; if(this.flame&&t.y>220)hot+=2;t.heat=Math.max(0,t.heat+(hot-.08)*dt);if(t.heat>=1)this.light(t);}else{t.burn+=dt/toys[t.kind].time;if(!t.popped&&t.burn>.42){t.popped=true;this.sparks++;this.emit('pop',t);if(t.kind===4){t.vy=-290;t.vx=(t.x<180?1:-1)*45;for(const a of this.items)if(a!==t&&Math.hypot(t.x-a.x,t.y-a.y)<100){a.vx+=(a.x-t.x)*2;a.vy-=120;if(!a.burning)this.light(a);}}if(t.kind===2){for(const a of this.items)if(a!==t&&Math.hypot(t.x-a.x,t.y-a.y)<65){a.vy-=100;a.vx+=(a.x-t.x)*2;}}}if(t.burn>=1){this.reward++;this.emit('ash',t);this.ash.push({x:t.x,y:291,r:8+t.r*.2,kind:t.kind});if(this.ash.length>24)this.ash.shift();}}
 }
 // Mass-weighted discs: softly stack, bounce, and separate without frame-rate-dependent explosions.
 for(let k=0;k<3;k++)for(let i=0;i<this.items.length;i++)for(let j=i+1;j<this.items.length;j++){const a=this.items[i],b=this.items[j];if(a.held||b.held||a.burn>=1||b.burn>=1)continue;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=a.r+b.r-4;if(d>=min)continue;if(d<.001){dx=.01;dy=-.01;d=Math.hypot(dx,dy);}const nx=dx/d,ny=dy/d,p=(min-d)*.52,ia=1/toys[a.kind].mass,ib=1/toys[b.kind].mass,sum=ia+ib;a.x-=nx*p*ia/sum;a.y-=ny*p*ia/sum;b.x+=nx*p*ib/sum;b.y+=ny*p*ib/sum;const rv=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(rv<0){const impulse=-rv*.6/sum;a.vx-=impulse*nx*ia;a.vy-=impulse*ny*ia;b.vx+=impulse*nx*ib;b.vy+=impulse*ny*ib;}}
 for(const t of this.items)if(!t.held){t.x=Math.max(t.r+10,Math.min(350-t.r,t.x));t.y=Math.max(t.r+12,Math.min(297-t.r,t.y));}this.items=this.items.filter(t=>t.burn<1);if(this.requests.every(i=>this.found.includes(i))&&!this.finishAt)this.finishAt=this.time+3.3;if(this.finishAt&&this.time>=this.finishAt){this.state='won';this.stars=1+(this.drops<=this.par?1:0)+(this.bestChain>=this.goal?1:0);this.wonAt=this.time;this.emit('win',{x:180,y:145});}}
 snapshot(){const s=copy(this);s.events=[];return s;}
 static restore(s){if(!s||!Number.isInteger(s.n)||s.n<1||s.n>9999||!['play','won'].includes(s.state)||!Array.isArray(s.items)||s.items.length>16||!Number.isFinite(s.time)||s.time<0)return null;const g=new Hearth(s.n),finite=x=>Number.isFinite(x)&&Math.abs(x)<1000000;for(const k of ['nextId','drops','bestChain','sparks','reward','chain','chainTimer','flame','finishAt'])if(!finite(s[k])||s[k]<0)return null;const ids=new Set();for(const t of s.items){if(!t||!Number.isInteger(t.id)||ids.has(t.id)||!Number.isInteger(t.kind)||t.kind<0||t.kind>7||!['x','y','vx','vy','angle','spin','heat','burn','age'].every(k=>finite(t[k]))||t.burn<0||t.burn>=1||t.x<0||t.x>360||t.y<0||t.y>340)return null;ids.add(t.id);}if(!Array.isArray(s.found)||s.found.some(x=>!Number.isInteger(x)||x<0||x>=12)||new Set(s.found).size!==s.found.length||!Array.isArray(s.ignited)||s.ignited.length>24||s.ignited.some(e=>!e||!Number.isInteger(e.kind)||e.kind<0||e.kind>7||!finite(e.time)||!finite(e.id))||!Array.isArray(s.ash)||s.ash.length>24||s.ash.some(a=>!a||!finite(a.x)||!finite(a.y)||!finite(a.r)||!Number.isInteger(a.kind)||a.kind<0||a.kind>7))return null;for(const k of ['time','state','nextId','drops','bestChain','sparks','reward','chain','chainTimer','flame','found','ignited','ash','finishAt'])g[k]=copy(s[k]);g.items=s.items.map(t=>({...copy(t),r:toys[t.kind].r,held:false}));g.stars=g.state==='won'?1+(g.drops<=g.par?1:0)+(g.bestChain>=g.goal?1:0):0;if(g.state==='won'&&!g.requests.every(i=>g.found.includes(i)))return null;g.events=[];return g;}
}
root.Hearth=Hearth;root.TOYS=toys;root.RECIPES=recipes;if(typeof module!=='undefined')module.exports={Hearth,toys,recipes,orders};
})(typeof window==='undefined'?globalThis:window);
