'use strict';const $=id=>document.getElementById(id),KEY='hug-the-sky-v1';let profile={stars:Array(8).fill(0),records:Array(8).fill(0),skin:0,sound:true,save:null},game,paused=true,pointer=null,menu='intro',acc=0,saveTime=0,toast=0,fx=[],view={w:390,h:700,s:.78,cam:900},ctxAudio,voices=0;const oscs=new Set(),threshold=[0,6,15];
try{const d=JSON.parse(localStorage.getItem(KEY));if(d&&Array.isArray(d.stars)&&d.stars.length===8&&d.stars.every(v=>Number.isInteger(v)&&v>=0&&v<=3)){profile={...profile,...d};profile.records=Array.from({length:8},(_,i)=>Number.isFinite(d.records?.[i])?Math.max(0,d.records[i]):0);profile.skin=[0,1,2].includes(d.skin)?d.skin:0;profile.sound=d.sound!==false;}}catch{}
const total=()=>profile.stars.reduce((a,b)=>a+b,0);if(total()<threshold[profile.skin])profile.skin=0;game=Hug.Run.restore(profile.save)||new Hug.Run(0);window.game=game;
function save(){profile.save=game.snapshot();try{localStorage.setItem(KEY,JSON.stringify(profile));}catch{}}
function audio(){if(!profile.sound)return;try{ctxAudio??=new(window.AudioContext||window.webkitAudioContext)();if(ctxAudio.state!=='running')ctxAudio.resume();}catch{}}
function note(f,d=.14,delay=0,type='sine',vol=.035,end){if(!profile.sound||!ctxAudio||ctxAudio.state!=='running'||voices>=14)return;const o=ctxAudio.createOscillator(),gain=ctxAudio.createGain(),t=ctxAudio.currentTime+delay;o.type=type;o.frequency.setValueAtTime(f,t);if(end)o.frequency.exponentialRampToValueAtTime(end,t+d);gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(vol,t+.008);gain.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(gain);gain.connect(ctxAudio.destination);o.start(t);o.stop(t+d+.02);oscs.add(o);voices++;o.onended=()=>{oscs.delete(o);voices--;o.disconnect();gain.disconnect();};}
function silence(){for(const o of oscs){try{o.stop();}catch{}}ctxAudio?.suspend();}
function tune(e){if(e.type==='grab'){note(180,.15,0,'triangle',.04,550);note(400+Math.min(e.combo,8)*55,.13,.07);}if(e.type==='fruit')[659,880,1047].forEach((f,i)=>note(f,.18,i*.06));if(e.type==='bonk'||e.type==='fall')note(280,.24,0,'triangle',.06,80);if(e.type==='crumble')note(90,.13,0,'sawtooth',.025);if(e.type==='checkpoint'){note(523,.15);note(784,.2,.1);}if(e.type==='won')[523,659,784,1047].forEach((f,i)=>note(f,.3,i*.1));}
function clear(){pointer=null;game.cancel();}
function say(s){$('toast').textContent=s;toast=1.05;$('toast').style.opacity=1;}
function burst(x,y,col,n=14){fx.push({kind:'ring',x,y,life:.45,max:.45,col});for(let i=0;i<n;i++)fx.push({kind:'bit',x,y:y-6,vx:Math.sin(i*2.399)*90,vy:-35+Math.cos(i*2.399)*80,spin:i%2?4:-3,life:.7,max:.7,col:i%3?col:'#fff1c1'});if(fx.length>100)fx.splice(0,fx.length-100);}
function consume(){for(const e of game.events.splice(0)){tune(e);if(e.type==='grab'){const r=game.ring(game.anchor);burst(r.x,r.y,'#c0d9b6',8);if(e.combo>2&&e.fresh)say('GRIP ×'+e.combo);}if(e.type==='fruit'){say('LITTLE STAR!');burst(e.x,e.y,'#f5ce7c',24);}if(e.type==='checkpoint')say('SAFE & SOUND');if(e.type==='bonk'){say('BOOP!');burst(e.x,e.y,'#e2a994',12);}if(e.type==='crumble'){say('CRUMBS!');burst(e.x,e.y,'#d6ae87',12);}if(e.type==='fall'){clear();say('I GOT YOU!');}if(e.type==='return')burst(e.x,e.y,'#c7d5ac',16);if(e.type==='won'){burst(game.x,game.y,'#f2c77d',40);profile.stars[game.n]=Math.max(profile.stars[game.n],game.stars);const old=profile.records[game.n];profile.records[game.n]=old?Math.min(old,game.grabs):game.grabs;paused=true;clear();save();open('won');}}}
function reset(n){game=new Hug.Run(n);window.game=game;view.cam=game.y-view.h*.68/view.s;paused=false;fx=[];acc=0;clear();$('overlay').classList.add('off');menu='';audio();save();update();}
function resume(){if(game.state==='won')return reset(game.n);clear();paused=false;acc=0;menu='';$('overlay').classList.add('off');audio();update();}
function open(kind){paused=true;clear();if(kind!=='won')silence();menu=kind;save();$('overlay').classList.remove('off');let html='';
if(kind==='intro')html='<div class="eyebrow">LONG ARMS. LITTLE COURAGE.</div><div class="mascot"></div><h1>Hug the Sky</h1><p>Drag toward a ring. Release to grab.<br>Find three stars. Give your friend a hug.</p><button data-act="resume">Reach out</button><button class="alt" data-act="book">Travel book</button>';
if(kind==='pause')html='<div class="eyebrow">HANG IN THERE</div><h1>Take a breath.</h1><p>'+game.map.name+'<br>Your little arms can rest.</p><button data-act="resume">Keep climbing</button><button class="alt" data-act="book">Travel book</button><button class="alt" data-act="restart">Restart</button>';
if(kind==='won')html='<div class="eyebrow">A HAND FOR A FRIEND</div><h1>A big little hug.</h1><div class="stars">'+'★'.repeat(game.stars)+'☆'.repeat(3-game.stars)+'</div><div class="stamp">'+game.map.name.toUpperCase()+'<br>'+game.tokens.length+'/3 STAR FRUITS · '+game.grabs+' GRABS<br>'+game.falls+' FALLS · '+game.bonks+' BOOPS</div><p>'+(game.stars===3?'Warm arms. Full heart. A perfect little escape.':game.tokens.length<3?'Golden rings hide little stars along the way.':'A gentle climb earns one more star.')+'</p><button data-act="next">'+(game.n<7?'Next escape':'Travel book')+'</button><button class="alt" data-act="restart">Again</button><button class="alt" data-act="photo">Postcard</button>';
if(kind==='book'){html='<div class="eyebrow">THE LONG WAY HOME</div><h1>Eight little skies.</h1><div class="stamp">'+total()+' / 24 STARS</div><div class="grid">';for(let i=0;i<8;i++)html+='<button data-level="'+i+'" '+(i&&!profile.stars[i-1]?'disabled':'')+'>'+String(i+1).padStart(2,'0')+'<small>'+'★'.repeat(profile.stars[i])+'·'.repeat(3-profile.stars[i])+'</small></button>';html+='</div><div class="skins">';['Biscuit','Clover','Crown'].forEach((s,i)=>html+='<button class="alt" data-skin="'+i+'" '+(total()<threshold[i]?'disabled':'')+' style="border:2px solid '+(profile.skin===i?'#779f89':'transparent')+'">'+s+'<br><small>'+threshold[i]+' ★</small></button>');html+='</div><button data-act="resume">Back to the sky</button><p style="margin-bottom:0;font-size:10px">Stars: rescue · three fruits · no falls & ≤2 boops</p>';}
$('panel').innerHTML=html;update();}
function photo(){try{const a=document.createElement('a');a.download='hug-the-sky-'+(game.n+1)+'.png';a.href=$('canvas').querySelector('canvas').toDataURL('image/png');a.click();if(!menu)say('POSTCARD SAVED');}catch{say('POSTCARD UNAVAILABLE');}}
$('panel').addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;audio();if(b.dataset.level!==undefined)return reset(Number(b.dataset.level));if(b.dataset.skin!==undefined){profile.skin=Number(b.dataset.skin);save();return open('book');}const a=b.dataset.act;if(a==='resume')resume();if(a==='book')open('book');if(a==='restart')reset(game.n);if(a==='next'){if(game.n<7)reset(game.n+1);else open('book');}if(a==='photo')photo();});$('book').onclick=()=>open('book');$('pause').onclick=()=>{if(paused&&menu==='pause')resume();else open('pause');};$('photo').onclick=photo;$('sound').onclick=()=>{profile.sound=!profile.sound;if(profile.sound)audio();else silence();save();update();};$('drop').onclick=()=>{if(!paused){clear();audio();game.drop();consume();save();}};
function update(){$('subtitle').textContent=game.map.name.toUpperCase();$('level').textContent=String(game.n+1).padStart(2,'0')+' / 08';$('tokens').textContent='★ '.repeat(game.tokens.length)+'☆ '.repeat(3-game.tokens.length);$('chain').textContent='↗ '+Math.round(Math.max(0,Math.min(100,(1420-game.y+74)/1089*100)))+'%';$('status').textContent=game.anchor<0?'↘ REACH FOR A RING':game.map.rings[game.anchor].type==='crumb'?'◌ THIS ONE CRUMBLES':'✦ A HAND FOR A FRIEND';$('sound').textContent=profile.sound?'♫':'♪';$('sound').setAttribute('aria-pressed',String(profile.sound));$('hint').textContent=game.t<12?'Drag to a ring · Release to grab':'';}
function point(e){const r=$('canvas').getBoundingClientRect();game.point((e.clientX-r.left-view.w/2)/view.s+250,(e.clientY-r.top)/view.s+view.cam);}
$('canvas').addEventListener('pointerdown',e=>{if(paused||pointer!==null)return;e.preventDefault();pointer=e.pointerId;$('canvas').setPointerCapture(pointer);audio();point(e);});$('canvas').addEventListener('pointermove',e=>{if(e.pointerId===pointer&&!paused){e.preventDefault();point(e);}});$('canvas').addEventListener('pointerup',e=>{if(e.pointerId!==pointer)return;e.preventDefault();point(e);pointer=null;const aimed=game.aim;if(!game.release()&&aimed){say("TRY A CLOSER RING");burst(aimed.x,aimed.y,"#ddc6a4",3);}consume();save();});function cancel(e){if(e.pointerId===pointer){clear();save();}}$('canvas').addEventListener('pointercancel',cancel);$('canvas').addEventListener('lostpointercapture',cancel);
function keyboardAim(dir){const arr=game.map.rings.map(r=>game.ring(r.id)).filter(r=>r.id!==game.anchor&&Math.hypot(r.x-game.x,r.y-game.y)<=242);arr.sort((a,b)=>dir==='ArrowLeft'?a.x-b.x:dir==='ArrowRight'?b.x-a.x:dir==='ArrowDown'?b.y-a.y:a.y-b.y);if(arr[0])game.point(arr[0].x,arr[0].y);}
document.addEventListener('keydown',e=>{if(e.code.startsWith('Arrow')){e.preventDefault();if(!paused)keyboardAim(e.code);}if(e.code==='Space'){e.preventDefault();if(!paused&&!e.repeat){audio();if(!game.aim)keyboardAim('ArrowUp');game.release();consume();save();}}if(e.code==='Escape'){if(paused&&menu==='pause')resume();else open('pause');}});function suspend(){if(!paused&&game.state==='playing')open('pause');clear();silence();}window.addEventListener('blur',suspend);document.addEventListener('visibilitychange',()=>{if(document.hidden)suspend();});window.addEventListener('pagehide',save);
new p5(p=>{p.setup=()=>{const box=$('canvas');p.pixelDensity(Math.min(devicePixelRatio||1,1.5));p.createCanvas(box.clientWidth,box.clientHeight).parent(box);p.frameRate(60);resize();open(game.state==='won'?'won':'intro');};function resize(){const box=$('canvas');p.resizeCanvas(box.clientWidth,box.clientHeight);view.w=box.clientWidth;view.h=box.clientHeight;view.s=Math.min(1.4,view.w/500,view.h/440);view.cam=game.y-view.h*.68/view.s;clear();}p.windowResized=resize;p.draw=()=>{const dt=Math.min(p.deltaTime/1000,.05);if(!paused){acc+=dt;while(acc>=1/60){game.step(1/60);acc-=1/60;consume();if(paused){acc=0;break;}}for(const f of fx){f.life-=dt;if(f.kind==='bit'){f.x+=f.vx*dt;f.y+=f.vy*dt;f.vy+=160*dt;}}fx=fx.filter(f=>f.life>0);toast-=dt;$('toast').style.opacity=toast>0?1:0;saveTime+=dt;if(saveTime>1){save();saveTime=0;}update();}view.cam=game.y-view.h*.68/view.s;HugArt.draw(p.drawingContext,view,game,fx,game.t,profile.skin);};});


