(()=>{'use strict';
const $=s=>document.querySelector(s),app=$('#app'),canvas=$('#stage'),music=$('#music'),fx=$('#spark'),c=fx.getContext('2d');
const initialPanel=$('#panel').innerHTML;let renderer,scene,camera,mixer,clips=[],keyLight,rimLight,chartData,ready=false,phase='loading',difficulty=0,round=1,notes=[],score=0,combo=0,maxCombo=0,earned=0,judged=0,energy=0,feverUntil=0,pausedPhase='',last=performance.now(),previewTime=0,countToken=0,particles=[],pressed=new Set(),held=new Map(),look=Number(localStorage.getItem('afuru-look')||0),stars=Number(localStorage.getItem('afuru-stars')||0),best=Number(localStorage.getItem('afuru-best')||0),lowFPS=0;
const COLORS=['#f0b2d5','#a7b5ed','#8edbd0'],LOOKS=[['Petal',0xffd7e9,0xe7d3ff],['Moon',0xc8d6ff,0xaca5ff],['Aurora',0xbcfff0,0xe5acff]];
const travel=1.9,judgmentWindow=.19;let duration=30.929;
function init3D(){renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,innerWidth<700?1.35:1.75));renderer.outputEncoding=THREE.sRGBEncoding;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.9;scene=new THREE.Scene();scene.background=new THREE.Color(0xb7b4d0);scene.add(new THREE.HemisphereLight(0xf3edff,0x716480,.92));keyLight=new THREE.DirectionalLight(0xffe6ed,.72);keyLight.position.set(2,4,4);scene.add(keyLight);rimLight=new THREE.DirectionalLight(0xd3c3ff,.4);rimLight.position.set(-3,2,-3);scene.add(rimLight);camera=new THREE.PerspectiveCamera(35,1,.04,100);resize();window.addEventListener('resize',resize);canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();pauseGame();$('#panel p').textContent='The graphics context was interrupted. Reload to restore the stage.'})}
function resize(){if(!renderer)return;const w=app.clientWidth,h=app.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.position.set(0,1.15,camera.aspect<.65?4.3:3.5);camera.lookAt(0,camera.aspect<.65?.5:.72,0);camera.updateProjectionMatrix();const d=Math.min(devicePixelRatio||1,1.5);fx.width=Math.round(w*d);fx.height=Math.round(h*d);c.setTransform(d,0,0,d,0,0)}
async function load(){try{init3D();chartData=await fetch('chart.json').then(r=>{if(!r.ok)throw Error('Rhythm chart unavailable');return r.json()});duration=chartData.duration;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),100000);const response=await fetch('afuru-mobile.glb',{signal:controller.signal});if(!response.ok)throw Error('Model download failed ('+response.status+')');const total=Number(response.headers.get('content-length'))||31317724,reader=response.body.getReader(),chunks=[];let received=0;while(true){const {done,value}=await reader.read();if(done)break;chunks.push(value);received+=value.length;const p=Math.min(96,received/total*96);$('#loadbar').style.width=p+'%';$('#loadtext').textContent='Loading your model · '+Math.min(100,Math.round(received/total*100))+'%'}clearTimeout(timer);$('#loadtext').textContent='Preparing dance and materials…';const bytes=new Uint8Array(received);let offset=0;for(const a of chunks){bytes.set(a,offset);offset+=a.length}const g=await new Promise((resolve,reject)=>new THREE.GLTFLoader().parse(bytes.buffer,'',resolve,reject));scene.add(g.scene);g.scene.traverse(o=>{if(o.isMesh){o.frustumCulled=false;const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{m.roughness=Math.max(.55,m.roughness||0);m.metalness=Math.min(.28,m.metalness||0)})}});mixer=new THREE.AnimationMixer(g.scene);clips=g.animations;clips.forEach(a=>mixer.clipAction(a).play());mixer.setTime(0);ready=true;phase='home';$('#loadbar').style.width='100%';$('#loadtext').textContent='Original model + video soundtrack · Ready';$('#start').disabled=false;$('#start').textContent='PLAY THE RHYTHM';$('#watch').disabled=false;updateHUD();applyLook();window.__afuru.loaded=true; }catch(e){phase='error';$('#loadtext').textContent=e.name==='AbortError'?'Download timed out. Check your connection and retry.':e.message;$('#start').textContent='RETRY LOADING';$('#start').disabled=false;$('#start').onclick=()=>location.reload();window.__afuru.error=String(e)}}
function applyLook(){keyLight?.color.setHex(LOOKS[look][1]);rimLight?.color.setHex(LOOKS[look][2]);$('#looks')?.querySelectorAll('button').forEach((b,i)=>b.classList.toggle('selected',i===look));localStorage.setItem('afuru-look',look)}
function bindHome(){document.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{difficulty=Number(b.dataset.diff);document.querySelectorAll('[data-diff]').forEach(x=>x.classList.toggle('selected',x===b))});$('#start').onclick=()=>start(false);$('#watch').onclick=()=>start(true);$('#looks').innerHTML=LOOKS.map((v,i)=>`<button title="${v[0]} ${i>0&&stars<i*2?'· earn '+i*2+' stars':''}" aria-label="${v[0]} lighting" style="--color:${COLORS[i]}" data-look="${i}" ${stars<i*2?'disabled':''}></button>`).join('');$('#looks').querySelectorAll('button').forEach(b=>b.onclick=()=>{look=Number(b.dataset.look);applyLook()});applyLook()}
function home(){countToken++;music.pause();music.currentTime=0;phase='home';app.classList.remove('watch','fever');$('#panel').innerHTML=initialPanel;$('#overlay').classList.remove('hidden');$('#notes').innerHTML='';notes=[];$('#judgment').className='';$('#countdown').textContent='';bindHome();$('#start').disabled=!ready;$('#watch').disabled=!ready;$('#start').textContent=ready?'PLAY THE RHYTHM':'SETTING THE STAGE…';$('#loadbar').style.width=ready?'100%':'0';$('#loadtext').textContent=ready?'Original model + video soundtrack · Ready':'Loading your model · 31 MB'}
function rng(seed){return()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}}
function makeNotes(){const random=rng(103+difficulty*127+round*233),source=[];if(difficulty<2){for(const [t,strength] of chartData.onsets){if(difficulty===0&&strength<.25)continue;if(source.length&&t-source.at(-1)<(difficulty===0?.36:.24))continue;source.push(t)}}else{const beat=60/chartData.bpm;for(let t=chartData.offset;t<duration-.9;t+=beat/2)if(t>1.4)source.push(t)}let previous=-1,laneEnd=[0,0,0];notes=source.map((t,i)=>{let lane=Math.floor(random()*3);if(lane===previous)lane=(lane+1)%3;for(let k=0;k<3&&laneEnd[lane]>t-.15;k++)lane=(lane+1)%3;const hold=i>3&&i%9===5?.5+(difficulty*.12):0;laneEnd[lane]=t+hold;previous=lane;const el=document.createElement('div');el.className='note'+(hold?' hold':'');el.dataset.lane=lane;el.style.setProperty('--lane',lane);el.style.display='none';$('#notes').appendChild(el);return{time:t,lane,hold,el,done:false,started:false,holdDone:false}})}
async function start(watch){if(!ready||phase==='countdown')return;try{music.currentTime=0;await music.play();music.pause();music.currentTime=0}catch{showJudgment('TAP TO ENABLE SOUND','#ffd4dd');return}const token=++countToken;phase='countdown';score=combo=maxCombo=earned=judged=energy=feverUntil=0;pressed.clear();held.clear();particles=[];$('#notes').innerHTML='';app.classList.toggle('watch',watch);app.classList.remove('fever');$('#overlay').classList.add('hidden');if(!watch)makeNotes();else notes=[];updateHUD();for(let n=3;n>0;n--){if(token!==countToken)return;$('#countdown').textContent=n;await new Promise(r=>setTimeout(r,650))}if(token!==countToken)return;$('#countdown').textContent='';phase=watch?'watch':'play';music.currentTime=0;try{await music.play()}catch{pauseGame()}mixer.setTime(0)}
function updateHUD(){$('#score').textContent=String(score).padStart(6,'0');$('#combo').textContent=combo;$('#best').textContent='BEST '+best;$('#difficultyLabel').textContent=['SOFT','FLOW','SPARK'][difficulty]+' · ROUND '+round;$('#energy').style.width=Math.min(100,energy)+'%'}
function showJudgment(text,color){const el=$('#judgment');el.textContent=text;el.style.color=color;el.className='';void el.offsetWidth;el.className='on'}
function burst(lane,color,n=14){const buttons=document.querySelectorAll('[data-pad]'),r=buttons[lane].getBoundingClientRect(),a=app.getBoundingClientRect(),x=r.left-a.left+r.width/2,y=r.top-a.top;for(let i=0;i<n;i++){const angle=Math.random()*Math.PI*2,speed=35+Math.random()*150;particles.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed-80,life:.45+Math.random()*.35,max:.8,color,size:2+Math.random()*4})}}
function miss(n){n.done=true;n.el.remove();combo=0;energy=Math.max(0,energy-12);judged++;showJudgment('MISS','#e9b0b7');updateHUD()}
function hit(lane){if(phase!=='play')return;const now=music.currentTime,n=notes.filter(n=>!n.done&&!n.started&&n.lane===lane&&Math.abs(n.time-now)<judgmentWindow).sort((a,b)=>Math.abs(a.time-now)-Math.abs(b.time-now))[0];if(!n){return}const delta=Math.abs(n.time-now),perfect=delta<.07,great=delta<.13,weight=perfect?1:great?.78:.5;n.started=true;combo++;maxCombo=Math.max(maxCombo,combo);earned+=weight;judged++;score+=Math.round((perfect?1000:great?750:450)*(music.currentTime<feverUntil?1.5:1));energy=Math.min(100,energy+(perfect?9:5));showJudgment(perfect?'PERFECT':great?'GREAT':'GOOD',COLORS[lane]);burst(lane,COLORS[lane],perfect?20:12);navigator.vibrate?.(perfect?12:5);if(n.hold){held.set(lane,n);n.el.classList.add('held')}else{n.done=true;n.el.remove()}if(energy>=100&&music.currentTime>=feverUntil){feverUntil=music.currentTime+7;energy=0;app.classList.add('fever');showJudgment('BLOOM FEVER','#ffefb9');for(let l=0;l<3;l++)burst(l,'#fff0cc',22);$('#flash').animate([{opacity:.25},{opacity:0}],{duration:450})}updateHUD()}
function release(lane){pressed.delete(lane);document.querySelector(`[data-pad="${lane}"]`).classList.remove('down');const n=held.get(lane);if(n){if(music.currentTime<n.time+n.hold-.12&&phase==='play'){combo=0;energy=Math.max(0,energy-8);earned=Math.max(0,earned-.3);showJudgment('HOLD THE TRAIL','#d8c0df')}else if(phase==='play'){score+=400;showJudgment('HELD',COLORS[lane]);burst(lane,COLORS[lane],10)}n.done=true;n.el.remove();held.delete(lane);updateHUD()}}
function press(lane){if(pressed.has(lane))return;pressed.add(lane);document.querySelector(`[data-pad="${lane}"]`).classList.add('down');hit(lane)}
document.querySelectorAll('[data-pad]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);press(Number(b.dataset.pad))});b.addEventListener('pointerup',()=>release(Number(b.dataset.pad)));b.addEventListener('pointercancel',()=>release(Number(b.dataset.pad)))});
const keys={d:0,f:1,j:2};window.addEventListener('keydown',e=>{if(e.key.toLowerCase() in keys&&!e.repeat){e.preventDefault();press(keys[e.key.toLowerCase()])}if(e.code==='Space'){e.preventDefault();pauseGame()}});window.addEventListener('keyup',e=>{if(e.key.toLowerCase() in keys)release(keys[e.key.toLowerCase()])});
function pauseGame(){if(phase!=='play'&&phase!=='watch')return;pausedPhase=phase;phase='paused';music.pause();for(const l of [...pressed])release(l);$('#panel').innerHTML='<small class="eyebrow">TAKE A BREATH</small><h1>PAUSED</h1><button id="resume" class="primary">RESUME</button><button id="restart" class="secondary">RESTART THE SONG</button><button id="back" class="secondary">BACK TO STAGE</button>';$('#overlay').classList.remove('hidden');$('#resume').onclick=async()=>{try{await music.play();phase=pausedPhase;$('#overlay').classList.add('hidden')}catch{}};$('#restart').onclick=()=>start(pausedPhase==='watch');$('#back').onclick=home}
$('#pause').onclick=pauseGame;document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseGame()});
function results(){if(phase!=='play'&&phase!=='watch')return;if(phase==='watch'){home();return}phase='results';music.pause();notes.forEach(n=>{if(!n.started&&!n.done)miss(n)});for(const [l,n] of held){n.el.remove();held.delete(l)}const accuracy=notes.length?earned/notes.length:0,rank=accuracy>=.95?'S+':accuracy>=.85?'S':accuracy>=.72?'A':accuracy>=.55?'B':'C',gain=accuracy>=.85?3:accuracy>=.65?2:accuracy>=.4?1:0,old=stars;stars+=gain;best=Math.max(best,score);localStorage.setItem('afuru-stars',stars);localStorage.setItem('afuru-best',best);app.classList.remove('fever');const unlock=old<2&&stars>=2?'MOON LIGHTING UNLOCKED':old<4&&stars>=4?'AURORA LIGHTING UNLOCKED':gain?'+'+gain+' STARS · '+stars+' TOTAL':'A NEW ATTEMPT AWAITS';$('#panel').innerHTML=`<small class="eyebrow">PERFORMANCE COMPLETE</small><div class="rank">${rank}</div><div class="resultStats"><div><b>${score}</b><small>SCORE</small></div><div><b>${Math.round(accuracy*100)}%</b><small>ACCURACY</small></div><div><b>${maxCombo}</b><small>BEST COMBO</small></div></div><p class="unlock">${unlock}</p><button id="next" class="primary">NEXT MIX · ROUND ${round+1}</button><button id="again" class="secondary">REPLAY THIS MIX</button><button id="back" class="secondary">BACK TO STAGE</button>`;$('#overlay').classList.remove('hidden');$('#next').onclick=()=>{round++;start(false)};$('#again').onclick=()=>start(false);$('#back').onclick=home;updateHUD()}
music.addEventListener('ended',results);music.addEventListener('loadedmetadata',()=>{if(Number.isFinite(music.duration))duration=music.duration});
function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;const t=music.currentTime;let animTime;if(phase==='play'||phase==='watch'||phase==='paused'||phase==='results')animTime=t;else if(phase==='countdown')animTime=0;else{previewTime+=dt;animTime=previewTime%30.03}if(mixer){mixer.setTime((animTime/duration*30.0333)%30.0333);const bloom=t<feverUntil&&phase==='play';keyLight.intensity=.72+(bloom?Math.sin(now*.012)*.22+.3:0);rimLight.intensity=.4+(bloom?.55:0);renderer.render(scene,camera);if(dt>.043&&phase==='play')lowFPS++;if(lowFPS>90&&renderer.getPixelRatio()>1){renderer.setPixelRatio(1);resize();lowFPS=0}}
if(phase==='play'){const track=$('#rhythm'),height=track.clientHeight-12;for(const n of notes){if(n.done)continue;const remaining=n.time-t;if(n.started){if(n.hold&&t>=n.time+n.hold-.03){score+=400;n.done=true;n.el.remove();held.delete(n.lane);burst(n.lane,COLORS[n.lane],8);updateHUD()}else{n.el.style.display='block';n.el.style.setProperty('--y',height+'px');n.el.style.setProperty('--tail',Math.max(0,n.time+n.hold-t)/travel*height+'px')}continue}if(remaining<-.23){miss(n);continue}if(remaining<travel){n.el.style.display='block';n.el.style.setProperty('--y',(height*(1-remaining/travel))+'px');n.el.style.setProperty('--tail',(n.hold/travel*height)+'px')}}if(t>=feverUntil)app.classList.remove('fever');$('#progress').style.width=t/duration*100+'%';$('#time').textContent='00:'+String(Math.floor(t)).padStart(2,'0')+' / 00:'+Math.ceil(duration)}if(phase==='watch')$('#progress').style.width=t/duration*100+'%';c.clearRect(0,0,app.clientWidth,app.clientHeight);for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=150*dt;c.globalAlpha=Math.max(0,p.life/p.max);c.fillStyle=p.color;c.beginPath();c.ellipse(p.x,p.y,p.size,p.size*.5,now*.002,0,Math.PI*2);c.fill()}c.globalAlpha=1;particles=particles.filter(p=>p.life>0);requestAnimationFrame(loop)}
window.__afuru={loaded:false,get:()=>({phase,score,combo,notes:notes.length,difficulty,round,stars,time:music.currentTime,drawCalls:renderer?.info.render.calls}),chart:()=>notes.map(n=>({time:n.time,lane:n.lane,hold:n.hold})),tap:hit};bindHome();load();requestAnimationFrame(loop);
})();

