'use strict';
const $=id=>document.getElementById(id),KEY='nimbus-nonsense-v1';let profile={stars:Array(8).fill(0),scores:Array(8).fill(0),skin:0,sound:true,save:null},game,paused=true,pointer=null,menu='intro',clock=0,acc=0,saveClock=0,fx=[],flash=0,toast=0,view={w:390,h:700,sx:.75,sy:1,s:.75,ox:14,oy:40},ctxAudio,rainGain,rainSource,voices=0;
try{const d=JSON.parse(localStorage.getItem(KEY));if(d&&Array.isArray(d.stars)&&d.stars.length===8&&d.stars.every(v=>Number.isInteger(v)&&v>=0&&v<=3)){profile={...profile,...d};profile.scores=Array.from({length:8},(_,i)=>Number.isFinite(d.scores?.[i])?Math.max(0,d.scores[i]):0);profile.skin=[0,1,2].includes(d.skin)?d.skin:0;}}catch{}
const oscillators=new Set();const total=()=>profile.stars.reduce((a,b)=>a+b,0),unlocks=[0,6,15];if(total()<unlocks[profile.skin])profile.skin=0;game=Nimbus.Run.restore(profile.save)||new Nimbus.Run(0);window.game=game;
function save(){profile.save=game.snapshot();try{localStorage.setItem(KEY,JSON.stringify(profile));}catch{}}
function audio(){if(!profile.sound)return;try{if(!ctxAudio){ctxAudio=new(window.AudioContext||window.webkitAudioContext)();const buf=ctxAudio.createBuffer(1,ctxAudio.sampleRate,ctxAudio.sampleRate),data=buf.getChannelData(0);let v=0;for(let i=0;i<data.length;i++){v=(v+Math.random()*.04-.02)*.96;data[i]=v;}rainSource=ctxAudio.createBufferSource();rainSource.buffer=buf;rainSource.loop=true;rainGain=ctxAudio.createGain();rainGain.gain.value=0;rainSource.connect(rainGain);rainGain.connect(ctxAudio.destination);rainSource.start();}ctxAudio.resume();}catch{}}
function note(f,d=.16,delay=0,type='sine',vol=.035,end){if(!profile.sound||!ctxAudio||ctxAudio.state!=='running'||voices>=14)return;const o=ctxAudio.createOscillator(),gain=ctxAudio.createGain(),t=ctxAudio.currentTime+delay;o.type=type;o.frequency.setValueAtTime(f,t);if(end)o.frequency.exponentialRampToValueAtTime(end,t+d);gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(vol,t+.012);gain.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(gain);gain.connect(ctxAudio.destination);o.start(t);o.stop(t+d+.02);voices++;oscillators.add(o);o.onended=()=>{voices--;oscillators.delete(o);o.disconnect();gain.disconnect();};}
function hush(){if(rainGain&&ctxAudio){rainGain.gain.cancelScheduledValues(ctxAudio.currentTime);rainGain.gain.setValueAtTime(0,ctxAudio.currentTime);}}
function silence(){hush();for(const o of oscillators){try{o.stop();}catch{}}ctxAudio?.suspend();}function tune(e){if(e.type==='thunder'){note(70,.55,0,'sawtooth',.025,30);note(110,.35,.05,'triangle',.08,40);}if(e.type==='done'){if(e.kind==='duck'){note(340,.12,0,'square',.015,220);note(360,.14,.15,'square',.015,200);}else if(e.kind==='person'){note(190,.13,0,'triangle',.07,80);note(320,.18,.08,'triangle',.04,140);}else if(e.kind==='balloon'){note(700,.1,0,'triangle',.045,90);}else [523,659,784].forEach((n,i)=>note(n*Math.pow(1.06,Math.min(e.chain,6)),.15,i*.045));}if(e.type==='won')[523,659,784,1047].forEach((n,i)=>note(n,.35,i*.12));}
function clearInput(){pointer=null;game.stop();keys.clear();hush();}
function say(s){$('toast').textContent=s;toast=1.3;$('toast').style.opacity=1;}
function burst(e){const col=e.kind==='duck'?'#f5d687':e.kind==='balloon'?'#eab4bc':e.kind==='person'?'#a6d6d5':'#e4db9f';fx.push({kind:'ring',x:e.x,y:e.y,max:.65,life:.65,col});fx.push({kind:'word',x:e.x,y:e.y-30,vy:-16,text:e.kind==='duck'?'QUACK!':e.chain>1?'×'+e.chain:'+120',max:1,life:1,col:'#fff9d5'});for(let i=0;i<18;i++)fx.push({kind:'bit',x:e.x,y:e.y-10,vx:Math.sin(i*2.399)*(25+i*3),vy:-50+Math.cos(i*2.399)*60,max:.8,life:.8,col:i%2?col:'#fff0c0',spin:i%2?4:-3});if(fx.length>120)fx.splice(0,fx.length-120);}
function consume(){for(const e of game.events.splice(0)){tune(e);if(e.type==='thunder'){flash=.45;fx.push({kind:'ring',x:e.x,y:e.y,max:.7,life:.7,col:'#ffedac'});say('BOOM!');}if(e.type==='done'){burst(e);if(e.kind==='duck')say('DUCK DISCOVERED!');else if(e.chain>=3)say('SPLASH CHAIN ×'+e.chain);else if(e.kind==='person')say('OH, DRIZZLE!');else if(e.kind==='cake')say('CAKE: SOUP.');else if(e.kind==='balloon')say('POP!');}if(e.type==='blocked')say('ϟ FLIP THAT UMBRELLA');if(e.type==='won'){profile.stars[game.n]=Math.max(profile.stars[game.n],game.stars);profile.scores[game.n]=Math.max(profile.scores[game.n],game.score);clearInput();paused=true;save();open('won');}}}
function reset(n){game=new Nimbus.Run(n);window.game=game;game.start();paused=false;acc=0;fx=[];flash=0;clearInput();$('overlay').classList.add('off');menu='';audio();save();update();}
function resume(){if(game.state==='won')return reset(game.n);clearInput();game.start();paused=false;$('overlay').classList.add('off');menu='';audio();update();}
function open(kind){paused=true;clearInput();hush();menu=kind;if(kind!=='won')silence();save();$('overlay').classList.remove('off');let html='';
 if(kind==='intro')html='<div class="eyebrow">FORECAST: A LITTLE CHAOS</div><div class="hero"><span>ϟ</span></div><h1>Nimbus<br>Nonsense</h1><p>Drag to rain. Make a little mischief.<br>Thunder flips umbrellas & pops balloons.<br>Three little ducks are hiding.</p><button data-act="resume">Make it rain</button><button class="alt" data-act="album">Album</button>';
 if(kind==='pause')html='<div class="eyebrow">A BREAK IN THE WEATHER</div><h1>Cloud nine.</h1><p>'+game.name+'<br>Your puddles are safe.</p><button data-act="resume">Keep drizzling</button><button class="alt" data-act="album">Album</button><button class="alt" data-act="restart">Restart</button>';
 if(kind==='won')html='<div class="eyebrow">A BEAUTIFULLY BAD FORECAST</div><h1>'+game.name+'</h1><div class="stars">'+'★'.repeat(game.stars)+'☆'.repeat(3-game.stars)+'</div><div class="stamp">'+game.ducks+'/3 DUCKS · '+game.score+' POINTS<br>BEST SPLASH CHAIN '+game.bestChain+'</div><p>'+(game.stars===3?'Every duck. Every puddle. Perfect nonsense.':game.ducks<3?'The hidden ducks love a little rain.':'Try three splashes in a quick chain.')+'</p><button data-act="next">'+(game.n<7?'Next neighborhood':'Open album')+'</button><button class="alt" data-act="restart">Again</button><button class="alt" data-act="photo">Postcard</button>';
 if(kind==='album'){html='<div class="eyebrow">YOUR LITTLE WEATHER DIARY</div><h1>Cloud collection.</h1><div class="stamp">'+total()+' / 24 STARS</div><div class="grid">';for(let i=0;i<8;i++)html+='<button data-level="'+i+'" '+(i>0&&!profile.stars[i-1]?'disabled':'')+'>'+String(i+1).padStart(2,'0')+'<small>'+'★'.repeat(profile.stars[i])+'·'.repeat(3-profile.stars[i])+'</small></button>';html+='</div><div class="skins">';['Oat','Blush','Royal'].forEach((s,i)=>html+='<button class="alt" data-skin="'+i+'" '+(total()<unlocks[i]?'disabled':'')+' style="border:2px solid '+(profile.skin===i?'#9ebcae':'transparent')+'">'+s+'<br><small>'+unlocks[i]+' ★</small></button>');html+='</div><button data-act="resume">Back to drizzle</button><p style="margin-bottom:0;font-size:10px">Stars: finish · three ducks · chain of three</p>';}
 $('panel').innerHTML=html;update();}
function photo(){try{const a=document.createElement('a');a.download='nimbus-neighborhood-'+(game.n+1)+'.png';a.href=$('canvas').querySelector('canvas').toDataURL('image/png');a.click();if(!menu)say('POSTCARD SAVED');}catch{say('POSTCARD UNAVAILABLE');}}
$('panel').addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;audio();if(b.dataset.level!==undefined)return reset(Number(b.dataset.level));if(b.dataset.skin!==undefined){profile.skin=Number(b.dataset.skin);save();return open('album');}const a=b.dataset.act;if(a==='resume')resume();if(a==='album')open('album');if(a==='restart')reset(game.n);if(a==='next'){if(game.n<7)reset(game.n+1);else open('album');}if(a==='photo')photo();});
$('book').onclick=()=>open('album');$('pause').onclick=()=>{if(paused&&menu==='pause')resume();else open('pause');};$('photo').onclick=photo;$('thunder').onclick=()=>{if(paused)return;audio();game.thunder();consume();update();save();};$('finish').onclick=()=>{game.finish();consume();};$('sound').onclick=()=>{profile.sound=!profile.sound;if(!profile.sound){silence();}else audio();update();save();};
function update(){$('subtitle').textContent=game.name.toUpperCase();$('level').textContent=String(game.n+1).padStart(2,'0')+' / 08';$('goals').textContent='✓ '+game.goals.filter(o=>o.done).length+' / '+game.goals.length;$('ducks').textContent='◆ '.repeat(game.ducks)+'◇ '.repeat(3-game.ducks);$('status').textContent=game.bestChain>=3?'✦ SPLASH CHAIN '+game.bestChain:game.chain>0?'✦ CHAIN '+game.chain:'☂ A LITTLE MISCHIEF';$('finish').hidden=!game.cleared;document.body.classList.toggle('ready',game.cleared);$('thunder').disabled=paused||game.zapCd>0;$('thunder-label').textContent=game.zapCd>0?Math.ceil(game.zapCd)+'s':'THUNDER';$('sound').textContent=profile.sound?'♫':'♪';$('sound').setAttribute('aria-pressed',String(profile.sound));$('hint').textContent=game.cleared?(game.ducks<3?'Find the ducks, or collect your stars':'Beautifully bad weather. Collect your stars!'):game.t<6?'Hold & drag to rain · ϟ flips umbrellas':'';}
function point(e){const r=$('canvas').getBoundingClientRect();return{x:(e.clientX-r.left-view.ox)/view.sx,y:(e.clientY-r.top-view.oy)/view.sy};}
$('canvas').addEventListener('pointerdown',e=>{if(paused||pointer!==null)return;e.preventDefault();pointer=e.pointerId;$('canvas').setPointerCapture(pointer);audio();const a=point(e);game.rainAt(a.x,a.y);});$('canvas').addEventListener('pointermove',e=>{if(e.pointerId!==pointer)return;e.preventDefault();const a=point(e);game.rainAt(a.x,a.y);});function end(e){if(e.pointerId===pointer){clearInput();save();}}$('canvas').addEventListener('pointerup',end);$('canvas').addEventListener('pointercancel',end);$('canvas').addEventListener('lostpointercapture',end);
const keys=new Set();document.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.code==='Escape'){if(paused&&menu==='pause')resume();else open('pause');}if(paused)return;keys.add(e.code);if(e.code==='KeyT'){audio();game.thunder();consume();}});document.addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='Space')game.stop();});function suspend(){keys.clear();if(!paused&&game.state==='playing')open('pause');clearInput();ctxAudio?.suspend();}window.addEventListener('blur',suspend);document.addEventListener('visibilitychange',()=>{if(document.hidden)suspend();});window.addEventListener('pagehide',save);
new p5(p=>{p.setup=()=>{const box=$('canvas');p.pixelDensity(Math.min(devicePixelRatio||1,1.5));p.createCanvas(box.clientWidth,box.clientHeight).parent(box);p.frameRate(45);resize();open(game.state==='won'?'won':'intro');};function resize(){const box=$('canvas');p.resizeCanvas(box.clientWidth,box.clientHeight);view.w=box.clientWidth;view.h=box.clientHeight;view.sx=(view.w-28)/480;view.sy=Math.min(1.2,(view.h-75)/500);view.s=Math.min(1.05,Math.max(.6,Math.min(view.sx,view.sy)));view.ox=14;view.oy=(view.h-500*view.sy)/2;clearInput();keys.clear();}p.windowResized=resize;p.draw=()=>{const dt=Math.min(p.deltaTime/1000,.05);if(!paused){clock+=dt;if(keys.size&&pointer===null){let x=(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0),y=(keys.has('ArrowDown')||keys.has('KeyS')?1:0)-(keys.has('ArrowUp')||keys.has('KeyW')?1:0);if(x||y){game.target={x:Nimbus.clamp(game.cloud.x+x*300*dt,35,445),y:Nimbus.clamp(game.cloud.y+y*300*dt,70,460)};}if(keys.has('Space')){if(ctxAudio?.state!=='running')audio();game.raining=true;}}acc+=dt;while(acc>=1/60){game.step(1/60);acc-=1/60;consume();if(paused){acc=0;break;}}for(const f of fx){f.life-=dt;if(f.kind!=='ring'){f.x+=(f.vx||0)*dt;f.y+=(f.vy||0)*dt;if(f.kind==='bit')f.vy+=150*dt;}}fx=fx.filter(f=>f.life>0);flash=Math.max(0,flash-dt);toast-=dt;$('toast').style.opacity=toast>0?1:0;if(rainGain&&ctxAudio?.state==='running')rainGain.gain.setTargetAtTime(game.raining&&profile.sound? .22:0,ctxAudio.currentTime,.04);saveClock+=dt;if(saveClock>1){save();saveClock=0;}update();}NimbusArt.draw(p.drawingContext,view,game,fx,clock,profile.skin,flash);};});



