(function(root){'use strict';const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const titles=['Little Haven','Fernwild','Amber Pools','The Old Garden','Moonroot Hollow','The Sleeping Heart','The Endless Grove'];
const gifts=['','DASH DRIVE','TWIN WINGS','NOVA BLOOM','HEART VESSEL','THE GROVE AWAKENS'];
const colors=[['#456e5d','#38564d','#789c70'],['#588673','#2c5751','#79a98b'],['#c4ad76','#826e54','#dfcc8e'],['#628578','#405d58','#98aa86'],['#555d83','#30364e','#8489a4'],['#43776c','#2b514c','#81b39a'],['#647a82','#354d58','#8bafad']];
function obs(room){const arr=[];for(let i=0;i<7;i++){let x=Math.sin(i*13+room)*245,y=Math.cos(i*17+room)*165;if(Math.hypot(x,y)<110)x+=150;arr.push({x,y,r:22+i%3*6})}return room===0?[]:arr}
function fresh(meta={}){return{v:1,room:0,phase:'play',p:{x:-90,y:60,hp:6,max:6,angle:0,shot:0,dash:0,boost:0,shield:0,inv:0,dx:0,dy:0},coins:0,upgrades:{power:0,rate:0,magnet:0},claimed:[true,false,false,false,false,false],cleared:[true,false,false,false,false,false],rooms:{},friends:0,uid:0,time:0,wave:0,meta:{best:Number(meta.best)||0,completions:Number(meta.completions)||0,mute:!!meta.mute},assist:true}}
function area(s){if(!s.rooms[s.room]){const enemies=[],n=s.room===0?0:s.room===5?1:s.room===4?7:s.room*2+2;for(let i=0;i<n;i++){let type=s.room===5?'heart':s.room===4&&i===n-1?'warden':i%3===2?'bud':i%4===3?'scarab':'seed',hp=type==='heart'?720:type==='warden'?110:type==='scarab'?14:8+s.room*2;enemies.push({id:++s.uid,type,x:Math.cos(i*2.399)*220,y:Math.sin(i*2.399)*170,hp,max:hp,timer:1.5+i*.27,angle:0,flash:0,wind:0,cycle:0})}s.rooms[s.room]={enemies,bullets:[],drops:[],crates:[{x:-180,y:-160,hp:4},{x:240,y:165,hp:4},{x:70,y:-185,hp:4}],cleared:s.room===0,shotCount:0}}return s.rooms[s.room]}
function emit(es,type,o={}){es.push({type,...o})}
function travel(s,id,es=[]){if(id<0||id>6||id>Math.min(6,s.friends+1)||s.phase==='lost')return false;if(id===6&&!s.claimed[5])return false;s.room=id;s.p.x=-315;s.p.y=130;s.p.hp=s.p.max;s.p.inv=1;s.p.boost=0;if(id===0){s.p.x=-90;s.p.y=60}if(id===6){s.wave++;s.rooms[6]=trial(s);s.meta.best=Math.max(s.meta.best,s.wave-1)}area(s).bullets=[];emit(es,'travel');return true}
function trial(s){const enemies=[],n=Math.min(28,5+s.wave*2);for(let i=0;i<n;i++){const type=s.wave%4===0&&i===0?'warden':i%3===2?'bud':'seed',hp=(type==='warden'?110:18)+s.wave*8;enemies.push({id:++s.uid,type,x:Math.cos(i*2.399)*240,y:Math.sin(i*2.399)*180,hp,max:hp,timer:2+i*.15,angle:0,flash:0,wind:0,cycle:0})}return{enemies,bullets:[],drops:[],crates:[],cleared:false,shotCount:0}}
function hurt(s,e,n,es){if(e.hp<=0)return;e.hp-=n;e.flash=.12;emit(es,'hit',{x:e.x,y:e.y,n});if(e.hp<=0){emit(es,'break',{x:e.x,y:e.y,big:e.type==='heart'||e.type==='warden'});for(let i=0;i<(e.type==='heart'?20:e.type==='warden'?8:3);i++)area(s).drops.push({id:++s.uid,x:e.x+Math.sin(i*9)*20,y:e.y+Math.cos(i*9)*20,value:1});if(e.type==='heart')area(s).drops.push({id:++s.uid,x:e.x,y:e.y,heart:true,value:0})}}
function dash(s,es=[]){if(s.phase!=='play'||s.p.dash>0||!s.claimed[1])return false;s.p.dash=1.8;s.p.boost=.18;s.p.inv=Math.max(s.p.inv,.32);emit(es,'dash',{x:s.p.x,y:s.p.y});return true}
function nova(s,es=[]){if(s.phase!=='play'||!s.claimed[3]||s.p.shield>0)return false;s.p.shield=6;s.p.inv=Math.max(s.p.inv,.4);let r=area(s);r.bullets=r.bullets.filter(q=>q.ally||dist(q,s.p)>180);for(const e of r.enemies)if(dist(e,s.p)<180)hurt(s,e,18+s.upgrades.power*3,es);emit(es,'nova',{x:s.p.x,y:s.p.y});return true}
function price(s,k){return (s.upgrades[k]+1)*8}
function buy(s,k,es=[]){if(s.room!==0||s.phase!=='play'||!Object.hasOwn(s.upgrades,k)||s.upgrades[k]>=3||s.coins<price(s,k))return false;s.coins-=price(s,k);s.upgrades[k]++;emit(es,'upgrade');return true}
function context(s){const r=area(s);if(s.room===0)return dist(s.p,{x:300,y:0})<90?'GO':dist(s.p,{x:0,y:0})<100?'SHOP':'';if(s.room===6&&r.cleared)return'NEXT WAVE';if(r.cleared&&!s.claimed[s.room]&&dist(s.p,{x:0,y:0})<85)return'RESCUE';if(s.claimed[s.room]&&dist(s.p,{x:370,y:0})<100)return s.room===5?'ENDLESS':'GO';return''}
function interact(s,es=[]){const a=context(s);if(a==='SHOP')return'shop';if(a==='RESCUE'){s.claimed[s.room]=true;s.friends=s.claimed.slice(1).filter(Boolean).length;s.coins+=8;s.p.hp=s.p.max;if(s.room===4){s.p.max=8;s.p.hp=8}if(s.room===5){s.meta.completions++;s.phase='won'}emit(es,'rescue',{gift:gifts[s.room],x:0,y:0});return a}if(a==='NEXT WAVE'){travel(s,6,es);return a}if(a==='GO'||a==='ENDLESS'){travel(s,s.room===0?Math.min(5,s.friends+1):s.room+1,es);return a}return false}
function goal(s){if(s.room===0)return{x:300,y:0,text:'Follow the trail'};const r=area(s);if(s.room===6)return r.cleared?{x:0,y:0,text:'Another wave awaits'}:{x:0,y:0,text:'Wave '+s.wave};if(!r.cleared)return{x:0,y:0,text:'Free the sleeping light'};return s.claimed[s.room]?{x:370,y:0,text:s.room===5?'The endless grove':'Follow the light'}:{x:0,y:0,text:'A friend is waiting'}}
function step(s,input,dt,es=[]){dt=clamp(dt,0,.05);if(s.phase!=='play')return;const p=s.p,r=area(s);s.time+=dt;for(const k of['shot','dash','boost','shield','inv'])p[k]=Math.max(0,p[k]-dt);let dx=input.x||0,dy=input.y||0,len=Math.hypot(dx,dy);if(len>1){dx/=len;dy/=len}if(len>.03){p.dx=dx;p.dy=dy}if(p.boost>0&&len<.03){dx=p.dx||Math.cos(p.angle);dy=p.dy||Math.sin(p.angle)}const speed=p.boost>0?790:185;p.x=clamp(p.x+dx*speed*dt,-400,400);p.y=clamp(p.y+dy*speed*dt,-245,245);for(const o of obs(s.room)){const d=dist(p,o),radius=o.r+13;if(d<radius){const a=Math.atan2(p.y-o.y,p.x-o.x);p.x=o.x+Math.cos(a)*radius;p.y=o.y+Math.sin(a)*radius}}if(input.aim&&Number.isFinite(input.aim.x))p.angle=Math.atan2(input.aim.y-p.y,input.aim.x-p.x);else{const near=r.enemies.filter(e=>e.hp>0).sort((a,b)=>dist(a,p)-dist(b,p))[0]||r.crates.filter(c=>c.hp>0&&dist(c,p)<230).sort((a,b)=>dist(a,p)-dist(b,p))[0];if(near)p.angle=Math.atan2(near.y-p.y,near.x-p.x);else if(len>.03)p.angle=Math.atan2(dy,dx)}
if((r.enemies.some(e=>e.hp>0)||r.crates.some(c=>c.hp>0&&dist(c,p)<230))&&p.shot<=0){p.shot=Math.max(.13,.26-s.upgrades.rate*.035);r.shotCount++;for(const spread of s.claimed[2]?[-.075,0,.075]:[0]){const a=p.angle+spread;r.bullets.push({x:p.x+Math.cos(a)*18,y:p.y+Math.sin(a)*18,dx:Math.cos(a)*540,dy:Math.sin(a)*540,r:5,life:1.4,ally:true,damage:4+s.upgrades.power*2})}emit(es,'shoot',{x:p.x,y:p.y})}
for(const e of r.enemies){if(e.hp<=0)continue;e.flash=Math.max(0,e.flash-dt);e.timer-=dt;e.wind=e.timer<.45?.45-e.timer:0;e.angle=Math.atan2(p.y-e.y,p.x-e.x);if(e.type==='seed'||e.type==='scarab'){const d=dist(e,p);if(d>110){const v=e.type==='scarab'?70:38;e.x+=Math.cos(e.angle)*v*dt;e.y+=Math.sin(e.angle)*v*dt}}else if(e.type==='heart'){e.x=Math.cos(s.time*.4)*40;e.y=Math.sin(s.time*.6)*40}if(e.timer<=0){e.cycle++;let count=e.type==='heart'?e.hp<e.max*.5?16:12:e.type==='warden'?8:e.type==='bud'?5:1;const ring=e.type==='heart'||e.type==='warden';for(let i=0;i<count;i++){const a=ring?e.cycle*.17+i/count*Math.PI*2:e.angle+(i-(count-1)/2)*.19,v=e.type==='scarab'?160:e.type==='heart'?112:92;r.bullets.push({x:e.x+Math.cos(a)*22,y:e.y+Math.sin(a)*22,dx:Math.cos(a)*v,dy:Math.sin(a)*v,r:e.type==='heart'?10:7,ally:false,life:6})}e.timer=e.type==='heart'?1.45:e.type==='warden'?2.5:e.type==='scarab'?2:2.9}}
for(const q of r.bullets){q.x+=q.dx*dt;q.y+=q.dy*dt;q.life-=dt;if(q.ally){const e=r.enemies.find(e=>e.hp>0&&dist(e,q)<(e.type==='heart'?44:e.type==='warden'?28:18)+q.r);if(e){hurt(s,e,q.damage,es);q.life=0}else{const c=r.crates.find(c=>c.hp>0&&dist(c,q)<20);if(c){c.hp-=q.damage;q.life=0;if(c.hp<=0){r.drops.push({id:++s.uid,x:c.x,y:c.y,value:3});emit(es,'break',{x:c.x,y:c.y})}}}}else if(r.enemies.some(e=>e.hp>0)&&p.inv<=0&&dist(p,q)<q.r+10){p.hp--;p.inv=s.assist?1.3:.85;q.life=0;emit(es,'hurt',{x:p.x,y:p.y});if(p.hp<=0){s.phase='lost';emit(es,'lost')}}}r.bullets=r.bullets.filter(q=>q.life>0&&Math.abs(q.x)<460&&Math.abs(q.y)<330);r.enemies=r.enemies.filter(e=>e.hp>0);if(!r.enemies.length&&!r.cleared){r.cleared=true;r.bullets=r.bullets.filter(q=>q.ally);if(s.phase==='lost'){s.phase='play';p.hp=1;p.inv=1}if(s.room<6)s.cleared[s.room]=true;else s.meta.best=Math.max(s.meta.best,s.wave);emit(es,'clear',{x:0,y:0})}
for(let i=r.drops.length-1;i>=0;i--){const c=r.drops[i],d=dist(c,p),magnet=75+s.upgrades.magnet*40;if(d<magnet){if(d>12){c.x+=(p.x-c.x)/d*320*dt;c.y+=(p.y-c.y)/d*320*dt}if(d<20){s.coins+=c.value;if(c.heart)p.hp=Math.min(p.max,p.hp+2);emit(es,'coin',{x:c.x,y:c.y,value:c.value});r.drops.splice(i,1)}}}
}
function retry(s,es=[]){s.phase='play';s.p.hp=s.p.max;s.p.inv=2;s.p.x=-315;s.p.y=130;area(s).bullets=[];emit(es,'retry');return true}
function restore(s){if(!s||s.v!==1||!s.p||!Array.isArray(s.claimed)||s.claimed.length!==6||!s.rooms||!Number.isFinite(s.p.hp)||!Number.isFinite(s.coins))return fresh();return s}
const api={fresh,area,step,dash,nova,buy,price,context,interact,goal,retry,restore,travel,obs,titles,colors,gifts};root.Wing=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
